### ISSUE TITLE
BlocklyStorage broken on "Code" demo

### ISSUE THREAD

**Issue by HALtheWise** [google/blockly#100]
At https://blockly-demo.appspot.com/static/demos/code/index.html , clicking the link icon in the upper right fails to save a link to the current workspace, printing in the console "Uncaught TypeError: a.getTopBlocks @ blockly_compressed.js:976".

Browser: Chrome 42.0.2311.135

![image](https://cloud.githubusercontent.com/assets/1697528/7615821/1b19b522-f96e-11e4-9ec4-47f70a9345c8.png)
![image](https://cloud.githubusercontent.com/assets/1697528/7615806/0dc97b32-f96e-11e4-92bf-ffdf3012dedf.png)

**Comment by NeilFraser** [comment]
Thanks.  Fixed and pushed.
