### ISSUE TITLE
Code demo is not escaping strings before colourizing them

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1002]
May be a security issue, load link then click JS (or another language tab):
https://blockly-demo.appspot.com/static/demos/code/index.html#naf7fr

Originally my fault.  Basically this is what happens every time one uses `innerHTML` no matter how careful one is.  The solution is to stop using `prettyPrintOne` and use `prettyPrint` instead.

Old code:
```
    if (typeof prettyPrintOne == 'function') {
      code = content.textContent;
      code = prettyPrintOne(code, 'js');
      content.innerHTML = code;
  }
```

Suggested code:
```
    if (typeof prettyPrint == 'function') {
      prettyPrint();
  }
```

Old HTML:
```
  <pre id="content_javascript" class="content"></pre>
```

Suggested HTML:
```
  <pre id="content_javascript" class="content prettyprint lang-js"></pre>
```

Likewise for the other languages.  And of course test that it can not only pretty print the code, but change the pretty printed code when the blocks are changed.

**Comment by NeilFraser** [comment]
Also, the alignment of the toolbox and the blocks tab is broken (yet again).  Resizing the window fixes this.  @picklesrus

**Comment by rachel-fenichel** [comment]
@NeilFraser can you move that second one to a new issue and add a screenshot?  I'm not seeing a misalignment on https://blockly-demo.appspot.com/static/demos/code/index.html

**Comment by NeilFraser** [comment]
Yeah, I forgot that I'm the only person in the universe whose copy of Chrome doesn't render that tab right.  Checked a bunch of other people and they all render fine.  Never mind then, it's just me.

**Comment by NeilFraser** [comment]
Fixed.
