### ISSUE TITLE
Split Field.init into Field.initView and Field.initModel

### ISSUE THREAD

**Issue by CoryDCode** [google/blockly#1010]
Currently, fields have one init function, which is called through the SVG flow. Variables currently do model logic in their init (adding variables to the list of variables, for reverse-compatibility.) That means headless versions of blockly don't correctly update their list of variables. I've added an initModel function to Field, so this can be solved manually, but we need to figure out where to call initModel so it gets called correctly in all flows.

**Comment by BeksOmega** [comment]
@CoryDCode Could you provide steps to reproduce the old bad headless initialization (possibly w/ xml)? I'm doing a bit of digging into the field lifecycle and I want to make sure there's no regression. If not that's cool but I wanted to reach out!

Thanks!
Beka

**Comment by rachel-fenichel** [comment]
@BeksOmega Done?

**Comment by BeksOmega** [comment]
Code is done, still possibly needs docs.

**Comment by rachel-fenichel** [comment]
Imo we're in good shape on docs, with the docs per field = the ones for creating a custom field.
