### ISSUE TITLE
Consider combining the bubble canvas and the block canvas

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1016]
After discussion with @NeilFraser, it sounds like the separate canvases are an artifact of early Blockly and not an explicit goal.

Getting rid of the bubble canvas could help simplify layout code and improve dragging performance when bubbles are open.

**Comment by BeksOmega** [comment]
Evaluated this during my design doc on layering, and we can't do this without breaking changes due to backwards compatibility.
