### ISSUE TITLE
Move block animations to a separate file

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1022]
The following functions in block_svg.js should be moved to a new file named block_animations.js:

Blockly.BlockSvg.connectionUiStep_, disposeUiStep_, disconnectUiStep_, disconnectUiStop_, disconnectUiStop_.pid, and disconnectUiStop_.group

**Comment by Razaik25** [comment]
Hi, If this is up for grabs. I would like to work on it.

**Comment by AnmAtAnm** [comment]
Go for it.  We don't have anyone here working on this, yet.

**Comment by rachel-fenichel** [comment]
Remember to make your changes against develop, not master.
