### ISSUE TITLE
Preinstall hook breaks npm/yarn install

### ISSUE THREAD

**Issue by polgfred** [google/blockly#1042]
This preinstall hook attempts to download and run selenium:

https://github.com/google/blockly/commit/f7a206abcb7d02cef3f5065d8612e0ef1a79d418#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R21

This is a huge pain when including blockly as an npm dependency, because npm will try to do this before installing the package. Any other way to accomplish the desired effect?

**Comment by RoboErikG** [comment]
Sorry about that. We're trying to get automated tests working with travis-ci and that was added to support it. We'll figure out how to only include it for testing and not all the time.

**Comment by RoboErikG** [comment]
Should be fixed.
