### ISSUE TITLE
Apostrophe in tooltip in Blockly Factory 

### ISSUE THREAD

**Issue by JakubRuzicka** [google/blockly#1045]
Hello, I found some issue with Blocky Factory. Webpage doesnt work after insert ' to Tooltip. After that can't export blocks and toolbox.
This issue can be solved with adding \ before every '.
Hope i help, have a nice day

**Comment by rachel-fenichel** [comment]
Root cause: unescaped user input here: https://github.com/google/blockly/blob/master/demos/blockfactory/factory_utils.js#L355

**Comment by rachel-fenichel** [comment]
Fixed by #1111
