### ISSUE TITLE
Update standard categories in Dev Tools

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#1046]
The standard toolbox categories are [defined here](https://github.com/google/blockly/blob/develop/demos/blockfactory/standard_categories.js).

They're a bit out of date so we should do a cleanup pass to make sure they're using current versions of all the blocks.

**Comment by Spoorthy1423** [comment]
@RoboErikG  i would like to work on this issue, please assign me

**Comment by BeksOmega** [comment]
We've moved to a new version of the blocks factory so this can be closed.
