### ISSUE TITLE
Preview image in image dropdown does not update whenever currently selected image changes

### ISSUE THREAD

**Issue by chuckhacker** [google/blockly#1047]
Whenever I select a new item in the dropdown, the image in the dropdown is still "stuck" at the very first one.

However, I have confirmed that the data itself has changed -- the resulting program operates as if the correct item was chosen -- only the view remains un-updated/stale.

Any ideas? Thanks a bunch!

![blockly_dropdown_bug](https://cloud.githubusercontent.com/assets/143290/25098992/752be342-235f-11e7-98f9-0654726e66d6.png)

**Comment by rachel-fenichel** [comment]
At first glance this sounds like another mismatch between setText and setValue.

@NeilFraser since this is your new dropdown.

**Comment by rachel-fenichel** [comment]
@chuckhacker I have a hunch!  Are you using alt-text for your images?  I'm guessing you're not.

https://github.com/google/blockly/blob/develop/core/field_dropdown.js#L343

We're calling `setText` with the alt-text of the image.  If that's the same as the previous text (which it would be if you have no alt-texts) `setText` will short-circuit and skip a rerender.

I'll fix this up, but in the meantime you should be able to fix it by adding alt-text, if my hunch is right.

**Comment by rachel-fenichel** [comment]
Fixed by #1321, though that fix doesn't resolve the underlying setText/setValue issues in fields.
