### ISSUE TITLE
Code and comment mismatch in scrollbar.js

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1051]
There is a comment on [line 279 of scrollbar.js](https://github.com/google/blockly/blob/master/core/scrollbar.js#L279) that says:

> Don't define if there is no document object (e.g. node.js).

But the code does no such thing.  Looking back in the history it used to, but it no longer does.  The change apparently happened by accident.

The first change by me moved from an explicit check of this.document to goog.getObjectByName which does the check implicitly:
https://github.com/google/blockly/commit/1fac3112247ab75d08745d31cff8a1d43a81d4cf

The second change by @carlosperate moved from goog.getObjectByName to goog.events.BrowserFeature.  In the process the check for document was lost:
https://github.com/google/blockly/commit/b1d3b019f1398b986d2f2d5d7cc8e716f98da39f

There are two options.  Fix the code to match the comment, or fix the comment to match the code.  I don't see any particular reason why we need to have the property undefined in node.js, so I suggest to keep the code and delete the comment.

**Comment by carlosperate** [comment]
I think the closure library `goog.events.BrowserFeature.TOUCH_ENABLED` does check if document is defined: 
https://github.com/google/closure-library/blob/be0326ba32f47ea74af4fbe8df038e579ec35215/closure/goog/events/browserfeature.js#L77-L83

**Comment by carlosperate** [comment]
Oh wait, I see what you mean now, to have it completely undefined, never mind.

**Comment by rachel-fenichel** [comment]
Let's keep the code and delete the comment.

**Comment by NeilFraser** [comment]
Make it so.

**Comment by rachel-fenichel** [comment]
Fixed by #1084
