### ISSUE TITLE
Dynamic creation of variables names if variable name is already in use ?

### ISSUE THREAD

**Issue by MarkusBordihn** [google/blockly#1061]
Unfortunately the "Create variable" disappears from the variable list, so I wonder if there is any best practice or already ready to use solution for the following.

I have an Block which create different objects with an variable.
The variable name is defined inside the XML, so it could not be easily updated dynamically.
It will be never the case that the same block with the same variable needs to be exists in the workspace.

When the user drop this block to the workspace and there is already one he currently needs to perform the following steps:
* User drop the block
* Open variables and create a new one
* Go back to the drop block and changed the used variable

What I would prefer:
* User drop the block
* If there is already an block with the same variable, rename the variable with "1" or so.

**Comment by rachel-fenichel** [comment]
This is an interesting use case.

Applying your desired behaviour globally would make it really hard to just drag a "set x" block out of the toolbox, so we'll need a specific fix instead.

I think the answer is to use an onChange function on the block, and have the block update itself if it's being added to the workspace and it notices that its variable name already exists.

https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#change_validator

**Comment by MarkusBordihn** [comment]
Thanks @rachel-fenichel make sense and will work in this use case.
