### ISSUE TITLE
missing Blockly.Procedures.NAME_TYPE

### ISSUE THREAD

**Issue by abcdvitamin** [google/blockly#1069]
Hi,
there is a $ prefix in generated php function names, because Blockly.Procedures.NAME_TYPE is undefinied.
I think there is a missing line in core\procedures.js file:
Blockly.Procedures.NAME_TYPE = 'PROCEDURE';
(also there is a missing line in core\variables.js
Blockly.Variables.NAME_TYPE = 'VARIABLE';
)

Regards,
Vitamin

**Comment by rachel-fenichel** [comment]
Thanks for pointing this out.

I moved those constants to core/constants.js a few months ago: https://github.com/google/blockly/commit/4872a6ad7f39321c1d838f253e6df8ffb77c3f0d

I probably missed a spot in the generators.  I'll take a look.
