### ISSUE TITLE
Remove uses of 'goog' in demos

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1072]
From Neil's comment in #1065 

> This change is very fragile. Since the demos don't use Closure (there's no goog.require and a compile step), this only works because a) Somewhere in Blockly goog.string.startswith is used and b) our compiler isn't currently renaming functions.
> 
> It would be much better to use:
> messageKey.indexOf('cat') == 0
> 
> While you are at it, grep the demos for any use of 'goog'. Likewise, the blocks and the generators should be 'goog'-free (other than require/provides). The Block Factory is a known issue (#668).

**Comment by AnmAtAnm** [comment]
Plane uses soy (closure templates) and BlockFactory uses `goog` libraries for color picker and other things. The latter is covered by #1834.

**Comment by rachel-fenichel** [comment]
Neil has mentioned that he wants to get rid of the plane demo (or at least unlink it).

**Comment by NeilFraser** [comment]
The only demo at this point that still uses 'goog' is the Block Factory.  Issue #668 specifically covers that particular problem, so I think we can close this broader issue.
