### ISSUE TITLE
elseifCount_ is NaN for an if-then-else block

### ISSUE THREAD

**Issue by msprotz** [google/blockly#109]
Hi there,

I've noticed a strange weirdness; the properties of an if-then-else block are as follows.
- if then: elseIfCount_ = 0, elseCount_ = 0
- if then / else if / else: elseIfCount_ = 1, elseCount = 1
- if then / else: elseIfCount_ = NaN, elseCount = 1

Is this expected?

Thanks,

Jonathan

**Comment by NeilFraser** [comment]
Fixed.  Thanks!
