### ISSUE TITLE
Move BlockSvg.getHeightWidth into block_render_svg

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1102]
https://github.com/google/blockly/blob/master/core/block_svg.js#L473

**Comment by RoboErikG** [comment]
It is, but Rachel's been working on some major block rendering changes so you might not want to make optional changes in the block_svg or block_render_svg files for now.

**Comment by TiaraIsTan** [comment]
Got it, thanks for the quick response time :)
