### ISSUE TITLE
Can't uncheck "allow statements" in the "functions" category

### ISSUE THREAD

**Issue by AlainBusser** [google/blockly#1103]
I use Blockly with Iceweasel and Chromium; both navigators have a strange behavior when trying to check out "allow statements" in a "to" block: Clicking on the checkbox just selects the whole block and that is all; so it is not possible for me to disallow statements. 

This bug is not very serious as it is still possible to use Blockly. But I remember it did not happen with an ancient version.

![checkbox](https://cloud.githubusercontent.com/assets/3930757/26022841/1f7224fa-37c0-11e7-878e-b33b46647cec.png)

**Comment by AnmAtAnm** [comment]
Fixed in develop branch. See #797, #835

**Comment by rachel-fenichel** [comment]
Fixed very recently, and holy cow was this a pain to fix.
