### ISSUE TITLE
Corrupted Variable fields after new variable via function mutator

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1104]
**`develop` branch only.**

In playground:
1. Add function to workspace.
2. Add a new function argument via the function mutator (default "x")
3. Open Variables category.

Expected variable fields to show "x" as the only option.
Found three variables: broken image, broken image, and "[object Object]"

<img width="779" alt="screen shot 2017-05-13 at 9 27 58 am" src="https://cloud.githubusercontent.com/assets/9916202/26027207/bc474b7c-37be-11e7-8abc-660db4609dae.png">
<img width="653" alt="screen shot 2017-05-13 at 9 29 04 am" src="https://cloud.githubusercontent.com/assets/9916202/26027208/bc49d70c-37be-11e7-9c6d-689f9635f73f.png">

**Comment by rachel-fenichel** [comment]
@marisaleung

**Comment by marisaleung** [comment]
Fixed in #1085.
