### ISSUE TITLE
RFE: Delete variables without creating a new variable field block

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1105]
Currently, variables do not delete themselves, even if there is no reference to them. In part, this is by design, because the creation of a variable occurs before a variable block is added to the workspace (via the toolbox "Create Variable" button).

Currently, the only way to delete such blocks is via create a block with a variable field, select the otherwise unused variable from the drop down, and then open the drop down again to select delete.

My intuitive expectation was the variable would autodelete after the last reference was removed (variable fields or function arguments). However, one would have to be careful this does not delete created variables before they are first used.

Alternatively, an affordance on the toolbox (perhaps only for unused variables).

**Comment by rachel-fenichel** [comment]
We are definitely not autodeleting after the last reference is removed--that was an explicit decision in the new design.

Right now unused variables don't get serialized, I think.  That might change in the future.

Either way it sounds like this is a request for a 'delete variable' button.  It would either:
- let you pick the variable (or possibly variables) from a list, or
- clean up all unreferenced variables in one pass.

**Comment by BeksOmega** [comment]
You can do this now by right clicking on the block in the toolbox.
