### ISSUE TITLE
Fields in auto-closing flyouts are editable

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1109]
Compare behavior on develop vs https://blockly-demo.appspot.com/static/tests/playground.html when doing the following:
1. open the math category
2. click in the number field of the number block.

Expected Behavior:
Block gets placed on the workspace and the flyout auto-closes.

Develop behavior:
You focus on the field and can type into it.

**Comment by marisaleung** [comment]
This bug began with commit https://github.com/google/blockly/commit/98914fcf6b4fd1bcc139bece6a5afd7af8c100ae

When Blockly.Gesture.handleUp() is called, this.isDraggingBlock_ is set to false. this.isDraggingBlock_ should be true.
