### ISSUE TITLE
Should have a method to hide the flyout?

### ISSUE THREAD

**Issue by NAllred91** [google/blockly#1110]
Sometimes it may be necessary to close the flyout when the user clicks on something outside of the blockly workspace.  

For example, if you have a 'Run Code' button you may want that to also trigger hiding the flyout so the user can see the blocks being highlighted.

**Comment by rachel-fenichel** [comment]
[Blockly.hideChaff](https://github.com/google/blockly/blob/master/core/blockly.js#L314) will do what you want, and also hide various other blockly-related things that could be visible.
