### ISSUE TITLE
Replace tests/generator/*.xml with .js files

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1142]
Our generator tests currently try to read XML directly, but this doesn't work in a local file environment (browser security limitation), such as exactly the environment developers are likely to want to use when they are editing and testing the code base.

Thankfully, there is an easy fix.  Since the test code is not distributed with other apps, we can use JavaScript ES6 [raw strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Raw_strings):

```
var testdata = String.raw`
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="unittest_main" x="33" y="140">
    <statement name="DO">
      <block type="procedures_callnoreturn">
        <mutation name="test repeat"></mutation>
        <next>
          <block type="procedures_callnoreturn">
            <mutation name="test repeat_ext"></mutation>
            <next>
              <block type="procedures_callnoreturn">
`
```

Raw strings can use any character except the backtick, and we don't have that in our test files.

```
$ grep \` tests/generators/*.xml
# No results
$
```

As `.js` files, we can import all the testdata via script tags. The only down side is that it is the file is no longer XML, but given that the XML does not need to be escaped, this is pretty trivial to cut and paste if you really need to use a syntax highlighting editor or other XML tool.

The page will need to update how it is reading the target test data in response to the selector.

**Comment by moogacs** [comment]
@AnmAtAnm  is this one still open ?

**Comment by AnmAtAnm** [comment]
I think so, but check with @rachel-fenichel.

**Comment by rachel-fenichel** [comment]
Yes.

**Comment by maribethb** [comment]
We now run the generator tests in a browser and we plan to continue to do so, therefore we don't need to implement this.
