### ISSUE TITLE
Dropdown renders incorrectly when dragged from toolbox into workspace

### ISSUE THREAD

**Issue by Ondross** [google/blockly#1155]
Hi,
I am having a rendering issue when dragging blocks into the workspace. It only occurs with a block that contains a dropdown field, and only if that dropdown block is a child of another block. Attached is an example of the kind of block group that fails.

Strangely, the render bug is different WHILE I'm dragging out of the toolbox. As soon as I let go of the mouse, it snaps to a different rendering bug. In the screenshots, all the blocks are connected to each other, though it doesn't look like it.

While Dragging:
![whiledragging](https://cloud.githubusercontent.com/assets/575508/26811231/46a17ec8-4a25-11e7-9e39-622545c59766.png)
After dragging:
![afterdragging](https://cloud.githubusercontent.com/assets/575508/26811218/3dcbfcba-4a25-11e7-884b-4da89c2e8fd4.png)

It happens regardless of whether the inputs are inline, or whether the block is a shadow block or not. 

Oh, also, the extent of the render bug depends on how far I drag the block from the toolbox. The farther down or right I drag the block, the worse the bug gets in that dimension. I'm guessing there is some calculation that is thrown off by the dropdown field?

Thanks for any help!

**Comment by Ondross** [comment]
Ah, a new development, and perhaps something I should just fix myself: I have an onchange() callback that removes and adds the dropdown. Under certain circumstances. If I don't do that, all is well. So maybe I can forego that change on initialization at least.

Feel free to wont-fix this, or let me know if you are interested in reproducing it and want more info.

**Comment by RoboErikG** [comment]
If you're doing that to change the contents of the dropdown take a look at the [Dynamic Dropdown APIs](https://developers.google.com/blockly/guides/create-custom-blocks/dropdown-menus#dynamic_menu). Another option is to use a mutator since you're modifying the block's structure. Let us know if you're still seeing a bug after trying one of those approaches.

**Comment by rachel-fenichel** [comment]
This is usually a symptom of a call to `render()` while dragging a block.  `render()` sets connection offsets in a way that doesn't work mid-drag.  

Is that what's happening here?
