### ISSUE TITLE
Allow newlines in field labels (multi-line fields)

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1159]
The primary use case is around labels on statement inputs.  JSON will handle \n escapes.

**Comment by YannCaron** [comment]
I'm really interested by this feature :+1: 
It give me opportunity to inject some javascript directly.

**Comment by rachel-fenichel** [comment]
Implemented in Q3 2019 release.

**Comment by rachel-fenichel** [comment]
Never mind, this is for labels, not textinputs.

**Comment by BeksOmega** [comment]
There's now a [field for this](https://github.com/google/blockly/blob/master/core/field_multilineinput.js) :D

**Comment by YannCaron** [comment]
Many thanks @BeksOmega for this good news :-)
