### ISSUE TITLE
Context menu broken for set/get variables

### ISSUE THREAD

**Issue by acbart** [google/blockly#118]
https://github.com/google/blockly/blob/master/blocks/variables.js#L71

This line binds the message string (Blockly.Msg.VARIABLES_GET_CREATE_SET) during the definition of the variables_get block (Blockly.Blocks['variables_get']). However, this value doesn't exist until after the definition, resulting in an undefined value. This leads to an error when it's interpolated in https://github.com/google/blockly/blob/master/blocks/variables.js#L81

**Comment by NeilFraser** [comment]
Good catch.  My fault, I 'simplified' this code and didn't realize the reason for assigning the value during init instead of load time.  Fixed.
