### ISSUE TITLE
generated API docs

### ISSUE THREAD

**Issue by trodi** [google/blockly#119]
Reviewing the source code, it is well documented, however, I don't see any auto generated API docs. What is the preferred method for reviewing the API? Shouldn't a JSDoc type doc be generated along with the build? This would easily allow one to wire up the documentation to view it inline in their IDE or to review in browser etc.

**Comment by ferrao** [comment]
I agree, the available documentation is missing a lot, would be really nice to get some API docs generated with the build.

**Comment by acbart** [comment]
I ran JSDoc on the codebase a while back, this was the result: https://dl.dropboxusercontent.com/u/23141976/blockly-documentation/index.html

Seems like it'd be a pretty-straightforward thing to do.

**Comment by rachel-fenichel** [comment]
Hey there!

Getting this set up is on my to-do list, but so are a lot of bugs.  I'm working on figuring out where these will live.  Big thanks for @acbart for his docs in the meantime.

**Comment by AnmAtAnm** [comment]
Well looky there.... https://developers.google.com/blockly/reference/js/
