### ISSUE TITLE
Flyout scrolling breaks after opening category with a flyout label in it

### ISSUE THREAD

**Issue by microsoftsam** [google/blockly#1195]
Affects develop.

Repro: (in playground.html)
1. Open the Logic category in a small window so the scroll bar shows up
2. Scroll to the bottom of the flyout to verify it stops at the last block
3. Open the text flyout (which has the Input/Output label in it) and scroll to the bottom
4. Open the Logic category again, and scroll to the bottom.

Bug: You'll notice Blockly adds a big margin below the last block. 

This only seems to happen with flyouts that have flyout labels in them.
It seems the height recalculation of the flyout breaks after opening a flyout that has a label in it.

![blocklyflyoutbug](https://user-images.githubusercontent.com/16690124/27574156-0f1597b8-5aca-11e7-9fac-ffca67ce3b78.gif)

**Comment by rachel-fenichel** [comment]
Is this the same as https://github.com/google/blockly/issues/966?

**Comment by microsoftsam** [comment]
Possibly. Coincidentally the text category in this case is also the tallest category. Let me try making one of the other categories the tallest.

**Comment by microsoftsam** [comment]
No I don't believe it is, I tried making one of the other categories the tallest by adding a bunch of more blocks, and the issue doesn't repro. 
It only repro's for me when a category has a Flyout label in it.

**Comment by microsoftsam** [comment]
Figured out the issue!
When creating Blocks, Flyout_Base creates a rect around each block and records a reference to it in backgroundButtons_ 
It uses the index of the block to set it in the array, so in the instance there is a FlyoutButton, that takes up an index, but doesn't create a rect and hence it's position in the array is undefined. 
ie: Block, Block, FlyoutButton/Label, Block, Block creates this array: 
backgroundButtons_ = [rect, rect, undefined, rect, rect]. 

The issue is the clearOldBlocks_ method in FlyoutBase iterates through the backgroundButtons_ array clearing each rect as it goes, until it reaches an undefined block. This means the last couple of rects are not cleared and remain in the workspace Canvas, causing scrolling issues listed above. 

So fix for this is to update the clearOldBlocks_ method in Flyout base to iterate through all the elements, and only clear if the rect is defined, something like this: 
```
  // Delete any background buttons from a previous showing.
  for (var j = 0; j < this.backgroundButtons_.length; j++) {
    var rect = this.backgroundButtons_[j];
    if (rect) goog.dom.removeNode(rect);
  }
```

I'll publish a PR.

**Comment by picklesrus** [comment]
Fixed on develop.
