### ISSUE TITLE
Long-press on Workspace doesn't show Context Menu

### ISSUE THREAD

**Issue by chrishopkin** [google/blockly#120]
When right mouse clicking on an empty area of the workspace, the context menu is shown (containing Collapse/Expand All options). When long-pressing on an empty area, the context menu is not being shown. (Long-pressing on blocks shows the context menu as expected.)

Can the long-press on empty space behaviour match the right-click on empty space behaviour?

**Comment by carloslfu** [comment]
The pull #96 fix this issue.

**Comment by NeilFraser** [comment]
This used to work, but regressed when workspaces were made headless.  Thanks for the fix.  I've also removed the older code that was no longer functional.
