### ISSUE TITLE
Lua generator test failure: Loops 3

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1200]
Error message: `[string "function unittest_report()..."]:68: '=' expected near 'continue'`

**Comment by TonyLianLong** [comment]
This is not a problem of Blockly generator. The `goto` statement is added in Lua 5.2.0. See [here](http://lua-users.org/wiki/GotoStatement). And the REPL interpreter's Lua version is 5.1 so it cannot run the test program. I installed Lua 5.2.4 on my Mac and run the test program and it seems that it works.
```
~ tll$ lua a.lua
........

Number of tests run: 8

OK
~ tll$ lua -v
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
~ tll$ ```

**Comment by TonyLianLong** [comment]
Maybe we can change the only interpreter recommended to another one with version 5.2.4. Can anyone recommend me one so that I can do it?

**Comment by rachel-fenichel** [comment]
I'm not familiar with Lua.  Offhand, a few questions come up for changing the interpreter:
- Is there a version of Lua that is more commonly used?  That is, do enough people use Lua 5.2.0 that we should aim to generate code for that version?
- When did this break?

**Comment by marisaleung** [comment]
Still investigating which Lua version is most used. The Lua website shows 5.3 for download.
It's correct that 5.2 broke this.
And alternate and up to date interpreter is: http://rextester.com/l/lua_online_compiler

**Comment by TonyLianLong** [comment]
Currently there are a lot of projects using Lua libraries such as [NodeMCU](https://github.com/nodemcu/nodemcu-firmware), which uses Lua 5.1 series, and do not support these functions. I think we can re-write the generator to render it able to generate code that Lua 5.1 can use while keeping the current one and use a constant somewhere to specify which one to use.

**Comment by rachel-fenichel** [comment]
Is it possible to just write code that works for Lua 5.1 and also works for newer versions of Lua?  We much prefer keeping one version of a generator around with the minimal number of options.  The more configuration flags we have the harder it gets to test.

@TonyLianLong if you understand how to rework the generator to write 5.1-compatible code, go for it and send us a pull request.

**Comment by TonyLianLong** [comment]
@rachel-fenichel I will try to have a look at the generator and rework it if it is possible.

**Comment by TonyLianLong** [comment]
@rachel-fenichel I found a solution online, that is to use a `repeat ... until true` and `break` in it to make the effect of jumping directly to the statement after true statement. But if we have while statement in the `repeat ... until true`, that is not going to work and will interrupt the while loop.
And now without an ideal solution in Lua I cannot rewrite the generator.
Do you have an idea in implementing continue in Lua 5.1?

**Comment by rachel-fenichel** [comment]
@marisaleung thoughts?

**Comment by marisaleung** [comment]
As discussed offline, it looks like Blockly's Lua generator has always supported the goto statement in Lua 5.2.0. So projects that use Blockly's Lua generator have been using Lua 5.2.0. And it should be fine to just change the interpreter to a more up-to-date one.

**Comment by TonyLianLong** [comment]
@marisaleung So could I change the interpreter to [this](http://rextester.com/l/lua_online_compiler) one and submit a pull request?

**Comment by marisaleung** [comment]
@TonyLianLong Yes that would be awesome.

**Comment by drigz** [comment]
Looks like you've sorted this out, but I can confirm that the generator was written for Lua >=5.2. It only adds the `continue` label if a continue statement is there for two reasons:
- to keep the generated code clean
- so that basic loops work in older versions of Lua
