### ISSUE TITLE
Create variables button overflows in top toolbox on IE11

### ISSUE THREAD

**Issue by riknoll** [google/blockly#1206]
In the playground on IE11, if you set the toolbox to "Top" and open the variables category, the "Create Variables" button spills over the flyout (so that it is half in and half out). Tested on master and develop.

**Comment by rachel-fenichel** [comment]
>Tested on master and develop
So it's present on both?

**Comment by riknoll** [comment]
Yep

**Comment by rachel-fenichel** [comment]
Closing because we no longer support IE.
