### ISSUE TITLE
If block SVG extra pixel peak

### ISSUE THREAD

**Issue by carlosperate** [google/blockly#121]
It looks like the close distance between the "next statement" notch and the "block input "in the if block might be causing an extra pixel to pop out, which it is only really visible if the block is selected, as the border width is 4px.

Hopefully this screenshot explains it better, it has been taken with the browser zoom set to high, but it is still visible without the zoom.
![if](https://cloud.githubusercontent.com/assets/4189262/8504360/30a01ada-21c8-11e5-980e-ecf5d4183b2a.png)

**Comment by NeilFraser** [comment]
Strange, can't figure out why the offending 'h 0.5 ' was in the code.  Removed this and it now works fine.

Usually when something like this happens the reason for the 'extra' code becomes clear shortly afterwards.  Let's see if anyone points out a regression...

**Comment by carlosperate** [comment]
Thanks Neil! I'll keep an eye to see if it has affected something else.
