### ISSUE TITLE
i think this repository need to suport chinese launguage and other launguage . thx

### ISSUE THREAD

**Issue by OOOOOldZhu** [google/blockly#1212]
i think this repository need to suport chinese launguage and other launguage . thx

**Comment by NeilFraser** [comment]
We do.  See the [msg directory](https://github.com/google/blockly/tree/master/msg/json), in particular [zh-hans.json](https://github.com/google/blockly/blob/master/msg/json/zh-hans.json) and [zh-hant.json](https://github.com/google/blockly/blob/master/msg/json/zh-hant.json).
