### ISSUE TITLE
Support and document changing category colors

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#1218]
Blockly used to allow category colors to be changed [after everything was loaded](https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/blockly/GsU9cHzmvBg). When we added support for JSON and %{messages} for loading colors this became a value instead of a reference, which means colors must be set after messages are loaded and before blocks are loaded to have an effect.

We should investigate if there's a way to make changing colors easy again or at the very least document how to do so with the current version.

**Comment by rachel-fenichel** [comment]
@alschmiedt This is now covered by themes, right?

**Comment by alschmiedt** [comment]
Yup themes covers changing category colours.
