### ISSUE TITLE
Flyout automatically shifts up after scrolling all the way to the top (using mouse scroll)

### ISSUE THREAD

**Issue by microsoftsam** [google/blockly#1220]
Repro steps: 
- Go to playground.html
- Resize your window to ensure the scrollbars would appear in the flyout
- Open any category, and scroll down
- Scroll back all the way to the top (using mouse scroll)
Issue: the Flyout scrolls to the top, and then automatically shifts up a bit

I tried to take a gif to show what's going on, but it's kind of hard to see as it's a mouse scroll: 
![blocklyflyoutscroll](https://user-images.githubusercontent.com/16690124/28221313-7fa1aea4-68cb-11e7-8c51-e6f611634540.gif)

In develop and master.

**Comment by RoboErikG** [comment]
Which browser and OS are you using? I'm not seeing this uson Chrome on a Mac.

**Comment by microsoftsam** [comment]
Mac and Chrome 59.0.3071.115

**Comment by microsoftsam** [comment]
Repro's on Firefox (Mac) but not Safari.

**Comment by microsoftsam** [comment]
Issue doesn't repro for me on the Blockly that's on developer page, or on Blockly Games, but I'm not sure what versions of Blockly they're using.

**Comment by RoboErikG** [comment]
We'll take a look. I'm not seeing it on the [hosted playground](https://blockly-demo.appspot.com/static/tests/playground.html) either, but I don't know if we updated that after our last push to master.

**Comment by microsoftsam** [comment]
Yep. Not repro'ing on the hosted playground either. I believe that's not up to date since Blockly/master has a different playground. Thanks for looking into it :)

**Comment by rachel-fenichel** [comment]
The hosted playground is out of date right now.

**Comment by rachel-fenichel** [comment]
I can repro on Chrome on Ubuntu with a thinkpad.

**Comment by rachel-fenichel** [comment]
And just to make it worse, this only happens with a trackpad scroll--not with a mousewheel scroll or (on a thinkpad) a middle-click scroll.

**Comment by rachel-fenichel** [comment]
@microsoftsam We have a cause, though we don't yet have a fix.

`Blockly.VerticalFlyout.prototype.wheel_()` sets the flyout scroll wrong when the event's delta is between -8 and 0.

When you scroll with the touchpad the browser adds "momentum" by injecting a series of extra wheel events after the actual gesture has ended.  Those wheel events have deltas that decay to zero (their start value depends on the magnitude of the wheel events before, I think).  When you scroll up the deltas are negative, and decay through the -8 to 0 range.

**Comment by rachel-fenichel** [comment]
Fixed by #1309.
