### ISSUE TITLE
Change event fired immediately after inject

### ISSUE THREAD

**Issue by msprotz** [google/blockly#123]
Hi Neil,

Looking at my integration code for Blockly, I stumbled upon the following piece: https://github.com/Microsoft/TouchDevelop/blob/master/www/blockly/blockly-main.ts#L312

The comment there says it all: in the process of calling `inject`, a `change` event is queued using a `setTimeout(..., 0)`, meaning that if I register a change listener *after* calling `inject`, I will get an initial, unwarranted `change` event.

Here's the stack trace, for reference:

Blockly.fireUiEvent (utils.js:200)
Blockly.WorkspaceSvg.fireChangeEvent (workspace_svg.js:377)
Blockly.WorkspaceSvg.createDom (workspace_svg.js:147)
Blockly.createMainWorkspace_ (inject.js:336)
startUi (inject.js:54)
Blockly.inject (inject.js:66)
setupEditor (blockly-main.js:1245)
receive (blockly-main.js:1031)
(anonymous function) (blockly-main.js:1025)

Is this expected?

Thanks,

Jonathan

**Comment by NeilFraser** [comment]
Removed.
