### ISSUE TITLE
Remove goog.dom.createDom(..) and .setProperties(..) usages

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1231]
`goog.dom.createDom(..)` API implies it can set the attributes as its second parameter. It calls down to `goog.dom.setProperties(..)` to do this. `setProperties()` attempts direct some assignments to `element.setAttribute(name, value)` and others `element[name] = value` based on an incomplete `goog.dom.DIRECT_ATTRIBUTE_MAP_` attribute name list.

DOM APIs should be stable for the functionality.  TODO: define an alternative utility function.

**Comment by samelhusseini** [comment]
This is done. I don't see any references in the codebase to createDom or setProperties.
