### ISSUE TITLE
The default image in a image dropdown doesn't change when selecting an option.

### ISSUE THREAD

**Issue by theyork2000** [google/blockly#1232]
I created a drop down input with images as the options. The default shows the first image, but when selecting a different image it doesn't update the default value to show the new image. It works perfectly fine if there is text in there.

If there is a mix of text and image options you can select a text option and then an image option and it switches to that image, but not from an image to another image.

I noticed the same issue in the block factory.

**Comment by rachel-fenichel** [comment]
I'm closing this as a duplicate of #1047, but I'll take a look at it again.
