### ISSUE TITLE
Adding docs to public members

### ISSUE THREAD

**Issue by trodi** [google/blockly#124]
There are a number of non-private variables that are useful, but undocumented like this.previousConnection below:
```javascript
/**
 * Fill a block with initial values.
 * @param {!Blockly.Workspace} workspace The workspace to use.
 * @param {string} prototypeName The typename of the block.
 */
Blockly.Block.prototype.fill = function(workspace, prototypeName) {
  this.previousConnection = null;
...
}
```

I'd like to add brief comments to these as then they can be easily grabbed for doc generation, IDE support, trans-compilation definition files, etc. Would you accept pull requests to document some of these members?

Example:
```javascript
/**
 * Fill a block with initial values.
 * @param {!Blockly.Workspace} workspace The workspace to use.
 * @param {string} prototypeName The typename of the block.
 */
Blockly.Block.prototype.fill = function(workspace, prototypeName) {
  /** @type {Blockly.Connection} */
  this.previousConnection = null;
...
}
```

**Comment by NeilFraser** [comment]
You got lucky with your pull request, I was seconds away from pushing my own.  As it was, I had to do the merge instead of you.  :)
