### ISSUE TITLE
Tab order is strange

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1250]
Tabbing in Blockly follows a strange ordering:

Within a block it goes through all text input fields and all inputs, in order.
If the current item is a Field it calls `showEditor_`.
If the current item is an input it calls tab on the target block of that input.
If there are no items left in the list it calls tab on the parent block.

As a result, it'll tab through all text input fields on a block correctly, and it will tab through all value and statement inputs correctly.  But when it runs out of inputs it will go up the stack, and when it runs out of room up the stack it will give up.  As a result it will never go to the next block in a stack.

Related, in scratch-blocks: https://github.com/LLK/scratch-blocks/pull/1030

**Comment by samelhusseini** [comment]
Fixed.
