### ISSUE TITLE
Blockly.Extensions is broken when compiled.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1251]
Blockly.Extensions.checkHasFunction_ was recently fixed to survive variable renaming.

However, Blockly.Extensions.checkBlockHasMutatorProperties_ is more serious.  It has the same variable renaming issue.  Additionally, its arguments (errorPrefix, block) don't match how it is called 
(name, block, errorPrefix).  I'm not really sure what the intention was here or even how it manages to work it its current state.  Backing away slowly.

Also, anything that uses Blockly.Extensions.MUTATOR_PROPERTIES_ will fail too.

**Comment by rachel-fenichel** [comment]
@RoboErikG @AnmAtAnm How are we doing on this?

**Comment by RoboErikG** [comment]
extensions.js is fixed in develop now. There may be some lingering issues with advanced optimizations, but thanks to https://github.com/google/blockly/pull/1259 we now also have a working demo that uses advanced optimizations.
