### ISSUE TITLE
Should the blockly.js file include files it doesn't *actually* require to run?

### ISSUE THREAD

**Issue by starfishmod** [google/blockly#1256]
I use a fairly customised set of blockly in the uncompressed form as I have a set of customised blocks. I noticed in core/blockly.js the following
````
goog.require('Blockly.FieldAngle');
goog.require('Blockly.FieldCheckbox');
goog.require('Blockly.FieldColour');
// Date picker commented out since it increases footprint by 60%.
// Add it only if you need it.
//goog.require('Blockly.FieldDate');
goog.require('Blockly.FieldDropdown');
goog.require('Blockly.FieldImage');
goog.require('Blockly.FieldTextInput');
goog.require('Blockly.FieldNumber');
goog.require('Blockly.FieldVariable');
````
As I don't use FieldAngle, FieldColour, FieldVariable in my blocks the only way for me to not to load them is to retain my own copy of the blockly.js file.

Is it feasible to remove these from the blockly.js file as from my reading these aren't technically required for the blockly.js file and the are also already called by goog.require in the blocklyuncompressed file in any case. (I can't speak for the compressed version and how it know which files to include).

Another way to look at it - should the blockly.js file include files it doesn't *actually* require to run?

**Comment by rachel-fenichel** [comment]
The requires in `blockly.js` determine which requires end up in `blockly_uncompressed.js` as part of our build process, so they need to be in that file.

What's the concern with having the extra files?  In general the non-date-picker files don't increase the footprint by much at all.

**Comment by starfishmod** [comment]
Thanks for the quick response. I guess to me it seems unnecessary to load files that aren't going to be used, especially as they in turn load files from closure (remember I'm running uncompressed, and then I'll do my own compression later as I'm using other closure libs) and goes against the spirit of building/loading only what you need and use; in the closure framework (every kb helps :) ). 

Is it something you would consider changing in the future for those of us that use blockly in a non-default way?

**Comment by rachel-fenichel** [comment]
My understanding was that if you care strongly about those extra kb you're building your project and then compressing it and tree shaking it, which.  Are those still left in after tree shaking?

The problem is that we would need to redo our build process entirely to support what you're asking for.  I agree that selectively including these things is a good idea, but I don't have it in the near term on my timeline.
