### ISSUE TITLE
CSS namespace injectionDiv

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1258]
One of the CSS rules falls outside the Blockly namespace:
https://github.com/google/blockly/blob/master/core/css.js#L129

This should be called blocklyInjectionDiv, or somesuch.  Otherwise we may collide with random elements on the host page.

**Comment by AnmAtAnm** [comment]
`wontfix` since this is a breaking change for anyone who has overridden the original class name (however rare that might be).
