### ISSUE TITLE
Kabyle localization

### ISSUE THREAD

**Issue by belkacem77** [google/blockly#1265]
Would you like consider adding the kab locale online on the site. Localization reaches 99.3%.

**Comment by rachel-fenichel** [comment]
I'll look into it--I need to find the steps for adding a new language.

**Comment by belkacem77** [comment]
Thank you. The team is waiting. We are planning training sessions for teens!!

**Comment by rachel-fenichel** [comment]
It looks like you're actually asking about Blockly Games. I've talked to the person who runs Blockly Games.  It will be in the next push, but we don't have a specific date for that yet.

We can also add kab to the [code demo](https://blockly-demo.appspot.com/static/demos/code/index.html), if you want.  That's completely optional.  To do that, you need to translate https://github.com/google/blockly/blob/master/demos/code/msg/en.js and submit it at demos/code/msg/kab.js.  Then we can add it to the dropdown on the demo.

**Comment by belkacem77** [comment]
Hi Rachel.
It's done. the cla signed and demos/code/msg/kab.js added (translated).

**Comment by rachel-fenichel** [comment]
Hi @belkacem77,

Quick update: we're still working on releasing the new version of Blockly Games (a lot has changed in blockly since the last release), but we haven't forgotten about this.

**Comment by belkacem77** [comment]
Hello @rachel-fenichel 
Thanks for taking care about it. The kab locale is waiting to see it. We are planing game sessions at schools in our region after release.

**Comment by rachel-fenichel** [comment]
@belkacem77 Sorry for the long delay.  Blockly Games isn't yet ready for a full release, but you can reach the kab version here: https://beta-dot-blockly-games.appspot.com/?lang=kab

Cheers,
Rachel

**Comment by belkacem77** [comment]
Hi @rachel-fenichel ,
Thanks. I shared it on social networks even though it's a beta release to see if there is translation errors. 

Thanks again
