### ISSUE TITLE
Hard to implement a custom field

### ISSUE THREAD

**Issue by felix2ch** [google/blockly#1270]
Microsoft Make Code implements custom fields by injecting lots of code and logic.  Is it possible to provide a super class for extending Fields?

**Comment by rachel-fenichel** [comment]
You can make a custom field by extending Blockly.Field.  For a complete example you can look at [Blockly.FieldTextInput.](https://github.com/google/blockly/blob/master/core/field_textinput.js).  We don't have great documentation about this, unfortunately, but it's completely doable.

**Comment by felix2ch** [comment]
Yes, I can extends Blockly.Field, then I need add it to  Blockly.Block.prototype.interpolate_ function in  blocks.js, That's blockly's source code. I'm not sure that is a proper way or not.

**Comment by rachel-fenichel** [comment]
Yes, that's currently the proper way.  We (currently) see adding a custom field as a sign that someone is extending blockly and playing around with fairly core pieces, rather than just using Blockly as a module.

**Comment by AnmAtAnm** [comment]
Fixed in #1594
