### ISSUE TITLE
Create variable doesn't handle '<' gracefully

### ISSUE THREAD

**Issue by jessica-norris** [google/blockly#1271]
We discovered today that when you try to create a new variable with a '<' in the name (eg. "<foo"), that the following behaviour occurs:

* No UI feedback -- no error message, you are returned to the playground, no new variable blocks are created, and all existing blocks in the variable tray are reduced to the 'use variable' type only
* All subsequent variables are created normally, except that only the 'use variable' type now appear in the variable tray.
* you can only access the "<foo" variable by dragging a different variable block out of the tray and using the dropdown box to switch to it.
* deleting the "<foo" variable from the dropdown box restores all other variables to their correct state inside the variables tray.

There may be other characters that cause this behaviour, however '>' does not appear to cause this effect.

To reproduce, open the [playground](https://blockly-demo.appspot.com/static/tests/playground.html), create a variable called "name" and then one called "<foo".

**Comment by rachel-fenichel** [comment]
Interesting.  Thanks for the detailed bug report.  We'll take a look.

**Comment by rachel-fenichel** [comment]
With a variable named `<foo` the result of `Blockly.Variables.generateVariableFieldXml_` is `
"<field name="VAR" variableType="" id="?xRg1|%c%P73;;;FOEH2"><foo</field>"`.

**Comment by rachel-fenichel** [comment]
https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents

Looks like we need to escape `<` and `&` before using textToDom.

**Comment by rachel-fenichel** [comment]
Fixed by #1279
