### ISSUE TITLE
Git push 403 forbidden, access denied

### ISSUE THREAD

**Issue by xlcrr** [google/blockly#1272]
I am trying to integrate Blockly into a Laravel app (Vagrant homestead vm)

When I add Blockly to /public and make a Get request I get a 403 Forbidden error
when I move the files to /public/js/blockly/ it works locally as expected. 

My issue is that when I git add ., commit, push, the contents of the folder are ignored. I have been experimenting with .gitignore but I don't think its a .gitignore issue.

If I change /blockly/.git/config to https instead of git, I get 

blockly:git push --all
remote: Permission to google/blockly.git denied to xlcrr.
fatal: unable to access 'https://github.com/google/blockly.git/': The requested URL returned error: 403

How can I push the contents of this folder to our git repo?
see
https://stackoverflow.com/questions/45611242/git-push-ignoring-blockly-subdir?noredirect=1#comment78181490_45611242

Thanks

**Comment by RoboErikG** [comment]
It sounds like you're trying to push to our repo, not your copy. You should read the [GitHub forking guide](https://guides.github.com/activities/forking/) for the basics of forking and making changes to your own copy.

In the future, please use the [Blockly mailing list](https://groups.google.com/forum/#!forum/blockly) to ask questions.
