### ISSUE TITLE
Enable scrolling in only one direction

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1292]
E.g. only horizontal scrolling in the workspace, or only vertical scrolling.  The other position would be fixed.

Open questions:
- Where to specify which direction of scrolling to allow?  Right now scrolling is specified in the options that are passed into the inject call, but is just a boolean.  
We could change it to be: "both", "none", "vertical", and "horizontal".
Leaving it undefined would keep the current behaviour: "both" if there are categories, otherwise "none".
"true" would be parsed as "both".
"false" would be parsed as "none".

- Will we allow vertical-only scrolling with a horizontal toolbox?  Or the other way around?
- What happens if the user zooms?  Or is that disallowed?

In the non-scrolling direction we would preserve the current behaviour:
- Blocks placed outside of the bounds would be [bumped back in](https://github.com/google/blockly/blob/master/core/inject.js#L203).
- The content dimensions would be the size of the blocks bounding box in that dimension, which is not allowed to be bigger than the viewport in that direction.

In the scrolling direction we would preserve the current scrolling behaviour:
- The content dimensions would include a buffer on each side, equal to half of the size of the viewport in that direction.

**Comment by RoboErikG** [comment]
> Will we allow vertical-only scrolling with a horizontal toolbox? Or the other way around?
> What happens if the user zooms? Or is that disallowed?
Would these just be checks on the injection params? I think you're right that those are probably bad configurations, but in general I think we should be moving away from APIs that need to check other parts of the UI to figure out what they can do. It's much easier to maintain an API for each component if you don't try to handle all the possible configurations for components, even if it lets devs do weird combinations.

**Comment by microsoftsam** [comment]
Will this be a mode (ie: an option)? or will that be the default, dependent on whether or not you're using horizontal or vertical workspaces?

**Comment by RoboErikG** [comment]
@Sam, this would be a new option, not the default. It was a feature we wanted to have for [Code a Snowflake](https://santatracker.google.com/snowflake.html) but didn't have time to implement.

**Comment by rachel-fenichel** [comment]
Here's another fun use case: setting a fixed height to the workspace, but still allowing vertical scrolling.
That would be for horizontal mode, and an equivalent vertical version would exist.  

That would let the user have more than a single stack of blocks, while not letting them get too lost in the workspace.

**Comment by brokenpylons** [comment]
I managed to hack something together. I added a single vertical scrollbar with:

```
workspace.scrollbar = new Blockly.Scrollbar(workspace, false);
```

However the panning didn't work as expected. I had to move the mouse horizontally for the workspace to scroll vertically. I fixed the problem by monkey patching ```updateScroll_``` in ```WorkspaceDragger```:

```
Blockly.WorkspaceDragger.prototype.updateScroll_ = function(x, y) {
  this.workspace_.scrollbar.set(y);
};
```
The problem is that single scrollbars accept only one argument and the original implementation called ```set(x, y)```,  so the ```x``` component got used instead of ```y```. An easy fix would be to check if ```horizontal_``` is ```false``` and in that case call ```set(y)```.

**Comment by brokenpylons** [comment]
For bonus points, I also managed to add scrolling with the mouse wheel. Just call this in the wheel event.

```
const {scrollbar} = workspace;
scrollbar.set((scrollbar.handlePosition_ / scrollbar.ratio_) + e.deltaY);
```

**Comment by brokenpylons** [comment]
I discovered another issue. I could not move the blocks off the visible part of the workspace because they get bumped in. I want this functionality on the left and right, but not the top and bottom. I had to monkey patch the ```createMainWorspace``` function (```workspaceChanged``` callback). I removed the part that bumps the blocks in at the top and the bottom. Here is the code:

```
Blockly.createMainWorkspace_ = function(svg, options, blockDragSurface,
    workspaceDragSurface) {
  options.parentWorkspace = null;
  var mainWorkspace =
      new Blockly.WorkspaceSvg(options, blockDragSurface, workspaceDragSurface);
  mainWorkspace.scale = options.zoomOptions.startScale;
  svg.appendChild(mainWorkspace.createDom('blocklyMainBackground'));

  if (!options.hasCategories && options.languageTree) {
    // Add flyout as an <svg> that is a sibling of the workspace svg.
    var flyout = mainWorkspace.addFlyout_('svg');
    Blockly.utils.insertAfter(flyout, svg);
  }

  // A null translation will also apply the correct initial scale.
  mainWorkspace.translate(0, 0);
  Blockly.mainWorkspace = mainWorkspace;

  if (!options.readOnly && !options.hasScrollbars) {
    var workspaceChanged = function(e) {
      if (!mainWorkspace.isDragging()) {
        var metrics = mainWorkspace.getMetrics();
        var edgeLeft = metrics.viewLeft + metrics.absoluteLeft;
        var edgeTop = metrics.viewTop + metrics.absoluteTop;
        if (metrics.contentTop < edgeTop ||
            metrics.contentTop + metrics.contentHeight >
            metrics.viewHeight + edgeTop ||
            metrics.contentLeft <
                (options.RTL ? metrics.viewLeft : edgeLeft) ||
            metrics.contentLeft + metrics.contentWidth > (options.RTL ?
                metrics.viewWidth : metrics.viewWidth + edgeLeft)) {
          // One or more blocks may be out of bounds.  Bump them back in.
          var MARGIN = 25;
          var blocks = mainWorkspace.getTopBlocks(false);
          var oldGroup = null;
          if (e) {
            oldGroup = Blockly.Events.getGroup();
            Blockly.Events.setGroup(e.group);
          }
          var movedBlocks = false;
          for (var b = 0, block; block = blocks[b]; b++) {
            var blockXY = block.getRelativeToSurfaceXY();
            var blockHW = block.getHeightWidth();
            // Bump any block that's off the left back inside.
            var overflowLeft = MARGIN + edgeLeft -
                blockXY.x - (options.RTL ? 0 : blockHW.width);
            if (overflowLeft > 0) {
              block.moveBy(overflowLeft, 0);
              movedBlocks = true;
            }
            // Bump any block that's off the right back inside.
            var overflowRight = edgeLeft + metrics.viewWidth - MARGIN -
                blockXY.x + (options.RTL ? blockHW.width : 0);
            if (overflowRight < 0) {
              block.moveBy(overflowRight, 0);
              movedBlocks = true;
            }
          }
          if (e) {
            if (!e.group && movedBlocks) {
              console.log('WARNING: Moved blocks in bounds but there was no event group.'
                        + ' This may break undo.');
            }
            Blockly.Events.setGroup(oldGroup);
          }
        }
      }
    };
    mainWorkspace.addChangeListener(workspaceChanged);
  }
  // The SVG is now fully assembled.
  Blockly.svgResize(mainWorkspace);
  Blockly.WidgetDiv.createDom();
  Blockly.Tooltip.createDom();
  return mainWorkspace;
};
```
