### ISSUE TITLE
Height of flyout is wrong sometimes

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1300]
Open up https://blockly-demo.appspot.com/static/tests/playground.html.
1. Open up Colour category. Note length of scrollbar (if there is one)
2. Open Text category
3. Open up Colour category.
Notice that the scroll bar in the Colour category allows you to scroll quite far down.  Opening the other categories doesn't seem to make this happen. Even Lists doesn't which is also a long one.

Happens on Chrome on a Mac. Haven't tested elsewhere.

Scrreenshot after step 1:
![screen shot 2017-09-01 at 11 55 46 am](https://user-images.githubusercontent.com/15675877/29983849-8b21e9e4-8f0c-11e7-9fef-efb68882e5c6.png)

Screenshot after step 3:
![screen shot 2017-09-01 at 11 55 20 am](https://user-images.githubusercontent.com/15675877/29983852-8d132ac4-8f0c-11e7-8f96-7a440bd205e7.png)

**Comment by microsoftsam** [comment]
I think this is the same as #1195

**Comment by picklesrus** [comment]
Yup. This is a dupe! Closing.
