### ISSUE TITLE
Flyout getMetrics causes a reflow and style recalculation

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1303]
Very similar issue to what https://github.com/google/blockly/commit/a67f841671dd5d61647ea4f159350e5823b69e69 solved.

Extra considerations for the flyout:
- Flyout also contains labels and buttons which need to be added to the bounding box calculations.
- Gaps as specified by the toolbox/flyout xml.

**Comment by alschmiedt** [comment]
The flyout now stores its `width` and `height` every time `reflow` is called. The metrics manager uses these values every time we call `getMetrics` instead of calling `getBBox` on the html div.
