### ISSUE TITLE
random id break the regular

### ISSUE THREAD

**Issue by duzc2** [google/blockly#1304]
when blockly want a new id for a block , the Blockly.utils.genUid() may return a string with a $ endding.
and then 
Blockly.JavaScript.STATEMENT_PREFIX.replace(/%1/g,'\''+block.id+'\'') return a bad javascript code.
Example:
the id is 
_nL*uyA.6:c?nRPwL3)1$_
the STATEMENT_PREFIX is
_highlightBlick(%1);_
after the replace() :
_highlightBlock('nL*uyA.6:c?nRPwL3)1);
);_

as you see , there are two ");" and lose a '

my solution is remove the $ from Blockly.utils.genUid.soup_

**Comment by NeilFraser** [comment]
I'm assuming you are referring to IDs in the procedure (function) generators.  They lacked proper escaping.  Fixed in develop branch.
