### ISSUE TITLE
The sound can not play normally in the wkwebview in IOS

### ISSUE THREAD

**Issue by varyzheng** [google/blockly#1310]
We use blockly in the wkwebview in IOS now, blockly-ios may be used later.
Now, the page in PC browser can play sound normally, but in the wkwebview, it can always play one sound, sometimes two or more, but never play every sound. I don't change workspace_audio.js codes, looking forward to your answer, thanks.@rachel-fenichel

**Comment by RoboErikG** [comment]
Unfortunately, iOS audio APIs for web don't work very well for loading multiple sounds. See the comment in https://github.com/google/blockly/blob/3ca7bcc3dfc80651c65c103740feec3de39fb1c3/core/workspace_audio.js#L113
