### ISSUE TITLE
Travis Script: Log sizes of _compressed.js and _uncompressed.js files.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1315]
Ideally, this should include the tree-shaken (advanced compilation) sizes.

This should be logged in a manner that can be extracted by other programs.

Even better if Travis can fail when size exceeds some percentage relative to the last compile attempt.

 * Can the travis script access an external URL?
 * How would the system know whether it was a master or develop branch, and know to compare to the previous master/develop build?

**Comment by rachel-fenichel** [comment]
Tracked with the metadata test.
