### ISSUE TITLE
Enable hats per block

### ISSUE THREAD

**Issue by vicng** [google/blockly#1325]
Each block should be able to define its own "hat", independent of others. It is currently a global setting defined via `Blockly.BlockSvg.START_HAT`.

### JSON
The JSON syntax for this should live under a `"style"` property.

eg.
```
{
  "name": "some_block",
  "style": {
    "hat": "cap"
  }
  ...
}
```

Two values can be specified for `"hat"`:
1. `"none"` - Flat horizontal top
![screen shot 2017-09-18 at 2 19 53 pm](https://user-images.githubusercontent.com/13488389/30565267-7f905548-9c7c-11e7-8f3c-388fd56bbbbd.png)

2. `"cap"` - Rounded oval with horizontal base
![unnamed](https://user-images.githubusercontent.com/13488389/30565085-e44dfa7c-9c7b-11e7-9980-2003a8255324.png)

Defining a hat in JSON still follows current rules, where it's only rendered if the block doesn't have a previous or output connection.

### JavaScript

A `hat` property needs to be added to the `Block` object.

Additionally, a new JS property should be defined named `Blockly.BlockSvg.Style.HAT` (note the added `Style` part). This new property accepts the same string values ("none" or "cap") and is the default hat to use for all blocks without a previous or output connection. This should deprecate `Blockly.BlockSvg.START_HAT`.

**Comment by rachel-fenichel** [comment]
Is there a reason to deprecate `Blockly.BlockSvg.START_HAT`?

**Comment by vicng** [comment]
Yes, "true"/"false" doesn't make sense if multiple hat types can be defined. We can still support it, but it should be removed from documentation.

**Comment by AnmAtAnm** [comment]
A hat block is now included in the playground [test_blocks.js](https://github.com/google/blockly/blob/develop/tests/blocks/test_blocks.js#L372), "Styles" category.

**Comment by RoboErikG** [comment]
Now supported with themes.

**Comment by rachel-fenichel** [comment]
@alschmiedt to point at documentation/an example of how to do this.

**Comment by alschmiedt** [comment]
A user can create a block style with "hat" and then set that block style for their specific block. More information can be found [here](https://developers.google.com/blockly/guides/configure/web/themes#block_style).
