### ISSUE TITLE
Calling getViewportPageOffset when showing the widget div

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1327]
### Problem statement
`Blockly.WidgetDiv.show` calls `goog.style.getViewportPageOffset`, which may be expensive.  We should investigate: is it expensive?  If so, how often is it happening?  Can we work around the firefox issue any other way?

```
 // Temporarily move the widget to the top of the screen so that it does not
 // cause a scrollbar jump in Firefox when displayed.
 var xy = goog.style.getViewportPageOffset(document);
```

- [X] Bug report
- [ ] Feature request

### Expected Behavior

N/A

### Actual Behavior

N/A

### Steps to Reproduce

Fields that use the widget div include:
Color picker
Date picker
Dropdown
Variable Dropdown

The context menu also uses the widget div.
### Stack Traces
N/A

### Operating System and Browser
This code happens in every browser, but says it's there to prevent a bug in firefox.

### Additional Information

N/A

**Comment by rachel-fenichel** [comment]
@samelhusseini do you know if this is still necessary, with all of the changes you've made in the widget div code?

**Comment by samelhusseini** [comment]
It appears the purpose of this code is layout of the widget div without a scrollbar appearing in Firefox. This is indeed running on all browsers (maybe it shouldn't). Nothing in my recent changes makes me think this is no longer necessary.

Impact:  This happens on every click to show a widget div. That's not too often in the grand scheme of things.

I'll try to repro the initial issue on Firefox and see if there's another way around it.

**Comment by samelhusseini** [comment]
It appears this was added to avoid a problem with dropdowns https://github.com/google/blockly/issues/186.
I can no longer repro any issues around scrollbars for text fields, context menu, and dropdowns in Firefox without the fix. Removing..

**Comment by samelhusseini** [comment]
Fixed.
