### ISSUE TITLE
Add Blockly.defineBlocksWithJsonArray to developer guides

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1333]
### Problem statement

- [ ] Bug report
- [ ] Feature request
- [x] Documentation request

### Expected Behavior

Documentation should describe `Blockly.defineBlocksWithJsonArray` and have at least one example.  There are two places it may be relevant: https://developers.google.com/blockly/guides/configure/web/custom-blocks https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks

### Actual Behavior

`Blockly.defineBlocksWithJsonArray` isn't documented in our developer guides.

### Additional Information

Mentioned by @devnook in https://github.com/google/blockly/pull/1273

**Comment by alschmiedt** [comment]
Added here: https://developers.google.com/blockly/guides/configure/web/custom-blocks#json_array
