### ISSUE TITLE
FieldImage: Support "flip_rtl", like scratch-blocks

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1339]
scratch-blocks added a boolean "flip_rtl" option in their JSON spec.  We should port that back to Blockly.

This is useful when the icon is relative to the text flow, such as a "u-turn" arrow on a repeat block.

<img width="124" alt="screen shot 2017-09-22 at 4 11 36 pm" src="https://user-images.githubusercontent.com/9916202/30767329-ac774ad0-9fb0-11e7-9634-05e8682c5dfe.png">
<img width="127" alt="screen shot 2017-09-22 at 4 12 44 pm" src="https://user-images.githubusercontent.com/9916202/30767349-da01bfee-9fb0-11e7-984f-a9d3d3c0a221.png">

Example:

    {
      "type": "field_image",
      "src": "icons/control_repeat.svg",
      "width": 40,
      "height": 40,
      "flip_rtl": true
    }

See implementation in scratch-blocks: https://github.com/LLK/scratch-blocks/search?q=flip_rtl

**Comment by rachel-fenichel** [comment]
+1.  We should definitely have this in blockly.

**Comment by vicng** [comment]
As discussed offline, this property should be in camelcase form to remain consistent with other JSON properties: `flipRtl`

**Comment by rachel-fenichel** [comment]
And here's the rest of the implementation for vertical blocks: https://github.com/LLK/scratch-blocks/blob/develop/core/block_render_svg_vertical.js#L659
