### ISSUE TITLE
Disable function calls when disabling the function definition

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1344]
### Bug Report

Disabling a function definition in the workspace may leave the system in a broken state, where any calls to function remain enable and generate code with no matching definition for the identifier.

<img width="614" alt="screen shot 2017-09-27 at 1 32 59 pm" src="https://user-images.githubusercontent.com/9916202/30936726-9bcc327c-a389-11e7-84a8-961919239389.png">

### Expected Behavior

Similar to how deleting a function definition deletes the matching function calls, disabling a function definition should also disable the matching calls.

### Actual Behavior

Function call is left enabled, and any generated code is broken.

### Steps to Reproduce

1. Add a user defined function.
2. Add a call to the function.
3. Disable the definition, but not the call.

**Comment by AnmAtAnm** [comment]
What should happen when the function definition get reenabled? Should the all the function calls also get reenabled? Should only the function calls that were disabled get re-enabled (requiring maintaining a list)?

What happens for functions with return values, and their callers that might be embedded in a block expecting a value?

**Comment by RoboErikG** [comment]
Proposed:

- Add an event listener to function call blocks.
- Listener should self disable/enable when the function definition is enabled/disabled.
- Listener should also keep track of previous state when disabling and only enable if it wasn't previously disabled.
- We will not serialize the previous state, so callers will always be re-enabled with their definition after loading a workspace.
