### ISSUE TITLE
Align first row of fields/inputs for connected blocks

### ISSUE THREAD

**Issue by vicng** [google/blockly#1346]
This is better explained with screenshots.

### Example 1
Problem:
![screen shot 2017-09-27 at 2 16 30 pm](https://user-images.githubusercontent.com/13488389/30938325-8019ff0a-a38e-11e7-943f-97ea75d01293.png)

Desired behaviour:
![screen shot 2017-09-27 at 2 14 37 pm](https://user-images.githubusercontent.com/13488389/30938301-6921e600-a38e-11e7-81a2-a7f715c9e890.png)

### Example 2

Problem:
![screen shot 2017-09-27 at 2 41 44 pm](https://user-images.githubusercontent.com/13488389/30939364-090a7f26-a392-11e7-8ae1-4cf4ebcdbad6.png)

Desired behaviour (note how the "do" label is also aligned with the first row):
![screen shot 2017-09-27 at 2 40 56 pm](https://user-images.githubusercontent.com/13488389/30939325-e9851b5c-a391-11e7-9fc2-fb2b1ebbbaf6.png)

### Example 3

Problem:
![screen shot 2017-09-27 at 2 47 09 pm](https://user-images.githubusercontent.com/13488389/30939580-c23185bc-a392-11e7-8b94-8695a1d299a4.png)

Desired behaviour (note how alignment still occurs for the bottom row with its children's first rows):
![screen shot 2017-09-27 at 2 46 50 pm](https://user-images.githubusercontent.com/13488389/30939571-b82ae40a-a392-11e7-9796-3230e4a75190.png)

**Comment by rachel-fenichel** [comment]
Fixed by #2835
