### ISSUE TITLE
Make horizontal spacing between fields/inputs more consistent

### ISSUE THREAD

**Issue by vicng** [google/blockly#1347]
Example:
![screen shot 2017-09-27 at 2 24 45 pm](https://user-images.githubusercontent.com/13488389/30938663-ac3bd5a8-a38f-11e7-8b72-40f8deb8845b.png)

**Comment by rachel-fenichel** [comment]
From a cursory inspection:

Here's the same block with external inputs:
![image](https://user-images.githubusercontent.com/13686399/30983747-25841f6e-a440-11e7-9171-6443466da335.png)

The first field in an input doesn't get extra space added in front of it: https://github.com/google/blockly/blob/develop/core/block_render_svg.js#L440

The application of that mismeasurement may be on a different line, though.

**Comment by BeksOmega** [comment]
You can now do this with a custom renderer.
