### ISSUE TITLE
[documentation request] Block context menu

### ISSUE THREAD

**Issue by carlosperate** [google/blockly#135]
A request rather than a bug report.

There is nothing documented in https://developers.google.com/blockly about context menus. For people adapting Blockly it could be quite useful to know that a context menu can be disabled in the block definition (`this.contextMenu = false;`) or that it can be expanded using the block function `customContextMenu: function(options) {}`.

**Comment by markfinn** [comment]
This is really useful element and browsing the issues list is the first I've seen of it.

**Comment by AnmAtAnm** [comment]
#1358 is a dupe, but it has more info, so leaving that one as the active.
