### ISSUE TITLE
Spelling error in index.html

### ISSUE THREAD

**Issue by toastflaming** [google/blockly#1352]
### Problem statement
N/A

- [ ] Bug report
- [ ] Feature request

_What were you trying to do when you hit this bug?  Or, what do you want to do with Blockly that your proposed feature would enable?_
N/A, See below

### Expected Behavior

Should display `executable` instead of `executible`
### Actual Behavior

_Describe what actually happens.  Include screenshots if applicable._

https://i.imgur.com/Z37sBCb.png

### Steps to Reproduce
view-source:https://developers.google.com/blockly/
_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Stack Traces

```
Please open up the console.  If you see any Blockly-related errors, paste them here.

Ignore any instances of "Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()."
```

### Operating System and Browser

- [ ] Desktop:
  - [x] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):
  - Device: N/A
  - OS: N/A
  - Browser N/A
  - Version N/A

### Additional Information

_Anything else we should know?_

**Comment by NeilFraser** [comment]
Can you provide a reference showing that "executible" is preferred over "executable"?

**Comment by NeilFraser** [comment]
[Deleted earlier incorrect response]
Confirmed.  The page's meta tags should use "executable".

**Comment by AnmAtAnm** [comment]
Fixed.   Thanks for the report.
