### ISSUE TITLE
Add a 'strict' flag on connections

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1357]
### Problem statement

- [ ] Bug report
- [x] Feature request

A connection with the `null` type will connect to any other connection, regardless of the other connection's type.  As a result, making a block that doesn't allow default blocks to connect to it is difficult: you have to change the connection types on all existing blocks.

### Requested Behavior

I'm considering adding an optional `strict` flag to connections.  

A connection with the `strict` flag set will only connect to another connection if they both have at least one type in common in their `checks`.

Compatible:
`['Zebra', 'Mongoose']` and `['Cobra', 'Mongoose']`
`null` and `null`

Incompatible:
`['Zebra', 'Mongoose']` and `['Lion', 'Cheetah']`
`['Zebra', 'Mongoose']` and `null`

This would let a developer easily add a few strict checks without needing to update all of their blocks.

### Additional Information
Related to https://github.com/LLK/scratch-blocks/issues/1127

**Comment by rachel-fenichel** [comment]
@vicng @AnmAtAnm 

Do you have thoughts about this, particularly with respect to Android and iOS?

**Comment by bkisdi** [comment]
I needed it in my projects too. I changed all the standard blocks to have 'Statement' type - this is to be done once (well, once after each download), and it solved the problem.

1. In all files of blockly/blocks replace all
setPreviousStatement(true);
with
setPreviousStatement(true, 'Statement');

2. In all files of blockly/blocks replace all
setNextStatement(true);
with
setNextStatement(true, 'Statement');

Please.

**Comment by vicng** [comment]
@rachel-fenichel Can you add a potential JSON spec to the proposal?

**Comment by rachel-fenichel** [comment]
## Options
- Don't add a strict flag at all, but make it easier to modify types of connections (in developer tools). 
  - No changes in core Blockly.
- Add a strict flag at the block level (we would choose a more descriptive name).
  - Adding a flag at the block level would be the simplest from an API perspective, but means that developers need to recognize that the block-level flag has an impact on connection types.  The block-level strict flag makes all connections on the block strict.  To make a non-strict connection on a strict block, a developer would set the type of that connection to the wildcard (null).

Block JSON would look like this:
```
{
  //...
  previousStatement: null,
  nextStatement: ["Panda", "Koala"],
  strict: true
}
```

- Add a strict flag at the connection level, by making connections into objects in JSON.
  - This keeps the strict specifier as close as possible to the connection definition, but means we need to keep backwards compatibility.

JSON would look like this:
```
{
  // ...
  previousStatement: {
    checks: null
  },
  nextStatement: {
    checks: ["Panda", "Koala"],
    strict: true
  }
}
```



## Compatibility Tables

Previously each connection could have the null type or one or more explicit types.  The first option would preserve this.  The compatibility matrix for two connections with different types looked like this:
![image](https://user-images.githubusercontent.com/13686399/31747500-21a6c0bc-b422-11e7-995f-989045e9c13d.png)

If we add any sort of strict tag, the new table looks like this:
![image](https://user-images.githubusercontent.com/13686399/31747526-423e2388-b422-11e7-8f9c-943f1bf7c96b.png)

**Comment by bkisdi** [comment]
The flag should be able to be set differently on different connections.
What aboout input connections?
Anyway, I suggest to keep the current (simpler) Compatibility Table, and add explicit type to the standard blocks, as I commented at Oct 11, 2017.

**Comment by rachel-fenichel** [comment]
Adding the wildcard (null) to the type list on a given connection or setting the checks to null on that connection lets it be non-strict when the rest of the block is strict.

Input connections can be treated the same way as my previous and next examples above.

Adding explicit types to the standard blocks may break other people's projects if they are relying on the wildcard behaviour of those blocks.

**Comment by duzc2** [comment]
@rachel-fenichel 
in the new table
strict TypeA - strict TypeA = N
Not strict TypeB - not strict TypeB = N 

why ?

**Comment by rachel-fenichel** [comment]
Done!
