### ISSUE TITLE
Missing documentation for custom context menus

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1358]
It should be on the [Define Blocks](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks) page, at a minimum.

`enableContextMenu` is the JSON flag (boolean).
In JavaScript, you set `contextMenu` to `true` to enable or `false` to disable.

Defining the `customContextMenu` on the block lets you modify or add menu options.

`customContextMenu` is a function that is passed the list of `menuOptions` to modify in place.

`menuOptions` is a list of options, each of which has `text`, `enabled`, and a `callback`.

Only supported on web.

**Comment by AnmAtAnm** [comment]
https://groups.google.com/d/msg/blockly/-Zf0D83BucE/OE5_Wz34AAAJ

**Comment by samelhusseini** [comment]
Update on this. enableContextMenu is no longer a thing.

block.contextMenu: boolean, set to false to disable the custom context menu on the block.
block.customContextMenu: function(!Array.<!Object>) to add additional items to the block context menu. Modify the passed in array.

**Comment by BeksOmega** [comment]
Usually I don't bump old issues, but it would be really great to get this documented!

Some additional things that could be added to the docs:
[BlockSvg.generateContextMenu](https://github.com/google/blockly/blob/52b818ed67c5bfa7fd73edf2b067649b8b1f447b/core/block_svg.js#L715) - allows you to add menu options to /all/ blocks.
[WorkspaceSvg.configureContextMenu](https://github.com/google/blockly/blob/52b818ed67c5bfa7fd73edf2b067649b8b1f447b/core/workspace_svg.js#L399) - allows you to add options to the workspace context menu.

I know there was a [proposal](https://github.com/google/blockly/issues/3237) for a new system a few months ago, but I still think it's important for the current users to have good docs.

**Comment by rachel-fenichel** [comment]
I just added the docs for basic block context menus: https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#context_menus

I don't want to add docs for overriding functions for the broader context menus, because @maribethb is currently working on the new system.
