### ISSUE TITLE
Long dropdown menu height calculations.

### ISSUE THREAD

**Issue by CarbonMan** [google/blockly#1364]
### Problem statement
I am populating a dropdown at runtime using ajax calls. It works however the list defaults to displaying all items regardless of the number of items. That is, while the dropdown has a scrollbar, the list will display all the items even if the screen cannot handle it. It can't scroll
[Example](https://lh3.googleusercontent.com/-p4SsBFvvps4/WeMRVT-TmhI/AAAAAAAAA7k/1rIDxZBJuiAd2V6DSpTOWF8wk3e8-1LQwCLcBGAs/s1600/list.png)

- [x ] Bug report
- [ ] Feature request

### Expected Behavior
I would expect the displayed dropdown to fit the available area and require the user to scroll to the items.

### Actual Behavior
All items are displayed, rather than a typical list that can be scrolled.

### Steps to Reproduce
N/A

### Stack Traces
N/A

### Operating System and Browser
- [x ] Desktop:
  - [x] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):

### Additional Information
The way I worked around it was to set this style into the page
<style>
  .blocklyWidgetDiv .goog-menu {
    max-height: 215px;
  }
</style>

Then the function in core\ui_menu_utils.js that calculates the height was overriden.

<script type=text/javascript>
Blockly.utils.uiMenu.getSize = function(menu) {
  var menuDom = menu.getElement();
  var menuSize = goog.style.getSize(menuDom);
  // Replaced scrollHeight with clientHeight
  menuSize.height = menuDom.clientHeight;
  return menuSize;
};
</script>

**Comment by rachel-fenichel** [comment]
Are you on the most recent version of Blockly?  We had a variety of issues with the dropdown and page sizing: https://github.com/google/blockly/issues/1242.  

I fixed it in this change: https://github.com/google/blockly/pull/1334 and it went out in the most recent master release.  It might fix the problem you're seeing.

**Comment by jano42** [comment]
I've reproduced it with an updated Blockl version (using 6e5f9b77f6ad6368865cd35b41c7bc18f5af9297)

The workaround provided by @CarbonMan works fine !

**Comment by rachel-fenichel** [comment]
https://github.com/google/blockly/pull/1483 should fix this.  I'm just waiting on some comments.

**Comment by Bohdan-Tereta** [comment]
Hi, I've got some idea of improved solution, see my comment here: 
https://github.com/google/blockly/pull/1483#issuecomment-381638639

**Comment by samelhusseini** [comment]
This is fixed.
