### ISSUE TITLE
multiple setWarningText() calls while dragging only work on the last call

### ISSUE THREAD

**Issue by NAllred91** [google/blockly#1365]
### Problem statement

- [x] Bug report
- [ ] Feature request

When the `create` event fires, if the created block is one of certain types I hold unto that block and evaluate if I have duplicates.  If I do, I call `block.setWarningText()` on each duplicate.

When the `create` event is fired because the user created a new block from the toolbox, then the first calls to `block.setWarningText()` have no effect.

When the `create` event is fired because the user duplicated a block, the calls to `block.setWarningText()` all work.

This seems to be because when you create a block from the toolbox, the block is being dragged.  That means `this.workspace.isDragging()` returns true for the first call to `block.setWarningText()` and then the second call to `block.setWarningText()` clears the first timeout.
https://github.com/google/blockly/blob/81dcdcb287e7027450336c74a104e8438e23e364/core/block_svg.js#L1142

### Expected Behavior

I'd expect to be able to iterate over an array of blocks and call `block.setWarningText()` on all of them and not have the last call wipe out all the previous calls.

### Additional Information

This code snippet briefly explains this situation.  Using this code you get different results if you create a new block from the toolbox or if you duplicate a block.

Creating a new block from the toolbox results in one block having the warning.
Duplicating an existing block results in both blocks having the warning.
```
var blocks = []
this._workspace.addChangeListener((event) => {
            if(event.type === 'create') {
                var block = this._workspace.getBlockById(event.blockId)
                if(block.isEventBlock) {    // Some way to determine if the block is the type you're looking for
                    blocks.push(block)
                    checkForDuplicates()
                }
            }
})

var checkForDuplicates = () => {
    if(blocks.length > 1) {
        blocks.forEach(block => block.setWarningText('You are a duplicate', 'duplicate_block'))
   }
}
```

**Comment by NAllred91** [comment]
If I give each warning a unique id, like 'duplicate_block1', 'duplicate_block2' then all of the blocks get their warnings set correctly.  But this seems like a hacky way to get around this problem.

**Comment by rachel-fenichel** [comment]
What do you mean by "the second call to `block.setWarningText()`?  

From your code snippet it looks like `setWarningText` should be called once per block.  

The database of warning PIDs is per-block, so followup calls to `setWarningText` on other blocks shouldn't be causing the original block's timeout to get canceled.

Similarly, using ids for the warnings is supposed to be for when there are multiple warnings on a block, not multiple warnings on the workspace.  It looks like the pid_ object is in the wrong place somehow.

**Comment by rachel-fenichel** [comment]
Oh I see--the `pid_` object is on the `setWarningText` function, so it's being shared between blocks.

**Comment by NAllred91** [comment]
Sorry, that wasn't too clear.

I call `setWarningText` on the first block, then call `setWarningText` on the second block.  That is what I meant by the second call.

But yea, it looks like you figured out what I was describing here!

**Comment by rachel-fenichel** [comment]
Yeah, I see the problem now.  I'll add it to my list :)

**Comment by rachel-fenichel** [comment]
Fixed.  Thanks for the detailed repro steps + code.
