### ISSUE TITLE
typeof in XML

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1368]
These two lines are broken:
https://github.com/google/blockly/blob/master/core/xml.js#L501
https://github.com/google/blockly/blob/master/core/xml.js#L600

A minor issue is that the style guide states that `typeof` is not a function and that the argument should not be in parens (unless needed for other reasons).
https://google.github.io/styleguide/jsguide.html#formatting-grouping-parentheses

A more major issue is that `typeof` can never return `undefined`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

**Comment by rachel-fenichel** [comment]
`          if (typeof(type) !== undefined && type !== null) {`

I can just replace that with `if (type) {`, right?

**Comment by NeilFraser** [comment]
Since this is a check on the results of [getAttribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute), then the values to be avoided are null and empty string, while the values to be trapped are non-empty strings.  So yes, `if (type) {` should be perfect.

**Comment by rachel-fenichel** [comment]
The empty string is a valid type.  Checking `if (type != null) {` seems to do the trick (and make all tests pass).
