### ISSUE TITLE
Block grab displacement and page scrolling

### ISSUE THREAD

**Issue by carlosperate** [google/blockly#137]
When the blocks are grabbed their moving position within the workspace is calculated based on mouse displacement, essentially keeping both the mouse icon and block displayed together. This relationship is broke if the page is scrolled during a grab as the workspace itself moves but the block position within the workspace stays the same.

Made a quick video illustrating the issue: https://youtu.be/_hvstVFbu-s
This case shows the scrolling done when the mouse leaves the page viewport, as it is a more likely scenario than somebody grabbing a block and using the mouse wheel, pressing home/end/page up/down etc, but all cases have the same result.

**Comment by NeilFraser** [comment]
This has just been fixed in the pr/125 branch.  Hoping to merge this with master soon.

**Comment by carlosperate** [comment]
Great, looking forward to try the zooming feature on master!
