### ISSUE TITLE
Function arguments: Disallow duplicate var names

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1377]
Blockly currently allows (with a warning) a user defined function to have duplicate variables names when there are multiple function arguments. This is not allowed in any language other JavaScript, and no longer allowed with strict mode.

We should upgrade the warning to a full error, or otherwise disallow it.

One possibility is to disable the second (or later) duplicate argument blocks in the mutator UI. Like the break block when outside of a loop, it could include a warning icon and message about why it was disabled.

**Comment by NeilFraser** [comment]
+1

The Blockly philosophy is "Just say no to syntax errors."  Duplicate function arguments is currently the only way (other than in non-strict JavaScript) to get a syntax error from Blockly.  It should simply not be possible to do this.

One solution would be to disable the function argument block in the mutator when a duplicate name is provided.  Like the way break blocks disable (with an explanatory warning) when outside of a loop.

Another solution would be to auto-correct the duplicate to something valid (e.g. x -> x2).  Like the way number fields allow you to type anything, but always resolve to a legal number upon loss of focus.

**Comment by rachel-fenichel** [comment]
I like the second option.  I prefer automatically doing something reasonable, rather than just putting an error and stopping.

**Comment by JonasKnerr** [comment]
this issue should be closed now, or?

**Comment by rachel-fenichel** [comment]
I'm not sure if we implemented the solution yet.  Can you check what the current behaviour is and let me know?

**Comment by moniika** [comment]
![07b024bb-9f60-4141-b9e9-f084f01ea149](https://user-images.githubusercontent.com/6621618/65725816-6196bc80-e068-11e9-98a9-df83acb080c7.gif)
