### ISSUE TITLE
Pull toolbox performance improvements back from scratch-blocks

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1378]
This is a place to keep track of the toolbox/flyout performance improvements made directly to scratch-blocks that we should back port to blockly.

First one: https://github.com/LLK/scratch-blocks/pull/1166 

There will likely be others over the couple few weeks.

**Comment by picklesrus** [comment]
Another one: https://github.com/LLK/scratch-blocks/commit/54bf2d6b62b69a107ea49142350c3a8b12caa6e8

**Comment by picklesrus** [comment]
Another one: https://github.com/LLK/scratch-blocks/pull/1438

**Comment by BeksOmega** [comment]
All of these have either been implemented, or are no longer relevant.
