### ISSUE TITLE
Comment is not works in latest Chrome

### ISSUE THREAD

**Issue by thuanhan** [google/blockly#1382]
My Chrome version:

Google Chrome is up to date
Version 62.0.3202.62 (Official Build) (64-bit)

I fill a long text in comment and then close & reopen this comment again.
The comment is screw up that I can't see the text area.

**Comment by CleoQc** [comment]
Oh thank you! I thought I had killed the comments! 
I'm getting the same behaviour

**Comment by CleoQc** [comment]
Looks like I can't edit on a cell phone. I never got mine to behave at all though

**Comment by picklesrus** [comment]
Separated out the editing issue into https://github.com/google/blockly/issues/1384 since I think that'll be a different fix.  Quick summary on that one is that the keyboard just doesn't seem to pop up on mobile unless you just opened the comment.

**Comment by rachel-fenichel** [comment]
The issue with long comment text making the text disappear looks like it's a chrome bug with handling foreignObjects.

**Comment by thuanhan** [comment]
In my case with very long comment, the issue is worse than the bubble doesn't resize itself.
![comment_issue](https://user-images.githubusercontent.com/20550115/31976923-8fe142d6-b964-11e7-957f-32a4a1aafdd6.jpg)

That I can't close or move the comment.
I think it's a chrome bug because it works fine in Firefox.

**Comment by AnmAtAnm** [comment]
Additional details and an example in #1690.

**Comment by BeksOmega** [comment]
Could not reproduce.
