### ISSUE TITLE
Clicking on an open comment bubble on mobile does not bring up the keyboard

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1384]
### Problem statement

Clicking on an open comment bubble on mobile does not bring up the keyboard which makes the comment appear un-editable.  Separating this out from discussion on https://github.com/google/blockly/issues/1382

- [x] Bug report
- [ ] Feature request

### Expected Behavior

Clicking inside the comment bubble should bring up the keyboard on mobile so you can change the contents.

### Steps to Reproduce
1. Long press on a block in the workspace.
2. Choose add comment.
3. Type in the comment box
4. Click somewhere else in the workspace
5. Click inside the comment bubble again
6. Notice that the keyboard doesn't pop up.

### Operating System and Browser

- [ ] Desktop:  Fine on Desktop!

- [x] Smartphone/Tablet/Chromebook (please complete the following information):
  - Device: [Nexus 7]
  - OS: [Android 4.4]
  - Browser [Chrome]

**Comment by gonfunko** [comment]
Unable to repro on iOS or Android, closing accordingly.
