### ISSUE TITLE
{textVariable} and {listVariable}

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1386]
Blockly [code demo](https://blockly-demo.appspot.com/static/demos/code/index.html) shows {textVariable} and {listVariable} in blocks.

Develop, master and production.  Chrome and FF.

<img width="253" alt="screen shot 2017-10-24 at 15 20 39" src="https://user-images.githubusercontent.com/250480/31971033-0f31c128-b8cf-11e7-98ef-6b015b62e867.png">
<img width="234" alt="screen shot 2017-10-24 at 15 20 50" src="https://user-images.githubusercontent.com/250480/31971034-0f4c2d56-b8cf-11e7-8a28-2c56a2ec4706.png">

**Comment by AnmAtAnm** [comment]
Looks like regression from #1028. Updating the mechanism used for category tab names, not realizing the old mechanism handled these other cases.
