### ISSUE TITLE
Can't disable if-return block inside procedure definition

### ISSUE THREAD

**Issue by vicng** [google/blockly#1390]
### Problem statement

- [x] Bug report
- [ ] Feature request

An "if-return" block can't be disabled once it's connected to a procedure block.

### Expected Behavior

It should be disabled.

### Actual Behavior

It remains enabled.

### Steps to Reproduce

1) Drag procedure definition into block to workspace.
2) Connect if-return block to it.
3) Right-click on the if-return block and select "Disable block".

### Stack Traces

No errors in console.

### Operating System and Browser

- [x] Desktop:
  - [ ] Chrome
  - [ ] Firefox
  - [x] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

**Comment by samelhusseini** [comment]
I think for this we should add a ``canBeDisabled`` property on a ``Blockly.Block``, and only show the context menu if that property is true. The procedures_if_return block should set ``canBeDisabled`` to false.

**Comment by johnnesky** [comment]
Fixed by: https://github.com/google/blockly/pull/7958
