### ISSUE TITLE
Should not be able to enable if-return block outside of procedure definition

### ISSUE THREAD

**Issue by vicng** [google/blockly#1392]
### Problem statement

- [x] Bug report
- [ ] Feature request

The "Enable block" context menu option should be disabled when the if-return block is not connected to a procedure definition block.

### Steps to Reproduce

1) Add if-return block to workspace
2) Right-click the block. The "Enable block" option is selectable.

**Comment by samelhusseini** [comment]
More or less the same as https://github.com/google/blockly/issues/1390. 

I think for this we should add a canBeDisabled property on a Blockly.Block, and only show the context menu if that property is true. The procedures_if_return block should set canBeDisabled to false.

**Comment by johnnesky** [comment]
Fixed by: https://github.com/google/blockly/pull/7958
