### ISSUE TITLE
Fix Blockly.Msg.TEXT_CHARAT_TITLE

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1397]
PR #1163 broke `Blockly.Msg.TEXT_CHARAT_TITLE` in two different ways:

First, the message doesn't parse correctly.  For example:
Blockly.Msg.TEXT_CHARAT_TITLE = "IN TEXT %1 X %2 Y";
Renders as:
<img width="281" alt="screen shot 2017-10-26 at 15 03 29" src="https://user-images.githubusercontent.com/250480/32083309-9f25ad8c-ba76-11e7-95a6-673d23c9d585.png">
Note that 'X' is lost, and Y is in front of %1. I'm also not sure what the %1 and %2 represent, since if they are reversed the block's inputs are unchanged (though different text is lost).

Second, existing translations were destroyed.  English is currently leaking into these languages.  These messages need to be resurrected, as seen in PR #1396.  I've fixed the other two messages that were destroyed in #1163, but TEXT_CHARAT_TITLE has structural issues that must be resolved first.

**Comment by RoboErikG** [comment]
When I converted these into JSON I had to update the string structure, but it looks like I missed some pieces in other languages in the mutator. I'll take a look to figure out how I can preserve X and Y when mutating.

**Comment by RoboErikG** [comment]
Fixed in develop

**Comment by RoboErikG** [comment]
Not fixed for compiled blockly.
