### ISSUE TITLE
Toolbox with Categories doesn't reflow correctly

### ISSUE THREAD

**Issue by acbart** [google/blockly#141]
If you expand content above a Blockly Toolbox with categories, then the Toolbox doesn't reflow with the canvas. If you click anywhere on the canvas, it immediately corrects the visual bug.

![image](https://cloud.githubusercontent.com/assets/897227/8922863/f762f63c-34b6-11e5-8a06-69397ddfed02.png)

Reproduce:
Go to the following blockly demo: 
https://blockly-demo.appspot.com/static/demos/toolbox/index.html
Run the following console command:
> document.body.insertAdjacentHTML( 'afterbegin', '\<div id="myID">...</div>' );

Notice that this bug does not occur with the toolbox sans categories:
https://blockly-demo.appspot.com/static/demos/fixed/index.html

**Comment by carlosperate** [comment]
If you are editing the canvas dynamically you should probably fire the resize event so that Blockly can recalculate the toolbox position, which is just an inject `div` into the DOM.

```
Blockly.fireUiEvent(window, 'resize')
```

**Comment by acbart** [comment]
I'm not editing the canvas, I'm editing content that's before the Blockly instance entirely (in fact, at the very start of the body). For example, the student receives feedback on their current progress, which is placed above the Blockly instance and can sometimes span one or more lines. This bumps the Blockly instance down, but not the toolbox.

Firing the event manually does trigger the redraw, but that's a rather cumbersome requirement - whenever anything placed before the Blockly instance grows, I need to know about it and fire off that event?

**Comment by carlosperate** [comment]
Sorry, I meant the HTML DOM, not the canvas.

The thing is that the toolbox has got absolute positioning, and it is injected at the end of body, so right now the only way to work around this is to recalculate it's position, by firing the resize event, if the rest of the page changes.

@NeilFraser Since the `Blockly.inject` function takes an HTML element to inject blockly, could that element also be used to nest `blocklyToolboxDiv`?

**Comment by NeilFraser** [comment]
@carlosperate The toolbox used to be injected next to the SVG, until 19 May 2015, when it was moved to the end of the document.  Here is the offending commit:
https://github.com/google/blockly/commit/6fdab711b26c8418cce70d1d6df32df88269a657
The commit message is "Fix several RTL bugs.", though I don't immediately see what bug moving the toolbox might have solved.

I don't really feel like exploring that rabbit hole all over again.  So I'll close this bug by confirming that Blockly.fireUiEvent(window, 'resize') is the correct solution.

**Comment by acbart** [comment]
Thanks for spotting me that commit. I undid its changes, and everything seems to be working just how I want it! Someday when I want RTL support, I'll have to revisit this, but for this semester, I'm a happy camper!

**Comment by slyfox75** [comment]
Thx
