### ISSUE TITLE
Permanent connection hints after failed connection.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1416]
If a block was dragged so that it was both over a delete area (trash or toolbox) AND it also happened to be in a place where a connection with another block was possible, the behaviour used to be the safe option: cancel the deletion, and make the connection.  This original behaviour can be experimented with in Blockly Games, Maze, Level 4:
https://blockly-games.appspot.com/maze?level=4

However, the current behaviour is to delete the block, and permanently highlight the connection that was offering to connect:
https://www.youtube.com/watch?v=_Az_08HyikU

**Comment by rachel-fenichel** [comment]
On Blockly games:
![9c78be92-9bc0-426b-a055-d5e21f248217](https://user-images.githubusercontent.com/13686399/32355112-1c6e4c5e-bfea-11e7-8678-81520e751158.gif)

**Comment by rachel-fenichel** [comment]
Deleting the block is deliberate.  We made the workspace slide behind the flyout instead of in front, so it should be clearer whether the user is dragging over the toolbox or the workspace.

Perma-highlighting is definitely not deliberate.
