### ISSUE TITLE
Block bumping is gone.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1417]
If one tries to connect two blocks that have different typed connections, Blockly currently does nothing: 
![b668dbde-c592-4705-8e41-8118bb12a39b](https://user-images.githubusercontent.com/250480/32357340-1873b33c-bff9-11e7-9be4-0d5d5bbb178c.gif)

However, it used to bump one of the blocks away, so that there was no ambiguity: 
![8bae687e-d50d-40da-92a9-5f400c50f962](https://user-images.githubusercontent.com/250480/32357294-be5862d0-bff8-11e7-8faa-40dad7ce28cb.gif)

Block based languages are supposed to eliminate syntax errors.  This is a visual syntax error.

**Comment by NeilFraser** [comment]
Note that the Code demo and the Playground both have grid snapping enabled which can sometimes result in behaviour similar to block bumping.

**Comment by picklesrus** [comment]
Fixed on develop
