### ISSUE TITLE
code generation breaks for blocks with empty next statements

### ISSUE THREAD

**Issue by yoderjen** [google/blockly#142]
Found this playing with the "code" demo I downloaded yesterday.  If you have a block that can have a statement attached to it (like the if block, the loop blocks, the function blocks), but the statement block is empty (just pull an if block and don't add anything to it, for example) , blockly/code/generator.js  fails at line 244
  goog.asserts.assertString(code,
      'Expecting code from statement block "%s".', targetBlock.type);
because it is trying to get the "type" of targetBlock, which does not exist, so you get the error

     Uncaught TypeError: Cannot read property 'type' of null

**Comment by NeilFraser** [comment]
Fixed.  Thanks!
