### ISSUE TITLE
Text/Number/Angle inputs offscreen in RTL

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1421]
Go to:
https://blockly-demo.appspot.com/static/demos/rtl/index.html
Click on '256'.
Expected: Edit box should appear on the block.
Actual: Edit box appears at left edge of browser.

Also affects angle inputs.
<img width="690" alt="screen shot 2017-11-03 at 15 06 39" src="https://user-images.githubusercontent.com/250480/32397812-ed5e494a-c0a8-11e7-8b65-e1eda5131769.png">

**Comment by rachel-fenichel** [comment]
Fixed by #1427
