### ISSUE TITLE
Flyout buttons not right-aligned in RTL.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1424]
<img width="331" alt="screen shot 2017-11-03 at 16 51 58" src="https://user-images.githubusercontent.com/250480/32399918-713ccb66-c0b7-11e7-9974-763c0ef3dd69.png">

**Comment by microsoftsam** [comment]
Dupe of https://github.com/google/blockly/issues/1208

**Comment by rachel-fenichel** [comment]
Closed as dupe.
