### ISSUE TITLE
Multiple errors of drawing blocks

### ISSUE THREAD

**Issue by deser** [google/blockly#1429]
### Problem statement

- [x ] Bug report
- [ ] Feature request

### Expected Behavior

Blocks should be shown corectly

### Actual Behavior

Here are some cases when blocks are drawn incorrectly:

1. Compare different types via generic logic block:
https://monosnap.com/file/IIaJg3nNhooEJI1VUpedBSd42mPs8Y
https://monosnap.com/file/vNFnRf66iRWKC6JzVgXtoB6yyLgIWb

### Steps to Reproduce

Here is saved workspace:
```xml
<xml><variables></variables><block type="logic_compare" id="v%swFmm?tnhTFRkeFY}T" x="-1870" y="-1190"><field name="OP">EQ</field><value name="A"><block type="fields_textedit" id="kTat(n2vpC4-^ZfJ,;gb"><field name="FIELD">b54405cb-9a4e-4aea-83e3-72fd3bd41a45</field></block></value></block><block type="fields_numberedit" id="Vvo/QZj@t4|Cum^XRbBr" x="-1486" y="-1184"><field name="FIELD">b54405cb-9a4e-4aea-83e3-72fd3bd41a45</field></block></xml>
```

### Actual Behavior
Condition block doesn't work correctly with loops:
https://monosnap.com/file/TwbeFjV90v4dDNSDEmZyYBpyJMfYcB

(video) http://recordit.co/3bhxJfM6vc

### Operating System and Browser

- [ ] Desktop:
  - [x] Chrome
  - [] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

**Comment by NeilFraser** [comment]
The bug here is that block bumping was broken, leading to visual syntax
errors.  Block bumping has already been fixed on 'develop'.  Issue #1417.

**Comment by deser** [comment]
Thanks for quick answer. How I can get it on `production`?

**Comment by RoboErikG** [comment]
We typically push to master about once a month. We're running a bit late with this month's push, though. It should go through in the next couple weeks.
