### ISSUE TITLE
field_image makes message not centered

### ISSUE THREAD

**Issue by NAllred91** [google/blockly#1430]
### Problem statement

- [x] Bug report
- [ ] Feature request

When you increase the height and width of a field_image, the "message" text remains near the top of the block and is not vertically centered.

### Expected Behavior

I think as you make the field_image larger, the "message" text should remain vertically centered in the block.

### Actual Behavior

![not_centered](https://user-images.githubusercontent.com/8683908/32505021-2b02cf06-c3af-11e7-99b4-5c2f9a112a59.jpeg)

### Steps to Reproduce

In this screenshot you can see that the text is not centered with the image.  In this case, my jsonInit looks like this:
```
this.jsonInit({
            'message0': '%1 %2 On Collision' + ' %3 %4',
            'args0': [
               {
                   'type': 'field_image',
                   'src': 'src/test/Asset.svg',
                   'width': 30,
                   'height': 30
               },
                {
                    'type': 'field_dropdown',
                    'name': 'DEVICE',
                    'options': getDeviceOptions
                },
                {
                    'type': 'input_dummy',
                },
                {
                    'type': 'input_statement',
                    'name': 'STATEMENT',
                },
            ],
            'colour': '#252E31',
        })
```

### Operating System and Browser
Mac 10.12.6
- [x] Desktop:
  - [x] Chrome, 62.0.3202.75
  - [ ] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

**Comment by NeilFraser** [comment]
Note that once this is 'fixed', someone will file a bug that "field_image makes message no longer aligned to top of block".  http://www.gifbin.com/986088

**Comment by NAllred91** [comment]
@NeilFraser That is fair.  Perhaps there could be a way to indicate that you want the message centered in the block?  Maybe the default behavior should stay the same, but we can provide an option to center the message?

**Comment by NAllred91** [comment]
@NeilFraser @rachel-fenichel My team is interested in trying to come up with a solution to this problem.  Do you have any guidance on what you'd expect a solution for this to look like?

It seems like we want the current behavior to remain the default behavior.  Should we add a property like `centerMessage0: true` to the jsonInit object?  Or is there a better way you would like this to be solved?

**Comment by NeilFraser** [comment]
I'd think that options should at a minimum include align top, align centre, and align bottom (after all, horizontal alignment includes all three).  Note that the horizontal label is "CENTRE", so it would be best to use a consistent spelling.  And this issue seems to overlap with https://github.com/LLK/scratch-blocks/issues/1221.  Input should also be obtained from the iOS and Android developers, to ensure that whatever is proposed is possible on their platforms.  Just my 2¢.

**Comment by rachel-fenichel** [comment]
I'm open to doing this, so let's talk about how we would include it in the JSON spec for a block.

I agree with Neil that we should have `top`, `center`, and `bottom` options.  I don't have a strong opinion about the spelling of center, but I agree that we should be consistent with the existing options.

On a block with external inputs, would the alignment be per-row?  On the same block with internal inputs, what would the alignment look like?
Or should we take the simple route and specify it on the whole block only?

**Comment by rachel-fenichel** [comment]
@NAllred91 thoughts on the implementation?

**Comment by NAllred91** [comment]
@rachel-fenichel 

![block](https://user-images.githubusercontent.com/8683908/33022302-bbe5834c-cdd2-11e7-860e-d83ce7fd0031.jpeg)

For a block like this, if you added an icon to the front of the block and set `align: 'centre'` I think I would expect `repeat`, the `10` block, and `times` to all be centered.  I think that is what you meant by "same block with internal inputs"?

For blocks with external inputs, maybe if you want different alignment per row you would need to use `args0` and `args1`

```
{
  "type": "block_type",
  "message0": "Line 1 %1",
  "message1": "Line 2 %1",
  "args0": [
    {
      "type": "input_value",
      "name": "NAME"
    }
  ],
  "args1": [
    {
      "type": "input_value",
      "name": "NAME"
    }
  ],
}
```

Then if you wanted to specify different alignments you could do
```
{
  "type": "block_type",
  "align0": "centre",
  "align1": "top",
  "message0": "Line 1 %1",
  "message1": "Line 2 %1",
  "args0": [
    {
      "type": "input_value",
      "name": "NAME"
    }
  ],
  "args1": [
    {
      "type": "input_value",
      "name": "NAME"
    }
  ],
  "tooltip": "",
  "helpUrl": "http://www.example.com/"
}
```

**Comment by BeksOmega** [comment]
This is handled in the thrasos renderer. If you care about the baseline, you can customize it in your renderer.
