### ISSUE TITLE
Allow a block to restrict the maximum number of instances allowed in the workspace.

### ISSUE THREAD

**Issue by NAllred91** [google/blockly#1435]
### Problem statement

- [ ] Bug report
- [x] Feature request

On a block object, can we add `setDuplicatable` and `isDuplicatable` methods?  This would be similar to `isMovable` and `setMovable`.
### Expected Behavior

If you `setDuplicatable` to false, the block can't be duplicated.  I'm not sure what the behavior would be if you had a block that is allowed to be duplicated that has a child that is not allowed.  I would think that if any of the selected blocks are not allowed to be duplicated then the selection cannot be duplicated.

**Comment by NeilFraser** [comment]
Note that non-deletable blocks are not duplicatable.

**Comment by NAllred91** [comment]
@NeilFraser That is working for one of my blocks.  I have a block that always exists in the workspace and it does not have an option to be duplicated.

These other blocks are optional event blocks, where the user may or may not want to use all of them, but should only be able to use one block of each type.

I'm using @rachel-fenichel's suggestion from here https://groups.google.com/forum/#!topic/blockly/pSaLjq30tUg which is does allow me to disable the block in the toolbox, but still gives the user the option to create more of the blocks by using the "Duplicate" option.

**Comment by NeilFraser** [comment]
Good points.  My concern though is that implementing this exactly as specified hits one specific use case rather than the general case.  `setDuplicatable` and `isDuplicatable` are only useful for the case where there is a maximum of one block allowed.  A more general solution for a maximum of 'n' blocks would be nice.

As it happens, I was facing a similar problem earlier today: I needed a maximum of four start blocks on a multi-threaded application.  My solution was this:

```
var disableExtraStarts = function(e) {
  var maxStarts = 4;
  if (e instanceof Blockly.Events.Create) {
    var startBlocks = [];
    var blocks = workspace.getTopBlocks(false);
    for (var i = 0, block; block = blocks[i]; i++) {
      if (block.type == 'start') {
        startBlocks.push(block);
      }
    }
    if (maxStarts < startBlocks.length) {
      // Too many start blocks.  Disable any new ones.
      for (var i = 0, id; id = e.ids[i]; i++) {
        for (var j = 0, startBlock; startBlock = startBlocks[j]; j++) {
          if (startBlock.id == id) {
            startBlock.setDisabled(true);
          }
        }
      }
    }
  } else if (e instanceof Blockly.Events.Delete) {
    var startBlocksEnabled = [];
    var startBlocksDisabled = [];
    var blocks = workspace.getTopBlocks(true);
    for (var i = 0, block; block = blocks[i]; i++) {
      if (block.type == 'start') {
        (block.disabled ? startBlocksDisabled : startBlocksEnabled).push(block);
      }
    }
    while (maxStarts > startBlocksEnabled.length && startBlocksDisabled.length) {
      // Enable a disabled start block.
      var block = startBlocksDisabled.shift();
      block.setDisabled(false);
      startBlocksEnabled.push(block);
    }
  }
};
workspace.addChangeListener(disableExtraStarts);
```

**Comment by NAllred91** [comment]
@NeilFraser If I'm reading this correctly, in your case the user will still have the option to duplicate a block, but if you've exceeded the maximum it creates a disabled block.  Then, if you delete a block it then enables one of the previously disabled blocks?

But doesn't the user still have the option to enable one of the disabled blocks?  It looks like you're only dealing with the Create and Delete event, but when you enable a disabled block it fires a Change event.

I agree though.  Would it be possible to add something to the `jsonInit` object that specifies the maximum amount of instances allowed?

**Comment by NeilFraser** [comment]
Correct.  My particular application has `'disable': true` in the config, so users can't reenable a disabled block.  But trapping the Change event would allow this configuration option to be enabled.

A maximum instance number would be quite helpful in that it could selectively disable blocks in the toolbox, disable menu options, and disable the clipboard so users don't end up with disabled blocks on the workspace.  I'll edit the title of this issue to make it more general.

**Comment by NAllred91** [comment]
That sounds good.

My current example is [https://activities.parrot.com/blockly](here).  I have an event block for the battery level of the drone, but I only want the user to be able to add that event once.  In my case, if they duplicate it and add more my code should just ignore all but one...  So it is currently a bit of an edge case, but still not good.  I'll look into using `'disable':true` and your solution tomorrow for a short term solution.
