### ISSUE TITLE
Integrate i18n translations for Tamil language

### ISSUE THREAD

**Issue by arcturusannamalai** [google/blockly#144]
Request to Integrate i18n translations for Tamil language based on my work at Transifex.

**Comment by NeilFraser** [comment]
We have an apparently good set of Tamil translations from Translatewiki:
  https://github.com/google/blockly/blob/master/msg/json/ta.json
Can you clarify what you wish us to do?  Thanks!

**Comment by arcturusannamalai** [comment]
Neil - I'm one of the authors of the translation and the first to get started at that; I'm just curious if the translations had made into the main codebase. 

From your link, and I did not know that prior, I can see the translation is integrated into the main code. You may close this issue.

Thanks.
-Muthu

**Comment by NeilFraser** [comment]
What would be helpful would be Tamil translations for this file:
https://github.com/google/blockly/blob/master/demos/code/msg/en.js
That way we could add Tamil as an option here:
https://blockly-demo.appspot.com/static/demos/code/index.html

Either submit a PR for ta.js in that directory, or just paste your translations into this issue and I'll be happy to create the file.  Thanks!

**Comment by arcturusannamalai** [comment]
Sounds good - I will keep this task on my radar and get it sorted out.
Thanks!
