### ISSUE TITLE
text_charat mutator is unable to load generator tests.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1444]
### Problem statement

Bug in generator tests:
`Blockly.Constants.Text.TEXT_CHARAT_MUTATOR_MIXIN.mutationToDom(..)` fails to load [`tests/generators/text.xml`](https://github.com/google/blockly/blob/develop/tests/generators/text.xml).

### Steps to Reproduce

1. Load [the latest version of the `text.xml`](https://raw.githubusercontent.com/google/blockly/34750bccd8a6a7e1513b7b0d494df5a3ca7afbeb/tests/generators/text.xml) or [`colour.xml`](https://raw.githubusercontent.com/google/blockly/34750bccd8a6a7e1513b7b0d494df5a3ca7afbeb/tests/generators/colour.xml) into the test harness.

### Stack Traces

```
index.html:145 TypeError: Cannot read property 'type' of null
    at Blockly.BlockSvg.mutationToDom (text.js:809)
    at Object.Blockly.Xml.blockToDom (xml.js:103)
    at Object.Blockly.Xml.blockToDom (xml.js:162)
    at Object.Blockly.Xml.blockToDom (xml.js:193)
    at Object.Blockly.Xml.blockToDom (xml.js:162)
    at Object.Blockly.Xml.blockToDomWithXY (xml.js:81)
    at new Blockly.Events.Create (events.js:465)
    at Object.Blockly.Xml.domToBlock (xml.js:482)
    at Object.Blockly.Xml.domToWorkspace (xml.js:345)
    at fromXml (index.html:139)
```

### Operating System and Browser

Tested in...
 * Desktop Chrome

**Comment by RoboErikG** [comment]
And I get a Cross origin error for every test category... When did that break?

index.html:112 Failed to load file:///.../tests/generators/logic.xml: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by RoboErikG** [comment]
Found another way to test by trying to generate xml for the text_charat block when it doesn't have the second input.

**Comment by rachel-fenichel** [comment]
Cross origin error: if it's only for the generator tests, that's a known problem: https://developers.google.com/blockly/guides/modify/web/unit-testing#block_generator_tests
