### ISSUE TITLE
Can't add inputs to function in Toolbox demo

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1447]
### Problem statement

- [x] Bug report
- [ ] Feature request

### Expected Behavior

Should be able to add inputs to procedures in the toolbox demo.

### Actual Behavior

You get a js error
### Steps to Reproduce

1. Open the Toolbox demo.  
2. Open the "randomize" category
3. Drag random function to workspace
4. Click settings icon to open mutator bubble
5. try to drag a new input to the mutator workspace.

### Stack Traces
Error: <g> attribute transform: Expected '(', "translate[object Object]".
Blockly.BlockSvg.moveDuringDrag @ blockly_compressed.js:1301

Presumably when the js error happens, the block gets stuck. See screenhot: 
![screen shot 2017-11-14 at 2 35 37 pm](https://user-images.githubusercontent.com/15675877/32808809-350376aa-c949-11e7-84c9-baf9744afc10.png)

### Operating System and Browser

_Remove this hint: these checkboxes can be checked like this: [x]_

- [x] Desktop:
  - [x] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):

**Comment by rachel-fenichel** [comment]
Fixed by #1449 (verified on https://rachel-fenichel.github.io/blockly/demos/toolbox/index.html)
