### ISSUE TITLE
Step interpreter demo: Child blocks scatter when set block disconnected from parent 

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1448]
### Problem statement

Fireworks! Blocks are exploding! :)

- [x] Bug report
- [ ] Feature request

### Expected Behavior

![a9330987-f1a8-4739-a2c5-e31fdbf5cf07](https://user-images.githubusercontent.com/15675877/32809568-1f5bb2ec-c94c-11e7-8f76-18f34a2c4870.gif)

### Steps to Reproduce

1. Open up Step Interpreter demo.
2. Disconnect "set n" block from its parent.  
3. Watch them scatter! 

### Stack Traces

blockly_compressed.js:1297 Error: <g> attribute transform: Expected '(', "translate[object Object]".
Blockly.BlockSvg.setParent @ blockly_compressed.js:1297

### Operating System and Browser

_Remove this hint: these checkboxes can be checked like this: [x]_

- [ x] Desktop:
  - [x ] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):

### Additional Information

_Anything else we should know?_

**Comment by picklesrus** [comment]
Happens on Graph demo too

**Comment by NeilFraser** [comment]
It is a result of compiling the code.  Switching to uncompressed makes the bug vanish.  Firefox and Chrome have the same behaviour.

**Comment by rachel-fenichel** [comment]
I can get this error in the playground in LTR by switching to compressed.

I think it's in this code: 
```
/**
 * Set parent of this block to be a new block or null.
 * @param {Blockly.BlockSvg} newParent New parent block.
 */
Blockly.BlockSvg.prototype.setParent = function(newParent) {
  if (newParent == this.parentBlock_) {
    return;
  }
  var svgRoot = this.getSvgRoot();
  if (this.parentBlock_ && svgRoot) {
    // Move this block up the DOM.  Keep track of x/y translations.
    var xy = this.getRelativeToSurfaceXY();
    this.workspace.getCanvas().appendChild(svgRoot);
    svgRoot.setAttribute('transform', 'translate' + xy);
  }

  Blockly.Field.startCache();
  Blockly.BlockSvg.superClass_.setParent.call(this, newParent);
  Blockly.Field.stopCache();

  if (newParent) {
    var oldXY = this.getRelativeToSurfaceXY();
    newParent.getSvgRoot().appendChild(svgRoot);
    var newXY = this.getRelativeToSurfaceXY();
    // Move the connections to match the child's new position.
    this.moveConnections_(newXY.x - oldXY.x, newXY.y - oldXY.y);
  }
};
```
and I think the translation is being set wrong.

**Comment by rachel-fenichel** [comment]
My spider sense says it's this change: https://github.com/google/blockly/commit/8cedef49ac73de98a5d17a020c0013fb31c36207#diff-fd04c06f310c3ed628154e399e570c9cL255

**Comment by rachel-fenichel** [comment]
My stack trace from opening the loops category, then the math category, on the playground.  LTR, compressed:
![image](https://user-images.githubusercontent.com/13686399/32810446-c6be59a6-c94f-11e7-8314-8b15255c5918.png)


Looks like it happens when disconnecting a child block in a group and setting the parent to null, at least here.

**Comment by NeilFraser** [comment]
Found it.  String(xy) is coming back as "[object Object]" rather than "(1, 4)".

**Comment by NeilFraser** [comment]
My fault.  Preparing a PR.  Rachel's spider sense was right on the money.
