### ISSUE TITLE
How to set default option in block define with field_dropdown?

### ISSUE THREAD

**Issue by felix2ch** [google/blockly#1450]
For define a block using JSON format, I can set args0 type to "field_dropdown", and give it a option list. Then, the default value should be the first item in options. How to change it to other item?

Thanks for your help!

**Comment by RoboErikG** [comment]
Please ask questions on [the mailing list](https://groups.google.com/forum/#!forum/blockly) in the future.

You can change the default by adding a [field tag to the xml](https://developers.google.com/blockly/guides/configure/web/toolbox) with the default value you want.
