### ISSUE TITLE
Dropdown fields with a large number of options become unscrollable and get cut offscreen

### ISSUE THREAD

**Issue by vicng** [google/blockly#1454]
### Problem statement

- [x] Bug report
- [ ] Feature request

If you open a dropdown field with more options than the workspace can display, you cannot scroll the list and a portion of the list becomes inaccessible.

eg.
![screen shot 2017-11-16 at 5 20 13 pm](https://user-images.githubusercontent.com/13488389/32924642-7d0ecbde-caf2-11e7-9e7c-cfdd1643326d.png)

### Expected Behavior

The list should be scrollable and should automatically cap its own height size based on its positioning/workspace size/etc.

### Actual Behavior

The list is unscrollable and a portion of the list is cut off screen.

### Steps to Reproduce

Create a block with a dropdown field containing many options (eg. 20+) and add it to a workspace.

### Additional Information

Here's a hack workaround to fix the problem at the moment.

1) In `core/css.js`, add the following CSS property to `.blocklyDropdownMenu`:
`'max-height: 300px !important;'` 

2) In `core/field_dropdown.js`, add the following to the `positionMenu_` function:

```
...
var menuSize = Blockly.utils.uiMenu.getSize(menu);

if (menuSize.height > 300) {
  menuSize.height = 300;
}

if (this.sourceBlock_.RTL) {
...
```

**Comment by AnmAtAnm** [comment]
#1897 solved edges where the field is near the center of a page that is <600px high.
