### ISSUE TITLE
Make BlockSvg.setColour more efficient

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1456]
https://github.com/google/blockly/blob/develop/core/block_svg.js#L1037

BlockSvg's setColour forces a rerender of all fields to make sure that dropdowns get the right colours. 

Not every field needs to be rerendered (only those that care about the parent block colour).  Also, rerendering a field calls `render` on the source block, so there can be an accidental rerender of the entire stack.  We can probably avoid that by:
- disabling rendering on the source block before rerendering the fields
- tracking whether any fields were rerendered
- enabling rendering on the source block
- explicitly calling `render` on the source block if anything changed.

This is silly, but not a high priority because most blocks don't change colour regularly.

**Comment by BeksOmega** [comment]
@rachel-fenichel I can't think of any further work to do here. [Applying the color](https://github.com/google/blockly/blob/64aa3e7df40c35fd2a92c4a9e2edf4172196189d/core/block_svg.ts#L930) happens separately from rendering now (e.g. calling `setColour` on a block doesn't force a rerender). Also the rendering queue removes the need to ever disable + reenable rendering. So I think we're good! I'm going to go ahead and close.
