### ISSUE TITLE
quotes in 'text' field are not rendered properly 

### ISSUE THREAD

**Issue by microsoftsam** [google/blockly#1467]
### Problem statement

- [x] Bug report
- [ ] Feature request

Rendering of 'text' block has messed up quotes.

### Expected Behavior

Should render like so: 
<img width="418" alt="screen shot 2017-11-20 at 9 17 04 pm" src="https://user-images.githubusercontent.com/16690124/33056065-30425bce-ce38-11e7-98fb-8fa171c33067.png">

### Actual Behavior

<img width="388" alt="screen shot 2017-11-20 at 9 17 21 pm" src="https://user-images.githubusercontent.com/16690124/33056070-3a45f464-ce38-11e7-9048-32b886c79dd2.png">

### Steps to Reproduce

Open the "Text" category in the Blockly playground.html

### Operating System and Browser

- [x] Desktop:
  - [x] Chrome Mac
  - [ ] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):

### Additional Information

Only affects develop

**Comment by NeilFraser** [comment]
FYI, this is not the quotes that are at fault, this is the text field reporting that its width is 0.  At least that's been the issue all the previous this issue has appeared.

**Comment by microsoftsam** [comment]
Yeah, it doesn't seem to like the change to call forceRerender instead of setText: https://github.com/google/blockly/pull/1457/files

**Comment by rachel-fenichel** [comment]
Bummer.  The switch from setText to forceRerender was supposed to make it easier to fix the problems with setText/setValue.  I'll circle back to this after the holiday weekend.
