### ISSUE TITLE
variable type check issue

### ISSUE THREAD

**Issue by duzc2** [google/blockly#1468]
### Problem statement

- [x ] Bug report
- [ ] Feature request

_What were you trying to do when you hit this bug?  Or, what do you want to do with Blockly that your proposed feature would enable?_

### Expected Behavior
workspace.createVariable(name,type);
should add a variable with a type check enabled.

### Actual Behavior
after invoke workspace.createVariable(name,type);
the menu can't fly out , and errors output in console.

### Steps to Reproduce
just add a variable with opt_type : workspace.createVariable("abc","string");

### Stack Traces
![image](https://user-images.githubusercontent.com/564778/33093117-08a1eb84-cf37-11e7-80c8-c3db13e65ec4.png)
### Operating System and Browser

_Remove this hint: these checkboxes can be checked like this: [x]_

- [ x] Desktop:
  - [ x] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):

### Additional Information
when I try to add a variable on workspace , it invokes 
variables.js:338 Blockly.Variables.generateVariableFieldXml_(variableModel)
the function set a attribute 
element.setAttribute('variableType', variableModel.type);

and when I fly out the menu
xml.js:594 var type = xmlChild.getAttribute('variableType') || '';
type always be ''

from https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute
we should know Element.setAttribute(name, value);
 The attribute name is automatically converted to all lower-case when setAttribute() is called on an HTML element in an HTML document.

so that  xmlChild.getAttribute('variableType')  skip the "variabletype" attribute .

I think we need to use the attribute name all lower-case. variabletype

**Comment by rachel-fenichel** [comment]
Yes, we fixed this in https://github.com/google/blockly/pull/1422

Try updating to develop.  If the problem persists, reopen this issue.
