### ISSUE TITLE
Incorrect position computations -- blocks "pop out"

### ISSUE THREAD

**Issue by msprotz** [google/blockly#147]
Here's the second issue. The testcase is also at http://jonathan.protzenko.free.fr/t/editor.html

Happens on IE, not firefox and chrome.

STR:
- in "images", drag "scroll image" onto the workspace
- in "images", drag "create image" into "scroll image" and connect it in the hole
- in "basic", drag "pause" onto the workspace, connecting it *above* scroll image
- drag "scroll image" to disconnect it from "pause"

If the bug is not observed, keep doing:
- drag a fresh "pause" block and connect it *above* to "scroll image"
- drag "scroll image" to disconnect it from "pause"

Screenshot:
![blocks_misplaced](https://cloud.githubusercontent.com/assets/8306576/8428920/84aee69a-1f40-11e5-8be1-198fec85022a.jpg)

This is kind of tricky to reproduce -- let me know if you need extra information.

Thanks,

Jonathan

**Comment by NeilFraser** [comment]
> Happens on IE, not firefox and chrome.

Ooh, that's a problem.  For security reasons don't have physical access to Windows computers here (nor Windows in a virtual machine).
https://plus.google.com/+NeilFraserName/posts/dmh9rjBoRUr
My next conference will be in October...

**Comment by msprotz** [comment]
Ouch. I will also happen to be at that conference, so you can use my machine there, but we kind of need this fixed earlier than that... I guess I will need to look into it then. Thanks for the reply!

**Comment by msprotz** [comment]
Fwiw I just tried this after the zoom code landed and it doesn't help.

**Comment by NeilFraser** [comment]
I'm in the process of provisioning an air-gapped computer so that issues like this can be looked at on this end.  Should be running mid-September.  (You can report to your manager that you just increased Windows' sales by one unit.)

**Comment by msprotz** [comment]
That's great news!

**Comment by mstrycharski** [comment]
Hi Guys,
I think we had similar issue with blockly. The reason of that was regular expression used to calculate x and y of translation. IE in opposite to Chrome and Firefox saves X in translate expression in scientific notation (e.g. 8.67548e-017). In this case regular expression used in method Blockly.getRelativeXY_ fails and cannot access y value from translate(X,Y) expression.

Here is our (fixed) regular expression from this method:

/translate\(\s*([-\d.]+(?:e-?\d+)?)([ ,]\s*([-\d.]+)\s*\))?/

Hope this is the same issue and it helps you solve this.

**Comment by NeilFraser** [comment]
Interesting.  I've committed a modified regex:
https://github.com/google/blockly/commit/f81a5bd11ae64a4fade4db94fa3c0b175eae7263
Does this help?

**Comment by msprotz** [comment]
It does seem to help. I'm asking testers on my side to confirm.

**Comment by msprotz** [comment]
Yep apparently we're good. Thanks for the fix!
