### ISSUE TITLE
Create variable context menu appears in toolbox

### ISSUE THREAD

**Issue by kyleplo** [google/blockly#1470]
### Problem statement
- [x] Bug report
- [ ] Feature request

I was testing the variable category.
### Expected Behavior

The context menu for the set [variable] to [] and [variable] blocks only contains the "Help" options.

### Actual Behavior

The "create 'set [variable]'" option appears, and when click a set [variable] to [] block appears that cannot be moved.
![image](https://user-images.githubusercontent.com/31634240/33096211-35070f8c-ced4-11e7-9330-e8fd21972460.png)

![image](https://user-images.githubusercontent.com/31634240/33096264-616f2fd2-ced4-11e7-9660-715eb1897a2f.png)

### Steps to Reproduce

1. Open any blockly workspace with a variables category
2. Create a variable
3. Right click on either the set [variable] to [] or the [variable] block

### Stack Traces

No errors were found

### Operating System and Browser
- [x] Desktop:
  - [x] Chrome
  - [ ] Firefox
  - [ ] Safari
  - [ ] Opera
  - [ ] IE 10+
  - [ ] IE 11
  - [ ] EDGE

- [ ] Smartphone/Tablet/Chromebook (please complete the following information):
  - Device: HP Pavilion Desktop
  - OS: Windows 10
  - Browser: Chrome
  - Version: 62

**Comment by rachel-fenichel** [comment]
Good catch.  It looks like the new block is being created on the wrong workspace; at any rate the context menu is wrong.

**Comment by redmangospros** [comment]
True, i see this issue too
 And it looks like a error in the new block.
Whst said sbove

**Comment by duzc2** [comment]
#1481
