### ISSUE TITLE
Workspace comments

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1476]
Currently Blockly only has comments on blocks, which can be created through the right-click menu on a block.

Scratch has comments on the workspace and on blocks.  Comments can be dragged between blocks and the workspace.  We want the same thing.

The `comments` branch has some initial work here: workspace comments that can be freely dragged around the workspace.

More work we need to do:
- readonly
- events
- RTL
- scaling/scrolling
- block comments using new comment object
- workspace options: disabling comments
- dragging workspace comments to blocks
- dragging block comments to the workspace
- resize
- delete (#1662)
- collapse
- IE decisions
- selected state (how does that interact with Blockly.selected?)
- workspace comments in generators
- clean up dragging code/combine with block dragging code
  - Implemented in #1661 
- highlighting/unhighlighting
- disallowing comments in the flyout (may be based on workspace options)

testing:
- id conflict
- creation
- lookup
- deletion
- XML cycle

code cleanup!

Current plan is to:
- try to use the new comment object for block comments but not be able to drag between blocks and the workspace
- clean up dragging
- merge that into blockly
- then add dragging from blocks to workspace and back.

**Comment by BeksOmega** [comment]
Superseded by https://github.com/google/blockly-samples/issues/827
