### ISSUE TITLE
Icons aren't visible when the window size is less than 688px.

### ISSUE THREAD

**Issue by jamesbarrett95** [google/blockly#1479]
### Problem statement

Feature Request

### Expected Behavior

- An expandable drop-down menu for the language choices
- The icons in the bottom-right of the screen (trash, recentre zoom) could be made of absolute value to the canvas, so they can always be accessed; no matter what the width of the window is.
- Icons at the top-right of the screen (trash, share, run) next to 'Blockly > Demos > Code' when the window width is less than 688px.

### Actual Behavior

Icons aren't fully visible when the window size is less than 688px.
![image](https://user-images.githubusercontent.com/15526293/33175078-589d394c-d052-11e7-8d03-8661ff55f104.png)

### Steps to Reproduce

Resize the browser to a width of less than 680px

### Additional Information

This feature was requested as a friend of mine struggled to use the described icons on a mobile device.

**Comment by RoboErikG** [comment]
The main use for that demo is showing how code generators work, but it would be nice to clean it up so we aren't demoing poor handling of screen sizes.

**Comment by jamesbarrett95** [comment]
I'll tackle this feature and make a pull request soon.

**Comment by BeksOmega** [comment]
Closed by #3345
