### ISSUE TITLE
Update JSON docs to explicitly allow arrays for 'check'

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#148]
The implementation for parsing the 'check' field in JSON allows an array of strings or a string to be set as a check, but the documentation only talks about a single string. Should probably mention somewhere in the docs that arrays are also allowed. https://developers.google.com/blockly/custom-blocks/json-definition

**Comment by NeilFraser** [comment]
Mmm?
"`check` is a type string or an array of type strings. See [Type Checks](https://developers.google.com/blockly/custom-blocks/type-checks) for details."

**Comment by RoboErikG** [comment]
Ah, my bad. I'd been looking at the various examples and missed the spot where it's defined. =)
