### ISSUE TITLE
Iterating over xml is not working

### ISSUE THREAD

**Issue by surajnarwade** [google/blockly#1480]
```
var allXml = Blockly.Xml.workspaceToDom(workspace);
var allCode = [];
for (var i = 0, xml; xml = allXml[i]; i++) {
  var headless = new Blockly.Workspace();
  Blockly.Xml.domToWorkspace(xml, headless);
  allCode.push(Blockly.JavaScript.workspaceToCode(headless));
  headless.dispose();
}
```
for loop is not working

**Comment by blockly** [comment]
There is no need for the loop.  Just remove it.  XML is a tree structure,
not an array.

There is also no need for the headless workspace, you can generate
JavaScript straight from the main workspace.

>

**Comment by surajnarwade** [comment]
but official document is saying the same,
https://developers.google.com/blockly/guides/create-custom-blocks/block-paradigms

**Comment by blockly** [comment]
Whoa, that page is wrong.  The loop should be iterating over the XML's
child nodes.  And I think each of them would need to be wrapped in it's own
XML parent node.  Will look into it...

Also, this quote is obsolete:

A Blockly-specific problem is that there is (currently) no way to highlight
more than one block to indicate execution.

**Comment by surajnarwade** [comment]
@NeilFraser , can you point me towards documentation code, I will be happy to fix that :)

**Comment by NeilFraser** [comment]
@surajnarwade Unfortunately our doc sources live in Google's internal repo.

**Comment by surajnarwade** [comment]
@NeilFraser okay, thanks

**Comment by NeilFraser** [comment]
Here's code that works properly:
```
var xml = Blockly.Xml.workspaceToDom(workspace);
var topBlocks = [];
for (var i = xml.childNodes.length - 1, node; block = xml.childNodes[i]; i--) {
  if (block.tagName == 'BLOCK') {
    xml.removeChild(block);
    topBlocks.unshift(block);
  }
}
var allCode = [];
for (var i = 0, block; block = topBlocks[i]; i++) {
  var headless = new Blockly.Workspace();
  xml.appendChild(block);
  Blockly.Xml.domToWorkspace(xml, headless);
  allCode.push(Blockly.JavaScript.workspaceToCode(headless));
  headless.dispose();
  xml.removeChild(block);
}
```
