### ISSUE TITLE
Translation error in msg/js/fr.js

### ISSUE THREAD

**Issue by jlaurens** [google/blockly#1482]
line 285 of msg/js/fr.js reads:

/** @export */ Blockly.Msg.NEW_VARIABLE_TITLE = "Nouveau nom de la variable :";

the translation is inaccurate in that case. Instead, it should read

/** @export */ Blockly.Msg.NEW_VARIABLE_TITLE = "Nom de la nouvelle variable :";

Mathematically speaking, this illustrates the difference between "(new variable) name" and "new (variable name)", the former corresponding to the new translation and the latter to the old one.

:-)

**Comment by RoboErikG** [comment]
I've switched it to the [alternate translation on translate wiki](https://translatewiki.net/w/i.php?title=Special:Translate&group=out-blockly-0-all&language=fr&filter=&action=translate) which will pull it in next time they push to Blockly.
