### ISSUE TITLE
Cannot remove single block from a stack anymore.

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1485]
### Problem statement
Modifier key for removing a single block doesn't work anymore.

Basically we seem to have undone #809, likely in #1078.

### Expected Behavior

We should be able to remove one block from a stack using the modifier key.

Reported on mailing list: https://groups.google.com/forum/#!topic/blockly/RlEEBoK_RGc

**Comment by jpsangare** [comment]
any update?

**Comment by rachel-fenichel** [comment]
Still broken.  No timeline for a fix.  Happy to take pull requests.

**Comment by rachel-fenichel** [comment]
@samelhusseini

**Comment by rachel-fenichel** [comment]
Fixed by #1752
