### ISSUE TITLE
Build.py without Closure service

### ISSUE THREAD

**Issue by Immortalin** [google/blockly#1497]
Is it possible to use `build.py` with local closure compiler instead of the online service? The [online documentation](https://developers.google.com/blockly/guides/modify/web/advanced) only describes invoking the local closure compiler manually, without any mention of how to integrate it with the defautlt `build.py` build tool.

**Comment by rachel-fenichel** [comment]
You can write a wrapper script that calls build.py for everything but compressed blockly (using the [arguments](https://developers.google.com/blockly/guides/modify/web/building) for build.py), then runs your shell script to compile with the local compiler.  If you just want to build core blockly and not compile in any other code, the script for the second half will look something like this:

```
java -jar closure-compiler.jar --js='main.js' \
  --js='../**.js' \
  --js='!../externs/**.js' \
  --js='!../msg/messages.js' \
  --js='../../closure-library/closure/goog/**.js' \
  --js='../../closure-library/third_party/closure/goog/**.js' \
  --generate_exports \
  --externs ../externs/svg-externs.js \
  --compilation_level ADVANCED_OPTIMIZATIONS \
  --dependency_mode=STRICT --entry_point=Main \
  --js_output_file main_compressed.js
```

Please post questions like this on the [developer forum](https://groups.google.com/forum/#!forum/blockly) in the future.

**Comment by Immortalin** [comment]
@rachel-fenichel how is this usually done at Google? I.e. do you guys use build.py in your CI service or is it also done manually?

**Comment by rachel-fenichel** [comment]
We use build.py and the online compiler.  For continuous integration we don't tend to hit the rate limit, and we rarely need to do a full rebuild during development since we mostly work with uncompressed blockly.
