### ISSUE TITLE
variableTypes array ignored for initial variable

### ISSUE THREAD

**Issue by NAllred91** [google/blockly#1503]
### Problem statement
I believe this is a bug, although it could be possible I'm using this feature incorrectly.

In the following screen recording I have `w` set on the window as my active workspace.

You can see that at the start I have a variable named `Document` with type `doc`.  I then drag the document block into the workspace, delete the variable named `Document`, then drag the document block back into the workspace.  When I drag the document block into the workspace a second time, it creates a variable named `Document` with no type.
![typedvariables](https://user-images.githubusercontent.com/8683908/33782133-6c9771d6-dc25-11e7-8f71-12ee525be97f.gif)

This is the code for my document block.
```
    Blockly.Blocks['documentapp_create'] = {
        init: function() {
            this.jsonInit({
                'message0': 'Create Document Named %1 %2',
                'args0': [
                    {
                        'type': 'field_input',
                        'name': 'DocumentName',
                        'text': 'string',
                    },
                    {
                        'type': 'field_variable',
                        'name': 'NAME',
                        'variable': 'Document',
                        'variableTypes': ['doc'],
                    },
                ],
                'colour': '#823B2F',
                'inputsInline': true,
            });
        },
    };
```

This is code I run right after I inject blockly.
``` 
       this._workspace.registerButtonCallback('createDocument', () => {
            Blockly.Variables.createVariable(this._workspace, null, 'doc');
        });

        this._workspace.createVariable('Document', 'doc');
```

### Expected Behavior

I would expect my document block to always have variables of type `doc` in the dropdown, since I specified `doc` as the variable type.  I want to make sure that the variable dropdown never contains untyped variables.

If I leave the `variable` attribute blank in the `args0` array for my document block, dragging the block into the workspace causes a new untyped variable to be generated (`i`, `j`, `k`, etc...).

I've tried a few different strategies to ensure that the variables dropdown never contains untyped variables, but so far there seems to always be a way to get untyped variables into the dropdown.

**Comment by rachel-fenichel** [comment]
Right, the specific problem is that the variable field specification doesn't include a default type (only a default name) so if the variable doesn't exist, it's created with the empty type.

I noticed this in my recent variables work and filed https://github.com/google/blockly/issues/1499 for it.

More generally variables are currently identified by name + type instead of by ID, and type is assumed to be the empty string if not specified.  I've been working on that in https://github.com/google/blockly/pull/1495

**Comment by NAllred91** [comment]
Thanks,

For the time being, I guess the best solution is to always make sure that a variable with that default name always exists and is the type I want it to be?  That may lead to strange user experiences if the user tries to delete the variable, but at least I should be able to force my `Document` variable to always exist and have the correct type.

I didn't realize 1499 was pretty much exactly the issue I was seeing...  I'll subscribe to that and follow this issue there!

**Comment by rachel-fenichel** [comment]
For the time being you could disallow deleting the variable with that name, or otherwise make sure that the variable exists.  As typed variables are starting to get used more, we're finding and shaking out bugs like this.

I'll close this since you're watching the other issue.
