### ISSUE TITLE
Selectively use default name option in variable drop down field

### ISSUE THREAD

**Issue by NAllred91** [google/blockly#1506]
### Feature Request

I think that the default name (and default type when https://github.com/google/blockly/issues/1499 is resolved) option should only be used if there is no variable that exists with a type that is in the variableTypes array. If a variable does exist with a type that is in the `variableTypes` array, then use that variable as the default.

Otherwise, every time you drag one of these blocks into the workspace a new variable is created with the default variable name.

**Comment by NAllred91** [comment]
Or, if the default name field could be a function that returns the name of the default variable that would work as well.

**Comment by RoboErikG** [comment]
The [variables by id branch](https://github.com/google/blockly/tree/variables_by_id) has changes similar to this, though not as aggressive. The planned behavior is to make the blocks in the flyout track the workspace once the variable has been dragged out once (so renames will update the flyout).

Auto renaming workspace variables to any existing variables on the workspace would break existing implementations. The current design allows a developer to specify how those blocks should read, which is important for blocks like 'get the first item in <list>'.

**Comment by NAllred91** [comment]
Thanks,

Renames updating the flyout seems like it would resolve the issue I'm dealing with as well.
