### ISSUE TITLE
Renaming variable to existing variable name should not be allowed

### ISSUE THREAD

**Issue by NAllred91** [google/blockly#1507]
### Problem statement
Renaming a variable the same name as an existing variable makes it turn into the existing variable.
![renamingvariables](https://user-images.githubusercontent.com/8683908/33801126-df77ed80-dd1e-11e7-8f3e-10bc5703f2e4.gif)

### Expected Behavior
I would expect trying to rename a variable to an existing name would not be allowed.

**Comment by RoboErikG** [comment]
This is intentional to allow users to combine two variables without changing every block themselves. The logic lives in [variables.js](https://github.com/google/blockly/blob/master/core/variables.js#L276).

**Comment by NAllred91** [comment]
Using the rename functionality to combine two existing variables doesn't seem very intuitive.

I'd be worried that a user might not realize that the new variable name they are typing already exists, and by mistake merge two existing variables.  By the time they realize something isn't right they may not be able to trace the source of the problem back to when they renamed the variable.

A less general issue I have is that, in my implementation, I need a variable drop down where the user cannot change the value to a different variable, but still have the option to rename or delete the variable.  With renaming a variable having the power to merge two variables together the user can get themselves into a state they shouldn't be allowed to get to.
