### ISSUE TITLE
Renaming a procedure does not group events

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#1508]
### Problem statement
It looks like we lost a setGroup(true) somewhere in procedure renaming. This is causing each keystroke and each rename of a caller to be a separate undo action.

If you rename a procedure that has callers you will end up with an extra undo op for every block that was renamed. When you use ctrl+z to undo you then have to do an extra undo for each block. They are all renamed on the first undo, so the extra undos are just no-ops.

### Expected Behavior
One undo group for all the renames.

### Actual Behavior
The events for a procedure name change have no group.

### Steps to Reproduce

1. Create a procedure
2. Create two callers of the procedure
3. Change the name of the procedure.
4. Undo the name change.

### Stack Traces

```
Replace with error stack trace.
```

### Operating System and Browser

Desktop Chrome

**Comment by BeksOmega** [comment]
For history's sake, this was actually reopened by #2441 ([apparently](https://github.com/google/blockly/pull/2441#issuecomment-489369438) I thought this was the intended behavior). And then fixed by #4952
