### ISSUE TITLE
FieldImage documentation refers to Blockly.pathToBlockly

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1511]
The image field [documentation](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#image) on the developers site says:

> The FieldImage object is created with the image URL and the desired height and width. The image will be scaled to within the specified dimensions, while preserving the aspect ratio. The block will expand as needed to accommodate the image. An optional fourth argument specifies the alternate text for use when the block is collapsed.
> 
> The image URL can be relative. On web, configure Blockly.pathToBlockly to specify Blockly's root directory. On Android, the relative URL is treated as an [asset path](https://developer.android.com/reference/android/content/res/AssetManager.html#open(java.lang.String).
> 

Two issues:
- The link on "asset path" is formatted wrong (minor issue)
- `Blockly.pathToBlockly` doesn't exist.  `Blockly.pathToMedia` exists, but is not used when loading an image for an image field.  Image fields can have an absolute path as the src or can have a path relative to the page--which is not relative to Blockly.  I chatted with Neil, and he says that the media folder is only intended to be used for core Blockly assets, not block assets.

**Comment by AnmAtAnm** [comment]
Fixed, with added documentation for iOS.
