### ISSUE TITLE
Flyout Alway Visible?

### ISSUE THREAD

**Issue by fdeitelhoff** [google/blockly#1514]
I've searched here and the google group but haven't found an answer:

Is it possible to show the flyout area the whole time? Basically it shouldn't be a flyout anymore. :)

I'm using Blockly with eye-tracking and if the flyout is above user generated code it is hard to distinguish those areas within the eye tracking data.

**Comment by RoboErikG** [comment]
There are several examples of this in the [Demos](https://blockly-demo.appspot.com/static/demos/index.html). Please ask questions on the google group in the future.
