### ISSUE TITLE
Right-click shows browser context menu on top of Blockly context menu

### ISSUE THREAD

**Issue by ericrosenbaum** [google/blockly#1516]
### Problem statement

Right-clicking on a block or on the workspace displays the browser context menu on top of the Blockly context menu.

### Expected Behavior

Only the Blockly context menu should display.

### Actual Behavior

Both menus display, with the browser's menu on top:
![screen shot 2017-12-15 at 2 41 16 pm](https://user-images.githubusercontent.com/567844/34057783-6af42a0a-e1a6-11e7-94aa-9b6770d0aa0a.png)

### Steps to Reproduce

1. Visit the Blockly [demo](https://blockly-demo.appspot.com/static/demos/code/index.html)
2. Right-click on a block or on the workspace.

### Stack Traces

Nothing in the console.

### Operating System and Browser

I saw this on a MacBook Air, with Mac OS 10.11.6, Chrome 63.0.

It happened when I right-clicked in any way available (control-clicking, two-finger clicking the trackpad, right-clicking using a mouse).

### Additional Information

I'm not seeing this bug on a MacBook Pro with Mac OS 10.12.6, Chrome 63.0.

**Comment by rachel-fenichel** [comment]
Can't repro on my linux box with chrome.  Can't repro on windows 7 with ie10, firefox, or chrome 63.

I'm marking as low priority and we'll keep an eye out for it.

**Comment by jlaurens** [comment]
I am seeing this on macOS 10.13.1 but only on Chromium 64, not on Chrome 63 nor safari, nor firefox

**Comment by MNSDivya** [comment]
Issue seems resolved in chromeOS/Chrome
Windows OS/ Firefox,edge,IE.

Have not checked in MacOS.

**Comment by alirezaAsadi2018** [comment]
I have came upon the same issue on windows 10 with firefox 83.0 (64-bit).
![Screenshot (804)](https://user-images.githubusercontent.com/44492608/101160909-0a658200-3645-11eb-95bb-0b4ff0d3504a.png)
Do you have any plan to fix this?
Thank you very much
