### ISSUE TITLE
Way to connect custom block shapes

### ISSUE THREAD

**Issue by kushal4** [google/blockly#1527]
hi,
Sorry this may be the same issue from google groups page,I want to connect 2 custom shaped blocks with my  own notches built for that.From the code itself from what i am understanding ,the connection info is maitained as 'db_' and 'dbOpposite_' for 2 compatible connections.But from there on I am getting misleaded about how to move further after including my own custom shape constants to the blockly json database.
Thanks,
Kushal

**Comment by RoboErikG** [comment]
Adding custom connection shapes is fairly involved. We don't have an API for doing so, which means you'd have to make modifications to the library yourself. I'd suggest asking on the mailing list as other developers have done similar work in the past.

**Comment by xylix** [comment]
@kushal4 Did you ever manage to get custom block connectors working?
