### ISSUE TITLE
Decide how validators work on variable fields

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1529]
`fieldVariable.onItemSelected` used to end with:
```
itemText = this.callValidator(itemText);

if (itemText !== null) {
  this.setValue(itemText);
}
```

The validator usually works on text rather than value, so I removed those calls as part of only referring to variables by ID.  As long as the ID came from the dropdown, it should be valid.  

Validators serve a second function of letting the developer override selection of items.  Is that something that we need to allow for variable fields?  If so, how?  If not, where does the documentation go?

**Comment by BeksOmega** [comment]
Validators were made consistent by the fields refactor. See the [new docs](https://developers.google.com/blockly/guides/create-custom-blocks/fields/validators) on them.
