### ISSUE TITLE
Add callbacks for determining the validity of a variable name based on its type

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1537]
Different types of variables may have different naming rules (e.g. in scratch certain types of variables can have conflicting names, but not others).  Developers should be able to provide callbacks to check name validity based on the name and the workspace's variable map.

**Comment by rachel-fenichel** [comment]
We'll need one for rename and one for create.  No validation should be needed for deletion beyond what the library does already.
Creation:
```
Blockly.Variables.validateVarCreate = function(ws, name, type) {
  // returns a boolean
};
```

Renaming:
```
Blockly.Variables.validateVarRename = function(ws, oldName, newName, type) {
  // returns a boolean
};
```

Questions:
- Should rename take in the old variable instead of the old name?
- Should they both take in a variable map instead of a workspace?
- Does the potential variable map need to be passed in?
- How do we specify this so that it doesn't disappear in compression?
- Should the functions be defined but always return true (okay) in the library, or should they not be defined?

**Comment by rachel-fenichel** [comment]
Also:
- Is this a general problem (needs a formal API) or a scratch-specific problem (just needs a function that they can cleanly override in scratch-blocks).

**Comment by rachel-fenichel** [comment]
After discussion, the correct way to get this behaviour is to override `Blockly.Variables.createVariable` and `Blockly.Variables.renameVariable`.  Those are the existing functions for requesting names from the user, validating those names, and creating the resulting variables only if appropriate.

We will not be making a formal API unless we get more requests for it.

**Comment by vandelpavel** [comment]
@rachel-fenichel
I'm currently trying to override these 2 functions but I'm not sure about how and where I should override these 2 functions.
Can you show me an example?
Thanks in advance! :)

**Comment by vandelpavel** [comment]
My target is adding validation on input fields of variables (used in a FieldVariable input in a block).
I tried to override the 2 mentioned functions but I'm unsure how to do so...
Fortunately, the "variable creation" was handled by a custom "create button" which allowed me to register a custom event and trigger my function.
Implementing the same for the rename has been tricky and the only way I've found was to override the "FieldVariable" class like so:

```ts
export class CustomFieldVariable extends FieldVariable {
  override onItemSelected_(menu: Menu, menuItem: MenuItem) {
    const id = menuItem.getValue();
    // Handle special cases.
    if (this.sourceBlock_ && !this.sourceBlock_.isDeadOrDying()) {
      // In the original file is casting the type
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      const variable = this.getVariable()!;

      if (id === RENAME_VARIABLE_ID) {
        // Rename variable.
        void openVariableDialog(this.sourceBlock_.workspace, variable);
        return;
      }
      if (id === DELETE_VARIABLE_ID) {
        // Delete variable.
        this.sourceBlock_.workspace.deleteVariableById(variable.getId());
        return;
      }
    }
    // Handle unspecial case.
    this.setValue(id);
  }
}
```
I just copy-pasted that same method and just changed the call of native `Variable.createVariableButtonHandler` with my custom function `openVariableDialog`.

This is a work around, let me know if there is a more direct and less invasive way to accomplish that.

**Comment by BeksOmega** [comment]
Hello @vandelpavel ! In general we encourage these kinds of questions to be posted to the [forum](https://groups.google.com/g/blockly), but it sounds like you might be looking for a [validator](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/variable#creating_a_variable_validator) =) If you have any further questions please follow up on the forum!

Best,
--Beka

**Comment by vandelpavel** [comment]
Answered you in the forum and linked this GH issue.
Let me know.

I wish you the best!
