### ISSUE TITLE
Clojure Support

### ISSUE THREAD

**Issue by Immortalin** [google/blockly#155]
Can Clojure support be added to the code generator? It is dynamically typed like python and JavaScript but can be compiled to jar, allowing for easier deployment.

**Comment by drpepper** [comment]
Clojurescript (Clojure that compiles to JavaScript) would also be a plus!

**Comment by Immortalin** [comment]
Clojure support should be trivial if clojruescript support could be achieved

**Comment by aadrian** [comment]
+1 for Clojure/ClojureScript support

**Comment by TechplexEngineer** [comment]
What would be the need/use case for using clojurescript?

**Comment by aadrian** [comment]
> What would be the need/use case for using clojurescript?

e.g. Clojure that runs in the browser.

**Comment by TechplexEngineer** [comment]
@aadrian I guess I'm unclear what the of benefit adding clojurescript to Blockly would be. Blockly works great as it is. Wouldn't using clojurescript require a substantial re-write of the blockly core?

**Comment by aadrian** [comment]
@TechplexEngineer for now Blockly produces/generates dart, js, php and python code. 
ClojureScript would be just another one.  (I'm not sure why would this require a re-write of the core, since a re-write was not done for the other languages either)

**Comment by carlosperate** [comment]
@aadrian I think the original issue was suggesting to change the blockly backed (I assume the appengine portion) to support Clojure, not to add it as another language generator.

**Comment by aadrian** [comment]
>  I think the original issue was suggesting to change the blockly backed  ...

Most usages I know are without appengine already :) (always considered the appengine files here for demo purposes only).

Since blockly does already everything in the browser, I see most of the value from having an extra ClojureScript and Clojure generator. 

How a diagram might be persisted or not, should be IMHO an integration detail that each user needs to decide depending on the use case.

**Comment by TechplexEngineer** [comment]
Ah I understand, the term "backend language" didn't make me think language generator, which makes much more sense.

**Comment by carlosperate** [comment]
The original message is talking about deployment, which clearly involves the backend language of Blockly. I am not saying it could not be added as a generator, just that we are talking about very two different things here. I would suggest, for clarity, to move all conversations of a clojure/clojurescript generator to a different issue and keep this one only for it's original intent.

Personally I agree with @TechplexEngineer, there is no real value added to move to Clojure, specially taking in consideration most Blockly devs don't seem to be using the current backend anyway and implementing their own.

**Comment by Immortalin** [comment]
Edit: used the wrong terms.
