### ISSUE TITLE
Don't let variables of different types have the same names.

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1559]
Scratch allows this for backwards compatibility, so we have the infrastructure to support it in blockly.  But the default behaviour should be to require all variable names to be unique.

**Comment by moniika** [comment]
Corner case with creating variables in functions needs addressed.

![duplicate](https://user-images.githubusercontent.com/6621618/65725653-0795f700-e068-11e9-9b05-0e7aaa460cf9.gif)

**Comment by RoboErikG** [comment]
Also marking low priority since we haven't fully fleshed out how typed variables work with functions.

**Comment by BeksOmega** [comment]
I think this is related to #3877

**Comment by BeksOmega** [comment]
This was implemented at some point and never closed.
