### ISSUE TITLE
Operator precedence for math_number (JS/PHP generators)

### ISSUE THREAD

**Issue by jschanker** [google/blockly#1563]
### Problem statement

**Bug Report**: The JavaScript/PHP generators for ``math_number`` currently return ``ORDER_ATOMIC`` for all numbers when they should be returning ``ORDER_UNARY_NEGATION`` for negative numbers.  In JavaScript, this can cause an issue if you e.g., extend ``Number.prototype`` by adding an ``abs`` method for absolute value and want to have a corresponding ``abs`` block (not for use in production, educational purposes only!)  For example:

![image](https://user-images.githubusercontent.com/9159008/35367661-8ff4521e-014d-11e8-82a0-1e2ea2fcc2f1.png)

### Expected Behavior

The generated code for the block above should be ``(-5).abs()`` so that it evaluates to ``5``.

### Actual Behavior

With ``ORDER_ATOMIC``, the above block would generate the code ``-5 .abs()``, which would incorrectly produce ``-5`` since the ``-5`` block is "ripped apart" as described in [Operator Precedence | Blockly | Google Developers](https://developers.google.com/blockly/guides/create-custom-blocks/operator-precedence).

### Operating System and Browser

All

### Additional Information

The ``math_number`` block generator for Dart, Python, and Lua account for negative numbers.

**Comment by NeilFraser** [comment]
Thanks for the patch!
