### ISSUE TITLE
Bad Block Sizing in Hidden Workspace

### ISSUE THREAD

**Issue by twodee** [google/blockly#1570]
### Problem statement

When I inject a workspace into a `div` whose `display` attribute is set to `none`, and programmatically add a block to it, the block is not properly sized when the `div` is made visible. In particular, the text extends beyond the block.

### Expected Behavior

<img width="209" alt="screen shot 2018-01-25 at 8 12 52 pm" src="https://user-images.githubusercontent.com/1939462/35422027-2a92fcbc-020c-11e8-8ed9-0cea9b8c8218.png">

### Actual Behavior

<img width="211" alt="screen shot 2018-01-25 at 8 04 28 pm" src="https://user-images.githubusercontent.com/1939462/35422005-05da36f6-020c-11e8-8270-1cc6d787ca93.png">

### Steps to Reproduce

This issue is visible in the following minimal example, which hides the `div` initially, injects the workspace, and then displays it 2 seconds later:

````
<!DOCTYPE html>
<html>
<head>
  <title>...</title>
  <script src="blockly/blockly_compressed.js"></script>
  <script src="blockly/blocks_compressed.js"></script>
  <script src="blockly/msg/js/en.js"></script>
  <style>

#blocklyDiv {
  display: none;
}

  </style>
</head>
<body>
  <div id="blocklyDiv" style="height: 200px; width: 200px;"></div>
  <script>

var workspace = Blockly.inject('blocklyDiv', {
  readOnly: true
});

var block = workspace.newBlock('controls_if');
block.initSvg();
block.render();

setTimeout(function() {
  var div = document.getElementById('blocklyDiv');
  div.style.display = 'block';
  Blockly.svgResize(workspace);
}, 2000);

  </script>
</body>
</html>
````

### Stack Traces

No warnings or errors are generated.

### Operating System and Browser

* Desktop Chrome
* Desktop Firefox
* Desktop Safari

### Additional Information

Maybe there's a resize call/event I'm missing.

**Comment by twodee** [comment]
Ahh, it looks like a call to workspace.render() fixes the issue. Sorry for the noise.

**Comment by rachel-fenichel** [comment]
Sounds like you're all sorted out.  

The root cause is that we're asking the browser for the measured width of the text, and it returns zero if it's not visible (or throws an error if it's Internet Explorer, but we catch that).  Re-rendering the offending blocks (or all blocks) usually fixes it.
