### ISSUE TITLE
Dropdown Bug

### ISSUE THREAD

**Issue by Kashdog** [google/blockly#1577]
https://github.com/google/blockly/issues/1454

This issue is still not fixed in blockly, I am using the latest version of Blockly and my dropdown extends upwards and gets cutoff
<img width="1429" alt="screen shot 2018-01-28 at 5 02 43 pm" src="https://user-images.githubusercontent.com/17529508/35487771-52fa9c8a-044d-11e8-8e94-d305b9187637.png">

**Comment by AnmAtAnm** [comment]
Please do not open new issues for known, tracked problems.

**Comment by AnmAtAnm** [comment]
The bug is marked fixed, but the develop branch has not been pushed to master since the fix was made. Feel free to use the develop branch if you need this feature.
