### ISSUE TITLE
Events for comments

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1580]
Part of #1476 

New event types:

- `Blockly.Events.COMMENT_CREATE`
  - Create a comment, on the workspace or on a block.
  - If the comment is on a block, contains the block ID.
  - Otherwise the blockId field is empty.
- `Blockly.Events.COMMENT_DELETE`
  - Delete a comment.  Contains the comment ID.
- `Blockly.Events.COMMENT_MOVE`
  - Move a comment.
  - Can move 
    - On the workspace (between absolute locations)
    - From the workspace to a block (block ID is set.  Location is absolute at beginning and relative at end.)
    - From a block to a different block (block ID changes.  Location is relative at beginning and end.)
    - From a block to the workspace (from relative location to absolute location.  Block ID goes to null.)
- `Blockly.Events.COMMENT_CHANGE`
  - Change the text of a comment.

Like all other events, these events contain the common properties:
- type
- workspaceId
- blockId
- group

**Comment by rachel-fenichel** [comment]
Currently changing a comment on a block fires a `BlockChange` event:
```
    Blockly.Events.fire(new Blockly.Events.BlockChange(
        this, 'comment', null, this.comment, text || ''));
```

**Comment by CleoQc** [comment]
Random thought: 
As we're showing the generated code, including comments, having a BlockChange event suits me just fine.

**Comment by moniika** [comment]
@rachel-fenichel Can this be closed?

**Comment by rachel-fenichel** [comment]
Yes.
