### ISSUE TITLE
Demo index page redesign

### ISSUE THREAD

**Issue by Rgtemze** [google/blockly#1586]
User interface experience of HTML file (/demos/index.html), listing all the demos, could be improved as it looks very simple and non-attractive including navigation-bar, headers etc..  Same also holds for the demos themselves that could be reached from (/demos/index.html), for example, Resizable Demo (/demos/resizable/index.html) does not appear to attract users; however, Blockly Developer Tool (demos/blockfactory/index.html) seems to be good in shape. I would request that those who are experienced in UI provide us with a better design in those HTML files. 
Thank you.

**Comment by AnmAtAnm** [comment]
While we whole-heartedly agree the index page needs some design attention, we'd like to keep the individual demo pages as simple as possible for the purposes for demonstration.  Perhaps iframes can be used to facilitate both goals.

All that said, we have no available cycles or design resources to address this. We welcome pull requests on this issue.

**Comment by kushthedude** [comment]
@AnmAtAnm Should Can I work on it?

**Comment by moniika** [comment]
Most of the demos are now on the [site](https://blockly-demo.appspot.com/static/demos/index.html), but there is still work do to there.

**Comment by AnmAtAnm** [comment]
> Most of the demos are now on the [site](https://blockly-demo.appspot.com/static/demos/index.html), but there is still work do to there.

Isn't that the same site it has always been on?

**Comment by steviedupree** [comment]
Does this still need to be worked on?

**Comment by alschmiedt** [comment]
Hello!

Sorry, yes I think the wrong site was pasted. Here is the new [site](https://google.github.io/blockly-samples/). There is still some work to do with migrating over demos, but I think the new look probably satisfies this issue.
@rachel-fenichel to confirm.

**Comment by rachel-fenichel** [comment]
@steviedupree there is still work to do on migration, if you are interested--specifically, for each demo that is now on blockly-samples, adding a redirect to the new location. There are probably between 10 and 15 demos that need to be properly redirected.

**Comment by BeksOmega** [comment]
We now have a fancy looking demo site in the samples repo.
