### ISSUE TITLE
Style Guide Not Consistent With .eslintrc

### ISSUE THREAD

**Issue by aramperez-tst** [google/blockly#1588]
Sorry if I'm reporting this in the wrong place. If this is the wrong place, please let me know where to report it.

### Problem statement

Reading the Blockly Style Guide [page](https://developers.google.com/blockly/guides/modify/web/style-guide) (of July 20, 2017), the 3rd bullet under "Do" states "Use eslint" and its sub-bullet has a [link](https://github.com/google/blockly/blob/master/.eslintrc) to your .eslintrc. The 11th line of the .eslintrc file (of May 25, 2016) is 

> "quotes": ["off"], # Blockly mixes single and double quotes

However, the 12th bullet of the Style Guide states "Use single quotes (except when writing JSON)". To a newcomer this is confusing.

### Expected Behavior

For the 11th line to be 

> "quotes": ["single"], # Blockly Style Guide recommends single quotes

### Operating System and Browser

Mac OS v10.13.3 and Chrome v64.0.3282.140

### Additional Information

I'm new to web programming and using eslint.

**Comment by RoboErikG** [comment]
There are js files with JSON blobs in them, so we aren't able to enforce one or the other since JSON requires double quotes to be correct. We should update the comment in the eslintrc to make it clear single quotes should be used except for JSON blobs.

**Comment by aramperez** [comment]
Ok, thanks!
