### ISSUE TITLE
goog.date.fromIsoString not defined in compressed blockly file

### ISSUE THREAD

**Issue by kmasuyama** [google/blockly#1591]
As of a few hours ago, the calendar in the field>date block has stopped working. The console throws the errors below, and the block acts as if dragged (yellow highlight, movable). However, the block cannot be placed down, and no further action is possible. Using blockly_uncompressed.js behaves as expected, so the problem seems to be in the compression process. 

Error on clicking the calendar:
```
blockly_compressed.js:2168 Uncaught TypeError: goog.date.fromIsoString is not a function
```

Warnings on subsequent clicks:
```
blockly_compressed.js:1768 Trying to end a gesture recursively.
blockly_compressed.js:1953 tried to start the same gesture twice
Blockly.WorkspaceSvg.getGesture @ blockly_compressed.js:1953
Blockly.Field.onMouseDown_ @ blockly_compressed.js:1788
h @ blockly_compressed.js:2345
blockly_compressed.js:1953 tried to start the same gesture twice
Blockly.WorkspaceSvg.getGesture @ blockly_compressed.js:1953
Blockly.BlockSvg.onMouseDown_ @ blockly_compressed.js:2041
h @ blockly_compressed.js:2345
blockly_compressed.js:1768 Trying to end a gesture recursively.
```

### Expected Behavior

I can click the calendar and pick a date. The block stays fixed and I can continue using the app.

### Actual Behavior

The calendar opens, but I cannot pick a date or put the block down.

### Steps to Reproduce

run python build.py on a project with a date block.
Open the app and try clicking on the calendar

### Additional Info

The first few builds when I started seeing the issue showed server error messages during the build.py process (no longer showing up). I think this may have to do with the online clojure compiler.

I am using the following:
node 7.9.0
npm 4.2.0
electron 1.8.2
electron-packager 10.1.2
python 2.7.13
blockly 1.0.0
google-closure-library v20171203.0.0

**Comment by AnmAtAnm** [comment]
Using Blockly Playground (blockly_uncompressed.js), I see similar behavior with a slightly different error message:

    Uncaught TypeError: goog.date.DateTime.fromIsoString is not a function
        at Blockly.FieldDate.createWidget_ (field_date.js:158)
        at Blockly.FieldDate.showEditor_ (field_date.js:123)
        at Blockly.Gesture.doFieldClick_ (gesture.js:707)
        at Blockly.Gesture.handleUp (gesture.js:573)
        at wrapFunc (blockly.js:447)
        at HTMLDocument.touchWrapFunc (blockly.js:459)

Note `goog.date.DateTime.fromIsoString` instead of `goog.date.fromIsoString`. I'm going to assume that is what @kmasuyama meant and investigate from there.

**Comment by AnmAtAnm** [comment]
I'm ruling this as a transient error due to a Closure refactor, probably related to moving the function into `goog.date.DateTime`.

The `FieldDate` in `blockly_compressed.js` worked fine for me, and when I updated my local `closure-library` the error in the playground / `blockly_uncompressed.js` went away.

Developers who see this message should update their local copy of `closure-library`.

**Comment by AnmAtAnm** [comment]
Here is the change in Closure:
https://github.com/google/closure-library/commit/8aed06d8aa8ddacd072235d69b083e082109d6ca#diff-59ad00690c3488039024368101b23393
