### ISSUE TITLE
Typed variable creation modal

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1606]
### Problem statement

Blockly does not provide a good UI for users to select the type of a variable as they create it.  Currently the only way to make this visible is to have a separate button per variable type (e.g. "create new number variable", "create new string variable", etc.).  This is fine for a small number of variable types, but can be crowd the toolbox as more variable types are created.

### Expected behaviour

Blockly should provide a default modal implementation for variable creation.  It should be able to replace [Blockly.Variables.promptName](https://github.com/google/blockly/blob/master/core/variables.js#L315) or [Blockly.Variables.createVariable](https://github.com/google/blockly/blob/master/core/variables.js#L238), depending on the implementation that we pick. 

The modal should look like this:
![image](https://user-images.githubusercontent.com/13686399/36046056-941d4eea-0d8c-11e8-8baa-4f5fea3cee7f.png)

It should take in a list of allowed variable types as strings.  In this case that list is `["Animal", "Vegetable", "Mineral"]`

The modal's implementation should conform to the Blockly style guide.  That means avoiding features that don't work in Internet Explorer.

**Comment by RoboErikG** [comment]
One nit: It should take a list of pairs with display text and value. [["Animal", "ANIMAL"],  ["Vegetable", "VEGETABLE"], ["Mineral", "MINERAL"]]. This way the display names can be translated without changing the values.

**Comment by rdosanjh** [comment]
Could i have a crack at this ?

**Comment by rdosanjh** [comment]
So i've just taken a look at this. Although the code in workspace.js supports variables it appears that the ui does not. If i create a variable of type string it doesn't display in the variables section. Is this something that will be added later or am i missing something ?

**Comment by jollytoad** [comment]
I've left an idea on google forum regarding creation of new typed variables, and inferring the type from the initial assignment connection... https://groups.google.com/forum/#!topic/blockly/-j-v5CLDQVA

**Comment by rachel-fenichel** [comment]
@rdosanjh That's correct.  We leave it up to the developer to decide how to represent variable types on their blocks, because the correct way to do that varies a lot depending on things like user, number of types supported, and language generated.

We discuss that more in #1312, but it's a problem that can be solved independent of this one.

@jollytoad I saw that, and it may be necessary for more complicated type systems.  For things with just two or three types, or where one of the goals is to teach people that types exist and how to work with them at a basic level, this sort of dialog is still helpful.  We don't need to make it the default, but it's something that we know developers would use if we had it in the library.

**Comment by alschmiedt** [comment]
Published as a plugin that can be found [here](https://github.com/google/blockly-samples/tree/master/plugins/typed-variable-modal)
