### ISSUE TITLE
RTL Render error on block with icon and no fields/inputs

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1608]
### Problem statement

Block with just mutator is not correctly rendered in RTL:
<img width="52" alt="screen shot 2018-02-13 at 12 35 34 pm" src="https://user-images.githubusercontent.com/9916202/36172379-8b063e76-10ba-11e8-81e7-8c6cacf68c34.png">

Also, the width is not calculated correctly:

<img width="158" alt="screen shot 2018-02-13 at 12 40 07 pm" src="https://user-images.githubusercontent.com/9916202/36172539-15ba5ed0-10bb-11e8-9fdb-1debc0857cdf.png">

### Expected Behavior

The RTL block should be curved (convex) on the right and flat on the right, containing the mutation gear icon.

Compare with the LTR version:
<img width="69" alt="screen shot 2018-02-13 at 12 38 50 pm" src="https://user-images.githubusercontent.com/9916202/36172491-e6ee9b84-10ba-11e8-9b5e-4a498abf5f24.png">

### Steps to Reproduce

1. Add this block to the playground:

```
Blockly.Blocks['bad-rtl-mutator'] = {
  init: function() {
    this.setMutator(new Blockly.Mutator(['math_number']));
  }
};
```

### Operating System and Browser

 * Desktop Chrome

**Comment by AnmAtAnm** [comment]
As seen in playground:
<img width="164" alt="screen shot 2018-02-20 at 2 13 26 pm" src="https://user-images.githubusercontent.com/9916202/36452170-4f3b1f7c-1648-11e8-90da-aa8bf560d76b.png">

**Comment by rachel-fenichel** [comment]
Still present in June.

**Comment by AnmAtAnm** [comment]
Still present in August.

**Comment by NeilFraser** [comment]
Still present in April.

**Comment by rachel-fenichel** [comment]
Fixed in new renderer.
