### ISSUE TITLE
Pinch gesture on iOS creates errors: 

### ISSUE THREAD

**Issue by winstonwolff** [google/blockly#161]
On iOS, if I use a pinch gesture in the workspace, these errors appear in the console:

```
Error: Invalid value for <rect> attribute x="NaN"
	set (scrollbar.js, line 503)
	set (scrollbar.js, line 137)
	onMouseMove_ (blockly.js, line 313)
	wrapFunc (utils.js, line 120)
```

The problem Blockly.onMouseMove_() is looking for e.clientX, but if it's a multitouch event, the clientX field is instead at e.touches[n].clientX

I'll submit a PR shortly to ignore multitouch events in that handler.

**Comment by carlosperate** [comment]
Based on https://groups.google.com/forum/#!topic/blockly/6_0b63cyDUE it looks like the intention is to implement zooming with pinch in touch devices, so unless it is breaking something right now I wouldn't submit a pull to ignore multitouch.

**Comment by winstonwolff** [comment]
Shouldn't we keep the code in good shape at all times? I.e. when the pinch gesture is implemented, then we stop ignore multitouch gestures?

**Comment by NeilFraser** [comment]
Merged.
For the record, this (borken) behaviour predates the zooming.  It's been like this forever.  Glad to have this patched.  Thanks.
We'll revisit this shortly to enable actual zooming.
