### ISSUE TITLE
Var id instead of var name in tooltip

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1619]
Loops: "Count with i from 1 to 10 by 1"

<img width="411" alt="screen shot 2018-02-14 at 2 20 17 pm" src="https://user-images.githubusercontent.com/9916202/36231299-5f69c976-1192-11e8-8bea-c762c03ea514.png">

Seen in rc/feb_2018

**Comment by rachel-fenichel** [comment]
Present on all of these blocks:
![image](https://user-images.githubusercontent.com/13686399/36333341-10e4b442-132b-11e8-9dca-41b7f50157d6.png)
