### ISSUE TITLE
Extract common Field support methods into new field_util.js

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1624]
Several Field classes have shared functionality the is unrelated to data type or inheritance hierarchy. These should be extracted as functions that can be used by all Field implementations. These functions should be collected into `core/field_util.js`, a new file.

@rachel-fenichel: specific function suggestions, examples, details?

**Comment by BeksOmega** [comment]
### Proposals

* [register](https://developers.google.com/blockly/reference/js/Blockly.Field#.register)
* [fromJson?](https://developers.google.com/blockly/reference/js/Blockly.Field#.fromJson)
* [startCache](https://developers.google.com/blockly/reference/js/Blockly.Field#.startCache)
* [stopCache](https://developers.google.com/blockly/reference/js/Blockly.Field#.stopCache)
* [getDisplayText_](https://developers.google.com/blockly/reference/js/Blockly.Field#getDisplayText_)

If this is something you're still interested in doing I'd be happy to grab it.

**Comment by BeksOmega** [comment]
Gentle bump, can this be closed or is it something you're still interested in?

**Comment by rachel-fenichel** [comment]
Yeah, if we're going to change this we should do it now while we're making everyone update all of their fields anyway.

+1 to:
- register
- fromJson
- startCache
- stopCache

And also
- cacheWidths_
- cacheReference_
- getCachedWidth

No to 
- getDisplayText
