### ISSUE TITLE
Build FieldDate as auxiliary .js file

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1625]
### Problem statement

FieldDate requires significant parts of the closure libraries that are not used by other parts of Blockly. As such, it bloats the library. The solution to date has been to comment out the field in default builds. This has lead to a situation where we are expecting users to modify the code to take advantage of the feature (complicating the process for users to update their version of Blockly).

This current solution has meant we rarely test with FieldDate.

With the new Field registration methods, we can separate FieldDate and its dependencies as a auxiliary library.

### Proposed Solution

 * [ ] Update build.py to build field_date.js as it's own `_compressed.js` library.
 * [ ] Import this library into the playground and possibly other demos for testing.

**Comment by bartbutenaers** [comment]
Hi Andrew (@AnmAtAnm ),

Is there already some kind of solution for this problem, or do we still need to uncomment the lines and compile the library by ourselves?  Having this block in a separate js file would indeed be a useful addition...

Thanks !
Bart

**Comment by AnmAtAnm** [comment]
Hi @bartbutenaers,

We have not made the changes recommended above, but we think this is the correct solution and would accept Pull Request to resolve this issue.

Thanks for your interest!

**Comment by javaczh** [comment]
how to use fieldDate in react,i use goog.require('Blockly.FieldDate'),but it's not work,so should can i do?

**Comment by RoboErikG** [comment]
Closing as we're tracking moving to a standalone date field in #2890
