### ISSUE TITLE
Add Field.prototype.toXml() & .fromXml()

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1627]
### Problem statement

Some fields need more than the `value=` attribute of the `<field>` XML when serializing and deserializing data. For example, FieldVariable uses `id=` and `variabletype=`.

### Proposed Solution

 * [ ] Add `.fromXml(/* @type {!Element} */ fieldElement)` and `.toXml(!Element} */ fieldElement)` to the `Field` base class.
 * [ ] Modify Blockly.Xml.fieldToDom_(..) and .domToField_() to call new methods.

**Comment by RoboErikG** [comment]
After internal discussion we'd like to keep writing the value as the text in the element instead of adding a value property to the tag.
