### ISSUE TITLE
Mutator flyout can get so wide that you can't drag blocks in the mutator

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1652]
### Problem statement
Mutator flyout can get so wide that you can't drag blocks in the mutator
![image](https://user-images.githubusercontent.com/13686399/36499473-3ade6120-16f6-11e8-9499-350aa898a489.png)

### Expected Behavior
The mutator should get wider, and the base block should move over to not be overlapping with the flyout.

### Actual Behavior
The base block doesn't move and the mutator doesn't change size, so it ends up fully in the flyout.  Visually it's over the flyout, but you can't drag blocks to connect to it.

### Steps to Reproduce
1. Go to the playground
2. Drag out a function block
3. Open the mutator
4. Start typing in the text field on the block in the mutator's flyout
5. Type until the flyout fills the mutator
6. Try to drag the block from the mutator's flyout to connect to the base block.

**Comment by amber-cd** [comment]
I have a similar issue with the mutator getting so tall I can't add blocks anymore (don't ask how I managed this...). Would that fall under this ticket, or should I make a new one?

**Comment by rachel-fenichel** [comment]
I think the solution will be similar, but they're different enough that having separate issues is fine.

**Comment by BeksOmega** [comment]
Could not reproduce
![Screen recording 2023-11-21 3 08 49 PM](https://github.com/google/blockly/assets/25440652/00206eb0-4a60-4a00-8307-e5858998b39b)
