### ISSUE TITLE
Unicode Variables

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1654]
Current behaviour

Blockly variables have their Unicode characters encoded.  Thus the variable '中国' is turned into '_E4_B8_AD_E5_9B_BD'.  Such JavaScript is legal, but completely unreadable.

Expected behaviour

It turns out that Unicode characters *are* allowed in JavaScript variable names.
```
var 中国 = 'China';
alert(中国);
```

Or:
```
var Hͫ̆̒̐ͣ̊̄ͯ͗͏̵̗̻̰̠̬͝ͅE̴̷̬͎̱̘͇͍̾ͦ͊͒͊̓̓̐_̫̠̱̩̭̤͈̑̎̋ͮͩ̒͑̾͋͘Ç̳͕̯̭̱̲̣̠̜͋̍O̴̦̗̯̹̼ͭ̐ͨ̊̈͘͠M̶̝̠̭̭̤̻͓͑̓̊ͣͤ̎͟͠E̢̞̮̹͍̞̳̣ͣͪ͐̈T̡̯̳̭̜̠͕͌̈́̽̿ͤ̿̅̑Ḧ̱̱̺̰̳̹̘̰́̏ͪ̂̽͂̀͠ = 'Zalgo';
alert(Hͫ̆̒̐ͣ̊̄ͯ͗͏̵̗̻̰̠̬͝ͅE̴̷̬͎̱̘͇͍̾ͦ͊͒͊̓̓̐_̫̠̱̩̭̤͈̑̎̋ͮͩ̒͑̾͋͘Ç̳͕̯̭̱̲̣̠̜͋̍O̴̦̗̯̹̼ͭ̐ͨ̊̈͘͠M̶̝̠̭̭̤̻͓͑̓̊ͣͤ̎͟͠E̢̞̮̹͍̞̳̣ͣͪ͐̈T̡̯̳̭̜̠͕͌̈́̽̿ͤ̿̅̑Ḧ̱̱̺̰̳̹̘̰́̏ͪ̂̽͂̀͠);
```

Here's documentation regarding what is and isn't allowed:
https://mathiasbynens.be/notes/javascript-identifiers

**Comment by rachel-fenichel** [comment]
![image](https://user-images.githubusercontent.com/13686399/36514468-61ac203e-1729-11e8-942c-c50b89dffe14.png)

**Comment by AnmAtAnm** [comment]
This doesn't appear to be occuring at a JavaScript specific level.  (/me sneaks aware for it can be reassigned.)

**Comment by NeilFraser** [comment]
Yup, it's in `Blockly.Names.prototype.safeName_` which states:

> Given a proposed entity name, generate a name that conforms to the
> [_A-Za-z][_A-Za-z0-9]* format that most languages consider legal for
> variables.

A quick check of Dart, Lua and Python 2 shows that they do not support Unicode variables, though Python 3, JavaScript and PHP do.

There's a feasible way to implement this in JavaScript:
```
eval('"use strict"; var ' + x)
```
where x is the first letter then the first two letters, then the first three letters of the name.  If it blows up, then encode the offending letter.  Also, '/n' and '/r' and ';' need to be escaped up front to prevent injection attacks.

**Comment by cpcallen** [comment]
> There's a feasible way to implement this in JavaScript:
> 
> ```
> eval('"use strict"; var ' + x)
> ```

Feasible, yes, but not exactly _sensible_, as the list of characters that would need to be escaped first is longer than just `[\n\r;]` (possibly much longer, and certainly not obvious).

A better approach is probably to use a regexp, even though the required regexp 8-10kB long and  depends on what version of ECMAScript _and_ Unicode one is targeting.
