### ISSUE TITLE
Reconsider ordinals in translation

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1657]
### Problem statement

Currently, some Blockly blocks have an "ordinal" string. For instance, in text and list blocks (with explicit "th" ordinal):

<img width="624" alt="screen shot 2018-02-23 at 9 52 21 am" src="https://user-images.githubusercontent.com/9916202/36608914-2423671a-1880-11e8-81ca-62406bdd8429.png">
<img width="455" alt="screen shot 2018-02-23 at 9 48 34 am" src="https://user-images.githubusercontent.com/9916202/36608924-301104b0-1880-11e8-8a38-916f5a4dd76d.png">

This works as designed with numbers:

<img width="643" alt="screen shot 2018-02-23 at 9 50 52 am" src="https://user-images.githubusercontent.com/9916202/36608951-45d2ba1e-1880-11e8-86ea-6b6fe31e1cc4.png">

Of course, the ordinal is a fixed string and doesn't adapt to the number (e.g., `1th` above).

It also is sufficiently separated from the digits that it doesn't read smoothly.

That said, it doesn't make sense with many variables. `currentth`? `indexth`?

<img width="733" alt="screen shot 2018-02-23 at 9 50 13 am" src="https://user-images.githubusercontent.com/9916202/36609005-6a60ab20-1880-11e8-8f43-ac23bfb1524b.png">

And look horribly if we enforce external inputs:

<img width="296" alt="screen shot 2018-02-23 at 9 47 43 am" src="https://user-images.githubusercontent.com/9916202/36609109-a9f835aa-1880-11e8-8665-8dc7782da4b9.png">
<img width="247" alt="screen shot 2018-02-23 at 9 49 09 am" src="https://user-images.githubusercontent.com/9916202/36609116-af2f1d5e-1880-11e8-8470-6dd5d9e3da6b.png">

Finally, ordinals are hard to translate (#1411) and hard to program around with mutators (#1656).

### Option 1: Remove all ordinals

Fairly self explanatory. I can't think of a single programming language that allows ordinals, anyway. Of course the intent is for the block to read like natural language, and the blocks that use `ORDINAL_NUMBER_SUFFIX` might need to be rephrased in the languages that assign `ORDINAL_NUMBER_SUFFIX`. 

### Option 2: Move the ordinal to the number block. Tag input connectors in a manner to trigger an ordinal.

<img width="590" alt="screen shot 2018-02-23 at 10 27 34 am" src="https://user-images.githubusercontent.com/9916202/36610208-43e2cd44-1884-11e8-81bf-91aca001d8a9.png">

<img width="298" alt="screen shot 2018-02-23 at 10 27 43 am" src="https://user-images.githubusercontent.com/9916202/36610212-4e2ac572-1884-11e8-9e05-93878d2bddd4.png">

Removing the ordinal from the parent to the child would solve the most of the problems listed above, but does take more effort.

The simplest implementation might be to add `ordinal` type checks to these inputs, and the `math_number` output type (in addition to `number`). Then, each `math_number` could add a change handler to test the parent connection, triggering add/remove of the ordinal `FieldLabel`.

This could allow `1st` instead of `1th`, but doing so would require an additional set of language translations.  This could be a set of translation messages (`ORDINAL_ONE`, `ORDINAL_TWO`, ...) or an optional function. E.g.:

```
ordinal = '';
if (goog.isFunc(GET_ORDINAL_TEXT_FNS[lang])) {
   ordinal = GET_ORDINAL_TEXT_FNS[lang](n);
}
```

**Comment by BeksOmega** [comment]
It seems these have been removed.
