### ISSUE TITLE
Impossible to enter data / move blocks on IE

### ISSUE THREAD

**Issue by msprotz** [google/blockly#166]
Using the latest -master (as of a few hours ago), Blockly seems to be badly broken on IE (can't edit text fields, can't drag&drop blocks). Has anyone else experienced this?

**Comment by NeilFraser** [comment]
I'm not tracking anything of this nature.  None of the recent commits (other than zooming) look dangerous.  (The exception is this one: [PR 162](https://github.com/google/blockly/pull/162) but I think that was committed moments *after* this issue was opened, so I don't think 162 is to blame.)

**Comment by carlosperate** [comment]
There are still some issues in IE, but I haven't experienced what you've
mentioned here.

**Comment by NeilFraser** [comment]
Yes, this was PR 162.  Oddly it worked on three devices when testing, but then failed hard some time later.  I have a feeling I got bit by a combination of caching and non-standard browser globals.
