### ISSUE TITLE
Error when renaming function argument in mutator

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1660]
### Problem statement

Below error/stacktrace when renaming a procedure argument inside the mutator window.

### Expected Behavior

Should not throw any errors due to a rename, even if bad. This lead to other side effects from incomplete execution (though eventually recoverable).

### Steps to Reproduce

Not exactly sure.  I have been unable to reproduce it. Attempted a number of variations of renaming in the toolbox block, in the connected block, with and without the variable present on other blocks.

### Stack Traces

```
Uncaught TypeError: outerWs.renameVarById is not a function
    at Blockly.FieldTextInput.validator_ (procedures.js:516)
    at Blockly.FieldTextInput.Blockly.Field.callValidator (field.js:330)
    at Blockly.FieldTextInput.setValue (field_textinput.js:112)
    at Blockly.FieldTextInput.onHtmlInputChange_ (field_textinput.js:285)
    at HTMLInputElement.wrapFunc (blockly.js:445)
```

This occurred in the recent `feb` release candidate branch.

**Comment by AnmAtAnm** [comment]
Cannot reproduce.  Reopen if you see a stack trace similar to this.

**Comment by nederland074** [comment]
I'm able to reproduce it with the following steps:
1) create a procedure block (with or without a return value - both affected)
2) open its mutator window
3) rename an argument with case change only, e.g. "x" to "X" (doesn't matter if it's in the toolbox or connected - it crashes in both cases)

**Comment by rachel-fenichel** [comment]
@nederland074 that matches what we found in #1958, so this will stay closed as a dupe.
