### ISSUE TITLE
Dropdown reports wrong value when called from extension

### ISSUE THREAD

**Issue by Marclev78** [google/blockly#1665]
### Problem statement

Given a dropdown field on a block, if I interrogate it from an extension, `getFieldValue()` will report the first option in the dropdown, irrespective of what is actually set on it. This makes it impossible to implement a case where I want the extension to do different things depending on the value of the dropdown, e.g. when loading a saved workspace where it will be called on blocks on the workspace that have been manipulated by the user.

### Expected Behavior

In the extension, `this.getFieldValue("dropdownField")` should return the value that has actually been set on the dropdown field, not simply the first value in its list of options.

### Actual Behavior

In the extension, `this.getFieldValue("dropdownField")` returns the first available value in the dropdown, irrespective of what it is actually set to on that block. It appears that the actual value is lazily evaluated after the extension has been called perhaps?

### Additional Information

It seems that if I use a mutator instead, it correctly report the dropdown field's value. This doesn't seem desirable though, as I don't want to make any changes to the DOM.

**Comment by AnmAtAnm** [comment]
Extensions functions are run during block instantiation, before the block is connected to other blocks or field values are set. It sounds like you want to add an `onchange` listener from the extension, and then perform the differentiated behavior inside that function.
