### ISSUE TITLE
Block comments: clicking on a block comment should bring it to the front

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1666]
### Problem statement

Block comments may overlap each other.  Clicking on one used to bring it to the front, in front of the rest of the stack, but this no longer happens.  We should add it back.

### Expected Behavior
Clicking on a block comment that is partly covered by another comment should bring the occluded comment to the front.

### Actual Behavior

Clicking on the outline of the comment brings it to the front, but clicking on the text area does not.

### Steps to Reproduce
In the playground:
1. Add two blocks
2. Add a comment on each block
3. Drag the comments so that one is partially covered by the other
4. Try to bring the partially covered comment to the front

### Additional Information

A click on the textarea of a block comment does not hit `Blockly.Gesture.prototype.doBubbleClick_` because `Blockly.utils.isTargetInput(e)` returned true at the beginning of `doStart`, and the gesture was cancelled.

**Comment by samelhusseini** [comment]
I've verified this no longer repro's / has been fixed.
