### ISSUE TITLE
Workspace comments: size of resize handle and delete button

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1669]
### Problem statement

The resize handle on a workspace comment should be easy to grab, and should probably grow on touch devices.

### Expected Behavior

Resize handle can be grabbed, even with touch.

### Actual Behavior

Resize handle is small and doesn't change size based on whether touch is enable.

### Additional Information

This is controlled by `Blockly.WorkspaceCommentSvg.RESIZE_SIZE = 8;`

Size 8: 
![image](https://user-images.githubusercontent.com/13686399/36758790-422843c8-1bca-11e8-8904-ea805cd3feb7.png)

Size 16:
![image](https://user-images.githubusercontent.com/13686399/36758808-4f408d5e-1bca-11e8-9b75-3404c822f3ea.png)

Size 24:
![image](https://user-images.githubusercontent.com/13686399/36758822-5a2e8766-1bca-11e8-9da7-b95e84873622.png)

**Comment by BeksOmega** [comment]
For the new workspace comments you can set the size with CSS. The positioning logic handles this correctly.
