### ISSUE TITLE
Namespace "Blockly.Msg.en" is provided in multiple files

### ISSUE THREAD

**Issue by Kaworru** [google/blockly#167]
See:
https://github.com/google/blockly/search?utf8=%E2%9C%93&q=%22Blockly.Msg.en%22&type=Code

I don't know the reason for the messages.js file, but maybe the namespace could be renamed to default or skeleton to avoid such message.

**Comment by carlosperate** [comment]
The `en` file is generated from the `messages` file (this file contains the original strings that can later be translate to the multiple languages), so only one of those files should be included in a Blockly implementation, not really creating any clashes.

**Comment by Kaworru** [comment]
Lets assume you get the Blockly Source code as it is, use the Closure compiler to compile Blockly.
It will throw you this error message, because of the pre-generated files.

To avoid something like this I see the following possibilities:
1.) Excluding the generated files from the source code
2.) Use another namespace for the single messages.js files
3.) Separate the source code (to use it in other projects) from the version with pre-generated files.

**Comment by fly7632785** [comment]
hi, could you tell me how to change the different language. Is it  by changing or adding file msg/js/xx.js?

**Comment by samelhusseini** [comment]
Blockly.Msg.en is no longer provided with the removal of closure. Closing.
