### ISSUE TITLE
Workspace comments: Code generation

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1674]
### Problem statement
What should workspace comments look like in generated code?

My first thought is that they should obey the same rules as blocks (sweep top to bottom, left to right (in LTR)), and just be formatted however comments are formatted in that language.Are there other intuitive ways to place them?

**Comment by maribethb** [comment]
Linked to https://github.com/google/blockly-samples/issues/827

Closing, can be addressed in samples
