### ISSUE TITLE
FieldInput on Win10: Overlay editor does not disappear when the user scrolls

### ISSUE THREAD

**Issue by valfis86** [google/blockly#1685]
### Problem statement

The FieldInput editor overlay does not disappear when the user interacts with the scrollbars ("inbuild scrollbars"?). Further, the overlay does not scroll with the workspace, leaving it disconnected.

![grafik](https://user-images.githubusercontent.com/19908672/36887468-ae101376-1df1-11e8-9bf6-bde8272e9ebc.png)

### Expected Behavior

The overlay should disappear as soon as the user scrolls or interacts with the scrollbar.

### Actual Behavior

The editor overlay remains visible and does not scroll with the workspace.

### Steps to Reproduce

Click into a textfield of a block (e.g. the number block) opens a small overlay to edit the current value. This overlay behaves incorrect if the blockly workspace is scrolled using the inbuild scrollbars. When scrolling the workspace the corresponding block changes its position as expected, but the overlay doesn't.

### Operating System and Browser

Tested with the february release of blockly on a Windows 10 machine with Firefox 58 and Chrome 64.

**Comment by AnmAtAnm** [comment]
> **Expected Behavior**
> 
> The overlay should change its position when the workspace is scrolled. When navigating away from the page where the blockly workspace is shown all overlays should dissapear.

I believe the overlay should disappear as soon as the user scrolls or interacts with the scrollbar.  This is the behavior I see on Mac Chrome.

Marking this a bug, but I have not tested on Win10 yet.

**Comment by AnmAtAnm** [comment]
I've split out the sizing issue to #1688, and rewrote the above issue to describe only the scrolling issue.

**Comment by RoboErikG** [comment]
@rachel-fenichel to repro

**Comment by samelhusseini** [comment]
Tested on v3.20200123.1 and it doesn't repro. Tested on Windows 10 with IE11 and Chrome.
