### ISSUE TITLE
FieldInput size does not account for text representation in preloaded workspace.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1688]
### Problem statement

With some cases of a workspace with blocks loaded that include a text field, the field does not render with space for the value text.

![grafik](https://user-images.githubusercontent.com/19908672/36887820-24d76904-1df3-11e8-81c3-f9583e017472.png)

(Separating an issue reported in #1685)

### Expected Behavior

The field should should size appropriately to account for the field value.

### Actual Behavior

The field is sized as if there is no text value. The text value is rendered by extends beyond the bounds of the field.

### Steps to Reproduce

1. Create a web application with two pages, the first page has a link to a second page with the blockly workspace
2. The blockly workspace should display the buildin scroll bars, the math blocks should be visible in the toolbox
3. Launch the application and navigate to the page with the blockly workspace.
4. Drag a basic math number block into the workspace and click the displayed "0". An overlay appears to edit the value.
5. Scroll the workspace using the mouse wheel => the overlay does not move.
6. Navigate back one page => the overlay is still visible.

Alternative:
1. Open the blockly developer tools where new blocks can be created.
2. Click the hue field to change the blocks color
3. Without changing the value click on the "Block Exporter" tab
4. Submit the "unsaved changes" dialog
5. Navigate back to the "Block Factory" tab => the hue value is incorrectly aligned in its corresponding block.

### Operating System and Browser

 * Desktop Chrome (Mac and Win10)
 * Desktop Firefox (Win10)

**Comment by RoboErikG** [comment]
@samelhusseini to confirm fixed
