### ISSUE TITLE
Deprecated lua code is generated

### ISSUE THREAD

**Issue by valfis86** [google/blockly#1695]
### Problem statement

There is a block with mathematical instructions such as "square root" and "absolute". This block also offers "log10" and "10^". When these instructions are used to generate lua code this code doesn't work with lua version 5.3 because the methods "math.pow" and "math.log10" were removed. 

### Expected Behavior

The lua methods "math.pow" and "math.log10" shouldn't be used. Instead use "x^y" and "math.log(x, y)".

### Actual Behavior

Lua code using methods that do not exist in current version is generated.

### Steps to Reproduce

Generate lua code from a workspace using the instructions "10^" and "log10".

**Comment by NeilFraser** [comment]
Using the latest version of Lua:

```
$ lua
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
> math.pow(2, 4)
16.0
> math.log10(42)
1.6232492903979
> 
```

Seems to work.  Can you clarify the Lua version in which this breaks?  Thanks.

**Comment by NeilFraser** [comment]
I see that math.log10 was deprecated in 5.2, and math.pow was deprecated in 5.3, but Lua appears to be preserving backwards compatibility (bless it, such a rare thing these days).  While I don't see the error, I agree that the generators should be updated as described.

PR #1696 fixes this, and the unit tests pass:

```
........................................................

Number of tests run: 56
```

**Comment by NeilFraser** [comment]
Fixed.
