### ISSUE TITLE
Number field: change the value via mouse drag

### ISSUE THREAD

**Issue by seldomU** [google/blockly#1701]
### Problem statement

For scripts that are evaluated after each edit, number fields would be more useful if the user could adjust their value by dragging the mouse (like an invisible slider). 

Maybe this behaviour could be activated when a mouse down event happens inside a number field.

**Comment by AnmAtAnm** [comment]
Now that [Blockly.Field.register(..)](https://developers.google.com/blockly/reference/js/Blockly.Field#.register) is official, this is something that can be done as a Blockly experiment, either overriding the `field_number` type, or creating completely new field. Once such a experiment has been demonstrated, we can consider whether this is a feature we want to include and support in our core code.

**Comment by rachel-fenichel** [comment]
We have a slider field available as a plugin now: https://github.com/google/blockly-samples/tree/master/plugins/field-slider

Demo: https://google.github.io/blockly-samples/plugins/field-slider/test/index.html

And on npm: https://www.npmjs.com/package/@blockly/field-slider

**Comment by rachel-fenichel** [comment]
![image](https://user-images.githubusercontent.com/13686399/93818690-87b95300-fc0f-11ea-91ad-b9ae15e59fc1.png)
