### ISSUE TITLE
Get rid of code that handles Safari 7.1.3

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1714]
In xml.js, there's a [comment](https://github.com/google/blockly/blob/develop/core/xml.js#L385):
```
  // Safari 7.1.3 is known to provide node lists with extra references to
  // children beyond the lists' length.  Trust the length, do not use the
  // looping pattern of checking the index for an object.
  var childCount = xml.childNodes.length;
```

Safari 7.1.3 is effectively deprecated now.  We're also not consistent with this approach across the rest of Blockly.  We should just look at the actual node list.

@NeilFraser if you object, speak now.

**Comment by NeilFraser** [comment]
https://groups.google.com/forum/#!searchin/blockly/safari$20nodelist%7Csort:date/blockly/-9d_OkvKBSQ/R-u59W2q4DoJ

**Comment by NeilFraser** [comment]
The bug (as described in the above post) does not exist in Safari 11, or any other browser I have immediate access to.  However the poster reported it failing on Safari 8 and at the time I confirmed it to also fail on Safari 7.

I don't know when it was fixed: Safari 9, 10, or 11.
