### ISSUE TITLE
Workspace comments: show delete cursor when drag to delete on toolbox

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#1725]
Show the delete cursor (hand delete) when deleting a comment by dragging onto the toolbox. 
It currently only works when deleting using the trash can.

**Comment by picklesrus** [comment]
You may already have a plan for how to do this, but in case not, here's the code for how we do it with blocks:
https://github.com/google/blockly/blob/e0be7e498b2ea76cb76faea0aff29220cfc077af/core/block_svg.js#L1262

And the dragger code that sets it: https://github.com/google/blockly/blob/e0be7e498b2ea76cb76faea0aff29220cfc077af/core/block_dragger.js#L275

**Comment by samelhusseini** [comment]
Yeah, so I tried doing that in my PR: https://github.com/google/blockly/pull/1720/files#diff-42a3492b344590b48a95aac6c87ab44cR166

but it only worked for me when dragging over the trash icon and not the toolbox. Unsure why. 
Opened this issue to track this.

**Comment by picklesrus** [comment]
Ah! I forgot about the toolbox being slightly special :-/ .  IIRC, the toolbox is z-ordered above the block so setting the cursor style on the block doesn't really do anything.  There's also this in start and end drag:
https://github.com/google/blockly/blob/e0be7e498b2ea76cb76faea0aff29220cfc077af/core/block_dragger.js#L173
https://github.com/google/blockly/blob/e0be7e498b2ea76cb76faea0aff29220cfc077af/core/block_dragger.js#L231

**Comment by samelhusseini** [comment]
Ah! That looks useful. I'll looking into it.

**Comment by samelhusseini** [comment]
Yep that fixed it. Thanks! Closing, and will fix in PR.
