### ISSUE TITLE
workspace comments: trim comment xml or fix formatter

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#1730]
Should Blockly trim comment textContent when loading from XML?

If you have any formatted xml using: 
```
Blockly.Xml.domToPrettyText(dom);
```
It formats a multi line comment like so: 
```
<xml>
  <comment h="120" w="160" id="#S_Ql:Z+rU1l!%41i$-V" x="364" y="200">Say something...

Hello world
  </comment>
</xml>
```

For starters I see no reason to add the new line there, since it's a simple tag (leaf node), but I think the very simple formatter in Blockly is missing that case.

Since it adds an extra new line and 4 characters, these characters will now be part of the comment text. 

So two possibilities here, either the domToPrettyText function is fixed to account for simple tags containing new lines, or we just trim textContent before creating the comment text from xml.

**Comment by rachel-fenichel** [comment]
Conclusion after discussion: we should fix the `domToPrettyText` function--better to fix this on save than to try to guess the right thing on load.

**Comment by BeksOmega** [comment]
The new JSON system properly handles multiline comments, and the XML system is being iceboxed, so I'm closing this.
