### ISSUE TITLE
image dropdown documentation improvement

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#1750]
The examples on this page (https://developers.google.com/blockly/guides/create-custom-blocks/dropdown-menus#images) refer to a variable "input" that isn't actually defined anywhere in the example.

If you copy/paste the code it won't work.  We should either expand the example to make the code copy/paste-able or add some kind of indication ( comments, ..., etc) that the developer is already expected to have an input by the time they get to this point in their code.

**Comment by rachel-fenichel** [comment]
Closing since we redid this documentation.
