### ISSUE TITLE
NPM Blockly package is out of date

### ISSUE THREAD

**Issue by Marclev78** [google/blockly#1764]
The version of Blockly published to NPM is one year old, meaning it hasn't got things like Extensions, and any other things that have been added / fixed since then.

Is there a reason that a more recent version has not been published?

https://www.npmjs.com/package/blockly

**Comment by rachel-fenichel** [comment]
We do not own that package.

**Comment by NeilFraser** [comment]
For what it's worth, there's a more recent package here:
https://www.npmjs.com/package/google-blockly

We do not own that package either.  :)

**Comment by mattrei** [comment]
I see. But why don't you publish/maintain an official package on npmjs.com then? Would be helpful for many people.

**Comment by rachel-fenichel** [comment]
Because blockly isn't a single thing.  It includes the core libraries, the block definitions (not everyone uses all of them) and the block translations (english, french, etc).  We don't want to have a separate package for each combination of those things.
