### ISSUE TITLE
\\n generated instead of \n

### ISSUE THREAD

**Issue by Sajdkick** [google/blockly#1779]
### Problem statement

I've encountered a bug when implementing Blockly with Unity. I'm using   [UniWebView](https://uniwebview.com/) to show a local html file containing Blockly. It works fine when i run it in the editor, or when i run the html file on its own. But when i build to android this happens:

### Expected Behavior

Windows (Works):
if jumpCount > 0 then _**\\n**_    if not jumped and input.jump then **_\\n_**   ...

### Actual Behavior

Android (Doesn't work):
if jumpCount > 0 then _**\\\\n**_    if not jumped and input.jump then **_\\\\n_**   ...

### Steps to Reproduce

1. Open a Blockly workspace locally using [UniWebView](https://uniwebview.com/).
2. Generate Lua code by calling Blockly.Lua.workspaceToCode(workspace);

### Operating System and Browser

* Smartphone/Tablet/Chromebook (please complete the following information):
  * Device: [e.g. Samsung Galaxy A5]
  * OS: [e.g. Android version 7.0]
  * Browser [Samsung Internet 6.4.10.5/Google Chrome 65.0.3325.109]

**Comment by AnmAtAnm** [comment]
This sounds like you have not correctly escaped the code string when passing it in or out of the web view. We do not have any examples of using web blockly with a mobile web view, and we have no experience with UniWebView.

Please feel free to ask this on the larger [community forum](https://groups.google.com/forum/#!forum/blockly).
