### ISSUE TITLE
Block focus switch glitch on Chrome

### ISSUE THREAD

**Issue by HendrikD** [google/blockly#178]
![bug](https://cloud.githubusercontent.com/assets/932437/9908348/831fc412-5c93-11e5-9a44-6b4bfdfa5015.gif)

When hovering over a textfield while selecting text inside another the focus switches to that block.
I was able to produce this in a normal windows chrome 45.0.2454.85 m and an embedded chromium version 31.8. However, In firefox 40.0.3 the focus is not switching.

**Comment by NeilFraser** [comment]
Sneaky.  Confirming on OS X too.

**Comment by NeilFraser** [comment]
This bug is no longer reproducible on OS X.  I'm assuming that it was fixed by the Chrome team.
