### ISSUE TITLE
Input connection move events do not undo fully

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1780]
### Problem statement

If a move event results in a connection, undoing the connection will not move the block back to its original location.

#### Before
<img width="364" alt="screen shot 2018-04-13 at 3 54 27 pm" src="https://user-images.githubusercontent.com/9916202/38760873-747c143a-3f33-11e8-8609-bca30953cf87.png">

#### After Move
<img width="383" alt="screen shot 2018-04-13 at 3 54 37 pm" src="https://user-images.githubusercontent.com/9916202/38760877-7b0d10e2-3f33-11e8-808d-4858a74f4250.png">

#### After Undo
<img width="389" alt="screen shot 2018-04-13 at 3 54 49 pm" src="https://user-images.githubusercontent.com/9916202/38760882-82e826bc-3f33-11e8-8f36-5bd166aa011d.png">

### Expected Behavior

The moved block should not only disconnect, but move back to its original location (below the text block, in the above example).

### Actual Behavior

The moved block disconnects, and bumps slightly (less than a normal full bump) from the previously connected block.

### Steps to Reproduce

1. Start with two blocks on the workspace, one with an input and another that is a valid output.
2. Drag the output block into the input.
3. Immediately undo the move (Ctrl+Z or Cmd+Z).

The behavior is similar when undoing a connection between next and previous connections.

The behavior does not depend on the presence of a shadow block in the input.

### Playground event log

<img width="1110" alt="screen shot 2018-04-13 at 4 08 10 pm" src="https://user-images.githubusercontent.com/9916202/38761107-0822613e-3f35-11e8-91c2-def547052966.png">

Note that the new coordinate of the move triggered by the undo is identical to the old coordinate of the original move, even though the behavior on the workspace does not reflect this.

### Operating System and Browser

 * Desktop Chrome

**Comment by jlaurens** [comment]
Here is an explanation of the problem and how I solved it.

1) When you disconnect a block, there are 2 Move events recorded on the undo stack, but when you connect a block, only one event is recorded. In fact, 2 events are created and fired but they are merged by the `Blockly.Events.filter` method. This method has a correct behaviour, only the events created when connecting are malformed. Let us see why.

2) When disconnecting a block, the drag manager starts by unplugging the block, which results in firing a first move event, then another move event is fired to record the drag movement.

3) when connecting, see what happens from [this code](https://github.com/google/blockly/blob/7679d227df8f62a12316334ee708d4a9a800ef17/core/block_dragger.js#L224) from lines 224 to 229

```
    this.draggingBlock_.moveConnections_(delta.x, delta.y);
    this.draggingBlock_.setDragging(false);
    this.draggedConnectionManager_.applyConnections();
    this.draggingBlock_.render();
    this.fireMoveEvent_();
    this.draggingBlock_.scheduleSnapAndBump();
```

In `applyConnections` at line 226, an event is created while connecting, and in `fireMoveEvent_` at line 228, another event is created for dragging. These are created in the same order than when disconnecting, this is weird.
The second move event properly records the location where the dragging starts, but it also records the information about its connection, which has occurred after the drag ends ! This second event is then malformed and fired too lately. For this reason, it is merged with the connect event, and the resulting event no longer knows about the start of the drag. When undoing, the block never comes back to its original location.

The solution is to fire the move events in the proper order. For that, one solution is to call `fireMoveEvent_` just before `applyConnections`like this

```
    this.draggingBlock_.moveConnections_(delta.x, delta.y);
    this.draggingBlock_.setDragging(false);
    this.fireMoveEvent_(); // Move here
    this.draggedConnectionManager_.applyConnections();
    this.draggingBlock_.render();
//    this.fireMoveEvent_();
    this.draggingBlock_.scheduleSnapAndBump();
```

HTH

**Comment by AnmAtAnm** [comment]
Thank you @jlaurens for digging into this.

**Comment by rachel-fenichel** [comment]
I tried moving the call to `fireMoveEvent_` to before `applyConnections`.  The result was that the block moved, but too far.  I'll keep looking.
