### ISSUE TITLE
Cannot add shadow block children in Block.init() fucntion

### ISSUE THREAD

**Issue by overklok** [google/blockly#1784]
### Problem statement

I use JSON format for defining blocks with different fields, and I should use some set of JavaScript instructions to specify complex shadow fields. So I wrote a special function for this:

```javascript
/**
 * @param {BlockSvg} block_svg      parent block that should contain a shadow block
 * @param {string} input_name       name of the input to be replaced
 * @param {string} block_name       name of the block to be used for replacing
 */
function appendShadowBlock(block_svg, input_name, block_name, block_value) {
    // create new block in the same workspace as the parent block (flyout's workspace)
    let shadowBlock = block_svg.workspace.newBlock(block_name);
    // make this block shadow
    shadowBlock.setShadow(true);
    // render it
    shadowBlock.initSvg();
    shadowBlock.render();
    
    // get an output connection 
    let ob = shadowBlock.outputConnection;
    // get an input connection 
    let cc = block_svg.getInput(input_name).connection;

    // then connect
    cc.connect(ob); // calling this function causes an error (see Expected Behavior)
};
```

based on [this solution](https://groups.google.com/forum/#!topic/blockly/krWiGqYNf_s).

Then I used it in the JSON definition of the blocks which should contain shadow fields like this:
```
Blockly.Blocks['math_number_brightness'] = {
    init: function() {
        this.jsonInit(/*some JSON here*/);
    }
};

Blockly.Blocks['set_brightness'] = {
    init: function() {
        this.jsonInit(/*some JSON here*/);
        appendShadowBlock(this, "/*name of argument specified in JSON*/", "math_number_brightness");
}
```

Works well with Blockly versions before d73337a commit.

### Expected Behavior

Can integrate different kinds of blocks as shadow inputs:
![2018-04-16 16 14 05](https://user-images.githubusercontent.com/12893923/38806034-70895846-4191-11e8-811d-d93d9efdd4e5.png)

replace shadow blocks with originals:

![2018-04-16 16 17 16](https://user-images.githubusercontent.com/12893923/38806125-acbea028-4191-11e8-9348-085ced65156c.png)

etc.

### Actual Behavior

Toolbox is empty:
![2018-04-16 16 20 17](https://user-images.githubusercontent.com/12893923/38806254-1de44870-4192-11e8-94ad-52b6a38594e5.png)

### Steps to Reproduce

1. Create an HTML file with the following content: [index.html](https://gist.github.com/overklok/94812259bc9bd8a199ecb8a9f807fe0b),
2. Clone Blockly repository to the same folder with this HTML file,
3. Open this file in the browser.

### Stack Traces

```
dom.js:1207 Uncaught TypeError: Cannot read property 'firstChild' of undefined
    at Object.goog.dom.removeChildren (dom.js:1207)
    at Blockly.FieldLabel.Blockly.Field.render_ (field.js:314)
    at Blockly.FieldLabel.Blockly.Field.getSize (field.js:402)
    at Blockly.BlockSvg.renderCompute_ (block_render_svg.js:443)
    at Blockly.BlockSvg.render (block_render_svg.js:304)
    at Blockly.BlockSvg.render (block_render_svg.js:312)
    at Blockly.FieldDropdown.Blockly.Field.forceRerender (field.js:490)
    at Blockly.BlockSvg.updateColour (block_svg.js:1038)
    at Blockly.BlockSvg.initSvg (block_svg.js:149)
    at Object.Blockly.Xml.domToBlock (xml.js:488)


  | goog.dom.removeChildren | @ | dom.js:1207
  | Blockly.Field.render_ | @ | field.js:314
  | Blockly.Field.getSize | @ | field.js:402
  | Blockly.BlockSvg.renderCompute_ | @ | block_render_svg.js:443
  | Blockly.BlockSvg.render | @ | block_render_svg.js:304
  | Blockly.BlockSvg.render | @ | block_render_svg.js:312
  | Blockly.Field.forceRerender | @ | field.js:490
  | Blockly.BlockSvg.updateColour | @ | block_svg.js:1038
  | Blockly.BlockSvg.initSvg | @ | block_svg.js:149
  | Blockly.Xml.domToBlock | @ | xml.js:488
  | Blockly.Flyout.show | @ | flyout_base.js:455
  | Blockly.WorkspaceSvg.updateToolbox | @ | workspace_svg.js:1328
  | updateToolbox | @ | index.html:58
  | (anonymous) | @ | index.html:157
```

### Operating System and Browser

* Desktop Chrome
* Desktop Firefox
* Desktop Safari

### Additional Information

I know that [the guide](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks) says that JSON format is not able to define advanced features, and I can use an XML format for this purposes, but I reported this just because this method worked well earlier (before commit d73337a).

**Comment by AnmAtAnm** [comment]
By calling `appendShadowBlock()` within `init()`, you are adding children before the parent block is finished initializing (before `init` returns). This is not a supported configuration, as there may be additional configuration called by the framework.

You can probably do something similar by calling `appendShadowBlock()` in a timeout, by calling `setTimeout()` in `init()`.
