### ISSUE TITLE
Move media/test_*.png to media/tests/*.png

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1785]
No reason to have them mixed up with the rest of the media files.

https://github.com/google/blockly/tree/develop/media

**Comment by NeilFraser** [comment]
Suggest moving them out of `/media`, and into a subdirectory of `/tests`.

**Comment by AnmAtAnm** [comment]
These files are to test remote image references.  They are place there so they will be put on the server.  If we move them, they will need to be reuploaded to the serve and the URLs in test_blocks will need to be updated.

**Comment by rachel-fenichel** [comment]
That's fine by me.  The current configuration means that they end up in the media folder for all forks, and they mix up with media files that belong to that fork.  I think they should be off on the side to reduce clutter for forks.
