### ISSUE TITLE
Automated build for the project

### ISSUE THREAD

**Issue by pawelkrupinski** [google/blockly#180]
Occasionally people make changes but don't check in the compiled / compressed files to the repo. 
I think it makes sense to automate the process (possibly uploading the files somewhere else so the build doesn't trigger itself again by checking in).

**Comment by NeilFraser** [comment]
I typically withhold checking in blockly_compressed.js when the changes are minor.  This is done in deference to GitHub, who probably appreciate the reduction in churn.

**Comment by pawelkrupinski** [comment]
If the churn is the problem, the files can be uploaded somewhere else.
I just don't see any upside to doing it manually.
