### ISSUE TITLE
Flyout blocks are highlighted on mouseover when the workspace is being dragged

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1801]
### Problem statement
Flyout blocks are highlighted on mouseover when the workspace is being dragged

### Expected Behavior
Flyout blocks should not highlight if the workspace is being dragged.

### Steps to Reproduce

1. open the playground with a simple toolbox
2. drag the workspace around, and move the mouse pointer over a block in the flyout.

## To Fix

Modify the [`addBlockListeners_`](https://github.com/google/blockly/blob/dc61e487b4e0024a53866e8aff652c0b108a0340/core/flyout_base.ts#L970) method to check if `this.targetWorkspace.isDragging` before calling `addSelect` or `removeSelect` on the block.

**Comment by neerajkumarc** [comment]
working on it!
