### ISSUE TITLE
Safari: Simple horizontal toolboxes do not show cursors during drag

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1805]
### Problem statement

In Safari (works in Chrome and Firefox), the `handdelete` cursor does not show in workspaces with the simple horizontal toolboxes. Includes when hovering over the trashcan.

### Expected Behavior

The `handdelete` cursor should show when dragging a workspace block over the trash can or toolbox.

### Steps to Reproduce

1. Open the [multi-playground in simple mode](https://blockly-demo.appspot.com/static/tests/multi_playground.html?toolbox=simple) in Safari.
2. In any of the horizontal workspaces (bottom four), drag a block to the workspace.
3. Drag the block over the toolbox. Note the lack of the handdelete cursor.
4. Drag the block over the trash can. Note the lack of the handdelete cursor.

This works in the vertically oriented toolboxes, in the category toolboxes, in Chrome, and in Firefox.

### Operating System and Browser

 * Desktop Chrome (Mac: works)
 * Desktop Firefox (Mac: works)
 * Desktop Safari (Mac: broken!)

**Comment by picklesrus** [comment]
FYI Safari loses the cursor altogether during drag, whether it is the hand-delete or the closed hand. But only with simple toolboxes/flyouts. <3 browsers.

**Comment by AnmAtAnm** [comment]
Ah, yes, there is also no `handclosed` cursor in these workspaces with simple, horizontal toolboxes.  Other cases are still fine.

**Comment by gonfunko** [comment]
This no longer repros.
