### ISSUE TITLE
Category selected UI event has null element

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#1810]
Looks like this recent change makes the assumption that an event with no block will use fromJson to fill in its attributes
https://github.com/google/blockly/commit/453fa014c701a92db7f8989ac40fb525fd5673fa

but that's not the case here: https://github.com/google/blockly/blame/master/core/toolbox.js#L583

### Problem statement

Category UI events have no content (category name)

### Expected Behavior

event.element should be set to the old category name (i think)

### Actual Behavior

event.element is empty

### Steps to Reproduce

1. Open playgrounds and enable event logging
2. Select categories in the toolbox. 
3. You'll see empty ui events with just the workspaceId set. 

### Operating System and Browser
All

### Additional Information

Affects master and develop

**Comment by rachel-fenichel** [comment]
That fix seems fine.  I haven't yet decided whether to split UI events.

**Comment by NeilFraser** [comment]
Issue #1825 shows how to recreate the original behaviour on an old build of Blockly.

**Comment by rachel-fenichel** [comment]
@NeilFraser does Sam's suggested fix work for you?

**Comment by NeilFraser** [comment]
That works for what I need it for in Blockly Games.  Though it's worth noting that it misses three other field that used to be populated:
```
  group: ""
  oldValue: Category name or null
  recordUndo: false
```
