### ISSUE TITLE
Offline compilation

### ISSUE THREAD

**Issue by pantoninho** [google/blockly#1811]
I've wrapped Blockly inside a node package (like node-blockly) for my own project. Blockly's source code is heavily modified and I have to compile it every time I make changes.
The necessity of having a network connection plus the limit imposed by google severely impacts the productivity.

Is it possible to compile blockly offline?

I've also tried replacing the current build process with webpack without success (closure-compiler module system does not play well with commonjs...), but I'm also open to suggestions on this.

Thanks and congratulations on this project.

**Comment by rachel-fenichel** [comment]
Yes, it's always been possible to use the closure compiler offline.

As of this release, we've got a build script to get you started: https://github.com/google/blockly/blob/master/local_build/local_build.sh

More information on the closure compiler: https://developers.google.com/closure/compiler/
