### ISSUE TITLE
Should user facing block counts include shadow blocks?

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1822]
The workspace context menu includes an option to delete all blocks, with a block count. Currently this includes a shadow blocks:

![screen shot 2018-04-23 at 4 27 50 pm](https://user-images.githubusercontent.com/9916202/39158173-59cb79ea-4713-11e8-95dd-4bd2dd90a469.png)

Since the user can't manipulate the shadow blocks (other than fields), should the shadow block be included in the count? In the above case, the user only dragged one block from the toolbox.

Or maybe the count rule needs to be more specific: Should the block count include external shadow blocks, but exclude internal shadows. This would match how text and number blocks treat themselves as independent blocks with respect to tooltips.

**Comment by NeilFraser** [comment]
I don't really have an opinion on this.

However, if the count changes, please ping me since a lot of the level evaluation in Blockly Games relies on block counts.  It's no problem, I'll just have to change some constants, but I'll need to know about it promptly.

**Comment by rachel-fenichel** [comment]
I think that shadow blocks should count as blocks, since if you put the same block over it (in a slightly different colour) it would count.

In scratch-blocks shadows don't count because they are rendered so differently that it's harder to notice that they are distinct blocks (and intentionally so).

**Comment by rachel-fenichel** [comment]
It would be a breaking change to modify how we count the number of blocks in stacks, and we haven't seen any follow-up requests.

Closing as wontfix.
