### ISSUE TITLE
Support colour attribute in toolbox dynamic categories.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1832]
### Problem statement

The toolbox categories can have a `colour=` attribute. Dynamic categories dynamically generate the `<category>` contents.  Make sure the `colour=` attribute can also be defined via the dynamic category function. (It may already work, but have not been tested).

At the same time, make sure any `colour=` applied in the static XML continues to work if no `colour=` is defined in the dynamic XML. For example, the dynamic variables category should remain purple in the demos, with adding the `colour=` to the dynamic XML.

Add a test case that includes and changes the `colour=` assignment in a dynamic category.

**Comment by sachan13harshit** [comment]
@AnmAtAnm please assign this issue to me

**Comment by BeksOmega** [comment]
Since we're moving towards doing styling with CSS I'm going to close this.
