### ISSUE TITLE
Remove Closure from Block Factory

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1834]
### Problem statement

BlockFactory is not a closure-compiled demo, but it is peppered with `goog` calls: provides, require, and a color picker. Replace this code to eliminate issues like https://github.com/google/closure-library/issues/897.

Consider https://neil.fraser.name/software/colourpicker/ as a color picker replacement.

### Expected Behavior

Code that is never compiled with Closure should not include `goog.require` and `goog.provide` statements.

Block Factory should not depend on Closure's color picker, since it is not compiled to ensure dependencies are correctly linked/available.

Recompiling main Blockly libraries, if successful, should not change whether Block Factory runs.

### Actual Behavior

Recent changes in Closure broke Block Factory, even though the compilation step succeeded. 

See https://github.com/google/blockly/issues/1830

**Comment by jplaisted** [comment]
You can use Closure Library without compiling, it has its own code loader. So long as you specify you dependencies correctly via `goog.addDependency` calls it will load fine. Though I suppose this less and less recommended these days, with compilation or bundling being more recommended.

**Comment by AnmAtAnm** [comment]
@jplaisted Yes, you are right and this is how we generally use Closure in the playground and the Block Factory to date. However, our real dependencies are limited to a simple color picker that can easily be replaced.  Therefore, it is worth simplifying.

**Comment by jplaisted** [comment]
Ah, thanks for the clarification. Makes sense.

**Comment by AnmAtAnm** [comment]
Part of #1072

**Comment by AnmAtAnm** [comment]
Dupe of #668
