### ISSUE TITLE
Add atan2 support

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1835]
### Problem statement

Programming with angles often uses `atan2(y,x)` instead of `atan(y/x)`, but Blockly currently doesn't have such a block.

 - [ ] Add `math_atan2` block with two inputs to [`blocks/math.js`](https://github.com/google/blockly/blob/master/blocks/math.js)
 - [ ] Add `math_atan2` JavaScript generator to [`generators/javascript/math.js`](https://github.com/google/blockly/blob/master/generators/javascript/math.js)
 - [ ] Add `math_atan2`Dart generator to [`generators/dart/math.js`](https://github.com/google/blockly/blob/master/generators/dart/math.js)
 - [ ] Add `math_atan2`Lua code generator to [`generators/lua/math.js`](https://github.com/google/blockly/blob/master/generators/lua/math.js)
 - [ ] Add `math_atan2`PHP code generator to [`generators/php/math.js`](https://github.com/google/blockly/blob/master/generators/php/math.js)
 - [ ] Add `math_atan2` Python code generator to [`generators/python/math.js`](https://github.com/google/blockly/blob/master/generators/python/math.js)
 - [ ] Add the new block to the all demos with a full Math toolbox category, including the various playgrounds.
 - [ ] Add test case for `math_atan2` to generator unit tests (blocks defined in [`tests/generators/math.xml`](https://github.com/google/blockly/blob/master/tests/generators/math.xml))

Because of the way the code generators are tested, all language implementations must exist for a pull request to be accepted into master.

**Comment by nadyafebi** [comment]
I'd like to help with this issue. Will be sending a pull request in a day or two 👍

**Comment by AnmAtAnm** [comment]
Thanks @nadyafebi!!

**Comment by rachel-fenichel** [comment]
@AnmAtAnm I think this is ready to close.  Please confirm.
