### ISSUE TITLE
"If" statement mutators crash Safari

### ISSUE THREAD

**Issue by acbart** [google/blockly#184]
This week has been exciting, and not in a great way. An instructor found that doing most actions in Blockly on Safari|Mac crashed the browser with a stack trace like this:

![hardcoremaccrash](https://cloud.githubusercontent.com/assets/897227/10036738/96a4f6fc-6179-11e5-9707-802b6879ac1f.jpg)

We upgraded to the latest version of Blockly (we had last upgraded near the start of August) and the problem disappeared... Almost. We can still trigger the crash if you add an "else" statement to a mutator on a page with multiple instances. I'm not sure what specific call does it, since I don't have easy access to a testing computer. However, I've been able to get two people to replicate it.

You can test this on the following canvas (this only occurs in Safari): https://dl.dropboxusercontent.com/u/23141976/google-blockly-2d60d94/google-blockly-2d60d94/demos/generator/index.html

I have suspicions that the following pull managed to fix most of the original problems, but I'm not sure: https://github.com/google/blockly/pull/159

**Comment by NeilFraser** [comment]
Confirming.  Safari on Mac gets very unhappy (up to and including crashing) when there are two Blockly instances on the same page and an mutator is used in the first Blockly instance.

This smells like somewhere there's a global reference to the root SVG object that needs to be isolated...

**Comment by NeilFraser** [comment]
I'm still tracking this down, attempting to get a minimal test case.  But it is not looking good.  Miniscule CSS changes can make the bug appear or disappear.  This does not appear to be an issue in Blockly at all.  It appears that something is badly wrong with Safari's rendering engine.

**Comment by NeilFraser** [comment]
Fixed.  There is still a crasher bug in Safari, but the changes I've made appear to eliminate that code path.  My initial hunch was correct, there was a shared filter between both SVG objects.

**Comment by NeilFraser** [comment]
Completed minimal test case and filed bug.  This affects the latest Webkit nightly.  https://bugs.webkit.org/show_bug.cgi?id=149613
