### ISSUE TITLE
I can't found generator code of declaration of a new variable when I set a item to it

### ISSUE THREAD

**Issue by johnrong** [google/blockly#1842]
### Problem statement

I use the block "variable_set" in variables category  ,connecting with a  custom block. But I can't declare a custom variable as I want 。
 
### Expected Behavior
when connecting with new block ，the block “variable_set" in  in variables category should allow my declaration of new variable, not just basic type like,int ,String ,or var in javascript. and I wanna know where variable is declared or variable type is stored 

### Steps to Reproduce

1. Start by..
2. Next, do..

### Stack Traces

```
Replace with error stack trace.
```

**Comment by AnmAtAnm** [comment]
The [`VariableMap`](https://developers.google.com/blockly/reference/js/Blockly.VariableMap) (available from [`workspace.getVariableMap()`](https://developers.google.com/blockly/reference/js/Blockly.Workspace#getVariableMap)) contains all the variable information.

The `variable_get` and `variable_set` in [`blocks/variables.js`](https://github.com/google/blockly/blob/master/blocks/variables.js) do not have type (which used by `<category custom="VARIABLES">` toolboxes). To use [typed variables](https://developers.google.com/blockly/guides/create-custom-blocks/variables#typed_variable_blocks), you will need to construct a custom toolbox and use [`blocks/variables_dynamic.js`](https://github.com/google/blockly/blob/master/blocks/variables_dynamic.js).

Even then, we only have generators for dynamic languages with untyped variables. The type information does not propagate to user code.

(In the future, please use our [community forum](https://groups.google.com/forum/#!forum/blockly) for questions about the code and similar support requests.)
