### ISSUE TITLE
[Improvement] Make flyout in toolbox without categories close when clicking outside it and autoClose=true

### ISSUE THREAD

**Issue by Bohdan-Tereta** [google/blockly#1852]
### Problem statement

Make flyout close when clicking outside it and autoClose=true. That's usefult, when flyout is turned on/off by some external menu. 
When toolbox has categories, clicking outside flyout hides it.
When toolbox has no categories and aoutoClose = true, flyout isn't closed when clicking outside it but only when creating a block from it. 

### Expected Behavior

Click outside flyout  with autoClose = true and it hides

### Actual Behavior

Click outside flyout  with autoClose = true and nothing happens

### Steps to Reproduce

1. Create flyout in toolbox without categories
2. Click outside it

### Stack Traces

No errors in console

### Operating System and Browser

Desktop Chrome, latest, not tested in other browsers

### Additional Information

Possible fix: 

add 

     if (workspace.flyout_ && workspace.flyout_.autoClose) {
       workspace.flyout_.hide();
     }

to hideChaff() in blockly.js

**Comment by rachel-fenichel** [comment]
Thanks for the issue!

I'd like to discuss this with the team to decide if we want to implement it.

Pros:
- It's very simple code
- Obviously at least one developer wants it

Cons:
- Adding a code branch that will rarely be hit leads to code rot
- Similar behaviour is available by making a category toolbox that only has one category
  - Similar, but not exactly the same

@AnmAtAnm @picklesrus what are your thoughts?

**Comment by Bohdan-Tereta** [comment]
Thank you for checking
Some of my thoughts:
1. Without this improvement autoClose behaviur is inconsistent (why should it depend on whether there are categories inside toolbox?)
2. Creating toolbox with a single category sometimes is not an option. Let's say, I have external menu for block categories somewhere outside blockly. I want to populate the flyout with blocks when selecting an entry in that external menu. Why should I display a category name again inside toolbox if it's already displayed in the menu? A toolbox without categories works perfect in that case.

**Comment by picklesrus** [comment]
The request is for a way to hide the simple flyout, right?
I haven't thought about the technical part yet...mostly because these questions seem important to understand that piece:
What's it going to look like when it is closed?
How do you open it again?

**Comment by Bohdan-Tereta** [comment]
![image](https://user-images.githubusercontent.com/7373957/40425087-075107da-5ea0-11e8-8734-978c4daa8e07.png)

**Comment by Bohdan-Tereta** [comment]
Imagine something like this, left part is a custom menu and not a part of blockly, but selecting a category in it opens blockly flyout and populates it with blocks. So after flyout is closed you can easily reopen it from external menu

**Comment by AnmAtAnm** [comment]
If the only use case for this requires an external UI and associated code, then this shouldn't be an standard feature of blockly.  There should not be a configuration of `autoClose` that makes blockly unusable.

The suggested code is small enough to be a trivial patch that individual developers can apply. It can even be implemented as a wrapper function of `hideChaff()`.

Alternatively, we can add the ability to register a `hideChaff()` callback.  I could see a few cases where a developer would want to hide their own app's "chaff" ad the same time Blockly attempts to, so this wouldn't be a single-purpose edit.

**Comment by BeksOmega** [comment]
Closed by the same thing that closed #7506
