### ISSUE TITLE
Opening a dropdown scrolls the page on FireFox

### ISSUE THREAD

**Issue by acbart** [google/blockly#186]
If you click a Blockly dropdown in Firefox, the page will scroll all the way to the bottom. It's not obvious on a page that's tiny, so here's an example of it happening with a larger page:

https://dl.dropboxusercontent.com/u/23141976/google-blockly-2d60d94/google-blockly-2d60d94/demos/generator/index.html

**Comment by NeilFraser** [comment]
Good catch.  Fixed.
