### ISSUE TITLE
Workspace comment resize icon renders a little outside the ws comment box 

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1865]
### Expected Behavior
Resize icon is always trimmed to the size of the comment box.

### Actual Behavior

Resize icon renders a little outside the ws comment box (when comment is unselected) / highlight border (when comment is selected)

**Comment by ManjariRathore** [comment]
Hello, If this issue is open for development, I can work on this issue. I'll start and raise a draft PR once assigned.

**Comment by BeksOmega** [comment]
This no longer reproduces.
