### ISSUE TITLE
Highlight all possible connection places for a piece !

### ISSUE THREAD

**Issue by aadrian** [google/blockly#188]
Right now there's highlighting (yellow) only to the "port" when a piece is very near it's destination to be dropped/connected.

It would be however very helpful if **all** possible (correct) destinations for a given piece would be highlighted (with a different color), even if the piece is not near them (just selected). This would greatly increase composition speed as programs grow.

**Comment by HendrikD** [comment]
Hi,

i wrote a plugin to do exactly that. You can clone or download it from https://github.com/HendrikD/blockly-type-indicator . It's easy to include into your project.

Greetings.

**Comment by aadrian** [comment]
@HendrikD This is simply fantastic :) !.

Thank you very much :) !

**Comment by starfishmod** [comment]
@HenrikD I have just seen your plugin it is awesome - thanks for this, it
should improve our usability dramatically.

On 9 October 2015 at 01:55, aadrian <notifications@github.com> wrote:

> @HendrikD <https://github.com/HendrikD> This is simply fantastic :) !.
>
> Thank you very much :) !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/blockly/issues/188#issuecomment-146588287>.
>



-- 
Regards

Andrew

**Comment by rachel-fenichel** [comment]
Closing since we've improved this flow with insertion markers.
