### ISSUE TITLE
typo and memory leak in flyout_button.js

### ISSUE THREAD

**Issue by jlaurens** [google/blockly#1880]
Hi

this one is so short that it really does not deserve a PR

In flyout_button.js, line [182](https://github.com/google/blockly/blob/7679d227df8f62a12316334ee708d4a9a800ef17/core/flyout_button.js#L182) reads
```
this.mouseUpWrapper_ = Blockly.bindEventWithChecks_(this.svgGroup_, 'mouseup',
```
instead of
```
this.onMouseUpWrapper_ = Blockly.bindEventWithChecks_(this.svgGroup_, 'mouseup',
```
Actually `this.mouseUpWrapper_` is never unbound nor disposed of.

**Comment by rachel-fenichel** [comment]
We don't mind small PRs--they're much easier and faster to review than large ones, and easier to roll back if there are issues.  Looks like Andrew's got this one handled.
