### ISSUE TITLE
Typed variable documentation doesn't mention default types

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1882]
https://developers.google.com/blockly/guides/create-custom-blocks/variables#typed_variable_blocks

Sample JSON:
```
 // Block for Panda variable getter.
 {
  "type": "variables_get_panda",
  "message0": "%1",
  "args0": [
    {
      "type": "field_variable",
      "name": "VAR",
      "variable": "%{BKY_VARIABLES_DEFAULT_NAME}",
      "variableTypes": ["Panda"]    // Specifies what types to put in the dropdown
    }
  ],
  "output": "Panda",    // Returns a value of "Panda"
  ...
},

 // Block for Panda variable setter.
{
  "type": "variables_set_panda",
  "message0": "%{BKY_VARIABLES_SET}",
  "args0": [
    {
      "type": "field_variable",
      "name": "VAR",
      "variable": "%{BKY_VARIABLES_DEFAULT_NAME}",
      "variableTypes": ["Panda"]
    },
    {
      "type": "input_value",
      "name": "VALUE",
      "check": "Panda"    // Checks that the input value is of type "Panda"
    }
  ],
  "previousStatement": null,
  "nextStatement": null,
  ...
```

Specifying a variable field like this,
```
  {
      "type": "field_variable",
      "name": "VAR",
      "variable": "%{BKY_VARIABLES_DEFAULT_NAME}",
      "variableTypes": ["Panda"]    // Specifies what types to put in the dropdown
    }
```
with type restrictions but no defaults, is a problem: the default type will be the empty string, and the default variable creation will error because the variable type doesn't match the field.

The documentation should include a default type, and should also explain what default types are.  See https://github.com/google/blockly/blob/master/core/field_variable.js#L253 and https://github.com/google/blockly/issues/1499.

**Comment by alschmiedt** [comment]
Updated here: https://developers.devsite.corp.google.com/blockly/guides/create-custom-blocks/variables#typed_variable_blocks
