### ISSUE TITLE
Image field: click handler gets ignored

### ISSUE THREAD

**Issue by seldomU** [google/blockly#1887]
### Problem statement

Image fields accept click handlers but do not invoke them.

### Expected Behavior

Clicking on the field's image should result in a call to the click handler.

### Actual Behavior

It does not.

### Steps to Reproduce

1. Create a block with an image field that has a click handler.
2. Try to click the block.

### Operating System and Browser

Desktop Chrome

### Additional Information

Setting the field's EDITABLE property to *true* makes it behave as expected.

**Comment by JarbasAl** [comment]
i am observing same behaviour in chrome and in firefox 60

works in firefox 52.8.1 (32-bit)
