### ISSUE TITLE
Category colours now mandatory.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#1893]
In the past if one didn't specify a colour on a toolbox category, there would be no colour.  Here's an old build of Blocky Games which shows this:
  https://2-dot-blockly-games.appspot.com/turtle?level=10
As of last week on develop, categories with no colour now have a brown patch:
  https://blockly-games.appspot.com/turtle?level=10
This brown has a hue of zero.

0 !== undefined

**Comment by AnmAtAnm** [comment]
`git bisect` blames #1881 / 629763e8ffb53e6c7f97053e67b1d86992aa4177, though I really thought I tested for exactly this issue before approving it.  :-|

**Comment by AnmAtAnm** [comment]
Testing this is as easy as loading the playground with `?toolbox=test-blocks`.
