### ISSUE TITLE
Bubble dragging does not work correctly in RTL

### ISSUE THREAD

**Issue by kchadha** [google/blockly#1896]
### Problem statement

Bubble dragging (e.g. for block comments) is not working correctly in RTL. It seems that the drag starts in the wrong place. The drag follows your cursor movement, but the block comment is not underneath the cursor.

### Expected Behavior

Bubble should remain attached to the cursor when dragging in RTL.

### Actual Behavior

Bubble is offset from the cursor position in RTL while dragging.

### Steps to Reproduce

1. Open the blocks playground.
2. Switch to RTL
3. Add a block to the workspace
4. Add a comment to the block
5. Show the comment
6. Drag the comment around

### Operating System and Browser

Not browser specific.

**Comment by kchadha** [comment]
@rachel-fenichel

**Comment by AnmAtAnm** [comment]
It looks like there is an bad multiplier in the coordinate transform. Compare dragging from the top middle (approximately correct), top left corner (way off), and top right corner (way off in the other direction).

**Comment by rachel-fenichel** [comment]
It works for workspace comments, but not for block comments, warnings, or mutators.

**Comment by samelhusseini** [comment]
Fixed.
