### ISSUE TITLE
Collapsed blocks in toolbox

### ISSUE THREAD

**Issue by VolkerSPE** [google/blockly#190]
During migration of on old blockly project (2013) i got a problem with collapsed blocks within the toolbox. All image fields of the block are shown in the upper right corner of the block.

I have added  

`<block type="text" collapsed="true"></block>`

to the toolbox of the code application and got the following result:

![collapse](https://cloud.githubusercontent.com/assets/14992903/10303465/30b9fd60-6c14-11e5-9ee9-482be22e62bd.png)

The SVG-blocks containing the images weren't made invisible. If such a block is placed on the workspace and is expanded and collapsed again the result is as expected: the images are not shown.

**Comment by NeilFraser** [comment]
Fixed.  Thanks!
