### ISSUE TITLE
Cannot Delete Blocks (Develop Branch)

### ISSUE THREAD

**Issue by TheBrokenRail** [google/blockly#1901]
### Problem statement

When trying to delete a block it throws an error.

### Expected Behavior

The block is deleted.

### Actual Behavior

It throws an error.

```
Uncaught TypeError: goog.Timer.defaultTimerObject.setTimeout is not a function
    at Function.goog.Timer.callOnce (bundle.js:formatted:5591)
    at Blockly.BlockDragger.maybeDeleteBlock_ (bundle.js:formatted:17759)
    at Blockly.BlockDragger.endBlockDrag (bundle.js:formatted:17737)
    at Blockly.TouchGesture.Blockly.Gesture.handleUp (bundle.js:formatted:18391)
    at Blockly.TouchGesture.handleUp (bundle.js:formatted:19323)
    at HTMLDocument.h (bundle.js:formatted:26732)
```

### Steps to Reproduce

1. ```git clone https://github.com/TheBrokenRail/MicroBlocks.git```
2. ```npm install```
3. ```npm start```
4. Go to ```localhost/editor``` in a web browser
5. Try to delete a block

### Operating System and Browser

Chrome on Ubuntu 18.04

### Additional Information

This is on the Blockly develop branch for its ability to generate a Node.js compatible file.

**Comment by AnmAtAnm** [comment]
Note for my own clarification: The above linked repo is using Blockly as a direct git dependency via NPM, calls `npm install` in that dependent module (concatenating the `core`/`blocks`/`javascript` files), and loads it into a client-side page via browserify.

FYI: The files that `npm install` concatenates are not rebuilt on every develop branch commit. They may be weeks out of date with the actual source.

**Comment by AnmAtAnm** [comment]
The delete key and the context menu delete actions both work fine. It is is dragging to delete (either over the toolbox or the trash can) that causes the stack trace.

I do not see this error in the demos, either in a direct Blockly check out of the develop directory, or the demos in the checkout created by npm (`node_modules/blockly/demos/code/index.html`).

**Comment by AnmAtAnm** [comment]
This bug is a weird interaction between the Closure compiled code and browserify.

When I run the code through a static instance (`demos/code/index.html`), `goog.Timer.defaultTimerObject` is a reference to `window`:

![screen shot 2018-06-04 at 1 28 52 pm](https://user-images.githubusercontent.com/9916202/40940016-4dbece96-67fb-11e8-8c1b-81fffee1b556.png)

When I run your app using browserify, `goog.Timer.defaultTimerObject` only has `Blockly` and `console`:

![screen shot 2018-06-04 at 1 30 38 pm](https://user-images.githubusercontent.com/9916202/40940090-8619004a-67fb-11e8-93eb-8eec1cc9c292.png)

**Comment by TheBrokenRail** [comment]
BTY are there any plans to publish Blockly on NPM?

**Comment by AnmAtAnm** [comment]
> are there any plans to publish Blockly on NPM?

Specifically, there are complications surrounding the fact that Blockly is really multiple small libraries: core, blocks, generators, messages. Messages in particular leads to a lot of maintenance overhead for us, if we are uploading each library individually, and I'm working to define a route forward on this issue.

The recent changes that allowed you link directly to the repo only work specifically for JavaScript generators and English language blocks.

We appreciate your build file demonstration that this could work for Browserify. This had not been tested yet.

Regarding the underlying issue, it looks like the Closure team agrees this is a bug worth fixing: https://github.com/google/closure-library/issues/903#issuecomment-394556840

**Comment by TheBrokenRail** [comment]
This also happens with Webpack and React.

**Comment by AnmAtAnm** [comment]
#1917 should sidestep the Closure problem by removing all uses of `goog.Timer.callOnce(..)`. Please let us know of similar problems when using Blockly in Browserify or WebPack.
