### ISSUE TITLE
Replace goog.Timer.callOnce(..) with setTimeout

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1905]
### Problem statement

We use both `goog.Timer.callOnce(...)` and `setTimeout(..)` in various places. We have not had problems with `setTimeout(..)`, but a recent issue (#1901) highlighted a problem with `Timer.callOnce(..)` dependency on a `goog.global`, which is set incorrectly in Node.js (https://github.com/google/closure-library/issues/903).

### Expected Behavior

Consistently use one API.

**Comment by Vimal-Raghubir** [comment]
Hi, I am interested in working on this issue. So based on my understanding, all instances of `goog.Timer.callOnce()` has to be replaced with the `setTimeout()` function?

**Comment by NeilFraser** [comment]
If you want to work on this, please submit changes to the "Closure-die-die-die" branch.  Eliminating all instances of "goog.Timer" from the codebase would be great.

**Comment by AnmAtAnm** [comment]
Sorry @NeilFraser . This one is important enough, as the behavior causes problems in Browserify and WebPack.

@Vimal-Raghubir Your understanding is correct. Please make a Pull Request against the `develop` branch.

**Comment by AnmAtAnm** [comment]
Resolved in #1917.
