### ISSUE TITLE
Headless mode no longer works

### ISSUE THREAD

**Issue by eclispe** [google/blockly#191]
broken by 6f924e349afffe3668456c85f8954855c14e8184

From Chome console when using the headless demo:

Blockly.Connection	@	blockly_compressed.js:882
Blockly.Block.appendInput_	@	blockly_compressed.js:1054
Blockly.Block.appendValueInput	@	blockly_compressed.js:1046
Blockly.Blocks.controls_if.init	@	blocks_compressed.js:37
Blockly.Block.fill	@	blockly_compressed.js:1026
Blockly.Block.initialize	@	blockly_compressed.js:1024
Blockly.Block.obtain	@	blockly_compressed.js:1024
Blockly.Xml.domToBlockHeadless_	@	blockly_compressed.js:972
Blockly.Xml.domToBlock	@	blockly_compressed.js:971
Blockly.Xml.domToWorkspace	@	blockly_compressed.js:970
generate	@	index.html:113
onclick	@	index.html:98

**Comment by FabianHahn** [comment]
I am having the same problem, but I think it is 7db8ce94de9c2fde999bdd59180031fbf5f2fd9d rather than 6f924e349afffe3668456c85f8954855c14e8184 that introduced the problem.

The error I am getting is *Uncaught TypeError: Cannot read property '1' of undefined* in *connection.js:45*:
```javascript
this.db_ = source.workspace.connectionDBList[type];
```

**Comment by eclispe** [comment]
Ah yes, you appear to be right, I didn't recompile when I bisected it

**Comment by NeilFraser** [comment]
Fixed.  Sorry about that.  Glad to see that headless is being used.  Thanks for reporting it.
