### ISSUE TITLE
Web Link wrong

### ISSUE THREAD

**Issue by samael205** [google/blockly#1913]
Hello,

I'm looking at the example you have of js_interpreter [here](https://developers.google.com/blockly/guides/app-integration/running-javascript#js_interpreter) and I think the link in the demo is wrong. It takes you to the javascript code generation demo: https://blockly-demo.appspot.com/static/demos/generator/index.html.

It should take you to this link: https://blockly-demo.appspot.com/static/demos/interpreter/step-execution.html, right?

**Comment by rachel-fenichel** [comment]
The javascript code generation demo also demonstrates how to run the code with the interpreter after generating it.  The other demos show off more complicated interpreter behaviour.
