### ISSUE TITLE
The "comment" feature doesn't seem to work on IE

### ISSUE THREAD

**Issue by msprotz** [google/blockly#192]
You can try this out at www.microbit.co.uk (hit "Create Code", then "Blocks", then drag any block, and try to add a comment on it).

Here's what it looks like:

![capture](https://cloud.githubusercontent.com/assets/10673049/10343359/4cf9d216-6cd2-11e5-88d3-7fbbdd4bf20f.PNG)

Thanks,

Jonathan

**Comment by carlosperate** [comment]
This specific issue has been documented on the code:
https://github.com/google/blockly/blob/5b7fec709279533e0dea4813852e0b24ed98f2db/core/comment.js#L141-L148

**Comment by msprotz** [comment]
Oh ok. Thanks.

**Comment by NeilFraser** [comment]
If it is any consolation, in the entire history of Blockly I've never seen a child read (let alone write) a comment.
