### ISSUE TITLE
Remove goog library calls from blocks/ files.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1922]
### Problem statement

`blocks/*.js` may not be compiled, and so should not depend upon Closure libraries.

Currently the system works because the functions called happened to be also required by Blockly `core/` files. In the case of advanced compilation, the block files are also compiled and the renamed, minified function definitions get replaced in the block definition calls.

**Comment by rachel-fenichel** [comment]
@AnmAtAnm I know you made some changes for this.  Is it all done?
