### ISSUE TITLE
Remove goog library calls from generators/ files.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1923]
### Problem statement

`generators/*.js` may not be compiled, and so should not depend upon Closure libraries.

Currently the system works because the functions called happened to be also required by Blockly `core/` files. In the case of advanced compilation, the generator files are also compiled and the renamed, minified function definitions get replaced in the generator functions.

**Comment by NeilFraser** [comment]
There are currently no goog library calls from generators/*.js
