### ISSUE TITLE
Workspace bounds are different for toolbox with no categories

### ISSUE THREAD

**Issue by asanzo** [google/blockly#1924]
### Problem statement

When rendering a block like this in the workspace:

```xml
<block type="al_empezar_a_ejecutar" x="15" y="15"></block>
```

If the toolbox has categories, it puts the block 15 px  to the right of the toolbox, which is the expected behaviour. 
![seleccion_355](https://user-images.githubusercontent.com/5421992/41377039-3b291c86-6f31-11e8-9d8f-d067d8397093.png)

Howerver, **if the toolbox doesn't have categories**, it puts the block **behind** the fixed toolbox.
![seleccion_357](https://user-images.githubusercontent.com/5421992/41377172-a73a49ae-6f31-11e8-8b83-90950903bdc3.png)

### Expected Behavior
**When the toolbox doesn't have categories** the described block should be placed 15 px to the right of the toolbox:
![seleccion_356](https://user-images.githubusercontent.com/5421992/41377088-633e2054-6f31-11e8-996c-8562a7efe720.png)

### Actual Behavior
**When the toolbox doesn't have categories** the described block is placed **behind** the toolbox:
![seleccion_357](https://user-images.githubusercontent.com/5421992/41377169-a50440ae-6f31-11e8-8e80-3fae57bd7614.png)

Actually, the whole workspace extends to the left bound of the toolbox, instead of behaving the same as with a categorized toolbox, in which the workspace starts in the right bound of the toolbox.

### Steps to Reproduce

1. Create a simple toolbox like https://blockly-demo.appspot.com/static/demos/fixed/index.html
2. Put a block in the workspace with no position information, or with a few pixels in x and in y.
3. It will appear behind the toolbox.
4. Repeat the same with a categorized toolbox like https://blockly-demo.appspot.com/static/demos/toolbox/index.html , the inserted block will always stay at the right of the toolbox.

### Operating System and Browser

Tested under Linux Mint, FF 59.0.2, and Chrome 65.0.3325.181

**Comment by AnmAtAnm** [comment]
This appears to work as expected in both the `master` and `develop` branches.

If you open the [playground with a simple toolbox](https://blockly-demo.appspot.com/static/tests/playground.html?toolbox=simple), and import the following XML:

```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="controls_if" id="+)wU?0#6oCmzE1?P!Y+i" x="0" y="0"></block>
</xml>
```
The block will anchor on the top left, adjacent to the toolbox. It will do the same when use the [playground with categories](file:///Users/marshalla/Projects/Blockly/web/tests/playground.html?toolbox=categories), as well.

**Comment by AnmAtAnm** [comment]
It appears your [ember-blockly](https://github.com/Program-AR/ember-blockly) package is pulling in the Bower [blockly-package](https://libraries.io/bower/blockly-package), which is over a year and a half old. We have no association with that package (or currently any NPM or Bower distribution) and do not control its contents.
