### ISSUE TITLE
Right-side ellipsis in RTL Arabic

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1928]
### Problem statement

Following messages have right ending ellipsis in our ar.json:
 * `RENAME_VARIABLE`: "إعادة تسمية المتغير..."
 * `NEW_VARIABLE`: "إنشاء متغير..."
* `MATH_CONSTANT_TOOLTIP`: "ير جع واحد من الثوابت الشائعة : π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity)."
* `PROCEDURES_DEFNORETURN_COMMENT`: "صف هذه الوظيفة..."

Which, if any, of these are correct?
Do other RTL languages show similar problems?

Also, there is differences between use of three periods versus an ellipsis character (`...` vs `…`).
Which ellipsis representation is preferred? Add a commit test after correcting.

**Comment by NeilFraser** [comment]
The translations are correct.  If you open the ar.json in an editor, place your cursor in one of these messages, and cursor right, the cursor will correctly move left to the end of the Arabic, then proceed to the ellipsis.  The byte order is absolutely right.

However, we are failing to display these messages properly.  The ellipsis is appearing on the wrong side of the message.

<img width="361" alt="Screen Shot 2019-03-04 at 01 55 17" src="https://user-images.githubusercontent.com/250480/55767097-691bc800-5a2c-11e9-931f-8d00ccc98323.png">

What's needed is a [RLM](https://en.wikipedia.org/wiki/Right-to-left_mark) or [LRM](https://en.wikipedia.org/wiki/Left-to-right_mark) in the creation of button text.

**Comment by samelhusseini** [comment]
Fixed.
