### ISSUE TITLE
Shadow block bug

### ISSUE THREAD

**Issue by HendrikD** [google/blockly#193]
I don't really know how i managed to break it but there is a bug with the shadow blocks preventing an other block from replacing it. The bug occured in the blockly playground with chrome 45.0.2454.101 m.

Since most number blocks are too large to see the small shadow block under them i was only able to test it with the math_number and math_constant blocks and with both the top shadow block refuses to disappear.

Greetings

![a bug](http://tinly.de/bug2.gif "a bug")

**Comment by starfishmod** [comment]
@HendrikD May I ask how you are creating shadow blocks in the first place? I haven't seen that before.

**Comment by HendrikD** [comment]
It's an upcoming feature presented by Fraser in the blockly google group [https://groups.google.com/forum/#!topic/blockly/bXe4iEaVSao]. You can check it out at blocklys playground linked in this thread. By the time i posted this issue i did not reallize the feature is not yet commited.. However you will be able to create shadow blocks by not using something like <block type="text"></block> but <shadow type="text"></shadow> in the toolbars xml.

Greetings.

**Comment by NeilFraser** [comment]
I'm unable to recreate this.  :(  However, I absolutely believe this issue exists since that was an exact error case that I saw (and thought I solved) earlier this week.  Not sure how this could be resurfacing.  Will be interested to see a repeatable test case.

Leaving open.

**Comment by NeilFraser** [comment]
Repeatable test case:
1. Create RGB colour block.
2. Add regular number block to an input.
3. Add a second regular number block on the same input.
The second number block displaces the first (as in should), but the shadow reappears in the process and becomes permanent.

Shouldn't be hard to fix now.

**Comment by NeilFraser** [comment]
Fixed, thanks!  (Not planning to push to the demo site immediately, so it will persist there for a little while.)
