### ISSUE TITLE
How does appendDomToWorkspace(..) deal with conflicting function/variable names?

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1931]
The introduction of variable ids breaks a basic assumption of `appendDomToWorkspace(..)`, since names are not sufficient to coalesce variable references. What does it do now, and what should it do?

Similarly, what happens if an imported workspace includes a function definition for a function name that is already defined on the workspace.

These issues might also apply to `domToWorkspace(..)` when the workspace already has blocks on it.

**Comment by rachel-fenichel** [comment]
Relevant code: https://github.com/google/blockly/blob/master/core/variable_map.js#L172 

If the name (+ opt_type) is already in use with a different ID, you get an error.
If the ID is already in use with a different name (+ opt_type), you get an error.
If a variable already exists with that name (+ opt_type) and ID, they refer to the same variable.
If the name and ID are not in use, it creates a new variable.

I'm not sure about functions.  Probably nothing good.

**Comment by rachel-fenichel** [comment]
The current behaviour (use the same variable if id, name, and type match; warn or error in conflict cases; make a new variable if none exists) is the correct and intended behaviour for variables. 

The [@blockly/block-shareable-procedures](https://www.npmjs.com/package/@blockly/block-shareable-procedures) plugin implements similar behaviour for procedures and is recommended for developers who want to synchronize between multiple workspaces.
