### ISSUE TITLE
Code Demo: Edge stops responding to touch

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1942]
### Expected Behavior

Blockly should never stop reacting to touch input.

### Actual Behavior

The Blockly workspace in the code demo stops reacting to touch events after a very specific sequence involving select the XML tab.

### Steps to Reproduce

1. Open Edge on a touch device such as a Surface.
2. Open the [Blockly Code Demo](https://blockly-demo.appspot.com/static/demos/code/index.html).
3. Add some blocks to the workspace. Observe how dragging and block connections work just fine.
4. Tap on the XML tab and then return via the Blocks tab.
5. Attempt to pan the workspace. Observe how the workspace stops responding to touch event such as the pan gesture after about one redraw. The user cannot select a block, a field, and toolbox interaction usually fails.

The same behavior works fine in Chrome and IE on the same device.

This was observed on both the previous release / master branch and the release candidate branch.

### Stack Traces

The sequence did not produce any error in the console.

### Operating System and Browser

* Windows Edge

**Comment by AnmAtAnm** [comment]
The bug is specific to the XML tab in the demo. The workspace works fine after return from a generator tab.

The show and hide on the playground does not trigger the problem.

**Comment by alschmiedt** [comment]
Closing because can't repro
