### ISSUE TITLE
Q: Rename function arguments?

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1946]
When we drag a variable block onto the workspace, we may rename it to make sure it is unique.

Currently, when we drag a new function definition that includes a function argument, we don't rename the argument even if it collides with an existing variable.

Is this the right behavior?

### Steps

1. Open the Playground test blocks.
2. Open the "Drag" category.
3. Drag two instances of "with one argument" to the workspace.

Observe the function name of the second gets renamed, but its argument does not rename, even though it collides with the variable created by the previous.

**Comment by rachel-fenichel** [comment]
Closing as wontfix because there's no reason to keep parameter names in different functions from conflicting.
