### ISSUE TITLE
Add Undo/Redo buttons to playground and multi_playground

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1947]
### Problem statement

Cannot test undo and redo on touch devices. This limits an important aspect from testing.

### Feature Request

Add Undo and Redo buttons to the UI. Which methods do these need to call?

**Comment by rachel-fenichel** [comment]
You should be able to longpress on the workspace to get the context menu, then select Undo and Redo.

That said, the functions are:
undo: `workspace.undo(false);`
redo: `workspace.undo(true);`

**Comment by rachel-fenichel** [comment]
And to be clear, I think these are good buttons to have.

**Comment by RoboErikG** [comment]
At least on Android long press wasn't working to bring up the context menu.

**Comment by AnmAtAnm** [comment]
I've had no problem with the long press.  I use it regularly to "Delete All Blocks". This worked on all touch devices, including Android.

**Comment by AnmAtAnm** [comment]
To be clear, the long press requires a steady finger. The touch slop radius could be widened/improved to make it easier to open.

**Comment by rachel-fenichel** [comment]
Now part of the advanced playground.
