### ISSUE TITLE
Code Demo on iOS: Double execution upon tapping run

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1949]
### Problem statement

On iOS Safari and Chrome, in the Blockly Code Demo, tapping the run button will execute the code twice.

### Expected Behavior

Tapping the run button should only execute the code once.

### Steps to Reproduce

1. On an iPad, open the Code Demo in either Safari or Chrome
2. Add one print block from the Text category.
3. Tap the run button.

Observe the alert dialog shows twice.

### Operating System and Browser

* Device: iPad mini, 1st gen
  * OS: 9.3.5
  * Browser Safari, Chrome

**Comment by BeksOmega** [comment]
Closed by #5037
