### ISSUE TITLE
Upgrade to Dart 2.0

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#1951]
### Problem statement

Dart has upgraded to 2.0, and so has the page we use for testing (dartpad).  Some of our generators don't work in 2.0 because there are breaking [changes](https://www.dartlang.org/dart-2) in the language.  We need to upgrade, ideally before the release at the start of September.

### Expected Behavior
Generated code from the generator tests in Dart can run on DartPad.

### Actual Behavior

A variety of type errors.

### Steps to Reproduce

Load all tests in the generator test page, and run the generated Dart in DartPad.

Instructions for testing generators: https://developers.google.com/blockly/guides/modify/web/unit-testing#block_generator_tests

**Comment by AnmAtAnm** [comment]
Assuming there is not a form that is compatible with both 1 and 2, do we need to keep a copy of the Dart 1 generator around for older existing projects? I don't mind deprecating it and taking it out of testing (or test generation without running the resulting code).

Alternatively, we can just point people to the older repo.

**Comment by rachel-fenichel** [comment]
I think we should just upgrade and tell people to go back in time to get the older generator.

**Comment by rachel-fenichel** [comment]
Done (thanks Neil)
