### ISSUE TITLE
Long press broken on Playground and Multi-Playground

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#1955]
### Problem statement

In Chrome on Android long press doesn't work to bring up the context menu on both the Playground and Multi-Playground pages. It works correctly on the Code demo and other Blockly pages. 

### Expected Behavior

Long press brings up the context menu.

### Actual Behavior

Long press selects the text left of the workspace.

**Comment by AnmAtAnm** [comment]
There is something particular about the playgrounds. The context menu appears as expected in both the Code demo and in Blockly Games.

**Comment by BeksOmega** [comment]
This looks like a dupe of #2188 Leaving that one open because it has more info.
