### ISSUE TITLE
Exporting workspaces with shadow blocks to XML introduces blank lines

### ISSUE THREAD

**Issue by FabianHahn** [google/blockly#196]
Since the introduction of shadow blocks, I noticed that exporting the workspace to XML sometimes introduces blank lines whithin generated *<shadow>* tags. While not syntactically a problem, repeatedly importing and exporting such a workspace seems to keep adding newlines indefinitely.

Minimal example to reproduce this:
```xml
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="variables_set" x="63" y="63">
    <field name="VAR">item</field>
    <value name="VALUE">
      <block type="math_arithmetic">
        <field name="OP">ADD</field>
        <value name="A">
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
          <block type="variables_get">
            <field name="VAR">item</field>
          </block>
        </value>
        <value name="B">
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
        </value>
      </block>
    </value>
  </block>
</xml>
```

Steps to reproduce the problem:

1. Open the Blockly playground at https://blockly-demo.appspot.com/static/tests/playground.html
2. Paste the above XML and click "Import from XML"
3. Click "Export from XML". The generated XML in the textarea contains a *<shadow>* tag with two extra newlines.
4. (optional) copy the generated XML, reload the page, paste the copied XML, and go back to step 3 to see how the problem gets worse

Received output with 879cacbb8d2be161b74f47e2aa846b3274dde27f:
```xml
[...]
          <shadow type="math_number">
            
            <field name="NUM">1</field>
          
          </shadow>
[...]
```

Expected output:
```xml
[...]
          <shadow type="math_number">
            <field name="NUM">1</field>
          </shadow>
[...]
```

**Comment by NeilFraser** [comment]
Good catch.  Fixed.  Thanks!
