### ISSUE TITLE
Block comments should not be owned by the icon in a rendered workspace

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#1969]
### Problem statement

On a rendered workspace the icon for opening the comment also owns the text for that comment. This means the block model depends on the rendered icon for information about the comment text (and position). This information should be independent of the icon so that it isn't lost when loaded/saved in a headless workspace.

### Expected Behavior

- Comment data is preserved in headless workspaces.
- There should not be any special cases for serializing comments.

### Actual Behavior

- Only the text is preserved in a headless workspace.
- We have to special case delete events to avoid losing the comment when its icon is destroyed.

### Steps to Reproduce

See discussion in #1960 

### Stack Traces

```
Replace with error stack trace.
```

**Comment by BeksOmega** [comment]
If it's ok, I'm going to take this because it needs to be fixed before I can look into block disposal (per #2152).

**Comment by samelhusseini** [comment]
Fixed by #2923
