### ISSUE TITLE
Add initSvg() to the BlockSvg constructor

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1980]
### Problem statement

Rendered blocks should be ready when they are returned from the constructor. Currently, the SVG tests require helper method with an extra call to `initSvg()` to properly prepare them. Adding that call to the `BlockSvg` constructor would simplify the API. It does not replace the need for `initSvg()`, since it may also be call after a mutation update.

Verify there are unintended side effects with this change, and no significant performance problems.

If it works, remove the helper method added in #1977.

**Comment by RoboErikG** [comment]
Note: initSvg also configures the parent svg group. Anyone working on this change should make sure that the correct parent is available in the constructor.

**Comment by ewpatton** [comment]
If this is implemented, can an option to disable it be provided? We often switch between the blocks and DOM representations when upgrading projects, so initializing the SVG if it isn't intended to be drawn would be a performance hit.

**Comment by AnmAtAnm** [comment]
Thanks for the feedback, @ewpatton. Sounds like a pretty good argument against this small API cleanup.
