### ISSUE TITLE
How to customize category style. 

### ISSUE THREAD

**Issue by AI2M** [google/blockly#1983]
I try to add property "icon" in category but it isn't works.
![screen shot 2561-07-19 at 17 43 53](https://user-images.githubusercontent.com/13836766/42980228-ad57db8a-8c00-11e8-86f7-89e5cfea2529.png)

it's possible  to customize other styles of category, isn't it? for example size of category.

**Comment by rachel-fenichel** [comment]
We don't have support for an icon in the toolbox.  Where did you read that we do?

Other customization can be done through CSS for the category menu.

In future, please direct questions like this to our [mailing list](https://groups.google.com/forum/#!forum/blockly).
