### ISSUE TITLE
Make Generator.provideFunction_() @protected (and many others)

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1985]
### Problem statement

Generator.provideFunction_() is currently marked `@private`, despite being use by non-core code. As such it is not documented in our reference. It is also useful for many generator authors and should become a standard `@protected` method.

### Expected Behavior

Generator authors should be able to find documentation on `provideFunction_()` and be expected to make use of it in their own code.

Looking further, `@protected` is not used anywhere in `generator.js`. There are probably several other methods that should be marked as such.

**Comment by BeksOmega** [comment]
I'm going to say this is a dupe of #7326
