### ISSUE TITLE
Handle keypresses correctly when there are multiple workspaces

### ISSUE THREAD

**Issue by fsih** [google/blockly#1998]
### Problem statement

This issue comes from comment https://github.com/google/blockly/pull/1819#discussion_r183542254

Once https://github.com/google/blockly/pull/1996 goes in, workspaces will ignore key presses when the main workspace is not visible or read-only. However, this may incorrectly ignore key presses when there are multiple workspaces and the main one is not visible or read-only, but others are not.
### Expected Behavior

Non-main workspaces should accept keypresses when the main one is hidden.
### Actual Behavior

Non-main workspaces will not accept keypresses when the main one is hidden.
### Steps to Reproduce

1. Create multiple workspaces. For instance the review comment suggests, "consider the multiple workspaces in the developer tools"
2. Set the main one to not visible

### Stack Traces

none

**Comment by BeksOmega** [comment]
The main workspace is now the last used workspace that isn't a flyout. So this is not longer an issue.
