### ISSUE TITLE
FieldTextInput validator called with value before keypress

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#2012]
### Problem statement

If a FieldTextInput has a validator function, upon text input, it can sometimes be asked to validate the previous text value.

`Blockly.FieldTextInput.prototype.onHtmlInputChange_` is responsible for invoking the validator. It does this by capturing the text in the `<input>`, assigning that to itself (calling `setText()`), and then `validate_()`. However, `onHtmlInputChange_` is actually a keyup / keypress listener (configured in `.bindEvents_()`). Sometimes this get called (apparently) before the input has processed the keystroke and updated its own contents. Thus, when the text is captured for validation, it captures the old text.

For example, if the field has "xy", and the user types "z" at the end, the validator may only process the string "xy" instead of testing "xyz". I've only seen this when adding a character. In testing, backspace keypresses have always processed first before the input update (by chance?).

I'm guessing the apparent non-deterministic behavior may be a side effect of the event handler being attached to both keyup and keypress. Maybe?

### Expected Behavior

The validator should always be called on the incoming string.  That is, the string that includes the modification incurred by the keypress.

### Steps to Reproduce

1. Add a function block. Open the mutator workspace.
2. Add a parameter to the function via the mutator workspace.
3. Add a breakpoint in `blocks/procedures.js`, near the top of `validator_()`. Alternatively, add a log statement for the `varName`.
4. Edit the variable name via the input field in the mutator workspace.  Note the value of `varName` in `validator_()`.

In standard blocks, only the parameter block of a function mutator has such a field validator.

### Operating System and Browser

 * Desktop Chrome

**Comment by AnmAtAnm** [comment]
Marking this as low priority, as the bug has not visible effects in the current code (as long as it does not apply to backspace, delete, or similar destructive key strokes).

**Comment by julientype** [comment]
You simply need to add a fire validation event like the field event you have <-----keypress
after the keycode is added  you grant a validate event  ...... DOM is nasty at keypress events let order take place.
here test this code out .......  the input text field gets @$$@@$.... 

onchange: function(e) {
 try {
        if (typeof(e.element) != "undefined") {
        switch (e.element) {
          case "theme":
                 break;
        case "selected":
 
            break;
case "field" :
             var answer =  this.getFieldValue('txtTableName');
            answer = goog.string.trimRight( answer.replace(/[^a-zA-Z_]/g, ''));
           e.newValue =answer;
           e.element.setText(answer);
           this.setFieldValue(answer,'txtTableName' );

           break;
        case "click" :
brake;
}
}
} catch (error) {
        alert("bock")
      }

**Comment by RoboErikG** [comment]
@BeksOmega is this fixed?

**Comment by BeksOmega** [comment]
The code in the text input still works as described:
> capturing the text in the \<input\>, assigning that to itself (calling setText()), and then validate_() 

But I can't reproduce the issue. And idk how:
> Sometimes this get called (apparently) before the input has processed the keystroke and updated its own contents.

could be occuring. So I'd say it's fixed.

**Comment by RoboErikG** [comment]
Thanks, @BeksOmega
