### ISSUE TITLE
Group isn't being set on function rename events

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2028]
### Problem statement

When a function is renamed by the user and all its callers are renamed with it there isn't a group set on the event. This means that undoing the events undoes each rename one by one.

### Expected Behavior

Function rename events should get a group id which is used for all caller renames.

### Actual Behavior

No group id is set.

### Steps to Reproduce

1. Create a function definition.
2. Create multiple caller blocks for the definition.
3. Turn logging on.
4. Rename the function definition.

**Comment by BeksOmega** [comment]
This is fixed for the upcoming sharable procedure blocks.
