### ISSUE TITLE
Result of textToDom() can't be passed to domToBlock()

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2029]
We should allow \<xml>, \<block>, or \<shadow> to be passed to textToDom as the top level tag.

### Problem statement

textToDom() requires that the text be wrapped with an \<xml> tag. domToBlock() requires that the top level tag be a \<block> or a \<shadow>. If you're trying to convert text xml to a single block stack you have to wrap it with \<xml> then get the first child in the dom and pass that to domToBlock().

### Expected Behavior

Should be a reasonable code path for generating a single block stack from a string.

### Actual Behavior

Have to do some extra massaging to make it work.

Example from older `events.js` code:

```
this.xml = Blockly.Xml.textToDom('<xml>' + json['xml'] + '</xml>').firstChild;
```

**Comment by samelhusseini** [comment]
Fixed by #2585
