### ISSUE TITLE
[Edge]: Field edit widget misaligned when browser page is zoomed.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#2032]
### Problem statement

When the user zooms the page (e.g., pinch zoom outside the workspace on the page background), any edit widget for fields (text, number, dropdown, color, date) do not align with the field in the block.

### Expected Behavior

The edit widget should always align perfectly with the block.

### Actual Behavior

The edit widget pops up below and to the right of the desired location when zoomed (and panned?).

### Steps to Reproduce

1. Opening a blockly page in Edge.
2. Drag a block with a text field, number field, variable/dropdown field, color field, or date field in the workspace.
3. Pinch zoom the page background, so the workspace bounds are larger.
4. Tap the field to initiate an edit.

Notice the location of the popup widget does not align with the rendered field on the block.

![edge-edit-widget-bug](https://user-images.githubusercontent.com/9916202/44819510-f13a1500-aba1-11e8-80f0-dd892457970b.png)

#### Works correctly in...

 * Windows Chrome 
 * Desktop Chrome (Mac)
 * Safari
 * Windows Internet Explorer 11 

#### Misaligned in...
 * Windows Edge

**Comment by MNSDivya** [comment]
@rachel-fenichel Field is not misaligned while editing a zoomed workspace on Edge browser. 
Issue seems resolved.
