### ISSUE TITLE
Recenter issue with a horizontal toolbox

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#2036]
### Problem statement

If a toolbox has a horizontal toolbox, recentered blocks will be far right of the workspace center, possibly outside the normal draggable bounds.

### Expected Behavior

After pressing the recenter button, blocks should be centered in the workspace. It the blocks fit, they in the visible space, they should not bleed off the workspace edge.

### Steps to Reproduce

1. Start by opening `tests/multi_playground.html`.
2. In any horizontal toolbox workspace (bottom four on page), add blocks from the toolbox.
3. Hit the recenter button.

Notice how the blocks are not centered, shifted to the right.

![screen shot 2018-08-30 at 11 30 58 am](https://user-images.githubusercontent.com/9916202/44871961-28173600-ac49-11e8-8276-d10714224d8e.png)

![screen shot 2018-08-30 at 11 28 46 am](https://user-images.githubusercontent.com/9916202/44871960-277e9f80-ac49-11e8-8a01-cfedbb992853.png)

Perhaps the toolbox length is being included in the horizontal workspace width?

**Comment by alschmiedt** [comment]
Closing as I can no longer repro.
