### ISSUE TITLE
build.py fails for duplicate provide

### ISSUE THREAD

**Issue by cdaringe** [google/blockly#204]
Hi all:

Blockly requires that `closure-library` be present in a sister directory.  This is kind of a bummer, vs. requiring it in as a dependency.  Regardless, we got it going :).  Thanks for great instructions!

However, if you run `npm install` in `closure-library`, then run `python build.py` in blockly, it errors out.

``` bash
$ python build.py
SUCCESS: msg/js/en.js
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "build.py", line 162, in run
    self.gen_core()
  File "build.py", line 184, in gen_core
    [os.path.join("core", "blockly.js")])
  File "../closure-library/closure/bin/calcdeps.py", line 226, in CalculateDependencies
    search_hash = BuildDependencyHashFromDependencies(deps)
  File "../closure-library/closure/bin/calcdeps.py", line 196, in BuildDependencyHashFromDependencies
    dep.filename))
Exception: Duplicate provide (goog.net.DefaultXmlHttpFactory) in (../closure-library/_node_modules/protractor/node_modules/selenium-webdriver/lib/goog/net/xmlhttp.js, ../closure-library/closure/goog/net/xmlhttp.js)

SUCCESS: blockly_uncompressed.js
```

It has scanned `node_modules` when looking for dependencies.  The resultant js errors out.

Tipskies?

Thanks!

**Comment by Immortalin** [comment]
@cdaringe why would you want to run `npm install` in the closure library directory? What I usually do is fork the closure repo, rename the project name in package.json from `google-closure-library` to `closure-library`, fork the blockly repo, rename the project name in package.json from `blockly-src` to `blockly`. Then I would create the root folder for both, run `npm init` to create a package.json, add blockly and closure(the forked versions) to the dependencies section and finally run `npm install` in the root folder. After that you can `cd` into the node_modules/blockly directory and run`python build.py` and everything would magically work! :D

**Comment by cdaringe** [comment]
Thanks for the input @Immortalin.  The presence of a package.json is a declarative manifest stating that "this package is defined by these characteristics and dependencies."  To go modify the folder structure and generate a new package.json is to declare the first package.json insufficient.  99.99 percent of projects using it specify a main script used when importing the library.  Here, that's not the case.  Further, such requirements aren't stated in the README.  I would run npm install in a repo simply by observing a package.jsons presence, as that is how it is intended to be used, if dependencies are listed.

My tone is cordial, not brash, FTR :).  Anyway, we have an automated build script that npm installs all packages with a package.json then after runs all builds that have a Gruntfile/gulp file if present.  This automated workflow is what uncovered the issue

**Comment by Immortalin** [comment]
@cdaringe I am saying that you should modify the folder structure. I am suggesting that if you use npm to install blockly and closure, they would automatically be in the right structure.

**Comment by MarkusBordihn** [comment]
Would it help if blockly could be build only over npm e.g. with "npm run build" ?

**Comment by Immortalin** [comment]
@MarkusBordihn remember to `cd` into the blockly else you will get a `closure not found` error as npm runs scripts and such from the root directory so `python ./node_modules/blockly/build.py` will fail while `cd ./node_modules/blockly ;python .py

**Comment by MarkusBordihn** [comment]
@Immortalin 
The question was more if Blockly would be benefit  if it could be build over npm, so without the python script and only with an "npm install" and "npm run build".

**Comment by cdaringe** [comment]
respectfully, IMHO, if closure-library is a dependency of blockly _and_ blockly is using a package.json, closure-library should either (a) be a `dependency` of blockly or (b) installed into blockly perhaps during the npm `postinstall` lifecycle hook.  It would be great if blocky didn't depend on externals. then, i could do something like `npm run build` or `grunt build` or whatever, which automatically would run when installing blockly to begin with (assuming it was npm distributed).  which it can be!  we can help :)

**Comment by MarkusBordihn** [comment]
I just asked, because I build "closure-builder" for another project which could easily handle the task.
If there is enough interest for this I could provide a patch for the needed changes.

For more details see: https://www.npmjs.com/package/closure-builder

**Comment by samelhusseini** [comment]
Closing as we've removed our closure-library dependency.
