### ISSUE TITLE
logic_boolean block can not be dragged from toolbox on Android

### ISSUE THREAD

**Issue by plattysoft** [google/blockly#2055]
### Problem statement

When using blockly for Android, the block "logic_boolean" is not draggable from the toolbox.

### Expected Behavior

When you tap on the "logic_boolean" block, it get dragged.

### Actual Behavior

It is impossible to tap on the block outside the dropdown box, you either open the dropdown or click outside the block.

### Steps to Reproduce

- Create a default blockly Activity with the logic_boolean block on the toolbox.
- Start the app on an Android phone or emulator
- Tap on the logic_boolean block
- Observe unability to drag it into the workspace.

### Additional Information

Other similar blocks do not have this problem.

- The block "math_number" is almost equivalent, but in that case you can click on the field because it is not a dropdown, and then you can drag it.
- The block "text" has quotes on both sides and can be easily dragged.

A simple workaround is to add text at the beginning of the block, then it can be tapped.

A better solution would be to increase the touch area on the sides of the block, add some spacing by default or have a minimum block size.

**Comment by RoboErikG** [comment]
Unfortunately, we had to [deprecate the native versions](https://groups.google.com/forum/#!searchin/blockly/deprecated%7Csort:date/blockly/b0AOtB7lUGA/EqBQIQ0uAgAJ) of Blockly. We'll accept pull requests against the [Android Repo](github.com/google/blockly-android), but we won't be working on additional changes ourselves.
