### ISSUE TITLE
Add support for custom inputs

### ISSUE THREAD

**Issue by ewpatton** [google/blockly#2062]
### Problem statement

This is a feature request to consider refactoring how Input works so that we can register custom inputs similar to how one can register custom fields. The challenge is that input drawing is handled by the block, rather than the input (fields handle their SVG). If we have Input serve as a abstract superclass of new, concrete StatementInput, DummyInput, and ValueInput types, then we can consider creating IndentedValueInput and backport the functionality from App Inventor to Blockly. At the moment, any merge of Blockly into App Inventor requires resolving conflicts from having to modify the render pipeline and Input class to handle indented value inputs.

### Expected Behavior

It should be easier for developers building on Blockly to extend the available set of input types.

### Actual Behavior

Adding new types of inputs requires significant modification to Blockly core, which makes updating difficult due to merge conflicts, especially when refactoring is concerned.

### Steps to Reproduce

N/A

### Stack Traces

N/A

### Operating System and Browser

All browsers affected.

### Additional Information

A preliminary design doc has been created as a shared Google Doc [here](https://docs.google.com/document/d/1Q5PqKluRparnMdQ3pB_RFKeGnOuwhyR8sQkSEHRLct8/edit?usp=sharing).

**Comment by rachel-fenichel** [comment]
Can I get a pointer to the App Inventor code that does this?

**Comment by ewpatton** [comment]
Since there's no clean way to do this, it's just a set of patches on top of Blockly core. To get a rough idea of what we needed to do to realize this, here are a few pointers:

block.js: [954](https://github.com/mit-cml/blockly/blob/918349eaf385713023300f17b3941830f9b45f32/core/block.js#L954), [1164](https://github.com/mit-cml/blockly/blob/918349eaf385713023300f17b3941830f9b45f32/core/block.js#L1164)

block_render_svg.js: [764](https://github.com/mit-cml/blockly/blob/918349eaf385713023300f17b3941830f9b45f32/core/block_render_svg.js#L764), [800](https://github.com/mit-cml/blockly/blob/918349eaf385713023300f17b3941830f9b45f32/core/block_render_svg.js#L800), [809](https://github.com/mit-cml/blockly/blob/918349eaf385713023300f17b3941830f9b45f32/core/block_render_svg.js#L809), [822](https://github.com/mit-cml/blockly/blob/918349eaf385713023300f17b3941830f9b45f32/core/block_render_svg.js#L822)

connection.js: [45](https://github.com/mit-cml/blockly/blob/918349eaf385713023300f17b3941830f9b45f32/core/connection.js#L45)

input.js: [44](https://github.com/mit-cml/blockly/blob/918349eaf385713023300f17b3941830f9b45f32/core/input.js#L44)

Note that our implementation isn't RTL compatible, so work needs to be done there. The aim would be to produce an implementation of Input where we could provide our own subclass (although the easier option is to back port) without having to hack the above files.

**Comment by BeksOmega** [comment]
Previous PRs: #3219 , #2146

**Comment by rachel-fenichel** [comment]
@johnnesky is working on a plugin to implement the rendering side of this. We discussed the APIs needed in core, and decided that the `Input` class needs a new property (`externality` or some much better name) to track whether an input is indented/inline or external.

**Comment by johnnesky** [comment]
I finally sent out a pull request for a plugin, although I went with a design that's a little bit different than originally intended. I realized that inline value input connectors are basically the same as indented external value input connectors, except for two things:

1. By default Blockly doesn't provide any way to force adjacent inline value input connectors to be on separate rows. This is addressed by the plugin in my pull request: https://github.com/google/blockly-samples/pull/1398
2. The visual style of inline value input connectors is obviously a little different from indented external value input connectors, but I think the inline version is a little more idiomatic for some use-cases. 

I still think that there's value in exploring indented external value input connectors, although I think I would recommend using the inline style for the use-case of returning a single value from a function.

**Comment by BeksOmega** [comment]
After talking with App Inventor we decided that the inline value inputs wouldn't serve their use case. One significant blocker was existing image-based curricula. Changing how their blocks look would "break" those curricula.

As such, we need a solution that allows App Inventor to render its indented value inputs. The proposed solution is as follows:
* Add a new `appendInput(input: Input): Input` method to the block which allows external developers to append arbitrary subclasses of our built-in `Input` class.
* Add custom input subclasses to the register so that they can be constructed via JSON.
  * For now, custom input subclasses will not have a `fromJson` method, so the only configuration options they will have are the current `check` and `align` configurations.

Custom renderers can then check the type/class of a given input and choose to render it differently.

Note that custom input subclasses will (for now) need to construct their own connections if they have them, because Blockly will have no way of knowing which type of connection it needs.
