### ISSUE TITLE
mathRandomInt problem

### ISSUE THREAD

**Issue by aufabdulnafea** [google/blockly#2070]
Hi, 
I am trying to build my application with new customized blocks, but I am facing this problem 

Blockly.JavaScript['startnode'] = function(block) {
  var value_name = Blockly.JavaScript.valueToCode(block, 'NAME', Blockly.JavaScript.ORDER_ATOMIC);
  var code = 'd3.select("#cir-' + value_name + '").style("fill", "red");\n';
  return code;
};

the code is not working the returned value from "value_name" variable is a string value.. 
and when I add "eval".. 

Blockly.JavaScript['startnode'] = function(block) {
  var value_name = Blockly.JavaScript.valueToCode(block, 'NAME', Blockly.JavaScript.ORDER_ATOMIC);
  var code = 'd3.select("#cir-' + eval(value_name) + '").style("fill", "red");\n';
  return code;
};

I become an error that mathrandomint function cannot be found. 

by the way, I have imported all the needed js files like that. 

<script src="js/lib/blockly_compressed.js"></script>
<script src="js/lib/blocks_compressed.js"></script>
<script src="js/lib/javascript_compressed.js"></script>
<script src="js/lib/en.js"></script>
<script
   src="https://code.jquery.com/jquery-3.3.1.js"
   integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
   crossorigin="anonymous">
</script>
<script src="https://d3js.org/d3.v4.min.js"></script>

**Comment by AnmAtAnm** [comment]
Working as intended.  See discussion [here](https://groups.google.com/forum/#!topic/blockly/Dx-KG4d70M8).
