### ISSUE TITLE
Pull vs Downloading .zip

### ISSUE THREAD

**Issue by aramperez-tst** [google/blockly#2075]
### Problem statement

There appears to be a difference between doing a "git clone https://github.com/google/blockly.git" vs downloading the .zip file.

### Expected Behavior

I expected the name to be identical (but I'm a git novice). Doing a 'git clone' names the directory just 'blockly'. Downloading the .zip file and unzipping it creates a directory called 'blockly-develop'.

In addition, the 'git clone' version does NOT contain the './demos/mobile' sub-directory.

### Actual Behavior

See Expected Behavior above.

### Steps to Reproduce

1. Start by cloning the git repository.
2. Download the .zip file and unzip all the files.
3. Compare the created directory structures.

### Stack Traces

N/A

### Operating System and Browser

I'm on a MacBook Air running Mac OS X v10.13.6.

### Additional Information

Not at this time.

**Comment by flowkraD** [comment]
`git clone` will clone the entire repository including all the branches and hence it will share the same name as the repository when you view on Github which in this case is `blockly` whereas downloading zip, you can only download one branch at a time so if you download the `develop` branch the directory will be named `bockly-develop` or if you download the master branch you will get `blockly-master`. If you clone, you can get each branch by typing `git checkout <branchname>` and you can view the files of a particular branch.
This is the way how Github download system and `git` works. Both will give you different directory names, but both will have same files and link the dependencies same way.

**Comment by aramperez-tst** [comment]
Hi flowkraD,

As a git novice, this is very confusing. When I go to the project (https://github.com/google/blockly), the default branch is "master". So when I click on the "Clone or download" button, shouldn't I always get the "master" branch, no matter if I clone or download the zip file?

In addition, when I look at the "master" branch via my browser, the demos/mobile directory is there. But when I git clone it (using the url provided from clicking the "Clone or download" button), the demos/mobile directory is not there.

Thanks,
Aram

**Comment by AnmAtAnm** [comment]
Hi @aramperez-tst,

The zip versus clone issue is you're describing is a implementation detail of the GitHub system, and not anything we can do anything about. You can reach out to them at their [contact page](https://github.com/contact) or via the [community](https://github.community/).

As for the `demos/mobile` directory, this is new code that does not yet exist in master.  You might be looking at the `develop` branch in your browser. Expect it to land in master in the next release.
