### ISSUE TITLE
Bump blocks after size change

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2091]
Given the configuration below, a visual syntax error is created when the 'if' block expands:

![85ae3f19-c550-4f8c-abb3-6c60ef8a8c1f](https://user-images.githubusercontent.com/250480/47622291-c0525f80-dac0-11e8-8a16-33e4aac8a010.gif)

Found when I was doing a live demonstration of how our block bumping worked.  Turns out it doesn't.

**Comment by NeilFraser** [comment]
For reference, this sequence works properly:
![5176bb43-6d1a-4f2e-b13b-44aeeb52aa2f](https://user-images.githubusercontent.com/250480/47622455-3b684580-dac2-11e8-813a-2310199eaa88.gif)

**Comment by gonfunko** [comment]
Closing since I can no longer repro this.
