### ISSUE TITLE
Serializing a stack of blocks only outputs the first block

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2096]
### Problem statement

Dragging a stack of blocks out of the Toolbox only copies the top block in the stack.

### Expected Behavior

The entire stack should be dragged out.

### Actual Behavior

Only the first block in the stack is dragged out.

### Steps to Reproduce

1. Open the local copy of tests/playground.html on develop branch
2. Switch to test blocks
3. Try to drag out the stack in the drag category

### Stack Traces

```
Replace with error stack trace.
```

### Operating System and Browser

Desktop Chrome

**Comment by RoboErikG** [comment]
The simplest repro case is actually to stack two blocks in the playground and click export to xml. Only one block will be exported.

**Comment by RoboErikG** [comment]
Looks like #2080 broke it by changing the node type for next blocks. @NeilFraser

**Comment by NeilFraser** [comment]
Sorry.
Good fix.

**Comment by VoxelPerfect** [comment]
Please run a Rebuild so that the fix is included in the compressed files. I had to override Blockly.Xml.blockToDom with that in your latest commit to make it work.

**Comment by rachel-fenichel** [comment]
@VoxelPerfect done: https://github.com/google/blockly/releases/tag/1.20181105.0
