### ISSUE TITLE
how to build blocks_compressed.js?

### ISSUE THREAD

**Issue by merryzsp** [google/blockly#2099]
i use this script build the local_blockly_compressed.js:
java -jar closure-compiler.jar ^
  --js='..\core\**.js' ^
  --js='..\..\closure-library\closure\goog\**.js' ^
  --js='..\..\closure-library\third_party\closure\goog\**.js' ^
  --generate_exports ^
  --warning_level='DEFAULT' ^
  --compilation_level SIMPLE_OPTIMIZATIONS ^
  --dependency_mode=STRICT ^
  --entry_point=Blockly ^
  --js_output_file local_blockly_compressed.js

but i don't know how to rebuild the 
..\blocks\**.js   to  local_blocks_compressed.js
..\generators\**.js  to local_generators_xxx_compressed.js
..\msg\js\**.js to xxx_compressed.js

is there someone can help me?

**Comment by RoboErikG** [comment]
Please ask on [the forums](https://groups.google.com/forum/#!forum/blockly) for help.
