### ISSUE TITLE
Multi touch event on workspace blocks interaction with non blockly-elements in the DOM

### ISSUE THREAD

**Issue by emiliojazz** [google/blockly#210]
After trying to do a gesture with more than one finger on the workspace, the rest of the document (apart from the toolbox and the workspace itself) becomes unresponsive (touchend event stop propagating).
Shows up with even with the playground.html page given in the sources.

**Comment by rexpie** [comment]
Same issue here. I use both WKWebview and Chromium to display a page with blockly, and as soon as I try to swipe with two or three fingers inside the blockly window, the rest of the webpage stop to respond to any 'onclick' handlers.

Currenlty I replaced my 'onclick' event listeners with Blockly.bindEvent_ calls. This is ugly. It does not seem to be fair for Blockly to interfere other event handling systems on other parts of the webpage.

**Comment by rexpie** [comment]
@emiliojazz Please check out https://github.com/google/blockly/pull/232 to see my fix. Hope they merge it soon.

**Comment by NeilFraser** [comment]
Thanks for the bug report and the patch!
