### ISSUE TITLE
Icon API

### ISSUE THREAD

**Issue by ewpatton** [google/blockly#2105]
### Problem statement

Over the years, the extended App Inventor team has worked on a number of features that have modified Blockly core to add icons. It would be nice if we could have an API for registering new icons with the block so that we can keep the core clean(er).

### Expected Behavior

The ability to do something like:

```javascript
AI.Blockly.MyIconConstructor = function(block) { ... }
goog.inherits(AIBlockly.MyIconConstructor, Blockly.Icon);

// [snip] cf. Blockly.Mutator or Blockly.Warning

Blockly.Block.registerIcon('myicon', AI.Blockly.MyIconConstructor);

var block = Blockly.mainWorkspace.newBlock('controls_if');
// Visibility option 1
block.showIcon('myicon');
block.hideIcon('myicon');
// Visibility option 2
block.setIconVisible('myicon', true);
```

### Actual Behavior

One needs to modify multiple parts of core, such as block.js, block_render_svg.js, etc. to make this work correctly. This includes modifying functions like getIcons() and dispose() to handle the additional icons.

### Operating System and Browser

Affects all browsers

### Additional Information

We can provide pointers to examples over the years where we have done this if necessary to better understand the problem.

**Comment by BeksOmega** [comment]
Currently icons are only added to blocks in rendered mode. This makes it difficult to support round-tripping (serializing and deserializing) icons through a headless workspace. Eg, currently we have to do all sorts of [horrible](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/core/block.js#L2005) [things](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/core/xml.js#L729) to get comments (a type of icon) to round-trip correctly.

When the icon API is built out, icons should either be added in both rendered _and_ headless mode (like Fields), or have two separate types (like Block and BlockSvg) or have a more traditional MVC architecture.
