### ISSUE TITLE
Toolbox no longer works in master branch

### ISSUE THREAD

**Issue by okachobi** [google/blockly#212]
I recently pulled the latest blockly from master branch and code that previously worked with a toolbox is not working.  The toolbox renders from xml that looks like:

```xml
    <xml id="toolbox" style="display: none">
     <category name="Groupings">
      <block type="qfr_complete_all"></block>
      <block type="qfr_group_no_limit"></block>
      <block type="qfr_allow_minutes"></block>
      <block type="qfr_allow_until_date"></block>      
     </category>
     <category name="Step Types">
      <block type="qfr_question"></block>
      <block type="qfr_pause"></block>
      <block type="qfr_pause_until"></block>
      <block type="qfr_arriveat"></block>
      <block type="qfr_collect_qrcode"></block>
     </category>
     <category name="Data">
      <block type="text"></block>
      <block type="math_number"></block>
      <block type="lists_create_with"></block>
     </category>
    </xml>
```

For whatever reason, the first 2 categories which contain custom blocks render such that the blocks all appear on top of each other in the toolbar and cannot be selected.  The non-custom blocks (the last category) appear to render ok and can be selected.  Has there been some change in the block implementation that is required for the toolbox to format the blocks correctly in the toolbox?  The custom blocks were implemented using the block factory and then customized.

**Comment by okachobi** [comment]
Upon further investigation, it appears that FieldDate is not defined...

"Uncaught TypeError: Blockly.FieldDate is not a function"

greping the blocky_compressed.js reviewed FieldDate being included.  I have not run build.py with the new version but don't think I did in the past...

**Comment by okachobi** [comment]
I believe I solved my own issue with this thread - the FieldDate is commented out by default due to code bloat:

https://groups.google.com/forum/#!topic/blockly/Kr0DNBmGqnQ

**Comment by NeilFraser** [comment]
There was about a one week window between when FieldDate was added, and when it was commented out after noticing the resulting code bloat.  It's possible that your earlier sync happened during this window.  Sorry for breaking compatibility.  But as you saw it is now just a matter of uncommenting a line and recompiling.
