### ISSUE TITLE
Dropdown menu always scrollable

### ISSUE THREAD

**Issue by Gamadril** [google/blockly#2128]
### Problem statement
Dropdown menu is always scrollable.

### Expected Behavior
Dropdown menu is not scrollable if the height is large enough for contained entries.

### Actual Behavior
![image](https://user-images.githubusercontent.com/3903793/48759525-a52fd580-eca3-11e8-9455-604bfbdc327b.png)

### Steps to Reproduce
1. Open https://developers.google.com/blockly/
2. click on "Count" variable to open dropdown menu

### Operating System and Browser
Tested on MacOS with FF and Chrome.

### Additional Information

Problem seems to be in core/ui_menu_utils.js

```
/**
 * Get the size of a rendered goog.ui.Menu.
 * @param {!goog.ui.Menu} menu The menu to measure.
 * @return {!goog.math.Size} Object with width and height properties.
 * @package
 */
Blockly.utils.uiMenu.getSize = function(menu) {
  var menuDom = menu.getElement();
  var menuSize = goog.style.getSize(menuDom);
  // Recalculate height for the total content, not only box height.
  menuSize.height = menuDom.scrollHeight;
  return menuSize;
};
```
menuSize contains the correct size of the menu content including (!) the border width.
however its height is set to the scrollHeight of the content which is 2px less because of the border.

Setting border to 0 or box-sizing to content-box might solve the problem.

**Comment by AnmAtAnm** [comment]
Confirmed bug. May not be obvious if your Mac scrollbar settings are the default "Show scroll bars <only> When scrolling".
Not sure about other platforms.

**Comment by Gamadril** [comment]
Just connect a mouse to your mac and you will see all scrollbars everywhere.

**Comment by RoboErikG** [comment]
@alschmiedt to repro

**Comment by alschmiedt** [comment]
Can no longer repro
