### ISSUE TITLE
Trashcan Contents

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2136]
### Problem statement

Feature Request: Trash Can Contents.

### Expected Behavior

From [Site](https://developers.google.com/blockly/guides/modify/future#improved_ui): Clicking on the trash can should bring up a bubble that contains everything that has been deleted. These blocks may be dragged out of the trash and back into the workspace.

### Actual Behavior

Logs a TODO message to console, saying that this should be added.

### Steps to Reproduce

1. Click the trash can.

### Stack Traces

Not Applicable.

### Operating System and Browser

All of them.

### Additional Information

I would like to take a crack at this. Here's the bad version:

1) Have the trashcan subscribe to BlockDelete events, and add the oldXml to a "contents" var.
2) Have the trashcan create a flyout in its init() function.
3) Have the trashcan call .show(contentsVar) on the flyout when it is clicked.

![img_20181124_091221](https://user-images.githubusercontent.com/25440652/48971002-36b38600-efc9-11e8-8d2d-113538980d5b.jpg)

I'm a bit unsure of how the contents should appear. Should they be in a bubble like mutators? A fullsidebar like the toolbox? If the workspace layout it set to horizontal, should the contents be horizontal as well?

**Comment by RoboErikG** [comment]
Just a note, this is related to https://github.com/google/blockly/issues/225 

Internally, we've discussed doing some refactoring to support drop targets that could include a backpack. Listening to the delete event seems like a good short term option for just the trash, though I'm not sure how you'd remove things from the trash if the user undoes the delete (or if the list gets too big). Another option would be to scan the last N events in the undo stack each time the trash is opened, though this might be slower.

@rachel-fenichel any comments on design?

**Comment by rachel-fenichel** [comment]
- Removing things from trash: do we need to?
- XML for contents, gotten from the deletion events, sounds good to me
- UI: a flyout that shows up on the right side of the workspace (for LTR) sounds like a good place to start.  We can worry about horizontal later.  
- App Inventor has something similar for their backpack. 
- Adding better drop targets (such as a backpack) is related, but not necessary to make this work--block deletion is easy to catch from events.

I think you should start by looking at the app inventor code for displaying and dragging out backpack contents, and try to make something equivalent happen in Blockly.  Once you have that, correctly populating the trashcan based on events should be easy.  

@ewpatton can you point to the relevant code in App Inventor for the backpack rendering and interactions?
