### ISSUE TITLE
Accidental close in context menu

### ISSUE THREAD

**Issue by ewpatton** [google/blockly#2137]
### Problem statement

On smaller screens where Google Closure Library has trouble placing the context menu, it may appear under the mouse cursor. When this happens, the menu dismisses on the mouse up event of the right-click that opens the menu, triggering the action associated with the menu item that ends up appearing under the cursor.

### Expected Behavior

The menu should not automatically dismiss and require a "complete" click to trigger a menu item.

### Actual Behavior

As described above

### Steps to Reproduce

1. Open a resizable Blockly workspace and shrink the browser so that it takes up the entire viewport
2. Right-click on the workspace to open a menu. You may have to move around the workspace to find a sweet spot
3. On success, the menu will appear and then immediately disappear

### Operating System and Browser

I tested this with Desktop Firefox on macOS Mojave, but the App Inventor user who reported it was using 

### Additional Information

Based on my investigation, the problem appears to be from redefining `handleMouseUp` at this line:

https://github.com/google/blockly/blob/d3a73241aea0e5ec17eccbf6092ddff8fc3b756e/core/contextmenu.js#L105

The implementation of `handleMouseUp` in Google Closure Library will check to see whether there is a mouse up without a corresponding mouse down, and will not fire the action if that's the case. By overriding MenuItem's `handleMouseUp` with this version, it will accept the mouse up from the opening click of the context menu and trigger the bad behavior.

**Comment by samelhusseini** [comment]
We have re-implemented our own menu instead of using closure's, and I've verified that the above issue doesn't repro there.
