### ISSUE TITLE
Blockly not compiling totally when using build.py

### ISSUE THREAD

**Issue by kushal4** [google/blockly#2138]
Hi,
### Problem statement

When I am trying to compile blockly with build.py its generating all the languages in msg directory but after that its stopping with error :  
FATAL ERROR
required "Blockly.Block" namespace not provided yet
../closure-library/closure/goog/debug/entrypointregistry.js at line 30:
goog.require('Blockly.Block');

### Expected Behavior

Exapected behaviour should be that the build should automatically detect 

'Blockly.Block'  namespace but it doesn't
### Actual Behavior

the build.py doesn't detect 'Blockly.Block' namespace and it states that :-  
required "Blockly.Block" namespace not provided yet

### Steps to Reproduce

1. simply do build.py from the parent directory 

WARNING: definition of TEXT_INDEXOF_TOOLTIP in msg/json/lv.json contained a newline character.
SUCCESS: msg/js/es.js
SUCCESS: msg/js/id.js
SUCCESS: msg/js/da.js
SUCCESS: msg/js/ia.js
SUCCESS: msg/js/shn.js
SUCCESS: msg/js/ja.js
SUCCESS: msg/js/sk.js
SUCCESS: msg/js/hrx.js
SUCCESS: msg/js/vi.js
SUCCESS: msg/js/sl.js
SUCCESS: msg/js/ru.js
SUCCESS: msg/js/pt-br.js
SUCCESS: msg/js/bcc.js
SUCCESS: msg/js/oc.js
SUCCESS: msg/js/sr.js
SUCCESS: msg/js/sd.js
SUCCESS: msg/js/be-tarask.js
SUCCESS: msg/js/ms.js
SUCCESS: msg/js/lb.js
SUCCESS: msg/js/br.js
SUCCESS: msg/js/bg.js
SUCCESS: msg/js/diq.js
SUCCESS: msg/js/zh-hant.js
SUCCESS: msg/js/lv.js
SUCCESS: msg/js/tl.js
SUCCESS: msg/js/uk.js
SUCCESS: msg/js/fi.js
SUCCESS: msg/js/ta.js
SUCCESS: msg/js/az.js
SUCCESS: msg/js/sv.js
SUCCESS: msg/js/mk.js
SUCCESS: msg/js/ba.js
SUCCESS: msg/js/lrc.js
SUCCESS: msg/js/et.js
SUCCESS: msg/js/en.js
SUCCESS: msg/js/sq.js
SUCCESS: msg/js/tcy.js
SUCCESS: msg/js/pl.js
SUCCESS: msg/js/nl.js
SUCCESS: msg/js/bn.js
SUCCESS: msg/js/en-gb.js
SUCCESS: msg/js/nb.js
SUCCESS: msg/js/pt.js
SUCCESS: msg/js/zh-hans.js
SUCCESS: msg/js/ca.js
SUCCESS: msg/js/ro.js
SUCCESS: msg/js/lt.js
SUCCESS: msg/js/fr.js
SUCCESS: msg/js/ab.js
SUCCESS: msg/js/he.js
SUCCESS: msg/js/cs.js
SUCCESS: msg/js/it.js
SUCCESS: msg/js/fa.js
SUCCESS: msg/js/eo.js
SUCCESS: msg/js/el.js
SUCCESS: msg/js/tr.js
SUCCESS: msg/js/th.js
SUCCESS: msg/js/kab.js
SUCCESS: msg/js/ar.js
SUCCESS: msg/js/is.js
SUCCESS: msg/js/be.js
SUCCESS: msg/js/lki.js
SUCCESS: msg/js/de.js
SUCCESS: msg/js/hi.js
SUCCESS: msg/js/pms.js
SUCCESS: msg/js/tlh.js
SUCCESS: msg/js/ko.js
SUCCESS: msg/js/hu.js
SUCCESS: msg/js/sc.js
SUCCESS: blockly_uncompressed.js
SUCCESS: blockly_accessible_uncompressed.js
FATAL ERROR
required "Blockly.Block" namespace not provided yet
../closure-library/closure/goog/debug/entrypointregistry.js at line 30:
goog.require('Blockly.Block');

**Comment by NeilFraser** [comment]
This issue was resolved 8 months ago:
https://github.com/google/blockly/commit/0ac5b2773e97c23ae11f0cae9e9809fdb90530af
Sync to the latest version and everything should work fine.
