### ISSUE TITLE
Subtracting Tab Width from X Coordinates in BlockSvg.getBoundingRectangle Causes WorkspaceSvg.scrollX to have a value of 8.

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2150]
### Problem statement

So as you can see from the title I already tracked down what is causing WorkspaceSvg.scrollX to have a value of 8. This happens if you drag a block with an output into the trashcan, and this block leaves the workspace empty. The problem continues even after you have added more blocks to the workspace.

This is causing me problems [here](https://github.com/google/blockly/blob/d3a73241aea0e5ec17eccbf6092ddff8fc3b756e/core/trashcan.js#L340), because after .scrollX gets set to 8 the dx will always be larger than the Blockly.DRAG_RADIUS. 

### Steps to Reproduce

1. First add a log statement above [here](https://github.com/google/blockly/blob/d3a73241aea0e5ec17eccbf6092ddff8fc3b756e/core/trashcan.js#L340) 
console.log(this.workspace_.scrollX);

2. Open the playground and drag a 'control_if' block from the flyout to the trashcan.
3. Click the trashcan, observe that your log statement outputs a value of 0 (or approx 0).
4. Drag a 'logic_compare' block from the flyout to the trashcan.
5. Click the trashcan, observe that your log statement outputs a value of 8.

### Additional Information

How long it took me to track this down leads me to believe changing how blocks w/ outputs calculate their bounding rectangles would cause other issues, so my plan is to just change how the trashcan.click function works. But I wanted to notify you guys about it anyway (gotta get some use out of that hour of my life!).

**Comment by RoboErikG** [comment]
That is awesome, Beka. We've noticed that 8 showing up before but couldn't find the source. =D

**Comment by gonfunko** [comment]
Closing since `getBoundingRectangle()` no longer performs this adjustment.
