### ISSUE TITLE
Needing to Initialize Generator Before Calling .blockToCode is Opaque.

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2153]
### Problem statement

Calling [.blockToCode](https://github.com/google/blockly/blob/ca17e4019530c044ac828de4b3c57515572c67f4/core/generator.js#L165) does not automatically initialize the generator like [.workspaceToCode](https://github.com/google/blockly/blob/ca17e4019530c044ac828de4b3c57515572c67f4/core/generator.js#L90) does. 

### Expected Behavior

A) .blockToCode should initialize the generator.
or
B) .blockToCode should throw an informative error.

### Actual Behavior

You get opaque errors like: [Uncaught TypeError: Cannot read property 'getName' of undefined at Blockly.BlockSvg.Blockly.JavaScript.procedures_callnoreturn](https://groups.google.com/forum/#!topic/blockly/tnr9pxj81H4)

### Steps to Reproduce

1. Add below code ~ln 366 in playground.
`<xml xmlns="http://www.w3.org/1999/xhtml" id="workspaceBlocks" style="display:none">
    <block type="procedures_callnoreturn" deletable="false" id="4Tu3_y[h.I1HOr0m3.CE" x="12" y="13"></block>
  </xml>`
2. Add below code ~ln 124 (after workspace has been injected) in playground.
`var workspaceBlocks = document.getElementById("workspaceBlocks");
  Blockly.Xml.domToWorkspace(workspaceBlocks, workspace);
  Blockly.JavaScript.blockToCode(workspace.getBlockById('4Tu3_y[h.I1HOr0m3.CE'));`
3. Refresh the playground and observe the unhelpful error.

### Stack Traces

```
Uncaught TypeError: Cannot read property 'getName' of undefined
    at Blockly.BlockSvg.Blockly.JavaScript.procedures_callnoreturn (procedures.js:85)
    at Blockly.Generator.blockToCode (generator.js:185)
    at start (playground.html:126)
    at onload (playground.html:307)
```

### Operating System and Browser

Assuming this is not browser specific.

### Additional Information

This doesn't occure with all blocks, only blocks that require the generator to be initialized (e.g. proceedures).

**Comment by RoboErikG** [comment]
A better error is probably safer at this point. workspaceToCode calls blockToCode for every top level block and it gets called again from scrub_ in the language specific generators and a few other places, which would cause init() to be called repeatedly if it was in both methods.

Some alternatives would be:

1. Refactor out blockToCode into a protected inner method blockToCode_ and the public wrapper blockToCode, change workspaceToCode to call the protected version, and add the init to the public version.
2. Use the new [opt_thisOnly](https://github.com/google/blockly/blob/develop/core/generator.js#L166) flag to decide if init() needs to be called.

**Comment by moniika** [comment]
This issue seems to pop up as a question often.
We could also consider updating JSDoc for blockToCode to clarify that it assumes the generator has been initialized.
