### ISSUE TITLE
Programatically calling workspace setScale doesn't properly scale scrollbars

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#2160]
### Problem statement

Calling workspace setScale doesn't properly scale the workspace scrollbars. 
Currently the only instance of setScale called internally is the zoom reset button, but that calls scrollCenter which in turn sets the state of the workspace scrollbar. 

Calling setScale on the workspace without following up with updating the workspace's scrollbar state causes the following issue, see screenshot.

### Expected Behavior

Calling setScale sets the scale of the workspace and in turn update / invalidates the scrollbar state.

### Actual Behavior

![setscale](https://user-images.githubusercontent.com/16690124/49711811-574d2400-fbf6-11e8-976b-dd2f57a1e1ed.gif)

### Steps to Reproduce

1. Open the Blockly playground with the simple toolbox (Although I've checked this repro's for category toolboxes as well)
2. Open the browser console and type: 
```
Blockly.mainWorkspace.setScale(0.5)
```
3. Drag any Block from the flyout and notice how the Block's scale is off.
4. This also causes issues with the Blockly

**Comment by rachel-fenichel** [comment]
Weird.  `setScale` includes a call to `this.scrollbar.resize`, that I would expect to fix this.  
And I can't repro this on the hosted playground, either in simple or categories, with your repro steps you gave.

**Comment by samelhusseini** [comment]
Hmm. I have a 100% repro on local develop Blockly. You're right this doesn't repro on the hosted version, not sure why, maybe bits have changed since. 

Can you repro locally?

**Comment by rachel-fenichel** [comment]
Aha.  I can repro if there are no blocks on the workspace.  If there are blocks on the workspace, it correctly adjusts the scale and it's all good.

It's short-circuiting the scrollbar update because the host metrics haven't changed, [here](https://github.com/google/blockly/blob/develop/core/scrollbar.js#L99).  If there's a block on the screen the host metrics *do* change.
