### ISSUE TITLE
uncheckedconversions compilation error: Fix in progress

### ISSUE THREAD

**Issue by murcielag00** [google/blockly#2164]
### Problem statement
Bug report:

Compiling blocks not work. It use closure-library to compile blocks.

### Expected Behavior

Yesterday, i compiled some blocks and there's no problem. NO changes in the application. 

### Actual Behavior

We can't compile new blocks.

### Steps to Reproduce
python build.py
(the path is fine)

### Stack Traces

FATAL ERROR

Violation: Using unchecked conversions requires a security review. See http://go/safe-coding/findings/restricted-apis#unchecked-conversions. Please use go/jsconformance-yaqs if you have further questions.

??? at line 1025:

      goog.html.uncheckedconversions
### Operating System and Browser

Tested:
Python 2.7.13
Linux sysop 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
Windows 10

### Additional Information

There's an issue in closure-library github about the file "trustedresourceurl.js" modified 17 hours ago. 
"uncheckedconversions.js" have goog.require('goog.html.TrustedResourceUrl'). I think this could be some relation with the problem.

**Comment by jonathancslynn** [comment]
I'm getting the same error too

**Comment by jonathancslynn** [comment]
I have the same problem on build as well.
OS: macOS Mojave 10.14
Python: 2.7.10

**Comment by pabl0xf** [comment]
Me too
4.8.0-59-generic #64-Ubuntu 
Python 2.7.12+

Building only generator works, but i'm not able to build the blocks again :(

**Comment by arclien** [comment]
Yeah, I have too....
not able to go through building blockly files ....

**Comment by RoboErikG** [comment]
It looks like Closure team added some security checks on the use of SafeHtml (which shows up in toolbox.js). We're looking into it but not clear yet what the tool wants us to change.

**Comment by physicsfamily** [comment]
I have the same problem.

.....
SUCCESS: msg/js/is.js
SUCCESS: msg/js/oc.js
SUCCESS: msg/js/gor.js
FATAL ERROR
Violation: Using unchecked conversions requires a security review. See http://go/safe-coding/findings/restricted-apis#unchecked-conversions. Please use go/jsconformance-yaqs if you have further questions.
??? at line 1025:
      goog.html.uncheckedconversions
      ^
SUCCESS: blockly_uncompressed.js
SUCCESS: blockly_accessible_uncompressed.js
root@fremont:~/blockly#

**Comment by RoboErikG** [comment]
This has now been fixed on the Closure server.
