### ISSUE TITLE
Set Trashcan Max Contents through Options Struct

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2165]
### Problem statement

At the moment you can only edit the max contents of the trashcan's flyout by changing the core.

### Expected Behavior

You should be able to change this through the workspace options struct.

### Actual Behavior

You are only able to change it by editing the [MAX_CONTENTS ](https://github.com/BeksOmega/blockly/blob/77ee4c8e22b41f7f127bda05833ec929829263d8/core/trashcan.js#L126)property of the trashcan.

### Steps to Reproduce

N/A

### Stack Traces

N/A

### Operating System and Browser

All of them.

### Additional Information

N/A

**Comment by samelhusseini** [comment]
Fixed by #2183
