### ISSUE TITLE
Realtime working only on a single browser/Machine

### ISSUE THREAD

**Issue by ziban** [google/blockly#217]
Blockly realtime is working only on a single browser e.g if I open it in Chrome, it will only work on Chrome  on that particular computer and not work  on any other browser on the same machine or other machines, even if users are logged in with Google.

**Comment by carlosperate** [comment]
Realtime is a feature that has had some issues and will have an upcoming revamp. See https://groups.google.com/forum/#!topic/blockly/W531zTbSrbo for more information.
