### ISSUE TITLE
Warnings Not Interacting with Collapsion/Expansion Correctly

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2175]
### Problem statement

Warnings don't act as expected when interacting with collapsion/expansion.

### Expected Behavior

1. Warnings should stay attached to a block even if the block is collapse & expanded.
2. If a warning is attached to a block and then the parent block is collapsed the warning should "bubble up" to the parent block.
3. If a warning is attached to a block when the parent block is already collapsed the warning should "bubble up" to the parent block.
4. When a block is expanded all warnings that have "bubbled up" should be removed, leaving only the original warnings.

### Actual Behavior

1. Warning stays when block is collapsed, disapears when block is expanded.
2. Does not happen.
3. Happens.
4. All warnings get removed (including original warnings) causing the warning to disapear as in 1.

![brokenwarn 1](https://user-images.githubusercontent.com/25440652/50055615-0feafa00-0106-11e9-91e6-de0890b4e2ca.jpg)
![brokenwarn 2](https://user-images.githubusercontent.com/25440652/50055616-12e5ea80-0106-11e9-92da-8b8e86777ca7.jpg)
![brokenwarn 3](https://user-images.githubusercontent.com/25440652/50055621-14afae00-0106-11e9-90e9-45f749b3e650.jpg)

### Steps to Reproduce

1. Add below code at ~ln 124 in playground:
`var workspaceBlocks = document.getElementById("workspaceBlocks");
  Blockly.Xml.domToWorkspace(workspaceBlocks, workspace);
  workspace.getBlockById('1').setWarningText('warning');
  workspace.getBlockById('2').setWarningText('warning');
  workspace.getBlockById('3').setWarningText('warning');
  workspace.getBlockById('4').setWarningText('warning');`
2. Add below code at ~ln 367 in playground:
`<xml xmlns="http://www.w3.org/1999/xhtml" id="workspaceBlocks" style="display:none">
    <block type="controls_if" id="1" x="12" y="13"></block>
    <block type="controls_if" x="12" y="100">
      <value name="DO0">
        <block type="controls_if" id="2"></block>
      </value>
    </block>
    <block type="controls_if" id="3" x="12" y="250">
      <value name="DO0">
        <block type="controls_if" id="4"></block>
      </value>
    </block>
  </xml>`

2. Collapse all of the top level 'controls_if' blocks.
3. Observe how the warning from the second stack does not "bubble up".
4. Expand all of the top level 'controls_if' blocks.
5. Observe how the warnings disappear.

### Stack Traces

N/A

### Operating System and Browser

Affects all Browsers

### Additional Information

N/A

**Comment by samelhusseini** [comment]
Fixed by #2176
