### ISSUE TITLE
Render error during drag on ChromeOS

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#2181]
### Problem statement

When dragging certain blocks, the dragged block on chromebook had a major rendering error.
![screenshot 2018-12-17 at 5 04 40 pm](https://user-images.githubusercontent.com/9916202/50175376-76604b80-02b1-11e9-97d0-5654e4ff0d98.png)

The error only occurred when dragging the "and" block, with no children, away from a prior parent connection. Dragging a previously disconnected block did not create the error, nor did dragging the block if it had children. Dragging other blocks rarely created the error.

Major rendering error was not reproducible after refresh, but minor errors limited to the bounds of the block were seen after refresh. The error was significantly more common on the "and" block without children. The major render occurred only on LTR, but the minor error was seen in both LTR and RTL. The error was only seen on the Dec2018 release candidate, and not the master/production release demos.

It is strongly possible this is a transient error, as it looks like the type of render error seen when a graphics subsystem runs out of memory. However, I would expect the error to be more random, less reproducible, or more easily reproducible over a wider breadth of actions/sequences if that was the case.

### Expected Behavior

No render errors.

### Steps to Reproduce

1. Build stack described in the manual testing document.
2. Delete the "not" and "true" children in the "and" block.
3. Drag the "and" block to disconnect it from its parent.

### Operating System and Browser

 * Asus C100-PA Flip Chromebook likely using ChromeOS 71.0.3578.94 (released Friday Dec 14th)

**Comment by gonfunko** [comment]
Closing given the age of this issue and suspicion that it may have been transient when originally filed. Given the popularity of ChromeOS in educational settings I expect we would have heard quite a lot about this if it was an ongoing issue.
