### ISSUE TITLE
Chrome Android: Cannot invoke workspace context with long press

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#2188]
### Problem statement

Long press on empty workspace area does not invoke the Blockly context menu.

### Expected Behavior

A long press on empty workspace should pop open the context menu if options like "Delete <N> blocks".

### Actual Behavior

The long press selects some text.  It may be label text in a block in the toolbox, as shown:
![screenshot_20181219-104813](https://user-images.githubusercontent.com/9916202/50243643-83993b00-0382-11e9-9911-8d77cf7ee461.png)

Or it may be text adjacent to the workspace, particularly if the toolbox flyout is not open.

Long press on a block will open the expected context menu.

### Steps to Reproduce

1. On an Android device with a recent version of Chrome, open any page with blockly.
2. Optionally add a block to the workspace from the toolbox or by loading a workspace.
3. On a blank space on the workspace, long press.
4. Note that the context menu did not come up, and now there is a text word selected, possibly on a block `field_label`.

### Operating System and Browser

* Android Pixel 2XL:
  * OS: Android 9
  * Browser: Chrome 
  * Version 71.0.3578.99

### Additional Information

Given #2187 is also related to Android Chrome, is also touch related, and is also seen in master.

**Comment by surajguduru** [comment]
Hey @AnmAtAnm  I would like work on this issue. Can you assign it to me ?

**Comment by BeksOmega** [comment]
@surajguduru Do you have an Android device to test with?
