### ISSUE TITLE
Document maxTrashcanContents Option

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2192]
### Problem statement

Request for documentation.

### Expected Behavior

The "[Getting Started](https://developers.google.com/blockly/guides/get-started/web)" page should include information about the maxTrashcanContents option.

### Actual Behavior

The "[Getting Started](https://developers.google.com/blockly/guides/get-started/web)" page is missing information about the maxTrashcanContents option.

**Comment by rachel-fenichel** [comment]
@alschmiedt will add this documentation, though it won't be pushed to the developer site until our next bimonthly release.

**Comment by rachel-fenichel** [comment]
Pushed.
