### ISSUE TITLE
No Accessor to tell if BlocklyStorage has Anything Stored

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2197]
### Problem statement

There is no way to tell whether there are blocks stored. So if you want to populate the workspace with starter blocks (undeletable/unmovable blocks) they get created in BlocklyStorage.restoreBlocks & in Blockly.Xml.domToWorkspace(). So you end up with duplicate starter blocks.

### Expected Behavior

There should be an accessor so you can tell if there are blocks stored. Then if there weren't any blocks stored you could call .domToWorkspace() and if there were blocks stored, you could restore them.

### Actual Behavior

You end up with a situation like so:
![multiplyingthroughsaving](https://user-images.githubusercontent.com/25440652/50530980-36bb1000-0ab8-11e9-886c-2f18276a59e4.gif)

### Steps to Reproduce

1. Add below code at ~ln 68 in playground.
`<script src="../appengine/storage.js"></script>`
2. Add below code at ~ln 124 in playground.
  ```
var workspaceBlocks = document.getElementById("workspaceBlocks");
  Blockly.Xml.domToWorkspace(workspaceBlocks, workspace);
  window.setTimeout(BlocklyStorage.restoreBlocks, 0);
  BlocklyStorage.backupOnUnload();
```
3. Add below code at ~ln 369 in playground.
  ```
<xml xmlns="http://www.w3.org/1999/xhtml" id="workspaceBlocks" style="display:none">
    <block type="controls_if" id="1" x="12" y="13"></block>
  </xml>
```
4. Refresh the toolbox repeatedly, observe how you continue to get more "controls_if" blocks.

### Stack Traces

N/A

### Operating System and Browser

I'm assuming this is not browser specific.

### Additional Information

I'm like 49% sure that there actually is a way to do this, I just couldn't find it.

Also I'm using local storage so I just added the below code to BlocklyStorage:
```
BlocklyStorage.hasStorage = function() {
  var url = window.location.href.split('#')[0];
  return 'localStorage' in window && !!window.localStorage[url];
};
```
So then the loading code just looks like this:
```
       if (BlocklyStorage.hasStorage()) {
          window.setTimeout(BlocklyStorage.restoreBlocks, 0);
          BlocklyStorage.backupOnUnload();
        } else {
          var workspaceBlocks = document.getElementById("workspaceBlocks");
          Blockly.Xml.domToWorkspace(workspaceBlocks, workspace);
        }
```

**Comment by rachel-fenichel** [comment]
BlocklyStorage is something that we use to make our demos work nicely, but isn't really part of the core library.  Handling storage is the responsibility of the developer, and depends on what the application is and where it's being run.
