### ISSUE TITLE
Document Mutator's saveConnections

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2198]
There is no mention of [saveConnections](https://github.com/google/blockly/blob/09853c37250528b65a87f6e0bb73432b57f86108/core/mutator.js#L283) on the [Web Mutators](https://developers.google.com/blockly/guides/create-custom-blocks/web/mutators#mixin_object) page.

It is used in the [controls_if mutator](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/blocks/logic.js#L399), the [text_join mutator](https://github.com/google/blockly/blob/b88a3bf41a15f2d92853cb7806effc53ef048882/blocks/text.js#L727), and the [list_create_with](https://github.com/google/blockly/blob/ca17e4019530c044ac828de4b3c57515572c67f4/blocks/lists.js#L213) mutator.

The Web Mutators page does mention that connections _should_ be saved at [the bottom of the compose and decompose section](https://developers.google.com/blockly/guides/create-custom-blocks/web/mutators#compose_and_decompose), but there is no mention of saveConnections.

**Comment by joseluiz98** [comment]
This function has documentation in someplace?

**Comment by BeksOmega** [comment]
Bloop: https://developers.google.com/blockly/guides/create-custom-blocks/web/mutators#saveconnections
