### ISSUE TITLE
Node.js instead of appengine

### ISSUE THREAD

**Issue by khanshakeeb** [google/blockly#220]
Hi,
I am new to blockly and going to create programming platform for children. Kindly let me know can I used nodejs as server instead of appengine?

Kindly share with me resources for that

Thanks

**Comment by MarkusBordihn** [comment]
The "server" is no requirement for Blockly, so you could use it offline as well (simple HTML page).
Is there are "special" functionality you want to use, which required an server ?

**Comment by khanshakeeb** [comment]
Yes, I want to make platform where user get signup, played with programming puzzle, create new programming puzzle and share with communities.

So I have to used Database for storage. Later I have decided to create cross platform desktop application by using electron

Thanks

**Comment by MarkusBordihn** [comment]
This is possible with the the following commands.

Storing the current workspace:
```
var xml = Blockly.Xml.workspaceToDom(workspace);
var data = Blockly.Xml.domToText(xml);
// data needs to store to your database
```

Loading the stored workspace:
```
var xml = Blockly.Xml.textToDom(data);
Blockly.Xml.domToWorkspace(workspace, xml);
```
You could use the app engine demo as general example.

**Comment by khanshakeeb** [comment]
Great, then let me develop out of the box application 

Thanks
