### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by harrybanda** [google/blockly#2200]
[This package](https://www.jsdelivr.com/package/npm/blockly) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by AnmAtAnm** [comment]
Our project does not fit the standard NPM expectations of a one .js import for one repo. Developers are expected to pick their appropriate...

 * blocks (often, but not necessarily, [blocks_compress.js](https://raw.githubusercontent.com/google/blockly/master/blocks_compressed.js))
 * generators (e.g., [javascript_compress.js](https://raw.githubusercontent.com/google/blockly/master/javascript_compressed.js))
 * and [language files](https://github.com/google/blockly/tree/master/msg/js)

in addition to the core implementation ([blockly_compressed.js](https://raw.githubusercontent.com/google/blockly/master/blockly_compressed.js)).

Given this, default file is inappropriate for this project.
If you happen to be using the the default blocks, with JavaScript generators and English language, you can use the gulp build file to concatenate these files in to an NPM-ready file.
