### ISSUE TITLE
blockfactory error

### ISSUE THREAD

**Issue by wwj718** [google/blockly#2206]
![image](https://user-images.githubusercontent.com/3153878/50629944-a1b58c80-0f79-11e9-9918-31e99b074b17.png)

**Comment by wojiaofengzhongzhuifeng** [comment]
hi, how do you resolve this problem?

**Comment by RoboErikG** [comment]
Are you accessing the demo from China?

**Comment by wwj718** [comment]
@RoboErikG Yes.
@wojiaofengzhongzhuifeng  It is normal.
