### ISSUE TITLE
Uploading Blockly to https://www.npmjs.com/

### ISSUE THREAD

**Issue by MarkusBordihn** [google/blockly#221]
With this "feature" request I want to discuss the integration of blockly to the offical npm repository.

Main concerns:
* Blockly has no number versions
* Rolling releases
* Required NPM account

Possible solution:
* Simple NPM script which could be run with "npm run deploy" which will automatically tag the change with an version number and updates the manifest.js by 0.0.1 and do the git push.
* An Travis CL job will detect each tagged git push and will automatically update the npm package on https://www.npmjs.com/

The setup would not be complex, but the maintainer of this repository needs to make sure to use such npm script to update the version number and to tag the release.

Advanced:
* Easy installation with "npm install blockly".
* Possibility to easily switch version for debuging and testing within npm.
* Possibility to stick to an version if something is broken in a newer version.
* Pseudo version numbers

Greetings,
- Markus B.

**Comment by carlosperate** [comment]
Related discussions: https://github.com/google/blockly/pull/136 https://github.com/google/blockly/issues/177

**Comment by MarkusBordihn** [comment]
Will close this, because it seems its not really needed.
