### ISSUE TITLE
block.dispose(/*healStack*/ true) should not attempt to heal shadow block connections

### ISSUE THREAD

**Issue by kushal4** [google/blockly#2227]
### Problem statement

Go to  https://blockly-demo.appspot.com/static/demos/code/index.html.
Then bring the setter block  

![setter_block_1](https://user-images.githubusercontent.com/23696183/51530737-a32ff180-1e61-11e9-9d60-5a6f1d6505a1.png)
![setter_variable_2](https://user-images.githubusercontent.com/23696183/51530740-a5924b80-1e61-11e9-9a07-22c0db74f6a1.png)
![setter_variable_3](https://user-images.githubusercontent.com/23696183/51530742-a75c0f00-1e61-11e9-9074-8e7c8532effa.png)

### Expected Behavior

The setter block shouldnt have the shadow block attached after the math block is delete
### Actual Behavior

the setter block  contains shadow block after math block is deleted

### Steps to Reproduce

1. Go to  https://blockly-demo.appspot.com/static/demos/code/index.html.
2.Create a variable.
3.Bring the setter variable block to the workspace.
4.Connect a math block to the setter block containing shadow block.
5.Delete this math block.

### Operating System and Browser

Chrome Desktop

**Comment by AnmAtAnm** [comment]
Confirmed.

**Comment by AnmAtAnm** [comment]
This is not specific to the variable set block. This looks like an over application of the `healStack` argument of `Block.prototype.dispose()`. It should definitely not be applied to shadow blocks

However, given that it is "heal **stack**", I'm not convinced it should be applied to value inputs at all. Do we want a delete operation (dispose with heal) to turn this:
![screen shot 2019-02-05 at 1 27 40 pm](https://user-images.githubusercontent.com/9916202/52305550-38df7c80-294a-11e9-942c-b49970718ba3.png)

Into this:
![screen shot 2019-02-05 at 1 27 49 pm](https://user-images.githubusercontent.com/9916202/52305566-409f2100-294a-11e9-8a2e-bb761943a2b9.png)

Or this:
![screen shot 2019-02-05 at 1 28 14 pm](https://user-images.githubusercontent.com/9916202/52305574-48f75c00-294a-11e9-847a-53abf6d8d4f5.png)

Or delete the entire subtree (equivalent to `block.dispose(/*don't heal*/false, /* do anim*/true);`{.javascript}).

I don't think the first option makes any sense.  The second, might seem reasonable in a few cases, but but I don't think it ever makes sense with more than one input connected, and we probably should change behavior based on the number of inputs of the deleted block. Thus leaves the last, option: delete entire branch.

**Comment by AnmAtAnm** [comment]
Splitting out the larger question of whether to heal value inputs in #2261.
