### ISSUE TITLE
COC?

### ISSUE THREAD

**Issue by alison985** [google/blockly#223]
Hi,

I'm just wondering what your code of conduct is for this project?

Thanks,
Alison

**Comment by NeilFraser** [comment]
All but one of the Blockly contributors with check-in permissions are Google employees and are thus bound by [Google's corporate code of conduct](https://investor.google.com/corporate/google-code-of-conduct.html).  The sole exception is our semi-automated checkins of content from [TranslateWiki](https://translatewiki.net/).

**Comment by pcbro** [comment]
Nice @alison985, I see you're PC too :+1:
