### ISSUE TITLE
Blocks disapper when a custom block connects with a defined block

### ISSUE THREAD

**Issue by rockbass2560** [google/blockly#2231]
### Problem statement

When I connect a custom block with a defined block I get the error described below. Also, the blocks disapper on the workspace

### Steps to Reproduce

1. I generate a custom block, the block is type "dummy" using Blockly Developer Tool
2. In toolbox I define two categories, the first category contains custom blocks, the second category contains default blocks
3. Both blocks are shown in workspace but I connect them a error is generated and the blocks disapper on the workspace

### Stack Traces
```
  | Blockly.WorkspaceAudio.play | @ | blockly_compressed.js:1236
-- | -- | -- | --
  | Blockly.BlockAnimations.disposeUiEffect | @ | blockly_compressed.js:1075
  | Blockly.BlockSvg.dispose | @ | blockly_compressed.js:1459
  | Blockly.BlockDragger.maybeDeleteBlock_ | @ | blockly_compressed.js:1106
  | Blockly.BlockDragger.endBlockDrag | @ | blockly_compressed.js:1104
  | Blockly.Gesture.handleUp | @ | blockly_compressed.js:1156
  | Blockly.TouchGesture.handleUp | @ | blockly_compressed.js:1202
  | h | @ | blockly_compressed.js:1723
```

### Operating System and Browser

Android 7.0, Samsung Galaxy Tab S2, Blockly inside Webview

**Comment by RoboErikG** [comment]
Hi rockbass,

Questions about specific errors in your own app are best asked on [the forum](https://groups.google.com/forum/#!forum/blockly). We use the issue tracker for bugs that can be reproduced in the Playground or with a minimal bit of example code to repro it, and testing your repro steps in the Developer tools doesn't produce an error.

Can you also include the full error when you ask on the forum? You've posted the stack trace but not the error.

**Comment by rockbass2560** [comment]
Did you test on a mobile? because the error only show in webview for android.

**Comment by rockbass2560** [comment]
I tested too in web browser and I didn't get any error, only in android.

**Comment by rockbass2560** [comment]
I just discover that the error only appears when you are a remote debugging with chrome... thanks for your help
