### ISSUE TITLE
Shadow blocks are positioned wrong when converted to real blocks in DevTools

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2234]
### Problem statement

In the ToolboxEditor of the [DevTools](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html), when you drag out a block with shadow blocks they get rendered in the wrong positions.

![image](https://user-images.githubusercontent.com/11066279/51771940-84b73980-209f-11e9-8b82-dba0b0d3cfbc.png)

### Expected Behavior

The shadow blocks that are dragged out are converted to regular blocks with the shadow rendering and appear in the correct places.

### Actual Behavior

They end up rendered offset from their correct position.

### Steps to Reproduce

1. Open [DevTools](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html)
2. Go to the Workspace Factory tab.
3. Drag out a 1 + 1 block

### Stack Traces

```
Replace with error stack trace.
```

### Operating System and Browser

Desktop Chrome

**Comment by NeilFraser** [comment]
Affects all browsers tested: Chrome, Firefox and Safari.
Not reproducible in code demo, only the dev tools.
Does not affect non-shadow blocks.

**Comment by RoboErikG** [comment]
Note, I can only repro when dragging them out of the Toolbox, which causes them to be converted to non-shadow blocks with shadow rendering. There's probably a layout step missing when that conversion happens.

**Comment by RoboErikG** [comment]
Woops, this is a dupe of #1693

**Comment by iadegesso** [comment]
This behaviour is still present in the master branch at 2019, 5th September.

Both in Firefox and in Chrome on a x85_64 Gentoo Linux workstation.

Iade Gesso, PhD in Computer Science
