### ISSUE TITLE
Trash hotspot wrong when trash is full.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2237]
1. Open this page:
  https://beta-dot-blockly-games.appspot.com/music
2. Drag a block over the trash.  Explore the top/bottom/left/right boundaries of the hotspot.  They are correct.
3. Drop the block into the trash.
4. Open the trash flyout, and drag the block out.
5. Drag this block over the trash.  Explore the top/bottom/left/right boundaries of the hotspot.  They are incorrect.

Affects both RTL and LTR.

**Comment by NeilFraser** [comment]
@BeksOmega I think this is yours?

**Comment by rachel-fenichel** [comment]
I agree, the root behaviour is bad, and fixing it would be better than adding in more special cases to mitigate it.  So go for it.

**Comment by NeilFraser** [comment]
Fix confirmed.  Thanks!
