### ISSUE TITLE
Image dropdowns of disabled blocks don't render properly.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2238]
1. Open https://beta-dot-blockly-games.appspot.com/music
2. Drag note block from toolbox directly to trash.
3. Drag note block from toolbox to workspace as an orphan so it gets disabled.
4. Drag disabled block to trash.
5. Look in the trash.

<img width="190" alt="screen shot 2019-01-28 at 11 54 40" src="https://user-images.githubusercontent.com/250480/51862677-f7205780-22f3-11e9-9f2c-966c4aa3ebf0.png">

Note that the dropdown fails to render properly.

**Comment by NeilFraser** [comment]
@BeksOmega I think this is yours?

**Comment by NeilFraser** [comment]
This issue is unrelated to the trash.  It's actually a bug in the rendering of image dropdowns.

1. Go to: tests/playground.html?toolbox=test-blocks
2. From the 'Fields' category, create a block with the image dropdown.
3. Right-click, disable block.
4. Right-click, duplicate block.

![screen shot 2019-01-29 at 10 59 38](https://user-images.githubusercontent.com/250480/51932974-25b23700-23b5-11e9-89d3-d87368341b02.png)

**Comment by BeksOmega** [comment]
I can still grab it if you're not working on it already.

**Comment by NeilFraser** [comment]
Go for it!  At this point my knowledge of the update path is obsolete enough that it's actively dangerous.  :)

**Comment by AnmAtAnm** [comment]
@rachel-fenichel @BeksOmega 
Resolved by #2246?
