### ISSUE TITLE
Disabled blocks can't be retrieved from the trash.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2239]
1. Open https://beta-dot-blockly-games.appspot.com/music
2. Drag note block from toolbox to workspace as an orphan so it gets disabled.
3. Drag disabled block to trash.
4. Open trash and attempt to retrieve the disabled block.

Disabled blocks can't be pulled out of the trash.

**Comment by NeilFraser** [comment]
@BeksOmega I think this is yours?

**Comment by BeksOmega** [comment]
Before I fix this (and #2238 ) I wanted to lay out another option: disabled blocks could be re-enabled when they are added to the trashcan.

I've never asked, but I assume the main usecases for disabled blocks are A) user debugging and B) blocks in the incorrect context? If this is true I don't think it'd be confusing that when the blocks are taken out of their debugging/incorrect context (i.e. put into the trashcan) they would be reenabled.

Opinions?

**Comment by rachel-fenichel** [comment]
Yeah, we discussed that briefly but were split on whether we wanted re-enabling to happen.  For now let's leave them disabled.

**Comment by NeilFraser** [comment]
Fix confirmed.  Thanks!
