### ISSUE TITLE
Add `local` option to build.py

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2245]
### Problem statement

build.py relies on the online closure compiler.  This is a problem for anyone in china and anyone who frequently rebuilds and gets rate limited.

We have a local build script that uses the local closure compiler, but it's a separate script and you have to manually download the compiler jar.

### Expected Behavior

- build.py has a `local` option that forces it to use the local closure compiler.
- Either the closure compiler jar is automatically downloaded and unzipped, or error messages tell the developer exactly what to do.

### Additional Information
https://www.npmjs.com/package/google-closure-compiler may be relevant

**Comment by jobsFu** [comment]
I cannot use python build.py in China and then use closure compiler to display The compiler is waiting for input via stdin. Why?

**Comment by vkboo** [comment]
> I cannot use python build.py in China and then use closure compiler to display The compiler is waiting for input via stdin. Why?

I want to know why~

**Comment by samelhusseini** [comment]
The python build.py script uses the online closure compiler to compile Blockly. This may be blocked by certain proxies. 
We have added a local build script option that you can use instead, first run:
```
npm install
```
then to execute the build script run:
```
npm run build
```

**Comment by vkboo** [comment]
> The python build.py script uses the online closure compiler to compile Blockly. This may be blocked by certain proxies.
> We have added a local build script option that you can use instead, first run:
> 
> ```shell
> npm install
> ```
> 
> then to execute the build script run:
> 
> ```shell
> npm run build
> ```

Not have "build" script in `package.json`

**Comment by vkboo** [comment]
@samelhusseini The `build` script can not build language json file to js, and how to do it?

**Comment by samelhusseini** [comment]
Yes, the gulp script doesn't have support for that yet. 
For now, you can do that using the old script, and that shouldn't hit the online closure compiler endpoint, so you should be fine:
```
python build.py --langfiles
```
You will need to comment out this [line](https://github.com/google/blockly/blob/master/build.py#L501) so you skip the compiling core Blockly.

**Comment by rachel-fenichel** [comment]
We have deprecated build.py in favor of `npm run build`.
