### ISSUE TITLE
UX feature: Faster accessing of needed blocks

### ISSUE THREAD

**Issue by dz0** [google/blockly#225]
It's a bit frustrating to construct more advanced expresion from different categories... Too many clicks..
As some blocks/expressions are mostly used - could we have them accessible "at a glance"?

Proposals:
- Could be something like http://wiki.scratch.mit.edu/wiki/Backpack (which could store the needed blocks in cookie). This could be extra space below categories -- in "root" (or separate category, if would be complicated to implement in "root")
-  Categories could open  on some hotkeys (maybe 1, 2, 3 or Alt+FirstLetter or so). So it would be faster to look through all the cats..
- quick search for the block (though it kind of breaks the idea of blockly "drag and drop" -- but it is very common in IDE's as hinting or autocomplete)

**Comment by rachel-fenichel** [comment]
Moving to https://github.com/google/blockly-samples/issues/233
