### ISSUE TITLE
request: Auto-generate Create buttons for added variable types

### ISSUE THREAD

**Issue by seldomU** [google/blockly#2256]
I'd like to have a method ```workspace.registerType(typeName, typeNameMsgKey)``` to announce my custom types. The typed variable category would then generate a "Create variable of type X" button for each registered type.

**Motivation**
Since the variable category lives in blockly core, I can't add create-buttons to it. If I understand the docs correctly, it's suggested to put create-buttons for my variable types in other categories, but I'd prefer to have all things variables in one place. In a scenario where the user is allowed to add extension-categories to her toolbox, the problem is amplified: if two extensions add the same type, they would both have to include a create-button for it.

With type-registration, the variable flyout would get populated from registered types. Something like this:

```javascript
Blockly.VariablesDynamic.flyoutCategory = function(workspace) {
  
  var xmlList = [];

  for(let variableType of workspace.getVariableTypes()){

    // variableTypes would look something like this by default
    // [
    //   { name: 'String', msgKey: TYPENAME_STRING},
    //   { name: 'Number', msgKey: TYPENAME_NUMBER},
    //   { name: 'Colour', msgKey: TYPENAME_COLOUR},
    //   { name: 'Bool', msgKey: TYPENAME_BOOL}
    // ];
    
    let callbackKey = 'CREATE_VARIABLE_' + variableType.name;
    let buttonLabel = Blockly.Msg.NEW_VARIABLE_OF_TYPE + " " + Blockly.Msg[variableType.msgKey];
    
    // add a button for this type
    var button = goog.dom.createDom('button');
    button.setAttribute('text', buttonLabel);
    button.setAttribute('callbackKey', callbackKey);
    xmlList.push(button);

    // register a callback for this type's button
    workspace.registerButtonCallback(callbackKey, (button) => {
        Blockly.Variables.createVariableButtonHandler(button.getTargetWorkspace(), null, variableType.name)
      } 
    );
  }

  var blockList = Blockly.VariablesDynamic.flyoutCategoryBlocks(workspace);
  xmlList = xmlList.concat(blockList);
  return xmlList;
};
```

Does that make sense?

**Comment by RoboErikG** [comment]
The recommendation is actually to replace the variables flyout with a custom one. This doesn't require modifying core as there are APIs for [adding your own dynamic flyouts](https://developers.google.com/blockly/guides/configure/web/toolbox#dynamic_categories).

**Comment by RoboErikG** [comment]
One more note: #1606 is what we think should actually be used for more than 3 variable types.
