### ISSUE TITLE
Add separate block shape curves for connectors

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#2258]
Currently, the same curve is used for both the block and the connector.  However, since one is suppose to wrap around the other, the "radii" should differ.

When using the offset bevel, this was less of an issue. However, with the introduction of the modern styling and high contrast color support, the misalignment is more prominent.

<img width="754" alt="screen shot 2019-02-05 at 9 40 22 am" src="https://user-images.githubusercontent.com/9916202/52294810-19872600-292f-11e9-8526-8b45858b7b9e.png">

<img width="743" alt="screen shot 2019-02-05 at 10 19 36 am" src="https://user-images.githubusercontent.com/9916202/52295172-f9a43200-292f-11e9-8099-2de40ea0ef01.png">

**Solution**
For value inputs, the connector should be larger, starting closer to the top and extend slightly further down. The top and bottom "lock" bumps around the jigsaw tab should be a tighter curves.

For next and statement inputs, the connector indent should be smaller than then block's top bump. Additionally, the curve should start further from the start edge (both LTR and RTL).

**Comment by samelhusseini** [comment]
This has been fixed with the re-design of the renderer. Tested with thrasos.
