### ISSUE TITLE
Adding a block comment should fire workspace change event

### ISSUE THREAD

**Issue by bkisdi** [google/blockly#226]
Shouldn't it?
Now I can't detect change (and enable my save button) if the user changes a block comment only.

At the end of Blockly.BlockSvg.prototype.setCommentText (or Blockly.Block.prototype.setCommentText?) add something like

if (changedState)
  this.workspace.fireChangeEvent();

Review the comment for Blockly.WorkspaceSvg.prototype.fireChangeEvent.

Be sure not to fire during Blockly.Xml.domToWorkspace.

**Comment by HALtheWise** [comment]
This will probably be fixed when <a href="https://docs.google.com/document/d/1KyF6X7yrc3phPqLGzpPdngLMMzZ0jvXOFK5W43IAwbY/edit">Blockly 2016</a> gets pushed, as it includes a rewrite of the event generation functions and the proposal indicates that comment changes will be included.

**Comment by NeilFraser** [comment]
Correct.  This is *very* fixed in the 2016 branch.  Hoping to push this to master in a few days.
