### ISSUE TITLE
Q: Should delete heal value input children with parent?

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#2261]
### Problem statement

Delete behavior (`block.dispose(/*healStack*/ true);`) currently also heals value inputs, if their singular value input has a output type compatible with the parent. This is convenient for simple transformations like logical and mathematical negation.

![screen shot 2019-02-05 at 2 21 43 pm](https://user-images.githubusercontent.com/9916202/52308260-b6f35180-2951-11e9-9640-5d6b1cedcad9.png)

![screen shot 2019-02-05 at 2 25 50 pm](https://user-images.githubusercontent.com/9916202/52308365-03d72800-2952-11e9-950f-c8b437208a94.png)

However, this can be surprising for other blocks. Are absolute value, length of a string, or wrapping in a list of one (all single value input blocks) simple enough blocks to apply this sort of healing behavior?  And why do we expect the end user to infer the behavior change based on the count of inputs?

![screen shot 2019-02-05 at 2 19 44 pm](https://user-images.githubusercontent.com/9916202/52308601-9d9ed500-2952-11e9-9e76-2ac3abd1921e.png)

### Steps to Reproduce

1. Create a chain of value output blocks with one of the above block types. The output of the third should be compatible with the input of the first.
2. Select the second block.
3. Hit delete or backspace to delete the selected block. Note the block that was third, is now connected to the first.

#### In general, should value inputs heal?

![screen shot 2019-02-05 at 1 27 49 pm](https://user-images.githubusercontent.com/9916202/52305566-409f2100-294a-11e9-8a2e-bb761943a2b9.png)
Is the current behavior correct. Personally, it feels surprising.

#### If not, what should the general case be?
This?
![screen shot 2019-02-05 at 1 28 14 pm](https://user-images.githubusercontent.com/9916202/52305574-48f75c00-294a-11e9-847a-53abf6d8d4f5.png)

This might seem reasonable in a few cases, but I don't think it ever makes sense with more than one input connected. And it forces keyboard deletes to occur one block at time (mouse deletion is a drag behavior, the entire stack/chain is always deleted, and visibly so). Additionally, we probably shouldn't change behavior based on the number of inputs of the deleted block (thought people haven't complained before).

Alternatively, delete entire branch. This is equivalent to
```javascript
block.dispose(/*don't heal*/false, /* do anim*/true);
```
and to the delete behavior when dragging.

#### Should we make exceptions?

For example, `logic_negate` and maybe `math_single` (home of the mathematical negation)?

#### Can we change the behavior of the `healStack` option in `block.dispose(..)`?

Doing so is an API change, though this would align it with the declared documentation. Otherwise we need another method or option to distinguish between healStack (next/prev) and heal any singular connection chain.

`dispose()` probably should have had an options object, rather than multiple boolean parameters. Now may be a chance to step toward that.

**Comment by cpcallen** [comment]
This is an interesting question, but the existing behaviour seems to never be worse than the alternative, and in many cases will be helpful, so we will continue to answer the title question with "yes" until we see a compelling reason not to.
