### ISSUE TITLE
Complete adding Hausa language (ha)

### ISSUE THREAD

**Issue by mapmeld** [google/blockly#2264]
Hausa is now a file in the develop branch's ```msg/json``` directory, but ```json_to_js.py``` hasn't yet been run to convert JSON -> JS.

Translations file in develop branch: https://github.com/google/blockly/blob/develop/msg/json/ha.json

Demo: http://mapmeld.com/blockly/demos/toolbox/index.html?lang=ha

Blockly Games: https://mapmeld.com/blockly-games/appengine/maze.html

**Comment by rachel-fenichel** [comment]
This will happen as part of the next release.

Blockly Games is in a separate repo; you may want to file an issue there as well.

**Comment by mapmeld** [comment]
Thanks!
