### ISSUE TITLE
Block input box sticks on the screen when scrolled/navigated away while focused.

### ISSUE THREAD

**Issue by ljitendra** [google/blockly#2267]
### Problem statement

Bug: Block input box sticks on the screen when scrolled/navigated away while focused.

### Expected Behavior

When user scrolls the screen or navigates away from the page containing the blockly editor, input html element should be deleted from DOM

### Actual Behavior

Input box sticks to the screen.

### Steps to Reproduce

1. Include blockly editor as part of a form page such that you get scrollbar on the page.
2. Insert a block with input box.
3. Focus on input box to enter some text
4. While focused, scroll the page or navigate away from that page using link.

### Operating System and Browser
Test on latest chrome and firefox browser

### Additional Information

The reason the input box sticks to the page because the div is attached to the body adjacent to the application div.
Including a screenshot to better understand the problem.
Potential solution to this would be clear `<div class="blocklyWidgetDiv" ... >` innerHTML on `blur` and `scroll` event to remove the input box from DOM.

**Comment by ljitendra** [comment]
![image](https://user-images.githubusercontent.com/15458935/52366902-d1443280-2a18-11e9-9e13-1d22e77177ed.png)

**Comment by rachel-fenichel** [comment]
It sounds like there's a missing call to `hideChaff`.

**Comment by samelhusseini** [comment]
Fixed by #2286
