### ISSUE TITLE
Clarification on Python version

### ISSUE THREAD

**Issue by Immortalin** [google/blockly#227]
Hi, what is the version of python blockly officially supports? I have found [references](https://code.google.com/p/blockly/issues/detail?id=75) of Python 3 support but I cannot find any other information on this.

**Comment by NeilFraser** [comment]
Thanks for raising this issue.  Generated code supports Python 2.6 to 3.5.  I just checked in some small changes to the 2016 branch that fixes some Python 3 math operations.

**Comment by edmorley** [comment]
Does this mean the Python 2 check in the build script can be removed too? :-)
https://github.com/google/blockly/blob/a77788deb4644be3e11c4f1c68a268b341dbad38/build.py#L38-L41

**Comment by carlosperate** [comment]
The Python compatibility mentioned by Neil was with respect to the generated code from the Python generator, not the Python version required to build Blockly.
