### ISSUE TITLE
Disable Next Blocks in Toolbox

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2273]
### Problem statement

Toolbox does not disable the next block when the top block is disabled (statement blocks are disabled, as you would expect).

### Expected Behavior

If the top block is disabled (for instance because maxBlocks is reached) the next blocks should also be disabled.

### Actual Behavior

Only the top block is disabled (and statements/inputs):
![disablingblocks](https://user-images.githubusercontent.com/25440652/52447126-ba6b1200-2ae4-11e9-8b4e-2703175e3889.jpg)

### Steps to Reproduce

1. Set the maxBlocks on the playground to 1.
2. Navigate to Test Blocks > Drag. Observe how the Multiple Variable Refs block only has the top block disabled.

### Stack Traces

N/A

### Operating System and Browser

I assume this is not browser specific.

### Additional Information

[filterForCapacity_()](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/core/flyout_base.js#L727) in flyout_base.js should deep-disable blocks.

**Comment by rachel-fenichel** [comment]
Fixed by #2278
