### ISSUE TITLE
Horizontal Flyout Scrolls on Resize

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2275]
### Problem statement

The flyout scrolls when you resize the window.

### Expected Behavior

The flyout should stay pinned to the right side (start side in RTL).

### Actual Behavior

Top Flyout RTL:
![scrollingwindowresize_top_rtl](https://user-images.githubusercontent.com/25440652/52449334-c1495300-2aeb-11e9-9358-dbdb853b4262.gif)
Bottom Flyout RTL:
![scrollingwindowresize_bottom_rtl](https://user-images.githubusercontent.com/25440652/52449337-c4dcda00-2aeb-11e9-9d6f-6aab9bbb8728.gif)

Working correctly in LTR for reference:
Edit: This is only true if the flyout is not scrolled.
![scrollingwindowresize_top_ltr](https://user-images.githubusercontent.com/25440652/52449344-cc9c7e80-2aeb-11e9-869d-71c33f7b37b6.gif)

### Steps to Reproduce

1. Open the multiplayground with simple toolboxes.
2. Scroll LTR flyouts so the scrollbars are on the right.
2. Resize the window. Observe how the horizontal flyouts scroll.

### Stack Traces

N/A

### Operating System and Browser

I am assuming this is not browser specific.

### Additional Information

Probably related to #2274

**Comment by BeksOmega** [comment]
Update: This does occure in LTR if the flyout has been scrolled.

Top LTR:
![scrollingwindowresize_top_ltr_bad](https://user-images.githubusercontent.com/25440652/52523761-9248f380-2c49-11e9-9d1f-6d0c0ab46487.gif)

Bottom LTR:
![scrollingwindowresize_bottom_ltr_bad](https://user-images.githubusercontent.com/25440652/52523767-a260d300-2c49-11e9-93a8-98193a66c1bd.gif)

**Comment by BeksOmega** [comment]
Update: Turns out it isn't related to #2274.

**Comment by samelhusseini** [comment]
Fixed by #2282
