### ISSUE TITLE
Q: Should the absoluteLeft and absoluteTop Metrics be Shifted to Avoid Simple Toolboxes?

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2280]
### Problem statement

Simple toolboxes do not act the same as normal toolboxes with respect to metrics, but it seems like they should.

### Expected Behavior

Blocks shouldn't be created behind the toolbox: (the best example is in RTL)
![importingblocks_categories_rtl](https://user-images.githubusercontent.com/25440652/52524365-05099d00-2c51-11e9-9f6e-c9414c0b3e84.gif)

Scrollbars should only scroll the accessible region:
![accessibleregion_categories](https://user-images.githubusercontent.com/25440652/52524412-9bd65980-2c51-11e9-9d2e-c9d9668dcd0d.gif)

### Actual Behavior

Blocks are created behind the toolbox: (the best example is in RTL)
![importingblocks_simple_rtl](https://user-images.githubusercontent.com/25440652/52524370-0dfa6e80-2c51-11e9-80d1-76b1725de3d9.gif)

Scrollbars scroll blocks behind the toolbox:
![accessibleregion_simple](https://user-images.githubusercontent.com/25440652/52524414-a0027700-2c51-11e9-8b9e-236304472128.gif)

I've also seen not a small amount of code scattered about specifically for getting flyouts to work correctly.

For example, [this](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/core/inject.js#L328) which fixes the block creation in LTR, but not in RTL (as evidenced above):
![importingblocks_categories_ltr](https://user-images.githubusercontent.com/25440652/52524377-266a8900-2c51-11e9-8b18-188c133b9f20.gif)
![importingblocks_simple_ltr](https://user-images.githubusercontent.com/25440652/52524379-29fe1000-2c51-11e9-864b-6348a247a504.gif)

See also: [Bubble Adjustment](https://github.com/google/blockly/pull/2279/files), [scrollCenter Adjustment](https://github.com/google/blockly/pull/2247/files#diff-d66993062276fda309492ac385508aeaR1759), [zoomControls Positioning](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/core/zoom_controls.js#L134), [Trashcan Positioning](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/core/trashcan.js#L242), etc.

### Proposal

Adjust the absoluteLeft and absoluteTop metrics, to avoid the simple toolboxes, this would make the categories and the simple toolboxes work exactly the same. Then go back and fix all of the math.

I have created a small example of this that works for vertical toolboxes. You can see my code changes [here](https://github.com/BeksOmega/blockly/commit/4131562f5f96740a001b5ec17c8e013020746294).  You can also see a video of the example [here](https://youtu.be/dscKOJTOInA).

**Comment by rachel-fenichel** [comment]
A: Yes, that sounds like a good idea.
