### ISSUE TITLE
Change WorkspaceSvg.scroll to Not Access Internal .ratio_ Property of Scrollbar

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2299]
### Problem statement

The WorkspaceSvg scroll function currently uses the private .ratio_ property when calling [setHandlePosition](https://github.com/google/blockly/blob/82871b3d24563388a6f113da8984694e9f37b53e/core/scrollbar.js#L373).

It should probably call a function like [scrollbar.set()](https://github.com/google/blockly/blob/82871b3d24563388a6f113da8984694e9f37b53e/core/scrollbar.js#L849) instead of [setHandlePosition](https://github.com/google/blockly/blob/82871b3d24563388a6f113da8984694e9f37b53e/core/scrollbar.js#L373), but doing that causes the workspace to jitter when scrolling after a zoom:

![scrollbarsset](https://user-images.githubusercontent.com/25440652/52823673-a8501d00-306a-11e9-8b74-c2789fe9a611.gif)

### Next Steps

These calls need to be sorted out so that .ratio_ stays internal.

**Comment by gonfunko** [comment]
WorkspaceSvg no longer has any references to ratio_.
