### ISSUE TITLE
[IE11] Cannot editor Comment

### ISSUE THREAD

**Issue by pelikhan** [google/blockly#230]
In IE11, it is possible to add a comment to a block -- using "Add Comment" -- but it is not possible to edit the text in the comment.

![image](https://cloud.githubusercontent.com/assets/4175913/12094387/2dbefb52-b2bd-11e5-960b-efba31063119.png)

**Comment by NeilFraser** [comment]
No version of IE (9, 10, 11) supports the foreignobject element:
http://msdn.microsoft.com/en-us/library/hh834675%28v=vs.85%29.aspx
That means we can't embed HTML text areas in comment bubbles for IE.

Given that comments are rarely used (in three years I've never seen anyone intentionally use them), we simply make comments in IE be read-only.  The alternative is some sort of heroic undertaking to layer multiple divs that float on top of Blockly, constantly synchronizing their locations and z-indices.  But I think Blockly would be better served if that effort went to other priorities with higher impact.

**Comment by NeilFraser** [comment]
Since this issue is not going to go away until Microsoft fixes IE (probably not this decade), I've simply disabled the menu option to create a comment when the user is running IE.  Leaving this bug open as it gets reported from time to time.

**Comment by pelikhan** [comment]
Thanks for the quick turn-around!

**Comment by rachel-fenichel** [comment]
Note for workspace comments: we need to also disable the "add comment" option on the workspace context menu in internet explorer.

@kchadha @samelhusseini

**Comment by rachel-fenichel** [comment]
I'm closing this bug, since we've decided to not even try to support this.  If it comes up again we'll refer people over to here for the explanation.
