### ISSUE TITLE
involuntary hatless mode

### ISSUE THREAD

**Issue by seldomU** [google/blockly#2302]
Setting Blockly.BlockSvg.START_HAT to true doesn't do anything since the February release. This assignment seems to go wrong: https://github.com/google/blockly/blob/82871b3d24563388a6f113da8984694e9f37b53e/core/block_render_svg.js#L570

**Comment by jollytoad** [comment]
`typeof this.hat !== undefined` is invalid, should either be...
`typeof this.hat !== 'undefined'` or why not just `this.hat` (is truthy), eg:

`this.hat ? this.hat === 'cap' : Blockly.BlockSvg.START_HAT`
