### ISSUE TITLE
Scroll Event Bound in inject.js Doesn't Work for Multiple Workspaces

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2310]
### Problem statement

The on document scroll -> updateInverseScreenCTM event is only bound to the first injected workspace because of the Blockly.documentEventsBound_ check. ([link](https://github.com/google/blockly/blob/d7e47c66b2ceb2aacfbb97bae42a1da093463dad/core/inject.js#L444))

This causes zooming with wheel to be off (for any secondary workspaces) after the page is scrolled.

### Expected Behavior

Every workspace should have updateInverseScreenCTM called on it when the document is scrolled.

### Actual Behavior

Only the workspace that is injected first has updateInverseScreenCTM called on it.

### Steps to Reproduce

1. Add the below code at ~ln 399 in [updateInverseScrenCTM](https://github.com/google/blockly/blob/d7e47c66b2ceb2aacfbb97bae42a1da093463dad/core/workspace_svg.js#L398) in workspace_svg.js:
`console.log(this.id);`
2. Open the multiplayground.
3. Scroll the document. Observe how only 1 id is being logged, i.e. only one workspace is having the function called on it.

### Stack Traces

N/A

### Operating System and Browser

I am assuming this is not browse specific.

### Additional Information

N/A

**Comment by BeksOmega** [comment]
Actually this may not need to be an event binding, we may just need to call [updateScreenCalculationsIfScrolled_](https://github.com/google/blockly/blob/d7e47c66b2ceb2aacfbb97bae42a1da093463dad/core/workspace_svg.js#L769) in [onMouseWheel_](https://github.com/google/blockly/blob/d7e47c66b2ceb2aacfbb97bae42a1da093463dad/core/workspace_svg.js#L1306).

**Comment by rachel-fenichel** [comment]
Good catch.  There's a workspaceDB object on Blockly that has all of the known workspaces; you can call updateInverseScreenCTM on each one, after confirming that the function exists (workspace_svg has it, but workspace doesn't).

**Comment by BeksOmega** [comment]
> Good catch. There's a workspaceDB object on Blockly that has all of the known workspaces; you can call updateInverseScreenCTM on each one, after confirming that the function exists (workspace_svg has it, but workspace doesn't).

I gave it a shot, but it seems like the WorkspaceDB_ object [only stores workspace's](https://github.com/google/blockly/blob/82871b3d24563388a6f113da8984694e9f37b53e/core/workspace.js#L43) and not workspace_svg's?

This code always returns undefined:

```
 Blockly.bindEventWithChecks_(document, 'scroll', null, function() {
      for (var workspace in Blockly.Workspace.WorkspaceDB_) {
        console.log(workspace.updateInverseScreenCTM);
      }
    });
```

I can make workspace_svg overwrite the database if this is the route you want to go.

**Comment by rachel-fenichel** [comment]
It contains both types of workspaces.  WorkspaceSvgs extend Workspace and call that constructor as well.  If you open up the [multi_playground](https://blockly-demo.appspot.com/static/tests/multi_playground.html) and type `Object.keys(Blockly.Workspace.WorkspaceDB_).length` in the console, you'll see that it has 24 elements: (one trash workspace, one flyout workspace, and one main workspace) * (8 blockly instances on the page).

Your code didn't work because you have to get items in the DB by key (it's just an object).  Change it to this:
```
 Blockly.bindEventWithChecks_(document, 'scroll', null, function() {
      for (var key in Blockly.Workspace.WorkspaceDB_) {
        var workspace = Blockly.Workspace.WorkspaceDB_[key];
        console.log(workspace.updateInverseScreenCTM);
      }
    });
```
