### ISSUE TITLE
Context Menus not Receiving Clicks

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2312]
### Problem statement

You know that [pull request](https://github.com/google/blockly/pull/2286) where I added code to receive document clicks? Turns out it breaks all context menus.

### Expected Behavior

Context menus should recieve clicks and call their callbacks.

### Actual Behavior

They don't.

### Steps to Reproduce

1. Add a block to the workspace.
2. Right click it.
3. Click the "add comment" option. Observe how the context menu disapears, and no comment box appears.

Or if you want to be more thorough:
1. Add the below code at ~ln 129 in playground:
```
workspace.configureContextMenu = function(options) {
    options.push({
      enabled: true,
      text: 'Test',
      callback: function() {
        console.trace('callback');
      }
    })
  }
```
2. Open the playground.
3. Right click on the workspace.
4. Click the "Test" option. Observe how the context menu disapears and no trace was logged to the console.

### Stack Traces

I added a console.trace() call to the document mouse down subscriber:

```
(anonymous) | @ | inject.js:441
-- | -- | --
  | wrapFunc  | @ | blockly.js:492
```

Then I disabled that subscriber and grabbed the trace from the above custom option.
```
callback | @ | playground.html:134
-- | -- | --
  | goog.events.EventTarget.fireListeners | @ | eventtarget.js:285
  | goog.events.EventTarget.dispatchEventInternal_ | @ | eventtarget.js:383
  | goog.events.EventTarget.dispatchEvent | @ | eventtarget.js:196
  | goog.ui.Control.performActionInternal | @ | control.js:1378
  | goog.ui.Control.handleMouseUp | @ | control.js:1321
  | childCtor.base | @ | base.js:2123
  | goog.ui.MenuItem.handleMouseUp | @ | menuitem.js:258
  | goog.ui.Container.handleChildMouseEvents | @ | container.js:672
  | goog.events.fireListener | @ | events.js:753
  | goog.events.handleBrowserEvent_ | @ | events.js:879
  | f | @ | events.js:296
```
### Operating System and Browser

I am assuming this is not browser specific.

### Additional Information

I was just going to fix this, and then I realized I didn't know how. I'm still willing to help if I can!

**Comment by BeksOmega** [comment]
Also breaks [field_dropdown.js](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/core/field_dropdown.js#L36) (as discovered by @cshung) and [field_variable.js](https://github.com/google/blockly/blob/09853c37250528b65a87f6e0bb73432b57f86108/core/field_variable.js#L335) because they also use the closure menus.

**Comment by rachel-fenichel** [comment]
Hey Beka,

The problem is probably related to the call to stopPropagation.  Remember that article about event propagation and bubbling?  If you stop the click as soon as you handle it, the other listeners on the field (like the context menu and dropdown listeners) don't get a chance to respond.  I think ther'es an option to override stopPropagation in bindEventWithChecks_.  Do you want to take a look?

**Comment by BeksOmega** [comment]
Can do!

**Comment by BeksOmega** [comment]
Ok I took another look at it:

I found out that the Blockly.hideChaff() call is actually the problem. This kills the menu before it has a chance to recieve the click. You can test this by commenting out the call [here](https://github.com/google/blockly/blob/4bf99436742e523ebe63c2f4e762fa523299de3f/core/inject.js#L424). Observe how the menu is not deleted and works correctly.

The odd thing about this is that from [my understanding](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Event_bubbling_and_capture), the goog.ui.Menu should get the event first, since it is the inner-most div:

![EventStructure](https://user-images.githubusercontent.com/25440652/54065229-b2c98680-41d2-11e9-9e6d-8ade90658499.png)


None of the events should be triggering on capture, because bindEventWIthChecks_ [explicitly says](https://github.com/google/blockly/blob/4bf99436742e523ebe63c2f4e762fa523299de3f/core/blockly.js#L502) to trigger it on bubbling. But if we attach listeners to all of the objects, we see it happens (intriguing/annoying-ly) in capture order:

1) Document
2) Widget Div
3) Menu

Getting the menu to recieve the click first should fix this, but since I don't know why it's triggering in capture order rather than bubbling order I'm stuck again.

Also: for completeness I tested all of the bindEventWithChecks_ optional parameter combinations, and they didn't seem to help.
