### ISSUE TITLE
Insertion Markers confusing fields during copy

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2314]
### Problem statement

The insertion markers are copying fields and assigning their value by name, but if you have multiple unnamed fields this just keeps setting the value on the first field. Normally this isn't a problem, but if the first field is a field_image then there's an error when it tries to get a random string as an image. It should be copying the values by location in the array instead.

The problem is this function:
https://github.com/google/blockly/blob/master/core/insertion_marker_manager.js#L279

### Expected Behavior

No errors in console

### Actual Behavior

Errors in console

### Steps to Reproduce

1. Create this block:
Blockly.Blocks['custom_block'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldImage("https://www.gstatic.com/codesite/ph/images/star_on.gif", 15, 15, "*"))
        .appendField("My block")
    this.setPreviousStatement(true);
    this.setNextStatement(true);
  }
};
2. Next, load it in the workspace
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="custom_block" x="138" y="87">
  </block>
</xml>

3. Drag the block and check the console

### Stack Traces

GET https://blockly-demo.appspot.com/static/tests/My%20block 404
  | Blockly.FieldImage.setValue | @ | field_image.js:185
  | Blockly.FieldImage.init | @ | field_image.js:113
  | Blockly.Input.init | @ | input.js:235
  | Blockly.BlockSvg.initSvg | @ | block_svg.js:161
  | Blockly.InsertionMarkerManager.createMarkerBlock_ | @ | insertion_marker_manager.js:283
  | Blockly.InsertionMarkerManager | @ | insertion_marker_manager.js:86
  | Blockly.BlockDragger | @ | block_dragger.js:63
  | Blockly.Gesture.startDraggingBlock_ | @ | gesture.js:453
  | Blockly.Gesture.updateIsDraggingBlock_ | @ | gesture.js:391
  | Blockly.Gesture.updateIsDragging_ | @ | gesture.js:441
  | Blockly.Gesture.updateFromEvent_ | @ | gesture.js:287
  | Blockly.Gesture.handleMove | @ | gesture.js:542
  | Blockly.TouchGesture.handleMove | @ | touch_gesture.js:181
  | wrapFunc | @ | blockly.js:492

```
Replace with error stack trace.
```

**Comment by maribethb** [comment]
should be closed due to #2556 being closed and these having the same underlying cause
