### ISSUE TITLE
Disabling orphan break blocks breaks undo

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2321]
### Problem statement

When a break block is auto-disabled because it's not in a loop it breaks undo. This is probably because the disable event isn't getting properly grouped with the events that triggered it (you have to manually add the event group when things are triggered by an event).

Side note: We should consider setting the event group while events are firing so that any new events are automatically grouped with the firing event.

### Expected Behavior

Can drag out an orphaned break block and then undo it.

### Actual Behavior

Undo gets stuck at the point where the block was disabled.

### Steps to Reproduce

1. Drag out a break block.
2. Try to undo it.

### Stack Traces

```
Replace with error stack trace.
```

**Comment by RoboErikG** [comment]
Note: Orphan blocks being disabled in DevTools is also breaking undo, but that might be a different issue.

**Comment by pantoninho** [comment]
I'm also experiencing this issue.

**Comment by zenboss** [comment]
I'm suffering from this issue.

**Comment by samelhusseini** [comment]
Fixed by #3697
