### ISSUE TITLE
Documentation: Category XML Attributes

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2333]
### Problem statement

The [toolbox > categories](https://developers.google.com/blockly/guides/configure/web/toolbox#categories) documentation is missing some info about attributes you can add to the category tags, namely:

- expanded
- categoryStyle

(at least these are the only two I know of, I only found expanded accidentally)

### Additional Information

The [Themes ](https://developers.google.com/blockly/guides/configure/web/themes#add_style_names)documentation should probably also be updated to reflect #2325

**Comment by alschmiedt** [comment]
I think I added these last release and never closed the ticket. 
expanded: https://developers.google.com/blockly/guides/configure/web/toolbox#expanded 
categorystyle: https://developers.google.com/blockly/guides/configure/web/toolbox#themes
