### ISSUE TITLE
Dropdown sizing issues (width and height)

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2337]
### Problem statement

Dropdowns look weird on develop, in a variety of ways.

In chrome on the playground in LTR:
![image](https://user-images.githubusercontent.com/13686399/54950340-4f439680-4efe-11e9-8192-8cf9a8a1b855.png)

The dropdown has a scrollbar even though it's only two items tall.  Mousing over makes the scrollbar disappear.  The bottom border is also missing.

None of these issues appear on a similar dropdown:
![image](https://user-images.githubusercontent.com/13686399/54950398-6a160b00-4efe-11e9-9fc3-b1574d2c2efa.png)

In RTL the checkmark is on the left instead of the right, the dropdown is way too big, and there's a scrollbar:
![image](https://user-images.githubusercontent.com/13686399/54950458-8ca82400-4efe-11e9-9343-cce17f44a2a4.png)

Mousing over also makes the scrollbar disappear here.

The scrollbar problem doesn't show up on Firefox, but the checkmark placement problem does.

### Additional Information

Dropdowns occasionally have scrollbars when they shouldn't on master right now, but it's nowhere near this bad.

### Operating System and Browser

* Desktop Chrome
* Desktop Firefox

**Comment by RoboErikG** [comment]
Note, the scrollbar issue is no longer reproducible but the checkbox and width issues in RTL are still there.

**Comment by RoboErikG** [comment]
Can be closed once #2356 is merged.
