### ISSUE TITLE
Document that statementToCode Should Only be Used Inside Generators (mostly)

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2339]
### Problem statement

I've seen a few people having the same issue as [this ](https://groups.google.com/forum/#!topic/blockly/mqN-YaK0oAw)gentleperson where they believe statementToCode should be used for generating workspace code.

### Expected Behavior

The documentation should probably have a caveat that most people shouldn't use statementToCode outside of a generator, and should instead use blockToCode or workspaceToCode.

### Actual Behavior

At the moment the documentation reads like this:

> Generate code representing the statement. Indent the code.

### Additional Information

N/A

**Comment by AnmAtAnm** [comment]
I think the issue in the linked comment is a confusion between a single "statement" and a single "statement input", the latter containing a stack of statements.

**Comment by BeksOmega** [comment]
> I think the issue in the linked comment is a confusion between a single "statement" and a single "statement input", the latter containing a stack of statements.

I'll look tomorrow to see if I can find an example that _is actually_ confusion about the above issue. If I can't find anything I'll close this.

**Comment by AnmAtAnm** [comment]
Given that the method is on the Generator object, I feel pretty confident most developers will only attempt to use it in a generator context.

The real issue in the initial message of that thread was the common confusion between generation time and runtime variables & state.

**Comment by BeksOmega** [comment]
These were the two other posts I was thinking of:

https://groups.google.com/forum/#!searchin/blockly/statementToCode|sort:date/blockly/BKiRK57a_VQ/vx_W7JeLHQAJ

https://groups.google.com/forum/#!searchin/blockly/statementToCode|sort:date/blockly/m5iiGKr4IpY/6oKrbeA2BQAJ
