### ISSUE TITLE
Can't click "Done" on android phone keyboard

### ISSUE THREAD

**Issue by dieudv** [google/blockly#2340]
"Done" button no function on all text input on the android phone. Only click back to close keyboard.

Some devices I tested:
- Samsung J500H
- Samsung galaxy note 3
- Xiaomi redmi note 3

![device20190327082005](https://user-images.githubusercontent.com/12602709/55043816-7cad5300-506a-11e9-8fb5-963cbf1dae4e.gif)

**Comment by RoboErikG** [comment]
This looks like a bug in Samsung/Xiaomi's keyboard. I can't reproduce with the default Google IME on a Pixel.

Does this happen on other website dialogs as well or just Blockly's?

**Comment by dieudv** [comment]
Other website are fine, but i can't find any case with button "Done" same as Blockly, It's usually "Go" or "Next"

**Comment by dieudv** [comment]
I found [this lines](https://github.com/google/blockly/blame/16a1a747e31b6eb28675f591cb9e6ae0a3e85a30/demos/mobile/android/app/src/main/java/com/google/blockly/android/webview/JsDialogHelper.java#L119-L130), i removed it and bug fixed. Please check!

**Comment by RoboErikG** [comment]
Yeah, that's not right. I suspect that's suppose to be for a specific API version of Android, but it's definitely causing problems with that TODO and not actually handling the event so removing it is reasonoable. https://github.com/google/blockly/pull/2634/files
