### ISSUE TITLE
Trashcan's flyout badly positioned on X axis

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2345]
Affects LTR and RTL.
![Screen Shot 2019-03-28 at 14 36 08](https://user-images.githubusercontent.com/250480/55194441-ec086d00-5166-11e9-9f9e-ebf4230ccfe1.png)

**Comment by BeksOmega** [comment]
On vacation, but I'll try to take a look.

**Comment by NeilFraser** [comment]
Thanks!
