### ISSUE TITLE
Transition to eslint-plugin-jsdoc

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2347]
Eslint is end-of-lifing jsdoc support but suggests switching to eslint-plugin-jsdoc going forward.

Here's the relevant post:
https://eslint.org/blog/2018/11/jsdoc-end-of-life

**Comment by kushthedude** [comment]
Hi @rachel-fenichel , Can I take up this issue ?

**Comment by rachel-fenichel** [comment]
@kushthedude Yes, go for it.

**Comment by maribethb** [comment]
All TypeScript code is now being linted with the jsdoc plugin. Technically, JS code is still being linted with the old `valid-jsdoc` rules, but we should migrate the rest of the js to ts, rather than updating our lint rules. So going to close this as completed.
