### ISSUE TITLE
Blockly math operators error

### ISSUE THREAD

**Issue by commander01S** [google/blockly#2348]
### Problem statement

There are some error with blockly math operators. Normally it is + - * / ^ ,but In my case it changed to + -  ิ  ๊  ^

### Expected Behavior

I should be able to use * / operators.
### Actual Behavior

It was   ิ   ๊  operator that do nothing.

### Operating System and Browser

Desktop Chrome on windows 10

**Comment by RoboErikG** [comment]
Can you provide more details?

- Does this reproduce on the [playground](https://blockly-demo.appspot.com/static/tests/playground.html) or only in your implementation?
- Are there errors in the console?

**Comment by NeilFraser** [comment]
Attaching screenshot sent via email.

![error blockly](https://user-images.githubusercontent.com/250480/55261824-29cdca00-5229-11e9-8f9d-54f6db33d143.png)

This is a very strange bug.  * and / are part of base ASCII, can't see why they'd end up somewhere in Unicode land.

**Comment by RoboErikG** [comment]
This also doesn't reproduce in the public version of that demo. I'm guessing there's something wrong in the local copy of the code, so any console logs or more details about setup would help.

![image](https://user-images.githubusercontent.com/11066279/55262282-95646700-522a-11e9-88bd-134d00e15668.png)

**Comment by commander01S** [comment]
> Can you provide more details?
> 
> * Does this reproduce on the [playground](https://blockly-demo.appspot.com/static/tests/playground.html) or only in your implementation?
> * Are there errors in the console?

Yep, I found error on playground too.

**Comment by commander01S** [comment]
> This also doesn't reproduce in the public version of that demo. I'm guessing there's something wrong in the local copy of the code, so any console logs or more details about setup would help.
> 
> ![image](https://user-images.githubusercontent.com/11066279/55262282-95646700-522a-11e9-88bd-134d00e15668.png)

I am using public version.
https://blockly-demo.appspot.com/static/demos/code/index.html

**Comment by AnmAtAnm** [comment]
I believe this is  a font issue for the Thai localization on Windows 10, based upon conversation in the forum.
