### ISSUE TITLE
Mouse clicks/drags are borked in Safari

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2362]
Open develop's playground in Safari (Version 12.1 (13607.1.40.1.5), OSX).  Try dragging blocks around and dragging the workspace.  Mouse-clicks are only recognized about 50% of the time.  The console fills up with "Tried to start the same gesture twice."

No problems with the playground on blockly-demo.

**Comment by alschmiedt** [comment]
Yeah this is most definitely because of this #2359 . Will take a look : )

**Comment by NeilFraser** [comment]
Appears to be resolved.
