### ISSUE TITLE
Dragging any collapsed block with a field breaks everything

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2363]
### Problem statement

If you collapse a math block (addition) and then try to drag it everything breaks forever.

### Steps to Reproduce

1. Drag out a + block
2. Right click -> collapse the block
3. Drag the block

### Stack Traces

`
block.js:1079 Uncaught Error: Field "undefined" not found.
    at Blockly.BlockSvg.Blockly.Block.setFieldValue (block.js:1079)
    at Blockly.InsertionMarkerManager.createMarkerBlock_ (insertion_marker_manager.js:279)
    at new Blockly.InsertionMarkerManager (insertion_marker_manager.js:86)
    at new Blockly.BlockDragger (block_dragger.js:63)
    at Blockly.TouchGesture.Blockly.Gesture.startDraggingBlock_ (gesture.js:453)
    at Blockly.TouchGesture.Blockly.Gesture.updateIsDraggingBlock_ (gesture.js:391)
    at Blockly.TouchGesture.Blockly.Gesture.updateIsDragging_ (gesture.js:441)
    at Blockly.TouchGesture.Blockly.Gesture.updateFromEvent_ (gesture.js:287)
    at Blockly.TouchGesture.Blockly.Gesture.handleMove (gesture.js:542)
    at Blockly.TouchGesture.handleMove (touch_gesture.js:181)
`

```
Replace with error stack trace.
```

**Comment by RoboErikG** [comment]
Note: This is already on master and no one else has noticed yet, so not critical to get it in to the April release. It should be fixed by the next release, though.

**Comment by NeilFraser** [comment]
Stumbled across this bug just now, it's bigger than just math blocks.  It affects any block with an editable field (colour, dropdown, number).

A weird exception is text fields.  Dragging a collapsed text field initiates a network call!
`GET file:///Users/fraser/Code/blockly/tests/%E2%80%9C%20%20%E2%80%9D net::ERR_FILE_NOT_FOUND`

**Comment by Yoshi20** [comment]
Here's my workaround that may help you fixing this bug:
```javascript
Blockly.InsertionMarkerManager.prototype.createMarkerBlock_ = function(sourceBlock) {
  var imType = sourceBlock.type;

  Blockly.Events.disable();
  try {
    var result = this.workspace_.newBlock(imType);
    result.setInsertionMarker(true, sourceBlock.width);
    if (sourceBlock.mutationToDom) {
      var oldMutationDom = sourceBlock.mutationToDom();
      if (oldMutationDom) {
        result.domToMutation(oldMutationDom);
      }
    }
    // Copy field values from the other block.  These values may impact the
    // rendered size of the insertion marker.  Note that we do not care about
    // child blocks here.
    for (var i = 0; i < sourceBlock.inputList.length; i++) {
      var input = sourceBlock.inputList[i];
      for (var j = 0; j < input.fieldRow.length; j++) {
        var field = input.fieldRow[j];
        if (field.name != null) { // <-- WORKAROUND: dragging collapsed bug
          result.setFieldValue(field.getValue(), field.name);
        }
      }
    }

    result.initSvg();
    result.getSvgRoot().setAttribute('visibility', 'hidden');
  } finally {
    Blockly.Events.enable();
  }

  return result;
};
```

**Comment by xAtomic** [comment]
The problem is that an additional input with a field is added during collapsed mode. As the "result" gets created from the "imType", the additional input is not present on the result. I fixed it by adding `result.setCollapsed` like this:
```javascript
 var result = this.workspace_.newBlock(imType);
 result.setCollapsed(sourceBlock.isCollapsed()); //<-- bugfix
 result.setInsertionMarker(true, sourceBlock.width);
```

This seems to fix the problem without further issues.

_Note: the problem is not encountered on the "if" block, because it has an unnamed field in the first input and the field added in the collapse input is also unnamed so the "getField" returns the (wrong) field of the first input and therefore doesn't throw._
