### ISSUE TITLE
Insertion Markers Show Incorrect Preview For Inputs

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#2370]
### Problem statement
Insertion markers do not always display correctly when attaching inputs. This can cause confusion because it does not accurately display where the block will end up when attached.

### Expected Behavior
In the case below we would expect that the insertion marker accurately displayed the text input being connected to the second toUpperCase block.
![Screen Shot 2019-04-08 at 2 33 30 PM](https://user-images.githubusercontent.com/23059043/55759022-40380a80-5a0d-11e9-98c9-5911872a1207.png)

### Actual Behavior
Currently the insertion marker displays the text being added to the end of the first block instead of showing it adding the last block in the chain.
![Screen Shot 2019-04-08 at 2 33 21 PM](https://user-images.githubusercontent.com/23059043/55759071-6198f680-5a0d-11e9-950c-c816c681978e.png)

### Steps to Reproduce
1. Import xml (found in comments) to playground
2. Try to connect the toUpperCase block to the first input on create text with
 
### Stack Traces

```
Replace with error stack trace.
```

### Additional Information
When we fix this we will probably need to change how we fixed this bug (#2336 ). The current fix (#2355 )only works if we make the assumption that only the displaced block is attached to the shadow block.

!-- Anything else we should know? -->

**Comment by alschmiedt** [comment]
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="text_join" id="tcOGICm`[?#eUYB;aR!|" x="113" y="138">
    <mutation items="2"></mutation>
    <value name="ADD0">
      <block type="text" id=")-Oa1JR[/5ufpnseT|aV">
        <field name="TEXT"></field>
      </block>
    </value>
  </block>
  <block type="text_changeCase" id="e(!zBhw,a-3[h`+)OdQK" x="288" y="212">
    <field name="CASE">UPPERCASE</field>
    <value name="TEXT">
      <shadow type="text" id="U]_l*1}8CssB8:dbTvfh">
        <field name="TEXT">abc</field>
      </shadow>
      <block type="text_changeCase" id="$IihoCVT8)@@,d3EsGD@">
        <field name="CASE">UPPERCASE</field>
        <value name="TEXT">
          <shadow type="text" id="D=44+LkP658bAA_3#qsA">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
    </value>
  </block>
</xml>

**Comment by alschmiedt** [comment]
`<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="text_join" id="tcOGICm`[?#eUYB;aR!|" x="113" y="138">
    <mutation items="2"></mutation>
    <value name="ADD0">
      <block type="text" id=")-Oa1JR[/5ufpnseT|aV">
        <field name="TEXT"></field>
      </block>
    </value>
  </block>
  <block type="text_changeCase" id="e(!zBhw,a-3[h`+)OdQK" x="288" y="212">
    <field name="CASE">UPPERCASE</field>
    <value name="TEXT">
      <shadow type="text" id="U]_l*1}8CssB8:dbTvfh">
        <field name="TEXT">abc</field>
      </shadow>
      <block type="text_changeCase" id="$IihoCVT8)@@,d3EsGD@">
        <field name="CASE">UPPERCASE</field>
        <value name="TEXT">
          <shadow type="text" id="D=44+LkP658bAA_3#qsA">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
    </value>
  </block>
</xml>`

**Comment by RoboErikG** [comment]
Leaving open for discussion, but this is probably working as intended. We only ever render a single block in the insertion marker so that it doesn't extend off the screen (which makes it impossible to place a block in some cases).

We might want some indication that multiple blocks will be added in the middle, but that's low priority.

**Comment by cpcallen** [comment]
@rachel-fenichel and I think this is fine (not lovely, but consistent with other behaviour) and we do not intend to fix it.
