### ISSUE TITLE
Mutator On RTL Displaying Flyout On Wrong Side

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#2377]
### Problem statement
The flyout is positioning itself on the wrong side of the mutator box.

### Expected Behavior
![Screen Shot 2019-04-12 at 11 40 18 AM](https://user-images.githubusercontent.com/23059043/56058973-c73ff800-5d17-11e9-93a9-3bc674376261.png)

### Actual Behavior
![Screen Shot 2019-04-12 at 11 39 15 AM](https://user-images.githubusercontent.com/23059043/56058910-a24b8500-5d17-11e9-9816-058668e0958f.png)

### Steps to Reproduce
Open blockly playground
Drag out an if block
Open the mutator

### Stack Traces

```
Replace with error stack trace.
```

**Comment by BeksOmega** [comment]
This one is probably mine. Can grab.

**Comment by alschmiedt** [comment]
I think the fix might be to just have (this.targetWorkspace_.toolboxPosition == this.toolboxPosition_) instead of (targetWorkspaceMetrics.toolboxPosition == this.toolboxPosition_).

**Comment by BeksOmega** [comment]
@alschmiedt 
Can change.

**Comment by RoboErikG** [comment]
Beka fixed with #2378 . Needs cherry-pick into the release.

**Comment by rachel-fenichel** [comment]
Cherry-picked in, and I've updated my demo site.
