### ISSUE TITLE
Angle picker needs border

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2379]
The new bubble (but not a Blockly.Bubble) around the angle picker looks good.  However, it is lacking a border, shadow, highlight or other visual separator.  The result is that if there's a block of the same colour underneath, it looks like it has a tumour:

<img width="245" alt="Screen Shot 2019-04-12 at 15 28 28" src="https://user-images.githubusercontent.com/250480/56069483-14cc5d00-5d38-11e9-943a-1a5bf7e8ee6a.png">

That weird tab had me genuinely confused until I realized what it was.

Blocks have a highlight (top & left) and a shadow (bottom & right).  Bubbles use an SVG filter.  Originally blocks also used the filter, but the performance was terrible.  However, there aren't usually a dozen bubbles open at once, so filters are ok for them.

**Comment by nhzandi** [comment]
Why not make it just like the colour picker, pass different values for background and border? Right now the same colour is passed for both background and border! Can lighten Background colour and use it for border in the `Blockly.FieldAngle.prototype.showEditor_` function:
```javascript
Blockly.DropDownDiv.setColour(this.sourceBlock_.getColour(),
     goog.color.rgbArrayToHex(goog.color.lighten(goog.color.hexToRgb(this.sourceBlock_.getColour()), 0.3)));
```

**Comment by rachel-fenichel** [comment]
Sounds good.  Can you make a PR and send it in with a screenshot of what it looks like with the new colours?

**Comment by NeilFraser** [comment]
Thanks @nhzandi 
Looks great!
