### ISSUE TITLE
Degree symbol should be right of number in RTL

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2380]
Blockly currently uses `90°` for LTR and `°90` for RTL.  My belief is that RTL should not be flipped, and that `90°` should be used universally.

This evidence for this claim is based on:
* The Hebrew wikipedia page on angles: https://yi.wikipedia.org/wiki/%D7%92%D7%A8%D7%90%D7%93_(%D7%95%D7%95%D7%99%D7%A0%D7%A7%D7%9C)
* Israeli weather site (note weather degrees are not angle degrees): https://www.israelweather.co.il/forecast/week_15.html
* Arabic weather site (note that the large panels use `90°` but the paragraph text uses `°90`): https://www.arabiaweather.com/%D8%AA%D9%88%D9%82%D8%B9%D8%A7%D8%AA-%D8%A7%D9%84%D8%B7%D9%82%D8%B3/%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6/344/sa

This is not extremely strong evidence.  But on balance, it appears that our degree symbol is on the wrong side.

**Comment by chrisgarrity** [comment]
Unfortunately it's not quite that simple. Hebrew mathematical notation is LTR, but in Arabic script it's mixed. This article on [Arabic mathematical notation](https://www.w3.org/TR/2006/NOTE-arabic-math-20060131/#Comparison) is helpful in showing the different Arabic usage.

However, putting the degree symbol on the right for RTL in Blockly is likely to be correct more often than not.
