### ISSUE TITLE
Calling setVisible(false) on a Field Does Not Update the Block Correctly

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2381]
### Problem statement

I was working on adding an isDirty_ flag to fields when I noticed that if you call setVisible on a field the field disappears but the block doesn't rerender. I created a test case for the playground ([link](https://github.com/google/blockly/compare/develop...BeksOmega:feature/SetVisible )) so you can see the behavior.

![SetVisible](https://user-images.githubusercontent.com/25440652/56081644-720df000-5dc4-11e9-923f-83d6c225229c.gif)

(As you can see, even if you do call render() on the block it has that gap at the end, but that's not what this issue is about.)

### Proposals

This is the current state of the setVisible() code.
```
Blockly.Field.prototype.setVisible = function(visible) {
  if (this.visible_ == visible) {
    return;
  }
  this.visible_ = visible;
  var root = this.getSvgRoot();
  if (root) {
    root.style.display = visible ? 'block' : 'none';
    this.render_();
  }
};
```

And then the code for that render_() call is:
```
Blockly.Field.prototype.render_ = function() {
  if (!this.visible_) {
    this.size_.width = 0;
    return;
  }
 // other unimportant stuff...
};
```

Note 1: As far as I can tell there's no reason the` this.size_.width = 0` line needs to be inside the render_() function.

Note 2: field.setVisible is only called from [input.setVisible](https://github.com/google/blockly/blob/09853c37250528b65a87f6e0bb73432b57f86108/core/input.js#L170) which is only called from [BlockSvg.setCollapsed](https://github.com/google/blockly/blob/82871b3d24563388a6f113da8984694e9f37b53e/core/block_svg.js#L503), which also rerenders the block.

#### Proposal 1

Remove setVisible from the public API. As it doesn't work I think it's pretty safe to assume no one is using it.

#### Proposal 2

Have setVisible force a rerender of the block. This would require that setVisible have some sort of internal function that doesn't force a rerender that input.setVisible could call so that  we don't get a bunch of duplicate render calls.

```
Blockly.Field.prototype.setVisible = function(visible) {
  if (this.visible_ == visible) {
    return;
  }
  this.visible_ = visible;
  // input.setVisible would call this instead of setVisible
  this.doInternalFunction();
  this.forceRerender();
};
```
This internal function could either be a public hook function that child classes could override, or a simple private function that they could not. I think the private function makes more sense as I can't think of a reason why a subclass would need special visibility behavior.

### Steps to Reproduce

1. Grab [this ](https://github.com/google/blockly/compare/develop...BeksOmega:feature/SetVisible)code an add it to your local copy.
2. Open the Test Blocks > Fields Refactor category.
3. Click the "Hide Middle Field" Button. Observe how there is a gap between fields because the block was not rerendered.

### Operating System and Browser

I am assuming this is not browser specific

### Additional Information

N/A

**Comment by RoboErikG** [comment]
I'd lean towards making setVisible @package. It needs to be called from Input/Block as part of collapsing a block, but it definitely shouldn't be used to hide fields individually like this. ;)
