### ISSUE TITLE
Comments should be allowed on non-movable/deletable blocks

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2388]
### Problem statement

Currently, [the check](https://github.com/google/blockly/blob/82871b3d24563388a6f113da8984694e9f37b53e/core/block_svg.js#L650) for whether or not you can add a comment to a block includes checking that a block can be moved and deleted. Comments should probably be allowed in the cases that a block is not movable or not deletable so long as it is still editable.

### Steps to Reproduce

1. Start by..
2. Next, do..

### Stack Traces

```
Replace with error stack trace.
```

**Comment by ahigerd** [comment]
I believe the above PR ought to address this issue.
