### ISSUE TITLE
Different point "0" for the Angle drop down ?

### ISSUE THREAD

**Issue by MarkusBordihn** [google/blockly#239]
At the moment the angel drop down has the "0" point at the right and "180" at the left, which is mathematical correct.
But it would be great if you could have an option to have the "0" point at the top and "180" at the bottom as well.

**Comment by NeilFraser** [comment]
Where should 90 be?

**Comment by MarkusBordihn** [comment]
I assume for LTR it should right and for RTL it should be left. 

@MartenvanWezel
Please provide additional details for this.

**Comment by MartenvanWezel** [comment]
I would say 0 degrees should be "12 o clock", 90 degrees = "3 o clock", 180-6, 270-9

**Comment by NeilFraser** [comment]
The X values on a graph do not reverse in RTL (I checked this), so I'm not sure that RTL angles should be reversed.

So we'd need a setting for where 0 is.
We'd also need a setting for which direction is increasing (math is counter-clockwise, yours is clockwise).
Do we also need a setting for where the wrap is?  Meaning is right 270, or is it -90?

**Comment by MartenvanWezel** [comment]
I suppose our situation ('controlling directional robots') is quite different from the other use case ('math'). I'm not enough of a math wiz to argue this strongly but  even for that case I found the current blockly implementation a bit counter-intuitive but I couldn't tell you exactly why.

Fact is though that with real live robots that have a 'driving direction', it makes sense to mentally project a clock face on top of the device, and have 0 degrees be 'forward', 90 be 'right' and 270 (or -90) be "left'. 

If you want to preserve the math case that sounds reasonable but I would submit that it would be good to then implement a second 'reality' mode.

**Comment by NeilFraser** [comment]
Ok, I'm seeing two different modes.

1. [Math mode](https://www.google.com/search?q=angle&source=lnms&tbm=isch&sa=X&ved=0ahUKEwimz6ru1-HKAhUBy2MKHYTPAjoQ_AUIBygB&biw=1600&bih=920#tbm=isch&q=angle+protractor&imgrc=_).  0 to the right, increasing counter-clockwise.
2. [Compass mode](https://www.google.com/search?q=compass+bearings&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjEgo201-HKAhVK7mMKHadAA0EQsAQIHA&biw=1600&bih=920#tbm=isch&q=compass+bearing).  0 to the top, increasing clockwise.

Both wrap at 360, not 180 (-90 typed becomes 270).  LTR and RTL behave identically.  This would be a global setting, it would not be possible to mix some angle pickers of one type with some angle pickers of the other type in the same page.

**Comment by MartenvanWezel** [comment]
Sounds like an excellent solution to me!

**Comment by NeilFraser** [comment]
Fixed in https://github.com/google/blockly/commit/a481c1cff8d311e82771a24921fd0f3d3080adde

(Note the 2016 branch is a bit buggy right now, so it's best to either cherry-pick this change or wait a few days for it to merge back to master.)
