### ISSUE TITLE
Buttons and Labels in Toolbox do Not Respect <sep> Elements

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2396]
### Problem statement

Sometimes you want to have lots of buttons in a flyout, but this can make your flyout look cluttered. It would be nice to be able to set the gap between buttons.

### Expected Behavior

Buttons should respect <sep> elements.
![SeparationNew](https://user-images.githubusercontent.com/25440652/56459243-abef7100-6345-11e9-9a8e-44eb4e2d4412.jpg)

### Actual Behavior

They do not.
![SeparationOld](https://user-images.githubusercontent.com/25440652/56459245-af82f800-6345-11e9-98ec-ce9bb3016d9d.jpg)

### Steps to Reproduce

1. Add the below code to the 'test-blocks' toolbox in the playground.
```
    <category name="Separation">
      <block type="logic_compare"></block>
      <sep gap="32"></sep>
      <block type="logic_compare"></block>
      <sep gap="8"></sep>
      <block type="logic_compare"></block>
      <button text="button" callbackKey="logCallback"></button>
      <sep gap="32"></sep>
      <button text="button" callbackKey="logCallback"></button>
      <sep gap="8"></sep>
      <button text="button" callbackKey="logCallback"></button>
      <label text="label"></label>
      <sep gap="32"></sep>
      <label text="label"></label>
      <sep gap="8"></sep>
      <label text="label"></label>
    </category>
```
2. Open the "Separation" category. Observe how the buttons and labels are all 24 units (default) appart.

### Stack Traces

N/A

### Operating System and Browser

I am assuming this is not browser specific.

### Additional Information

N/A

**Comment by RoboErikG** [comment]
Thanks again, Beks. =)
