### ISSUE TITLE
Look at performance issues in mobile browsers

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#240]
Tracking bug for looking at Blockly's performance on mobile browsers.

If you open Blockly Playground in Chrome on Android significant jank can be observed.

Dragging the workspace is the worst offender with frames sometimes taking over 200ms to render. Dragging groups of blocks is less severe but still has issues. From the traces it looks like touch events can take ~50ms to process which leads to multiple touch events being handled between frames. Attached tracefile can be opened in Chrome Developer Tools in the Timeline tab (right click for save/load menu).

[Nexus9ChromePlaygroundTimeline2.json.zip](https://github.com/google/blockly/files/98092/Nexus9ChromePlaygroundTimeline2.json.zip)

**Comment by RoboErikG** [comment]
Instructions for remote debugging can be found here: https://developer.chrome.com/devtools/docs/remote-debugging

**Comment by NeilFraser** [comment]
Workspace dragging now twice as fast: https://github.com/google/blockly/commit/0027d9294a1dea2b544c924e444868153febd9e0

**Comment by MNSDivya** [comment]
Dragging worked fast on chrome browser in iPhone. Needs a check on Android devices.

**Comment by rachel-fenichel** [comment]
Closing as this is not tracking anything now.
