### ISSUE TITLE
TypedVariables category is not in StandardCategories.categoryMap.

### ISSUE THREAD

**Issue by duzc2** [google/blockly#2408]
### Problem statement
TypedVariables category is not in StandardCategories.categoryMap.
### Expected Behavior
when add a category in block factory ,  can use 'TypedVariables' to add a 
    category name="Variables" style="variable_category" custom="VARIABLE_DYNAMIC"
to editing toolbox
### Actual Behavior

let the use rewrite the name of category.

### Steps to Reproduce

1. go to blockfactory/index.html
2. open Workspace Factory
3. add a Standard Category 
4. type 'TypedVaraibles'

**Comment by alschmiedt** [comment]
Done.
