### ISSUE TITLE
MIT's licence appearing in compressed file

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2412]
The Closure compiler leaves all licences in the compiled code, presumably for legal reasons.  This resulted in dozens of copies of Google's standard licence in the compressed JS files.  To fix this, there's a regular expression that detects Google's standard Apache licences and strips them:
https://github.com/google/blockly/blob/master/build.py#L394

However, there's now an MIT licence that's lurking in the compressed file:
https://github.com/google/blockly/blob/master/blockly_compressed.js#L1579

This represents 634 bytes that do nothing.  The source is here:
https://github.com/google/blockly/blob/master/core/dropdowndiv.js

Can we get written permission from MIT that it's ok to strip their licence in compiled code only?  No change to their source code or to their licence.

**Comment by thisandagain** [comment]
Hi @NeilFraser. Yes, it is ok to strip the MIT License from the compiled code.

**Comment by NeilFraser** [comment]
Resolved in Blockly with https://github.com/google/blockly/commit/8d4a73e33dd2b9bba3a77a84f1cdb9ad43160e03

Resolved in Blockly Games with https://github.com/google/blockly-games/commit/88d59e19b851f481a88d90af6b4df37c5a027a88

Thanks!
