### ISSUE TITLE
getAllBlockStyles Annotation Error?

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2414]
### Expected Behavior

The annotation and the return type match.
A) getAllBlockStyles would return an {Array.\<String\>} as annotated.
or B) Annotation would say getAllBlockStyles returns {Object.<string, Blockly.BlockStyle>}.

### Actual Behavior

The annotation and the return type do not match.

### Steps to Reproduce

See [here](https://github.com/google/blockly/blob/9c4f9d6c1693c3c25160f008d3eaa2539127c9e8/core/theme.js#L56).

**Comment by suhailsinghbains** [comment]
Hi @BeksOmega 
Can I please work on this issue, I am new here.
Thanks

**Comment by BeksOmega** [comment]
Hi @suhailsinghbains 
I don't manage the github, I'm just a contributor =) but generally if something is marked with the help wanted tag that means anyone can grab it. 
--Beka

**Comment by suhailsinghbains** [comment]
I can't find the installation docs, can you please help me how to set up the project locally.
Thanks

**Comment by BeksOmega** [comment]
You'll want to look at [getting the code](https://developers.google.com/blockly/guides/get-started/web#get_the_code). That should be enough to get you started with this issue :D

Hopefully that'll get you up and running, but if you have further questions please post on the [developer forum](https://groups.google.com/forum/#!forum/blockly). I hope it goes well!
Beka

P.S. If you want to do further work with blockly I'd start by reading through some of the [docs ](https://developers.google.com/blockly/guides/configure/web/fixed-size)and messing with the [playground](https://developers.google.com/blockly/guides/modify/web/building#playground).

**Comment by NeilFraser** [comment]
Fixed.  Thanks @BeksOmega!
