### ISSUE TITLE
what can i do to return the result from the function that use in controls_if block when i try to create a new block (actually i need it return true or false,but nothing return)

### ISSUE THREAD

**Issue by wiserliu** [google/blockly#2416]
### Steps to Reproduce

1. Start by..
2. Next, do..

### Stack Traces

```
Replace with error stack trace.
```

**Comment by wiserliu** [comment]
![image](https://user-images.githubusercontent.com/44865004/56845698-b1295e80-68f7-11e9-8f5b-d21a8d56345e.png)
![image](https://user-images.githubusercontent.com/44865004/56845701-bdadb700-68f7-11e9-8f0f-39e699aa85fb.png)
And the funtion checkKeyDown will return ture or false, but unfortunately.

**Comment by wiserliu** [comment]
the entrance caller do not return ...

**Comment by RoboErikG** [comment]
Please ask questions like this on [Blockly's forum](https://groups.google.com/forum/#!forum/blockly)
