### ISSUE TITLE
Clarify in docs that variabletype needs to be set in Toolbox XML when using typed variables

### ISSUE THREAD

**Issue by YannCaron** [google/blockly#2422]
This problem lead me to craziness :-) I think it is a bug.

A want to create a custom type called 'Actor' to manage some object in my game engine.

![image](https://user-images.githubusercontent.com/5962300/56957362-250d7600-6b47-11e9-8284-7493fa914fcd.png)

But if I setup the type of the field_variable as well :
``` json
{
  "type": "field_variable",
  "name": "NAME",
  "variable": "hero",
  "validator": null,
  "variableTypes": ["Actor"],
  "defaultType": "Actor"
}
```
And I want to setup the value of this field within the tookbox definition (I also tried with a shadow block, same issue) :
``` xml
<block type="actor_create" inline="true">
  <field name="NAME">hero</field>
</block>
```
NB: the block definition is into a dynamic category, so the 'hero' variable exists at the block definition time :-)

Even if 'hero' is an Actor object, it's lead to this error
``` sh
Error: Variable type doesn't match this field! Type was 
```

I turn around from a long time with that and searched on google to find solutions, but nothing.
I know that defaultType is mandatory and everything seems OK, that's why I think it is a bug.

Here is the 'actor_create' definition :
``` json
{
  "type": "actor_create",
  "args0": [
    {
      "type": "field_variable",
      "name": "NAME",
      "variable": "hero",
      "validator": null,
      "variableTypes": [
        "Actor"
      ],
      "defaultType": "Actor"
    },
    {
      "type": "input_value",
      "name": "IMG",
      "check": "Image"
    },
    {
      "type": "input_value",
      "name": "X",
      "check": "Number"
    },
    {
      "type": "input_value",
      "name": "Y",
      "check": "Number"
    }
  ],
  "inputsInline": true,
  "colour": "%{BKY_ACTOR_HUE}",
  "message0": "%{BKY_ACTOR_CREATE_MSG}",
  "tooltip": "%{BKY_ACTOR_CREATE_HELP}",
  "helpUrl": "%{BKY_ACTOR_CREATE_URL}",
  "previousStatement": null,
  "nextStatement": null
}
```

**Comment by RoboErikG** [comment]
How are you creating the 'hero' variable? Are you calling createVariable with the optional type set to Actor?
`Blockly.Variables.createVariable(workspace, null, 'Actor');`

**Comment by YannCaron** [comment]
Hello @RoboErikG , No, I am using
`Blockly.Variables.createVariableButtonHandler(button.getTargetWorkspace(), null, 'Actor');` with a button

**Comment by YannCaron** [comment]
Something is that 'hero' variable seems to be created 2 times :
![image](https://user-images.githubusercontent.com/5962300/57015329-9d8e3880-6c14-11e9-9786-0aa739e54229.png)

**Comment by RoboErikG** [comment]
Ah, gotcha. You need to add a type attribute to the toolbox xml.

<field name="NAME" variabletype="Actor">hero</field>

We should probably update the documentation at the least to make this clearer. We could potentially infer the type when it's in the toolbox, but there are a lot of corner cases where that could cause problems.

**Comment by YannCaron** [comment]
Brilliant @RoboErikG It's works perfectly ! Many thanks.
I am just surprised that it is not camel case formatted like other attributes ("variableType") but anyway, the most important is that it is working and let me carry on my project :-)
Thanks again and keep up the good job :+1:

**Comment by rachel-fenichel** [comment]
Oh yeah, the lack of camel casing is because attributes get forced to lowercase in `setAttribute` (either on XML or HTML DOM elements, I don't remember which).  I agree that it's a mismatch with everything else we do.

**Comment by RoboErikG** [comment]
Toolbox page will get a new section on variables next week.

**Comment by YannCaron** [comment]
Great ! Many thanks !
