### ISSUE TITLE
Change Access Level of Field.updateWidth

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2428]
### Problem statement

The updateWidth function is called as part of the rendering of a field. After all of the parts of the field have been shuffled around it figures out how much room they take up and assigns that value to the field's size_ property.

It doesn't really make sense to call this from anywhere besides the render_ function, and I can't think of a reason a developer would want to call it, so having it be public seems unecessary.

This also makes it confusing when you want to create a custom field that has variable /height/ (which is supported!) but you only see an "updateWidth" function.

[Here](https://github.com/google/blockly/search?q=updateWidth&unscoped_q=updateWidth)'s a link to all the places updateWidth gets called, incase anyone is interested.

### Proposal

Since it wouldn't make sense for a developer to call this function externally, I believe it can safely be changed to a private function.

**Comment by RoboErikG** [comment]
Since it's overridden by a few subclasses it'd need to be package or protected, but otherwise sounds reasonable.
