### ISSUE TITLE
Blockly Future

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2432]
The "Future" page in our documentation needs some love and attention:
https://developers.google.com/blockly/guides/modify/future

This page has been almost unchanged for more than five years.  Maybe we should visit it on a yearly basis so that it has a closer connection with our longer term goals.  Or if that's more effort than the value of the page, maybe scrap it.

**Comment by RoboErikG** [comment]
I'd lean towards scrapping that page and making future plans part of our yearly updates email.
