### ISSUE TITLE
Very very bad FOR loop semantics

### ISSUE THREAD

**Issue by bkisdi** [google/blockly#244]
IMO, the semantics of the "controls_for" block is a very bad approach in Blockly.
Namely, it investigates the start and final values of the loop for the greater one, and changes the sign of the step value to run into the "good" direction. (It' against the 2nd Law of Robotics... :) )

This seams to be "comfortable", but teaches a bad practice, which is not supported in other programming languages. Young programmers shouldn't learn this!

Consider for example, the simple task of cloning an array. The loop should run from 1 to the length of the array, but it will count down from 1 to 0 for an empty array, indexing it by two invalid indices, instead of simply non entering the cycle. An extra IF is needed to rule out the empty array case, which is not so in the "real" life.

It is also impossible to specify a negative step value, because the block "decides" instead of the programmer to use its absolute value.

Please let's discuss it, and give the "controls_for" block a simpler and more usable semantics.

**Comment by NeilFraser** [comment]
This appears to be a no-win scenario.  Blockly's original behaviour was the more conventional approach you describe.  And we got very confused kids who wanted to count down from 10 to 1 and got nothing.

I don't think there is a solution that satisfies all parties.  Different audiences have different expectations (such as should arrays be 1 based or 0 based).  Ultimately, Blockly is just a visual editor, not a language.  The blocks that come with Blockly are samples which you (as a developer) can use, or discard, or modify.  Feel free to fix the behaviour to match the expectations of your audience.
