### ISSUE TITLE
Q: Should fields initialize with default values?

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2454]
### Problem statement

I'm writing up constructor, fromJson, and setValue tests for all of the fields and I'm unsure of how they're supposed to handle being constructed with no arguements.

Here are some examples of current behavior:
* The number and angle fields build themselves with a value of 0 if no value is given and they have their value marked as optional.
* The checkbox field builds itself with a value of 'FALSE' if no value is given, but its value is /not/ marked as optional. [EDIT: The date field works similarly, initializing to the current day while the value is not marked as optional.]
* The colour field throws an uncaught error when it tries to run [this ](https://github.com/google/blockly/blob/9c4f9d6c1693c3c25160f008d3eaa2539127c9e8/core/field_colour.js#L198) line, and its value is not marked as optional.
* [EDIT: The dropdown field throws a purposeful error, so that's nice!]

How do you guys want this to be handled? (Although I generally like consistency, I think this could be done on a field-by-field basis if you think that makes more sense.)

**Comment by rachel-fenichel** [comment]
I think in general the fields should initialize with default values or throw clear errors.  Variable fields may be an exception--making a value for a variable field doesn't make sense until it's installed on a block.
