### ISSUE TITLE
Extension Documentation Example Incorrect

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2474]
### Problem statement

The example code for creating an extension doesn't work.

### Expected Behavior

You should be able to copy-pasta the example and run it.

### Actual Behavior

If you try you get errors.

### Steps to Reproduce

1. Define a block with the below code (the extension has been taken directly from the extensions page)
```
{
    "type": "dynamic_dropdown",
    "message0": "number %1",
    "args0": [
      {
        "type": "input_dummy",
        "name": "INPUT"
      }
    ],
    "output": null,
    "extensions": [/*"dynamic_menu_extension", */"parent_tooltip_extension"]
  }

Blockly.Extensions.register('parent_tooltip_extension',
  new function() {
    // this refers to the block that the extension is being run on
    this.setTooltip(function() {
      var parent = thisBlock.getParent();
      return (parent && parent.getInputsInline() && parent.tooltip) ||
        Blockly.Msg.MATH_NUMBER_TOOLTIP;
    });
  });
```
2. Reload the playground.
3. Observe how you get an error.

### Stack Traces

```
Uncaught TypeError: this.setTooltip is not a function
    at new <anonymous> (my_test_blocks.js:726)
    at my_test_blocks.js:724
(anonymous) @ my_test_blocks.js:726
(anonymous) @ my_test_blocks.js:724
```

### How to Fix

The code should look like this:
```
Blockly.Extensions.register('parent_tooltip_extension',
  function() {
    // this refers to the block that the extension is being run on, we need
    // to cache it so that it can be used inside the tooltip function.
    var thisBlock = this;
    this.setTooltip(function() {
      var parent = thisBlock.getParent();
      return (parent && parent.getInputsInline() && parent.tooltip) ||
        Blockly.Msg.MATH_NUMBER_TOOLTIP;
    });
  });
```
* the 'new function() {' line was changed to just be function() {
* thisBlock is now defined.

### Test Coverage

1. Define the block JSON as stated in the 'Steps to Reproduce' section.
2. Define the extension as stated in the 'How to Fix' section.
3. Load the below XML into the playground.
```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="logic_compare" id="x:kAZ3n%BQ6s8xS@DT02" x="62" y="137">
    <field name="OP">EQ</field>
    <value name="A">
      <block type="example_block" id="Cb|TxRhLz`XjwU)%-+.q"></block>
    </value>
  </block>
  <block type="example_block" id="ZF@lLZiM?|A_QhX+m=2`" x="63" y="212"></block>
</xml>
```

4. Hover over the orphaned number block, observe how its tooltip says 'a number'. (pass)
5. Hover over the child number block, observe how its tooltip says 'Return true if both inputs equal eachother'. (pass)

**Comment by rachel-fenichel** [comment]
Self-assigned to update the sample code in the documentation.

**Comment by rachel-fenichel** [comment]
Done, and it'll go live next time we push the developer site.
