### ISSUE TITLE
How to Redevelop Field_date

### ISSUE THREAD

**Issue by zxt-gitDemo** [google/blockly#2480]
I need to use Field_date in the react project, but the Blockly_compressed.js and blocks_compressed.js files are loaded and the Field_date component is not normally used. How do I configure it?

**Comment by rachel-fenichel** [comment]
Add [this line](https://github.com/google/blockly/blob/master/core/blockly.js#L40) and run `build.py` to rebuild.

Cheers,
Rachel

**Comment by zxt-gitDemo** [comment]
Operation error reporting，If you can, can you send the uncommented, running files directly to my mailbox? Thank you
