### ISSUE TITLE
Firefox 67.0 when block drag from toolbox, block not centred to mouse

### ISSUE THREAD

**Issue by YannCaron** [google/blockly#2482]
After updated by Firefox to 67.0 I experienced a strange behaviour :
When picking block from toolbox, the block is displaced but not centred to the cursor. It move far to the left of it (I estimate about 250px).
I don't know if it is a blockly bug or a firefox one.

**Comment by NeilFraser** [comment]
Confirmed.  Works as expected on FF 66, breaks badly in FF 67.

This affects category toolboxes, not simple toolboxes.  Master and Develop.

Pretty nasty bug.  Thanks for reporting!

**Comment by NeilFraser** [comment]
The root issue is that this is failing to match:
```
'display: block; transform: translate(107px);'.match(Blockly.utils.getRelativeXY.XY_2D_REGEX_)
```

**Comment by NeilFraser** [comment]
PR #2485 fixes this issue.  I appear to be alone in the office today (is there a Blockly party I'm not invited to?), so this might take a little while to land in develop and master.

**Comment by YannCaron** [comment]
Wahou ! Many thanks for the reactivity.
Great, I will wait until the fix is applied to master branch :-) :+1:

**Comment by NeilFraser** [comment]
Patch applied to both develop and master.
* The Blockly team needs to push to the demo server
* I'll handle a recompile and push to Blockly Games later today.
* We also need to ensure that larger users (e.g. Scratch) know about this issue since it affects them and they need to update.

Keeping this issue open.

**Comment by RoboErikG** [comment]
@thisandagain @pelikhan

**Comment by rachel-fenichel** [comment]
@ewpatton

**Comment by YannCaron** [comment]
I've tested on my Ubuntu's Firefox v67.0 (64bits) and it works perfectly now.
Many thanks for your great job :-)
