### ISSUE TITLE
FieldVariable Variable Types Investigated

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2483]
### Expected Behavior

If a variable field does not have a defined type (or types) all types should be accepted.

### Problem Statement

Based on the typeIsAllowed_ and getVariableTypes_ functions, this may not always work as expected.

* typeIsAllowed_ seems to expect getVariableTypes_ to possibly return null, but it does not.
* typeIsAllowed /does not/ seem to expect getVariableTypes_ to return an array containing an empty string, which it may.
* getVariableTypes_ checks if the field is attached to the workspace. But it should only get called after it is attached to a workspace, so this check may be irrelevant.

All of the above need to be investigated.

### Additional Information

When this is updated typeIsAllowed_ tests should probably be added to the variable field.

Also the empty variable list error should probably be made more descriptive (block type and field name).

**Comment by seldomU** [comment]
The following should be valid toolbox XML, but can only be loaded if the workspace already contains a variable of type _Object_:
```xml
<block type="variables_get_dynamic">
    <field name="VAR" variabletype="Object">someObject</field>
</block>
```

It goes wrong when typeIsAllowed_ is called with a type (_Object_) and getVariableTypes_ returns ['']. typeIsAllowed_ should return true but doesn't. Modified like this, the field works as expected: 
```JavaScript
Blockly.FieldVariable.prototype.typeIsAllowed_ = function(type) {
  var typeList = this.getVariableTypes_();
  for (var i = 0; i < typeList.length; i++) {
    if (type == typeList[i] || typeList[i] == "") {
      return true;
    }
  }
  return false;
};
```

**Comment by samelhusseini** [comment]
Fixed.
