### ISSUE TITLE
Blockly.FieldDate is not a constructor

### ISSUE THREAD

**Issue by zxt-gitDemo** [google/blockly#2488]
When Date uncomments, the report lacks a FiledDate constructor

**Comment by RoboErikG** [comment]
You need to run the build.py script after uncommenting the requires. If you're still having problems after that please post on the forum and include information about your setup and the specific steps you took to enable FieldDate.

**Comment by KernelLora** [comment]
blockly.js seems to be restructured.
Now where should we  enable the FieldDate to be part of build output ?
