### ISSUE TITLE
Some Browsers Don't Properly Import XML with Sub-Block Nodes

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2499]
### Problem statement

If the XML parser tries to deserialize some xml that has nodes inside block tags (i.e. shadow blocks, values, etc) it will sometimes fail, depending on the browser.

This can be seen when opening certain toolbox categories, as well as when importing straight XML through the playground.

### Steps to Reproduce

1. Try to import the below code in the playground.
```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="controls_if" id="L:ym~c^IZzI,G#/PaR(^" x="38" y="88">
    <value name="IF0">
      <block type="logic_boolean" id="JQdsdXtYxW}j~W8k%ke`">
        <field name="BOOL">TRUE</field>
      </block>
    </value>
  </block>
</xml>
```
2. Observe the error.

### Stack Traces

```
0: Object doesn't support property or method 'getAttribute'
xml.js (630,6)
```

### Operating System and Browser

* Windows Internet Explorer 11
* Windows Edge

### Additional Information

I think the problem originates with #2468 If you try and log the value of `Element.TEXT_NODE` inside of the `domToBlockHeadless_` function when you're running on internet explorer or edge, it will return undefined. If you log it when on chrome or firefox it returns 3 (correct).

**Comment by NeilFraser** [comment]
Good grief.  Thanks for this.

Can you check to see if Microsoft browsers know about Node.TEXT_NODE?

**Comment by NeilFraser** [comment]
I've prepared this commit: https://github.com/google/blockly/commit/2c0983911ffcb937bf58f618f1868e46e4fa2e8b  However, I'll wait until we hear whether Microsoft browsers support Node constants before creating a PR.

What's odd is that Element is a child of Node.  Which means that if a property is on Node, then it should also be on Element.

**Comment by BeksOmega** [comment]
> Can you check to see if Microsoft browsers know about Node.TEXT_NODE?

Screen Cap of Edge Console:
![TEXTNODE_Edge](https://user-images.githubusercontent.com/25440652/58382993-284d2380-7f86-11e9-90e8-dbca407e858e.jpg)

Screen Cap of IE 11 Console:
![TEXTNODE_IE](https://user-images.githubusercontent.com/25440652/58383001-30a55e80-7f86-11e9-80ad-92eca66029c5.jpg)

So it looks like they do!

**Comment by NeilFraser** [comment]
Thanks!  PR #2503 created.

**Comment by RoboErikG** [comment]
#2503 has been merged.
