### ISSUE TITLE
Correctly cleanup resources on dispose

### ISSUE THREAD

**Issue by manzato** [google/blockly#250]
Disposing a workspace doesn't dispose all the created elements. Particularly 2 DIVs are left behind attached to the document body: ```blocklyWidgetDiv``` and ```blocklyTooltipDiv```. Even if those are manually removed by the caller, ```Blockly.WidgetDiv``` and ```Blockly.Tooltip``` hold internal references (```Blockly.WidgetDiv.DIV``` and ```Blockly.Tooltip.DIV```) to the generated DOM, and aren't created again (while this is the case with ```Blockly.Toolbox```), breaking the editor in subsequent uses.

**Comment by mr-unicoder** [comment]
Please, any help on this ?
I'm facing the same problem which breaks my entire application.

**Comment by rachel-fenichel** [comment]
The problem here is that the widget div and tooltip div can be shared across multiple workspace instances.  One solution may be to make one of each for each workspace.

**Comment by NeilFraser** [comment]
> Particularly 2 DIVs are left behind attached to the document body: blocklyWidgetDiv and blocklyTooltipDiv.

Correct.  These two divs are empty and invisible.

> Even if those are manually removed by the caller

Why would you do that?

Blockly works correctly if you create and inject a workspace, then dispose it, then create and inject another workspace.  Yes, things break if you start nuking DOM elements.  Please explain the need to delete these empty divs.  I just want to understand the use case before making changes.  Thanks!

**Comment by manzato** [comment]
I have a single page app which uses Blockly in one of the multiple components this app has, and closing it doesn't free all the resources as explained above. Don't remember now (other than cleanliness) what were the negative effects on my app.

**Comment by NeilFraser** [comment]
Any reference-counting code that deletes and respawns these DOM elements is going to be larger than:
  <div class="blocklyWidgetDiv"></div><div class="blocklyTooltipDiv"></div>

And these elements don't accumulate as Blockly is created and deleted, so it never gets worse than that.  I'm scratching my head about the issue and how it "breaks my entire application".

I'm happy to reopen and make changes if a problematic use case is identified.  If memory usage is the only issue, any fix would result in greater memory usage than the current situation.
