### ISSUE TITLE
Variables Page Documentation Updates

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2502]
### Problem statement

The lovely gentleperson over [here ](https://groups.google.com/forum/#!topic/blockly/e83RlQbKo1c)was having some trouble getting typed variables setup. They followed the documentation, but the things they were having trouble with were not documented.

### Suggestions

* Javascript block definitions should be included in addition to JSON definitions.
* The JSON comments could probably be removed? Everything in the comments is also explained below, and I think they make it look a bit cluttered, but that's just a matter of preference.
* Examples of block XML should be given for typed and untyped blocks.
* The last line of [this ](https://developers.google.com/blockly/guides/create-custom-blocks/variables#add_variables_to_toolbox)section can be removed, as it is incorrect. If you're overriding the dynamic category you don't need to do any work to remove the default blocks.
* The [create variable button](https://developers.google.com/blockly/guides/create-custom-blocks/variables#create_variable_button) example code should be changed to reflect the [new creation API](https://github.com/google/blockly/blob/0e0cd666c0a62a0354e2d0daba419a9860ab2b6f/core/variables.js#L285).

### Additional Information

N/A

**Comment by RoboErikG** [comment]
This is related to #2422 but provides additional changes to improve readability and accuracy. Punting out of this release as we've run out of time.
