### ISSUE TITLE
highlightBlock incorrect code generation

### ISSUE THREAD

**Issue by manzato** [google/blockly#251]
I'm using blockly to generate Javascript code and using ```Blockly.JavaScript.STATEMENT_PREFIX``` ```highlightBlock``` to track progress. This used to work OK, but now, with the new block ID generation (which generates strings instead of numeric values), if the generated id ends with the dollar sign "$", the generated code is incorrect, making my program fail randomly.

Wrongly generated code:
```
statement();
highlightBlock('@xM02,OD|StGUj6EP^i);
);
statement();
```
Expected to be:
```
statement();
highlightBlock('@xM02,OD|StGUj6EP^i$');
statement();
```

I'm obtaining the code using:
``` 
  Blockly.JavaScript.STATEMENT_PREFIX = 'highlightBlock(%1);\n';
  console.log(Blockly.JavaScript.workspaceToCode(workspace));
```

**Comment by manzato** [comment]
Note this didn't happen before (with numeric Ids) nor it happens if the last character of the block ID is something other than '$'.

**Comment by NeilFraser** [comment]
What an interesting bug.  It could be fixed with `id.replace(/\$/g, '$$$$')` in generator.js (three places).  But I have a feeling that it would just resurface in a couple of years once we've forgotten about this case.

Instead I've removed $ from the crypto soup.

**Comment by manzato** [comment]
Thanks for the fast response/fix @NeilFraser !
