### ISSUE TITLE
How to regenerate the blockly_compressed.js file after FieldDate unannotates it?

### ISSUE THREAD

**Issue by zxt-gitDemo** [google/blockly#2510]
I need to be able to get the FieldDate constructor in Windows, but I can't get the local compiled file load.
I used component test development, did not find a modular import package, can only import external JS files, and I now need to use the FieldDate time component, but after I recompile, still can not succeed!
My import before Compilation：
![image](https://user-images.githubusercontent.com/28282727/58455812-2c7b6b80-8155-11e9-92ee-98d9019bcec0.png)
After compilation, I import
![image](https://user-images.githubusercontent.com/28282727/58455834-3c934b00-8155-11e9-82d7-690dcda12659.png)
I still can't get the FieldDate constructor from Windows

**Comment by RoboErikG** [comment]
Please ask questions on the forum.
