### ISSUE TITLE
Why does the locally opened window have FieldDate, while the project launched with http://localhost:3000 has no FieldDate alone?

### ISSUE THREAD

**Issue by zxt-gitDemo** [google/blockly#2511]
file:///C:/Users/86187/Desktop/index.html，
![image](https://user-images.githubusercontent.com/28282727/58467823-efbc6e00-816e-11e9-9b02-0aee2a33d7e9.png)
http://localhost:3000
![image](https://user-images.githubusercontent.com/28282727/58467859-0236a780-816f-11e9-9d0e-eb55558fb4ad.png)
They all load the same js. Why does one of them have one and the other have none?

**Comment by RoboErikG** [comment]
I'm not sure off the top of my head, but [the forum](https://groups.google.com/forum/#!forum/blockly) would be a better place to ask.

You should also include your setup, what you've modified, and what page you're looking at. There's a lot of demo index.html files.
