### ISSUE TITLE
Dropdown arrow missing padding.

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2527]
Old:

![image](https://user-images.githubusercontent.com/13686399/58724983-d267e980-8392-11e9-9fe1-96c0697b1890.png)

New:
![image](https://user-images.githubusercontent.com/13686399/58724991-d7c53400-8392-11e9-9a27-962fadb313f4.png)

@BeksOmega probably from your most recent change.  Can you take a look?

**Comment by BeksOmega** [comment]
Can do!
