### ISSUE TITLE
New Field Rendering

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2530]
### Problem statement

Before the new field creation documentation goes up, I think there needs to be some guidelines for how to set up a field's SVG structure. Things like padding, spacing, etc so that people can know their fields will look good and be handled correctly.

### Example

**Note: I think this is why editable fields are acting like jackasses.**

Right now the field rendering is a bit messy and unclear. For example the [createBorderRect_ ](https://github.com/google/blockly/blob/7c5a94d0d9642991abb0de48db0049d8d7fc3d1a/core/field.js#L259)function:
```
Blockly.Field.prototype.createBorderRect_ = function() {
  this.borderRect_ = Blockly.utils.createSvgElement('rect',
      {
        'rx': 4,
        'ry': 4,
        'x': -Blockly.BlockSvg.SEP_SPACE_X / 2,
        'y': 0,
        'height': 16,
        'width': this.size_.width + Blockly.BlockSvg.SEP_SPACE_X
      }, this.fieldGroup_);
};
```
References [Blockly.BlockSvg.SEP_SPACE_X](https://developers.google.com/blockly/reference/js/Blockly.BlockSvg#.SEP_SPACE_X), which is documented as "Horizontal space between elements." But if you remove references to Blockly.BlockSvg.SEP_SPACE_X:
```
Blockly.Field.prototype.createBorderRect_ = function() {
  this.borderRect_ = Blockly.utils.createSvgElement('rect',
      {
        'rx': 4,
        'ry': 4,
        'x': 0/*-Blockly.BlockSvg.SEP_SPACE_X / 2*/,
        'y': 0,
        'height': 16,
        'width': this.size_.width/* + Blockly.BlockSvg.SEP_SPACE_X*/
      }, this.fieldGroup_);
};

Blockly.Field.prototype.updateSize_ = function() {
  var width = Blockly.Field.getCachedWidth(this.textElement_);
  if (this.borderRect_) {
    this.borderRect_.setAttribute('width',
        width/* + Blockly.BlockSvg.SEP_SPACE_X*/);
  }
  this.size_.width = width;
};
```
You can see that it is /actually/ being used as padding:
![Rendering_BorderX](https://user-images.githubusercontent.com/25440652/58762861-ec2b3d00-8508-11e9-974b-9db5a7acc167.jpg)

### Problem Statement Continued

Here's an initial list of things I think need to be decided:
- [ ] Horizontal Padding
- [ ] Vertical Padding
- [ ] Who handles padding
  - borderRect_
  - all "child" elements (not actually children of borderRect_)
  - add some 'padding element' that offsets all the "children"
- [ ] Probably some other stuff...?

Also I think the field CSS could use a bit of a refactor. For example I believe once the clickHandler_ stuff gets implimented, the editable vs non-editable CSS will break.

### Additional information

I don't know whether this should go in before or after the new rendering, but I wanted to put it on your radar because I think it does need to go in before the field creation docs are released.

**Comment by RoboErikG** [comment]
Probably after the new renderer so we can standardize all of those properties more easily. Thanks for writing this up!

**Comment by akinariobi** [comment]
Can I take this?

**Comment by rachel-fenichel** [comment]
@akinariobi No, this one is related to the new rendering code and is still changing significantly, so we're not ready for writing out these guidelines.

**Comment by RoboErikG** [comment]
@rachel-fenichel

**Comment by rachel-fenichel** [comment]
I think this is actually done now--Beka documented all of the internal things (such as text content and background rectangles) and fields are no longer responsible for spacing in either direction.  Now it's just "A field attaches everything to a single root SVG group, reports a bounding box size, and draws things only inside that box."
