### ISSUE TITLE
Code: add line numbers

### ISSUE THREAD

**Issue by SebCanet** [google/blockly#2533]
### Problem statement

When opening div with code translated, I would like to see line numbers. I tried to modify th prettify call but I cannot pbtain more than colors....

### Expected Behavior

Starting each line of code with its number.

### Actual Behavior

All code is writtent without it.

### Steps to Reproduce

Open demos -> code and look at each code translation.

### Operating System and Browser

Any webbrowser on any OS.

### Additional Information

Many thanks!!!

**Comment by RoboErikG** [comment]
The code demo is just demonstrating how to use the code generators. If you want to use it for more than that you'll need to make your own modifications.

If you want to do this yourself I'd suggest changing text box or the page around the code, not the generated code. That way the numbers wouldn't be part of the code that was run, just part of the page display. One way you could achieve this is to add a second text box to the left of the displayed code that has the same size of font and just contains line numbers.

**Comment by SebCanet** [comment]
The aim is use prettify, not ask for a global enhancement of Blockly.
Add second text box is not a very good solution...I would like to see something like in Github.
