### ISSUE TITLE
Shadow blocks shouldn't hide blocklyPathDark

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2535]
Shadow blocks look too small because their dark path is hidden (`display: none`) instead of displaying with the shadow color.

This shows up on develop but not master.

I don't know how this will interact with themes.

**Comment by RoboErikG** [comment]
My vote is for setting the border colour using [getColourShadow](https://github.com/google/blockly/blob/develop/core/block.js#L889) for now.
