### ISSUE TITLE
Uncompressed Mode - Error using dynamics variables

### ISSUE THREAD

**Issue by ufalak** [google/blockly#2536]
If i include in my toolbar the use of dynamics variables, then i switch to use uncompressed mode of blockly.

I get a javascript error: 

> Uncaught TypeError: Unknown block type: variables_set_dynamic
>     at Blockly.BlockSvg.Blockly.Block (block.js:167)
>     at new Blockly.BlockSvg (block_svg.js:100)
>     at Blockly.WorkspaceSvg.newBlock (workspacesvg.js:623)
>     at Object.Blockly.Xml.domToBlockHeadless (xml.js:634)
>     at Object.Blockly.Xml.domToBlock (xml.js:549)
>     at Object.Blockly.Xml.domToWorkspace (xml.js:432)

**Comment by rachel-fenichel** [comment]
Sounds like you need to include `blocks/variables_dynamic.js`

**Comment by Qura-tul-ain** [comment]
How I can add block of new type in blockly code? ,i want to add motion blocks like move forward ,move backward etc.

**Comment by rachel-fenichel** [comment]
Check out the documentation on [custom blocks](https://developers.google.com/blockly/guides/create-custom-blocks/overview).
