### ISSUE TITLE
Shadow blocks sent to trash

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2538]
### Problem statement

Overwriting a shadow block results is trashcan activity.

### Expected Behavior

Open playground.
Drag math "+" block onto workspace.
Drag math "123" block into "+" block.
Trashcan should not change.

### Actual Behavior

Trashcan lid tilts and empty flyout appears when it is clicked.

**Comment by BeksOmega** [comment]
Question: Is there ever a case where a non-shadow block is the child of a shadow block? If so that will make this fix a bit more complicated.

**Comment by RoboErikG** [comment]
Nope. Non-shadows are explicitly not allowed to be children of shadows.
