### ISSUE TITLE
Dragging on touch IE

### ISSUE THREAD

**Issue by carlosperate** [google/blockly#254]
Dragging blocks or the workspace using touch in Internet Explorer is not really working. It gives the impression that the touch even is caught instead by the "browser behaviour" (page scroll, switch apps/tabs).

Very similar to what was described in https://github.com/google/blockly/issues/40 a while ago, however since that seemed to be fixed at the time by https://github.com/google/blockly/pull/41, I though this should go on separate issue.

The microbit blocks implementation does not exhibit this issue, maybe @msprotz could give us some insight?

Tested on Win10x64 on a touch screen laptop, and Win8.1x32 on a tablet.

**Comment by msprotz** [comment]
Hmm that's a good question. I'm no longer following our micro:bit Blockly integration, but git tells me that no one refreshed our version of Blockly since Nov 19th, so chances are the version from back then was pretty stable and worked for us?

**Comment by carlosperate** [comment]
Thanks @msprotz, we can then look at the commits from that date to see what might be causing this issue.

**Comment by pelikhan** [comment]
I have a fix that simply involves testing for pointer events support and replacing the TOUCH_MAP array.

You also have to disable the tap-hold gesture using css.

```
        if (window.navigator.pointerEnabled) {
            (Blockly.bindEvent_ as any).TOUCH_MAP = {
                mousedown: 'pointerdown',
                mousemove: 'pointermove',
                mouseup: 'pointerup'
            };
            document.body.style.touchAction = 'none';
        }
```

**Comment by pelikhan** [comment]
@carlosperate The fix was tested on various Windows 10 device successfully.
