### ISSUE TITLE
Insertion Marker Rendering Error

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2556]
### Problem statement

If a block has an input (dummy, value, or statement) with any field appended to it, and then another input (dummy, value, or statement) with an image field appended to it, the insertion marker will be wider than expected.

![Insertion Markers](https://user-images.githubusercontent.com/25440652/59148361-d4e2c880-89bc-11e9-8047-a5e809d97f46.gif)

### Expected Behavior

The insertion marker should be the size of the block.

### Actual Behavior

The insertion marker is larger.
![InsertionMarker_Larger](https://user-images.githubusercontent.com/25440652/59148348-9fd67600-89bc-11e9-9f5d-b13bd86caf50.jpg)

The size of the insertion marker is not dependent on the size of the image.

### Steps to Reproduce

1. Add the following blocks to the test blocks file.
```
Blockly.Blocks['rendering_error'] = {
  init: function() {
    this.appendDummyInput("NAME")
      .appendField("Text");
    this.appendStatementInput("NAME")
      .appendField(new Blockly.FieldImage(
        "https://www.gstatic.com/codesite/ph/images/star_on.gif",
        45,
        45,
        "*"));
    this.setColour(230);
    this.setPreviousStatement(true);
    this.setNextStatement(true);
  }
};


Blockly.Blocks['no_rendering_error'] = {
  init: function() {
    this.appendStatementInput("NAME")
      .appendField(new Blockly.FieldImage(
        "https://www.gstatic.com/codesite/ph/images/star_on.gif",
        45,
        45,
        "*"));
    this.setColour(230);
    this.setPreviousStatement(true);
    this.setNextStatement(true);
  }
};
```
2. Load the following XML to the playground.
```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="controls_if" id="f5)j/J^)c;^)!wWWlfb^" x="10" y="10"></block>
  <block type="rendering_error" id="GWZP|Dohar%1C{0x(+G$" x="10" y="125"></block>
  <block type="no_rendering_error" id="AW9%H{]Fhy;r3Q8fj@j{" x="10" y="250"></block>
</xml>
```
3. Drag the top "star" block into the if statement, observe how the insertion marker is extra wide.
4. Drag the bottom "star" block into the if statement, observe how the insertion marker is the correct size.

### Operating System and Browser

I am assuming this is not browser specific (reproduced on chrome and firefox).

### Additional Information

Found because of [this ](https://otterserver.com/blockly-class-expression/)lovely website. Drag an Expression > Set Opperations > Union block into the Class Expression block.

Maybe related to #2314? But I'm not receiving errors.

**Comment by moniika** [comment]
This will probably be fixed by the new renderer.

**Comment by RoboErikG** [comment]
oh, I gave @moniika bad info. The new renderer won't fix this because the text field on the insertion marker is being set to the image source string. It is indeed the same root issue as #2314

**Comment by RoboErikG** [comment]
Changing InsertionMarkerManager.createMarkerBlock_ to check for a name before setting a copied field's value would probably fix this, but someone would need to check that.
