### ISSUE TITLE
there is a exception (workspace is undefined) in the xml.js while using the compressed version

### ISSUE THREAD

**Issue by a49594a** [google/blockly#256]
`Blockly.Xml.blockToDomWithXY = function(block) {
  var width;  // Not used in LTR.
**  if (workspace.RTL) {
    width = workspace.getWidth();
  }**
  var element = Blockly.Xml.blockToDom(block);
  var xy = block.getRelativeToSurfaceXY();
  element.setAttribute('x',
      Math.round(block.workspace.RTL ? width - xy.x : xy.x));
  element.setAttribute('y', Math.round(xy.y));
  return element;
};
`
the workspace is undefined while using the compressed version

**Comment by NeilFraser** [comment]
Sorry about that.  Fixed.  Thanks!
