### ISSUE TITLE
text_append block shows all variables in dropdown menu

### ISSUE THREAD

**Issue by duzc2** [google/blockly#2561]
### Problem statement
text_append block shows all variables in dropdown menu.

### Expected Behavior
shows only untyped and text variables

### Actual Behavior

text_append block shows all variables in dropdown menu.

### Steps to Reproduce
create a number variables,and text_append block. the variable shown in the dropdown menu.

**Comment by RoboErikG** [comment]
By default Blockly only uses untyped variables and there's no concept of a 'text' type. If you're using typed variables you need to create your own versions of variable blocks with the desired type restrictions.
