### ISSUE TITLE
Remove getCorrectedSize

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2562]
`getCorrectedSize` is a function defined on fields and icons to bridge the gap between old and new rendering: we cannot make changes to `getSize` to make new rendering work without breaking old rendering.

Many implementations of `getCorrectedSize` return the size of the field with some offset in X and Y.  We should be able to remove those offsets in pairs: in the code that made them necessary and in `getCorrectedSize`.

In the best case, we'll entirely remove `getCorrectedSize` and just use the bounding box of the `svgRoot`, as @BeksOmega prototyped here: https://github.com/google/blockly/compare/render/collab...BeksOmega:fixes/getCorrectedSize

This issue should not be worked on by external contributors until new rendering has landed.

**Comment by rachel-fenichel** [comment]
Not actually closed: still need to handle icons.

**Comment by Shivansh2407** [comment]
Can I work on this @rachel-fenichel ? Also Can you let me know what exactly is needed to be done here ?

**Comment by rachel-fenichel** [comment]
@Shivansh2407 this isn't a great first bug, but we have a lot of [help wanted](https://github.com/google/blockly-samples/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues on blockly-samples that may be a good place to start. What sort of issue are you looking for?

**Comment by gonfunko** [comment]
`getCorrectedSize()` appears to have been fully removed.
