### ISSUE TITLE
Make travis test errors easier to read

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2595]
### Problem statement

The majority of tests we're running on Travis generate html pages that make it easy to read the tests when you open the generated page. When these get viewed on Travis, though, you end up with lots of html formatting text that obscures the problem and makes it hard to quickly see which tests failed.

It would be nice if our tests generated sections specifically for Travis' logging or were otherwise made more readable when viewing the results on travis.

**Comment by moniika** [comment]
Goal to make travis results easier to read so you don't need to run tests locally in order to determine which test failed.
