### ISSUE TITLE
Previously partial XML parsing failure becomes absolute failure

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2600]
We may not need to worry about this case, but I want to mention it.
I found a case where we used to parse as far as we could and then fail, and now fail early.  It's malformed XML.

The XML is at the end of the issue. 

### What it looks like
On the old playground it looks like this:
![image](https://user-images.githubusercontent.com/13686399/60377439-e58acb00-99cb-11e9-8185-87de73879849.png)

On the new playground it fails to parse.

The intent was for it to look like this:
![image](https://user-images.githubusercontent.com/13686399/60377444-f4717d80-99cb-11e9-95db-a68c94b6c4bd.png)

### The error
It fails in parsing.  It's a silent failure on the playground, but inside it says that it has an error parsing an attribute name.

The problem is this line:
`<shadow type="text"`, which is missing a close `>`.

```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <variables>
    <variable type="" id="YUz?xxnE}SFx_,jmW#s;">item</variable>
  </variables>
  <block type="text_append">
    <field name="VAR" id="YUz?xxnE}SFx_,jmW#s;" variabletype="">item</field>
    <value name="TEXT">
      <shadow type="text"
        <field name="TEXT">one</field>
      </shadow> 
    </value>
  </block>
</xml>
```

**Comment by NeilFraser** [comment]
+1 for catching bugs early.
