### ISSUE TITLE
Add a last outline block in an inline one

### ISSUE THREAD

**Issue by ufalak** [google/blockly#2604]
In a block configured "inline" i need to add a last block with outline style to continue the "programming line".

**Comment by RoboErikG** [comment]
This seems like you're having trouble doing something, but I'm not sure what. Please ask on [the forums](https://groups.google.com/forum/#!forum/blockly) and provide more information about what you're trying to do and what you've already tried, thanks!

**Comment by ufalak** [comment]
Yes, but its something that is not possible to do now.

In a block like this one:
![image](https://user-images.githubusercontent.com/19731415/60467089-f33e8b80-9c2b-11e9-964e-44fdc4eedfc3.png)

i need to add a right conector "outline" to continue the line.
So im requesting if its possible to add this functionality

**Comment by RoboErikG** [comment]
Ah, interesting. We probably won't get to it anytime soon, but reopening as a feature request. Thanks for clarifying.

**Comment by maribethb** [comment]
Closing this as a duplicate of #216

**Comment by linonetwo** [comment]
I think that issue is not as clear as this one, it seems focus on "change line" instead of "outline last input".
