### ISSUE TITLE
Insertion markers bypass movable/deletable checks

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2616]
### Problem statement

Insertion markers can disconnect blocks that are marked as not movable. See [this thread](https://groups.google.com/forum/#!topic/blockly/o8YJWUbzegY) for a repro case.

### Expected Behavior

Insertion markers should not disconnect blocks with movable=false.

### Actual Behavior

Insertion markers disconnect non-movable blocks.

### Steps to Reproduce

1. Create a workspace with two non-movable blocks attached inside a third block.
2. Drag another block across the connections.

### Stack Traces

```
Replace with error stack trace.
```

**Comment by BeksOmega** [comment]
Fixed, possibly by https://github.com/google/blockly/pull/6800
