### ISSUE TITLE
Add Dark Mode [FEATURE REQUEST]

### ISSUE THREAD

**Issue by TheBrokenRail** [google/blockly#2639]
This would make the workspace and toolbox darker colors.

https://material.io/design/color/dark-theme.html

**Comment by RoboErikG** [comment]
Note, this would involve some work in themes to make additional parts of the UI customizable in themes. Currently we only support toolbox category and block colours.

**Comment by TheBrokenRail** [comment]
Could this be separate from the existing theme API, so every theme does not have to have dark and light variants. The dark mode should just change the toolbox background to be darker, make the workspace background black, and make the images work on the new background.

**Comment by RoboErikG** [comment]
Out of curiosity, what's the issue around making dark and light themes? Are you expecting to have lots of color variants that work equally well on light or dark backgrounds?

**Comment by TheBrokenRail** [comment]
I'm embedding Blockly into a WebView in an Android app, and want Blockly to have a dark mode since the rest of the app has one.

**Comment by RoboErikG** [comment]
But what's the issue with us implementing as part of the theme? Both themes would be able to refer to the same set of block colors and have distinct background/toolbox colors.

**Comment by TheBrokenRail** [comment]
Mostly, it would be hard for theme developers to have to create two themes instead of one.

**Comment by alschmiedt** [comment]
Closing this since we now have a dark theme found [here](https://github.com/google/blockly/blob/master/core/theme/dark.js). 

<img width="440" alt="Screen Shot 2020-01-23 at 10 22 20 AM" src="https://user-images.githubusercontent.com/23059043/73012033-4d6e8c00-3dca-11ea-87e5-58b632c103d2.png">
