### ISSUE TITLE
Angle Field Doesn't Handle Touch Input Correctly

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2642]
### Problem statement

It seems like it's not capturing the input correctly so it's allowing scrolls? Not sure.

### Expected Behavior

I should be able to drag the angle picker without it getting "stuck"

### Actual Behavior

The angle picker gets stuck.
![AngleFieldInput](https://user-images.githubusercontent.com/25440652/61251321-f139f980-a70e-11e9-8b90-b701ea814920.gif)

### Steps to Reproduce

1. Load up an angle picker on mobile (preferably the blockly developer tools).
2. Try to drag it.
3. Observe how it sometimes drags the window instead of dragging the angle picker.

### Operating System and Browser

* Tablet:
  * Device: Samsung Galaxy Tab S2
  * OS: Android 7
  * Browser: Chrome
  * Version: 75

### Additional Information

Maybe related to #2316 ?

**Comment by alschmiedt** [comment]
I am not having this problem when I tested on safari or chrome for ios. However, tested on android and can confirm it is getting stuck.

**Comment by RoboErikG** [comment]
Note, Chrome 75 for Android came out on June 5th this year. We may be getting hit with some changes to gesture handling in Chrome itself.

**Comment by RoboErikG** [comment]
Possibly related to https://bugs.chromium.org/p/chromium/issues/detail?id=974823

**Comment by samelhusseini** [comment]
Fixed.
