### ISSUE TITLE
Update getPreviousBlock and getParent Documentation

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2648]
### Problem statement

It seems like getPreviousBlock and getParent act the same.

### Steps to Reproduce

1. Load the following XML to the playground:
```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="controls_if" id="1">
    <comment>1</comment>
  </block>
<block type="controls_if" id="2">
    <comment>2</comment>
  </block>
<block type="controls_if" id="3">
    <comment>3</comment>
  </block>
</xml>
```
2. Configure:
![Prev1](https://user-images.githubusercontent.com/25440652/61332545-5a863f00-a7d9-11e9-8f2d-6d28565daba5.png)

3. Run both commands: `Blockly.mainWorkspace.getBlockById('1').getPreviousBlock()`, `Blockly.mainWorkspace.getBlockById('1').getParent()`.
4. Observe how they both return "2"
5. Repeat steps 3-4 for:
![Prev2](https://user-images.githubusercontent.com/25440652/61332763-ee580b00-a7d9-11e9-9d2f-04e0e23c30c2.png)

5. Repeat steps 3-4 for:
![Prev3](https://user-images.githubusercontent.com/25440652/61332769-f021ce80-a7d9-11e9-9a13-663604b1c387.png)

5. Repeat steps 3-4 for:
![Prev4](https://user-images.githubusercontent.com/25440652/61332772-f2842880-a7d9-11e9-8fa8-648ce7eeedbb.png)

### Additional Information

* getParent has been around longer, getPreviousBlock was added recently for insertion markers.
* Obviously getParent has a confusing name.
* getParent uses caching while getPreviousBlock does not.

Idk which one should be kept and which one should be removed.

**Comment by julientype** [comment]
i think getparent  
root node <---
  childnode1
  childnode2
  childenode3

if i,m on childnode3   and call  a getPreviousBlock would be in DOM==childnode2
if i,m on childnode3 and call getparent in DOM == root node

**Comment by julientype** [comment]
`here.... to build a program like i kinda simple

<root>
<block type=  "whatever">
<input type="number">10</input>
<input type="linebrake">\n</input>
<input type="loop" >
<actions >loop \n</action >

</input>
</bock>
<root>

now to get the code out with a simply call    xml.rootnode.innerText 

node.apend toolbar.block.xml  <--- block  xml with its svga form......

svga render xml.block.view ..... 

i did not have to run any loops on blocks i just call innerText it strips out all tags.....

voila a block code application

**Comment by julientype** [comment]
here a show you more with this image.....
create table block is my workspace root node.....   the other 2 are just foating in process....
as i stated in xml each bock retains inner-text  space.... ony 1 call
look at the errors...... 
defaut_text is not connected to root-node  <--- it needs no bockToCode rendering
with a simple call to xml.root.node.innertext <--no errors would happen 
not only that but the amount of nodes you can add would 100X more this way....
also notices colum shows up in code output yet its not connected....
yes if i code it in correctly the errors will go away.....but its over kill of memory......

![image](https://user-images.githubusercontent.com/23644389/61431253-dd52eb00-a8fa-11e9-857b-779293e4f94c.png)

**Comment by julientype** [comment]
here..... is how simple this works... with just one call to the xml.root.innertext
 each block holds its own innertext space.. notice  the root-block can add at the top and bottom like every other block..... voila formatted block code made simple...
![image](https://user-images.githubusercontent.com/23644389/61434348-acc37f00-a903-11e9-8749-3cdc045013c4.png)

**Comment by RoboErikG** [comment]
@julientype don't spam other people's issues. I'm deleting your comments as they aren't helpful for this issue.

**Comment by ewpatton** [comment]
@BeksOmega This is true for statement blocks, but I do not believe it is true for value blocks. For value blocks, I would expect `getParent()` to return the block into which the value block is plugged, but I expect `getPreviousConnection()` to return `null` because the value block doesn't have a previous connection, just an output connection.

I don't know what the correct answer is if a block is defined as having both an output block and a previous connection (I think I remember Rachel saying someone did this once at last year's Blockly summit).

**Comment by RoboErikG** [comment]
@ewpatton Yep, you're right about the difference between the two methods. We should probably update the comments to be clearer.

Regarding output and a previous, that's explicitly not allowed because it causes loops in the block tree and a lot of code depends on the tree being acyclic.

**Comment by jscolega** [comment]
i rather have the actual father, why im getting the previous statement???????

**Comment by jscolega** [comment]
why this is closed?
