### ISSUE TITLE
DOM html appoint you svga rights to render events not DOM

### ISSUE THREAD

**Issue by julientype** [google/blockly#2649]
### Steps to Reproduce

1. Start by..
2. Next, do..

### Stack Traces

```
Replace with error stack trace.
```

**Comment by RoboErikG** [comment]
Could you please provide more detail on the issue and how to reproduce it?

**Comment by julientype** [comment]
svga is not DOM .... like an iframe in a  HTML page they send message to each other 
keypress is a nasty one ...is it DOM or SVGA  that govs  the  interprets to the key board actions 
key press is done not by DOM but the SVGY engine
so the keyup even is sent to DOM because svga is done rendering key press event....
this is where a validate event can fire   to DOM it cant be done by both to render a keypress events it just dispatch to the other  by a key up event that svga cars nothing about yet DOM does  ... 
keyboard  press can only be done by one.... DOM vs  svga engine....  pick

**Comment by RoboErikG** [comment]
I'm still not sure I follow.

What are the steps that would cause an issue? Create an SVG with ...?

Why is it an issue? It causes ...?

**Comment by julientype** [comment]
tk    i did solve it    .... it had to do with validating a text-input....
i need from the user  a to z only input at length 20 ...
what happens with the input view  will only upgrade after the lost focus of the Block not during editing of input field..... it look buggy on the user....
so the user will see   [ dfff23@4 ]  where should only be [ dfff ] yet it corrects it self   on the lost focus event
i just started testing your APIs

tk....  Julien

**Comment by RoboErikG** [comment]
Ah, that updating issue in specific is fixed in the release going out this week.

**Comment by julientype** [comment]
I found anew type of bug....
i;m running a custom generator file......
i have a root block you cant delete and the return code work grate ....
next i try drag and drop a new bock into place..... <----error 
as i select  it to  drag  its inserting its return code .........<---not good
 basically this should not happen until i drop it into place or remove..... 
 where block A  will request block B  once in place.......

  MYGenerator['column_def'] = function(block) {
  var str ='test return code';
   return str;
   };

nasty error shows up in DOM    and all i did was drag drop remove  add remove with 2 blocks......
Uncaught (in promise) DOMException

I am i missing something ???? like parent child index

**Comment by RoboErikG** [comment]
That's probably related to https://github.com/google/blockly/issues/2646 The easiest way to fix it is to check workspace.isDragging() in the code that calls the generator and to skip generating while a drag is in progress.

If you have further problems I'd recommend asking on [the forum](https://groups.google.com/forum/#!forum/blockly) and including information like

- What your setup looks like
- What you're trying to do
- The error messages or console logs you're getting
- Any code you think is related to the issue

We are faster to respond on the forums and providing a clearer explanation of what you're doing and the problem will make it easier for folks to answer your question.
