### ISSUE TITLE
blocks with relational joint setting

### ISSUE THREAD

**Issue by julientype** [google/blockly#2650]
when you create a block we need the the right to implement better relational joints...
your a parent and your only willing to let your child in thats it.... 
now your the child with a bunch of friends your parents dont want in ...
ohhh your friend of a friend your child does not want in ..
json lets us create these types of relation that basic logic cant do..
input and output is limited  its the parent that creates the joint...
you have many blocks with input yet the the parent only respects 4 out 20... the chold like 10 and the 10 like 3 or 4 other types all with sting inputs and out puts
its why you need a json joint field  letting the DOM commander set up its joint relations  with similar objects that can fit in yet reject by the list you implement as a joint index array Jason 
i as parent only want 4 child connected to me.... a simple json list to the block it self in relation to all other blocks .... drag drop check.... its not just strings or numbers but actual extended relations .....
this has to do with custom generator engines  with new blocks where we can sent  a relational joints check list....  where you have many type blocks of the same format yet you want only 1 out many you created to fit in...... 
here is what i mean.... with a json list do i need to enable and disable them each in DOM no.... i have a list i appended if your not on the list your disabled and the child has its own list and its buddies an so on ....   your joints are kinda string Boolean and numbers ///// i have 10 blocks as strings yet i only want 1 or 2 or 3 for the user to move into place... block joints  and you dont have to find them  the filter order puts them at the start... then the disable ones  .....  root node worm to filter out what the user needs to select....

**Comment by RoboErikG** [comment]
These types of issues are not useful. Please provide a clear statement of the problem and steps to reproduce.

**Comment by julientype** [comment]
here is simple block.... in SQL we use ingrate  one-to-one or one-to many

Blockly.Blocks['default_text'] = {
    init: function() {
      this.appendDummyInput()
          .appendField("default-text '")
         .appendField(new Blockly.FieldTextInput("default"), "txtTableName")
          .appendField("'");
      this.setPreviousStatement(true, "String");
      this.setColour(260);
   this.setTooltip("");
   this.setHelpUrl("");
    },
onchange: function(e) {

      try {
        if (typeof(e.element) != "undefined") {
        switch (e.element) {
          case "theme":
           // alert("a-theme")
            break;
        case "selected":
          //  alert("selected")
            break;
        case "field" :
//   alert("a-field");
            var answer =  this.getFieldValue('txtTableName');
            
           
            answer = goog.string.trimRight( answer.replace(/[^a-zA-Z_]/g, ''));
           e.newValue =answer;
           e.element.setText(answer);
           this.setFieldValue(answer,'txtTableName' );
          // alert( e.element.getText());
            break;
        case "click" :
            alert("a-click")
            
            break; 
  };
==========
resting the text input value fails....... next is the joints ... by default  you control joints .... it has to do with enabling and disabling other blocks in tool drag and drop bin.....
like this....
 this.sub-joint-blocks-are(block1 , block2 , block10);

the worm code would simply check all open slots from it root block downward checking the joint list also good for drag and drop.... is it in the list yes or no and null list would let normal default connectors work....

**Comment by RoboErikG** [comment]
It sounds like what you want to do is have better control over toolboxes and enabling/disabling blocks. We have APIs for all of this. The way you seem to be asking to do it is by handing dom manipulation yourself. This is part of the core functionality in Blockly and overriding dom handling is not a use case we will support, sorry.

Dynamic toolboxes: https://developers.google.com/blockly/guides/configure/web/toolbox#dynamic_categories

Per block state: https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#per-block_configuration

Custom fields: Coming soon (this week or next week)!
