### ISSUE TITLE
Undoing a midstack delete hides blocks

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2660]
### Problem statement

If you delete a block in the middle of a stack and then undo the delete the blocks after the deleted block are hidden.

### Expected Behavior

Undoing a delete looks just like before the delete

### Actual Behavior

Blocks disappear but still exist

### Steps to Reproduce

```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="text_print" id="!22zy!$0oSJPOfUO~A@!" x="113" y="237">
    <value name="TEXT">
      <shadow type="text" id="e%VoIKTYc_a$f{brMJ`]">
        <field name="TEXT">1</field>
      </shadow>
    </value>
    <next>
      <block type="text_print" id="wtH5!1%|a84?rir=orr?">
        <value name="TEXT">
          <shadow type="text" id="#iDZLUyZ.4FHb@F)_o?1">
            <field name="TEXT">2</field>
          </shadow>
        </value>
        <next>
          <block type="text_print" id="|WD@N-m73;V*yj8eS6Pe">
            <value name="TEXT">
              <shadow type="text" id="|!#ov}.]3Rw5_v_t.2s?">
                <field name="TEXT">3</field>
              </shadow>
            </value>
          </block>
        </next>
      </block>
    </next>
  </block>
</xml>

```
1. Import the xml above into the playground
2. Delete the middle block
3. Undo the delete

### Stack Traces

```
Replace with error stack trace.
```

**Comment by RoboErikG** [comment]
Possibly related to #2632

**Comment by BeksOmega** [comment]
@RoboErikG I traced this back to the new connect and disconnect overrides on the rendered connection. Do you want to take it from there? or do you mind if I keep lookin' into it?

**Comment by RoboErikG** [comment]
heh, I was pretty sure it was related to my change but I hadn't had a chance to confirm. If you've got an idea feel free to work on it, otherwise we'll probably get to it tomorrow morning.

**Comment by BeksOmega** [comment]
I looked into it a little, but I don't know enough about this system to feel safe touching it right before a release hehe. I'll let you guys grab it.
