### ISSUE TITLE
Here is a live example of generator

### ISSUE THREAD

**Issue by julientype** [google/blockly#2665]
You cannot teach HTML  like this until 2 features are fix...

http://blocklyhtml.zgtm.de/

try it out and look at the render code window or HTML window.....
now move a block out and in..... the code still shows and it effects what the kid will see....
next is to pull out a child block from its parent......
if i pull the top child out the others pop out also....<-no good
it should pull out like the last child block dose....

you need a root render connected nodes......

HTML render for the child would remove a button and its gone. out of the view pop it back in and it shows up again thats how the child will learn how to code

**Comment by julientype** [comment]
let do a drag drop connect operation with a do loop .......
open live sample....
http://blocklyhtml.zgtm.de/
you will see a block call content ...... 
now go connect your do-loop from your script category and pops in<---not good
this why you have xml tool file for to govern to the output.....
can html category block accept a do loop under scripting category<----no
under tool box governing rule it would not plug in unless you have script block-tag 
i dont do drag and drops Blockly does base on my programmable xml layout
before drop check what?????  the target  block category.... it dont fit....

like i said this is grate sample to explain blockly generator code  and its effect on  rendered output

**Comment by julientype** [comment]
to understand a a blocly type program you need to understand your objection... 
html is ASCII to graphics  your not html your  graphics to ASCII 
i as a user program  i care about  2 things from you..... graphics to xml to ASCII
ok 3.... yet i need to see default values feed it data so we  get 4 ....  like drop down or check box within block  it self......
its just a little error with my logic  3 ... 4  yet i ask for 2 to move data around to be corrected to produce what  ASCII  from a formatted xml file ....

Block.insert  this block
value 
value
ohh events to its block change.... 
 feed it data... for what
to get the XML data  ASCII  text out....

**Comment by julientype** [comment]
category tool bar.....with a root node with 4 open slots how many tool bar blocks can be activated and filtered into position base on my ability to set up xml tool bar attributes
if you fave no open slots left what blocks can you feed the user.. none....
pull a block out what blocks do you grant.... i dont do this code nor should i other then setting up category index array  that Blockly check in the xml tool structure ... 
a circuit broad hand full of logic block to build a board you fave that logic....right now integrate with a category structure  and building blooks become easy  .. all gov by the tool bar xml array

**Comment by RoboErikG** [comment]
@julientype I'm sorry, but I don't think any of us can help. If you find clear bugs in our implementation that you can provide simple steps to reproduce please let us know by filling out the bug template, but please stop filing long form issues like this, we will not look into them.
