### ISSUE TITLE
Text is mismeasured on IE11 and Edge

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2671]
### Problem statement

Some fields containing text don't have enough space in IE11 and Edge.  This has come up in the past, usually because they return 0 for the width of the field when hidden.  It usually means that the width is getting measured and cached while hidden and then failing to be remeasured when shown to get a real value.

### Expected Behavior
Fields should have space for the text.

### Actual Behavior
![image](https://user-images.githubusercontent.com/13686399/61553329-04024600-aa0f-11e9-8425-23488ee27295.png)

### Steps to Reproduce
Open the playtground in IE11 or Edge--the release candidate is currently hosted [here](https://rachel-fenichel.github.io/blockly/tests/playground.html).

### Operating System and Browser

* Desktop Firefox
* Windows Internet Explorer 11
* Windows Edge

### Additional Information

This is release blocking.

**Comment by BeksOmega** [comment]
@rachel-fenichel I have family activities this afternoon, so I won't be able to grab this.

**Comment by BeksOmega** [comment]
Note: I'm not getting the same behavior from dropdowns as shown in the issue.
![TextSizing](https://user-images.githubusercontent.com/25440652/61560239-93642500-aa20-11e9-8109-a4f445b32153.png)
Tested on the release candidate site.

**Comment by alschmiedt** [comment]
Looks like firefox is having the same problem. Also I think the dropdowns are only having the problem when they are imported from xml.

**Comment by rachel-fenichel** [comment]
Another detail: it's only on child blocks.  Whether the child is a shadow doesn't matter.

That also explains why you're not seeing it on that dropdown, Beka, and it why it doesn't show up on the field demo blocks.

So maybe child blocks aren't kicking their fields to rerender properly?

Or, possibly, there's somewhere where we're still trying to set the width to 0 instead of setting `isDirty`

**Comment by rachel-fenichel** [comment]
More debugging:
`getComputedTextLength` is returning 0 when the field is first rendered.  Maybe we're calling it earlier now than previously?

**Comment by RoboErikG** [comment]
Somehow this is caused by https://github.com/google/blockly/pull/2003 so I'll be reverting that change and maybe we'll try again next quarter.
