### ISSUE TITLE
Toolbox buttons on the playground don't work in IE11

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2672]
### Problem statement

Clicking flyout buttons in the playground does nothing on IE11 on the July 2019 release candidate.

### Steps to Reproduce
https://rachel-fenichel.github.io/blockly/tests/playground.html

Open the playground in IE11, go to test blocks, and click some buttons in the flyout.
There is a warning in the console, saying that buttons should have callbacks.
They seem to work in other browsers.

### Operating System and Browser

* Windows Internet Explorer 11

### Additional Information

This is probably release blocking.

**Comment by alschmiedt** [comment]
It looks like it was doing this in master as well.

**Comment by samelhusseini** [comment]
This bug has been around forever. 
IE doesn't like cases in the xml, so it converts it all to lowercase. 
<img width="555" alt="Screen Shot 2019-07-26 at 10 53 16 PM" src="https://user-images.githubusercontent.com/16690124/61990595-36580880-aff8-11e9-8c63-8697293d883f.png">

"callbackKey" won't exist, but "callbackkey" will. 
Here's an easy fix that won't break backwards compatibility: https://github.com/google/blockly/pull/2719

**Comment by samelhusseini** [comment]
FYI, this only affects flyout buttons that are authored in xml. When you set the attribute in JS it maintains the case, and hence Variable / Procedure flyout buttons work today.

**Comment by samelhusseini** [comment]
Fixed by #2719
