### ISSUE TITLE
Undoing connecting a collapsed block causes positioning issues

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2675]
### Problem statement

If you connect a collapsed block between blocks such that some blocks get added into the collapsed group, then undo it child blocks get positioned incorrectly.

### Expected Behavior
Undo should position blocks correctly.

### Steps to Reproduce

```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="logic_ternary" id="4H=DIk|U}:}a(%z9!(t:" x="112" y="113">
    <value name="IF">
      <block type="logic_negate" id="oxQ5,hS7Y,`7pnX=(xEf">
        <value name="BOOL">
          <block type="logic_negate" id="$}7#Y8YE*umkz%LV/bC{"></block>
        </value>
      </block>
    </value>
  </block>
  <block type="logic_negate" id="1kC@XKq]HI9~HDwucD0D" collapsed="true" x="65" y="268">
    <value name="BOOL">
      <block type="logic_negate" id="L2);`8=$z0u%7/{PDmka"></block>
    </value>
  </block>
</xml>
```

1. Load the above xml into the playground
2. Drag the collapsed block to the first test connection (consuming the two 'not' blocks)
3. Undo

Note the last not block will get rendered somewhere random.

### Stack Traces

```
Replace with error stack trace.
```

### Operating System and Browser

Desktop Chrome

**Comment by alschmiedt** [comment]
Update:
I couldn't repro this exact case, but am seeing the issue if I follow the steps below:
1. Load the above xml into the playground
2. Drag the collapsed block to the first test connection (consuming the two 'not' blocks)
3. Expand the block
4. Undo

**Comment by alschmiedt** [comment]
Closing as I can no longer repro either case.
