### ISSUE TITLE
where XML  id get confusing  id="4H=DIk|U}:}a(%z9!(t:" x="112" y="113"

### ISSUE THREAD

**Issue by julientype** [google/blockly#2677]
You have your generator it needs the crazy id ... should generator Id show-up in XML programming layer<---no
XML is an application description  language to the generator..... 

You want it simple to program so 75% of your API are simple XML attributes the generator will read
xml root work space attributes govern the work space.
xml category attributes govern the tree
xml block attributes govern the bock
xml await connection bock appending space file...

in dom i can append  an li tag to a list ul and remove them   
the generator would behave the same way dom operation works on tree structure....

now to teach the logic out is simple.... its just like dom HTML yet its  Block xml attributes 
you have your tool xml file  your workspace xml and your await connection xml space file....

these are just append, cut , drop,create and move operation <---generator render view layers and code

would a developer user need to understand a generator id....<- no
hash table <--your generated id  
my xml ID is set by me...... index array ID just like you do in DOM - scripting 
once i set an id in DOM i use it in code ......

when i set the ID i can reference it an input block item in the block code area.  
alert(  to complete the task you need ID block name because we found none in your layout)
dont forget DOM needs to read this type of ID attribute <---they read all ID attributes as its browser generator and ignore other types....  its assigned to the DOM  viewer  or call it BlockID would be ignored 

in a bowser div id="xyz"
now in script the browser created a reference object to script
xyz.value <---it automatic create a script object in DOM    to avoid this never use the ID attribute 
like memory leak you told DOM to create script objects to monitor

you have to respect browser DOM or it wont respect you.....

for android i believe it 5.0 and up and 6 is better they support full DOM

ohhhh one more.....
"4H=DIk|U}:}a(%z9!(t:" x="112" y="113"
this is bad formatting for DOM XML id attribute 
"4H=DIk|U}:}a(%z9!(t:' x='112' y='113'"<--- and still should not be used
 you cant mix json with xml as an id..... dom will get mess up in indexing your values 
"4H=DIk|U}:}a(%z9!(t:" <--- even this as an Id is not good its un readable as a XML  application attribute 

i would actually drop jason in the xml block build layer  it just a boot script .langue used for other type of operations where you need tiny foot print and speed to move app info settings around ..
its like trying to run html with dom-xml or json to get same results<--they would never support it and over code the app.... 
JSON Message Interpolation <----gone its just attach and detach xml nodes you built to an xml file and you as engine developer are no longer testing 2 sets of logic and that both render the same...

when you have 3 xml files  the user index your block joins  for you.... its why you dont put everything in one xml file it reduces the amount of code to manage ....
since this is a web app use the power of the container your in.....
parser = new DOMParser
doc = parser.parseFromString(string, "application/xml")
or you end up with 2 copys    what ever you throw at dom it requires to index it..... 
a pre compile engine in every browser......  no Json just xml to java to svg rendering 
this engine is good for about 100,000 speed reference  
just 1 call to root node workspace and out comes your code..... your blockly app edited its innertext  checking variables by JavaScript  as programmer i can set.... the app code you need keeps shrinking ... because your using the power of the container your in..... a browser

Undoing connecting a collapsed block causes positioning issues
DOMParser    <---- it index's all the complex relational joins base-on block insertion point by the user and block type xml definition 
if you have nested child blocks an want to remove middle child then you simply remove it  out of the DOMParser and run a call  re check svg to cleanup  by its getparent id   .... no such blocks in the list please redraw ...... your svg block is no different then a html input statement  tag ......  so now your svg draw layer is govern by the DOMParser in memory xml file you loaded..... and your db file is governing undo and redo to the DOMParser who will tell svg class layer what to draw.... your db file cant do joints like xml can and nor can jason or you end with very complex calls. and adding feature becomes easy its govern by xml attributes .....   your api to the developer  
workspace .....Prepend a common prefix onto each line of code.
DOMParser would not do this at a workspcace level for each block but at the block creation level setting up innnertext format.... to insert an if block the block holds prefix input added to its innertext....
then the root node innertext will pickup all formats... i just shrunk your code required to build a statement ..... and the developer is now in control at the block creation level not the workspace to make all the blocks fit.  { <---prefix  starts the block innertext and ends the block --->} the input field has its own innertext space and can also have a prefix "  and "  or ' and '..... 1 call to get your code out.... user just enters data names or numbers.   done... delete the node and the innertext is gone and all its child nodes....  render svg and update
code= workspace.root,node,innertext    
see json is not very good block building other then transferring info to svg or to db from the DOMParsing file as a small foot print  this because json is no good at handling a prefix without braking the json format so you had to add it to the workspace where xml innertert can retain and move values around with simple append node array of nodes.... and json is grate for the db it only needs to record user input to a selected xml tool block with the embeded prefix and user is only playing with numbers and text to strore as an undo command thats injected back into the xml block and json can be formatted to deal with complex relation xml offers.... as a transponder format language to svg and db

====the key to DOMParsing file is to create 3  of them each will get allotted memory and keeping its index small  will speed up referencing mush like 3 tab bars in a browser.... no need to store x y in it when the svg dose the calculation and svg cares not about prefix being stored in the xml block 

=== prefix syntax form one language to the other have verification problems to solve this is to create different category .... Java insert or c++or c     so the prefix should not be set from workspace but set in the xml block....  basically  block building is not an  interpreter  language engine ..  like PHP 4 to 7....lol or a class constructor.....

**Comment by rachel-fenichel** [comment]
JSON is a core technology that we use.

Our XML format is intended to contain the IDs.
