### ISSUE TITLE
Block jittering on small workspaces

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2681]
Go to https://blockly-demo.appspot.com/static/demos/resizable/overlay.html
Execute on console:
```
document.getElementById('blocklyDiv').style.width = '300px';
Blockly.svgResize(demoWorkspace);
```
Drag a 'repeat' block into the workspace.

Expected: a 'repeat' block sitting serenely on the workspace.
Actual:
![5a0b340a-6f90-40e6-9e35-2d161d40b91e](https://user-images.githubusercontent.com/250480/61663681-028e8300-ac86-11e9-8558-5d80b80f90bf.gif)

**Comment by BeksOmega** [comment]
A developer could solve this by making the workspace draggable. I know that doesn't work under all circumstances (documentation comes to mind) but I thought it would be worth mentioning.
