### ISSUE TITLE
Upstream scratch-blocks fixes for workspace comments

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2724]
This is a tracking bug for multiple recent fixes for workspace comments that scratch-blocks made.  We'll want to pull these in, but it's not yet high priority.

https://github.com/LLK/scratch-blocks/pull/1970
https://github.com/LLK/scratch-blocks/pull/1967

@kchadha @picklesrus @paulkaplan Please add any that I've missed.

**Comment by rachel-fenichel** [comment]
https://github.com/LLK/scratch-blocks/pull/1971

**Comment by samelhusseini** [comment]
https://github.com/microsoft/pxt-blockly/pull/243

**Comment by kchadha** [comment]
@samelhusseini, we just looked into the same delete touch gesture bug and we ended up fixing it a slightly different way: https://github.com/LLK/scratch-blocks/pull/1970/files#diff-c7bb21e1a4838f04477d19d4b3d4e816R100

`bindEventWithChecks_` has extra flags for not capturing the touch identifier.

**Comment by samelhusseini** [comment]
Awesome thanks for pointing that out @kchadha.
@shakao FYI

**Comment by rachel-fenichel** [comment]
https://github.com/LLK/scratch-blocks/pull/1975

**Comment by rachel-fenichel** [comment]
I'm referencing this in the tracking bug for splitting out workspace comments, but closing it because the fixes are no longer directly applicable (we can't just pull them upstream, given changes since this issue was filed).
