### ISSUE TITLE
How to deal with multi-workspace and multi-toolbox?

### ISSUE THREAD

**Issue by greenSnot** [google/blockly#273]
My project has some "sprites" in "sprite panel",each "sprite" has its code(workspace) and different toolbox.
`var workspace=Blockly.inject('blockly-workspace-'+sprite_id,{
   toolbox:document.getElementById('toolbox-'+sprite_id)
})
`
The toolboxes will be converted to 'blocklyToolboxDiv' and appended to <body>  so it's hard to deal with  its workspace because they are in different dom.

**Comment by greenSnot** [comment]
I have solved it.
`
function addWorkspace(sprite_id){
    var workspace=Blockly.inject('blockly-workspace-'+sprite_id,{         toolbox:document.getElementById('toolbox-'+sprite_id) }) 
    $('.blocklyToolboxDiv:last-child').attr('id','blockly-toolbox-'+id);
}
function setActiveWorkspace(id){
    $('.blockly-workspace').removeClass('blockly-active');
    $('#blockly-workspace-'+id).addClass('blockly-active');
    $('.blocklyToolboxDiv').removeClass('blockly-active');
    $('#blockly-toolbox-'+id).addClass('blockly-active');
}

<style>
 .blockly-active{z-index:10}
</style>
`
I think it is a bad solution.

**Comment by jano42** [comment]
I suggest you to have a look at  #PR/241 

https://github.com/google/blockly/pull/241

One of the PR effect is to have one toolbox per workspace. (the div is injected in injection container).
Maybe it could solve this issue.
