### ISSUE TITLE
Replace closure toolbox categories with a custom implementation

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#2735]
**Is your feature request related to a problem? Please describe.**

We've been depending on collapsible lists from the Closure UI library for the toolbox's categories. This is one of the big remaining parts of removing Closure UI from Blockly.

**Describe the solution you'd like**

Custom toolbox categories with a well defined Blockly API. Should be compatible with existing documented APIs.

**Describe alternatives you've considered**

**Additional context**

**Comment by samelhusseini** [comment]
Consider: 
- [ ] Categories that are used as Labels or Buttons with custom callbacks.

**Comment by samelhusseini** [comment]
Resolved by https://github.com/google/blockly/pull/2819
