### ISSUE TITLE
The DropDownDiv Should Respect Toolboxes

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2744]
**Describe the bug**

The DropDownDiv can overlap the toolbox.

Bubbles (mutators, comments, etc) respect the toolbox, so the DropDownDiv probably should as well, matter of preference though.

**To Reproduce**

1. Open the playground to the test blocks page.
2. Pull out an angle test block (Fields > Default)
3. Place the angle /field/ right next to the edge of the toolbox.
4. Click the angle field to open the DropDownDiv.
5. Observe how the DropDownDiv overlaps the toolbox.

**Expected behavior**

The DropDownDiv should be shifted to avoid the toolbox.

Note that it already shifts it self to stay within the injectionDiv, just not the "workspace".

**Screenshots**

![AvoidToolbox_1](https://user-images.githubusercontent.com/25440652/62161999-28420a80-b2cc-11e9-904d-3bbc864a43ca.png)
![AvoidToolbox_2](https://user-images.githubusercontent.com/25440652/62162001-28420a80-b2cc-11e9-91ba-3bf40c2849ef.png)
![AvoidToolbox_3](https://user-images.githubusercontent.com/25440652/62162002-28420a80-b2cc-11e9-987c-f5e5b05e4529.png)
![AvoidToolbox_4](https://user-images.githubusercontent.com/25440652/62162003-28420a80-b2cc-11e9-8e4e-9266f9449dc9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75

**Additional context**

N/A

**Comment by samelhusseini** [comment]
I actually think its fine for the dropdown div to "momentarily" be on top of the toolbox. Just like the flyout is momentarily over blocks on the workspace.
My concern with avoiding the toolbox is you're much more likely to end up in cases where you resort to the fallback which in the case of your last example would be to fallback to the TOP which actually looks worse. We could prefer to avoid the toolbox if we have space, but I would definitely much rather show content on top of the toolbox than to resort to the fall back.

**Comment by rachel-fenichel** [comment]
I'm okay with the dropdown div over the toolbox, since it's fairly transient.  Also because there are already lots of branches in the positioning code for the dropdown div, and I think adding this would add more complexity for a corner case (edge case?).
