### ISSUE TITLE
Make a single field uneditable without making the whole block uneditable

### ISSUE THREAD

**Issue by Tereshka** [google/blockly#2763]
**Is your feature request related to a problem? Please describe.**

Need an opportunity to make a single field uneditable without making the whole block uneditable

**Describe the solution you'd like**
There was a topic in Blockly developers group with solution:
[https://groups.google.com/d/msg/blockly/OiUL3gzGATQ/WUadyexeBwAJ](https://groups.google.com/d/msg/blockly/OiUL3gzGATQ/WUadyexeBwAJ)

**Additional context**

It will be great to have an implementation of above solution in blockly core itself.

**Comment by BeksOmega** [comment]
Closing as a dupe of #4932 as that one has more detail.
