### ISSUE TITLE
Undo is broken with Ctrl + Z

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#2765]
**Describe the bug**

Undo'ing with CTRL + Z yields an error and doesn't undo, regardless when you call it. 

**To Reproduce**

1. Open the playground
2. Make a few changes
3. Press Ctrl + Z

**Expected behavior**

Undo the last change

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Stacktrace**

<img width="456" alt="Screen Shot 2019-08-01 at 8 42 55 AM" src="https://user-images.githubusercontent.com/16690124/62307905-5133de00-b439-11e9-85e0-fc05f18fda05.png">

**Additional context**

Checked master, only affects develop.

It appears related to this change https://github.com/google/blockly/pull/2710#pullrequestreview-269716509

**Comment by alschmiedt** [comment]
Fixed with #2766
