### ISSUE TITLE
Pinch to zoom can't be configured / turned off

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#2782]
**Describe the bug**

Pinch to zoom doesn't respect zoom options in order to figure out whether or not to zoom the workspace. 

**To Reproduce**

1. Configure the playground without any zoom options.
2. Browse to the playground on a touch device. 
3. Try to pinch to zoom the workspace
4. It works, when it shouldn't..

**Expected behavior**

I expect a developer can turn off pinch to zoom with the zoom options.

**Smartphone (please complete the following information):**
 - Device: Iphone X
 - OS: IOS 12
 - Browser: Safari

**Additional context**

Currently there is no zoom option for pinch to zoom. We have a few options: 
- We could overload wheel. 
- We could create a new option.
- We could just check for the existence of the zoom option (ie: any zoom option, enables it). 

I feel if we create a zoom option for it now, we'd have to communicate to people that they have to now opt into it through that option.

**Comment by BeksOmega** [comment]
> I feel if we create a zoom option for it now, we'd have to communicate to people that they have to now opt into it through that option.

You could also have it default to the value of `wheel`. Might not solve all cases, but it's another option.

**Comment by samelhusseini** [comment]
Yep, thats what I meant by overloading wheel :)

**Comment by RoboErikG** [comment]
Let's make it so enabling zoom enables pinch zoom and disabling zoom disables pinch zoom.

**Comment by RoboErikG** [comment]
Took another look at the APIs and realized there's no global enable/disable of zoom. It looks like the zoom controls and wheel zoom both default to false and need to be enabled explicitly. It's probably expected by a user that pinch zooming is also available if controls or wheel are enabled, so I'm updating my recommendation:

- Add a 'pinch' key to the zoom object that can be true or false.
- If the 'pinch' key is not defined, default to wheel | controls

**Comment by samelhusseini** [comment]
Fixed.
