### ISSUE TITLE
Overwriting a JSON Key is Not Consistent

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2788]
**Is your feature request related to a problem? Please describe.**

Overwriting a JSON key does not have a consistent feedback mechanism.

[Blockly.defineBlocksWithJsonArray](https://github.com/google/blockly/blob/de39d5f2d056f0f380dbbfb8f86cfa82ea449f55/core/blockly.js#L423) logs a warning.
[Blockly.Extensions.register](https://github.com/google/blockly/blob/de39d5f2d056f0f380dbbfb8f86cfa82ea449f55/core/extensions.js#L56) throws an error.
[Blockly.Field.register](https://github.com/google/blockly/blob/de39d5f2d056f0f380dbbfb8f86cfa82ea449f55/core/field.js#L72) does nothing.

**Describe the solution you'd like**

I prefer the log a warning option.

* It was stated explicitly on the [draggable number field issue](https://github.com/google/blockly/issues/1701#issuecomment-385534439) that overriding fields was an option, so I think that should be kept.
* I also wished I could override extensions when I was working on an [alternative mutators demo](https://github.com/google/blockly/issues/1845) recently, so I think that should be allowed.
* I think a similar principle applies to blocks.

**Describe alternatives you've considered**

* Throwing errors. This is annoying, if I want to override something I think I should be allowed to.
* Not doing anything. This would be fine... but I don't mind the extra "hey be careful there" of a warning either.

**Additional context**

[Applicable field registry test](https://github.com/google/blockly/blob/33cce3c8693dfd2d9a52f1d9039e4ef4eabb7250/tests/mocha/field_registry_test.js#L61)

**Comment by rachel-fenichel** [comment]
What about
- allow explicitly unregistering an existing JSON key
- log a warning if your registration overrides an existing key.

That way we don't spam warnings (the fix is to unregister first) and developers have to be clear about intent.

Argument against:
- should just not include the block definition if you are planning to override 
  - same for extension and field definitions?
- means that the order matters (but it already does)

**Comment by BeksOmega** [comment]
Not a JSON key, but renderers also support registration. #3013

As of writing, overwriting a renderer key throws an error.

**Comment by RoboErikG** [comment]
Discussed. Preference would be:

- Leave blocks with a warning.
- Add unregister methods for extensions, fields, and renderers.
- Make overriding extensions, fields, and renderers an error since that will usually be because someone copied an existing one and forgot to change the name.
