### ISSUE TITLE
Flyout Buttons with Different Font Size are Not Rendered Correctly

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2793]
**Describe the bug**

Flyout buttons accept classes. If you give this class a font-size that is different from the standard one, the button does not render correctly.

**To Reproduce**

1. Add the following css to the playground:
```
.customFlyoutButton .blocklyText {
    font-size: 30px;
}
```
2. Add the following button to the playground (any toolbox category is fine):
`<button text="test" callbackKey="" web-class="customFlyoutButton"></button>`
3. Open the flyout.
4. Observe how the button is not rendered correctly.

**Expected behavior**

The flyout button should render to have the correct padding around the text, regardless of the height of the text.

**Screenshots**

![FlyoutButton_Text](https://user-images.githubusercontent.com/25440652/62794538-37be1200-ba89-11e9-89b3-968fb13ed133.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76

**Additional context**

Thematically related to #2649, but the code is unrelated.

[This line](https://github.com/google/blockly/blob/de39d5f2d056f0f380dbbfb8f86cfa82ea449f55/core/flyout_button.js#L158) is the root of the problem.

**Comment by samelhusseini** [comment]
Thanks for filing @BeksOmega. I wanted to add that this is more of a general problem with sizing based on font size that's throughout the project. You can find similar bugs with changing the font size of the text input or the ``.blocklyText`` class.

**Comment by samelhusseini** [comment]
Fixed
