### ISSUE TITLE
blocks with hats zoom out of the toolbar

### ISSUE THREAD

**Issue by mattbishop** [google/blockly#2800]
**Describe the bug**

If your workspace is horizontal, and you have start hats turned on, zooming the workspace causes the elements without start connections to step their way out of position and eventually disappear from the toolbar.

**To Reproduce**

1. Load the attached HTML file in a Blockly environment.
2. click the zoom + button a few times
3. Then click the zoom - button a few times
4. The "procedures" block steps down and out of the toolbox view

**Expected behavior**

The procedures block should work the same way as it would without the hat, meaning it zooms in and out without disappearing

**Screenshots**

I'll add a screen cap.

**Desktop (please complete the following information):**
 - OS: Mac OS  10.14.6
 - Browser chrome 76, safari 12.1

**Additional context**

Blockly July 2019 release. Same bug appears in Scratch Blocks too.

**Comment by mattbishop** [comment]
[zoom-hat-bug.html.txt](https://github.com/google/blockly/files/3490543/zoom-hat-bug.html.txt)

**Comment by mattbishop** [comment]
![zoom-bug](https://user-images.githubusercontent.com/363909/62840844-2e81a080-bc55-11e9-82e0-548106de0d3c.gif)

**Comment by mattbishop** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>scrolling bug</title>
  <style>
    #blocklyDiv {
      height: 600px;
      width: 800px;
    }
  </style>
</head>
<script src="../node_modules/google-blockly/blockly_compressed.js"></script>
<script src="../node_modules/google-blockly/blocks_compressed.js"></script>
<script src="../node_modules/google-blockly/msg/js/en.js"></script>
<block id="toolbox">
  <block type="controls_if"></block>
  <block type="logic_compare"></block>
  <block type="procedures_defnoreturn"></block>
</block>
<body>
  <div id="blocklyDiv"></div>
  <script>
    Blockly.BlockSvg.START_HAT = true
    const blocklyDiv = document.getElementById('blocklyDiv');
    Blockly.inject(blocklyDiv, {
      horizontalLayout: true,
      toolbox: document.getElementById('toolbox'),
      zoom: {
        controls: true
      }
    });
  </script>
</body>
</html>
```

**Comment by mattbishop** [comment]
BTW, verticalLayout also behaves badly, just in a different way.

**Comment by RoboErikG** [comment]
Fixed in new renderer.
