### ISSUE TITLE
Formalize type declarations/annotations for shape objects for rendering.

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2803]
Objects like `Blockly.blockRendering.constants.PUZZLE_TAB` are used for rendering now, and should be swappable as long as we have a good description of what properties each one needs to have.  Right now that's lacking.

Here is a sample object:
```
Blockly.blockRendering.constants.NOTCH = (function() {
  var width = Blockly.blockRendering.constants.NOTCH_WIDTH;
  var height = Blockly.blockRendering.constants.NOTCH_HEIGHT;
  var innerWidth = 3;
  var outerWidth = (width - innerWidth) / 2;
  function makeMainPath(dir) {
    return Blockly.utils.svgPaths.line(
        [
          Blockly.utils.svgPaths.point(dir * outerWidth, height),
          Blockly.utils.svgPaths.point(dir * innerWidth, 0),
          Blockly.utils.svgPaths.point(dir * outerWidth, -height)
        ]);
  }
  // TODO: Find a relationship between width and path
  var pathLeft = makeMainPath(1);
  var pathRight = makeMainPath(-1);

  return {
    width: width,
    height: height,
    pathLeft: pathLeft,
    pathRight: pathRight
  };
})();
```

Notice that it evaluates immediately, so the actual object just has `width`, `height`, `pathLeft`, and `pathRight` properties for the rest of the rendering code to use.

**Comment by rachel-fenichel** [comment]
Additional note from the rendering hackathon: some shape objects call `makeMainPath` with `-1` or `1`, while others use `true` or `false`.

We should be consistent.

**Comment by gonfunko** [comment]
Closing since these are all now full Typescript interfaces in renderers/common/constants.ts.
