### ISSUE TITLE
CREATE events for shadow blocks?

### ISSUE THREAD

**Issue by tmickel** [google/blockly#281]
@NeilFraser 

We have CHANGE events for shadow blocks in develop, but no CREATE events seem to be fired when these blocks are first dragged out of the flyout. Is this an oversight, or should we be reading the field values of these blocks out of the parent block's CREATE event xml?

**Comment by NeilFraser** [comment]
When one or more blocks are created from the toolbox _one_ create event is fired.  That event may describe a large tree of blocks, including nested shadow blocks.  Here's the xml property of a trigonometry block being created that shows the enclosed shadow block.

```
<block type="math_trig" id="GKyIh]Oo[j%I#9{*P+Z~" x="9" y="172">
  <field name="OP">SIN</field>
  <value name="NUM">
    <shadow type="math_number" id="xrbb=H=LOpdyuA9(lcs_">
      <field name="NUM">45</field>
    </shadow></value>
</block>
```

**Comment by tmickel** [comment]
Ok, thanks, Neil!
