### ISSUE TITLE
Blocks with outputs misaligned in flyout

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2828]
**Describe the bug**
Blocks with output tabs are supposed to be moved left so that the blocks align based on the visible "left edge" of the block.  New rendering messed this up.

![image](https://user-images.githubusercontent.com/13686399/63062718-ba423980-beae-11e9-9219-572cebd0b458.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/13686399/63062696-abf41d80-beae-11e9-9d2a-00fb46eaaab6.png)

**Additional context**

There's a question here about whether I should offset the block by the connection width or by some startX value that can be independent from the connection width.

Something similar holds true for hats.

**Comment by RoboErikG** [comment]
https://github.com/google/blockly/issues/2800 is related to your comment about hats.

**Comment by rachel-fenichel** [comment]
#2800 is fixed by my current code, but I don't want to close it until I finish this up.

**Comment by moniika** [comment]
Fixed
