### ISSUE TITLE
Stop filtering subdirectories in the compile test script

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2838]
**Is your feature request related to a problem? Please describe.**
The compile test script (`scripts/compile.sh`) filters out subdirectories because it was designed to only include one rendering directory.

This doesn't interact well with the new pile of subdirectories in core.

It is also unnecessary now that we've decided to choose the renderer at runtime instead of at compile time.

**Comment by rachel-fenichel** [comment]
And also in build.py, actually.

**Comment by alschmiedt** [comment]
Fixed in #2842
