### ISSUE TITLE
Convert all JSunit tests to mocha

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#2870]
The jsunit tests still depend on closure for a bunch of mock functionality. As we move away from closure, we can re-implement that functionality. Instead we can move away from jsunit altogether, and adopt mocha tests for all the coverage in jsunit. 

Conversion between the two should be straightforward. We just need to make sure we don't lose test coverage. Using this issue to track this conversion: 

- [x] block_test.js
- [x] connection_db_test.js https://github.com/google/blockly/pull/2872
- [x] connection_test.js https://github.com/google/blockly/commit/1baf7d1dcf6f8e54f30b90dc6f17c061e3a7e862#diff-e69b0acbbba2a2b3df6e74941d868499
- [x] event_test.js
- [x] extensions_test.js
- [x] generator_test.js
- [x] gesture_test.js https://github.com/google/blockly/pull/2875
- [x] json_test.js
- [x] metrics_test.js https://github.com/google/blockly/pull/2871
- [x] names_test.js https://github.com/google/blockly/pull/2873
- [x] theme_test.js https://github.com/google/blockly/pull/2874
- [x] utils_dom_test.js
- [x] utils_math_test.js
- [x] utils_string_test.js
- [x] utils_test.js
- [x] variable_map_test.js
- [x] variable_model_test.js
- [x] variables_test.js
- [x] widget_div_test.js
- [x] workspace_comment_test.js
- [x] workspace_test.js
- [x] workspace_undo_redo_test.js
- [x] tests/workspace_svg/procedure_svg.js
- [x] tests/workspace_svg/event_svg.js
- [x] tests/workspace_svg/workspace_svg_test.js
- [x] tests/blocks/logic_ternary_test.js

**Comment by moniika** [comment]
We should also review the jsunit tests under tests/workspace_svg/ and either convert to mocha or remove.
