### ISSUE TITLE
Upgrading build.py to use closurebuilder

### ISSUE THREAD

**Issue by Immortalin** [google/blockly#288]
@NeilFraser are there any plans to upgrade `build.py` to use `closurebuilder` since `calcdep.py` has been [deprecated](https://developers.google.com/closure/library/docs/calcdeps)?

**Comment by NeilFraser** [comment]
At the moment I'm just leaving it since the current method works and there are higher priorities.  Though if someone wants to upgrade build.py before it breaks, that would be great.

**Comment by MarkusBordihn** [comment]
If you don't mind using "npm" instead of Python I could work on an integration over https://github.com/google/closure-builder 

I will add the online compiler in the next versions, so no Java would be required.

**Comment by Immortalin** [comment]
@MarkusBordihn that would be great!

**Comment by MarkusBordihn** [comment]
Ok, closure-builder is now supporting the online compiler as well
But as long the missing require(...) and provide(...) statements are not fix it makes no sense to start such integration.

**Comment by Immortalin** [comment]
@MarkusBordihn what needs to be done now?

**Comment by MarkusBordihn** [comment]
@Immortalin 
The Blockly team needs to decide on the following things, before I could move on.
- https://github.com/google/blockly/issues/395
- https://github.com/google/blockly/pull/366
- https://github.com/google/blockly/issues/450
- https://github.com/google/blockly/issues/448

**Comment by Immortalin** [comment]
@markusbordihn will things work if I use your fork?

**Comment by MarkusBordihn** [comment]
@Immortalin 
Maintaining a fork which include such changes would be to much manual work.
This is something which needs to be done consistently on the original source.

**Comment by samelhusseini** [comment]
Using the npm closure compiler for local builds.
