### ISSUE TITLE
Field Cursor Configuration

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2885]
**Is your feature request related to a problem? Please describe.**

It is currently unclear if you should, and how you can change the cursor for fields.

E.g:
* Can/Should you change the cursor of a field type?
* Can/Should you change the cursor of a field instance?
* Can/Should you change it dynamically (e.g. based on if the field is editable)?

**Describe the solution you'd like**

I think it would be the most flexible to say yes to all three.

* Some CURSOR properties already exist on field subclasses. One could also be added to the abstract field class. That way you won't have to dig through the css to figure out what the default cursor is.
* Add a cursor property to the opt_config of the abstract field class.  This would allow it to also be passed through the JSON Definition.
* Add a setCursor function that allows the cursor to be changed dynamically.

**Describe alternatives you've considered**

* No to all three.
* No to some and yes to some.

The abstract field class should maybe get a CURSOR property anyway though, for consistency.

**Additional context**

I've seen people setting the CURSOR property of field instances directly (on the forums), so I think there is demand for this.

This could also be handled by CSS instead of programmatically. Related: #2884

**Comment by samelhusseini** [comment]
I would generally learn towards letting developers use CSS to configure properties that are simply being set in JS on the field element, but given the legacy of this property I'm not opposed to doing all of the above.
