### ISSUE TITLE
RTL mode doesn't seem to be compatible with toolbox-less workspaces

### ISSUE THREAD

**Issue by ens-lg4** [google/blockly#29]
How to reproduce: switch on RTL mode on injection, do not create a toolbox, but pre-place some blocks on the workspace. Then drag any block and drop it back onto the workspace. The block itself and the associated cluster of its children will disappear with animation as if dropped into the trashcan.

For some reason the method Blockly.Workspace.prototype.isDeleteArea returns true in the middle of the workspace. It probably shouldn't?

**Comment by NeilFraser** [comment]
Fixed.  Thanks!
