### ISSUE TITLE
Exception when deleting an if block with the configuration open

### ISSUE THREAD

**Issue by lidavidm** [google/blockly#290]
Steps to reproduce at https://blockly-demo.appspot.com/static/demos/fixed/index.html:

1. Create an if block.
2. Click the gear icon.
3. Without closing the popup, drag the if block over the toolbox to delete it.

Result: two exceptions

Browser: Firefox Nightly (45.0a1) (`Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0`)

```
17:21:37.610 TypeError: this.block_.workspace is null
Blockly.Mutator.prototype.setVisible() blockly_compressed.js:1037
Blockly.Icon.prototype.dispose() blockly_compressed.js:880
Blockly.Mutator.prototype.dispose() blockly_compressed.js:1039
Blockly.BlockSvg.prototype.dispose() blockly_compressed.js:1119
Blockly.BlockSvg.prototype.onMouseUp_() blockly_compressed.js:1102
Blockly.bindEvent_/e<() blockly_compressed.js:1310
1 blockly_compressed.js:1037:178
```

```
17:21:37.613 TypeError: a is null
Blockly.Blocks.controls_if.saveConnections() blocks_compressed.js:42
Blockly.Mutator.prototype.setVisible/this.sourceListener_() blockly_compressed.js:1036
Blockly.Workspace.prototype.fireChangeListener() blockly_compressed.js:859
Blockly.Events.fireNow_() blockly_compressed.js:1163
1 blocks_compressed.js:42:169
```

**Comment by NeilFraser** [comment]
Sorry about that.  This was discovered and fixed a couple of days ago.  It is checked into the 'develop' branch and will be rolling out to 'master' soon.
https://github.com/google/blockly/commit/95fbc0bb49a717707b716c018f189a602964c790
