### ISSUE TITLE
Download screenshot option

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#2914]
Add an optional context menu option to download a screenshot of blocks or the workspace.
This should trigger a download of a screenshot PNG of the block stack or group of blocks.

We should also consider serializing the xml into PNG metadata:
It would also be nice if dragging that same PNG onto the workspace loaded a copy of that stack onto the workspace.
In the case that it was a workspace screenshot, perhaps it should replace the entire workspace with that screenshot source.

**Comment by JoshuaLowe1002** [comment]
Is this still being considered? Would love this feature

**Comment by rachel-fenichel** [comment]
@samelhusseini plugin candidate?

**Comment by samelhusseini** [comment]
Yes for sure. Simply adding what we have in a plugin is straightforward, however I don't think screenshot.js in Blockly is complete. For starters it doesn't support all browsers..

**Comment by rachel-fenichel** [comment]
Closing in favor of a plugin: https://github.com/google/blockly-samples/issues/249
