### ISSUE TITLE
Move bumpObjects out of Inject

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2916]
**Describe the bug**

Object (block/workspace comment) bumping logic currently lives inside of the `createMainWorkspace_` function.

This causes problems when you're trying to test the events system, because `bumpObjects` can fire events that mess up your tests. 
And having it live inside inject makes it really hard to remove (the easiest thing I've found is setting `scrollbars` to true so that `bumpObjects` doesn't get added).

The placement is also kind of confusing, because while it does, in a way, help initialize the workspace, it mainly adds a lot of behavior.

**Some solutions (I don't like any of them lol)**

1. Quick and dirty: **Move the bumpObjects function out of createMainWorkspace_, but keep it inside inject.js.** At least it's removable now, but it's still oddly placed.
2. Slower and maybe better?: **Move the bumpObjects function onto the workspaceSvg.** Now it's removable, so that's still good. And it's better placed. But the workspace already handles so much logic, it feels kinda sad just to stuff bumpObjects in there.
3. So slow it's crazy: **Create a new file that could eventually handle workspace metrics/movement, and add bumpObjects to that.** Removable ✓ And it feels like a good place for it. It also hints at the idea of moving movement handling out of the workspaceSvg, an idea that both excites and *terrifies* me.

**Additional context**

N/A

**Comment by rachel-fenichel** [comment]
If the goal is mostly to make things better for testing, let's go with 1.

If the goal is just cleanup, let's leave it alone for right now, and eventually go with 3.  I suspect that working on 3 would spiral into moving lots of workspace code around as well, and I prefer to keep that can of beans closed this week.

**Comment by BeksOmega** [comment]
Ima say this was closed by #5453
