### ISSUE TITLE
Value or dummy after statement is broken.

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#2921]
Rendering a value or dummy input after a statement input is broken, especially with inline inputs.
![image](https://user-images.githubusercontent.com/13686399/63803474-d63fd500-c8c9-11e9-96c6-282f873289ac.png)

**Comment by rachel-fenichel** [comment]
With #2947:
![image](https://user-images.githubusercontent.com/13686399/64057415-65125300-cb51-11e9-84c4-92869c17c3f2.png)
🤔

**Comment by moniika** [comment]
Fixed
