### ISSUE TITLE
onchange no more in Block definition ? (have to use this.setOnChange in init:)

### ISSUE THREAD

**Issue by ArfyFR** [google/blockly#2925]
Sorry, first try vanished 

I upgraded to "blockly": "2.20190722.1" @ npm

My blocks was defined with init: and onchange:

But nothing happenned if changes occured ...
If I look at the doc:
https://developers.google.com/blockly/guides/configure/web/events
there was an onchange ;)
But now it should be replaced by a call to
```
this.setOnChange(function(changeEvent) {
...
```
in init:  according to
https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#change_listeners_and_validators

I didn't see a note in the changelog or ?
Bug ?

**Comment by rachel-fenichel** [comment]
Defining `onchange` directly on the block should still work, even if it's not set in init:
https://github.com/google/blockly/blob/d471f5104539843cb2912c2749600c8a80f0cdbe/core/block.js#L203

**Comment by ArfyFR** [comment]
Hi
Sorry, my bad. It was linked to the move of createSvgElement into Blockly.utils.dom I noticed later.
You can ignore this (but perhap just update the doc / example).

**Comment by alschmiedt** [comment]
Updated here: https://developers.google.com/blockly/guides/configure/web/events
