### ISSUE TITLE
TypeScript definition problems

### ISSUE THREAD

**Issue by jollytoad** [google/blockly#2937]
The current blockly.d.ts TypeScript definition file does not accurately describe the data types in many places of the API, either through errors in the JSDoc types, insufficiently rich typing, or just incompatibilities between Closure and TS.

I'm currently upgrading our codebase to use Blockly July 2019 release, from its npm package rather than directly from the repo, and the supplied TypeScript definitions, rather than our very outdated and hacked definitions.

I'm opening this issue to start documenting the areas in which I've had to patch up or workaround issues in the supplied blockly.d.ts file...

- Mismatch between `Blockly.Options` and `BlocklyOptions` - the inject fn takes the former, but really should take the latter
- A `BlockSvg` should have a workspace of type `WorkspaceSvg`
- `BlockSvg.render` is missing
- `WorkspaceSvg.newBlock` should return a `BlockSvg`
- `Events.Abstract` should ideally have a type property, rather than individual subclasses having it
- `Icon` is missing some internal props and methods, which makes adding a custom Icon a pain

I've managed to fix above with the following...

```typescript
import Blockly from 'blockly'

declare module 'blockly' {

    interface BlockSvg {
        workspace: Blockly.WorkspaceSvg

        render(opt_bubble?: boolean): void
    }

    interface Options extends Blockly.BlocklyOptions {
    }

    interface WorkspaceSvg {
        newBlock(prototypeName: string, opt_id?: string): Blockly.BlockSvg
    }

    interface Icon {
        block_: Blockly.BlockSvg
        iconGroup_?: SVGElement

        drawIcon_(group: SVGElement): void

        setVisible(visible: boolean): void
    }

    namespace Events {
        interface Abstract {
            type: string
        }
    }
}
```

- `Blockly.Msg` is declared as a module with a single `LOGIC_HUE` prop, preventing arbitrary overrides within TS code, really it should be declared as a `Record<string, string>` to allow any message key to be overridden. The only work-around I've found for this is use of `// @ts-ignore` :(
- `Blockly.VariableMap.prototype.getVariable` returns `Blockly.VariableModel` but should be `Blockly.VariableModel | null` according to the docs

_more to come..._

**Comment by samelhusseini** [comment]
Thanks for filing Mark. I appreciate it.
The ``BlocklyOptions`` issue is an issue with how closure declares structs. I'm able to define the ``BlocklyOptions`` as a [typedef](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#typedef-type) but it doesn't allow optional properties. 
So unless you're setting all the options in TypeScript, it's going to be better to just do what I do in this (Blockly Angular Sample](https://github.com/google/blockly-samples/blob/master/blockly-angular/src/app/blockly/blockly.component.ts#L73) and cast your options to ``Blockly.BlocklyOptions``. I think I can drum up a better solution in the next release, I think I can just tell closure that ``BlocklyOptions`` is of type ``*`` (any), and then re-declare the type in TypeScript.
In regards to messages, I've fixed that in #2774, that will be coming the next release.

**Comment by jollytoad** [comment]
Hello again, after many months of doing other things I finally moved back to a spot of Blockly related work.

I'm currently in the process of upgrading to the latest 3.20200123.1 from 2.20190722.1

I'm finding some TS decl issues still, i can confirm that all of the fixes above are still required.

I've found a lot of place where 'null' is a valid value but this is not reflected in the TS decl.

specifically:

Blockly.Connection__Class
- setCheck(check: string|string[]**|null**): Blockly.Connection
- getCheck(): **string[] | null**

but many places merely state *or null* in the jsdoc without formally specifying it, for example:

Still in Blockly.Connection...

```
            /**
             * Get the parent input of a connection.
             * @return {Blockly.Input} The input that the connection belongs to or null if
             *     no parent exists.
             * @package
             */
            getParentInput(): Blockly.Input;
```

should be:

```
            getParentInput(): Blockly.Input | null;
```

I think the Closure type defs need fixing to account for this, but i'm not sure how *or null* is representing in Closure.

**Comment by xAtomic** [comment]
> WorkspaceSvg.newBlock should return a BlockSvg

As far as I've seen, none of the functions tagged with `@override` appear in blockly.d.ts
My solution currently is to simply remove the override tag. If I understand it correctly, it was only put in because of the closure compiler. As Blockly is now independent of the closure compiler, can the tag simply be removed permanently?

**Comment by kazamov** [comment]
Is there any plans to convert Blockly's codebase to the Typescript?

**Comment by rachel-fenichel** [comment]
@kazamov We won't rule it out, but it's not happening soon.

@xAtomic we're still using the closure compiler. What we stopped using is the closure UI library.

**Comment by jollytoad** [comment]
Hey gang, finally getting round to another Blockly update, from 3.20200123.1 to 3.20200625.2, so I thought I should keep this ticket updated.

Here are my type fixes for this release...

```
import 'blockly'

declare module 'blockly' {

    interface BlocklyOptions {
        parentWorkspace?: Blockly.WorkspaceSvg
    }

    interface WorkspaceSvg {
        newBlock(prototypeName: string, opt_id?: string): Blockly.BlockSvg
    }

    interface Icon {
        iconGroup_?: SVGElement

        setVisible(visible: boolean): void
    }

    module fieldRegistry {
        function register(type: string, fieldClass: { fromJson: (options: any) => Blockly.Field }): void
    }

    namespace Events {
        interface Abstract {
            type: string
        }
    }
}
```

The most notable change being the `Blockly.fieldRegistry.register` `fieldClass` param appears to be declared incorrectly...

The blockly.d.ts declares `register` as:

```
function register(type: string, fieldClass: { (_0: any[]): any /*missing*/ }): void;
```

but `fieldClass` should be an object containing a `fromJson` function rather than just a function.

**Comment by samelhusseini** [comment]
#4281 fixes the field registry, icon and options typings.

**Comment by jollytoad** [comment]
Just doing the upgrade to 3.20200924.3, the typings are looking a lot better with each release, great work gang.

My overrides are down to...

```
declare module 'blockly' {

    interface WorkspaceSvg {
        newBlock(prototypeName: string, opt_id?: string): Blockly.BlockSvg
    }

    module fieldRegistry {
        function register(type: string, fieldClass: { fromJson: (options: any) => Blockly.Field }): void
    }

    namespace Events {
        interface Abstract {
            type: string
        }
    }
}
```

I don't think the `Blockly.IRegistrableField.fromJson` is quite right, the arg could really do with being `any` rather than `Object`, I get the following error without my fix above:

```
error TS2345: Argument of type '{ fromJson: ({ url: urlTemplate, isMultipleSelectDropdown, defaultOptions: defaultValues }: FieldOptions) => FieldDropdown; }' is not assignable to parameter of type 'IRegistrableField'.
  Types of property 'fromJson' are incompatible.
    Type '({ url: urlTemplate, isMultipleSelectDropdown, defaultOptions: defaultValues }: FieldOptions) => FieldDropdown' is not assignable to type 'fromJson'.
      Types of parameters '__0' and '_0' are incompatible.
        The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
          Type 'Object' is missing the following properties from type 'FieldOptions': url, defaultOptions
```

NOTE the message: `The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?`

where my IRegistrableField is defined as...

```
const field_fetching_dropdown = {
    fromJson: function ({url: urlTemplate, isMultipleSelectDropdown, defaultOptions: defaultValues}: FieldOptions) {
```

It would also be really useful, if the `type` prop could be defined on `Events.Abstract`.

**Comment by samelhusseini** [comment]
Adding more to this. The different renderers we publish are currently not included in the blockly.d.ts

**Comment by coderoid** [comment]
Hey all,
I have been using blockly recently in a typescript project and getting to a point where not having accurate typescript definition files are leading to major pain points.
I want to for one instance inherit from zelos and can't do it without fully rewriting zelos in ts and even then it's not that straightforward.
There are other similar issues and would really love a complete TS definition file.
Any idea how we can get this?

**Comment by samelhusseini** [comment]
Hi coderoid.

Since the library isn't written in TypeScript, we do our best to convert the closure annotations (jsdoc) to a TypeScript definition available on npm and at: https://github.com/google/blockly/blob/master/typings/blockly.d.ts

Since this is an auto-conversion, and it relies on the correctness of our JSDOC annotations, we don't always get it right.
This bug is tracking some of the outstanding work we have on a few methods, please feel free to add more for any methods that you see a disconnect.

As for the zelos renderer not being included, acknowledged and it should, and this is the right place to request that.

**Comment by coderoid** [comment]
I'll try and find all my // @ts-ignores I have in my project and add them to the list here, that has been my way of making the ts compiler to stop complaining.
Is this the only issue documenting all the missing pieces for closure to pick it up? Also what is the timeline for getting some of these fixes in?

**Comment by coderoid** [comment]
Here is one more to add to the list, cannot define this in TypeScript
const customlDark = Blockly.Theme.defineTheme('customlDark ', {
    // @ts-ignore Exists in blockly
    base: Blockly.Theme.Classic,
    componentStyles: customDarkComponentStyle,
    blockStyles: customDarkBlockStyles,
});

**Comment by jollytoad** [comment]
Hi gang, quick update on this, just testing against 5.20210624.0-beta.4, but still have to retain the overrides from 3.20200924.3 ... https://github.com/google/blockly/issues/2937#issuecomment-716580273

**Comment by BeksOmega** [comment]
I'm gonna go ahead and close this to encourage people to file new issues against our typings.
