### ISSUE TITLE
Insertion Markers Do Not Properly Handle Typed Statement Connections

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2948]
**Describe the bug**

* The insertion marker manager will always decide to insert an insertion marker, if the block is a stack block, rather than highlight the block that is going to be replaced.
* As a side affect, stacks can be disconnected, but not appear to be disconnected. See screenshots.

**To Reproduce**

1. Add the following block definitions to the test blocks file:
```
Blockly.defineBlocksWithJsonArray([
  {
    "type": "blue_stack",
    "message0": "",
    "previousStatement": "none1",
    "nextStatement": "greenRel",
    "colour": 230,
  },
  {
    "type": "yellow_stack",
    "message0": "",
    "previousStatement": [
      "greenRel",
      "yellowRel"
    ],
    "nextStatement": [
      "yellowRel",
      "orangeRel"
    ],
    "colour": 60,
  },
  {
    "type": "red_stack",
    "message0": "",
    "previousStatement": "orangeRel",
    "nextStatement": "none2",
    "colour": 0,
  }
]);
```
**IMPORTANT**: This means that yellow blocks cannot connect to the bottom of red blocks.
See [this](http://bekawestberg.me/blog/types-1/#stacks-with-middle) for more details about how I defined these blocks.

2. Load the following xml to the playground:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="blue_stack" id="*+%$O_fE95g4=b)=FZ7s" x="54" y="69">
    <next>
      <block type="yellow_stack" id="iUhgU~iJ`ZzKk6[1x_n%">
        <next>
          <block type="yellow_stack" id="m]!RMy!do1;j#=YmhV?g">
            <next>
              <block type="red_stack" id="Gd6P6pgs{FHb70g=5I%,"/>
            </next>
          </block>
        </next>
      </block>
    </next>
  </block>
  <block type="red_stack" id="$,r0?rk/tGNIieasY$rh" x="123" y="66"/>
</xml>
```
3. Drag the orphan red block between the two yellow blocks, and drag it back out.
4. Observe how the insertion marker manager chose to insert an insertion marker, and observe how the stacks are now disconnected but do not appear so.

**Expected behavior**

The insertion marker manager should choose to highlight the block being replaced.
Testing block placement should not break stacks.

**Screenshots**

![InsertionStacks](https://user-images.githubusercontent.com/25440652/64127009-dece5a80-cd64-11e9-8009-436bca48bcc5.gif)

**This is not browser specific**

**Additional context**

Row blocks work correctly:
![InsertionRows](https://user-images.githubusercontent.com/25440652/64127253-b2ffa480-cd65-11e9-9cdc-cd3922efaf33.gif)

**Comment by BeksOmega** [comment]
I'll grab this.

**Comment by c3ho** [comment]
I'm pretty sure this is related to this issue here #2949.

**Comment by nazneennahar** [comment]
i would like to work on this

**Comment by BeksOmega** [comment]
> i would like to work on this please

Go for it! I think the[ shouldReplace_](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/insertion_marker_manager.js#L411) function is probably a good place to start hunting. The bug report says that it is always choosing to insert a block, so this case is probably not being handled inside of that function.

But I could be wrong and the bug could be somewhere else. ¯\_(ツ)_/¯

Happy bug hunting!
--Beka

**Comment by nazneennahar** [comment]
Can you please attach the Row Block definitions and it corresponding XMl?

**Comment by BeksOmega** [comment]
> Can you please attach the Row Block definitions and its corresponding XML as well?

Absolute!

Block Defs:
```
Blockly.defineBlocksWithJsonArray([
  {
    "type": "blue_row",
    "message0": "%1",
    "args0": [
      {
        "type": "input_value",
        "name": "NAME",
        "check": "greenRel"
      }
    ],
    "output": "none1",
    "colour": 230,
  },
  {
    "type": "yellow_row",
    "message0": "%1",
    "args0": [
      {
        "type": "input_value",
        "name": "NAME",
        "check": [
          "yellowRel",
          "orangeRel"
        ]
      }
    ],
    "output": [
      "greenRel",
      "yellowRel"
    ],
    "colour": 60,
  },
  {
    "type": "red_row",
    "message0": "%1",
    "args0": [
      {
        "type": "input_value",
        "name": "NAME",
        "check": "none2"
      }
    ],
    "output": "orangeRel",
    "colour": 0,
  }
]);
```

Xml:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="blue_row" id="tl{Pm#EBzFs)1*W6fLG@" x="10" y="10">
    <value name="NAME">
      <block type="yellow_row" id="8N)#6GKT$34}]Bj0|hUo">
        <value name="NAME">
          <block type="yellow_row" id="hDFgIp8atYkC~`.F_7T=">
            <value name="NAME">
              <block type="red_row" id="FYr#WMPprjNetK}^?_=["/>
            </value>
          </block>
        </value>
      </block>
    </value>
  </block>
  <block type="red_row" id="kmhUj0X.Zl{bE6sYt$rj" x="16" y="45"/>
</xml>
```
There ya go :D

**Comment by nazneennahar** [comment]
thanks

**Comment by alschmiedt** [comment]
Fixed.
