### ISSUE TITLE
Allow customization of checkbox character and class name

### ISSUE THREAD

**Issue by pelikhan** [google/blockly#295]
In the micro:bit editor, we use the checkboxes to represent LEDs. In order to make it look 'prettier', it would be great to allow to change the character and CSS class to allow styling (as seen below).

![image](https://cloud.githubusercontent.com/assets/4175913/13933061/936c2762-ef68-11e5-80fa-8f5185bb2f9b.png)

**Comment by NeilFraser** [comment]
Good idea.  Fixed on the 'develop' branch:
https://github.com/google/blockly/commit/4585e21d9ffd3fbc380e0dbd1c09d29c1509a493

The character may be changed by setting:
Blockly.FieldCheckbox.CHECK_CHAR = 'X'
This applies to all checkboxes in Blockly, not on a case by case basis.

CSS may be specified using the 'blocklyCheckbox' class.
