### ISSUE TITLE
Space below a child block in a statement input varies based on number of child blocks

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#2951]
**Describe the bug**
The space added below child blocks inside a statement input that accounts for the notch is dependent on the number of blocks attached when it shouldn't.
It should only add one notch height worth of space.

Repro's in renderers that change the height of their notch.

**To Reproduce**
Using the zelos renderer:

Drag the following onto your workspace to reproduce:
<img width="302" alt="Screen Shot 2019-09-01 at 12 30 21 PM" src="https://user-images.githubusercontent.com/16690124/64081332-4aa4ba80-ccb4-11e9-9a70-e39dd8c2ada2.png">

Notice how additional space was added below the last repeat block inside the statement input.

**Expected behavior**
Here's what happens when it's just one repeat block inside:
<img width="321" alt="Screen Shot 2019-09-01 at 12 31 00 PM" src="https://user-images.githubusercontent.com/16690124/64081341-6740f280-ccb4-11e9-8576-73a3a235b4d9.png">

It should be based on the notch height and not have anything to do with the number of blocks.
If I reduce the zelos NOTCH_HEIGHT to 4 pixels, everything works fine, so there's a dependency there that isn't being accounted for.

**Comment by joshlory** [comment]
Also repros on the geras renderer, if using a notch-height other than 4px:

![image](https://user-images.githubusercontent.com/413693/66683540-8d9b6b80-ec2c-11e9-885b-42ff876a470d.png)
