### ISSUE TITLE
blocklyWidgetDiv not moved on resize

### ISSUE THREAD

**Issue by drigz** [google/blockly#296]
![blockly resize widget bug](https://cloud.githubusercontent.com/assets/632207/13982967/258e22dc-f0ed-11e5-8d06-749ec83b6404.png)

When an onresize event moves a block relative to the window, the blocklyWidgetDiv doesn't move.

Steps to reproduce:

1. Open Code demo.
2. Create a math_number block, and select the number to edit it.
3. Resize the browser window horizontally until the play/trash buttons wrap, moving the top of the workspace down.
4. Observe that the editable text has been left behind, while the rest of the block has moved.

**Comment by NeilFraser** [comment]
Fixed.
