### ISSUE TITLE
[zelos only] Child blocks in statement inputs shouldn't have any spacer after the notch

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#2963]
**Describe the bug**

Remove whitespace from under child blocks in statement inputs in the zelos renderer. 

<img width="371" alt="Screen Shot 2019-09-03 at 5 12 45 PM" src="https://user-images.githubusercontent.com/16690124/64216574-445a3e00-ce6e-11e9-9e2f-d3e9ecc2dd8a.png">

instead of

<img width="331" alt="Screen Shot 2019-09-03 at 5 14 26 PM" src="https://user-images.githubusercontent.com/16690124/64216581-4cb27900-ce6e-11e9-9c4f-04ce839f2f11.png">

@rachel-fenichel I wonder if this should be the default in base?
Maybe Thrasos also wants to adopt this, could be a later point decision as well.

**Comment by rachel-fenichel** [comment]
https://developers.google.com/blockly/guides/app-integration/best-practices#2_nesting_sub-stacks

**Comment by samelhusseini** [comment]
Fixed.
