### ISSUE TITLE
How to compile project with local closure compiler?

### ISSUE THREAD

**Issue by dhcn** [google/blockly#2975]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NeilFraser** [comment]
Here's the instructions:
https://developers.google.com/blockly/guides/modify/web/advanced

**Comment by dhcn** [comment]
> Here's the instructions:
> https://developers.google.com/blockly/guides/modify/web/advanced

Many Thanks

**Comment by dhcn** [comment]
> Here's the instructions:
> https://developers.google.com/blockly/guides/modify/web/advanced

this is for project compile
I want to compile for lib generation
