### ISSUE TITLE
Endmost value connections are not considered available

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2989]
**Describe the bug**

If you have a group of "row" blocks, each with a single input. The last input is not considered "available" when searching for viable connections.

**To Reproduce**

1. Load the following XML to the playground:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="logic_negate" id="=x,AGNcntldv}jzRvW/?" x="73" y="266">
    <value name="BOOL">
      <block type="logic_negate" id="-P9*H~zHvH:qzpfeRJix"/>
    </value>
  </block>
  <block type="logic_boolean" id="|_4LpV/.(?daxuc@/LpC" x="218" y="267">
    <field name="BOOL">TRUE</field>
  </block>
</xml>
```
2. Drag the two "not" blocks towards the "true" block.
3. Observe how no insertion marker is shown.

**Expected behavior**

Endmost input connections should be treated as available (at least in the case where this is only a single one).

**Screenshots**

![EndConnection_Rows](https://user-images.githubusercontent.com/25440652/64547114-ccae6800-d2e0-11e9-8095-0df47c0d64fd.gif)

**This is not browser specific**

**Additional context**

This does not occure with stack blocks:
![EndConnection_Stacks](https://user-images.githubusercontent.com/25440652/64547241-0ed7a980-d2e1-11e9-8d38-84ecd3ddb4f0.gif)

**Comment by moniika** [comment]
This is working as intended.
The reasoning behind this decision is that the last input in a stack is always a single connection with a straightforward path, but in the case of the last input in a chain it can get a lot messier.
We didn't want the inconsistency of having it work in simple cases but not more complicated ones (or working in seemingly inconsistent ways).
