### ISSUE TITLE
Connection.connect throws uncaught error when trying to connect to a "nested" connection

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2990]
**Describe the bug**

If you call Connection.connect and provide a connection on a block that is a child of the original connection's source block, you get an uncaught error.

**To Reproduce**

1. Load the following XML to the playground.
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="controls_if" id="top">
    <statement name="DO0">
      <block type="controls_if" id="nested"/>
    </statement>
  </block>
</xml>
```
2. Run the following code in the console:
```
topBlock = Blockly.mainWorkspace.getBlockById('top');
nestedBlock = Blockly.mainWorkspace.getBlockById('nested');
topBlock.previousConnection.connect(nestedBlock.nextConnection);
```
3. Observe the error.

**Expected behavior**

Optimally, the connections would correctly connect (since they are compatible).

Alternatively, it would throw a descriptive error.

**This is not browser specific**

**Stack Traces**

```
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at Blockly.BlockSvg.setParent (file:///C:/Users/bekawestberg/Documents/Web%20Developement/blockly/core/block_svg.js:287:28)
    at Blockly.RenderedConnection.Blockly.Connection.connect_ (file:///C:/Users/bekawestberg/Documents/Web%20Developement/blockly/core/connection.js:235:14)
    at Blockly.RenderedConnection.connect_ (file:///C:/Users/bekawestberg/Documents/Web%20Developement/blockly/core/rendered_connection.js:409:51)
    at Blockly.RenderedConnection.Blockly.Connection.connect (file:///C:/Users/bekawestberg/Documents/Web%20Developement/blockly/core/connection.js:479:21)
    at <anonymous>:3:29
```

**Additional context**

Running this code does work:
```
topBlock = Blockly.mainWorkspace.getBlockById('top');
nestedBlock = Blockly.mainWorkspace.getBlockById('nested');
topBlock.nextConnection.connect(nestedBlock.previousConnection);
```
Which is another point towards making the above work.

There are two (duplicate) checks for this [here ](https://github.com/google/blockly/blob/4efa0dad1f2c882234759d3ba7ecd0ebd95a4c77/core/connection.js#L429)and [here](https://github.com/google/blockly/blob/4efa0dad1f2c882234759d3ba7ecd0ebd95a4c77/core/connection.js#L352), but they only work when dragging.

**Comment by moniika** [comment]
This is probably a documentation issue where isConnectionAllowed() needs to be called before connect is called programatically.
Another solution is that we could add a check in connect and add a flag to allow for the check to be skipped to avoid duplicate checks (as in the case of drags where the check is already done).

**Comment by rachel-fenichel** [comment]
Yeah, part of what's happening (here and in some of the related bugs that you filed) is that `isConnectionAllowed` is called from the dragged connection manager, but not in connect.  That's because we were trying to avoid going through all of that logic twice.  Basically, `isConnectionAllowed` is more about acceptable things to do while dragging, while the checks in `canConnectWithReason` check for bad states to avoid.

**Comment by RoboErikG** [comment]
Needs JSDoc on connect() to clarify expectations.

**Comment by rachel-fenichel** [comment]
The connection checker API lets you call `doSafetyChecks` independent of `doDragChecks`, so you can check for these issues before calling `connect` programmatically. As noted above, this is already handled during drags.
