### ISSUE TITLE
Add Typescript typings for generators

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#2995]
**Is your feature request related to a problem? Please describe.**

Include Typescript definitions for Blockly generators.

**Describe the solution you'd like**

scan the generator directory as part of the typescript definition generation: 
https://github.com/google/blockly/tree/master/generators

Feature requested on forums: 
https://groups.google.com/forum/#!topic/blockly/Su046eekUZY

**Comment by aabounegm** [comment]
Any updates on this? I wrote the following workaround in my project:
```typescript
declare module 'blockly/javascript' {
    import { Generator } from 'blockly';
    const instance: Generator;
    export = instance;
}
```
but that still doesn't give it the additional properties defined on the `Blockly.JavaScript` object (which I also can't use because typescript screams that `Property 'Javascript' does not exist on type 'typeof Blockly'`)

**Comment by cpcallen** [comment]
This was fixed by all the work done to convert the generators to TypeScript (see issue #6828).
