### ISSUE TITLE
Object.values not available in IE

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#2999]
**Describe the bug**

No Object.values in IE: 
see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values

We're making use of it here: 
https://github.com/google/blockly/blob/develop/core/keyboard_nav/key_map.js#L121
and here: 
https://github.com/google/blockly/blob/develop/core/keyboard_nav/key_map.js#L141

@alschmiedt FYI

**To Reproduce**

1. Run the playground on IE.

Use Object.keys and then use the key to extract the value.

**Comment by NeilFraser** [comment]
Sounds like a great fit for the Object utils file that's just about to appear.

```
/**
 * Returns an array of a given object's own enumerable property values.
 * @param {!Object} obj Object containing values.
 * @return {!Array} Array of values.
 */
Blockly.utils.object.values = function(obj) {
  if (Object.values) {
    return Object.values(obj);
  }
  // Fallback for IE.
  return Object.keys(obj).map(function(e) {
    return obj[e];
  });
};
```

**Comment by samelhusseini** [comment]
Fixed.,
