### ISSUE TITLE
Have a way to choose which renderers are included in your bundle

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3018]
We currently don't have a way to pick and choose which fields or renderers are included in a bundle for those building with the closure compiler (Blockly Games, App Inventor, etc). 

We should pull out any Blockly "modules" into a separate entry point that we then use as our main entry point for building compressed Blockly. 

Folks wanting to customize what's included in their bundle are then able to goog.require whatever fields / renderers they want.

**Comment by RoboErikG** [comment]
Nice to have for this release but could be punted if necessary.

**Comment by samelhusseini** [comment]
Fixed.
