### ISSUE TITLE
Link in `ReadME` points to an invalid URL

### ISSUE THREAD

**Issue by kushthedude** [google/blockly#3021]
**Where**

In `blockly/readME.md`

**What**

  
- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

Currently, `Blockly Docs` link is mentioned wrong in the `readME.md`

**Suggested content**

Correct the link for `Blockly`

**Comment by RoboErikG** [comment]
Thanks for reporting. This is fixed in develop and will go out in the next release in October.

**Comment by samelhusseini** [comment]
Already fixed by Fixed by https://github.com/google/blockly/pull/2721

**Comment by kushthedude** [comment]
> Thanks for reporting. This is fixed in develop and will go out in the next release in October.

@RoboErikG Sure, I will be more aware before making any new PR, Thanks.
