### ISSUE TITLE
Keyboard Nav: Cursor not showing correct location 

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3028]
**Describe the bug**
The cursor doesn't seem to be showing the correct location on the workspace.

**To Reproduce**
Move cursor to the workspace. 
Insert block from flyout. 
Observe the block is moved to a slightly different location.
**Expected behavior**
Block is moved to the location of the cursor.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by kushthedude** [comment]
@alschmiedt Can I try fixing the following ?

**Comment by alschmiedt** [comment]
Yup! Let me know if you have any questions : )

**Comment by samelhusseini** [comment]
This feature is still very new and has limited documentation. I wouldn't recommend this as a good place to start. Please use the ``help-wanted`` tag for good first issues. These will help you get familiar with the codebase and with our contributing guidelines.

https://github.com/google/blockly/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+
