### ISSUE TITLE
blockly factofy NAME is not editable

### ISSUE THREAD

**Issue by codeskyblue** [google/blockly#303]
<https://blockly-demo.appspot.com/static/demos/blockfactory/index.html>

The NAME can't changed.

![image](https://cloud.githubusercontent.com/assets/3281689/14131029/1f90d5b4-f66a-11e5-81d7-6169087ee22c.png)

**Comment by NeilFraser** [comment]
This is due to a fix for issue #300.  I've rolled that back, and am pushing a new version now.  Thanks for the quick report!
