### ISSUE TITLE
npm: new blocks instances appear below menuFlyout while dragging

### ISSUE THREAD

**Issue by microspace** [google/blockly#3032]
Blocks always go under menuflyout when I drag clock to create new block instance.
Issue appears when I use **npm** package of blockly

1. Go to https://github.com/google/blockly-samples/tree/master/blockly-webpack
2. clone, npm install, npm run start
3. Drag any of block from toolbox.
4. See error: block appears below menuFlyout

![Снимок](https://user-images.githubusercontent.com/2958584/65040348-966e8980-d96d-11e9-87a9-19b54fe5305f.PNG)

**Desktop:**
 - OS: Windows 10
 - Chrome browser
 - Version 76

**Comment by samelhusseini** [comment]
Fixed in develop. We are planning an npm release in a few weeks.

**Comment by microspace** [comment]
@samelhusseini , thank you! Can I use the develop version for now, or it is not possible?

**Comment by RoboErikG** [comment]
@microspace We don't publish our develop branch to npm, so if you would like to use it you'll have to clone it from the GitHub repo.

**Comment by microspace** [comment]
@samelhusseini , sorry to bother, but do I have to build develop version myself?
I get error "no module named blockly" when I install develop version of blckly from github
