### ISSUE TITLE
Add the ability to make a read-only workspace writable

### ISSUE THREAD

**Issue by NoahAndrews** [google/blockly#3049]
**Is your feature request related to a problem? Please describe.**

I need to be able to have a workspace start out as read-only, but become writable.

**Describe the solution you'd like**

For maximum flexibility, I'd love to see a `workspace.setReadOnly(boolean)` function, but if it's easier to only support going from read-only to writable, a function `workspace.enableEditing()` would suffice.

**Describe alternatives you've considered**

I found [this message](https://groups.google.com/d/msg/blockly/NCukwTKMR0U/30BABGu4BQAJ) from Neil on Google Groups, which suggests putting a transparent div over Blockly to prevent interactions. The problem with this is that it also disables panning and zooming around the Blockly workspace. I want users to be able to interact with, but not edit, the workspace.

**Additional context**

In [that message](https://groups.google.com/d/msg/blockly/NCukwTKMR0U/30BABGu4BQAJ), Neil said this:

> Readonly cannot be changed after init.  There are too many event handlers that would need to be added and removed.

I don't understand why that would be an unsolvable problem (maybe I'm just not familiar enough with the Blockly source). I'd like to try to implement this change myself, so I'd appreciate any additional context or guidance that anyone (@NeilFraser) can give me.

**Comment by RoboErikG** [comment]
It's a lot of work to implement correctly and to maintain. It's also not a common use case, so it's unlikely to get prioritized by us anytime soon. You're welcome to give it a shot, though.

**Comment by BeksOmega** [comment]
You might also be able to handle this by:

1. Serializing the readonly workspace.
2. Disposing of it.
3. Re-injecting an editable workspace.
4. Deserializing.

I've done this for language-changing before and I remember it being pretty seamless.

**Comment by NoahAndrews** [comment]
@BeksOmega How do I properly dispose of a workspace? I basically tried what you suggested, and couldn't get it to work correctly. I think the new workspace still wasn't really editable.

**Comment by NoahAndrews** [comment]
Ooh there's an actual dispose method! Nice! I'll have to try that out, thank you

**Comment by NoahAndrews** [comment]
@BeksOmega Thanks so much, it's working great now!
