### ISSUE TITLE
Toolbox suffers from code bloat

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#3056]
The toolbox (category tree, not the flyout) compiles down to 25 KB, that's 1/6th of our codebase (as measured by tests/compile).  There is not enough functionality in this widget to justify that kind of size.

The origin of this bloat is Closure.  Unlike most of the rest of the removal of Closure, our current toolbox is basically copied from Closure rather than being rewritten.  Maybe the toolbox needs to be rewritten, or maybe there's some stuff we don't use that can simply be trimmed out.

In any event, it shouldn't take over 2,500 lines of code (plus CSS) to create a category tree.

**Comment by NeilFraser** [comment]
PR #3055 deleted 400 lines of unused code, but only reduced the toolbox by 1 KB since the compiler's tree shaking was already stripping most of that code.

**Comment by alschmiedt** [comment]
While the toolbox size has overall stayed the same, I don't think this is any longer the case. With the toolbox rewrite we have removed unnecessary code that was left in from closure. The size of the toolbox is due to the extra features that have been added as part of the toolbox rewrite.
