### ISSUE TITLE
Prevent blocks from toggling inline/external

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#3077]
It used to be that if a block was `this.isDeletable() && this.isMovable()` then the inline/external menu row would appear (assuming the block's topology qualified).  This original behaviour can be seen in the archived version of Blockly Games where the green puzzle pieces do *not* have an inline context menu option:
https://2-dot-blockly-games.appspot.com/puzzle

The current code is that the block need only be `this.isMovable()` for the menu row to appear.  This new behaviour can be seen in the live version of Blockly Games where the green puzzle pieces do have an inline context menu option:
https://blockly.games/puzzle

It is desirable to be able to eliminate this menu option for simple Blockly instances such as Puzzle.  The original mechanism worked, but doesn't make a lot of sense.  The new mechanism doesn't have any options for removing the menu option.  What's the best way to restore this functionality?

I think the key question is does it need to be per block, per block type, or can it just be across the workspace?  Personally I think workspace is fine, but don't care one way or another.

**Comment by RoboErikG** [comment]
My preference is for a workspace level switch just like collapse.

[Relevant code is in block_svg](https://github.com/google/blockly/blob/develop/core/block_svg.js#L713).

**Comment by maribethb** [comment]
Closing since this can be done with the context menu API: https://github.com/google/blockly/pull/4923#issuecomment-863456995 (either per workspace, trivially, or per-block by setting up a more complicated precondition function)
