### ISSUE TITLE
+/- buttons for dynamically extending value input list

### ISSUE THREAD

**Issue by nicolaipoehner** [google/blockly#3078]
Hey, 
we're currently working on a block-based editor for SQL (https://github.com/nicolaipoehner/blocklysql) for education purposes. I read here (https://developers.google.com/blockly/guides/create-custom-blocks/style-guide) that one option for growing blocks is using +/- buttons. They would be helpful for my SELECT and FROM-statement blocks. Do you have any examples / tutorials for this? 

Kind regards,
Nicolai

**Comment by BeksOmega** [comment]
Hello Nicolai,

There is currently no official demo for +/- mutators, but there is a [tracking issue](https://github.com/google/blockly/issues/1845) for creating one.

I do have the [start of a demo](https://github.com/google/blockly/compare/develop...BeksOmega:demo/AlternateMutators) which I've been working on off-and-on in my free time. It's not completed or polished, but it does show the basic steps for achieving this.

1. **Create some sort of +/- UI.**
  * Option 1: Create a **custom icon** (like comment, warning, and mutator icons). The one issue is Icons are always drawn at the top-left corner of a block.
  * Option 2: Create a **custom field**. Custom fields can be drawn anywhere on a block, and will also allow you to easily define click-callbacks.
  * Option 3: Use image fields. This works, but is a bit of a hastle long term. You have to keep passing your +/- image locations to your image fields, and keep assigning click handlers to them. This would be a pain to change if you ever needed to.

I chose to go with option 2 in my demo. I know OpenRoberta chose to go with Option 1.

2. **Define your Blocks**. How this will work will depend on what UI option you decided to go with. You can see the demo linked above for how to make it work with fields, and you can see [OpenRoberta's source](https://github.com/OpenRoberta/blockly/blob/b04bc851038c44a83b55477877958d720e16cdd3/blocks/logic.js#L555) for how to make it work with icons.

3. **Make them mutate**. This is basically just adding callbacks to your +/- UI so the block can respond to clicks.

4. **Add serialization**. To make it so your mutated blocks round-trip through XML, you'll need to define the `domToMutation` and `mutationToDom` methods just like you would for a [normal mutator](https://developers.google.com/blockly/guides/create-custom-blocks/web/mutators#mutationtodom_and_domtomutation).

5. **Celebrate!** You have created +/- mutator blocks.

I hope that helps! If you have any further questions I think it's probably best to move this conversation to the [forums](https://groups.google.com/forum/#!forum/blockly) (I don't think I'm /technically/ supposed to reply to things here haha) Good luck with your project!
--Beka

**Comment by RoboErikG** [comment]
And please ask questions on [the forum](https://groups.google.com/forum/#!forum/blockly) instead of posting issues. You're more likely to get a response, especially when looking for examples of what other folks have done.
