### ISSUE TITLE
Remove render debug and non-default renderers from default build

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3089]
Debug rendering (`Blockly.blockRendering.Debug`) should be an optional module, like this: https://github.com/google/blockly/pull/3076/files

We should directly import it in the playground, since it's essentially a playground debugging tool.

Non-default renderers (zelos and thrasos) should not be in the default build.

**Comment by rachel-fenichel** [comment]
@samelhusseini one issue with removing zelos and thrasos from the default build is that anyone pulling it down npm no longer automagically gets to pick their renderer.  We should definitely take it out for this release and discuss longer term.

**Comment by samelhusseini** [comment]
Everything is in the playground by default, so no need to add anything special there. We can just leave it out of our compressed file.

Yeah I'm of the opinion we should ship them all in our compressed build longer term, I was just saying that perhaps we want to leave them out of this next release as they're not fully baked.

**Comment by rachel-fenichel** [comment]
> Everything is in the playground by default

No, the playground loads blockly_uncompressed, and that's built based on the requires.

**Comment by samelhusseini** [comment]
Fixed.
