### ISSUE TITLE
BlockFactory: Dummy input block has unused id field.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#309]
Highlighted in red:
<img width="199" alt="screen shot 2016-04-01 at 11 12 05 pm" src="https://cloud.githubusercontent.com/assets/9916202/14224841/489be45c-f85f-11e5-9490-0d465fc36612.png">

These fields should be removed because dummy input ids are never exported (and never needed) in both JSON and JavaScript formats

**Comment by NeilFraser** [comment]
Good catch.  Fixed.  Thanks!
