### ISSUE TITLE
Workspace drag performance regression

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3094]
Drag performance has gotten worse again.  Of particular concern is that it's much worse with the spaghetti test than with a comparable number of blocks on the workspace separately.  It's also getting worse with the number of blocks on the workspace even when they aren't connected.  

Workspace drag performance should not be related to the number of blocks, except maybe in the time it takes to move the blocks to the drag surface at the beginning of the drag.

@picklesrus for ideas before I start digging.

**Comment by samelhusseini** [comment]
Looked into this today, and it seems that this is Chrome specific. Since Chrome 72 the workspace and block drag performance have regressed, something to do with how Chrome is perceiving ``translate3d`` on the SVG canvas. This only seems to affect large workspaces, when the number of DOM elements is abundant.
This doesn't appear to affect Firefox and Safari.

**Comment by samelhusseini** [comment]
Another observation is Chrome is fine up until spagetti(7). That's when it reaches the limit and starts lagging.

**Comment by rachel-fenichel** [comment]
@rachel-fenichel to check if this is fixed after Chrome 72.

**Comment by samelhusseini** [comment]
Still occurs in Chrome 79 at spagetti(8). 7 and below are fine. Issue doesn't repro in Firefox or Safari.

**Comment by mattbishop** [comment]
Possibly related? https://bugs.chromium.org/p/chromium/issues/detail?id=666244

If not, worth filing a new bug?

**Comment by samelhusseini** [comment]
Last I looked into this I had trouble creating a simple repro for filing a bug. I'll try again this week.

**Comment by rachel-fenichel** [comment]
Closing because this only happens under extreme stress (spaghetti(8+)) and only on Chrome.

**Comment by mrkprdo** [comment]
@rachel-fenichel I don't think it's only affecting extreme stress with >7 spaghetti anymore with blockly 9.2.1 and chrome 109.
