### ISSUE TITLE
block.getFirstStatementConnection not used?

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#3096]
`Blockly.Block.prototype.getFirstStatementConnection` is at the root of a call stack that doesn't seem to be reachable.  And the functionality of getFirstStatementConnection does not match any behaviour in Blockly.  It does however match Scratch's insertion mechanism which prevents connecting to anything other than the first statement connection.

Some investigation is needed to figure out what this code is doing in Blockly.

**Comment by samelhusseini** [comment]
Not sure if this wasn't used at the time this bug was filed, but today the method is used in ``Blockly.InsertionMarkerManager.prototype.shouldReplace_``
