### ISSUE TITLE
keyboard reappears on iOS 8

### ISSUE THREAD

**Issue by cartmanguo** [google/blockly#31]
when i finished editing a text block and click confirm,the new text is set.And then no matter where I touch on the screen,the keyboard shows up again.I use UIWebview to load a local html.
exactly the the same issue described in this link:https://code.google.com/p/blockly/issues/detail?id=169.

**Comment by NeilFraser** [comment]
A bunch of mobile updates have landed and this issue does not seem to be repeatable.  I think it got fixed in the process of dealing with other bugs.  Can you check if this is still a problem?  Thanks!

**Comment by cartmanguo** [comment]
This problem still exists

**Comment by jluthiger** [comment]
Even in iOS 8.3 this problem still exists. No similar problems on Android devices!
After changing the value of a "math_number" or "text" block for example, the context menu reappears  and the user is forced to deal with the input dialog again. See example (context menu after entering a value for the first time):

![bildschirmfoto 2015-06-24 um 08 59 14](https://cloud.githubusercontent.com/assets/7327664/8325274/61f4a794-1a58-11e5-8bd9-8b373077172a.png)
