### ISSUE TITLE
New field_number type (and maybe others) for better <input> fields and standardized validators

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#310]
Blockly needs a number field type, and possible more field types to expose `<input>` features, especially in a mobile environment where the appropriate type can lead to better input methods / onscreen keyboards.

I propose `field_number`, with JSON attributes `value`, `precision`, `min` & `max`. A number must be divisible by `precision` (usually a power of 10), and inclusively between `min` and `max`.

`field_integer` might be shorthand for a field_number with precision == 1.  `min` and `max` still apply.
### Why?

Right now, there there are only two ways to mark a field as a number:
1. Use the undocumented input field validators, the way `math_number` does: `new Blockly.FieldTextInput('0', Blockly.FieldTextInput.numberValidator)`.
2. Use the overly specific FieldAngleInput.

Both create `<input>` HTML for typing in the number, but neither input field uses `type="number"` to trigger HTML level validation and appropriate input methods.  This is especially important on mobile, where numeric input are much more cumbersome on the full keyboard, compared to the number specific input method.  [Try it out.](http://jsfiddle.net/ctsobcdL/3/embedded/result/)

Further, the current use of functions as validators means these current features are inaccessible from JSON block definitions. With a new `field_number`, a validating and normalizing function could be generated with a small handful of optional parameters: min, max, precision, etc.

For example:

```
{
  "id": "math_decimal",
  "message0": "%1",
  "args0": [
    {
      "type": "field_number",
      "name": "NUM",
      "value": 10.00
    }
  ],
},
{
  "id": "math_integer",
  "message0": "%1",
  "args0": [
    {
      "type": "field_number",
      "name": "NUM",
      "value": 10,
      "precision": 1
    }
  ],
}
```

Or:

```
{
  "id": "midi_note",
  "message0": "%1",
  "args0": [
    {
      "type": "field_integer",
      "name": "NOTE",
      "value": 60,
      "min": 0,
      "max": 127
    }
  ],
}
```
### Further types

While perhaps not quite as necessary for Blockly, there are other input types that provide improved desktop input and excellent mobile input methods: `"date"`, `"time"`, `"week"`, `"month"`, `"tel"`.  With lesser benefit, there is also `"email"` and `"url"` (though the CSS `:valid` and `:invalid` selectors can be useful).

**Comment by NeilFraser** [comment]
We totally agree on all points.  (Note that we already have a custom field_date, though it is commented out since almost nobody uses it and it significantly bloats the code.)

Furthermore, the midi note block you are building should use an field_note type such as the one Scratch uses (they explicitly gave permission for us to copy it):
<img width="313" alt="screen shot 2016-04-02 at 04 59 07" src="https://cloud.githubusercontent.com/assets/250480/14226193/b4302e32-f88f-11e5-9383-d53c16038f88.png">

I'll look into this next week.

**Comment by AnmAtAnm** [comment]
Good to hear.

Love the keyboard.  Looking forward to it from our prior conversations.

As for the date, where is the bloat coming from? Custom UI, similar to field_angle?  If so, can the UI be stubbed with <input type="date"/>? Even the desktop UI is decent on that one.

**Comment by AnmAtAnm** [comment]
I also want to consider JSON arg hints for one of two pop-up helper interfaces (similar to the color or angle popups): either a continuous slider, or increment/decrement buttons.

Not sure if there should be any pop-up be default. Perhaps buttons if the precision is a multiple of 1, otherwise slider if min and max are set.

**Comment by RoboErikG** [comment]
Everything sounds good to me. Just a note, I'd prefer not adding field_integer since we can support that functionality with just field_number. Adding two ways to do the same thing tends to be annoying to support and isn't really worth it to save one parameter.

field_note, by comparison, is a completely different UI and later can be extended with fields like 'instrument'. ;)

**Comment by pelikhan** [comment]
field_integer is important when input is integral, e.g. micro:bit does not support floats

**Comment by AnmAtAnm** [comment]
@pelikhan 
Erik's point was we have support for integers through precision: 1 (or 5, or 10 or 100, etc).  So if a microcontroller only supports 32-bit ints, you could use:

```
{
  "id": "math_int32",
  "message0": "%1",
  "args0": [
    {
      "type": "field_number",
      "name": "NUM",
      "value": 10,
      "precision": 1,
      "min": -2147483648,
      "max": 2147483647
    }
  ],
}
```

**Comment by pelikhan** [comment]
Great!

Sent from Outlook Mobile<https://aka.ms/djubve>




On Thu, Apr 7, 2016 at 10:20 AM -0700, "Andrew n marshall" <notifications@github.com<mailto:notifications@github.com>> wrote:


@pelikhan<https://github.com/pelikhan>
Erik's point was we have support for integers through precision: 1 (or 5, or 10 or 100, etc). So if a microcontroller only supports 32-bit ints, you could use:

{
  "id": "math_int32",
  "message0": "%1",
  "args0": [
    {
      "type": "field_number",
      "name": "NUM",
      "value": 10,
      "precision": 1,
      "min": -2147483648,
      "max": 2147483647
    }
  ],
}


-

**Comment by AnmAtAnm** [comment]
`field_number` has existed for a while not.  Tracking `<input>` changes in #1595.
