### ISSUE TITLE
Shadow blocks do not morph anymore to standard blocks

### ISSUE THREAD

**Issue by miguel76** [google/blockly#311]
I realized that the behaviour of shadow blocks changed.
Originally they morphed to standard blocks if one of the fields was modified.
Now it seems to me that they stay as shadow blocks anyway.
Is this the new intended behaviour?

**Comment by NeilFraser** [comment]
Yes.  Morphing from shadow blocks to regular blocks was an experiment that didn't work out as well as we'd hoped.  It was the source of a number of errors, inconsistencies, and unexpected behaviours.  Ultimately we felt that shadow blocks should remain shadow blocks even if modified.

**Comment by miguel76** [comment]
Thanks for the explanation.
By the way, I have tried the following code in my project and is working fine...

```javascript
workspace.addChangeListener( function(event) {
  var block = Blockly.Block.getById(event.blockId);
  switch (event.type) {
    case Blockly.Events.CHANGE:
      if (block.isShadow()) {
        block.setShadow(false);
      }
      break;
    default:
  }
});
```

**Comment by NeilFraser** [comment]
Check to see what happens if you try to undo/redo an action that sets a shadow...
