### ISSUE TITLE
Theme configuration.

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3113]
**What UI components should be configurable by the theme, and what should the configuration name be.**

- [x] `workspace`: The workspace background color
- [x] `toolbox`: Toolbox background color
- [x] `toolboxText`: Toolbox category text color
- [x] `flyout`: Flyout background color
- [x] `flyoutText`: Flyout label text color
- [x] `flyoutOpacity`: Flyout opacity
- [x] `scrollbar`: Scrollbar color
- [x] `scrollbarOpacity`: Scrollbar opacity
- [x] `insertionMarker`: Insertion marker color
- [x] `insertionMarkerOpacity`: Insertion marker opacity
- [ ] `flyoutButton`: Background color for flyout buttons
- [ ] `fieldOpacity`: The opacity of the background of a field.
- [ ] `fieldColor`: The background color for the field.
- [ ] `highlight`: The highlight color of the selected block **(in progress)**
- [ ] `dropdown`: Default dropdown div background color
- [ ] `dropdownBorder`: Default dropdown div border
- [ ] `dropdownText`: Default dropdown div text. (or whether or not it's inverted)
- [x] `font`: The font for toolbox and blocks. (Could be useful for people with dyslexia)
- [x] `startHats`: Whether or not to enable start hats for blocks with no previous or output connections.

Using this issue to track proposals, please feel free to add to this list.

@alschmiedt FYI

**Comment by samelhusseini** [comment]
Another extension point to think about is the ability to add custom filters. Currently all our filters are just injected in inject.js. Developers can't extend that though. It would be good to standardize that.
Even if that's not taken care of on a theme by theme basis.

**Comment by rachel-fenichel** [comment]
Do we really want to encourage the use of custom filters?  They're very browser-dependent and can really slow things down if we're not careful.

**Comment by alschmiedt** [comment]
Per discussion we have new and improved names:

workspace -> workspaceBackgroundColour
toolboxText -> toolboxForegroundColour
flyout -> flyoutBackgroundColour
flyoutText -> flyoutForegroundColour
scrollbar -> scrollbarColour
insertionMarker -> insertionMarkerColour
flyoutButton -> flyoutButtonColour
dropdown -> dropdownBackgroundColour
dropdownText -> dropdownForegroundColour

*Also discussed in the meeting, we are mostly sticking with our CSS as default except for a few cases where it makes sense to have javascript as default. (ex. selected)

**Comment by rachel-fenichel** [comment]
For q4 release: font configuration.
@rachel-fenichel to post PR for font configuration in the renderer.

**Comment by samelhusseini** [comment]
Font configuration https://github.com/google/blockly/pull/3698
