### ISSUE TITLE
Update Themes Documentation

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3138]
**Where**

**What**

  
- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

**Suggested content**
Once decided add information on what different components can be changed.
Update information on how to set the theme since it has been moved from Blockly to the workspaces.

**Additional context**

**Comment by samelhusseini** [comment]
Also include changes to passing in themes as options: https://github.com/google/blockly/pull/3379

**Comment by samelhusseini** [comment]
Also include https://github.com/google/blockly/pull/3413#pullrequestreview-313694424

**Comment by alschmiedt** [comment]
Finished.
