### ISSUE TITLE
[Help needed]Cannot set Output connections dynamically according to dropdown selected

### ISSUE THREAD

**Issue by gomathykailas** [google/blockly#315]
Hi,

I am new to Blockly , I am facing a problem in blockly output connection.

I have a dropdown field in a block , and the output of this block should be changed according to the dropdown selected.

Eg : If we have 'ADD' and 'IS_NULL' in dropdown , then i should be able to do
**setOutput(true, String)** for 'ADD' dropdown and **setOutput(true, Boolean)** for 'IS_NULL' dropdown.

I have made these changes in the **onchange** function in blockly , but I am always getting exception as **Uncaught Disconnect connection before disposing of it** , while adding output connections with the dropdown.

I am also sharing code i made . 

Blockly.Blocks['test'] = {

        init : function() {
		var OPERATORS = [ [ '+', 'ADD' ], [ '-', 'IS_NULL' ] ];
		this.setColour(1);
		this.appendDummyInput('B').appendField(
				new Blockly.FieldDropdown(OPERATORS), 'OP');

	},
	onchange : function(event) {

		var mode = this.getFieldValue('OP');
		switch (mode) {

		case 'ADD':
			this.setOutput(true, 'String');
			break;

		case 'IS_NULL':
			this.setOutput(true, 'Boolean');
			break;

		}
	},
	mutationToDom : function() {
		var container = document.createElement('mutation');
		container.setAttribute('op', this.getFieldValue('OP'));
		return container;
	},
	domToMutation : function(xmlElement) {
		this.updateShape_test(xmlElement.getAttribute('op'));
	},
	updateShape_test : function(newOp) {
		switch (newOp) {
		case 'ADD':
			this.setOutput(true, 'String');
			break;

		case 'IS_NULL':
			this.setOutput(true, 'Boolean');
			break;
		}
	}
};

Please provide correct code for above scenario, if code i shared is incorrect .
Otherwise provide changes that is to be made in above code.

Thanks in advance

**Comment by NeilFraser** [comment]
Rather than use `this.setOutput(true, 'Type');` try using `this.outputConnection.setCheck('Type');`

That said, your approach makes sense and I'll adjust the code to support what you did.
