### ISSUE TITLE
Object.assign (ES6) in codebase

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#3153]
[Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) does not exist in any version of IE (according to MDN).
The following instances exist:

- [ ] [/core/keyboard_nav/key_map.js:81](https://github.com/google/blockly/blob/develop/core/keyboard_nav/key_map.js#L81)
- [ ] [/demos/keyboard_nav/index.html:328](https://github.com/google/blockly/blob/develop/demos/keyboard_nav/index.html#L328)
- [ ] [/demos/custom-fields/turtle/blocks.js:51](https://github.com/google/blockly/blob/develop/demos/custom-fields/turtle/blocks.js#L51) 

There are also three more in /package, but I don't know if they matter.

**Comment by rachel-fenichel** [comment]
@alschmiedt for the ones in keyboard nav

@BeksOmega for the one in the turtle demo

I think the ones in /package just derive from the ones in core and demos.

**Comment by samelhusseini** [comment]
The ones in package are used by the npm package. I’ll take a look at those. I remember testing IE with the npm package, so I wonder why that wasn’t caught.

**Comment by samelhusseini** [comment]
Turns out each framework patches in a polyfill. Except for our UMD sample, which is broken in IE. Will fix.

**Comment by samelhusseini** [comment]
Fixed.
