### ISSUE TITLE
Sizing of text inputs fields in mutator workspaces is broken

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3166]
**Describe the bug**
Text input fields in mutator workspace doesn't resize to the right size of the block. 

**To Reproduce**

1. Go to the playground.
2. Drag out a procedure block
3. Open the mutator dialog
4. Drag out an input x block
5. Click on the x field to change its name.

**Expected behavior**

The field's input box should resize to the size of the field. 

**Screenshots**

<img width="371" alt="Screen Shot 2019-10-04 at 2 36 18 PM" src="https://user-images.githubusercontent.com/16690124/66241801-bb286800-e6b4-11e9-9b1f-77e86bc12562.png">

Repro's on Safari and Chrome, probably others too.

**Additional context**

Affects RC/Oct_2019

**Comment by samelhusseini** [comment]
Looks like you need to be zoomed in to repro this, so an issue with zoom as well.
Not a regression.

**Comment by rachel-fenichel** [comment]
Makes sense--mutators aren't actually zoomed because they're inside the parent svg that was zoomed, and I can see that getting out of hand.

**Comment by samelhusseini** [comment]
Fixed.
