### ISSUE TITLE
Empty mutator throws an error

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3167]
**Describe the bug**

Error thrown when opening the mutator dialog of the ``test_basic_empty_with_mutator`` block. 

**To Reproduce**

1. Go to the playground
2. Switch to the test blocks.
3. Under basic, drag out the second block, the empty block with the mutator dialog icon.
4. Open the dialog, see error.

**Expected behavior**

No error?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
mutator.js:269 Uncaught TypeError: this.block_.decompose is not a function
    at Blockly.Mutator.setVisible (mutator.js:269)
    at Blockly.Mutator.Blockly.Icon.iconClick_ (icon.js:135)
    at Blockly.Mutator.iconClick_ (mutator.js:115)
    at SVGGElement.wrapFunc (blockly.js:473)
```

**Additional context**

**Comment by RoboErikG** [comment]
I'm pretty sure that's WAI. decompose and compose are required to use the default mutator UI. https://developers.google.com/blockly/guides/create-custom-blocks/web/mutators#mixin_object
