### ISSUE TITLE
Keyboard Nav: Cursor not blinking in IE11

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3175]
**Describe the bug**
The cursor is not blinking in IE11.

**To Reproduce**
1. Enter keyboard navigation mode. 

Observe: The cursor is a solid red line.

**Expected behavior**

**Screenshots**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by gonfunko** [comment]
Closing since we've dropped support for IE.
