### ISSUE TITLE
Value to stack measurement incorrect

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#3176]
**Describe the bug**

If you have a block with an output and a next connection its width doesn't get measured correctly when it's attached to a parent block. 

![functionMismeasure](https://user-images.githubusercontent.com/11066279/66333268-691d5780-e8eb-11e9-9c56-3196b53cbd4e.png)

**To Reproduce**

1. Open the playground
2. Switch to the test blocks
3. Drag out a value to stack block from the basic category
4. Attach a print Drag me by this child block from the drag category
5. Drag out a 10 = 10 block from the mutators category
6. connect the value to stack to one of the inputs on the 10 = 10 blocks

**Expected behavior**

Input grows to wrap entire stack of blocks, but instead there's a small overlap between the print and the parent block.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by RoboErikG** [comment]
Note, I'm pretty sure the overlap is the output connection distance. I think it's finding the max width and assuming an overlap with the output, but because only the first block has an output we end up with an output sized overlap on the right side.

**Comment by rachel-fenichel** [comment]
The debug rectangles will help to diagnose the actual problem.

**Comment by RoboErikG** [comment]
Yeah, that's what led me to think it's the output connection distance. There's no rectangle that goes around the whole stack, only individual blocks.

**Comment by samelhusseini** [comment]
Fixed.
