### ISSUE TITLE
Dropdown menus on iOS move around when page is zoomed

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3178]
**Describe the bug**
Dropdown fields slide around when zooming on an ios device. 

**To Reproduce**
1. Open playground on ios device
2. Open a dropdown
3. Zoom outside of workspace.

Observe: The dropdown slides around as user zooms in.
**Expected behavior**
The dropdown should stay in the same location. 

**Screenshots**
![IMG_20191007_104525](https://user-images.githubusercontent.com/23059043/66336114-5443c280-e8f1-11e9-9fbc-966f90adc817.jpg)

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by samelhusseini** [comment]
This is a generic problem with dropdownDiv by the looks of it. Widgetdiv doesn't have the same behaviour. Angle picker, colour field, and pretty much any field that uses the dropdown div is also affected by this.

**Comment by samelhusseini** [comment]
Fixed.
