### ISSUE TITLE
Variable field validator test block is breaking

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#3184]
**Describe the bug**

If a variable field gets unset Blockly crashes when the dropdown is opened.

**To Reproduce**

1. Open the playground and select test blocks
2. Drag out the always a 1 variable validator
3. Rename the variable from '1a' to 'foo'
4. Open the dropdown and select 'foo'
5. try to open the dropdown again

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Uncaught Error: Tried to call dropdownCreate on a variable field with no variable selected.
    at Blockly.FieldVariable.dropdownCreate [as menuGenerator_] (field_variable.js:401)
    at Blockly.FieldVariable.Blockly.FieldDropdown.getOptions (field_dropdown.js:394)
    at Blockly.FieldVariable.Blockly.FieldDropdown.dropdownCreate_ (field_dropdown.js:239)
    at Blockly.FieldVariable.Blockly.FieldDropdown.showEditor_ (field_dropdown.js:207)
    at Blockly.TouchGesture.Blockly.Gesture.doFieldClick_ (gesture.js:732)
    at Blockly.TouchGesture.Blockly.Gesture.handleUp (gesture.js:588)
    at Blockly.TouchGesture.handleUp (touch_gesture.js:195)
    at HTMLDocument.wrapFunc (blockly.js:475)

  | Blockly.FieldVariable.dropdownCreate | @ | field_variable.js:401
-- | -- | -- | --
  | Blockly.FieldDropdown.getOptions | @ | field_dropdown.js:394
  | Blockly.FieldDropdown.dropdownCreate_ | @ | field_dropdown.js:239
  | Blockly.FieldDropdown.showEditor_ | @ | field_dropdown.js:207
  | Blockly.Gesture.doFieldClick_ | @ | gesture.js:732
  | Blockly.Gesture.handleUp | @ | gesture.js:588
  | Blockly.TouchGesture.handleUp | @ | touch_gesture.js:195
  | wrapFunc | @ | blockly.js:475


```

**Additional context**

**Comment by BeksOmega** [comment]
I think this might be WAI.

If the developer's local validator returns something invalid, that's their problem. We expect it to be valid.

We don't currently validate things returned from a validator, as noted in... I think the jsdoc of the dropdown field, or maybe the actual doc.

**Comment by RoboErikG** [comment]
Worth fixing the crash. For this release if the fix is safe/easy.

**Comment by samelhusseini** [comment]
Looking into this further, I also think this is WAI.
The assumption in each of the doValueUpdate_ methods is that the option has been run by the validator. If the local validator returns an invalid option that's not in the dropdown list, then it'll have various side effects.
This is all because the local validator is given the final go at changing the value. We could make it so the class validator is run after the local validator,  but that would make what the local validator can do more restrictive.

I think it's fair to assume that the local validator returns a valid value. In this case it doesn't unless you hit the "Add test variables" button before adding the blocks onto the workspace.

**Comment by samelhusseini** [comment]
I'd be happy to close this unless @RoboErikG has other concerns.

**Comment by samelhusseini** [comment]
Related to https://github.com/google/blockly/issues/3185

**Comment by RoboErikG** [comment]
My worry is that setting an invalid value on field variable can be a runtime error that the user triggers. It looks like this error has been there for at least 2 years, though, so agree it's not a high priority.

**Comment by maribethb** [comment]
Closing for reasons stated by Beka and Sam above, and because we have documentation about it. Rachel is adding a sentence to the document linked by Beka above that says the behavior is undefined if your validator does not adhere to the spec.
