### ISSUE TITLE
Inline Input Width Incorrect - Minimalist Renderer

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3191]
**Describe the bug**

Inline inputs do not have the correct size when a block with external inputs is connected to the inline input:
![Inline1](https://user-images.githubusercontent.com/25440652/66357009-098e6e80-e922-11e9-8ef7-d8c7bf291c19.png)

Works:
![Inline4](https://user-images.githubusercontent.com/25440652/66357310-21b2bd80-e923-11e9-9188-111f2aec2e04.png)

**To Reproduce**

1. Go to the playground.
2. Switch to the minimalist renderer.
3. Load the following XML:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="logic_compare">
    <field name="OP">EQ</field>
    <value name="B">
      <block type="logic_ternary">
        <value name="IF">
          <block type="logic_ternary"/>
        </value>
      </block>
    </value>
  </block>
</xml>
```

**Expected behavior**

The inline input should surround any blocks it contains.

**Screenshots**

![Inline2](https://user-images.githubusercontent.com/25440652/66357079-55411800-e922-11e9-887d-91d359c93c1f.png)
![Inline3](https://user-images.githubusercontent.com/25440652/66357082-570adb80-e922-11e9-899d-07a98e70a3a8.png)

**Additional context**

It feels like it should be related to `getHeightWidth`:
```
Blockly.BlockSvg.prototype.getHeightWidth = function() {
  var height = this.height;
  var width = this.width;
  // Recursively add size of subsequent blocks.
  var nextBlock = this.getNextBlock();
  if (nextBlock) {
    var nextHeightWidth = nextBlock.getHeightWidth();
    height += nextHeightWidth.height - 4;  // Height of tab.
    width = Math.max(width, nextHeightWidth.width);
  }
  return {height: height, width: width};
};
```

But idk why I can't get it to reproduce in geras or thrasos :(

-- Maybe affects hackathon? --

Related to #3176

**Comment by BeksOmega** [comment]
Ha! I tracked down the issue.

The problem is that the row.widthWithConnectedBlocks and block.widthWithChildren are not adjusted when the row widths are changed to make the block square.

Notice how the block bounds change when I move the 'not' block:
![BlockWidth](https://user-images.githubusercontent.com/25440652/66876915-657f7580-ef68-11e9-9e56-82db8f42761c.gif)

And here's a good picture of what's happening:
![BlockWidth2](https://user-images.githubusercontent.com/25440652/66877028-cc049380-ef68-11e9-8d40-9764367e65c1.png)

As you can see the green dashed lines (which show the row.widthWithConnectedBlocks property), are not as wide as they should be.

No clue how to fix that though haha.

**Comment by rachel-fenichel** [comment]
Nice debug.  It looks like `addAlignmentPadding` does more in Geras than in core (which we knew) but that some of the work in Geras should be moved over to core.

**Comment by rachel-fenichel** [comment]
(make that common, not core)
