### ISSUE TITLE
workspace.updateToolbox broken in latest drop

### ISSUE THREAD

**Issue by pelikhan** [google/blockly#320]
![image](https://cloud.githubusercontent.com/assets/4175913/14350899/01bf01ba-fc81-11e5-991f-e5726d3f5f6e.png)

I suspect broken by https://github.com/google/blockly/commit/0686762a12bbfa87afafe9ac5c6bb95ae6ebea1b

**Comment by NeilFraser** [comment]
This has been checked into the develop branch and will land in master shortly.
