### ISSUE TITLE
Insertion markers sometimes trigger ternary block to change type checks

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#3204]
**Describe the bug**

When dragging a boolean block out of a ternary block it sometimes causes the ternary to pop out of its parent.

**To Reproduce**

1. Connect a ternary to a repeat block
2. connect a false block to the first input on the ternary
3. drag the false block down off the ternary so it crosses the if true/false inputs
4. the ternary sometimes disconnects.

**Expected behavior**

Ternary should stay connected, instead it disconnects.

**Screenshots**

![image](https://user-images.githubusercontent.com/11066279/66450185-71b97f00-ea0c-11e9-9470-b852fbdd0543.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by MNSDivya** [comment]
Issue still persists.

**Comment by moniika** [comment]
Unable to repro.
