### ISSUE TITLE
Script for publishing blockly-demo to app engine

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3209]
**Is your feature request related to a problem? Please describe.**
Script for publishing blockly-demo to app engine

**Describe the solution you'd like**

With gcloud being an npm package: https://www.npmjs.com/package/gcloud, we can add it as a dev dependency and have a deploy script that deploys the app to appengine.

**Additional context**

**Comment by NeilFraser** [comment]
Currently one just pushes the "Deploy" button in GoogleAppEngineLauncher.  This way it's not an option that external developers end up with.  Not sure what problem we're trying to solve here.

**Comment by rachel-fenichel** [comment]
The problem we're solving for is that we have a lot of manual steps for deployment.  Each one is pretty simple, but it would be better to tie them all together into a script.

As a bonus, I believe the google app engine launcher is both deprecated and doesn't work on linux.

@samelhusseini I'm also down to have this in a separate repo with the rest of our tooling, though that seems unnecessary.

**Comment by RoboErikG** [comment]
Any issue with putting it in blockly-tools?

**Comment by rachel-fenichel** [comment]
Mostly that the rest of our releasing stuff is over here (in the `scripts` section in `package.json`), and we've been moving toward being able to just say `npm run release`.  Pulling in blockly-tooling and linking everything adds complexity and seems nonstandard.

**Comment by moniika** [comment]
Fixed in https://github.com/google/blockly/pull/4551
with the caveat that the npm package `gcloud` is deprecated and so gcloud needs to be manually set up at first.
