### ISSUE TITLE
How to add a block into block into canvas with js code.

### ISSUE THREAD

**Issue by codeskyblue** [google/blockly#321]
For example:

```
workspace.addBlockToCanvas('<block><field name='text'><value>123</value></field></block>')
```

Maybe not a good code. Just want some help about how to implement this function.

**Comment by codeskyblue** [comment]
Can someone show some hint?

**Comment by NeilFraser** [comment]
```
var xml = Blockly.Xml.textToDom('<xml><block type="text" x="100" y="50"><field name="TEXT">123</field></block></xml>');
Blockly.Xml.domToWorkspace(xml, workspace);
```

**Comment by codeskyblue** [comment]
Thanks a lot.

**Comment by ceides9497** [comment]
Nice... thanks... but I have a question... @NeilFraser with this way I put the block '<xml><block type="math_arithmetic"><value name="A"> <shadow type="math_number"> <field name="NUM">1</field> </shadow> </value> <value name="B"> <shadow type="math_number"> <field name="NUM">1</field> </shadow> </value> </block></xml>'

right? but... I can't drag the different block it's like a one block... please... do you have a solution for this?

**Comment by picklesrus** [comment]
Hi @ceides9497  I don't believe what you're reporting is a bug so you're better off asking for help over on the Blockly mailing list/forum: https://groups.google.com/forum/#!forum/blockly

That said, I think you're confusing "blocks" and "shadow". See https://developers.google.com/blockly/guides/configure/web/toolbox#shadow_blocks and if you have a follow up, please ask over on the mailing list.
