### ISSUE TITLE
Script to bump version and tag release on master

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3210]
**Is your feature request related to a problem? Please describe.**

A late step in releasing is to bump the version on master and tag that commit.  This should be scripted.

**Comment by rachel-fenichel** [comment]
Formats:

Master:
Major version number is 3 after the q3 2019 release
major.yyyymmdd.patch

Develop:
Builds off the most recent release to master.
major.yyyymmdd.patch-develop

This complies with semver.

**Comment by samelhusseini** [comment]
The version in the blockly_compressed is pulled from the package.json.
As part of this change, we should make sure that the version is bumped before a re-build so that the latest version is bundled into the release candidate.
