### ISSUE TITLE
Blockly.JavaScript.workspaceToCode is missing 

### ISSUE THREAD

**Issue by yuanwei92** [google/blockly#3220]
Based on [documentation](https://developers.google.com/blockly/guides/configure/web/code-generators), JavaScript code could be generated by

`var code = Blockly.JavaScript.workspaceToCode(workspace);`

But in the javascript_compressed.js, workspaceTocode functions is missing. How do I generate code from workspace? I get the error of "Cannot read property 'wrap' of undefined"

**Comment by samelhusseini** [comment]
Each of the generators extends from Blockly.Generator which has the workspaceToCode method on its prototype.

You would need to include blockly_compressed.js, with that you should be able to call the above code to generate code from the workspace.

You can see how it's done in the demos here: https://github.com/google/blockly/blob/master/demos/code/code.js
