### ISSUE TITLE
Developer site blocked in Iran

### ISSUE THREAD

**Issue by 0xaryan** [google/blockly#3221]
I was just trying to build up a nuclear weapon! using blocks in the blockly website, but then I saw that I can't even access this site.

![image](https://user-images.githubusercontent.com/9091958/66697038-bb40ed00-ecde-11e9-92a6-bcf31735aaaf.png)

Thank you, Google! for saving the world from me, a criminal whose crime is that I live in Iran.

I wish you more success by showing more and more 403s to people in specific regions because as you already know, banning is always the solution to everything, no matter the target is innocent or sinful.

Best regards

**Comment by 0xaryan** [comment]
but who cares? I close this.

**Comment by NeilFraser** [comment]
Actually, that's important for us to know.  Are you reporting that https://developers.google.com/blockly is blocked in Iran?  If so, could you also check the site's root page at https://developers.google.com

US companies are prevented from publishing cryptography algorithms in places such as Iran, and some projects on developers.google.com do involve crypto.  However Blockly does not and there is no reason why we shouldn't be visible.

If you can confirm if each of those two links go 403 for you, and that you are indeed in Iran, then we can look into it for you.

**Comment by 0xaryan** [comment]
Thank you for the reply

I'm in Iran, and I can confirm both links https://developers.google.com/blockly and  https://developers.google.com are unavailable (403).

It looks like while it is possible to leave free parts available (Microsoft's approach), Google bans the whole service if a part of the service is commercial -or- has a strategic impact(as you already mentioned). For example, Google banned Iran from the whole of its Analytics product because of Ad Words feature (googletagmanager still collects Iranians info without any problem tho).

Besides all these, it was surprising for me to see blockly is not accessible from Iran, while it seems there is no commercial feature or strategic ones in it. To be honest, the only thing came into my mind was that Google is just trying to do some harassment.

**Comment by NeilFraser** [comment]
Thanks!  I've raised the issue with the team that runs Google's developer's site to see what's possible (both technically and legally).  Will let you know what we find out.

I've spent the past hour reading about the US embargo on your country.  It is an immensely complicated set of regulations dating back 40 years.  Definitely something that only our lawyers will be able to accurately interpret.

**Comment by NeilFraser** [comment]
Just a follow-up to say that we are still working on this problem.  For better or worse, lawyers are now involved.

**Comment by 0xaryan** [comment]
Thank you so much for your investigation. Even if lawyers decide not to unblock any of those websites, I'm happy because at least there were efforts by Googlers who tried to change that.

**Comment by NeilFraser** [comment]
Another quick update.  Lawyers were helpful and we are making progress.  @RoboErikG is handling the implementation.

**Comment by 0xaryan** [comment]
That's awesome news. Thank you @NeilFraser

**Comment by RoboErikG** [comment]
developers.google.com/blockly should now be accessible in all countries. The only thing we couldn't get permission to unblock is the live demo on the landing page, but all the static documentation should be accessible. Please let us know if you still can't access the content.
