### ISSUE TITLE
Text of hidden fields is shown when blocks are collapsed

### ISSUE THREAD

**Issue by MatzElectronics** [google/blockly#3223]
**Describe the bug**
Example block (with a hidden field):
![image](https://user-images.githubusercontent.com/19737272/66710332-e9e4b500-ed2a-11e9-8c15-dced0d9083c1.png)
When a block is collapsed, the text of any hidden fields becomes visible:
![image](https://user-images.githubusercontent.com/19737272/66710336-01bc3900-ed2b-11e9-9a5c-2185ebdd4dc3.png)
Expanding the block again does not re-hide the fields either:
![image](https://user-images.githubusercontent.com/19737272/66710341-303a1400-ed2b-11e9-83d8-7df4e1bdf718.png)

**To Reproduce**
1. Create a block with a hidden field.  
2. Collapse the block. (this makes the error visible)
3. Re-expand the block. (error continues to be visible)

**Expected behavior**
Hidden field text should not be included in the text of a collapsed block, and re-expanding the block should not alter the visibility of a field.

**Desktop (please complete the following information):**
 - OS: MacOS, Windows 10
 - Browser: Chrome, Firefox

**Comment by samelhusseini** [comment]
Hey @MatzElectronics, I'm not aware of us supporting visibility of specific fields. How are you setting certain fields as visible / hidden?

**Comment by MatzElectronics** [comment]
It's a method for fields in the blockly core:
```
/**
 * Sets whether this editable field is visible or not. Should only be called
 * by input.setVisible.
 * @param {boolean} visible True if visible.
 * @package
 */
Blockly.Field.prototype.setVisible = function(visible) {
  if (this.visible_ == visible) {
    return;
  }
  this.visible_ = visible;
  var root = this.getSvgRoot();
  if (root) {
    root.style.display = visible ? 'block' : 'none';
  }
};
```

You can just call it on a field:
```
Blockly.Blocks.my_new_block = {
  init: function() {
    this.setStyle('loop_blocks');
    this.appendStatementInput('S1')
        .appendField('Visible text', 'VIS')
        .appendField('Hidden text', 'HID');
    this.getField('HID').setVisible(false);
  }
}
```

**Comment by samelhusseini** [comment]
Right, that method is used internally by blockly to set the visibility of fields (eg: when blocks are collapsed). It's not meant as a public API. (Notice how the method is marked as @package, the description also mentions it should only be called by input.setVisible).

Now, to understand a little more about what got you here, could you describe a little more about what you're trying to achieve by setting fields as hidden / visible?

**Comment by MatzElectronics** [comment]
Sure,  we use it a lot within mutators, and we use mutators a lot to "guide" users to do things like use the correct pins on a microcontroller, etc.

Here's an example of a block definition that we show and hid fields in:
```
Blockly.Blocks.GPS_date_time = {
    helpUrl: Blockly.MSG_GPS_HELPURL,
    init: function () {
        var timeZones = [['UTC+0', '0']];
        for (var tz = -1; tz != 0; tz--) {
            if (tz < -12) {
                tz = 14;
            }
            timeZones.push(['UTC' + (tz > -1 ? '+' : '') + tz.toString(10), tz.toString(10)]);
        }
        this.setTooltip(Blockly.MSG_GPS_VELOCITY_TOOLTIP);
        this.setColour(colorPalette.getColor('input'));
        this.appendDummyInput()
                .appendField("GPS current ")
                .appendField(new Blockly.FieldDropdown([
                    ["year", "GPS_UNIT_YEAR"],
                    ["month", "GPS_UNIT_MONTH"],
                    ["day", "GPS_UNIT_DAY"],
                    ["hour", "GPS_UNIT_HOUR"],
                    ["minute", "GPS_UNIT_MINUTE"],
                    ["second", "GPS_UNIT_SECOND"]
                ], function (unit) {
                    var zone_label = this.sourceBlock_.getField('ZONE_LABEL');
                    var zone_value = this.sourceBlock_.getField('ZONE_VALUE');
                    if (unit === 'GPS_UNIT_HOUR' ||
                            unit === 'GPS_UNIT_DAY' ||
                            unit === 'GPS_UNIT_MONTH' ||
                            unit === 'GPS_UNIT_YEAR') {
                        zone_label.setVisible(true);
                        zone_value.setVisible(true);
                    } else {
                        zone_label.setVisible(false);
                        zone_value.setVisible(false);
                    }
                    var currBlockTimeout = this.sourceBlock_;
                    setTimeout(function() {
                        currBlockTimeout.render();
                    }, 200);
                }), "TIME_UNIT")
                .appendField("time zone", 'ZONE_LABEL')
                .appendField(new Blockly.FieldDropdown(timeZones), "ZONE_VALUE");
        this.setOutput(true, 'Number');
        this.setNextStatement(false, null);
        this.setPreviousStatement(false, null);
        this.getField('ZONE_LABEL').setVisible(false);
        this.getField('ZONE_VALUE').setVisible(false);
    },
    mutationToDom: function () {
        var container = document.createElement('mutation');
        container.setAttribute('unit', this.getFieldValue('TIME_UNIT'));
        return container;
    },
    domToMutation: function (xmlElement) {
        var ut = xmlElement.getAttribute('unit');
        if (ut === 'GPS_UNIT_HOUR' ||
                ut === 'GPS_UNIT_DAY' ||
                ut === 'GPS_UNIT_MONTH' ||
                ut === 'GPS_UNIT_YEAR') {
            this.getField('ZONE_LABEL').setVisible(true);
            this.getField('ZONE_VALUE').setVisible(true);
        } else {
            this.getField('ZONE_LABEL').setVisible(false);
            this.getField('ZONE_VALUE').setVisible(false);
        }
    },
    onchange: function () {
        var allBlocks = Blockly.getMainWorkspace().getAllBlocks().toString();
        if (allBlocks.indexOf('GPS module initialize') === -1)
        {
            this.setWarningText('WARNING: You must use a GPS module\ninitialize block at the beginning of your program!');
        } else {
            this.setWarningText(null);
        }
    }
};
```

For what it's worth - I'm open to suggestions for other ways to accomplish this.  Field visibility is buggy and often requires a render call in a timeout, which feels very much like a hack.

**Comment by RoboErikG** [comment]
The way that's done is to [remove or add the field](https://developers.google.com/blockly/guides/create-custom-blocks/web/mutators#mutationtodom_and_domtomutation) on the block model in the mutator. It's definitely more work than just changing the visibility, but as Sam said visibility isn't really supported for most cases.

**Comment by rachel-fenichel** [comment]
I remember we discussed this over breakfast, and it sounded like you were using the hidden fields as a way to store data on the block.  I agree that mutators are a good way to do this; you could also use the `data` [attribute](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#block_data_web_only), though that will serialize in addition to your mutator.

I think the key is that from `domToMutation` you are allowed to just set properties on the block, as long as you keep track of which properties exist and what values they have.

**Comment by MatzElectronics** [comment]
Thank you for the help - I've been able to refactor nearly all uses of this out of our block definitions, and I believe this issue can now be closed.
