### ISSUE TITLE
More control over how themes are applied to path_objects

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3233]
### Is your feature request related to a problem? Please describe.

For the Blockly Summit 2019 Hackathon I wanted to create a block that had different border widths on the top-left than on the bottom-right.

To do this I created a custom path_object (which held the top-left border, the inside, and the bottom-left border), but then themes did not know how to apply colours to my new path_object.

This is because updating themes is handled by the blockSvg, which expects specific properties on the path_object.

#### Allow the Path_Object to handle colour updates
The path_object interface gains the following functions:
* setStyle(style)
* setShadow(style)
* setDisabled(style)

The path_object can then apply colours (and other css properties for that matter) to its svg elements in any way it desires.

I also think the following properties should be added to the style interface. They currently exist on the block (I believe) but those could easily be made into facade-functions that just pass the responsibility to the style.
* getColourPrimary
* getColourSecondary
* getColourTertiary
* getColourShadow
* getColourBorder
* getColourMain <- Currently exists as getColour

Giving the responsibility to the style would keep the path_object from having knowledge of the block.

#### Set colours automatically based on css class names
Path_objects would be responsible for applying class names to the different elements, which would tell the themes how to apply colours to the different svg elements.

E.g. The path_object would apply a `blocklyBorderColourStroke` class to every svg element that you want to have a stroke value of the border colour.

I don't like this solution as much because you'd end up needing a class for everything a developer would want to do.

For example: What if a developer wanted shadow blocks to have borders?
* `blocklyShadowBorderColourStroke`

Then what if they wanted shadow blocks to have the primary colour as the border instead of the normal border colour?
* `blocklyShadowPrimaryColourStroke`

And as things get added to styles (e.g. stroke width, stroke dashes, opacity, etc) It would just get more and more complicated to maintain these.

### Additional context

N/A

**Comment by rachel-fenichel** [comment]
@BeksOmega we've made a bunch of changes to how path objects work and interact with styles, including that they go through constants, and that constants get refreshed when themes change.  Can you take a look and comment on those APIs?

**Comment by BeksOmega** [comment]
Confirmed! It is now possible to apply colours to a pathobject in a render-specific fasion. Thanks for the fix!
