### ISSUE TITLE
Tooltips mispositioned in IE11

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3234]
**Describe the bug**

Tooltips show up somewhere else on the screen, rather than directly over the block/field/mouse.

**To Reproduce**
Go to the playground in IE11
Drag out any block
Hover and wait for the tooltip.

**Comment by samelhusseini** [comment]
I'm not able to repro this. Could you confirm if this was tested on saucelabs or on a physical machine?

**Comment by rachel-fenichel** [comment]
Sauce labs.
