### ISSUE TITLE
Angle picker round 30 validator setting the wrong value

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#3235]
**Describe the bug**

There seems to be an issue with the round 30 validator in the playground's test blocks. It looks like it's setting the field to the previous value that was dragged over instead of the value that was selected.

Might be related to #2012 

![roundingIssue](https://user-images.githubusercontent.com/11066279/66774476-7c459f80-ee76-11e9-9cf8-35313af32f34.gif)

**To Reproduce**

1. Open the playground and switch to test blocks
2. drag out the round 30 block from the test angle category

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by RoboErikG** [comment]
Oh, it's actually that there's a fade out on the picker and the value can still be changed while it's fading out.

**Comment by samelhusseini** [comment]
Yeah, this is fixed by https://github.com/google/blockly/pull/3202
But we thought we wouldn’t pull that in to the release. Seeing that there’s another way to repro this, perhaps we should consider.

**Comment by samelhusseini** [comment]
@rachel-fenichel

**Comment by rachel-fenichel** [comment]
Still okay with not pulling it in.  Even if you select the wrong value, it's easy to go back and select the right value--so annoying, but not world-breaking.
