### ISSUE TITLE
Let Cursors handle most Blockly Actions

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#3244]
**Is your feature request related to a problem? Please describe.**

Right now, Blockly.navigation handles the vast majority of actions created by key events. This means there's one file that handles all the logic related to actions and adding support for new actions is cumbersome and requires modifying the core library.

**Describe the solution you'd like**

Blockly.navigation should only be handling switching between top level entities (toolbox/flyout, trashcan flyout, and workspace) and otherwise pass those events along to the currently active Cursor to handle. This will allow the logic for handling to be localized and easily replaceable on each top level Blockly component.

This would mean that the Cursor on the main workspace implements an onAction(Blockly.Action) method which handles previous, out, next, in, insert, mark, and disconnect. This would also allow new actions to be added and handled by supplying a custom Cursor that overrides onAction.

**Describe alternatives you've considered**

**Additional context**

**Comment by rachel-fenichel** [comment]
@alschmiedt What is the remaining work on this?

**Comment by alschmiedt** [comment]
I think we can close this one. There is some work remaining for easily allowing toolbox shortcuts, but I think that is a different feature request.
