### ISSUE TITLE
Cleanup can appear to delete all blocks.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#3248]
Video:
https://youtu.be/ErPs6SbDpDw

It used to be that scrollbars would auto-bump themselves, so that at least one block would always be onscreen (unless there were two blocks separated from each other by more than a workspace width).  This is no longer the case.

If this was not a deliberate change, then fixing it would mean that the dragged 'if' blocks would appear on the right margin at the start of the video, and the left margin at the end of the video.  On the other hand, if this was a deliberate change, then (at a minimum) cleanup should center on the origin.

**Comment by samelhusseini** [comment]
Fixed by #3274.
