### ISSUE TITLE
Modifying the row height inside recordElemPositions_ is not supported

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3249]
**Is your feature request related to a problem? Please describe.**

I am creating a renderer that tries to align rows on a single baseline.

Because of this I need to modify the height of the row inside the getElemCenterline_ method.

With Height Adjustment:
![YCursor_WithHeight](https://user-images.githubusercontent.com/25440652/66792166-60f58700-eeac-11e9-8f57-b0620fe3d916.png)

Without Height Adjustment:
![YCursor_NoHeight](https://user-images.githubusercontent.com/25440652/66792170-6357e100-eeac-11e9-832e-a888d3890212.png)

To get the height adjustment to work [this line](https://github.com/google/blockly/blob/8874e58f912ec2ed58e7c4216751dd6caf2ccbb1/core/renderers/common/info.js#L688) `yCursor += row.height;` needs to come after `recordElementPositions_` b/c the row height is being modified inside `recordElementPositions`

Otherwise I get this:
![YCursor_StartFunction](https://user-images.githubusercontent.com/25440652/66792229-a9ad4000-eeac-11e9-8e33-53e0292f3a9a.png)

**Describe the solution you'd like**

It would be great if the `yCursor += row.height;` line could just be moved to the end of the loop. But idk if you want to support setting the row height inside of `recordElemPositions_` or not.

**Describe alternatives you've considered**

* Don't allow this behavior. Maybe there's a better place I could put this.
* You could have subclasses override the function & move the one line.

**Additional context**

N/A

**Comment by rachel-fenichel** [comment]
I think there's a better place to put the code, which is in measure on the row.  At that point all of the elements in the row should have been measured (including child blocks) and I think you should be able to find the correct row height and centerline from there.

Right now `recordElemPositions_` only changes information on the elements in the row--it never modifies the row itself.  I think that's correct, and maybe I should add that in the comment on that function.

**Comment by BeksOmega** [comment]
So moving the code to `measure` works, but it still doesn't feel quite right. Because now the row is modifying properties of its elements (i.e. `centerline`). See [this paste](https://pastebin.com/YZd8LVMD).

My getElementCenterline_ method is also a bit weird as a result.
```
Blockly.baseline.RenderInfo.prototype.getElemCenterline_ = function(row, elem) {
  if (elem.centerline) {
    return elem.centerline + row.yPos;
  }
  return row.yPos + row.height / 2;
}
```
But the finalize method no longer needs to be modified! So that's rad.

**Comment by rachel-fenichel** [comment]
This can be done by subclassing parts of the renderer.
