### ISSUE TITLE
Proposal: Replace SVG Rendering with CSS3 DIVs

### ISSUE THREAD

**Issue by adammunich** [google/blockly#3251]
CSS has come a long way since when blockly was first conceptualized, and, much of what the SVG renderer does now can be accomplished with native HTML & CSS

There seems to be a great deal of interest in styling blockly among its users --why not let the CSS engine handle all of this hard work for us instead of writing custom theme APIs? It seems like it could save a lot of work in the long run.

All we would need to do is apply classes to the blocks and their components during the render, then properties like their color, padding, etc, can be set by the user with a stylesheet.

**Comment by samelhusseini** [comment]
Color is a simple one, and that today can be delegated over to the CSS with a class.
I'm not sure I see how you would get an HTML div to look like a block. Would you be able to describe your proposal a little more?

**Comment by adammunich** [comment]
I think the way I would approach it is to use the absolute positioning features of block divs. 

In the case of a puzzle piece, the body of the piece can be made with a square block and border-radius, whilst the puzzle cut-outs can be child divs positioned absolutely and ordered with z-index. In this way, if the shape of the puzzle piece changes, then all the cut-outs are re-positioned automatically 

(eg: ones placed to the bottom with bottom:0, transformY(-100%) will move as the size of the block is changed)

These cut-outs can be SVGs or themselves made from CSS attributes.

**Comment by adammunich** [comment]
I made a blockly block entirely out of CSS. All the dimensions are automatically calculated by the browser.

![image](https://user-images.githubusercontent.com/3454296/66903677-c4b8a680-efb7-11e9-8d2a-3990f2e0a165.png)

https://codepen.io/adam-munich/pen/xxxOgBz

I am very good at designing with CSS, but don't understand enough about the inner workings of blockly to replace the renderer. If someone who understands the renderer, could modify it to generate HTML DOM elements instead of SVGs, I could style them pretty easily I think.

**Comment by RoboErikG** [comment]
Looking through your example I can see how making specific blocks isn't too hard, but building complex blocks dynamically or with less standard shapes would be significantly more difficult using CSS.

For example, doing the sizing and alignment between blocks as they connect and disconnect, as well as the puzzle tabs on inputs/outputs would involve generating quite a bit of CSS and figuring out how to layer quite a few pieces to get the right shape. SVG lets us draw shapes directly to exactly match our contents instead of assembling them out of layered parts.

![image](https://user-images.githubusercontent.com/11066279/66937455-53e3af80-eff4-11e9-84e3-41304e05872e.png)

![image](https://user-images.githubusercontent.com/11066279/66937581-88f00200-eff4-11e9-8b53-a1d494a2942f.png)

Doing smooth corners also seems like a problem as you need to layer rounded corners and circles very carefully to get arbitrary shapes, or fall back to just specifying an svg path as a clip-path (which isn't well supported).

It's an interesting idea, but rewriting rendering to use CSS instead of SVG at this point would be a significant amount of work and a significant cost to all of our existing developers without a clear gain.

**Comment by samelhusseini** [comment]
I'd also add, although your demo doesn't use CSS3.
CSS3 isn't available on IE11 and IOS Safari so we wouldn't go down that route to maintain cross browser compatibility.

**Comment by adammunich** [comment]
@RoboErikG Not necessarily, since DOM elements will calculate their dimensions based on the size of the contents this should be very straight forward to accomplish.

![image](https://user-images.githubusercontent.com/3454296/66945072-408c1080-f003-11e9-9210-0cd1ec9efa77.png)

I think blockly is in a pickle with the limitations of the SVG renderer. 

It's really important for a developer to choose their own look and feel for the system, because when kids see applications with blockly blocks, if kids have had a bad experience previously with them in another application, it's an immediate turn-off and they lose interest right away. 

CSS3 is absolutely available in IOS! Most of the rules work in browsers as old as IE11, except for the very newest ones. https://www.w3schools.com/cssref/css3_browsersupport.asp

**Comment by rachel-fenichel** [comment]
@adammunich Testing this should be reasonably straightforward for you, even on complicated blocks.

You'll want to read through the [quickstart guide](https://sites.google.com/corp/view/blockly-user-summit-2019/hackathon/rendering-quick-start) from the rendering hackathon and then replace the default drawer.js entirely.  All of the sizing information is there, so you can test out your theory about absolute positioning.  When you've got a demo that handles most of the blocks in the playground, send it out and we'll take a look.

**Comment by adammunich** [comment]
It looks like that link is private

**Comment by rachel-fenichel** [comment]
My bad.  I replaced it with one that should be public.

**Comment by phptuts** [comment]
I know it would be a lot of work, but really like the idea.  I think it would help frontend developers contribute more to Blockly.   

@adammunich I am willing to work with you on this and see what comes out of this.  I would like to understand more on rendering anyways.

**Comment by samelhusseini** [comment]
As a starting point, I did a quick prototype of using ``<foreignobject>`` to add html elements in the block svg root.
You can find it [here](https://github.com/samelhusseini/blockly/tree/blockly_html_renderer).
To test, use the "Minimalist" renderer in the playground.

Of particular interest is the draw method [here](https://github.com/samelhusseini/blockly/blob/blockly_html_renderer/core/renderers/minimalist/drawer.js#L58).

**Comment by rachel-fenichel** [comment]
I'm with @RoboErikG in being fairly skeptical of this as a full replacement for the SVG renderer.

I think it's still an interesting thing to explore as an alternate renderer, especially for more limited block sets.  Either way, I'd like to hear what you learn as you explore this.

I know that one of the big things SVG gives us is that it handles checking if a point is inside or outside of a path.
