### ISSUE TITLE
Proposal: Standard dynamic plugin system for Blockly.

### ISSUE THREAD

**Issue by jollytoad** [google/blockly#3260]
**Is your feature request related to a problem? Please describe.**

Many customisations of Blockly require hacking of the core, either by forking or monkey patching.
There is also no standard way to write and publish a customisation (which I'll refer to as 'plugin' herein) for Blockly.

**Describe the solution you'd like**

A standard API within Blockly which can be used to register and unregister plugins into Blockly dynamically.
Blockly core and other plugins can define named hooks that any plugin can supply.
Plugins may also run initialisation and disposal code.
Plugins may supply Aspects (AOP) to augment behaviour of Blockly core features that don't leverage hooks.
Plugins can be implemented with any build system or transpiled language so long as they return a standard plugin spec object.
Plugins can be agnostic to the origin of Blockly itself - ie. we pass Blockly to the plugin.

**Describe alternatives you've considered**

**Additional context**

I've already started thinking about this, so i'll post some ideas later.

**Comment by jollytoad** [comment]
I've hacked an initial stab at the plugin system API, I've used TypeScript to define it, as I'm more familiar with this, although I'm not suggesting it will be implemented in TS.

I've put this in a gist so it can be evolved... https://gist.github.com/jollytoad/841545a2e55cee8c5b56d53f464a2b09

I'm not sure everything i've added would definitely be necessary. I'm going to try to implement the basics of the API and some example plugins.

I'd love to get some early feedback on this and whether it's something that would be considered for core Blockly, and whether other Blockly users would make use of it.

**Comment by jollytoad** [comment]
Take a look at my branch in the PR linked above for examples.

**Comment by jollytoad** [comment]
This could help with https://github.com/google/blockly/issues/3023 allowing features to be loaded/unloaded on demand

**Comment by RoboErikG** [comment]
Quick update: We've been discussing this internally and using your PR as one option for making this possible. Here's the summary of our internal discussions so far.

- We aren't really comfortable with making whole chunks of the library arbitrarily replaceable. This could make compatibility and maintenance a big problem as it's harder to define clear API boundaries with this approach.
- We do like the way Rendering is being done, using an API for registering/replacing components that conform to a specific API and extend a base class. We will probably try this approach with a few more components to see how well it generalizes.
- We also want to explore peer dependencies on npm. That seems like a good way to publish extensions for Blockly. We would encourage anyone building extensions using this to stick to public/protected APIs as package/private APIs are subject to change. These explorations will likely happen in the [blockly-samples repo](github.com/google/blockly-samples).

**Comment by jollytoad** [comment]
Thanks for the update @RoboErikG. I should clarify some of the reasoning behind what i've presented in the plugin API.
So ideally, plugins would use official extension points and public APIs only, but unfortunately that won't always be possible, and it may be sometime before the extension points and APIs exist even after they have been identified and planned for additional in an official release.
Whilst there are gaps like this, users will always need to fork or monkey patch to work-around - and everyone will end up doing that differently. So the point of the AOP style API is to allow users a standard way to do this until official extension points can be implemented, or for cases that are so specialised/quirky that there will never be a extension point.
It'll be a lot easier to share and communicate ideas for exceptional behaviour and extension points if we all follow a similar style.

I don't expect a plugin to override a massive chunk of the API - in fact that is the whole point of AOP really... atm I have to replace whole chunks of the API to satisfy some of our requirements, but with an AOP API can just inject behaviour exactly where I need it.

Regardless of whether this approach is accepted or not into the core we (and I expect many others) will still have to do our own monkey patching in one style or another - so we'll still need to maintain something like this anyway.

**Comment by rachel-fenichel** [comment]
We have picked a direction for plugins, so I'm closing this proposal.
