### ISSUE TITLE
Blockly.BlockSvg.START_HAT is broken

### ISSUE THREAD

**Issue by duzc2** [google/blockly#3279]
**Describe the bug**
if I set Blockly.BlockSvg.START_HAT = true
all blocks have a hat.

**To Reproduce**
just 
Blockly.BlockSvg.START_HAT = true

**Expected behavior**

only blocks with no previous or output connections have a 'hat' on top

**Screenshots**
![bug](https://user-images.githubusercontent.com/564778/66994479-e7ee6d80-f0ff-11e9-945a-65e72365a187.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 75

**Additional context**

I found someting like :
![bug1](https://user-images.githubusercontent.com/564778/66994809-79f67600-f100-11e9-8a7a-a5bf34b73f35.png)
it must think about hasPrevious and output.

**Comment by rachel-fenichel** [comment]
![image](https://user-images.githubusercontent.com/13686399/67052825-3f86dc00-f0f4-11e9-841d-4318e27fc798.png)

**Comment by samelhusseini** [comment]
This has been fixed and cherry-picked to master. Thanks for filing!
