### ISSUE TITLE
how to get new variables

### ISSUE THREAD

**Issue by yzxnwj** [google/blockly#3291]
Blockly.Blocks['block_type'] = {
  init: function() {
    this.appendDummyInput()
        .appendField(new Blockly.FieldVariable("item"), "NAME");
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour(230);
 this.setTooltip("");
 this.setHelpUrl("");
  }
};

Blockly.JavaScript['block_type'] = function(block) {
  var variable_name = Blockly.JavaScript.variableDB_.getName(block.getFieldValue('NAME'), Blockly.Variables.NAME_TYPE);
  // TODO: Assemble JavaScript into code variable.
  var code = '...;\n';
  return code;
};

**Comment by samelhusseini** [comment]
Please ask for help on our [forums](https://groups.google.com/forum/#!forum/blockly), not on the issue tracker.
