### ISSUE TITLE
workspace metrics incorrect when top block has hat

### ISSUE THREAD

**Issue by pelikhan** [google/blockly#330]
It seems that since https://github.com/google/blockly/commit/a67f841671dd5d61647ea4f159350e5823b69e69 the computation of a workspace metric does not take into account hats.

repro: create a workspace with a single hat block, measure size and compare to actual SVG size reported by the debugger.

**Comment by picklesrus** [comment]
Are there any hat blocks defined in the basic block set or blockly games I could use?  If not, how do I build one? Or maybe @pelikhan, you have a block definition I can borrow for testing?

**Comment by pelikhan** [comment]
Simple set BlockSvg.START_HAT = true to get hats on all events.

https://developers.google.com/blockly/custom-blocks/code-structure

There is also a related bug with the toolbox (if you want to fix 2 in 1 shot!!), if the first block has a hat, it bleeds off the top of the toolbox :)

Sent from Outlook Mobile<https://aka.ms/djubve>




On Tue, Apr 12, 2016 at 8:17 AM -0700, "picklesrus" <notifications@github.com<mailto:notifications@github.com>> wrote:


Are there any hat blocks defined in the basic block set or blockly games I could use? If not, how do I build one? Or maybe @pelikhan<https://github.com/pelikhan>, you have a block definition I can borrow for testing?

-

**Comment by picklesrus** [comment]
Thanks for the pointer!

I put together a fix, though it feels a bit brittle :-/  We'll see if @NeilFraser has any better ideas.

**Comment by NeilFraser** [comment]
Merged.  Thanks!
