### ISSUE TITLE
If statement doesn't update connections after mutation change

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3305]
**Describe the bug**

After using the if statement mutator UI to add else / elseif sections, connections aren't updated on the block and so dragging a block near the elseif or else sections of the block don't allow you to connect or show an insertion marker.

**To Reproduce**

1. Go to the playground
2. Drag an if statement block
3. Use the gear wheel mutator to add an elseif
4. Attempt to connect any block in the else section of the block.
Notice how you're unable to connect.

**Expected behavior**

Connection info should update after a mutation.

**Additional context**

This affects develop only and was introduced by [this](https://github.com/google/blockly/pull/3133) change.

**Comment by BeksOmega** [comment]
Can grab.

**Comment by samelhusseini** [comment]
Fixed.
