### ISSUE TITLE
Python generation error

### ISSUE THREAD

**Issue by jano42** [google/blockly#331]
I'm using Blockly to generate python code from a custom application.
I've set up the `Python.INDENT` to use `\t` instead of double spaces.

A blockly workspace which illustrate issue:
![image](https://cloud.githubusercontent.com/assets/3135683/14460572/84b78bc8-00be-11e6-94ff-c2fa33323288.png)

The generation with `\t` as `Python.INDENT`

````python
item = None

while True:
	if item == 5:
      pass
````

The `if` statement is prefixed with tab.
The `pass` is prefixed with double spaces.

After looking at the github code, I've seen that Python.PASS is hardcoded with double spaces.

https://github.com/google/blockly/blob/dfa9b44a7f5266421f3ad43f33c72e9769700fb6/generators/python.js#L85

The resulting code is **not python compatible.**
I've to manually change `pass` with `\t' to make it work

**Comment by NeilFraser** [comment]
Good catch.  Also, the predefined helper functions were all hardcoded to double spaces (which will work in Python (unlike the pass error) but leads to inconsistent code).

Fixed.  Thanks!
