### ISSUE TITLE
Rendering bug on upgrading to Blockly 3

### ISSUE THREAD

**Issue by mtravers** [google/blockly#3313]
I recently switched from Blockly 2 to 3.20191014.2 and in general it works great, the removal of the Closure dependency helps me a lot. But there is one weird rendering bug that has appeared – blocks that are the arguments of statement inputs are misaligned, leaving ugly whitespace that wasn՚t there before. An example: In Blockly 2, this renders properly:

![Screen Shot 2019-10-22 at 9 44 27 AM](https://user-images.githubusercontent.com/19027/67311545-a4f01980-f4b4-11e9-8931-4161e4cf7aed.png)

But in 3, gaps appear:

![Screen Shot 2019-10-22 at 9 43 27 AM](https://user-images.githubusercontent.com/19027/67311504-9275e000-f4b4-11e9-82ef-cd59b19ef053.png)

I thought this might be due to a CSS issue, but removing all my custom CSS didn't change the behavior. Nor did trying a different browser (same issue in both Firefox and Chrome). I'm kind of mystified.

(FYI: this is an application using Blockly as a query building tool for a graph database of biomedical research data. Also, it's using Clojurescript and React in combination with Blockly, which may be weird but it was working fine before).

**Comment by RoboErikG** [comment]
Ooph, that reproduces on the playground as well. Definitely a bug on our end. Depending on the fix we may consider cherry-picking this and releasing a new patch.

![image](https://user-images.githubusercontent.com/11066279/67312785-c4884180-f4b6-11e9-91d6-0bcc1f547ad7.png)

**Comment by samelhusseini** [comment]
Yeah the connection position of the value to statement block is wrong:
<img width="656" alt="Screen Shot 2019-10-22 at 10 54 35 AM" src="https://user-images.githubusercontent.com/16690124/67314935-6c533e80-f4ba-11e9-933c-4ea3d5200c42.png">

**Comment by mtravers** [comment]
Thanks for the quick fix! (Fixes the bug, not sure if I should close the issue myself).

**Comment by samelhusseini** [comment]
Thanks for filing @mtravers!
