### ISSUE TITLE
Shadow blocks in modern theme have highlights

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3319]
**Describe the bug**
When using the modern theme, shadow blocks still have a highlight dark path that is visible.

**To Reproduce**
1. Go to the playground
2. Change theme to modern
3. Pull out a block with a shadow

<img width="531" alt="Screen Shot 2019-10-23 at 7 46 20 AM" src="https://user-images.githubusercontent.com/23059043/67405175-3e790300-f569-11e9-8f4d-860d907d3800.png">

**Expected behavior**
<img width="498" alt="Screen Shot 2019-10-23 at 7 45 01 AM" src="https://user-images.githubusercontent.com/23059043/67405030-0bcf0a80-f569-11e9-87cc-a1c2e6180e21.png">

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by rachel-fenichel** [comment]
Fixed.
