### ISSUE TITLE
Npm run build does not recognize a new file

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3328]
- I made a new file (renderers/common/colourer.js) and put `goog.provide('Blockly.Colourer')` at the top.  
- In another rendering file I required `Blockly.Colourer`.
- I ran `npm run build`.
- I opened the playground.
- I got a standard console error for referencing a bad provide.
- I then ran `./build.py -core` and reloaded the playground.
- I was able to run my new code.

**Comment by samelhusseini** [comment]
This is because `build-uncompressed` isn't included in ``npm run build``. We should include it in that list. In the meantime, you can run ``gulp build-uncompressed``.

**Comment by samelhusseini** [comment]
Fixed.
