### ISSUE TITLE
Blockly.bindEvent_ is deprecated, remove it's use internally

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3332]
Filing this issue to track removing calls to Blockly.bindEvent_ internally as it is deprecated.
When removing these calls, we should also remove the ``@suppress {deprecated}`` annotations so the compiler doesn't skip those.

**Comment by BeksOmega** [comment]
I think there might be times when `bindEvent_` needs to be called. See [here ](https://github.com/google/blockly/blob/23a78c89e4c0f2801768b5c55c7f91ac261f4bc6/core/trashcan.js#L269)and [here](https://groups.google.com/forum/#!topic/blockly/QF4yB9Wx00s). But I'm not sure.

**Comment by NeilFraser** [comment]
FYI, it's called in 27 places in Blockly and 9 places by Blockly Games.  Last time I checked there were no alternatives to using it in some circumstances.  Not sure why it would be labeled as @deprecated.

**Comment by samelhusseini** [comment]
Yeah I agree with Neil, if we're using it and want to keep it around we shouldn't mark as deprecated.

**Comment by samelhusseini** [comment]
[This](https://github.com/google/blockly/pull/3333) PR is pretty much just ignoring the deprecated call, which is a round about way of saying we want to keep it "for now".

**Comment by rachel-fenichel** [comment]
We can remove the deprecation marker.  bindEventWithChecks just doesn't fully replace it.  However, uses of it in developer code may be a code smell.
