### ISSUE TITLE
Dropdown are acting weird with screen readers

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3340]
**Describe the bug**
When using a screen reader the and the arrow keys for fields hitting enter doesn't do anything, or will create a duplicate list.

**To Reproduce**

1. Turn on voiceover 
2. Use keyboard navigation to navigate to a field. 
3. Use the arrow keys to move around the field
4. try hitting enter

**Expected behavior**
Should select the item in the dropdown

**Screenshots**
<img width="164" alt="Screen Shot 2019-10-25 at 1 09 36 PM" src="https://user-images.githubusercontent.com/23059043/67601479-55feea00-f729-11e9-9748-3e0dff3f30e6.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by MNSDivya** [comment]
Seems working on ChromeOS, chrome browser. No duplicate list displayed.
https://screenshot.googleplex.com/zFRBVArP9Pu.png

@alschmiedt please confirm if this issue is on some other OS/browser to replicate

**Comment by alschmiedt** [comment]
Confirmed it is working. Thanks for checking!
