### ISSUE TITLE
Value input before/after dummy input row height inconsistencies

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3341]
Value input after dummy input.

Original rendering: 
<img width="180" alt="Screen Shot 2019-10-25 at 1 13 25 PM" src="https://user-images.githubusercontent.com/16690124/67602215-015c6e80-f72b-11e9-91e3-2f171a81451e.png">

Geras rendering:
<img width="148" alt="Screen Shot 2019-10-25 at 1 26 42 PM" src="https://user-images.githubusercontent.com/16690124/67602270-1f29d380-f72b-11e9-8b2b-679436a1aaec.png">

Value input before dummy input.

Original rendering:
<img width="162" alt="Screen Shot 2019-10-25 at 1 27 47 PM" src="https://user-images.githubusercontent.com/16690124/67602378-4aacbe00-f72b-11e9-85f5-8c0c235634ee.png">

Geras rendering:
<img width="151" alt="Screen Shot 2019-10-25 at 1 27 55 PM" src="https://user-images.githubusercontent.com/16690124/67602389-4ed8db80-f72b-11e9-8daf-cb214372b2c9.png">

**Comment by RoboErikG** [comment]
Somewhat related to #3330

**Comment by samelhusseini** [comment]
Fixed.
