### ISSUE TITLE
Click events fired for fields, clicking shadow blocks triggers event for parent

### ISSUE THREAD

**Issue by tmickel** [google/blockly#336]
1. When you click a field to focus it, a UI click event is triggered. Is this the intended behavior? If it is, can we add an additional flag to the event to indicate it was for a field focus?
2. Clicking in a shadow block, the ID for the block click appears to be the parent block's ID, not the shadow block ID. And, clicking a field that's contained in a shadow block also reports the ID of the parent block. Is this the intended behavior?

**Comment by NeilFraser** [comment]
> When you click a field to focus it, a UI click event is triggered. Is this the intended behavior?

Nope.  Fixed.

> Clicking in a shadow block, the ID for the block click appears to be the parent block's ID

This is harder.  Still working on it.

**Comment by NAllred91** [comment]
@NeilFraser  For #2, do you know of any work around to figure out that a shadow block was clicked?

**Comment by rachel-fenichel** [comment]
I was holding off on this due to a large change that was in progress, but I'll take a look now.  I think it'll be straightforward to fix.

**Comment by rachel-fenichel** [comment]
Fixed by #1089
