### ISSUE TITLE
Minimalist renderer doesn't account for input alignment

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3361]
**Describe the bug**

The minimalist renderer doesn't account for any of its inputs alignment properties.

**To Reproduce**

Open the playground, switch to test blocks, switch to the minimalist renderer.
Open the Align category. Notice how none of the inputs are aligned properly.

**Expected behavior**

Unclear, but it seems the base renderer should at least take into account the input's alignment properties.

**Screenshots**
![Screen Shot 2019-10-29 at 9 47 32 AM](https://user-images.githubusercontent.com/16690124/67789555-68329e00-fa31-11e9-8715-e4a94f3e2a4b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by rachel-fenichel** [comment]
Good call.  Align is fundamental enough that it should be in the base renderer.

**Comment by samelhusseini** [comment]
Fixed.
