### ISSUE TITLE
Statement input rendering: bar below input got longer

### ISSUE THREAD

**Issue by seldomU** [google/blockly#3367]
Blocks with statement inputs are rendered differently with the new renderer.
The horizontal bar below the statement input has the same width as the bar above it. The old renderer made the bar as short as possible. This is especially noticable in the for-loop block.

I tested with Q3 patch 3.

![statementInputBar](https://user-images.githubusercontent.com/10736677/67852143-2cb8d200-fb0c-11e9-94ea-2464847b2e00.png)

**Comment by seldomU** [comment]
I'd argue for putting it back in. The bar blocks screen space and stands out visually. See the screenshots comparison of the code that made me realize the change.

![longBar](https://user-images.githubusercontent.com/10736677/67958930-420b2a80-fbf8-11e9-8383-f5cc68a80c76.png)
![shortBar](https://user-images.githubusercontent.com/10736677/67958931-42a3c100-fbf8-11e9-9ba0-d00dbe40b98a.png)

**Comment by samelhusseini** [comment]
Fixed.
