### ISSUE TITLE
Compute canvas is affecting page layout

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3368]
**Describe the bug**

The text compute canvas is affecting the layout of pages.

**To Reproduce**

This is very clear to see on my personal playground (I have a personal one cuz I have a small screen, and the playground doesn't work well with that)
![ComputeCanvasPersonal](https://user-images.githubusercontent.com/25440652/67866492-43e4c900-fae6-11e9-8eeb-109120acc323.png)

But you can also see it on the playground:
1. Search for "blocklyComputeCanvas" in the elements console tab.
2. Observe how it is affecting the layout:
![ComputeCanvasPlayground](https://user-images.githubusercontent.com/25440652/67866647-83131a00-fae6-11e9-973c-5254f539b5b2.png)

**Expected behavior**

The compute canvas should not affect the page layout

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 77

**Additional context**

I'll be happy to provide CSS and HTML if needed.

**Comment by samelhusseini** [comment]
Fixed.
