### ISSUE TITLE
No events on blocks in the flyout

### ISSUE THREAD

**Issue by tmickel** [google/blockly#337]
- No click events are generated for clicking blocks in fixed flyouts.
- When editing fields on flyout blocks or their values, no events are generated.

Do these flyout blocks have fixed IDs? If so, that's great. If not, once click events are implemented, how can we tell what kind of block is being clicked?

Thanks!

@thisandagain @NeilFraser

**Comment by NeilFraser** [comment]
> No click events are generated for clicking blocks in fixed flyouts.

Fixed.

> When editing fields on flyout blocks or their values, no events are generated.

Works for me.  Are you remembering to listen to the events on the flyout's workspace?  This is different form the main workspace.

> Do these flyout blocks have fixed IDs?

Yes.  Blocks in fixed flyouts have fixed IDs.  Disappearing flyouts change their IDs, but the blocks still exist after the flyout closes (they are eventually deleted when the flyout is reopened).

**Comment by tmickel** [comment]
Oh yes, thank you again!
