### ISSUE TITLE
Bad colour in deuteranopia theme

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3372]
https://github.com/google/blockly/blob/develop/core/theme/deuteranopia.js#L37

  "colour_blocks": {
    "colourPrimary": "#f2a72c",
    **"colourSecondary": "#f1c17",**
    "colourTertiary": "#da921c"
  },

New style code is validating styles and found this error.  I'm making it `#f1c170` so that the playground doesn't have an error, but @alschmiedt to get the colour right.

**Comment by alschmiedt** [comment]
Fixed.
