### ISSUE TITLE
Dynamic toolbox category from list of block names

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3376]
Instead of providing block XML, the developer should be able to provide a list of block names as strings and have the category populate based on that.

Note that this means no shadow blocks.

**Comment by alschmiedt** [comment]
This is more or less completed with the upcoming tooblox rewrite. The user can provide a list of block names in the following format: 
```
[
  {
    'kind': 'block',
    'type': '<block_type>'
  }
]
```
