### ISSUE TITLE
Set default gap between blocks in a category

### ISSUE THREAD

**Issue by Smittyvb** [google/blockly#3396]
**Is your feature request related to a problem? Please describe.**
I want to change the pixel gap between all the blocks in a category in my toolbox. While I *could* add a
```xml
<sep gap="XX"></sep>
```
between all of the blocks, or write a script to add them automatically, I want to be able to do it easily from within the toolbox code.

**Describe the solution you'd like**
```xml
<category id="catMath" name="Math" gap="10">
  [...]
</category>
```

**Describe alternatives you've considered**
- perhaps this could be stored in a theme?

**Comment by maribethb** [comment]
If you want to change the default gap, you can subclass the Flyout and set the value of `GAP_X` or `GAP_Y` for horizontal or vertical flyouts respectively.

Since there is already a way to do this I'm going to close this bug as working as intended.

**Comment by vkoshcheev** [comment]
As far as I can tell this is not (no longer?) possible, or example is needed.

**Comment by maribethb** [comment]
The workaround mentioned above is still possible, you can subclass and [register](https://developers.google.com/blockly/guides/configure/web/customization) a custom flyout and override the [GAP_Y property](https://github.com/RaspberryPiFoundation/blockly/blob/91ef951e92576a090aea7c675bafd37a93ac369a/core/flyout_base.ts#L173)

If you need additional help please post on the [forum](https://groups.google.com/g/blockly?pli=1), as we monitor that for questions but comments on closed bugs may or may not be seen by the right person. Thanks!
