### ISSUE TITLE
All stock blocks in Blockly Games now black.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#3397]
<img width="251" alt="Screen Shot 2019-11-04 at 19 02 53" src="https://user-images.githubusercontent.com/250480/68175370-e0b7c400-ff35-11e9-9d1c-c7fa5211dd4e.png">

All blocks defined by Blockly are now black in Blockly Games.  Both in compiled mode and uncompiled mode.  There are no errors in the console.  The relevant includes are:
```
goog.require('Blockly');
goog.require('Blockly.Constants.Logic');
goog.require('Blockly.geras.Renderer');
```
These includes appear to be consistent with those in https://github.com/google/blockly/blob/master/tests/compile/main.js yet I can't recreate this behaviour in Blockly develop's demos or tests.  It is a new behaviour since Blockly Games renders properly on Blockly master.

I'm rather puzzled since there's doesn't seem to be any code on Blockly Games' side to break.  All we do is `require` the block category and then use it in XML.  I thought we were done with this sort of breaking changes.

**Comment by samelhusseini** [comment]
Intriguing. Let me take a look.

**Comment by NeilFraser** [comment]
Yes, both Monica and I can see this when pulling from develop.  Master is fine.

**Comment by NeilFraser** [comment]
And we are black again.  This time only in compressed mode.  Blockly games synced to Blockly develop is broken, master is fine.
![puzzle](https://user-images.githubusercontent.com/250480/71326716-e18bc180-24b3-11ea-99da-b52f33f4b261.png)

**Comment by BeksOmega** [comment]
I believe this is because the Theme constructor's signature changed again. The [new constructor](https://github.com/google/blockly/blob/54cb686dcdca1ecfe66358706fb2cb73f7037fb1/core/theme.js#L41) also takes in a name parameter as well as the old things.

I [tagged this for docs updates](https://github.com/google/blockly/pull/3413#issuecomment-552646883). And it got added to issue #3138 .

I hope that fixes it for you! It's just an instinct though.

**Comment by rachel-fenichel** [comment]
The fact that this keeps happening means we need to add a test for it, for both compressed and uncompressed.

**Comment by samelhusseini** [comment]
Fixed.

**Comment by alschmiedt** [comment]
Added #3585 to track creating an automated test for this issue.
