### ISSUE TITLE
shift-clicking a block creates some kind of selection marker

### ISSUE THREAD

**Issue by seldomU** [google/blockly#3411]
Clicking a block on the workspace while holding shift creates a new kind of selection marker around the block. The marker only disappears when another block is selected in the same way. It doesn't seem to serve any purpose at the moment. It also doesn't surround the block completely, nor adjust to the block's shape changes. 

Maybe this made it into master by accident?

**Comment by alschmiedt** [comment]
Hello! 
I think you have stumbled upon keyboard navigation. If you use the wasd keys you can move the cursor around. We are still working out how keyboard navigation and the mouse should interact. I think this is more of a feature request that the user shouldn't be able to enter accessibility mode by accident.

**Comment by alschmiedt** [comment]
Closing this issue and opening a feature request #3412.
