### ISSUE TITLE
Decide what to do about output shape on the block

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3414]
Zelos blocks sometimes set the output shape in JS (by calling block.setOutputShape). We should decide what to do about those blocks that want to specify the output shape explicitly and not use the ``shapeFor`` method to dynamically decide what shape to use.

**Comment by rachel-fenichel** [comment]
The task here is to add `setOutputShape` as a function on a block

**Comment by samelhusseini** [comment]
Fixed.
