### ISSUE TITLE
the issue about local_build.sh

### ISSUE THREAD

**Issue by PotStudio** [google/blockly#3422]
I'm try to use "local_build.sh" that in "blockly/local_build" to compress my js files,  but have some error such as ` Required namespace "Blockly.***" never defined`，
and I check the file 'local_build.sh', there just have two goog.provide:
`goog.provide('Blockly');
goog.provide('Blockly.Blocks');`
but compress need other dependences, so , I check 'build.py' , there have this:
`echo -e "'use strict';\ngoog.provide('Blockly');
goog.provide('Blockly.Blocks');
goog.provide('Blockly.Comment');
goog.provide('Blockly.FieldCheckbox');
goog.provide('Blockly.FieldColour');
goog.provide('Blockly.FieldDropdown');
goog.provide('Blockly.FieldImage');
goog.provide('Blockly.FieldLabel');
goog.provide('Blockly.FieldMultilineInput');
goog.provide('Blockly.FieldNumber');
goog.provide('Blockly.FieldTextInput');
goog.provide('Blockly.FieldVariable');
goog.provide('Blockly.Mutator');
goog.provide('Blockly.Warning');" > temp.js`
so i copied it into local_build and  then it works.
I wonder if "local_build.sh" is missing these contents or my method is wrong?

**Comment by moniika** [comment]
Yes, that looks like an issue on our side, thanks for pointing this out. The fix you have there is the right workaround for the time being.

**Comment by PotStudio** [comment]
> Yes, that looks like an issue on our side, thanks for pointing this out. The fix you have there is the right workaround for the time being.

ok,thanks

**Comment by rachel-fenichel** [comment]
We've been moving to a gulp-based build system, which supports local building.  We'll likely remove local_build.sh in this coming release.

To build with gulp:
```
npm install blockly
npm run build
```

This still uses the closure compiler.

**Comment by samelhusseini** [comment]
@PotStudio just checking in to see if the npm local build works for you? I'll keep this issue open to track removing the local_build.sh script.
