### ISSUE TITLE
Novice question: how do you pass requirejs-based modules the results of running user-generated code (eval() of runJS)

### ISSUE THREAD

**Issue by liudxhit** [google/blockly#3449]
CommonJS style (define-module.exports) module to receive blockly run results in real time data?
In other words, how can blockly be rewritten as a module that can be loaded by the requireJS module loader?How?
Eagerly looking forward to your reply, please give advice.

**Comment by RoboErikG** [comment]
Hi @liudxhit 

In general, please ask questions on [the forum](https://groups.google.com/forum/#!forum/blockly) instead of our issue tracker. I don't think anyone on the team has dug that much into the full CommonJS stack with Blockly, but maybe another developer on the forum has.
