### ISSUE TITLE
Scrollen in Blockly

### ISSUE THREAD

**Issue by ltsalvatore** [google/blockly#3451]
Hallo zusammen,

eigentlich sind dies mehr Anregungen für ein nächstes update statt issues.
und nach dem ich mittlerweile schon fast 2 jahre mit Javascript Script Engine (hauptsächlich blockly) in iobroker arbeite und sich in der hinsicht leider nichts getan hat, muss ich es doch mal anregen, denn ich finde das wäre eine große bereicherung und viele user wären sehr dankbar dafür.

und zwar...

scrollen = wieso ist es nicht möglich in dem scriptfenster (Blockly) mit dem mausrad zu scrollen, anstatt dabei die linke maustaste gedrückt halten und ziehen zu müssen?
bei sehr langen schripten wäre es mit dem mausrad um einiges einfacher

**Comment by BeksOmega** [comment]
I actually added scrolling with the mouse wheel! [Documentation link.](https://developers.google.com/blockly/guides/configure/web/move) Just make sure you set scrollbars and wheel to true in the move struct. If wheel is also enabled for zooming, the control button plus mouse wheel will zoom.
