### ISSUE TITLE
The xml tag id auto generate should be from a-z 0-9

### ISSUE THREAD

**Issue by dieudv** [google/blockly#3453]
Currently the ids of the automatically generated xml tags include special characters.
Ex: 
```
<block type="math_number" id="vo^CA;-e!Wm%`$D{*(H{"> 
```
Characters such as ``` are also inserted, causing some formatting errors.
So I think it should be limited to a-z characters 0-9.

**Comment by NeilFraser** [comment]
From:
https://github.com/google/blockly/blob/master/core/utils.js#L423

> Legal characters for the unique ID.  Should be all on a US keyboard.
> No characters that conflict with XML or JSON.  Requests to remove additional
> 'problematic' characters from this soup will be denied.  That's your failure
> to properly escape in your own environment.  Issues #251, #625, #682, #1304.
