### ISSUE TITLE
unable to run blockly using npm run test, it keeps giving me this error

### ISSUE THREAD

**Issue by HiskDeathnote** [google/blockly#3457]
![image](https://user-images.githubusercontent.com/18376750/69202839-1b506c00-0b86-11ea-9e70-f7ae08583d88.png)

**Comment by samelhusseini** [comment]
Could you provide more details of your environment. 
- What version of node and npm are you running?
- What OS?

**Comment by HiskDeathnote** [comment]
NPM 6.12.0, Node 12.13.0 and Windows 10.

**Comment by samelhusseini** [comment]
Are you able to confirm that this problem repro's if you remove your ``node_modules`` directory and redo ``npm install``. 
It looks to be a problem with concurrently on your machine, and I can't find any known issues around that online.
