### ISSUE TITLE
Hide toolbox category

### ISSUE THREAD

**Issue by EvilPeanut** [google/blockly#347]
Is there a way to hide a toolbox category?

**Comment by NeilFraser** [comment]
You can use workspace.updateToolbox(newTree); to change the toolbox to not have the offending category:
 https://developers.google.com/blockly/installation/toolbox#changing_the_toolbox

Or you could use CSS to hide a category:
document.getElementById(':1').style.display = 'none'
and show it again:
document.getElementById(':1').style.display = ''

**Comment by terrencestark** [comment]
Hi, how could I know the id that Blockly auto generates for the element?
like ":1" or "blockly:1"

**Comment by alschmiedt** [comment]
Hello!
It goes in the order that you define in your toolbox xml.
In the future if you could ask questions on our [forum](https://groups.google.com/g/blockly) that would be great. We try to watch our forum and also it gives you the chance to get answers from others who might be able to help out.
