### ISSUE TITLE
Dropdown arrow not coloured properly 

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3472]
**Describe the bug**
When opening the toolbox all dropdown arrows are black. 

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="164" alt="Screen Shot 2019-11-25 at 8 47 18 AM" src="https://user-images.githubusercontent.com/23059043/69560188-36452680-0f60-11ea-9a10-db2ccef95a8a.png">

**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**
It seemed to fix it when I added a call to applyColour in field dropdown initView. However, not sure if this is the fix we want.

**Comment by samelhusseini** [comment]
Can't repro. Is this on develop?

**Comment by samelhusseini** [comment]
Fixed by https://github.com/google/blockly/pull/3465
