### ISSUE TITLE
Colour field not updated properly

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3473]
**Describe the bug**
<img width="225" alt="Screen Shot 2019-11-25 at 8 54 28 AM" src="https://user-images.githubusercontent.com/23059043/69560854-427db380-0f61-11ea-8cfe-49c28b9c9034.png">

Colour field is not getting updated properly. 

**To Reproduce**
Go to develop. 
Open the colour category in the toolbox

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

Replace with error stack trace.

**Additional context**
I think this is the same problem as #3472

**Comment by samelhusseini** [comment]
How do you repro?

**Comment by alschmiedt** [comment]
I just opened the colour toolbox on develop

**Comment by samelhusseini** [comment]
Fixed by https://github.com/google/blockly/pull/3465
