### ISSUE TITLE
Block width incorrect for nested blocks

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3481]
**Describe the bug**
In zelos renderer when a block is nested it messes with the width of the block.

**To Reproduce**
1. Switch to the zelos renderer
2. Nest a block
3. In debug rectangles click blockBounds and connectedBlockBounds

**Expected behavior**
1. Should be the width of the block.

**Screenshots**
<img width="272" alt="Screen Shot 2019-12-03 at 10 31 11 AM" src="https://user-images.githubusercontent.com/23059043/70078746-1cd35880-15b8-11ea-803e-854178fa3929.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by samelhusseini** [comment]
Zelos only.

**Comment by samelhusseini** [comment]
Fixed.
