### ISSUE TITLE
[zelos rendering] vertical tight nesting

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3495]
**Is your feature request related to a problem? Please describe.**

Similar to how we cut back the implicit padding added by the left and right connection shapes, we need to do the same with the padding added by the top / bottom row in some situations:

![Screen Shot 2019-12-06 at 4 48 28 PM](https://user-images.githubusercontent.com/16690124/70365819-41ddfa80-1848-11ea-9f10-fdf96b8ee070.png)

**Describe the solution you'd like**

Use negative spacing on the first and last row spacer.

**Comment by samelhusseini** [comment]
Done.

**Comment by laurensvalk** [comment]
I realize this is an older issue, but I'm really curious about the design reason behind this fix.

Until I found this thread, I somehow assumed this was a glitch/bug. It seemed surprising that the block would get vertically smaller when inserting a block, with the whole stack resizing as a result.

Maybe this is less noticeable in Blockly apps that don't use many shadow inputs?

https://github.com/google/blockly/assets/12326241/d9e5a84a-2a3f-435b-8294-130d465e3a14

Video can be reproduced on the advanced playground with Zelos renderer and theme.
