### ISSUE TITLE
Allow non-visible grids

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#3503]
**Is your feature request related to a problem? Please describe.**

Per https://groups.google.com/forum/#!topic/blockly/Av4i5QHdNdE the grid can have its color and length modified, but it can't be non-visible while using a snap.

**Describe the solution you'd like**

Add a property to the grid parameters to allow it to be non-visible even while using the snap.

**Describe alternatives you've considered**

The current workaround is to set the color to be the same as the background.

**Additional context**

**Comment by mattbishop** [comment]
This is a purely-aesthetic request, but I think it looks really nice to not see the grid, but experience the clean alignment snap provides.

**Comment by mattbishop** [comment]
One simplistic idea would be to accept `length: 0` as a grid value and that would cause the grid to not render. In fact that is what I tried first.

**Comment by NeilFraser** [comment]
The grid is specifically designed to handle `length: 0` and not draw anything.  However, changes in the options parser made specifying `0` impossible:

https://github.com/google/blockly/blob/develop/core/options.js#L273

I'll prepare a PR...

**Comment by samelhusseini** [comment]
Fixed.
