### ISSUE TITLE
Remove initSvg and render from after mutator compose

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3511]
**Describe the problem**

Calling initSvg or render after calling a block's compose method should not be necessary.

This is because anything you do inside of a compose method (add a field, remove a warning, etc) should itself force a rerender of the block.

So the fact that initSvg and render /are/ currently called after compose means they could be hiding bugs.

**Why removing them won't break things**

I looked into all of the elements you could append to a block while mutating, and all of them correctly initialize themselves and rerender the block (excepting mutators).

* Comment ([creation](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/block_svg.js#L1156), [initSvg](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/comment.js#L64), [render](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/block_svg.js#L1164)).
* Warning ([creation](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/block_svg.js#L1227), [initSvg](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/warning.js#L42), [render](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/block_svg.js#L1247)).
* Mutator ([creation](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/block_svg.js#L1257), [initSvg](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/block_svg.js#L1264), no render :/)
* Field ([creation](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/input.js#L101), [initSvg](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/input.js#L117), [render](https://github.com/google/blockly/blob/ba6dfd812552e0823ed75f3dc5133a267cc6fbc9/core/input.js#L134)) 

There is a separate bug filed to fix mutators #3510.

This means that the current calls to initSvg and render, are really just duplicates.

**Additional context**

Info in this post was originally outlined in [this comment](https://github.com/google/blockly/pull/3468#issuecomment-562292414).

To fix this you would simply need to remove the two calls in the [workspaceChanged_](https://github.com/google/blockly/blob/77951c585e9253bded2dabbc0321bfaec8ae7b5e/core/mutator.js#L350) function, and probably add some tests to make sure render is getting called properly.

But before anyone takes this, you should get approval from one of the official Blockly teammembers, because they may want to investigate.

**Comment by RoboErikG** [comment]
@rachel-fenichel to comment.

**Comment by rachel-fenichel** [comment]
Looks right.  Thanks for all the links.

**Comment by maribethb** [comment]
Approved for this work to be done. We need tests for this before merging the fix though. The tests can spy on the render method and make sure it's called.
