### ISSUE TITLE
Blocks can scroll into flyout

### ISSUE THREAD

**Issue by drigz** [google/blockly#352]
If you use a fixed flyout (for example, by deleting all lines containing "category" from tests/playground.html) the workspace extends under the flyout, and blocks can be scrolled over the flyout:

![blockly block in flyout](https://cloud.githubusercontent.com/assets/632207/14880134/9cc09e78-0d2d-11e6-9dbc-fed716523e72.png)

I've tried to fix this my adjusting getMainWorkspaceMetrics to define the workspace view starting from the edge of the flyout, in the same way that the workspace view doesn't include the toolbox currently.

This creates (at least) one bug when you create the first block:
1. The user grabs a block from the flyout.
2. placeNewBlock_ creates and positions the new block.
3. Positioning the new block changes the workspace metrics (contentLeft etc).
4. Blockly.svgResize updates the scrollbars, which rescroll so that the block is in the view (ie not over the flyout).
5. The block is no longer under the cursor.

~~This isn't present in the downstream project...~~ _Not true_

Do you think this bug is worth fixing in Blockly, and if so, is this the right way? Can you think of a way around the positioning issue (other than merging in the downstream patch for a separate layer for dragged blocks)?

**Comment by picklesrus** [comment]
Fixed in develop by #771
