### ISSUE TITLE
method updateToolbox keep the category state

### ISSUE THREAD

**Issue by candy4290** [google/blockly#3520]
**Is your feature request related to a problem? Please describe.**

when i use updateToolbox, category's state will be reset; for example, i open some category and i call the updateToolbox method, category will be closed.
**Describe the solution you'd like**

i want when i call updateToolbox, the category will keep previous state.
**Describe alternatives you've considered**

**Additional context**

**Comment by rachel-fenichel** [comment]
Does `toolbox.refreshSelection()` solve your problem?

**Comment by candy4290** [comment]
no, i want to insert or delete an item, and i want to keep the category status,
for example
![image](https://user-images.githubusercontent.com/19907991/71138870-bd2bad00-2247-11ea-8e0c-3af20885b737.png)
when i am searching, the 'serarch result' appear, when i clear search input, the 'search result' disappear.

**Comment by candy4290** [comment]
Thanks for you replay. I have an idea,may be i can have 'search result' at the beginning and just control the style 'display'. I'll have a try. 
But i think method updateToolbox should keep previous state.

**Comment by candy4290** [comment]
I have solved my question, use an idea like up and use refreshSelection; Thanks again!
