### ISSUE TITLE
fromXml method will result in showing flyout,even an empty flyout

### ISSUE THREAD

**Issue by candy4290** [google/blockly#3523]
when i select an item of category, and this item does not have any responding flyout content,so the flyout is not appeared; But when i call method fromXml, an empty flyout appears. Like this:
![image](https://user-images.githubusercontent.com/19907991/71153935-59b87400-2275-11ea-8641-a0cbe3f559d8.png)
![image](https://user-images.githubusercontent.com/19907991/71153976-718ff800-2275-11ea-8ac7-e1161b1a266f.png)

**Comment by candy4290** [comment]
I find that method Flyout.show will be called after fromXml.

**Comment by UCYT5040** [comment]
Which `fromXml` function is being used here? The only `fromXml` function I could find is [`FieldVariable.fromXml(fieldElement)`](https://developers.google.com/blockly/reference/js/blockly.fieldvariable_class.fromxml_1_method) which isn't really related to the toolbox at all.

I think this may have been fixed already, or at least the method in question deprecated.

**Comment by BeksOmega** [comment]
Thanks for looking into this @UCYT5040 =) I think you're right and this can be closed.
