### ISSUE TITLE
Can we release an official React-blockly package?

### ISSUE THREAD

**Issue by hsluoyz** [google/blockly#3524]
React owns a lot of popularity in JS world. But it's hard to use Blockly in React. I found some 3rd-party homemade packages:

https://github.com/nbudin/react-blockly
https://github.com/patientslikeme/react-blockly-component
https://github.com/xvicmanx/react-blockly-drawer

But their code quality and usability are really far under the expectation. This may become the real "blocks" for React users to use blockly.

Therefore, can you please consider about releasing an official, high-quality React blockly package on both GitHub and npmjs? Thanks.

**Comment by rachel-fenichel** [comment]
Nat Budin (and friends) rewrote `react-blockly` to get it up to date with mainline Blockly and have it be a relatively thin wrapper around Blockly. Recent core rewrites also made Blockly behave well in React now.

As such, we [officially recommend](https://groups.google.com/g/blockly-announce/c/vQ-MZ2BZyvw/m/0VMV1cjjBAAJ) that developers use [react-blockly](https://github.com/nbudin/react-blockly).
