### ISSUE TITLE
Custom field, the width of parent element is not enough, overflow, how to solve it?

### ISSUE THREAD

**Issue by senbochen** [google/blockly#3528]
![image](https://user-images.githubusercontent.com/45449695/71649539-b4100500-2d4a-11ea-91fd-1c42b1868db2.png)

**Comment by senbochen** [comment]
![image](https://user-images.githubusercontent.com/45449695/71660394-decb7f00-2d85-11ea-90fe-bd822db582a2.png)

**Comment by samelhusseini** [comment]
Dupe of https://github.com/google/blockly/issues/3529
