### ISSUE TITLE
The width of the parent element is not enough, my light belt overflows

### ISSUE THREAD

**Issue by senbochen** [google/blockly#3529]
![image](https://user-images.githubusercontent.com/45449695/71649936-b031b200-2d4d-11ea-8a2f-5e67d8904367.png)

**Comment by senbochen** [comment]
![image](https://user-images.githubusercontent.com/45449695/71660335-ad52b380-2d85-11ea-81e1-564dc5473038.png)

**Comment by samelhusseini** [comment]
This looks like scratch-blocks. You might have better luck asking your question over at https://github.com/llk/scratch-blocks.

In general, the field's width is determined by the value set in this.size_.width.
