### ISSUE TITLE
Shadow block no more unshadow

### ISSUE THREAD

**Issue by jano42** [google/blockly#353]
I've tested the last version (my previous test were made at the start of the year) and it appears that shadow blocks don't "unshadow" when I change its value. 

This was working in my previous tests, and I found it awesome !
Is this a bug ?
Can it be configured from any parameter ?

![shadow](https://cloud.githubusercontent.com/assets/3135683/14883343/1568e3ac-0d3e-11e6-9c5a-73f2f4bb0c2e.gif)

**Comment by carlosperate** [comment]
Feature has been removed: https://github.com/google/blockly/issues/311
And there is currently an open PR to add it as an optional behaviour: https://github.com/google/blockly/pull/319
