### ISSUE TITLE
Changing Style/Colour of Inherited disabled block has unexpected behaviour

### ISSUE THREAD

**Issue by radovan76** [google/blockly#3530]
When you change style or colour of block which is child of disabled block (getInheritedDisabled() of child block is true), colour of block is changed wrongly.

### Steps to reproduce the behavior:

1. Create top block
2. Create child block
3. Disable top block (child block will be  disabled because childBlock.getInheritedDisabled()==true)
4. Change style of child block
5. Child block looks like shadow block

### Expected behavior:

5. Child block still looks like disabled block

### Additional context:
**Change code in block_svg.js:**
```
Blockly.BlockSvg.prototype.updateColour = function() {
  if (!this.isEnabled()) {
    // Disabled blocks don't have colour.
    return;
  } 
```
to:
```
Blockly.BlockSvg.prototype.updateColour = function() {
  if (!this.isEnabled() || this.getInheritedDisabled()) {
    // Disabled blocks don't have colour.
    return;
  }
 ```

**Comment by alschmiedt** [comment]
This should be fixed in develop by this line of [code](https://github.com/google/blockly/blob/develop/core/renderers/common/path_object.js#L152).
