### ISSUE TITLE
When block has mutation, initModel is called before fromXml

### ISSUE THREAD

**Issue by radovan76** [google/blockly#3542]
**Description**
When block has mutation, initModel is called before fromXml. If block contains field_variable, default variable is created before initialization from XML and stays in variableMap after fromXml.

**To Reproduce**
1. try this simple HTML:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <script src="https://blockly-demo.appspot.com/static/blockly_compressed.js"></script>
  <script src=".https://blockly-demo.appspot.com/static/blocks_compressed.js"></script>
  <script src="https://blockly-demo.appspot.com/static/msg/js/en.js"></script>
</head>
<body>
  <button onclick="logit()">log variables</button>
  <div id="blocklyDiv" style="height: 480px; width: 600px;"></div>
  <xml xmlns="https://developers.google.com/blockly/xml" id="toolbox" style="display: none">
    <block type="var"><mutation/></block>
  </xml>
<script>
var logit=function(){console.log(workspace.getAllVariables())}
Blockly.Blocks.var = {
  init: function () {
    this.jsonInit({
      message0: "variable %1",
        args0: [{
          type: "field_variable",
          name: "VAR",
      }],
    });
  },
  mutationToDom: function () {
    var m= Blockly.utils.xml.createElement('mutation');
    m.setAttribute('any', 'any');
    return m
  },
  domToMutation: function (xmlElement) {return;},
};
var workspace = Blockly.inject('blocklyDiv',{media: 'https://blockly-demo.appspot.com/static/media/',toolbox: document.getElementById('toolbox')});
</script>
</body>
</html>
```
2. Move almost two blocks from toolbox to workspace
3. click on button
4. see console (you will see equal number of variables as number of blocks, but every block show same variable)

**Expected behavior**
4. see only one (used) variable

**Comment by samelhusseini** [comment]
Unsure if https://github.com/google/blockly/pull/3527 has masked the issue here, but on the latest Blockly (3.20200123.0). Could you try it out and let me know if it conflicts with your desired behaviour here?

**Comment by moniika** [comment]
(issue observed on master and develop)
In `domToBlockHeadless`, when a block has a mutation, then `initSvg` (and `init` for the variable field) is triggered before `domToField_` (and `fromXml` for that field). That seems to be where these extra variable models are created.
