### ISSUE TITLE
Investigate how fields cache options

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3553]
**Describe the bug**
When a dropdown field list refreshes the selected item does not match the real selection. 
This occurs when an item in the list is renamed and causes a resort of the options list.
Bug was introduced in #3036. 

**To Reproduce**
1. Navigate to test blocks
2. Choose Dynamic dropdown 
3. Add 'aa', 'bb', 'cc' as options
4. Choose 'cc'
5. In the console rename 'cc' to be 'ab'
6. Observe 
<img width="206" alt="Screen Shot 2020-01-06 at 4 13 00 PM" src="https://user-images.githubusercontent.com/23059043/71858351-b7372800-309f-11ea-83cd-23c318631959.png">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**
The forum post found [here](https://groups.google.com/forum/#!topic/blockly/h34eayeVOzM) describes the issue further.

**Comment by samelhusseini** [comment]
Fixed.
