### ISSUE TITLE
chore(tools): add release-drafter.yml inside .github

### ISSUE THREAD

**Issue by snitin315** [google/blockly#3555]
**Actual Behaviour**
Currently we don't have the `release-drafter.yml` file which is very useful to keep track of a project. As pull requests are merged, a draft release is kept up-to-date listing the changes, ready to publish when you’re ready.
Right Configuration can  categorises the changes into headings, and automatically suggests the next version number as well.

for more info visit [here](https://github.com/release-drafter/release-drafter)

**Additional Context**
**I Would like to work on the issue**

**Comment by moniika** [comment]
Thanks for pointing out this tool. It seems like it could potentially be very useful for compiling release notes. We'll need to discuss more with the team internally on enabling this GitHub app and integrating it into our existing release process.
We may also need to further discuss our existing labels so they can be effectively used by this tool.
