### ISSUE TITLE
Lua codegen of lists_getIndex block has problems with list literals

### ISSUE THREAD

**Issue by seldomU** [google/blockly#3566]
When a _lists_getIndex_ block has a list input that is not a variable, but a literal like _lists_create_with_, the generated Lua code looks like ```{'foo', 'bar'}[1]```. That's not valid Lua according to the interpreter I'm working with and two other online interpreters I tested (repl.it and tutorialspoint). Wrapping the literal in parentheses makes the interpreters happy: ```({'foo', 'bar'})[1]```.

Maybe _lists_create_with_ should always wrap the list literal in parens or _lists_getIndex_ should have different operator precedent rules?

![lua_list_example](https://user-images.githubusercontent.com/10736677/71988051-81c14480-322f-11ea-9b74-45650a692247.png)

**Comment by moniika** [comment]
Thanks for filing a bug. This also means our generator tests aren't catching this case.

**Comment by BeksOmega** [comment]
Don't know if this is related: https://github.com/google/blockly/issues/1201

**Comment by moniika** [comment]
> Don't know if this is related: #1201

Similar in that its also a syntax error in generation, but this issue is much smaller and seems like it'd be an easier fix. (Also our tests don't catch it :O, but to be fair its not a use case we expect where someone creates a list in the arguments of get index).
