### ISSUE TITLE
Dropdown option is immediately selected due to order of processing touch events

### ISSUE THREAD

**Issue by Adam13531** [google/blockly#3567]
**Describe the bug**

This bug seems to be a resurfacing of #1804; on mobile, when a dropdown would appear directly over where the user tapped to spawn the dropdown, a selection will be made immediately.

**To Reproduce**

(note: I did the following steps using [this official sample](https://blockly-demo.appspot.com/static/demos/code/index.html), although I have a local repro too that I can provide if that's insufficient)

1. Do all of this either from a real mobile device or from Chrome's device emulation (DevTools → Toggle device toolbar)
1. Create 12 variables with any names (just so that they'll populate the dropdown menu)
1. Add a "set variable to" block to the canvas
1. Try opening the dropdown for that block

At this point, the dropdown will open and immediately choose the value underneath your finger/mouse.

**Expected behavior**

The dropdown stays open so that you can choose an option.

**Screenshots**

I have a video of myself reproing this: https://clips.twitch.tv/CheerfulCleverKleeOSfrog

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 79.0.3945.88

**Smartphone (please complete the following information):**
 - Device: Google Pixel XL
 - OS: Android 10
 - Browser: Chrome
 - Version: 79.0.3945.93

**Additional context**

We investigated, and the problem is that the dropdown menu is already drawn by the time the event is handled. We wrote a hack to work around this behavior by modifying Blockly directly to stop propagating the event:
```diff
--- a/core/components/menu/menuitem.js
+++ b/core/components/menu/menuitem.js
@@ -258,6 +258,29 @@ Blockly.MenuItem.prototype.setEnabled = function(enabled) {
  * @package
  */
 Blockly.MenuItem.prototype.handleClick = function(_e) {
+  var target = _e.currentTarget;
+  var parentMenu = this.getParent();
+
+  if (target &&
+    target.classList.contains("focused") &&
+    this.isEnabled() &&
+    parentMenu.getHighlighted() === null) {
+    return;
+  }
+
   if (this.isEnabled()) {
     this.setHighlighted(true);
     this.performActionInternal();
```

**Comment by samelhusseini** [comment]
Fixed.
