### ISSUE TITLE
Textarea of comment missing scrollbars

### ISSUE THREAD

**Issue by moniika** [google/blockly#3596]
**Describe the bug**

Comments are missing scrollbars

**To Reproduce**

1. Create a comment on a block that results in needing to scolls
2. Observe no scrollbars

**Expected behavior**

Expected comments to have scrollbars

**Screenshots**
![image](https://user-images.githubusercontent.com/6621618/72393601-2dfba300-36e8-11ea-8892-1107045545c4.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Additional context**

Issue originally brought up in #39

**Comment by psyduck1203** [comment]
hey can i work on this issue ?

**Comment by rachel-fenichel** [comment]
Yes, go for it.

**Comment by jossiey** [comment]
Hi, I have solved this issue, can I submit a PR?
