### ISSUE TITLE
Wrong cursor over text labels on block

### ISSUE THREAD

**Issue by moniika** [google/blockly#3617]
**Describe the bug**

The mouse cursor style while hovering/dragging a block when over a text label field is always an arrow when it should be a pointer hand.

**To Reproduce**

1. Pull out a block from toolbox with a text label.
2. Hover over edge and then text label
3. Observe how cursor changes to arrow when over text.

**Expected behavior**

Cursor should be pointer hand over text label.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Comment by NeilFraser** [comment]
This bug is independent of browser and OS.  Recreated on OS X Firefox.
