### ISSUE TITLE
Collapsed block text not updating

### ISSUE THREAD

**Issue by moniika** [google/blockly#3619]
**Describe the bug**

Collapsed block does not update text after label is changed with call to `setFieldValue`.

**To Reproduce**

1. Add block to workspace with text label.
2. Collapsed the block.
3. Change the value of the text label using `setFieldValue`, observe how text does not update
4. Expand block and observe text value displaying correctly.

**Expected behavior**

Collapsed block text should update after label value changes.

**Screenshots**

![f93b7f8c-758c-4882-8d2d-b01b6b9faba9](https://user-images.githubusercontent.com/6621618/72845249-090cb000-3c53-11ea-8d08-115d27202558.gif)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome

**Comment by samelhusseini** [comment]
I just tried repro'ing this bug and I believe this has been fixed. I think by this change: https://github.com/google/blockly/pull/3806
