### ISSUE TITLE
TextInput fields have extra padding in readonly

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3632]
**Describe the bug**
It looks like textinputs have more padding around them in readonly mode.

**To Reproduce**
1. Import following xml in to a playground that is in readonly mode 

` <xml xmlns="https://developers.google.com/blockly/xml">
  <block type="controls_repeat_ext" id="6B|/UvKRbPaWKPGeVR._" x="137" y="112">
    <value name="TIMES">
      <shadow type="math_number" id="HR-}CEhizODrNSY,ubD%">
        <field name="NUM">10</field>
      </shadow>
    </value>
  </block>
</xml> `

**Expected behavior**

**Screenshots**
**Readonly true**
<img width="445" alt="Screen Shot 2020-01-21 at 8 31 01 PM" src="https://user-images.githubusercontent.com/23059043/72921652-8a6e4c00-3d00-11ea-95d2-b2102203f926.png">

**Readonly false**
<img width="406" alt="Screen Shot 2020-01-21 at 8 31 10 PM" src="https://user-images.githubusercontent.com/23059043/72921656-8c380f80-3d00-11ea-952d-ba106435b6ab.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by samelhusseini** [comment]
Yeah we should probably be using field.EDITABLE instead of field.isCurrentlyEditable in the field measurable.

**Comment by moniika** [comment]
This issue is also seen in Thrasos.
