### ISSUE TITLE
Row block in plane demo incorrect location after connecting

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3639]
**Describe the bug**
When you try to connect the row block in the plane demo it doesn't have the correct location.
This only happens when a user drags directly from the toolbox. If you drop the block on the workspace and then connect it will work as expected.

**To Reproduce**
1. Go to plane demo
2. Drag out a multiplication block
3. Drag out a row block and try to attach to multiplication block

**Expected behavior**

**Screenshots**
<img width="285" alt="Screen Shot 2020-01-22 at 2 11 25 PM" src="https://user-images.githubusercontent.com/23059043/73011399-00d68100-3dc9-11ea-9e07-b0b9cee3fc48.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by MNSDivya** [comment]
Unable to reproduce the steps.

**Comment by alschmiedt** [comment]
Did you try connecting it without dropping on the workspace first? I'm still seeing this on chrome and ipad when I drag the block directly from the toolbox and try to connect without dropping it on the workspace.

**Comment by MNSDivya** [comment]
I was unable to find the rows block. Can you please assist on this.

**Comment by moniika** [comment]
Repro on Linux/Chrome:
![32d94f4e-67af-42ee-a05f-7cbc9182c420](https://user-images.githubusercontent.com/6621618/77594106-de3d1300-6eb2-11ea-8d68-e515f276492c.gif)
