### ISSUE TITLE
Warning text is hard to read (white-on-lightgreen)

### ISSUE THREAD

**Issue by mattbishop** [google/blockly#3657]
**Describe the bug**

When my application sets a warning on a block, the displayed text is unreadable.

**To Reproduce**
1. Zelos renderer, Dark theme
2. Given a block, set it's warning text programmatically: 
```javascript
block.setWarningText("Hi there, we have a problem with this block.")
```
3. Click on Warning icon.
4. See that the text is white on a light-green background and hard to read.

**Expected behavior**
The text will be black on light-green.

**Screenshots**

<img width="437" alt="Screen Shot 2020-01-25 at 10 28 57 AM" src="https://user-images.githubusercontent.com/363909/73125668-6445e780-3f5e-11ea-9da6-adb4439339d5.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15
 - Browser chrome, safari
 - Version: lastest for both

**Comment by samelhusseini** [comment]
This isn't zelos specific, the same behaviour happens in geras. I think the trick here is figuring our whether the colour contrasts better with white or black and changing the text colour accordingly.

Here it is in geras: 
![Screen Shot 2020-01-27 at 11 19 30 AM](https://user-images.githubusercontent.com/16690124/73206112-2d570980-40f7-11ea-95c0-b0d842db89a1.png)

**Comment by moniika** [comment]
It looks like the light-green background color for the warning looks a bit different than what we see reproduced on the playground:

![Untitled drawing](https://user-images.githubusercontent.com/6621618/73207287-55e00300-40f9-11ea-9cd0-2a332d54a701.png)

Possibly there is some css in play or there is some edge case that it hits.

**Comment by mattbishop** [comment]
My screenshot was taken with Safari; on Chrome it looks more like the one on the right.

The green appears the same in both.

**Comment by moniika** [comment]
It is odd that the color of the warning is lighter in safari. We should investigate that as well to ensure it isn't a bug.

**Comment by samelhusseini** [comment]
Fixing in the upcoming release.
