### ISSUE TITLE
Update custom fields documentation for updateColour->applyColour rename

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3660]
**Where**

https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/creating#matching_block_colours

**What**

  
- [X] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

If you want elements of your field to match the colours of the block they are attached to, you should override the updateColour method. You will want to use the getColour suite of functions.

```
Blockly.FieldDropdown.prototype.updateColour = function() {
  if (this.sourceBlock_.isShadow()) {
    this.arrow_.style.fill = this.sourceBlock_.getColourShadow();
  } else {
    this.arrow_.style.fill = this.sourceBlock_.getColour();
  }
};
```

**Suggested content**

If you want elements of your field to match the colours of the block they are attached to, you should override the applyColour method. You will want to access the colour through the block's style property.

```
Blockly.FieldDropdown.prototype.applyColour = function() {
  var sourceBlock = this.getSourceBlock();
  if (sourceBlock.isShadow()) {
    this.arrow_.style.fill = sourceBlock.style.colourSecondary
  } else {
    this.arrow_.style.fill = sourceBlock.style.colourPrimary
  }
};
```

**Additional context**

N/A

**Comment by samelhusseini** [comment]
Done.
