### ISSUE TITLE
Pseudo version for npm (package.json)

### ISSUE THREAD

**Issue by MarkusBordihn** [google/blockly#367]
Because NPM caching gets more aggressive, it would be needed to increase the version number in the package.json file from time to time so that NPM is downloading the latest changes.

In #366 I added the command "npm run patch", which will automatically increase the version number by x.x.1 and added the "package.json" file for git commitment.

I will take care of this from time to time, but maybe it should be automated over Travis-cl.

Please note, because we are not using the npm-js repository it would be not possible to fetch a specific version over npm even if we have pseudo numbers.

If pushing blockly to the npm-js repository automatically is needed, this is something I could work on.

**Comment by aminmarashi** [comment]
Adding semver to the npm repo helps other developers to update blockly in their project knowing what kind of change has happened. Will you officially maintain an npm repo in a near future?

**Comment by rachel-fenichel** [comment]
Version numbers are currently 2.yyyymmdd.x so they always increment.  This is semver compliant even if it looks weird, and we are working on publishing to npm.
