### ISSUE TITLE
Zelos: Reporter block with statement input

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3676]
What it looks like in Zelos:
![blockError](https://user-images.githubusercontent.com/13686399/73582443-13446080-4442-11ea-8f75-872ff1b7db78.png)

What it looks like in Geras:
![image](https://user-images.githubusercontent.com/13686399/73582451-193a4180-4442-11ea-8e83-32917014374d.png)

What it should look like:
I'm not sure.  This is the function definition, not the call.  On the other hand, making this just get taller and taller means adding more dead space in the horizontal direction, which I don't like.

**Comment by Navaneethan-B** [comment]
I'm facing this issue in the new Zelos rendering.

**Comment by samelhusseini** [comment]
I think for this sort of block (used for things like Promises), we should borrow a design choice from SNAP and only render the left side of the connection shape like so: 

![Screen Shot 2020-02-06 at 5 12 14 PM](https://user-images.githubusercontent.com/16690124/73992782-0376c180-4905-11ea-8d0f-3d8c6bf49970.png)

**Comment by samelhusseini** [comment]
So it would look something like this: 

<img width="449" alt="Screen Shot 2020-02-06 at 5 41 31 PM" src="https://user-images.githubusercontent.com/16690124/73993731-f27b7f80-4907-11ea-8c0b-6e40a44cfb79.png">

**Comment by samelhusseini** [comment]
Fixed.
