### ISSUE TITLE
Field Registration Doc Updates

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3678]
**Where**

Here:
    https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/creating#json_and_registration
Here:
    https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/extending#json_and_registration
New section here:
    https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/upgrading#danger_areas

**What**

  
Text & Code

**Old content [link 1](https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/creating#json_and_registration)**

Call Blockly.Fields.register to add your field type to this map, passing in the field class as the second argument:

```
Blockly.Field.register('field_generic', CustomFields.GenericField);
```

**Suggested content link 1**

Call Blockly.fieldRegistry.register to add your field type to this map, passing in the field class as the second argument:

```
Blockly.fieldRegistry.register('field_generic', CustomFields.GenericField);
```

**Old content [link 2](https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/extending#json_and_registration)**

```
ySubclassName.fromJson = function(options) {
  var value = Blockly.utils.replaceMessageReferences(options['value']);
  return new MySubclassName(value);
};

Blockly.Field.register('field_my_subclass', MySubclassName);
```

**Suggested content link 2**

```
ySubclassName.fromJson = function(options) {
  var value = Blockly.utils.replaceMessageReferences(options['value']);
  return new MySubclassName(value);
};

Blockly.fieldRegistry.register('field_my_subclass', MySubclassName);
```

**Old content [link 3](https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/upgrading#danger_areas)**

Nuthin'

**Suggested content link 3**

Fields are not longer registered through `Blockly.Field.register();` There is now a fieldRegistry namespace that handles registration.

```
Blockly.Field.register('my_field_name', myFieldClass);
```
Becomes:
```
Blockly.fieldRegistry.register('my_field_name', myFieldClass);
```

**Additional context**

I pulled up an old project and I realized the docs for this never got updated. Original PR is #2789

**Comment by alschmiedt** [comment]
Updated. Thanks @BeksOmega !
