### ISSUE TITLE
Child SVG remains in DOM when parent is collapsed

### ISSUE THREAD

**Issue by greyivy** [google/blockly#3682]
When a parent block is collapsed, all of its child blocks (especially those contained inside a statement input) are left in the DOM and rendered despite being hidden. If it is possible to temporarily remove these while the block is collapsed, performance could be improved dramatically, especially for large workspaces.

**Expected behavior**

Child blocks are removed from the DOM when the parent block is collapsed and not rendered again until the parent block is no longer collapsed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79

**Comment by rachel-fenichel** [comment]
In which cases are the collapsed blocks still being rendered?  Rendering happens from leaves up toward the root, so a hidden block would have to be told directly to rerender, such as when a procedure definition changes.

Do you have a repro case that I can play with for this causing a performance hit?

**Comment by greyivy** [comment]
Apologies for the poor wording. The blocks aren't rerendered, but they are left in the DOM, which causes the performance hit. 

This can be seen anywhere (e.g. the Try Blockly section at https://developers.google.com/blockly). If you collapse the loop, the print block is still in DOM if you inspect the page.

**Comment by rachel-fenichel** [comment]
The existence of the DOM nodes doesn't automatically mean that the performance is taking a hit--adding and removing nodes is much worse than having them passively there, as far as I can tell.  If you have a specific case where it's causing measurable performance degradation, I'll reopen this issue.
