### ISSUE TITLE
Failed to run with Windows WebView API

### ISSUE THREAD

**Issue by manhnt9** [google/blockly#3683]
**Describe the bug**

Blockly fails to run with IE11. Tested with IE11 and Windows' WebView API.

With browser IE11: Fixed HTML demo just shows a blank blocklyDiv.

With embedded webview in a desktop app, it shows more errors then still a blank div.

Here is what shows if I keep choosing Yes (in desktop app).

![Capture](https://user-images.githubusercontent.com/11463928/73921167-724e1d80-48f9-11ea-8bbb-407c9a6c6513.PNG)

![Capture](https://user-images.githubusercontent.com/11463928/73921200-7e39df80-48f9-11ea-980e-14efd31d0664.PNG)

![Capture](https://user-images.githubusercontent.com/11463928/73921224-885bde00-48f9-11ea-93d1-b1cc33abdbd8.PNG)

![Capture](https://user-images.githubusercontent.com/11463928/73921264-9447a000-48f9-11ea-8811-a2b388cd28ec.PNG)

**To Reproduce**
For web browser:
1. Install IE11 for Windows 10
2. Open demos/fixed/index.html with IE11

For desktop app with webview:
1. Download and extract and run 
[test.zip](https://github.com/google/blockly/files/4164124/test.zip)

(May require some DLLs, please comment and I'll add them)

**Desktop:**
 - OS: Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Screenshots**

![Capture](https://user-images.githubusercontent.com/11463928/73921591-39fb0f00-48fa-11ea-87a7-cfcefa9c9c9a.PNG)

**Comment by manhnt9** [comment]
I believe that IE10 will suffer the same bugs.

**Comment by manhnt9** [comment]
For the first bug screenshot it may be this line. I think `Blockly.Blocks` is null somehow and the access to `Blockly.Blocks.colour` is invalid.

![Capture](https://user-images.githubusercontent.com/11463928/73921167-724e1d80-48f9-11ea-8bbb-407c9a6c6513.PNG)

![Capture](https://user-images.githubusercontent.com/11463928/73922768-42544980-48fc-11ea-9dad-f5b6b8d6b16c.PNG)

**Comment by NeilFraser** [comment]
FYI: We no longer officially support IE10.  But IE11 is definitely supported.

We'll check this out in the morning.  In  the meantime, can you tell us if you are using the `master` or `develop` branch?  Thanks!

**Comment by manhnt9** [comment]
@NeilFraser it is the  Q4 2019 release. I'm gonna test master branch now.

**Comment by manhnt9** [comment]
`master` and `develop` have same errors, similar 4 bug screenshots as in the description. Hope that it'll be resolved soon!

Thanks Google Team.

**Comment by samelhusseini** [comment]
I just tried https://blockly-demo.appspot.com/static/demos/fixed/index.html on Window 10 with IE11 browser and had no trouble loading or moving blocks around.

I'm curious what's specific about your environment that's causing this issue..

**Comment by manhnt9** [comment]
Oh, I retried, latest release actually works with IE11 (both above link and my downloaded release). Not sure why I was having problems with browser yesterday.

Anyways my important issue is the desktop app with webview, browser error is like a side-finding.
I think that `blocks_compressed.js` is causing some errors with Windows WebView API.

**Comment by manhnt9** [comment]
Another clue, colour is marked as deprecated but is being used.

![Capture](https://user-images.githubusercontent.com/11463928/74003686-168d9e00-49a6-11ea-8745-73270974bb2f.PNG)

**Comment by manhnt9** [comment]
Yeah I think that's it, the first `colour` is lowercase but other `Colour` after that is uppercase.

`blocks_compressed.js`
![Capture](https://user-images.githubusercontent.com/11463928/74003751-49379680-49a6-11ea-9520-1681dda944cb.PNG)

**Comment by manhnt9** [comment]
Okay I think there's something wrong with my code!
I navigate to the `index.html` on disk instead of the embedded HTML code in the app and it worked.

![Capture](https://user-images.githubusercontent.com/11463928/74004660-01663e80-49a9-11ea-98aa-a6119ef1f796.PNG)

**Comment by manhnt9** [comment]
I think the error still persists. Somehow it works if I load external HTML file and won't work if I evaluate scripts.

The `blockly_compressed.js` passed, but the evaluation of `blocks_compressed` doesn't. I'm debugging to see which code causes error for MsJavaSrcript Engine. It raises: `Microsoft C++ exception: Js::JavascriptExceptionObject`

**Comment by manhnt9** [comment]
In the end it is on MS's webview API's side and the webview library I'm using. Not a bug of Blockly.
