### ISSUE TITLE
Is there an official XSD that we can use to verify our blockly workspaces?

### ISSUE THREAD

**Issue by bruzkovsky** [google/blockly#3688]
**Is your feature request related to a problem? Please describe.**

We have a custom parser to edit our blockly workspaces. Since we had a problem recently that we did not support a tag that was essential, is there some XSD which we can use for that? We found [blockly.xsd](https://github.com/google/blockly/blob/master/tests/xml/blockly.xsd) in the test folder, but is this official?

**Describe the solution you'd like**

Ideally a maintained XSD for the blockly workspace, living here in this repository.

**Comment by bruzkovsky** [comment]
@gentledepp FYI

**Comment by samelhusseini** [comment]
Yes, https://github.com/google/blockly/blob/master/tests/xml/blockly.xsd

**Comment by bruzkovsky** [comment]
@samelhusseini awesome, does this mean this is actively maintained?

Thanks!
