### ISSUE TITLE
Cache field dom values and only apply changes if the value has changed.

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3701]
**Is your feature request related to a problem? Please describe.**

Many things can cause a field to re-render. We shouldn't apply need to re-reapply certain attributes or commit certain dom operations if nothing has changed. 

**Describe the solution you'd like**

Perhaps keep a cache of the dom element attributes we're interested in, and apply a change only if something has changed.

**Describe alternatives you've considered**

**Additional context**

**Comment by BeksOmega** [comment]
Not sure what this means because field rerenders are all triggered explicitly, not based on changing the dom. Closing
