### ISSUE TITLE
Zelos and Geras dropdown arrows react differently to text size

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3705]
**Describe the bug (not really a bug - just a thing)**

In geras dropdown arrows match the text size.
![Size-Dropdown2](https://user-images.githubusercontent.com/25440652/74892941-ee0b8980-533f-11ea-9a5e-fdae42452adf.gif)
In Zelos they do not.
![Size-Dropdown1](https://user-images.githubusercontent.com/25440652/74892938-ed72f300-533f-11ea-8279-12177e3efdd0.gif)

This isn't really a problem, but it's something to note.

**To Reproduce**

1) Select the geras render.
2) Load the following xml:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="test_dropdowns_images_and_text">
    <field name="FIELDNAME">IMAGES AND TEXT</field>
  </block>
</xml>
```
3) Resize the text using the playground's slider.
4) Observe how the arrow changes size.
---
1) Select the zelos render.
2) Load the following xml:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="test_dropdowns_images_and_text">
    <field name="FIELDNAME">IMAGES AND TEXT</field>
  </block>
</xml>
```
3) Resize the text using the playground's slider.
4) Observe how the arrow does not change size.

**Expected behavior**

It's worth considering making them act the same. As developers switching between renderers probably expect them to act the same.

**Additional context**

N/A

**Comment by Jash2606** [comment]
@BeksOmega I would like to work on this issue. please could you assign me this issue?

**Comment by BeksOmega** [comment]
Actually I don't think this bug needs to be worked on anymore @Jash2606 because we're changing how the text sizing works. But thank you for your interest!
