### ISSUE TITLE
Sidebar missing from 'Guides' section of website

### ISSUE THREAD

**Issue by jollytoad** [google/blockly#3713]
**Where**

https://developers.google.com/blockly/guides/overview

**What**

  
- [ ] Text
- [ ] Image or Gif
- [x] Other

**Old content**

There used to be a navigation sidebar, it seems to have gone astray!

**Suggested content**

**Additional context**

<img width="499" alt="missing-sidebar" src="https://user-images.githubusercontent.com/71291/75137784-6d9ead00-56e0-11ea-846f-7c8c36536cdf.png">

**Comment by alschmiedt** [comment]
Thanks for reporting! I have filed a bug with the internal team that is responsible for this and will update you when I learn more.

**Comment by alschmiedt** [comment]
Ok just checked and it looks like it has been fixed. Let me know if you are still seeing the problem.

**Comment by hansdejong** [comment]
I reported the same issue yesterday (march 7) in the Blockly Developers-group and was pointed to this issue. The problem still exists for me, region Amsterdam. My report yesterday:
I'm trying to read the Blockly developer-guides. I'm not sure if I'm missing some setting, but today I lost the index alongside the pages, and with that the ability to navigate the guides.
(I tried it in Ubuntu firefox/chrome and Ipad.)

**Comment by alschmiedt** [comment]
Re opening since it seems to be happening again.

**Comment by alschmiedt** [comment]
From the forum post it looks like this might have to do with translating to a different language: https://groups.google.com/g/blockly/c/e6VAcA6sBCw/m/4O1mAPrRAAAJ

**Comment by MNSDivya** [comment]
![image](https://user-images.githubusercontent.com/56336353/77044607-bc8ce900-69e5-11ea-8791-e4c18fde7fa6.png)
I could see sidebar on iPad as in above screenshot.
Are we expecting anything else?

**Comment by alschmiedt** [comment]
Yes the above photo is what we are expecting. From what I can tell this is an intermittent issue that has been difficult to reproduce. Planning on leaving open for a bit longer to see if any other people report this issue.

**Comment by hansdejong** [comment]
I still have the problem with a Dutch toolbar.
I use the "hamburger-menu" for switching language, the pulldown  doesn't contain Dutch.
Other languages I tried until now don't seem to have the problem.

**Comment by bobfuru** [comment]
I'm not seeing any of the reported issues any longer. Seems like this issue could be re-closed.
