### ISSUE TITLE
Add custom blocks to blockly (npm)

### ISSUE THREAD

**Issue by foberm2s** [google/blockly#3717]
Hi there, 

I am currently using Blockly in an angular 9+ project. As of now I did not modify Blockly as such, but now want to add custom blocks to it. However, compared to the "normal" blockly (where you simply add script tags to your code and add the necessary files in the blockly/blocks/ folders), I do not see a way to do that. 

Is there even an option for the npm version to do so?

Regards
Frederik

**Comment by samelhusseini** [comment]
Yes, you can add custom blocks in the same way when using npm. The only difference is how Blocky's library gets bundled in (script tag vs import).
Here's a specific example of that: 
https://github.com/google/blockly-samples/blob/master/blockly-vue/src/blocks/stocks.js

You can refer to the samples in [blockly-samples](https://github.com/google/blockly-samples) for help integrating Blockly into your project with npm.

In the future, please post questions to our Blockly community forums at https://groups.google.com/forum/#!forum/blockly
