### ISSUE TITLE
Insertion Markers shows wrong when changing "inline" default property

### ISSUE THREAD

**Issue by gpfernandezflorio** [google/blockly#3718]
## Steps to Reproduce
1. Add a repeat block.
2. Change it to "external inputs".
3. Try to insert it somewhere.

![image](https://user-images.githubusercontent.com/5846063/75883342-a259e500-5e01-11ea-87ea-d7006538ea1d.png)

The Insertion Marker shadow shows the inline version of the block.

**Comment by samelhusseini** [comment]
Fixed.
