### ISSUE TITLE
You can open a Context on another Context

### ISSUE THREAD

**Issue by gamefroot-developer** [google/blockly#372]
So the title says it all.

You can open a context menu on a context menu, this is a problem due to most browsers first option is "back" which as you can guess is pretty scary option, when your in the process of making your masterpiece.

So I think it would be best if the context menu would be disabled on another context menu, so you wouldn't be able to open the context menu on a existing menu.

Here is a Screenshot showing the issue.
![untitled](https://cloud.githubusercontent.com/assets/17057710/15412456/d5d19df2-1e7b-11e6-83a5-dab63640dc40.png)

**Comment by NeilFraser** [comment]
Good call.  Fixed.  Thanks.
