### ISSUE TITLE
Procedure callers are tightly coupled to mutator UI

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3725]
**Describe the bug**

Procedure callers are tightly coupled to the mutator UI implementation. So there are some things that are impossible to do with a new mutator UI.

Specifically, you cannot reorder the parameters because the caller relies on blockIds from the mutator.

**To Reproduce**

Currently I have a branch of the blockly-samples repo that replicates this behavior. You can pull it [here](https://github.com/google/blockly-samples/compare/master...BeksOmega:demo/alternate-mutators) if you would like to replicate it.
1. Drag out a procedure def and a caller.
2. Add two params using the plus button.
2. Add number blocks to the param inputs.
3. Switch the order of the params using the arrows.
4. Observe how the param order switches but the blocks are not moved correctly.
![ParamOrder](https://user-images.githubusercontent.com/25440652/76047875-f4415e80-5f18-11ea-8566-bff96687fdad.gif)

**Expected behavior**

Caller should be UI-Agnostic.

**Additional context**

Problems originate in the procedure caller's [setProcedureParameters](https://github.com/google/blockly/blob/1a77a5e85938b9cd76a363f4a5b013b7a3324b69/blocks/procedures.js#L650) function.

Here is a demo pull request showing one method of fixing it: https://github.com/google/blockly/pull/3724
It is based on the idea that this can be fixed by having the procedure caller rely on variable ids instead of block ids.

**Comment by BeksOmega** [comment]
So... demo fixes the problem, but makes another problem. I didn't realize that creating another variable each time the name was edited was the intended behavior (it prevents the user from accidently renaming things they didn't want to, or accidently coalescing variables). So back to the drawing board
(┏－‿ ◕)┏

**Comment by rachel-fenichel** [comment]
> creating another variable each time the name was edited was the intended behavior (it prevents the user from accidently renaming things they didn't want to, or accidently coalescing variables). 

Did you figure this out because we have a test for it (seems unlikely) or just by exploring the code?

**Comment by BeksOmega** [comment]
> > creating another variable each time the name was edited was the intended behavior (it prevents the user from accidently renaming things they didn't want to, or accidently coalescing variables).
> 
> Did you figure this out because we have a test for it (seems unlikely) or just by exploring the code?

Just by exploring.

**Comment by BeksOmega** [comment]
Demo mk2: https://github.com/google/blockly/pull/3750

**Comment by BeksOmega** [comment]
This will be fixed as part of #6526
