### ISSUE TITLE
Blockly Developer-guides sidebar

### ISSUE THREAD

**Issue by hansdejong** [google/blockly#3726]
I reported the same issue yesterday (march 7) in the Blockly Developers-group and was pointed here. The problem still exists for me, region Amsterdam. My report yesterday:
I'm trying to read the Blockly developer-guides. I'm not sure if I'm missing some setting, but today I lost the index alongside the pages, and with that the ability to navigate the guides.
(I tried it in Ubuntu firefox/chrome and Ipad.)

(Issue #3713 was closed (I made the same comment there).

**Comment by alschmiedt** [comment]
Closing in favor of #3713
