### ISSUE TITLE
Variable fail do detect global scope

### ISSUE THREAD

**Issue by werlang** [google/blockly#3728]
In python, when updating a variable set in global scope, you need to use the global keyword, or it will give an error. In blockly, I see no way of updating a variable previously set in another scope, such as in the example.

![image](https://user-images.githubusercontent.com/19828711/76235347-bd659400-6209-11ea-95c8-0dc5c32180bd.png)

The above blocks generate the following code:

```
bar = 0
def foo():
    bar = bar + 1
    print(bar)
foo()
```

Which give the following error when run:

```
Traceback:
File "answer.py", line 3, in foo
bar = bar + 1
File "answer.py", line 5
foo()
UnboundLocalError: UnboundLocalError: local variable "bar" referenced before assignment on line 3
```

The correct code generated to avoid this error and run according to the intent is:

```
bar = 0
def foo():
    global bar
    bar = bar + 1
    print(bar)
foo()
```

**Comment by NeilFraser** [comment]
I've never seen that 'define' block before.  Where does that block come from?  It's badly programed if it doesn't use "global".

For reference, the blocks that come with Blockly behave correctly:
https://blockly-demo.appspot.com/static/demos/code/index.html#mciwtq

```
bar = None

def foo():
  global bar
  bar = bar + 1
  print(bar)

bar = 0
foo()
```

**Comment by werlang** [comment]
Oh yes, my bad. The block was not correctly programmed.

Can you please direct me to a somewhere that shows how to program such a custom procedure blocks?

**Comment by NeilFraser** [comment]
No problem.  Here's the code for the Python generator on the default procedure block:
https://github.com/google/blockly/blob/master/generators/python/procedures.js#L29

The first thing it does is handle global variables.
