### ISSUE TITLE
Create a Public Metrics Method 

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3746]
**Is your feature request related to a problem? Please describe.**
Currently the only way to get metrics is by using the same method we use internally for processes that need to know just about everything about the workspace. Therefore, the method returns a lot of information that is not well organized or very well documented. 

**Describe the solution you'd like**
A metrics method that is meant to be public and provides a subset of the current values returned from getMetrics with easier to understand and better documented values. 

**Describe alternatives you've considered**

**Additional context**
Possible Use Cases: 
- Where to position something relative to the toolbars. 
- For scrolling to blocks

**Comment by alschmiedt** [comment]
So far it seems like the following methods would be most useful: 

**getAbsoluteMetrics** (or different name)

Gets the metrics for the workspace without the toolbox.
This would be used for anything that needs to be positioned on top of the workspace. 
**Examples**: WorkspaceSearch, Trashcan, ZoomControl, Flyouts, Modals*
returns {
   absoluteLeft  
   absoluteTop 
   absoluteWidth
   absoluteHeight
}
*Modals would have to be used with workspace.getParentSvg().getClientBoundingRect() since the modal is outside of the blockly div(because it uses the widgetDiv)

**getContentMetrics** (probably different name. I don't like this name.)

This would hold what is currently the content and view metrics from our current getMetrics method.
This would be used for anything that needs to be positioned on the workspace or need information on how the workspace is scrolled.
**Examples**: Bubble, Scrolling on workspace

**getToolboxMetrics**

Contain the metrics for both the flyout and toolbox
Not currently used internally anywhere except flyout_vertical and flyout_horizontal. And I think that might be able to be factored out.

**Comment by alschmiedt** [comment]
Related concerns:
* Having some way to display debug rectangles similar to rendering_debug would be nice.
* I think making these methods public would fix the problem where users who want to create their own `getMetrics` method but don't want to have to copy and paste all of the private `getTopLevelWorkspaceMetrics_`.

**Comment by maribethb** [comment]
Another use case would be preventing blocks from going behind an always-open flyout (more specifically, a flyout on a toolbox where the flyout has autoClose = true. This already works when the workspace contains just a flyout and no toolbox). Currently to achieve this, most of getTopLevelWorkspaceMetrics is fine, but we need to change some properties to take into account the width of both toolbox + flyout. So having this method public would allow me to call it from a custom getMetrics method without having to copy/paste a bunch of code I don't need to change.

The approach of having multiple smaller public methods also seems like it could work, I could call those methods for the values I don't need to change, and put their values into my custom getMetrics method.
