### ISSUE TITLE
Input fields unresponsive in fullscreen mode

### ISSUE THREAD

**Issue by bartbutenaers** [google/blockly#3758]
Hello everybody,

Last year I [integrated ](https://flows.nodered.org/node/node-red-contrib-blockly)blockly into the Node-RED IOT framework.  This works fine but our users have asked to be able to show the Blockly editor in _**full-screen**_ mode.  I have implemented that feature request in [plain](https://www.w3schools.com/howto/howto_js_fullscreen.asp) Javascript, and it works!  

But the problem is that (only in fullscreen mode) the input fields don't respond: 
+ When clicking on a dropdown, the dropdown doesn’t appear
+ When clicking on a color picker, the picker doesn’t appear
+ When clicking on an edit box, the text is not selected and you can not enter new characters
+ ...

In had this problem in my old Blockly version, but after installing the *current version from the Github master* branch it is still the same behaviour.  So I assume it is in all Blockly versions...

**To Reproduce**

I used the following standard code snippet to goto fullscreen mode, when an expand button is clicked:
```
var blocklyArea = $("#node-red-contrib-blockly-expandable");
var blocklyFullScreenRequest = blocklyArea[0].requestFullscreen || blocklyArea[0].mozRequestFullScreen || blocklyArea[0].webkitRequestFullscreen || blocklyArea[0].msRequestFullScreen;
// Check whether the browser supports fullscreen
if (blocklyFullScreenRequest) {
   // Expand the Blockly editor when the expand button has been clicked
   expandblocklyAreaButton.click(function(e) {
      // Make sure (on all browsers) that the blocklyArea DIV element has 100% AFTER it has become fullscreen
      // If document.fullscreenElement is null then full-screen mode has been quitted...
      blocklyArea.on('webkitfullscreenchange mozfullscreenchange msRequestFullscreen fullscreencha nge', function(e) {
         if (document.fullscreenElement) {
            // Make sure the blockly area fills the entire screen
            document.fullscreenElement.style.height = "100%";
         }
      });
                    
      // Expand the blocklyArea element to fullscreen
      blocklyFullScreenRequest.call(blocklyArea[0]);
   })
}
```
1. Show the Blockly editor in fullscreen mode.
2. Try to enter a text in a text input field, or try to open a dropdown input.
3. Nothing will happen ...

**Expected behavior**

I expect in fullscreen mode that I can enter data into my blocks.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox, Edge

**Stack Traces**

I don't see any issues in my console log.

**Additional context**

Have spend some hours debugging the events of a colorpicker, but now I'm stuck ...

Here is a demo animation for a color picker in normal (non-fullscreen) mode:

![demo_normal](https://user-images.githubusercontent.com/14224149/77142775-771df980-6a81-11ea-94eb-65221000534d.gif)

As you can see: the events (mouse, keydown, ...) arrive nicely in Blockly.  And as soon as the transform is executed, the color picker is displayed at the correct location.

But when we look at the demo for the same color picker in fullscreen mode:

![demo_fullscreen](https://user-images.githubusercontent.com/14224149/77142758-63729300-6a81-11ea-9ea5-855515262eae.gif)

You can see that the colorpicker is NOT displayed after executing the transform statement.  However when I open the color picker (variable "f" in above code) in the console, it seems to have the correct structure (i.e. seems identical to one in normal mode):

![image](https://user-images.githubusercontent.com/14224149/77143701-383d7300-6a84-11ea-8a0b-53b31a37e859.png)

This means the color picker has the correct html structure, but this html elements don't become visible after the transform statement.

So I thought that the parent element perhaps would be wrong, but in both modes the console shows that variable "f" has the (Node-RED) body element as parent:

![image](https://user-images.githubusercontent.com/14224149/77143841-9bc7a080-6a84-11ea-8ee6-f93f873236ca.png)

Which means that in both modes the color picker should become available in the body.  Don't know if that is a problem in fullscreen mode, since the body is perhaps displayed BELOW the blockly editor (so the body is invisible)????

When I let my program run, at the end the color picker html elements will be added to the DOM tree in normal mode:

![image](https://user-images.githubusercontent.com/14224149/77144220-90c14000-6a85-11ea-93e2-7f44b96cf5a8.png)

But at the end in fullscreen mode, the color picker html table is not available anymore:

![image](https://user-images.githubusercontent.com/14224149/77144278-ba7a6700-6a85-11ea-81af-d454593655d3.png)

That might be the reason why the color picker is not visible?  But I have no clue why this html table is not added in fullscreen mode...

Hopefully somebody can help me, because this is way too far into depth for me ;-(

Thanks a lot !!
Bart Butenaers

**Comment by rachel-fenichel** [comment]
Definitely sounds like the elements are somehow ending up below the blockly editor in fullscreen mode.  Interesting that it's not just in one browser.

@samelhusseini thoughts?

**Comment by samelhusseini** [comment]
The full screen api takes a DOM element and places it full screen. Blockly uses a WidgetDiv, and a Dropdown div as supplemental elements that are placed at the bottom of the page for showing fields inputs, context menus, etc.

So by taking the Blockly injection div (or blockly area in your case) and making it full screen. The widget div element and dropdown div element remain outside that scope and are not shown. 

The only way around that if so place everything ``blocklyDiv``, ``blocklyDropDownDiv``, and ``blocklyWidgetDiv`` in the same container (say blocklyArea), and call fullscreen on that element.

The widgetdiv and dropdown divs are injected to ``document.body`` by Blockly, and we don't currently provide an easy way to change that. We should be able to allow you to adjust that.

**Comment by bartbutenaers** [comment]
Hi Rachel (@rachel-fenichel), Sam (@samelhusseini),

Wow that is fast and great support...  Thanks a lot!!!
Is there an easy way for me to install the Blockly version with the pull request code?
Or should I wait perhaps until the pull request review is completed?

Kind regards,
Bart

**Comment by samelhusseini** [comment]
This will be fixed in the upcoming release next week using: 
```
Blockly.setParentContainer(...)
```
run before the initial inject.

**Comment by bartbutenaers** [comment]
Hi Rachel (@rachel-fenichel), Sam (@samelhusseini),
Thanks again!
Bart
