### ISSUE TITLE
Unable to include new categories

### ISSUE THREAD

**Issue by Botcho3003** [google/blockly#3760]
Greetings. I am trying to create new blocks, but I can't find a way to include the new file in my .html file. However, I tried using <script src="blocks/events.js"></script> at the beginning of the file, but that doesn't seem to work.

**Comment by rachel-fenichel** [comment]
Some debugging steps:
- check the console for errors
- make sure that your files are in the correct directories relative to each other

Note that adding new block definitions does not automatically [add them to the toolbox](https://developers.google.com/blockly/guides/configure/web/toolbox).

In the future, please post questions like this on our [forum](https://groups.google.com/forum/#!forum/blockly), where there's a group of other developers who may be able to help with debugging common issues.
