### ISSUE TITLE
Typo at ja.js

### ISSUE THREAD

**Issue by yoshi1125hisa** [google/blockly#3770]
**Describe the bug**
`リストの指定された部分のコピーを作成してくださ。` is wrong and `リストの指定された部分のコピーを作成してください。`  is correct.

**Comment by rachel-fenichel** [comment]
Thanks for the bug report.  We do all translations through translatewiki.net, and changes made directly in this repo do not persist.  See [this page](https://developers.google.com/blockly/guides/modify/web/translating) for more information about translation.
