### ISSUE TITLE
Procedure block tests

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3781]
The procedure blocks are fragile in part because they are missing some tests.  Some test cases:
- Serialization
- Deserialization
  - Deserialization with the caller before the definition
- Deletion
- Compose
- Decompose
- Add parameter
- Remove parameter
- Rename parameter
- Reorder parameter

**Comment by BeksOmega** [comment]
Sorry! On the demo I wasn't very clear. I just meant that there wasn't a test for "typing over" a variable that had already been created. There are /some/ procedure tests.
<details>
<summary>Current Tests</summary>

- isNameUsed
  - No Blocks
  - True
  - False
- rename
  - Simple, Programmatic
  - Simple, Input
  - lower -> CAPS
  - CAPS -> lower
  - Whitespace
  - Whitespace then Text
  - Set Empty
  - Set Empty, and Create New
- getCallers
  - Simple
  - Multiple Callers
  - Multiple Procedures
  - Call Different Case
  - Multiple Workspaces
- getDefinition
  - Simple
  - Multiple Procedures
  - Multiple Workspaces
- Mutation
  - Composition
    - Statements
      - Has Statements
      - Has No Statements
      - Saving Statements
    - Untyped Arguments
      - Simple Add Arg
      - Multiple Args
      - Simple Change Arg
      - lower -> CAPS
      - CAPS -> lower
      - Set Arg Empty
      - Whitespace
      - Whitespace and Text
      - <>
  - Decomposition
    - Statements
      - Has Statement Input
      - Has Statements
      - No Has Statements
    - Untyped Arguments
      - Simple Single Arg
      - Multiple Args
      - <>

</details>

But there still need to be more for things you mentioned: deserializing callers first, reordering params, etc.

**Comment by rachel-fenichel** [comment]
I take that back: "don't have tests" -> "are missing some tests".

The tests that I think are missing are around mutating a definition while there are callers with blocks connected.  The [closed bugs around functions](https://github.com/google/blockly/issues?q=is%3Aissue+label%3A%22component%3A+functions%22+is%3Aclosed) show that we've played whack-a-mole with those issues in the past.

**Comment by cpcallen** [comment]
Assigned to @BeksOmega on the theory that Rachel asked for this to be addressed before making other changes to procedures, and Beka seems to be keen on writing test (or at least decidedly diligent about doing so, anyway).
