### ISSUE TITLE
[Keyboard nav] keyboard press is captured by browser

### ISSUE THREAD

**Issue by SebCanet** [google/blockly#3792]
**Describe the bug**

When using keyboard navigation non Firefox 73 or 74, my key pressed are captured by Firefox and it opens search with the key I pressed.
On Chromium it seems to work normally.

**To Reproduce**

1. Go to http://google.github.io/blockly/tests/playground.html or http://google.github.io/blockly/demos/keyboard_nav/index.html
2. Click on "Enable Accessibility Mode"
3. Key press
4. Search bar opens

**Desktop (please complete the following information):**
 - OS: Windows 7 or 10 x64
 - Browser: Firefox
 - Version: 73 & 74

**Comment by alschmiedt** [comment]
hello! I am having trouble reproducing this issue. Is it a specific key combination that is opening up the search bar? Or hitting any key will open it?

**Comment by SebCanet** [comment]
After many tests, I think it's a problem with my Firefox.
It's a portable version, copied on 3 computers and synced together...so that's why the pb was on different computers/Firefox.
So it's just on one Firefox, with any key...
After tests on Edge, Chromium and Firefox, this bug exists no more (except for my Portable Firefox...).
So I close, sorry.
