### ISSUE TITLE
mutator error when clicking after attach a block

### ISSUE THREAD

**Issue by carloslfu** [google/blockly#38]
![bug-report1](https://cloud.githubusercontent.com/assets/5993168/5587762/3b8f1d0c-90c2-11e4-924a-0b3be5e35279.jpg)

**Comment by NeilFraser** [comment]
Partially fixed now.  A similar issue with 'if' mutators remains.  This is the top priority, will be fixed today or tomorrow (I'm just back from vacation).

**Comment by NeilFraser** [comment]
Fully fixed now.  Thanks!
