### ISSUE TITLE
Highlighted/disabled input statements look overlapped in zelos

### ISSUE THREAD

**Issue by mattbishop** [google/blockly#3802]
**Describe the bug**

Zelos L&F blocks with input statements appear overlapped when highlighted or disabled. They kind of look overlapped when enabled and unhighlighted, too, but that's not so bad.

**Expected behavior**

A nice non-overlapped block layout.

**Screenshots**

<img width="323" alt="Screen Shot 2020-04-10 at 3 06 29 PM" src="https://user-images.githubusercontent.com/363909/79026214-f2347600-7b3c-11ea-89d5-b34fbc30a4b6.png">
<img width="364" alt="Screen Shot 2020-04-08 at 2 28 29 PM" src="https://user-images.githubusercontent.com/363909/78835965-f9754b80-79a5-11ea-9d46-af2415a8690b.png">
<img width="364" alt="Screen Shot 2020-04-08 at 2 28 45 PM" src="https://user-images.githubusercontent.com/363909/78835970-fc703c00-79a5-11ea-822c-017cb8caea11.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser safari (chrome too)
 - Version 13.1, chrome 80

**Comment by hpnrep6** [comment]
This issue most likely has been fixed by #5369.

**Comment by BeksOmega** [comment]
You are correct @hpnrep6 ! Thanks for flagging.
