### ISSUE TITLE
Blockly dropdown repeact options

### ISSUE THREAD

**Issue by foreverzmy** [google/blockly#3807]
**Describe the bug**

I use blockly develop, but I want to define custom toolbox style，It works，but the block dropdown will repect options when click block, not select option, just click dropdown, can you help me to resolve it? 

**To Reproduce**

1. Go to [Demo](https://react-ts-k1thkj.stackblitz.io/).
2. Drop `logic_operation` block to panel.
3. Click `and` position.
![image](https://user-images.githubusercontent.com/11779129/79003705-b540a180-7b85-11ea-955c-1d9fbe49d01d.png)
4. See options repeat.

**Expected behavior**

options not repeat.

**Screenshots**

![image](https://user-images.githubusercontent.com/11779129/79003364-0603ca80-7b85-11ea-8f96-650146f24eab.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome
 - Version: 80.0.3987.163

**Comment by samelhusseini** [comment]
What version of Blockly are you running?
Looks like the dropdown div's dispose method is not getting called.

This does not repro on our [Blockly demo](https://blockly-demo.appspot.com/static/demos/fixed/index.html).

**Comment by foreverzmy** [comment]
> What version of Blockly are you running?
> Looks like the dropdown div's dispose method is not getting called.
> 
> This does not repro on our [Blockly demo](https://blockly-demo.appspot.com/static/demos/fixed/index.html).

Sorry, I forgot to show the resource, here is the [code](https://stackblitz.com/edit/react-ts-k1thkj), blockly version is `3.20200402.1
`.

**Comment by samelhusseini** [comment]
Looked at your code, and I don't see a bug in Blockly.
You're overriding ``Blockly.hideChaff``, but you're not calling: 
```
  Blockly.Tooltip.hide();
  Blockly.WidgetDiv.hide();
  Blockly.DropDownDiv.hideWithoutAnimation();
```
https://github.com/google/blockly/blob/master/core/blockly.js#L325

If you add those to your code, everything works.

Cool toolbox btw. @alschmiedt is currently taking ideas for developer APIs that would make writing custom toolboxes easier, I'm sure she'd love to hear from you [here](https://groups.google.com/forum/#!topic/blockly/5h2j_TG4oVQ).

**Comment by foreverzmy** [comment]
@samelhusseini Thanks to help me resolve this problem, I will connect to alschmiedt for contribute my own ideas.
