### ISSUE TITLE
Add properties to the Blockly.blockRendering.IPathObject interface

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3816]
Add the following properties to the IPathObject interface: 
- svgPath, used by Blockly.BlockSvg and the workspace search plugin.
- constants, used by Blockly.BlockSvg
- cursorSvg, used by Blockly.BlockSvg
- markerSvg, used by Blockly.BlockSvg
- style, used by many fields

Here's how to do it: 
https://github.com/google/closure-compiler/wiki/Structural-Interfaces-in-Closure-Compiler#nominal-interfaces

**Comment by rachel-fenichel** [comment]
@samelhusseini is this done?

**Comment by samelhusseini** [comment]
Yep.
