### ISSUE TITLE
xml_test test case throws error after test run

### ISSUE THREAD

**Issue by moniika** [google/blockly#3819]
**Describe the bug**

 The test case under` mocha/xml_test.js` `'Headless -> XML -> Rendered -> XML'` causes an error to be thrown due to async logic triggered by `domToBlockHeadless_`.

**To Reproduce**

Run mocha/xml_test.js

**Expected behavior**

Tests should not throw a console error.

**Stack Traces**

```
comment.js:247 Uncaught TypeError: Cannot read property 'isEditable' of null
    at Blockly.Comment.createBubble_ (comment.js:247)
    at Blockly.Comment.setVisible (comment.js:236)
    at xml.js:671
```

**Additional context**

Looking into the source of the error, it appears it is caused by a setTimeout call in `domToBlockHeadless_` in comment case. It may be the case that the cleanup function (`workspace.dispose()`) is called and then the setVisible call is made (and error).

Adding `async` to test appears to prevent error, but it may not be the correct fix.

**Comment by BeksOmega** [comment]
Would using a [sinon fake timer](https://sinonjs.org/releases/v1.17.6/fake-timers/) work?

**Comment by moniika** [comment]
> Would using a [sinon fake timer](https://sinonjs.org/releases/v1.17.6/fake-timers/) work?

I think sinon fake timer would work, but it relies on us knowing how long to move the clock. So, if possible something like an await, if possible, would be nicer from a maintenance perspective.

**Comment by samelhusseini** [comment]
Async + await would only work if there is a promise to await on. setTimeout doesn't return a promise.
To me it appears your best bet with this behaviour is to use a timeout (be forgiving, wait a bit longer than you think you need to), and then use the done callback to tell mocha when you're done.

```

   test('Comment', function(done){
       setTimeout(function(){

          ..... 

           done();
       }, 3000)
   })
```

**Comment by rachel-fenichel** [comment]
@moniika is this done?
