### ISSUE TITLE
JavaScript reverse to blokly  visualization 

### ISSUE THREAD

**Issue by wang1104014663** [google/blockly#383]
I want to make javasceipt code transform to blockly visualization .

**Comment by NeilFraser** [comment]
Sounds interesting.  We look forward to seeing the results.

**Comment by nisen** [comment]
I create a project name as Js2Blockly.I can guide a student as a gsoc2016 or  gsoc2017 project. 
https://github.com/osokay/js2Blockly

**Comment by nisen** [comment]
This may be a gosc2017 project. I can be a mentor :)

**Comment by nisen** [comment]
## The Next Project May Be Useful

* https://github.com/NeilFraser/JS-Interpreter 
* Parser Generator for JavaScript http://pegjs.org/development

**Comment by rraallvv** [comment]
Someone already did this for Python, the repo is at https://github.com/RealTimeWeb/blockpy and the demo page is at http://think.cs.vt.edu/blockpy/load

It seems that they implemented a parser from Python AST to blocks by mapping the AST nodes to a custom library of Blockly blocks.

So, the round trip from JS to blocks could be accomplished by adding the JS AST nodes that are missing in Python’s and making the parser read the JS AST instead.
