### ISSUE TITLE
Make copy/paste logic extensible

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3833]
The ICopyable interface describes what it means to have an object on the workspace be copyable.

We should support extending the objects that can be pasted.

Proposed design: 
- Add registerCopyPasteProvider on the workspace (or a derivative object)
- When something is pasted, go through all registered providers and give each of them the opportunity to handle it. 
Eg: workspace comment would look at the XML tag, and decide if its theirs (ie: == comment), and move on otherwise. A block would only handle XML for the block tag.

These providers may want to also maintain additional metadata for copying / pasting, in the case of blocks, it would want to keep track of typeCounts.

**Comment by BeksOmega** [comment]
This was completed as part of work on https://github.com/google/blockly/issues/6275
