### ISSUE TITLE
Field Dropdown and Field Variable options opening mispositioned when inside a compose/decompose mutator

### ISSUE THREAD

**Issue by joseluiz98** [google/blockly#3834]
Hi guys!

I have a compose/decompose mutator with sub blocks that have either FieldDropdown or FieldVariable so user can select the correct option. But when I open this dropdowns, they are positioned ackward on the screen, always on the left side, instead of below its trigger like the html select.

**To Reproduce**

Just create a mutator with compose and decompose methods so the button trigger that opens the bubble will appear, like its mentioned on the docs. Then, pass a block that have a fieldDropdown in the args to this mutator, and open this dropdown inside the bubble.

**Expected behavior**

I expect the field dropdown options to appear below the trigger, the same behavior as the html select with the option array inside it.

**Screenshots**

![image](https://user-images.githubusercontent.com/24555974/79599494-f7a13b80-80bb-11ea-9ed0-579ce3a82afc.png)

**Comment by samelhusseini** [comment]
Thanks for filing the bug @joseluiz98. We've been able to reproduce your problem and have a fix: https://github.com/google/blockly/pull/3835
