### ISSUE TITLE
Can't drag a block out of the toolbox by a child shadow block

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#385]
If you click and drag on a child shadow block in the toolbox it doesn't do anything. If you click on one of the shadow block's fields it works, but clicking the block itself gets ignored.

https://github.com/LLK/scratch-blocks/issues/357

**Comment by drigz** [comment]
@RoboErikG, I'm looking at this problem but I don't see the same behaviour as you. I can't drag from the shadow block or its field, when testing with 4ba2b1b on Chrome on Linux.

Are we using different versions or are we testing differently?

![drag from shadow](https://cloud.githubusercontent.com/assets/632207/15855209/8faf0c88-2cae-11e6-9515-4ac31583e5aa.gif)
*trying to drag shadow blocks in 4ba2b1b - not very clear as there's no visual feedback on mousedown/up*

**Comment by rachel-fenichel** [comment]
Not just the shadow blocks--also can't drag on any connected (input or next) blocks.  See the jabberwocky category here: https://blockly-demo.appspot.com/static/demos/toolbox/index.html
