### ISSUE TITLE
Block instant search bar

### ISSUE THREAD

**Issue by joseluiz98** [google/blockly#3851]
**Featura request description**

My suggestion consists on a block search bar, where the user would have a instant search bar behavior to find the block he wants to drag.

**Print**
Below I attached a print so you guys could have this feature with a visual idea. You may see the search box above the main categories toolbox.

![image](https://user-images.githubusercontent.com/24555974/80000981-3a845a00-8494-11ea-8960-4f63e8beb474.png)

**Comment by moniika** [comment]
Thanks for the suggestion!

We've done some work with workspace search in [Blockly Samples](https://github.com/google/blockly-samples) and searching in the toolbox is a good candidate for another plugin for Blockly (in Blockly Samples).
We are currently working on some cleanup and refactoring in the toolbox code, and after that, this would be a good avenue to explore.

**Comment by rachel-fenichel** [comment]
Closing in favor of https://github.com/google/blockly-samples/issues/242

**Comment by joseluiz98** [comment]
> Thanks for the suggestion!
> 
> We've done some work with workspace search in [Blockly Samples](https://github.com/google/blockly-samples) and searching in the toolbox is a good candidate for another plugin for Blockly (in Blockly Samples).
> We are currently working on some cleanup and refactoring in the toolbox code, and after that, this would be a good avenue to explore.

Ok, thank you for the heads up, we're always trying to make Blockly even better =)

**Comment by liuhongbo1** [comment]
I also need the searchbar, can you tell me how do you solve it, thanks!

**Comment by moniika** [comment]
> I also need the searchbar, can you tell me how do you solve it, thanks!

There is no instant search bar currently implemented. This bug is closed, but the  bug https://github.com/google/blockly-samples/issues/242 is where we are tracking the status of the feature.
If you'd like to get help with Blockly, you can ask questions on our [developer forum](https://groups.google.com/g/blockly).
