### ISSUE TITLE
Shadow blocks lose the mutationToDom

### ISSUE THREAD

**Issue by duzc2** [google/blockly#3860]
**Describe the bug**
When a shadow block be respawning , does not have the mutationToDom.

**To Reproduce**

1. Config a toolbox with :
 block A has Shadow block B,
 B have a mutation.
 block C have same output as B.
2. drag A into the workspace
3. drag C into block A
4. remove C from A.
5. B respawn back ,but it lost the mutation

**Expected behavior**
when B respawn back ,it should have the same mutation as it was hadden

**Screenshots**

**Desktop (please complete the following information):**
 OS: Windows
 Browser chrome
 Version 78

**Stack Traces**

```
Uncaught Error: Child block does not have output or previous statement.
    at Blockly.RenderedConnection.Blockly.Connection.respawnShadow_ (blockly_compressed.js:formatted:3863)
    at Blockly.RenderedConnection.respawnShadow_ (blockly_compressed.js:formatted:8265)
    at Blockly.RenderedConnection.Blockly.Connection.disconnect (blockly_compressed.js:formatted:3840)
    at Blockly.BlockSvg.Blockly.Block.unplugFromRow_ (blockly_compressed.js:formatted:6875)
    at Blockly.BlockSvg.Blockly.Block.unplug (blockly_compressed.js:formatted:6869)
    at Blockly.BlockSvg.dispose (blockly_compressed.js:formatted:8888)
    at Object.callback (blockly_compressed.js:formatted:8000)
    at Object.<anonymous> (blockly_compressed.js:formatted:7938)
    at Blockly.MenuItem.performActionInternal (blockly_compressed.js:formatted:7888)
    at Blockly.MenuItem.handleClick (blockly_compressed.js:formatted:7883)
```

**Additional context**

**Comment by duzc2** [comment]
I generate the output connection via the mutation.
when the shadow respawn , the mutation dom is lost,
and build a block without output connection.
and throws the error

**Comment by BeksOmega** [comment]
Hi! I'm not on the blockly team, but I think it might be easier for them to reproduce your issue if you provide a simplified block definition that replicates this problem. At the moment it's kind of hard to test since none of the core blocks work this way :/

I'm sure they really want to get this fixed though so anything you could provide would help!

**Comment by duzc2** [comment]
` 
<xml id="xml">
        <block type="math_number"></block>
        <block type="test">
            <mutation>abcdefg</mutation>
        </block>
        <block type="test">
            <mutation>number</mutation>
        </block>
        <block type="math_arithmetic">
            <field name="OP">ADD</field>
            <value name="A">
                <shadow type="test">
                    <mutation>number</mutation>
                </shadow>
            </value>
            <value name="B">
                <shadow type="math_number">
                    <field name="NUM">1</field>
                </shadow>
            </value>
        </block>
    </xml>
`

`
        let test_mutation = function () { }
        let test_mutator = {
            mutationToDom: function () {
                return this.mutationDom
            },
            domToMutation: function (xmlDom) {
                console.log(xmlDom);
                this.mutationDom = xmlDom = xmlDom;
                let input = this.appendDummyInput();
                let field = new Blockly.FieldLabel(xmlDom.innerHTML);
                input.appendField(field);
                if(xmlDom.innerHTML == 'number'){
                    this.setOutput(true,"Number")
                }
            }
        }
        Blockly.Extensions.registerMutator('test_mutator',
            test_mutator, test_mutation);
        Blockly.Blocks['test'] = {
            init: function () {
                this.jsonInit({
                    "message0":"message",
                });
                Blockly.Extensions.apply('test_mutator', this, true)
            }
        }
`

I'm sorry ,I don't know how to keep the format...

**Comment by duzc2** [comment]
![image](https://user-images.githubusercontent.com/564778/80364528-ac0b4080-88b8-11ea-82ec-89db2e082343.png)
![image](https://user-images.githubusercontent.com/564778/80364614-cfce8680-88b8-11ea-95fb-87e891c7821b.png)
![image](https://user-images.githubusercontent.com/564778/80364675-e4ab1a00-88b8-11ea-9ac4-e27102b3da87.png)
![image](https://user-images.githubusercontent.com/564778/80364698-ed9beb80-88b8-11ea-95e2-cfd71e50e078.png)

it got error when I try to remove the inner block:
![image](https://user-images.githubusercontent.com/564778/80364762-07d5c980-88b9-11ea-8a0e-2a396670552a.png)
![image](https://user-images.githubusercontent.com/564778/80364779-0efcd780-88b9-11ea-908c-2b7f7bfee769.png)

**Comment by duzc2** [comment]
cut &paste lose the mutation too ~~~~~

**Comment by samelhusseini** [comment]
I looked into this and this does not appear to be a bug in Blockly, the built in blocks don't suffer from the same issue. 
Specifically for your code, it seems keeping around the mutation node and re-using it between blocks is causing weird behaviour. Instead, serialize the mutation node using `Blockly.Xml.textToDom` and `Blockly.Xml.domToText` to achieve the same outcome: 

```js

let test_mutation = function () { }
let test_mutator = {
  mutationToDom: function () {
    return Blockly.Xml.textToDom(this.mutationDom);
  },
  domToMutation: function (xmlDom) {
    this.mutationDom = Blockly.Xml.domToText(xmlDom);
    let input = this.appendDummyInput();
    let field = new Blockly.FieldLabel(xmlDom.innerHTML);
    input.appendField(field);
    if(xmlDom.innerHTML == 'number') {
      this.setOutput(true, "Number");
    }
  }
}
Blockly.Extensions.registerMutator('test_mutator', test_mutator, test_mutation);
Blockly.Blocks['test'] = {
  init: function () {
    this.jsonInit({ "message0":"message", });
    Blockly.Extensions.apply('test_mutator', this, true);
  }
}
```

Hope that helps.
