### ISSUE TITLE
Add 'renderer' config property documentation

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3869]
**Where**

https://developers.google.com/blockly/guides/get-started/web#configuration

**What**

  
- [X] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

N/A

**Suggested content**

Add a row for the 'renderer' property. Optionally include a list of valid pre-packaged renderers, or have a separate page that this row links to.

For example:
|Name|Type|Description|
|-|-|-|
|renderer:| string|Determines the renderer used by blockly. Pre-packaged renderers include 'geras' (the default), 'thrasos', and 'zelos' (a scratch-like renderer).

**Additional context**

N/A

**Comment by rachel-fenichel** [comment]
Done.
