### ISSUE TITLE
Shadows are darker (instead of lighter) when using default theme with zelos

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3870]
**Describe the bug**

If you switch your renderer to zelos without changing the theme from default -> modern your shadow blocks end up looking darker instead of lighter.

**To Reproduce**

1. Open the playground
2. Switch to zelos
2. Drag out the text print block.
3. Observe how the shadow is darker.
4. Switch to the modern theme.
5. Observe how the shadow is lighter.

**Expected behavior**

I would expect the shadows to be lighter by default, because this is clearer for the user.

**Additional context**

This issue was originally reported by a lovely developer on the forums [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/blockly/r6EmKsVfv5A/6gwu3S7iAwAJ). You can also go there to see screen shots =)

**Comment by samelhusseini** [comment]
When the secondary / tertiary colours are not set (which they aren't for the default theme: `Blockly.Themes.Classic`), the decision on how to generate the secondary and tertiary colours falls back onto the renderer. 

I can see how it's confusing if you're expecting the shadow colour to be lighter.
I think the decision for making the secondary colour darker, came from both Scratch and MakeCode choosing darker colour for their default shadow colour. (and zelos is based on their renderers)

Note: the tertiary colour is also darker than both the primary and secondary colours. ie: 
primary = colour
secondary = darken(colour, 0.15)
tertiary = darken(colour, 0.25)

That being said, this is something developers can adjust, either by: 
- creating a new renderer and overriding constants `generateSecondaryColour_`.
- setting the secondary colour in their theme.

**Comment by BeksOmega** [comment]
Sounds good to me @samelhusseini !
