### ISSUE TITLE
removeBlockById() won't remove blocks from my workspace!

### ISSUE THREAD

**Issue by joseluiz98** [google/blockly#3881]
**Describe the bug**

workspace.removeBlockById() isn't removing the block from my workspace. It didn't throw any errors, but the blocks are getting someway broken after I run this function, and the block keeps on my Blockly editor for the user. Then, when I try to move or delete by dragging them to the trash, or even right-click them, my console blows with many errors.

Here's my code:

```
let idx = 1;
while (SELF.workspace.getBlockById('FILTER' + idx)) {
    SELF.workspace.removeBlockById('FILTER' + idx);
    idx++;
}
```

When I change 

`SELF.workspace.removeBlockById('FILTER' + idx);`

to

`SELF.workspace.getBlockById('FILTER' + idx).dispose(false);`

It runs ok! This was a tip I got from @BeksOmega  [on this topic](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/blockly/8tWEMu8wFOY), to bypass this bug.

**To Reproduce**

So, i've created a block with workspace.newBlock('FILTER' + idx), idx is just a counter to certify blocks are created with unique IDs. Then, I may need to remove this blocks depending on user actions on my mutator, so, I remove all of 'filter' blocks before creating them again, but when I tried to remove using workspace.removeBlockById(), nothing happens on the screen and the blocks "delted" are getting broken, fixed, on my blockly editor.

**Expected behavior**

I expect, according to the [documentation of this function](https://developers.google.com/blockly/reference/js/Blockly.Workspace#removeBlockById), that the block passed as parameter via valid ID must disappear of my Blockly editor for the user. If I understood documentation correctly, of course.

**Desktop**
 - Browser Chrome
 - Version 81.0.4044.122 64 bits
- Ubuntu OS 18.04.4 LTS
- Angular Application using 9th version of the framework

**Comment by rachel-fenichel** [comment]
Hi Jose Luiz,

This isn't a bug, it's just the wrong function to call. It's an internal function that is part of block removal, but you should use `block.dispose()` to actually get rid of the block.
