### ISSUE TITLE
Simple and fancy playgrounds

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3882]
Split the playground into two:
-  a basic playground (still at tests/playground.html) that doesn't have any dependencies and uses uncompressed blockly.
- a fancy playground (name undetermined) that has all of the bells and whistles for development

After that, split out components that can be standalone dev tools.  For each one:
- move it to the dev tools plugin (in blockly-samples)
- add it to package.json as a dev dependency
- use it as a node module in the fancy playground

Some good candidate components:

- [x] screenshot downloading (https://github.com/google/blockly-samples/issues/245)
- [x] test blocks (https://github.com/google/blockly-samples/issues/210)
- [x] test block toolbox (https://github.com/google/blockly-samples/issues/210)
- [x] most dropdowns that control options
  - e.g. renderer, toolbox position
  - use the dat.gui configuration system
- [x] block rendering debug

**Comment by rachel-fenichel** [comment]
Do we want to still load the renderer, rtl, etc from the url?
  - My inclination is no, leave it to the gui controls instead of mixing the two.

**Comment by rachel-fenichel** [comment]
Another candidate component: the textarea with its attendant to/from XML buttons.

**Comment by rachel-fenichel** [comment]
Another candidate for dev tools:
- [ ] populateRandom, with a boolean controlling whether it's from the toolbox contents or from all defined blocks.

**Comment by samelhusseini** [comment]
- [ ] Rendering constants
- [ ] Event logging
- [ ] Custom Theme (color / font editing)

**Comment by rachel-fenichel** [comment]
@samelhusseini how are we doing on this?

**Comment by samelhusseini** [comment]
The only remaining item here is:
- [ ] Cleanup: remove test toolbox json definition when the toolbox definition is finalized.

**Comment by alschmiedt** [comment]
Closing since test blocks were removed in #4250.
