### ISSUE TITLE
Comment nodes throw error in Blockly.Xml.domToBlockHeadless_

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#3886]
**Describe the bug**

A comment node within a block node causes an error to be thrown in ``Blockly.Xml.domToBlockHeadless_``. 

**To Reproduce**

1. Go to the Blockly playground.
2. Insert the following in the text box: 
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="controls_repeat_ext" x="113" y="88">
    <!-- Comment node -->
    <value name="TIMES">
      <shadow type="math_number">
        <field name="NUM">10</field>
      </shadow>
    </value>
  </block>
</xml>
```
3. Click 'import'
**Expected behavior**

No error in console, comments should just be ignored.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Uncaught TypeError: xmlChild.getAttribute is not a function
    at Object.Blockly.Xml.domToBlockHeadless_ (xml.js:664)
    at Object.Blockly.Xml.domToBlock (xml.js:551)
    at Object.Blockly.Xml.domToWorkspace (xml.js:427)
    at fromXml (playground.html:424)
    at HTMLInputElement.onclick (playground.html:664)
```

**Additional context**

**Comment by rachel-fenichel** [comment]
Closing because this is just a restriction on what your XML can look like, and it's not the only restriction.

`mapSupportedXmlTags` in `xml.ts` does some validation and may handle this case gracefully, but still by throwing an error.
