### ISSUE TITLE
Add Blockly.Theme.register

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#3887]
**Is your feature request related to a problem? Please describe.**

https://github.com/google/blockly-samples/issues/263
I would like to be able to iterate across all defined/registered themes and refer to them by name.

**Describe the solution you'd like**

Add `Blockly.Theme.register`, to parallel the registration process for a renderer.
Add parsing a string as a theme name for injection options.

**Describe alternatives you've considered**

Currently everything is added explicitly on the Blockly.Themes object (e.g. Blockly.Themes.Dark).  We could continue with that.

**Comment by rachel-fenichel** [comment]
@alschmiedt fyi

**Comment by samelhusseini** [comment]
Fixed by https://github.com/google/blockly/pull/3932
