### ISSUE TITLE
Data retention enhancements needed for 3 blockly demos (code, cloud storage and block)

### ISSUE THREAD

**Issue by mmathrani** [google/blockly#3899]
**Is your feature request related to a problem? Please describe.**
Today three demo's (code, cloud storage and block) provide an option to store user created samples. These samples are stored in appengine datastore. They are not tied to any user and the link to the sampleas can be shared between users. We have no defined data retention policy around this and we need to build that to adhere to company privacy guidelines.

**Describe the solution you'd like**
1. Add a timestamp to the appengine data store that stores this data in XML format. This will help us delete the records after a specific time interval (currently planned for 1 year).
2. Create a cron job that will run once a week and clear records > time interval
3. Update the message on 'Save' to be 'Share your blocks with the below public link. We\'ll store them for a year. Please be sure not to include any private information.' from 'Share your blocks with the below public link.'
4. Backfill all existing records with today (the day we release) timestamp.
5. Provide a note in FAQ or help section to allow deletion of any saved sample before the data retention cron job deletes it. This will send an email to the core Google group who can do the needful.

**Comment by NeilFraser** [comment]
They tried to get us to do expiry in Blockly Games too.  I considered this utterly unacceptable (there are lesson plans, [bug demos](https://github.com/google/blockly/issues/216), official [example links](https://blockly-demo.appspot.com/static/demos/code/index.html?lang=tlh#ortpyd), and the entirety of the block factory data).  After a closer look they backed down on the basis that this data was not tied to any individual user.

Push back.  Don't break a decade's worth of material.

**Comment by mmathrani** [comment]
Based on internal discussions within the team, there is a change in direction wrt to the logic of deletion of developer created samples.
Point 1 from the PR description
"Add a timestamp to the appengine data store that stores this data in XML format. This will help us delete the records after a specific time interval (currently planned for 1 year)."
**changed to ** 
"Add a timestamp to the appengine data store that stores the last access time. This will help us delete the records after a specific time interval (currently planned for 1 year). The get/setter for this last_access_time will be updated from the code that loads/saves the three samples"

**Comment by rachel-fenichel** [comment]
Done.
