### ISSUE TITLE
textarea of comment don't scroll properly on chrome

### ISSUE THREAD

**Issue by carloslfu** [google/blockly#39]
when write a large comment and try to scroll with arrow keys, the scroll don't work properly and cause a little displacement of the field. This works well on firefox.

![bug-report2](https://cloud.githubusercontent.com/assets/5993168/5588151/6527cec2-90cf-11e4-9e73-3d19fe5af8dd.jpg)

**Comment by NeilFraser** [comment]
Thanks.  Definitely a Chromium bug.  I've reported it here:
https://code.google.com/p/chromium/issues/detail?id=448200

**Comment by NeilFraser** [comment]
No idea why viewing Chromium bug 448200 has been restricted to Google employees only.  I think that's just a mistake, not an indication that its a security bug.

**Comment by NeilFraser** [comment]
Claims to have been fixed:
https://bugs.chromium.org/p/chromium/issues/detail?id=568614

However, testing now reveals a worse bug where the whole comment text area vanishes instead of providing a scrollbar.

**Comment by AnmAtAnm** [comment]
Tested today.  No scrollbar seen on either Mac Chrome or Mac Firefox.

**Comment by carloslfu** [comment]
It seems to be fixed https://bugs.chromium.org/p/chromium/issues/detail?id=568614

**Comment by RoboErikG** [comment]
Scrolling by moving the cursor seems to be working correctly now, but there are no longer scrollbars so leaving this open.

**Comment by moniika** [comment]
Created a new bug to track scrollbar issue.
