### ISSUE TITLE
Hook to add items in main context menu

### ISSUE THREAD

**Issue by pelikhan** [google/blockly#391]
Simularly to the context menu of custom blocks, it would be great to be able to manipulate the `menuOptions` array before it is being sent into `show`. Or maybe I just missed how to do that!

Our particular scenario is adding another context item.

https://github.com/google/blockly/blob/abe2533d7eedbd8546d53f3f193128489a785942/core/workspace_svg.js#L852

**Comment by towerpark** [comment]
It seems customizing menu options is not support yet. Currently I have it done
by hooking Blockly.ContextMenu.show and adding my options before calling the
real show function, but an official API would be appreciated :)

Thanks for the great work.

**Comment by rachel-fenichel** [comment]
Done!  In #1710.  It'll go out in the April release.  Still needs documentation.
