### ISSUE TITLE
How to use Blockly with VUE

### ISSUE THREAD

**Issue by wkandjw** [google/blockly#3917]
**Is your feature request related to a problem? Please describe.**

Recently, I am writing a desktop application with blockly + Vue + electron，but blockly NPM cannot be installed. The script tag is used to import the compressed file, but errors are always reported in the project. I searched a lot of data and found no corresponding solution. I hope to have a demo as a reference.

'goog' is not defined
'Blockly' is not defined

**Describe the solution you'd like**

I hope there is a demo to show how to use blocky correctly through NPM or script tag in Vue project

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/33707870/82887263-58a11680-9f7a-11ea-91c8-3975c092dc72.png)

**Comment by rachel-fenichel** [comment]
We have a sample: https://github.com/google/blockly-samples/tree/master/examples/blockly-vue

**Comment by wkandjw** [comment]
> We have a sample: https://github.com/google/blockly-samples/tree/master/examples/blockly-vue

yes, thank you very much

**Comment by diablokevin** [comment]
Is there a example on VUE3?

**Comment by BeksOmega** [comment]
> Is there an example on VUE3?

There is not :/ but you could give the Vue2 example a try. If you run into any problems using it in Vue3 we can look into upgrading the sample, or creating an additional one =)

**Comment by diablokevin** [comment]
I had try the Vue2 example on Vue3 project，and there are some problems. I couldn't find out the solution. It would be very grateful if you could give an example of Vue3!

**Comment by BeksOmega** [comment]
> I had try the Vue2 example on Vue3 project，and there are some problems. I couldn't find out the solution. It would be very grateful if you could give an example of Vue3!

Thank you for the info, I created a [new feature request](https://github.com/google/blockly-samples/issues/1130) to track creating an upgraded example =) If you have any more details to add (such as what issue you ran into) we would really appreciate you adding a comment on that feature request!

Best wishes, -- Beka
