### ISSUE TITLE
"TextArea" that can input multiple lines

### ISSUE THREAD

**Issue by Taikono-Himazin** [google/blockly#3939]
I intend to take a closer look at the internet. However, I couldn't find a way to create a block that allows for multiple lines of text input including line breaks.
This probably requires defining a new field. However, I could not define a new field with my own strength. I'm getting the error "This is not a constructor".

Are you planning to create a TextArea that can input multiple lines? Or let me know if you have code that can implement such functionality.

If you have any misunderstanding, feel free to point me out.
Thank you.

**Comment by BeksOmega** [comment]
There actually is one! It just never got documented. Afaik it also hasn't been unit tested, but if I remember right the code looked pretty solid. [Here](https://github.com/google/blockly/blob/master/core/field_multilineinput.js) is the source code.

Just use `.appendField(new Blockly.FieldMultilineInput());` and it should work :D
