### ISSUE TITLE
Error while using workspace.removeBlockById()

### ISSUE THREAD

**Issue by NavpreetDevpuri** [google/blockly#3940]
i have a custom block with type `a`
```javascript 
Blockly.Blocks['a'] = {
        init: function() {
            this.appendValueInput("a1")
                .setCheck(null)
                .appendField(new Blockly.FieldDropdown([["aaa","0"], ["b","1"], ["c","2"]]), "a2");
            this.setColour(130);
            this.setTooltip("");
            this.setHelpUrl("");
        }
    };
    Blockly.JavaScript['a'] = function(block) {
        var dropdown_a2 = block.getFieldValue('a2');
        var value_a1 = Blockly.JavaScript.valueToCode(block, 'a1', Blockly.JavaScript.ORDER_ATOMIC);
        // TODO: Assemble JavaScript into code variable.
        var code = '...;\n';
        return code;
    };
```
i run `workspace.removeBlockById(workspace.getBlocksByType("a")[0].id)` in console and it show following error as shown in following gif 
![1tks3hbAD8](https://user-images.githubusercontent.com/30471072/83965004-37bbb800-a8ce-11ea-9a02-63d254079d7f.gif)

It should delete block

**Comment by BeksOmega** [comment]
Hi! When filing an issue please fill out all of the pre-made sections. That helps people figure out what could be going on =)

Lucky for you someone else had the same problem a few weeks ago =) You want to use `block.dispose()` ([docs](https://developers.google.com/blockly/reference/js/Blockly.Block#dispose)) not `.removeBlockById`. As you can see [that function is package](https://developers.google.com/blockly/reference/js/Blockly.Workspace#removeBlockById).

I hope that helps! If you have any further problems (specifically related to disposing) I think it might be best to redirect your questions to the forums. Thank you :D

**Comment by NavpreetDevpuri** [comment]
thanks for replying 
I want to achive something like "delete a block but don't want this deleted block goes into recyclebin"
thats why is used `.removeBlockById` 

mainly my main motive was to achive something like "update dropdown list of a block programmically" 
i was able to do that by simply reinitialize block by `Blockly.Blocks['a']` but this creates a problem that the blocks that are inside workspace those blocks just don't update in any way but those blocks that are inside toolbox are updated then i tried to delete those unchanged blocks and try to add new ones it works but then these deleted blocks just appears inside recyclebin.


now i just 
1) export xml of blocks 
2) clear the workspace 
3) reimport blocks from xml 
it works fine it update blocks.

Thats what i want to achive 
![HSgjRh9DEn](https://user-images.githubusercontent.com/30471072/83977682-0e2b7c80-a920-11ea-84f1-0e6166e440d4.gif)

i think blockly should provide this method in documentation that "How can we modify blocks programmically at any time ?" because i was searching for a method to do that and i don't found any usefull information and this is a important question.

OR may be include some function to class workspace something like `workspace.refresh()` that refresh both toolbox and workspace area something similar to `workspace.refreshToolboxSelection()`  that refresh only toolbox
![YroRl89Pja](https://user-images.githubusercontent.com/30471072/83978042-5fd50680-a922-11ea-9e35-7d53052a607b.gif)

**Comment by NavpreetDevpuri** [comment]
@BeksOmega i want to know that what is the name of workspace area where we put blocks ? likewise there is a name for right menu "toolbox".

**Comment by samelhusseini** [comment]
The trashcan uses Blockly events to determine when to add blocks to its list of blocks.
You can disable events and then call `block.dispose()`, ie: 
```
Blockly.Events.disable();
block.dispose();
Blockly.Events.enable();
``` 

Blockly does support dynamic dropdowns, see: 
https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/dropdown#dynamic_dropdowns

If you're unsure whether what you've stumbled upon is a bug or if you need advice / have questions about what you're trying to achieve, the Blockly [forum](https://groups.google.com/forum/#!forum/blockly) is a better place to ask questions.
