### ISSUE TITLE
Close Mutator on Workspace Click

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3947]
**Is your feature request related to a problem? Please describe.**
Developers want to be able to close the mutator editor when a user clicks on the workspace. Previously people were trying to use the select and deselect events. For example: #3865

**Describe the solution you'd like**
I think a hook in `onMouseDown_` for the workspace would solve the problem.

**Describe alternatives you've considered**
Making onMouseDown_ public so that it can be overridden. We could also do this, but it seems like people have already been overriding this and so the name change from onMouseDown_ -> onMouseDown would break them. 

**Additional context**

**Comment by BeksOmega** [comment]
>  it seems like people have already been overriding this and so the name change from onMouseDown_ -> onMouseDown would break them.

Yes! There is at least one case in AppInventor ([link](https://github.com/mit-cml/appinventor-sources/blob/8375942b037d89e924f925bfd530ff3caa42755b/appinventor/blocklyeditor/src/workspace_svg.js#L75))

**Comment by mattbishop** [comment]
Testing this on the #develop branch.

I'm not clear from the issue title that this has been fixed. I would expect that clicks on the workspace outside the mutator bubble will close the mutator. (Also expect the same for comment bubbles).

Is there an API I should use to turn this behavior on?

**Comment by alschmiedt** [comment]
I updated the title to hopefully make this more clear. We are not providing this functionality in core, but have instead created an event that is fired on workspace click so a developer can add this feature by listening for the `workspaceClick` event.
