### ISSUE TITLE
Consider adopting Closure Rules

### ISSUE THREAD

**Issue by jart** [google/blockly#395]
Greetings. I noticed you're doing Google-style JavaScript development with the Closure Tools.

In that case, you may be interested in [Closure Rules for Bazel](https://github.com/bazelbuild/rules_closure). It's the polished open source equivalent to Google's internal JavaScript build rules. Please consider adopting it. Let me know if there's anything I can do to help.

**Comment by MarkusBordihn** [comment]
Only to adding some historical content to this.

In #288 we discussed to using https://github.com/google/closure-builder as alternative build system which could be easily installed over npm for the different platforms like win, mac, linux.

I think that Bazel is a great tool, but its more for the advanced users.
But it is the Blockly team decission what they think will work for their current user group.

@NeilFraser 
Please let us know if you prefer more Bazel or Closure Builder as build system for this project. Thanks,

**Comment by jart** [comment]
Closure Builder provides a pretty cool veneer for the Closure Tools that's much easier to configure than with shell scripts. Markus put a lot of work into it. I'm sure he'd be able to offer first class support. So his offer is worth your consideration.

If you choose to give Closure Rules a try, then I will make you two promises:

1. No more GenJSDeps
2. No more dual stack build system

With Closure Rules, you can have the exact same build system internally as externally. You can just MOE your BUILD files onto GitHub. There is already a production service doing this. Ping me on chat and I'll show you more. It's a beautiful thing.

Closure Rules isn't anything new. Basically what we've been doing is making all the JS tooling internally, available externally. It's part of the whole Alphabetization process. Except we're going back to first principles to get rid of some of the warts, e.g. GenJSDeps.

Markus correctly points out that Bazel Closure Rules is for advanced users. However blockly *is* an advanced user. This project uses JS types and Closure Library. You guys are basically coding JavaScript on the hardest difficulty setting. Closure Rules offers a tooling that caters to this highly professional development process.

However I believe that the most advanced professional tools, should be accessible to *everyone*. That's why we've gone to painstaking lengths to make Bazel / Closure Rules very accessible, to even the most casual developers.

So I think your external contributors will be grateful that they'll be able to hack on your project with the same tools a Googler would use internally, without any of the pain and frustration to which Googlers have grown accustomed. Wouldn't you say that's a beautiful thing?

**Comment by samelhusseini** [comment]
Closing as we've landed on using the closure compiler's npm package.
