### ISSUE TITLE
maxLines config for Multiline text input fields

### ISSUE THREAD

**Issue by mattbishop** [google/blockly#3969]
**Is your feature request related to a problem? Please describe.**

The Multiline Input field is a great way to collect larger amounts of text, such as descriptions. The width of the field has a smart ellipsis cutoff capability to allow long lines to keep the width of the field reasonable.

Unfortunately no such feature seems to exist for tall input fields. If a user types many lines, even pastes in a page or two of text from another source, the text field becomes too tall to be useful.

**Describe the solution you'd like**

A Multiline field with scrollbars, basically. With a configurable height setting so I can keep it to 3 lines, for instance.

**Describe alternatives you've considered**

None yet.

**Comment by LarryKlugerDS** [comment]
Vertical scrollbars after the multiline text field has reached a set height would be a great feature.
