### ISSUE TITLE
Orientation change event bound in inject.js doesn't work for multiple blockly workspaces on one page.

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#397]
The resize function uses getMainWorkspace which will only resize the most recently touched workspace.
See https://github.com/google/blockly/blob/master/core/inject.js#L325

**Comment by rachel-fenichel** [comment]
The culprit code is in `inject.ts`:
```
    // Some iPad versions don't fire resize after portrait to landscape change.
    if (userAgent.IPAD) {
      browserEvents.conditionalBind(
          window, 'orientationchange', document, function() {
            // TODO (#397): Fix for multiple Blockly workspaces.
            common.svgResize(common.getMainWorkspace() as WorkspaceSvg);
          });
    }
```

We should check whether this is still necessary for iPads. For other devices this code path isn't hit, and the resize handler in `inject.ts` is bound separately on each workspace.
