### ISSUE TITLE
Flyout Fires Workspace Click Event (parent workspace id)

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3976]
**Describe the bug**

Very similar to #3975. I'm not sure what the desired behavior is here.

When you click on the background of an open flyout it fires a workspace click event. The workspaceId in the event is not the id of the flyout itself, but the id of the parent workspace.

**To Reproduce**

1. Turn on event logging.
2. Open the flyout.
3. Click the background of the flyout.
4. Observe the fired click event.

**Expected behavior**

Again I'm just not sure how it should work in this situation. I think my instinct is that it would fire, but it would use the flyout's id and not the id of the parent. But I'm not sure that that's the most useful way to structure it.

**Comment by alschmiedt** [comment]
Similar comment as in #3975. This will get taken care of when we look at emitting click events in more detail next release.

**Comment by moniika** [comment]
I'm fairly certain that the cause of this is because we bind `getGesture` on the flyout workspace to the main workspace in flyout_base.js.

```
// A flyout connected to a workspace doesn't have its own current gesture.
  this.workspace_.getGesture =
      this.targetWorkspace_.getGesture.bind(this.targetWorkspace_);
```
