### ISSUE TITLE
Multiline Field Not Rendered Correctly in Flyout

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#3977]
**Describe the bug**

The multinline field is not sized correctly when in the flyout.
![MultilineInFlyout](https://user-images.githubusercontent.com/25440652/84944560-cc76a080-b09a-11ea-8896-8b267d506dbd.png)

**To Reproduce**

1. Go to the playground.
2. Open the Test Blocks > Fields > Defaults flyout.
3. Observe the issue.

**Expected behavior**

The background rect and block should surround the text.

**Additional context**

It looks like it calls the old getTextWidth() method instead of the new getFastTextWidth() method, so switching that over may help. The issue seems to be that the text hasn't yet been rendered when getTextWidth calls getComputedTextLength? Not sure though.

**Comment by samelhusseini** [comment]
Git bisect yields this as the offending PR: https://github.com/google/blockly/pull/3891

**Comment by alschmiedt** [comment]
Will take a look : )

**Comment by samelhusseini** [comment]
Looks like the  `setVisible` needs to happen before `createFlyoutInfo_`.

**Comment by samelhusseini** [comment]
Fixed.
