### ISSUE TITLE
Multiline literals are getting indented

### ISSUE THREAD

**Issue by seldomU** [google/blockly#3978]
The language generator's multiline_quote_ function can generate multiple lines of source code. Those lines get indented. Those indentation characters are then part of the string literal, which they should not be. All generators except for JavaScript seem to have this problem.

**Comment by rachel-fenichel** [comment]
Javascript fixes this by doing a multiline string like this:
```
var str = 'some stuff' + 
  'some other stuff' +
  'and so on';
```

This means that the additional indentation is all outside of the string.

**Comment by rachel-fenichel** [comment]
The Python implementation looks like this:
```
  string = string.replace(/'''/g, '\\\'\\\'\\\'');
  return '\'\'\'' + string + '\'\'\'';
```

A possible solution is to use Python's `dedent` function: https://docs.python.org/3/library/textwrap.html#textwrap.dedent

That would look something like:
```
  string = string.replace(/'''/g, '\\\'\\\'\\\'');
  return 'textwrap.dedent(' + '\'\'\'' + '\\n' + string + '\'\'\'' + ')';
```

Howeve, this requires an import for `textwrap`.
