### ISSUE TITLE
Is it possible to generate code on the server side?

### ISSUE THREAD

**Issue by Taikono-Himazin** [google/blockly#3981]
Blockly does the process of generating code from blocks in js, is there a way to do that on the server side?

I want to have a certain string in the code generated by a particular block as a security measure. Doing that when you run workspaceToCode will change it to a malicious user This is a risk.
Is there a better way?

https://groups.google.com/forum/#!topic/ blockly/N70CBxwENDg
I found this article, but this was from 2015 and I wasn't sure it was still possible.

**Comment by alschmiedt** [comment]
Hello, 
Yes it is still possible to generate code on the server side. There is a [demo](https://blockly-demo.appspot.com/static/demos/headless/index.html) for this.

In the future if you could post your questions on our [forum](https://groups.google.com/forum/#!forum/blockly) that would be great. Posting them there allows other people to answer the question and benefit from them : ) 
Thanks!

**Comment by rachel-fenichel** [comment]
Yup, this is trivial:
- On the client side, serialize the workspace to XML
- Create a headless workspace on the server side
- Load the XML in the headless workspcae
- Run the generator in the headless workspace
- (If needed) Send the generated code back to the client
