### ISSUE TITLE
Workspace doesn't redraw properly any more after latest updates.

### ISSUE THREAD

**Issue by ajfisher** [google/blockly#399]
I'm using absolute latest from master and am having issues with the redraw of the toolbox, code view and workspace when you switch around.

Notably, per https://github.com/google/blockly/issues/169 I was using the fireUiEvent to trigger an appropriate update and that has now disappeared and thus causing errors.

What is new preferred method of doing this if manually triggering the UI event is no longer supported?

Specifically I am trying to ensure that when the user flips back and forth between the code view and the block workspace that everything is rendered correctly, especially because when using categories in the toolbox you get artefacts when you switch to the code view.

**Comment by picklesrus** [comment]
It sounds like a combination of https://github.com/google/blockly/commit/217c681b86b0f2df76c479c9efae62e6e5abcede and https://github.com/google/blockly/commit/213469a479a92f1a3ce043803ad560a9b2a3f0cf.

I'm guessing you just need to replace fireUiEvent with Blockly.svgResize.

If your project is similar to the blockly code demo (blockly/demos/code/index.html)  you may way to take a closer look at the changes I made to code.js in https://github.com/google/blockly/commit/213469a479a92f1a3ce043803ad560a9b2a3f0cf.  The resizing in that demo (mostly on initial load)  was slightly broken so I fixed it as part of that change too.

Let me know if that helps!

**Comment by carlosperate** [comment]
Since svgResize was changing a couple of times, and there was still some work going on that area, I personally ended up firing a manual window resize event, which I think fireUiEvent was originally doing, that way if the API changes once more you should not need to update your code.

**Comment by ajfisher** [comment]
@Carlos with something like a window.resizeBy(x,y) ?

**Comment by carlosperate** [comment]
With `window.dispatchEvent(new Event('resize'))`.

**Comment by rachel-fenichel** [comment]
@ajfisher is this still an issue for you?

**Comment by gerritbes** [comment]
When i open a modal with angular uib modal the workspace ,prefilled with some hardcoded blocks,  renders fine. When i close the modal and open the modal again the workspace is not rendered ok.only half the block is visible. When i drag the block it renders fine.
I will try the resize event monday

**Comment by picklesrus** [comment]
@gerritbes If that doesn't work you, a screenshot would be helpful.  I'm not sure I understand the problem you're describing, but I think a screenshot would help.

**Comment by gerritbes** [comment]
Here are 2 screenshots. One with rendering ok , and one with rendering wrong.

When a modal is openend for the first time, the rendering is ok.
The next times the rendering is not ok.
When i drag the block , its rendered ok again.
![rendered_ok](https://cloud.githubusercontent.com/assets/8036080/20303987/44622158-ab2e-11e6-8fe1-952fa97d0373.PNG)
![rendered_not_ok](https://cloud.githubusercontent.com/assets/8036080/20303988/4462b938-ab2e-11e6-9639-010341f1ea0a.png)



When openening the modal , Blockly.inject is called. next the block is added to the returned workspace
like this :
 ` let dom= Blockly.Xml.textToDom(xml_block);
        Blockly.Xml.domToWorkspace(dom, workspace);`

**Comment by gerritbes** [comment]
okay its fixed.
The modal that is opened ( uib-modal from angular) has a rendered promise. When blockly is injected + blocks added to workspace after the rendered promise is resolved , it works ok.
