### ISSUE TITLE
Update Configuring A Workspace

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#3990]
**Where**

**What**
https://developers.google.com/blockly/guides/create-custom-blocks/blockly-developer-tools#configuring_a_workspace_for_web_blockly

  
- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

**Suggested content**
Add information at the end of this page on how to convert dom to workspace
`Blockly.Xml.domToWorkspace(Blockly.Xml.textToDom(xml), workspace);`

**Additional context**
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/blockly/Cu2aeBZ7CZ8/kX54MjEJAgAJ

**Comment by rachel-fenichel** [comment]
Done. Will be published at the Q3 release.
