### ISSUE TITLE
Touch input does not work

### ISSUE THREAD

**Issue by carlosperate** [google/blockly#40]
I am unable to drag blocks in the latest version of blockly if using touch input. I have tried this using the several of the demos on: 
* Android: chrome allows to drop blocks from toolbox with a single touch, but there is no dragging, android browser does not do anything with the toolbox
* iOS7 on iPad: same results as Android chrome with safary and iOS chrome
* Windows 8 laptop with touch screen: same behaviour in chrome and opera, IE11 will kind of choppily  react to touch dragging, firefox works fine

**Comment by carlosperate** [comment]
I've submitted a pull request to fix the problem that I was referring to in this issue.
 
However, touch functionality in IE is still very laggy in my current test environment. The closure [TOUCH_ENABLED](https://github.com/google/closure-library/blob/master/closure/goog/events/browserfeature.js#L77) test does return 'true' in IE11 and the [Blockly.bindEvent_.TOUCH_MAP](https://github.com/google/blockly/blob/master/core/utils.js#L119) gets assigned, so the problem lays somewhere else.

I never tested this functionality in IE11 before, so I do not know if it worked correctly in the past. If somebody can replicate this problem, I would suggest to open a new issue, as a merge of the current pull request will close this one.

**Comment by carlosperate** [comment]
Anybody looking into this? Currently Blockly is still broken for touch screens.

**Comment by NeilFraser** [comment]
Thanks for this.  Android/iOS support the current top priorities.

**Comment by pelikhan** [comment]
I've added a comment on #254. Turns out that the fix is rather simple. You have to use pointer events in TOUCH_MAP and prevent the tap-hold action.
