### ISSUE TITLE
FieldDate is not included in the master branch

### ISSUE THREAD

**Issue by fayvaz** [google/blockly#4013]
Hello -

I am looking at the Blockly documentation and it looks like the Date field is included (https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/date?hl=en) and the following is recommended to enable Date field:

__Warning: Due to its limited use and large footprint, FieldDate is not compiled into Blockly by default. To use it you will need to require it and rebuild. Add goog.require('Blockly.FieldDate') to your project, or uncomment it inside blockly.js to enable it. FieldDate also depends on the Closure Library which is no longer compiled into Blockly by default. You will need to add google-closure-library to your package.json and rebuild with the --closure-library flag: gulp build --closure-library.__

However, unfortunately, I could not see any code or reference related to FieldDate in the master branch content in Github. Am I missed something somewhere or is there anything wrong in the documentation.

Many thanks,
-fatih

**Comment by samelhusseini** [comment]
Thanks for filing @fayvaz.

We've moved FieldDate to it's own package and is now published at https://www.npmjs.com/package/@blockly/field-date

Will keep this issue to track updating the documentation to reflect that.

**Comment by moniika** [comment]
Closing this issue in favor of #4094 that more clearly explains how to update documentation.
