### ISSUE TITLE
External images not working on dropdown input

### ISSUE THREAD

**Issue by FabioOliveira1** [google/blockly#4015]
**Describe the bug**

Images from external sources are not being displayed on dropdown options on production environment - neither on my project nor on blockly demos.
Instead of displaying it, a message object HTMLImageElement is shown.

**To Reproduce**

Click here: [demo](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#mw4oh2)

or

1. Go to https://blockly-demo.appspot.com/static/demos/blockfactory/index.html
2. Add a dummy input inside the main block
3. Add a dropdown field inside the dummy input
4. Change the dropdown items to show only one image - instead of 3 text field
5. Click on dropdown options on the preview
6. See the message [object HTMLImageElement] instead of showing the image

**Expected behavior**

It was supposed to show a image on the dropdown options

**Screenshots**

![image](https://user-images.githubusercontent.com/13422600/86609643-93876880-bf82-11ea-9280-5a85ed814419.png)

**Desktop:**
 - OS: Ubuntu 19.04
 - Browser: Chrome
 - Version: 83.0.4103.106 (Official Build) (64-bit)

**Additional context**

It works on local environment

**Comment by samelhusseini** [comment]
A git bisect leads to this PR: https://github.com/google/blockly/pull/3880

**Comment by samelhusseini** [comment]
Fixed and released patch 3.20200625.2
