### ISSUE TITLE
Tech Debt: Add nullability modifier for reference types

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#4039]
The [Google Style Guide](https://google.github.io/styleguide/jsguide.html#jsdoc-nullability) suggests to always use an explicit `?` and `!` modifiers for reference types that refer to classes, enums, records, and typdefs (basically anything that is upper case).

We don't currently do that, and as a team have decided that although in some cases we're okay to diverge from the Google Style Guide (especially in cases where the guide has changed over time), in this case, we see more value in switching to match the guide.

A regex `(^(?!.*(@this|@extends|@implements|@throws))[^\{]*)\{([A-Z]+[^=]*)\}` to find all the current annotations that don't have an explicit modifier leads roughly 550 results.

As we work through this tech debt, we've decided that it would be beneficial to have any **new code** meet this requirement.

**Comment by gonfunko** [comment]
Closing since the TS migration has obsoleted/addressed this.
