### ISSUE TITLE
If a workspace scroll ends over a field, the editor opens

### ISSUE THREAD

**Issue by drigz** [google/blockly#404]
![scroll onto field](https://cloud.githubusercontent.com/assets/632207/15853989/d5d8f040-2ca7-11e6-9ff9-bae4a44b6ad3.gif)

In this example, the upwards scroll starts below the block and ends over the field. The mouseup event is sent to the field and opens the editor.

**Comment by drigz** [comment]
We could fix this by adding a method, WorkspaceSvg.isDragging, which replaces the [dragMode_ check in field.js](https://github.com/google/blockly/blob/6ec7d31629f0a712cf208e0d2851077effce0eb6/core/field.js#L432) and checks if the workspace or flyout is scrolling as well as checking dragMode_. Any thoughts?

**Comment by RoboErikG** [comment]
Another option is to make mouse down cache what the click started on and only open the flyout if mouse down and mouseup were on the same element.
