### ISSUE TITLE
Deprecation warning util

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#4049]
When we deprecate functions we usually add a console.warn about it, often with an explanation of what to do instead.

I propose standardizing onto a function that prints
- the name of the deprecated function
- when it was deprecated
- when it will be deleted
- (optionally) which function to call instead

Detailed explanations of how to replace the call can go in comments instead of in the log.

Motivation:
- standardize messaging
- always have a planned deletion date in deprecation messages

**Comment by rachel-fenichel** [comment]
Followup work: go through all deprecation warnings in functions and make them use the new helper.

**Comment by halitanildonmez** [comment]
I have been going through the code and as far as I can see all the deprecation for functions have warnings except for the constant variable, for example blocks/loops.js Blockly.Constants.Loops.HUE = 120; 

Question is, is there a plan to add warnings for constants or is there anything else to do here ?

**Comment by alschmiedt** [comment]
There is not currently a plan to add warnings for constants.

I think there is [one case](https://github.com/google/blockly/blob/11987dc6d6aa16138b36237e8959f2a3f91eb4e2/core/field_textinput.js#L534) in field_textinput.js that needs to be updated to use `Blockly.utils.deprecation.warn` but other than that I think this is finished.

Thanks for commenting!

**Comment by halitanildonmez** [comment]
No worries 😄 

I can fix that one if you wish ?

**Comment by alschmiedt** [comment]
If you would like to that would be great :)

**Comment by halitanildonmez** [comment]
Done!

**Comment by alschmiedt** [comment]
This looks to be finished.
