### ISSUE TITLE
Flyout field clicks are handled inconsistently

### ISSUE THREAD

**Issue by drigz** [google/blockly#405]
![flyout field clicks](https://cloud.githubusercontent.com/assets/632207/15854173/b851101a-2ca8-11e6-880c-038c7078926c.gif)

If you click a field that is part of a shadow block, you can edit it within the flyout. If you click a normal field, it creates the block immediately in the workspace.

What is the intended behaviour in these cases?

**Comment by drigz** [comment]
My first approach was to allow editing in all fields consistently. This UX was intentionally chosen by the Scratch team, as I understand.

However, this creates some slightly weird behaviour with variables - you can rename/add variables to no effect:

![renaming in flyout](https://cloud.githubusercontent.com/assets/632207/15854645/420bf6a6-2cab-11e6-89c5-bffaae5a0515.gif)

Additionally, any edits to fields are lost when you close and reopen the flyout, although that seems OK to me. Any thoughts on this? Options:

- Leave as is, forgetting changes when the flyout closes.
- Cache flyout blocks (or just the variables?) to remember changes.
- Do nothing when the user clicks on fields (or just the vairables?) to remove the corner case.

**Comment by RoboErikG** [comment]
I think the intent was to always drop it in the workspace and close the flyout if it's a closeable flyout, and if you clicked on a field also start editing the field.

When the flyout can't be closed then it should edit it in the flyout.
