### ISSUE TITLE
Flyout doesn't resize when blocks change size

### ISSUE THREAD

**Issue by drigz** [google/blockly#406]
If you edit the text in a shadow block to increase the size of the block, the flyout no longer resizes to fit the block. This was introduced by #386.

![flyout resizing](https://cloud.githubusercontent.com/assets/632207/15854900/b1672c7c-2cac-11e6-8d2d-3b3fc4232db8.gif)
*before #386* 

![flyout not resizing](https://cloud.githubusercontent.com/assets/632207/15854901/b324d6cc-2cac-11e6-8999-62bc4f52a58f.gif)
*after #386*

@picklesrus, any idea how to approach this?

**Comment by picklesrus** [comment]
@drigz Thanks for finding this!  It looks like maybe it can be fixed in Blockly.FieldTextInput.prototype.resizeEditor_  I'm going to take a closer look now.

**Comment by drigz** [comment]
Fixed by #408.
