### ISSUE TITLE
Blockly.JavaScript.variableDB_ is undefined

### ISSUE THREAD

**Issue by easrng** [google/blockly#4060]
**Describe the bug**

`Blockly.JavaScript.variableDB_` is undefined. This makes it impossible to use variables. It affects the code generation for get variable blocks and variable inputs.

**To Reproduce**

1. Go to 'https://painted-erratic-pluto.glitch.me/'
2. Open JS console
3. See error

**Expected behavior**

The code is logged to the console.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium 81
 - Version: `blockly@3.20200625.2`

**Stack Traces**

The variable codegen stack trace is:
```
Uncaught TypeError: Cannot read property 'getName' of undefined
    at Blockly.BlockSvg.Blockly.JavaScript.variables_get (variables.js:20)
    at Blockly.Generator.blockToCode (generator.js:189)
    at Blockly.Generator.valueToCode (generator.js:229)
    at Blockly.BlockSvg.Blockly.JavaScript.text_print (text.js:296)
    at Blockly.Generator.blockToCode (generator.js:189)
    at (index):54
```

**Additional context**

I am using blockly from the JSDelivr CDN.

**Comment by moniika** [comment]
I believe what is happening here is that the generator is not initialized when you call `blockToCode`. Unlike `workspaceToCode`,` blockToCode` does not initialize the generator (and also the variable database).
You could fix this either by initializing the generator with:
`Blockly.JavaScript.init(workspace)`
or
using `workspaceToCode` instead (which will initialize the generator if it hasn't been already).
There is also currently a bug open regarding this error being non-descriptive #2153

**Comment by easrng** [comment]
Thanks!

**Comment by Chappie74** [comment]
I too was also experiencing this issue when trying to convert blocks of type `procedures_defreturn` to code. At first I got the issue mentioned above, so I tried using Blockly.JavaScript.init(workspace). This fixes the first issue, but now, all I get is an empty string generated.  Everything works perfectly if I use `workspcaeToCode` but I cannot use this for my use case, since i only want the code for a specific block, `procedures_defreturn`. Any help would be appreciated.

**Comment by Chappie74** [comment]
Okay so i'm using `getBlocksByType` to find all of the `procedures_defreturn` block types which is an Array. As a workaround the above issue what i did was to copy the `workspaceToCode` function code on the repo and made my own function, changing the array it iterates over from `workspace.getTopBlocks(true)` to the  array returned by `getBlocksByType`
