### ISSUE TITLE
Horizontal flyout needs to reflow when block text fields are changed.

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#407]
See screenshot where loop block starts to sit on top of the and block.  (Oddly, the screenshot flipped the z order of what chrome actually shows... In the browser,  the loop block appears on top of the and block not below it).

![ss-overlap](https://cloud.githubusercontent.com/assets/15675877/15872910/c20ef934-2cb0-11e6-8f53-e0d8c7204f94.png)

**Comment by drigz** [comment]
reflowHorizontal does get called, but [because the height hasn't changed](https://github.com/google/blockly/blob/105f0da3d2fccec9dc035617a7bcaf405039e4ac/core/flyout.js#L1019) it doesn't do anything.

**Comment by samelhusseini** [comment]
@moniika to verify this has been fixed.

**Comment by moniika** [comment]
closing because can not repro
