### ISSUE TITLE
This section of JS code how to automatically generate process graphics block

### ISSUE THREAD

**Issue by tianyazjq** [google/blockly#4071]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

How to make a simple JS logic code block, automatically reverse self graphics code, without manual drag combination graphics. For example, I write a JS code,

if(test < 100){

Alert ('less than 100 ')

}else{

Alert ('greater than 100 ')

}

This section of JS code how to automatically generate process graphics block, no need to manually drag to create.

**Describe alternatives you've considered**

**Additional context**

**Comment by tianyazjq** [comment]
比如右边有一个js编辑器，编写简单的js，左侧区域自动生成图形逻辑代码块

**Comment by tianyazjq** [comment]
For example, there is a JS editor on the right to write simple JS, and the left area automatically generates graphic logic code blocks

**Comment by alschmiedt** [comment]
Hello! 

We do not offer support for translating text into block. Some other projects such as [Microsoft Makecode](https://www.microsoft.com/en-us/makecode?rtc=1) have worked on this, but it is not something that blockly supports. 

In the future, if you have any questions please add them to our [forum](https://groups.google.com/g/blockly). We try to keep most questions there so developers have a central place to ask and answer questions : ) Thanks!
