### ISSUE TITLE
How can we create a treeview toolbox in blockly as in image any sample code or need guide to the docs

### ISSUE THREAD

**Issue by suryadevelope** [google/blockly#4072]
![IMG_20200727_123239](https://user-images.githubusercontent.com/59243908/88513363-c4990d00-d005-11ea-9ab3-8d69df6a8f98.jpg)

**Comment by ewpatton** [comment]
@suryadevelope That looks like App Inventor, and in App Inventor we use the Tree object from Google Web Toolkit (GWT). Selecting an item in the tree opens the flyout with the corresponding blocks for the category/object. AFAIK, there is no functionality to do this in Blockly and you will need to use another UI library to provide the Tree element.

**Comment by alschmiedt** [comment]
Hello! 
We do offer the ability to create a tree like structure in the blockly toolbox although it doesn't look exactly the same as the app inventor toolbox. Here is an example of a [toolbox](https://blockly-demo.appspot.com/static/tests/playground.html?dir=ltr&toolbox=test-blocks) that has nested categories, and the [guides](https://developers.google.com/blockly/guides/configure/web/toolbox#tree_of_categories) that show how to implement it. 

If you have any more questions in the future it would be great if you could use our [forum](https://groups.google.com/g/blockly). Thanks!
