### ISSUE TITLE
Gamepad-based programming

### ISSUE THREAD

**Issue by eanders-MS** [google/blockly#4073]
Hello! I work on MakeCode Arcade, and I have an opportunity to experiment with adding gamepad support to the Blockly editor. What I'd like to do is take gamepad events and synthesize Blockly input events from them. Things like "pick up block", "move selected block by (x, y)", "insert block". I'm not very familiar with Blockly's architecture yet. Is there an input event system I could hook into?

I'll be starting on this experiment tomorrow. Just hoping for some high-level pointers.

I realize this might not be the best place to ask such questions. Please feel free to close immediately. Thanks!

**Comment by alschmiedt** [comment]
Hello! 

I think what you are looking for is our [event documentation](https://developers.google.com/blockly/guides/configure/web/events). On the [playground](https://blockly-demo.appspot.com/static/tests/playground.html) you can check the "Log Events" button on the left and all events that get fired for the main workspace will show up in the console. 

In the future if you could use our [forum](https://groups.google.com/g/blockly) to ask questions that would be great : ) Thanks!

**Comment by eanders-MS** [comment]
Perfect thank you.
