### ISSUE TITLE
Update type checks page to describe the connection checker

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#4076]
**Where**
https://developers.google.com/blockly/guides/create-custom-blocks/type-checks

**What**
  
- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

Currently there's a description of Blockly's default type system.

**Suggested content**

Add a section on the ConnectionChecker API and how it relates to the default system, plus how it can be overridden.

**Comment by creatorpiyush** [comment]
Hi, can I work on this issue?

**Comment by alschmiedt** [comment]
This is a documentation issue and is something that we update internally. If you have an opinion on how the documentation should be updated, feel free to comment here. Thanks!

**Comment by rachel-fenichel** [comment]
I wrote this documentation but have to figure out where to put it. In the meantime, here's the text:


# Connection Checks

A major benefit of using Blockly is that it ensures the generated code is
syntactically correct. Blockly applies three levels of checks: safety, type,
and drag checks.

## Safety checks

Safety checks ensure that the blocks are on the same workspace, that the
connections are on different blocks, and so on. These ensure that Blockly does
not get into a bad state.

Safety checks also block nonsensical combinations, such as connecting two next 
connections.

## Type checks

Developers can label connections with type information. Type checks use this
information to enforce a type system--e.g. by blocking the connection of a
string where a number is expected.

## Drag checks

Drag checks are applied only when connecting blocks by dragging, rather than
programmatically. For example, only connections within a certain radius should
be considered during a drag.

# The Connection Checker

The Connection Checker is the object that enforces these rules. By default, the
checker applies a simple type system, as described in the 
[Type Checks](/blockly/guides/create-custom-blocks/type-checks) page.

## Overriding the Connection Checker

Developers who wish to provide their own logic for type checks or drag checks
can register a substitute connection checker object that implements the
`IConnectionChecker` interface.

In general, developers should not override Blockly's safety checks.

The [strict connection checker plugin](https://github.com/google/blockly-samples/tree/master/plugins/strict-connection-checker)
is a simple example of a custom checker.

**Comment by rachel-fenichel** [comment]
Done: https://developers.google.com/blockly/guides/create-custom-blocks/type-checks#custom_type_checks and https://developers.google.com/blockly/guides/plugins/interfaces/connection_checker
