### ISSUE TITLE
Mutator bubble gets misconfigured if sub-block gets wider

### ISSUE THREAD

**Issue by joseluiz98** [google/blockly#4086]
**Describe the bug**
If a flyout block gets wider inside a mutator bubble for any reasons (e.g a wider dropdown option label), the flyout width doesn't resize itself, this causes a mix between the bubble flyout and the bubble workspace, a 'weird' behavior for the user.

**To Reproduce**

Just create a simple mutator on a block, in this block put a FieldDropdown with two options - one with a short label (e.g 'test'), and another one with a much wider option (e.g 'testing this bubble mutator grow ability), and see the magic.

**Expected behavior**

I have two behaviors in mind that, for me, solve this problem:

1- Grow up the bubble as its contents get wider
2- Implement a 'ellipsis' such as CSS have the 'ellipsis-overflow' option, basically, the dropdown option would be abbreviate if it's too long.

**Screenshots**

I made up a quick gif to show this, see:

[click here](https://giphy.com/gifs/XfhtkpWk7hlev1DRAh)
[or click here, to see it bigger](https://giphy.com/gifs/XfhtkpWk7hlev1DRAh/fullscreen)

**Comment by alschmiedt** [comment]
Just some additional context. It looks like the flyout is getting resized, but the position of the block in the workspace and the size of the bubble are not getting updated properly. 

Shows the flyout a bit better: 
![3e2653af-9ff0-414a-96a4-c6733af6a368](https://user-images.githubusercontent.com/23059043/88827105-60e61f80-d17e-11ea-813f-10e48ee8594f.gif)

**Comment by joseluiz98** [comment]
> Just some additional context. It looks like the flyout is getting resized, but the position of the block in the workspace and the size of the bubble are not getting updated properly.
> 
> Shows the flyout a bit better:
> ![3e2653af-9ff0-414a-96a4-c6733af6a368](https://user-images.githubusercontent.com/23059043/88827105-60e61f80-d17e-11ea-813f-10e48ee8594f.gif)

Yep, you're right!
