### ISSUE TITLE
Naming: addChangeListener(..) does more than register CHANGE events

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#409]
Suggested name: addWorkspaceListener(..)

ditto for removeChangeListener(..)

**Comment by AnmAtAnm** [comment]
Alternatively, use different add/remove methods for each event type.  After all, the events received are different, too.

**Comment by NeilFraser** [comment]
There are a lot of things it would be nice to rename with the benefit of hindsight.
* procedures should be functions.
* the Blockly.* utility functions should be renamed to Blockly.utils.*
* Scratch want shadow blocks to be default blocks (or something).
* controls_if should be logic_if.
* The Blockly.Blocks['text'] block forced the category to be named Blockly.Blocks.texts

...and many more.

All of these were good names when they were first written, but subsequent developments made the names less than optimal.  Unfortunately these are all publicly in use and changing them would make life harder for existing developers.  An example of a recent change was flipping the arguments for Blockly.Xml.domToWorkspace, and despite adding support for the old argument order we still hurt several developers who used current documentation to call older versions of Blockly, resulting in fail.

As a result of having lots of users and lots of forks, I don't think we can perform this class of renamings without unacceptable levels of collateral damage.
