### ISSUE TITLE
Field date documentation should say to use the published package

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#4094]
**Where**

https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/date

**What**

- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

Warning: Due to its limited use and large footprint, FieldDate is not compiled into Blockly by default. To use it you will need to require it and rebuild. Add goog.require('Blockly.FieldDate') to your project, or uncomment it inside blockly.js to enable it. FieldDate also depends on the Closure Library which is no longer compiled into Blockly by default. You will need to add google-closure-library to your package.json and rebuild with the --closure-library flag: gulp build --closure-library.

**Suggested content**

Warning: The date field is no longer part of the core Blockly library. We now publish it on npm as a plugin named [@blockly/field-date](https://www.npmjs.com/package/@blockly/field-date).

**Comment by samelhusseini** [comment]
Fixed.
