### ISSUE TITLE
FieldNumber does not respect precision for small precision values

### ISSUE THREAD

**Issue by mfallihee** [google/blockly#4105]
When instantiating a FieldNumber with a very small precision value, they are handled incorrectly.

Repro:
1. Create FieldNumber with precision of a very small number value (e.g. .0000001, 1e-8, etc)

Expected Behavior:
The field respects the precision and rounds values appropriately

Actual Behavior:
The precision value gets converted to exponential notation (e.g. 1e-8) and when trying to parse the number of decimal places in Blockly.FieldNumber.prototype.setPrecisionInternal_ it ends up with decimalPlaces_ = 0. This causes all numbers to be rounded to integer values.

~~This is easily worked around by using a string representation for the precision (e.g. ".0000001")~~ but this used to work in older versions and is a regression. 

Edit: Upon further testing, a string representation is not a workaround and fails for the same reason.

**Comment by mfallihee** [comment]
My suggestion is to switch from using Number.prototype.toString() to do the parsing and instead use Number.prototype.toLocaleString()
```
precision.toLocaleString("en-US", { maximumFractionDigits: 20 });
```
This should always give a consistent result when trying to count decimal places. 

I'm happy to submit a PR for this.

**Comment by moniika** [comment]
Definitely is a bug, thanks for catching it! I can't think of a reason off the top of my head why `toLocaleString` wouldn't be an appropriate fix. We would definitely welcome a PR. I've also added a test case that catches this bug.
