### ISSUE TITLE
Alternatives for browser specific functions like window.prompt, window.alert, window.confirm, ...

### ISSUE THREAD

**Issue by MarkusBordihn** [google/blockly#412]
Alternatives for browser specific functions like window.prompt, window.alert, ... to have more flexibility in Chrome apps, extensions and web based app.

In some instances window.prompt, window.alert, window.confirm are not available or blocked.
We need a way to use alternatives functions like modal windows or the <dialog> element instead.

See #396 for the first step in this direction.

Example implementation:
```
  // Modal window
  var modalPrompt = function(promptText, defaultText, callback, opt_title) {
      dialogInstance.showPrompt(opt_title || 'Blockly', promptText,
        callback, defaultText);
  };

  // Editor
  this.nodeEditor = goog.dom.getElement(this.prefix + 'code');
  this.workspace = this.blockly.inject(this.nodeEditor, {
    path: this.mediaFiles,
    toolbox: this.nodeEditorToolbox,
    trashcan: opt_trashcan,
    modal: {
      prompt: modalPrompt
    },
    zoom: {
      controls: true,
      wheel: true,
      startScale: 1.0,
      maxScale: 3,
      minScale: 0.3,
      scaleSpeed: 1.2
    }
  });
```

Working example at: https://github.com/google/coding-with-chrome

**Comment by AnmAtAnm** [comment]
Fixed in #703.  The browser methods are now wrapped by Blockly equivalents. Override Blockly.alert(..), Blockly.confirm(..), and Blockly.prompt(..) if you want different behavior.  Note the callback semantics are new, since these might not block the JavaScript thread.
