### ISSUE TITLE
Reserve words for code runtime, not generator runtime

### ISSUE THREAD

**Issue by seldomU** [google/blockly#4137]
The JS generator reserves words based on its global object. They should be based on the code's intended runtime environment, which is not always the same. For example, when a node.js process generates code for a website, the reserved words should be based on the browser's *window* object.

How about adding an argument to the generator constructor, so users can indicate whether the code is intended for the browser or node.js? The argument could be a list of tags so that generators can make more distinctions in the future, like for Python 2 vs 3 or JS ES5 vs ES6.

**Comment by NeilFraser** [comment]
For most of Blockly's history we attempted to compile a superset of all the global properties in all browsers.  It was an insane list, that changed weekly, was incomplete, and was utterly unmaintainable.  Browsers play fast and lose with custom properties.

No objection to a developer injecting their own list of reserved properties for their platform, but this is probably not a task that the Blockly team is eager to undertake again.

**Comment by rachel-fenichel** [comment]
@seldomU why would this be a generator argument instead of being does as a replacement generator?

**Comment by seldomU** [comment]
@rachel-fenichel a second generator would solve the problem just as well as a constructor argument. But that would still require changes to the first generator, to lock it into one mode: generate browser code or node.js code.

@NeilFraser  I've seen the old word list and appreciate how difficult maintenance must have been. For 99% of Blockly users the current solution is great. But can the old list be used for the niche case of generating browser JS from a node.js process? Because the list is way better then using the names of node's global object (which is currently done), even if its never maintained again.

For user that _want_ to generate node.js code, there could be a separate generator or a constructor argument to indicate that. Then the generator could check its environment and either derive names from the global object (when in a node process) or fall back to some list (when in a browser).

Maybe I should explain my situation a bit. We have a classic Blockly site with a workspace next to an execution area. Generation and execution both happen in the same window. So far so good. Users can store their projects on our server. In addition, we have a *presentation* page where the window contains only the execution area but not the workspace. This one would ideally only pull a project's generated code from the server and run it. Which would require us run the code generator on the server whenever a project is saved. Currently that page pulls Blockly, the workspace content, the related blockdefs and codegens and generates the code in headless mode before finally executing it. That's not ideal.

**Comment by rachel-fenichel** [comment]
After discussion: this can be done with the existing APIs and we do not intend to change the current generator.

There is no need to make changes to the existing generator to lock it into one mode. The subclass generator can simply do `myGenerator.RESERVED_WORDS_ = ''; myGenerator.addReservedWords(words);`. This works because `RESERVED_WORDS_` is protected.
