### ISSUE TITLE
Shadowed statements can't be replaced if the replacement has no next connector

### ISSUE THREAD

**Issue by markfinn** [google/blockly#414]
As an example, as of the current master you won't get the option to drop this accept block here:

![blockly](https://cloud.githubusercontent.com/assets/1516753/15897474/367b0b56-2d5a-11e6-9c3d-3b5ddc92cb81.png)

You won't get the option to connect the accept block over the continue one because accept is a "terminal" block and has no next connection. You also can't drag the shadowed statement out of the way since it's shadowed, so there's no way to replace a shadowed statement block with another "terminal" one.

The non-shadowed case seems to be on purpose from commit 4ae34599

---

My image above IS showing the option to connect there because I made this change:

    --- a/core/connection.js
    +++ b/core/connection.js
    @@ -373,7 +373,8 @@ Blockly.Connection.prototype.isConnectionAllowed = function(candidate) {
      // Don't let a block with no next connection bump other blocks out of the
       // stack.
       if (this.type == Blockly.PREVIOUS_STATEMENT &&
           candidate.isConnected() &&
    -      !this.sourceBlock_.nextConnection) {
    +      !this.sourceBlock_.nextConnection &&
    +      !candidate.targetBlock().isShadow()) {
         return false;
       }

This seems to solve my problem well, but I don't know enough about the code base to know if that breaks anything else, like when the replaced statements are a chain of shadowed blocks instead of just one.

**Comment by NeilFraser** [comment]
This is behaviour added to match Scratch.  I've raised an issue with Scratch to see if we can come to common ground:
https://github.com/LLK/scratch-blocks/issues/397

Ideally we can just make all blocks behave as normally.  But if we can't change Scratch's behaviour, then I'll add a special case for shadow blocks that overrides the special case for terminal statements that overrides the normal behaviour.
