### ISSUE TITLE
Non-existant block warnings with undo/redo on shadows

### ISSUE THREAD

**Issue by tmickel** [google/blockly#415]
In the current live version of the playground:

To reproduce:

- Create a "repeat X times" block.
- Drag in a math_number block into its shadow.
- Undo to remove the math_number block.
- Redo to replace the math_number block.

Warnings occur on the redo:

> Can't move non-existant block: yNjU|NL_o-+5,N^3qL~w (events.js:698)
> Can't delete non-existant block: yNjU|NL_o-+5,N^3qL~w (events.js:462)

**Comment by NeilFraser** [comment]
That is actually ok, these warnings are not a sign of a problem with events.

However, while that's the behaviour in the live version, the current version in develop is far worse:
Error: asserts.js:86 Uncaught AssertionError: Failure: Shadow block cannot be a top-level block.
This is very wrong and needs fixing urgently.

**Comment by NeilFraser** [comment]
Fixed the error.

The warnings remain.  I'm open to removing the warnings, but I'd rather leave them in for now since undo/redo is still fairly new and knowing about problems in other cases would be helpful.
