### ISSUE TITLE
Custom Elements - isTargetInput fails

### ISSUE THREAD

**Issue by razvangeangu** [google/blockly#4157]
**Describe the bug**

When using customElements (web-components), some events (i.e. 'input' with BACKSPACE) are not propagated because they are not recognised as an input by [Blockly.utils.isTargetInput](https://github.com/google/blockly/blob/93b5be40b6229cf164e83b63fe5a6cc4d44a9b5f/core/utils.js#L47).

**To Reproduce**

1. Add the sample Blockly workspace
2. Add a custom element input that does not have a `type` property
3. Type in something and press BACKSPACE

**Expected behavior**

Be able to delete the value when pressing BACKSPACE

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 84.0.4147.105 (Official Build) (64-bit)

**Additional context**

Developers building custom elements do not have to add a `type` property to an input element if they want to enforce rules around the input. `Type` can also be used for other purposes such as the `kind` of component - in that case the method would fail without extra information.

**Comment by razvangeangu** [comment]
This can be resolved on the app-side if developers overwrite the **Blockly.utils.isTargetInput** method in ways like this:

```ts
const isTargetInput = Blockly.utils.isTargetInput;
Object.defineProperty(Blockly.utils, "isInputTarget", {
  value: (e) => {
    if (e.target.tagName === 'MD-TEXT-INPUT' || e.target.tagName === 'MD-SEARCH-FIELD') {
      return true;
    }

    return isTargetInput;
  },
});
```

**Comment by razvangeangu** [comment]
Another way to do achieve this it would be to introduce a `data-` attribute to custom elements and a check in the original method:

```diff
/**
 * Is this event targeting a text input widget?
 * @param {!Event} e An event.
 * @return {boolean} True if text input.
 */
Blockly.utils.isTargetInput = function(e) {
  return e.target.type == 'textarea' || e.target.type == 'text' ||
         e.target.type == 'number' || e.target.type == 'email' ||
         e.target.type == 'password' || e.target.type == 'search' ||
         e.target.type == 'tel' || e.target.type == 'url' ||
-        e.target.isContentEditable;
+        e.target.isContentEditable || e.target.dataset.isInput;
};
```

```html
<md-text-input data-is-input />
<md-search-field data-is-input />
```

**Comment by alschmiedt** [comment]
@razvangeangu fyi this will go into our next release scheduled for September 25th.
