### ISSUE TITLE
Grammatical mistake in README.md file

### ISSUE THREAD

**Issue by mehrdadrafiee** [google/blockly#42]
There is a grammatical sentence used in README.md file.
Attached document is a snapshot of webpage. It should be `Users can drag blocks together to build programs` or something similar and relative.

![screen shot 2015-01-08 at 2 13 03 am](https://cloud.githubusercontent.com/assets/7308807/5659672/ff009210-96db-11e4-9894-676564851b73.png)

**Comment by NeilFraser** [comment]
Fixed, thanks!
