### ISSUE TITLE
Zooming fails with fixed flyouts.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#423]
Go to playground.html?toolbox=simple
Zoom in or out.
Observe that the flyout does not scale, and that coordinates are wrong when a block is created.

**Comment by picklesrus** [comment]
There's a heavy hammer fix which is to call Blockly.svgResize(this); at the end of workspace_svg's setScale.  I can send you a PR if you want it fixed ASAP.  But it isn't really the "right" thing to do so I'm going to keep digging through the flyout's reflow & position to understand why the scale isn't quite right.

**Comment by picklesrus** [comment]
A little more from our research on the remaining horizontal rtl problem mentioned in #424 

The more minor problem (from a ux perspective) is that when zooming out the blocks are not aligned to the edge of the toolbox. (screenshot below)

The larger problem is that when zooming in, the blocks are shifted too so far to the right that they're off screen (with no scrollbar) despite there being space for them (screenshot below). Zoom reset does not solve the problem.
The other odd thing is that, the multi_playground.html behavior is different from the playground.html behavior. In the multi_playground, all the blocks are always accessible (via a scrollbar), though the scrollbars scroll to the wrong spot when the zoom button is clicked.

![zoomedout](https://cloud.githubusercontent.com/assets/15675877/15981732/b9568660-2f2e-11e6-8d0f-2320c2004f2e.png)
![zoomedin](https://cloud.githubusercontent.com/assets/15675877/15981733/bc4984a8-2f2e-11e6-9690-a1fcbfa697a9.png)
![multiplaygroundzoom](https://cloud.githubusercontent.com/assets/15675877/15981810/cbba4d72-2f2f-11e6-9190-b7c3c2b5c0a4.png)
