### ISSUE TITLE
QUESTION: this.appendAddSubGroup

### ISSUE THREAD

**Issue by Ju99ernaut** [google/blockly#4236]
I came across the code below from the project [here](https://github.com/JC-Orozco/BlocksIDE/blob/master/src/lib/bi_blockly/blocks/bi_blockly.js)

```js
Blockly.Blocks['bi_switch'] = {
  init: function() {
    this.appendValueInput('switch')
        .setCheck(null)
        .appendField('switch');
    this.appendAddSubGroup('', 'items',null,
                           '');
    this.itemCount_ = 1;
    this.updateShape_();
    this.appendStatementInput('default')
        .setCheck(null)
        .appendField('default');
    this.setInputsInline(false);
    this.setHelpUrl('http://www.example.com/');
    this.setColour(120);
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    //    this.setOutput(true, null);
    this.setTooltip('');
  }
};
```

When I run the demo of this project it produces the block which is shown in the image below which has the `+` icon that adds new inputs and a `-` icon which removes an input when clicked, however this is not working in the current version of `blockly` so my question is, has this been deprecated, renamed or something else like an extension or mutation?

![Screenshot (25)](https://user-images.githubusercontent.com/48953676/91643759-69a86a80-ea36-11ea-87d8-b53d8a03f9c3.png)

**Comment by moniika** [comment]
I took a look at the repo and I'm not sure where `appendAddSubGroup` is from, but that project hasn't been updated in a few years and `appendAddSubGroup` doesn't exist in the current version of Blockly.
We have a plugin [block-plus-minus](https://github.com/google/blockly-samples/tree/master/plugins/block-plus-minus) on Blockly-Samples that accomplishes a similar functionality by [registering a custom mutator](https://developers.google.com/blockly/guides/create-custom-blocks/extensions) that you could take a look at. 

In the future please ask questions on our [developer forum](https://groups.google.com/g/blockly).
