### ISSUE TITLE
Custom PHP Function to Blockly Block

### ISSUE THREAD

**Issue by analyserdmz** [google/blockly#4255]
Hello, I have a feature request / question on converting a custom PHP function back to Blockly Block. Let's say we have a function like the following, is it / will be at some point possible to create a block for Blockly which will produce the exact same result as the function?

(Totally random) Example function:
```
function getMyLyckyNumber($name)
{
    $randomNumber = random_int(1, 500);
    return "$name here is your lucky number: $randomNumber\r\n";
}
```

**Comment by alschmiedt** [comment]
We do not support going from code to block in the core library and currently do not have any plans to do so. There is a [forum post](https://groups.google.com/forum/#!searchin/blockly/python$20code$20to$20blocks%7Csort:date/blockly/779RyDheAqg/ed2MkPH3AAAJ) that goes into a bit more information that might be helpful for you.
