### ISSUE TITLE
The undo feature + Blockly.Events.disableOrphans = strange behaviour

### ISSUE THREAD

**Issue by zenboss** [google/blockly#4261]
**Describe the bug**

The undo feature has a strange behaviour if it works with `workspace.addChangeListener(Blockly.Events.disableOrphans);`

**To Reproduce**

![undo-issue](https://user-images.githubusercontent.com/928027/92533635-01078c00-f287-11ea-978d-6369791a50da.gif)

**Comment by alschmiedt** [comment]
I can repro on master. It looks like the disabled change event that is being emitted does not have the same group id as the other events.

**Comment by maribethb** [comment]
This was fixed by #4304. Thanks for reporting!
