### ISSUE TITLE
It looks very strong, but do not know how to use!(CN=看起来很强大,但是不知道如何使用!)

### ISSUE THREAD

**Issue by 2947721120** [google/blockly#427]
##EN
It looks very strong, but do not know how to use!
cdnjs similar to obtain a list of distinction, js suffix plus script, plus link after css
A key copy.
How should generate js script

Thank you very much saw the problem, if not mention, or a bad answer! Please close your question, I am a novice, there are differences in mainland China, the way of thinking, I beg your pardon!

My advice:
1 If there is paste js code is automatically generated similar modules /demos/code/index.html perfect!
2. Alternatively targeted firebase generation tool can do, because it does not know how to use!
##CN
看起来很强大,但是不知道如何使用!
cdnjs类似,获取列表区分,js后缀加 script,css后加link
一键复制.
应该怎样生成js脚本

非常感谢您看了问题,如果提的不对,或者不好回答! 请您关闭问题,我是新手,中国大陆地区,思维方式有差异,请您原谅!

个人建议:
1  如果有粘贴js代码,自动生成类似模块/demos/code/index.html就完美了!
2 .或者有针对firebase生成工具也行,因为实在不知道怎么用!

**Comment by 2947721120** [comment]
##EN
It looks very strong, but do not know how to use!
cdnjs similar to obtain a list of distinction, js suffix plus script, plus link after css
A key copy.
How should generate js script

Thank you very much saw the problem, if not mention, or a bad answer! Please close your question, I am a novice, there are differences in mainland China, the way of thinking, I beg your pardon!

My advice:
1 If there is paste js code is automatically generated similar modules /demos/code/index.html perfect!
2. Alternatively targeted firebase generation tool can do, because it does not know how to use!
##CN
看起来很强大,但是不知道如何使用!
cdnjs类似,获取列表区分,js后缀加 script,css后加link
一键复制.
应该怎样生成js脚本

非常感谢您看了问题,如果提的不对,或者不好回答! 请您关闭问题,我是新手,中国大陆地区,思维方式有差异,请您原谅!

个人建议:
1  如果有粘贴js代码,自动生成类似模块/demos/code/index.html就完美了!
2 .或者有针对firebase生成工具也行,因为实在不知道怎么用!

**Comment by wingcd** [comment]
里面有demo的，不过文档确实好。我现在都直接看代码解决问题了
