### ISSUE TITLE
Restoring state of dynamic fields into workspace [Question]

### ISSUE THREAD

**Issue by ajfisher** [google/blockly#428]
I have a scenario where some of my blocks change based on the state of them. EG user selects a drop down field and then they may get a subsequent input field to provide a value (a good example would be select your "title" and if you select "Other" then you'd be presented with a text field to enter it).

I've got the workspace saving and generally restoring however the specific values for the dynamically added fields are not restoring and I'm hoping someone can point me at the right way to do this.

I've confirmed all the data is being serialised and saved properly in XML on the `workspaceToDom` call including the values of these dynamic fields. I've also confirmed that the saved data is being returned from storage properly and being passed to the `domToWorkspace` function in order to set up the workspace.

Once that executes, the blocks all appear and the the states in things like the drop down menus are correct, however any value that is in a dynamic field is just set to the default. I'm also getting a warning like this at start up:

```
Ignoring non-existent field <<dynamic field>> in block <<custom block>>
```

If I had to guess, I'd say what's happening is the block is being added to the workspace with all the values but because the dynamic field hasn't been added to the block yet then it gets skipped (causing non-existent field warning). 

After that, the `onchange` event fires on my block because it's been added and has had data attached and now it updates to add the new fields in which are added in their default state.

So the questions I have are:

1. Is there a way I can add information to the block definition about how to restore it's state?

2. Is there a way I could call `domToWorkspace` and then call it a subsequent time with the data again?

3. Is there some other way to update the workspace with the dom data after the workspace has been created?

If it's relevant, here's a block definition of a block I'm using: https://github.com/makenai/robotnik/blob/master/static/js/src/blocks/led.js

And the relevant code where it updates based on determination of the state of the dropdown menu to add a different input field in.

https://github.com/makenai/robotnik/blob/master/static/js/src/blocks/led.js#L48-L68

**Comment by ajfisher** [comment]
Apparently Mutators aren't just for changing the layout of a block (that was my reading of the documentation) and can be used for this use case (or at least that's what I gleaned from the mutator docs which aren't that clear). 

Hopefully this is the right approach - regardless I've got what I need working by using the domToMutation and mutationToDom methods on the block and then writing and reading the relevant dynamic fields.

Having just done this across a stack of custom blocks it strikes me that this is a very common pattern that requires a lot of boilerplate code to save and recover state...

**Comment by rachel-fenichel** [comment]
Hi @ajfisher,

Please consider mailing the [blockly google group](https://groups.google.com/forum/#!forum/blockly) with questions like this.  There's a lot of aggregated experience developing with blockly over there.

Sounds like you found as solution, so I'm going to close this issue.

**Comment by abhi3675** [comment]
Hi @ajfisher 

I am also facing the similar issue with my code when integrating blockly with Angular 4 appliation.
Could you please elaborate on how you fixed this issue?
Your help will be deeply appreciated.

**Comment by AnmAtAnm** [comment]
Hi @abhi3675,

Let me reiterate Rachel's advice and email the [blockly google group](https://groups.google.com/forum/#!forum/blockly). The Blockly team uses these issues to track bugs and feature requests, not support requests.  Using the Google Group allows the community to help, rather than making our small team a bottleneck in the support process.

Thanks.
