### ISSUE TITLE
Change in Geras rendering for bottom notch in statement input

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#4282]
The renderer used to split the bottom statement tab so that half of it created whitespace, and half of it was consumed by an overlap.

![unnamed](https://user-images.githubusercontent.com/250480/93285693-80272380-f7a3-11ea-90b7-1a522595f3c7.png)

However, we got a bug report today that the new renderer no longer does any overlap, resulting in twice as much whitespace.

![Screen Shot 2020-09-15 at 19 31 51](https://user-images.githubusercontent.com/250480/93285953-0a6f8780-f7a4-11ea-9b94-0ccc5ca13ac9.png)

**Comment by alschmiedt** [comment]
Fixed
