### ISSUE TITLE
blocks appear on themselves when their count  is more than 150

### ISSUE THREAD

**Issue by ayoub-root** [google/blockly#4297]
**Describe the bug**
when i create more than 150 custom blocks inside each category, all their position will be of the first block 

![image](https://user-images.githubusercontent.com/29442800/93667313-4b59eb80-fa85-11ea-8788-7b8a96a50cfa.png)

**Expected behavior**
as a list 
![image](https://user-images.githubusercontent.com/29442800/93667334-64629c80-fa85-11ea-80f6-c6e11ba7f570.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [85.0]

**Stack Traces**

```
Replace with error stack trace.
```

**Comment by NeilFraser** [comment]
I'm unable to recreate.  Can you check your browser's console.  There's probably an error that's being thrown.  Knowing this error should help.

**Comment by ayoub-root** [comment]
oh yeah i found some special characters  like & 
thank  you
