### ISSUE TITLE
Spaghetti in playground on IE11 & Edge sometimes taking unreasonably long

### ISSUE THREAD

**Issue by moniika** [google/blockly#4308]
**Describe the bug**

Loading spaghetti code in IE11 is **sometimes** taking several minutes (~4min) (after repeated testing, seeing between 1-4min).
(testing against develop currently hosted on github pages)

**To Reproduce**

1. Open [playground](google.github.io/blockly/tests/playground.html) in IE11
2. Click "Spaghetti" button to load large xml
3. Observe how long it takes to load the blocks.

**Expected behavior**

Loading blocks from xml shouldn't take this long

**Additional context**

Tested using BrowserStack.
Also compared behavior with currently hosted playground on blockly-demo, where it took between 40sec-3min on repeated tests.

**Comment by moniika** [comment]
Repeated testing showing ~2-3 min sometimes on both hosted demos and github pages. May not be a regression, but worth investigating.

**Comment by moniika** [comment]
After repeated testing, I am also seeing on hosted demos a similar lag in loading spaghetti blocks ~2-3min, indicating this might not be a regression, but worth looking into.

**Comment by moniika** [comment]
Having dev-tools open also seems to cause a longer load time.

**Comment by alschmiedt** [comment]
This is also happening on Edge.

**Comment by gonfunko** [comment]
Closing since we no longer support IE 11 and Edge is now a Chromium fork. This takes about a second or two nowadays.
