### ISSUE TITLE
Coordinate jump on empty workspace

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#432]
Open playground.
Create any block.
Delete the block.
Scroll to the bottom-right.

Note that the scrollbars are offset.  Also the workspace jumps when a drag starts.

<img width="161" alt="screen shot 2016-06-14 at 13 51 08" src="https://cloud.githubusercontent.com/assets/250480/16059253/1ce188e6-3237-11e6-9cad-8ebb8c6c0a7a.png">

**Comment by picklesrus** [comment]
Put together #434, but it means there isn't a way to "batch" delete without updating the scrollbars in between each one.  If that's unacceptable, I think I can detangle the showContextMenu methods in block_svg and workspace_svg to 1. share code, 2. provide the right hook at the end to only resize after all deletions have happened.
