### ISSUE TITLE
[2020Q3]Repeated switch toolbar grouping causes the workspace position to jump

### ISSUE THREAD

**Issue by htq110219891** [google/blockly#4338]
**Describe the bug**
Repeated switch toolbar grouping causes the workspace position to jump

**To Reproduce**
1. Drag any number of blocks to the workspace.
2. Drag the workspace position to make a big change in the position of the block.
3. Click on the toolbox menu with secondary grouping to open.(There must be a submenu in the group)
4. Click on the same toolbox menu to close. 
5. Repeat 3, 4 twice or more.
6. workspace position jump before drag(error)
7. Drag the workspace cause location recovery

**Expected behavior**
workspace position unchanged.

**Screenshots**
step2.
![拖动前](https://user-images.githubusercontent.com/6227487/94651501-212ce700-032b-11eb-96d5-b885d0d67347.jpg)

step6.
![微信截图_20200930144043](https://user-images.githubusercontent.com/6227487/94651521-27bb5e80-032b-11eb-8d6b-0e3fa3de69a4.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 85.0.4183.121

**Stack Traces**
blank

**Additional context**
both opening or closing toolbox Errors occur.
toolbox is xml format.
2020q2 release does not have this problem.

**Comment by alschmiedt** [comment]
Thanks for reporting!
It looks like this is getting caused by #4139 due to [the newY](https://github.com/google/blockly/blob/23c28a0e595ff0dab2b517a23f0cb7600aa7446d/core/toolbox/toolbox.js#L618) getting set to 0 if it is not a toolbox positioned at the top.
