### ISSUE TITLE
how to Remove horizontal scrollbar in the workspace in blockly

### ISSUE THREAD

**Issue by Vaibhav-Goti** [google/blockly#4343]
hello meme,
    My issues is how to i am remove the horizontal scrollbar in the workspace like image 1 above i am attached and second thing is
when workspace is null at time didn't show vertical scrollbar and when workspace in 4 to 5 blocks are available at time show vertical scrollbar so please meme help me for this. 

and i am giving link above in this how to work scrollbar as link i need this so please check one time and please help me.
https://studio.code.org/s/artist/stage/1/puzzle/1

![Screenshot (33)](https://user-images.githubusercontent.com/64088772/94791303-0de64e00-03f5-11eb-9eff-5566202b6f0b.png)

**Comment by moniika** [comment]
Blockly does not support disabling horizontal scrollbar. You will need to create your own custom implementation.
The website you have linked is using its own custom fork of blockly ([code-dot-org/blockly](https://github.com/code-dot-org/blockly))

I see you have also asked this question on the forum, the forum is where you should be directing these questions, not as a github issue.
