### ISSUE TITLE
Text fields are red sometimes on valid input

### ISSUE THREAD

**Issue by moniika** [google/blockly#4345]
**Describe the bug**

When a text field with a validator has a character changed that makes it invalid and changed back, the field will still be highlighted red (partially due to the value not having changed). 

**To Reproduce**

![8bd568fc-07f2-47dc-85f4-62d79acd9d6c](https://user-images.githubusercontent.com/6621618/94973210-e8724680-04bf-11eb-90d8-394f8993ee93.gif)

**Expected behavior**

Fields should not be red on valid input

**Additional context**

This issue is reproducible with number fields and date fields.

**Comment by alschmiedt** [comment]
Fixed.
