### ISSUE TITLE
perf improvement: investigate caching matrix from getScreenCTM

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#436]
Mouse down events end up calling getScreenCTM when trying to save the coordinates of at the start of a drag.  This causes a style recalculation and a forced layout (see screenshot of timeline).  Similarly to #435, I don't think the matrix should change unless workspace resize ends  up being called.  Look into caching it.

![screenctm](https://cloud.githubusercontent.com/assets/15675877/16092003/f0a2fd50-32ea-11e6-80b5-bce0019c296c.png)

The delay when starting a drag is most visible on mobile.

**Comment by rachel-fenichel** [comment]
Performance improvement from a naive implementation of this:
![fastctm](https://cloud.githubusercontent.com/assets/13686399/16164727/a2ce7842-3494-11e6-894e-bca1b012fa32.png)
![slowctm](https://cloud.githubusercontent.com/assets/13686399/16164728/a2d2e044-3494-11e6-9103-ad99e3e42231.png)

Tested in the blockly playground  by hitting the airstrike button, then starting recording and hitting "fake many drags", then stopping the recording after the drags finished.
