### ISSUE TITLE
`No Message String...` warning in console

### ISSUE THREAD

**Issue by stclairdaniel** [google/blockly#4369]
**Describe the bug**

In a minimal Blockly use case with a simple toolbox, warnings of the following type appear in the console:
```
No message string for %{BKY_MATH_ONLIST_TOOLTIP_STD_DEV} in %{BKY_MATH_ONLIST_TOOLTIP_STD_DEV}
No message string for %{BKY_MATH_ONLIST_TOOLTIP_RANDOM} in %{BKY_MATH_ONLIST_TOOLTIP_RANDOM}
...
```

**To Reproduce**

1. Visit this [minimal reproduction example](https://codesandbox.io/s/clever-chaum-hv8nf?file=/src/App.js) and view the console

**Expected behavior**

No warnings in the console

**Screenshots**

![Screen Shot 2020-10-13 at 2 28 53 PM](https://user-images.githubusercontent.com/14972752/95918330-72dc6500-0d60-11eb-948e-d0c1e50dc7cf.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.6
 - Browse: Chrome 85.0.4183.121 (Official Build) (64-bit)
 - Version:   "blockly": "3.20200924.3",

**Comment by moniika** [comment]
I think this is the same issue that is happening in #4358. I will close that one in favor of easier repro steps described here.

Based on investigation on that issue already done by @oleggo, `Blockly.utils.checkMessageReferences` is run after page load and in some environments the `Blockly.Msg` table is not yet loaded.

https://github.com/google/blockly/blob/11987dc6d6aa16138b36237e8959f2a3f91eb4e2/core/extensions.js#L415

**Comment by oleggo** [comment]
@moniika it happens in the case when Blockly main module starts to load *AFTER* `document.readyState` is set to `'complete'`. It causes `Blockly.utils.checkMessageReferences` to be called immediately without waiting for current tick to finish, because of this code: https://github.com/google/blockly/blob/11987dc6d6aa16138b36237e8959f2a3f91eb4e2/core/utils.js#L486
One possible scenario is when Blockly is loaded under Webpack.

**Comment by becnealon** [comment]
Has this issue been fixed? I am still able to recover this error. Is there a recommended solution?

**Desktop (please complete the following information):**
OS: MacOS Big Sur 11.2.3
Browse: Chrome 87.0.4280.141 (Official Build) (arm64)
Version: "unpkg" 6.20210701.0 as well as "github/blockly"  7.20211209.0

**Comment by johnnyoshika** [comment]
I'm also interested in this issue. It started to appear when I split my React app using code splitting. Here's the relevant discussion on Google Groups: https://groups.google.com/g/blockly/c/VQ1qjKMe3m4/m/Z-s_T2vrEQAJ

**Comment by selucaciu** [comment]
I am also facing this issue. Does anyone know how to fix this?

**Comment by CodingAvenger** [comment]
this isn't a fix at all, but I got to to work by using blockly.min.js instead of blockly.compressed.js
`<script src="node_modules\blockly\blockly.min.js"></script>`

**Comment by stnor** [comment]
Also having the issue. I'm using lazy loading with:
```
const Blockly = await import('blockly/browser');
```

**Comment by johnnyoshika** [comment]
@stnor That seems consistent with the problem I'm having. Although these warnings are annoying, they haven't been a problem for my app so far.

**Comment by alexbk66** [comment]
It also causes "screenshader.js:80 Uncaught **Error**: Tooltip function must return a string"

I don't do anything special, just load html with a simple Blockly example. Getting lots of warnings.

**Comment by johnnyoshika** [comment]
I'm using [Create React App](https://create-react-app.dev/), which does the loading using its pre-configured webpack settings. Create React App is pretty popular, so I imagine this will be a common problem with Blockly. That said, these warnings haven't been a problem other than the annoying console messages, so it's something I'm willing to live with.

**Comment by alexbk66** [comment]
> I'm using [Create React App](https://create-react-app.dev/), which does the loading using its pre-configured webpack settings. Create React App is pretty popular, so I imagine this will be a common problem with Blockly. That said, these warnings haven't been a problem other than the annoying console messages, so it's something I'm willing to live with.

But if you hover the mouse over the blocks - when it tries to display the **Tooltip** - doesn't it fail because the messages are not loaded?

**Comment by maribethb** [comment]
Hi everyone,

We submitted a fix for a related issue and I'm hoping it may have helped this, but since we don't use Angular or React ourselves it would be great to hear from you. Could you try this beta version `8.0.1-beta.0` and see if this issue is resolved? Thanks!

**Comment by DBurkeAoE** [comment]
Hello, I just recently started a project using Blockly in Angular and was running into this issue when using version 8.0.0 but updating to the version 8.0.1-beta.0 was able to fix the problem. However when updating to version 8.0.1 that just released the problem returned so I had to go back to the beta version. Was the fix intentionally removed in the stable release for 8.0.1 and if so can we expect it in a future stable release?

**Comment by reedspool** [comment]
I am having this issue as well without a build step. I did `npm install blockly` today and have version 8.0.2. I serve my application simply with `npx serve`. This is how I am loading Blockly at the end of my `<body />` tag:

```
        <script type="text/javascript" src="./node_modules/blockly/blockly_compressed.js"></script>
        <script type="text/javascript" src="./node_modules/blockly/msg/en.js"></script>
        <script type="text/javascript" src="./node_modules/blockly/javascript_compressed.js"></script>
        <script type="text/javascript" src="./node_modules/blockly/blocks_compressed.js"></script>
```

Unfortunately I'm not able to find the beta branch or release package to test if that would fix it.

If I move `msg/en.js` above `blockly_compressed.js` then I get this error: 

```
en.js:8 Uncaught TypeError: Cannot set properties of undefined (setting 'Msg')
    at en.js:8:22
    at en.js:10:2
```

**Comment by adrianfung** [comment]
I use version 8.0.2 too. 
I removed the `node_modules/blockly/msg` and use the GitHub's `msg`, 
and then changed the script src to `./node_modules/blockly/msg/js/en.js`

**Comment by jasonpanelli** [comment]
> I use version 8.0.2 too. I removed the `node_modules/blockly/msg` and use the GitHub's `msg`, and then changed the script src to `./node_modules/blockly/msg/js/en.js`

This worked for me too, as a quick fix

**Comment by reedspool** [comment]
I did as @jasonpanelli, worked a charm.

1. Copied `https://raw.githubusercontent.com/google/blockly/master/msg/js/en.js` to local `./blockly_msg_en.js`
2. Added `<script type="text/javascript" src="./blockly_msg_en.js"></script>`

**Comment by BeksOmega** [comment]
Hello everyone,

We've submitted another fix that we hope should work for all methods of loading (all module systems + script tags). For those of you having trouble with this, could you try this beta version: `8.0.4-beta.0` and reply here if it works or not?

If we get feedback that it works, then we can release an actual patch for the wider world!

Thanks,
Beka

**Comment by johnnyoshika** [comment]
@BeksOmega I tried `blockly@8.0.4-beta.0` and it results in this compile error which prevents my React app from loading:

![image](https://user-images.githubusercontent.com/504505/173996549-0d11f43a-fee9-441a-b176-70deae9d4b0d.png)

This error doesn't occur in `blockly@8.0.3-beta.1` so I believe it's a regression.

I hope that's helpful.

**Comment by maribethb** [comment]
Thanks Johnny. We have the latest fix at `8.0.1-beta.1` and it seems to be working in all the tests we've thought to run so far. would greatly appreciate you taking another look!

**Comment by johnnyoshika** [comment]
@maribethb I just tried [8.0.4-beta.1](https://www.npmjs.com/package/blockly/v/8.0.4-beta.1) and unfortunately I still get the string warnings:

![image](https://user-images.githubusercontent.com/504505/174942546-dc8c998a-d6d5-42a8-a7cf-3a8074a7e463.png)

My environment is described here: https://groups.google.com/g/blockly/c/VQ1qjKMe3m4/m/DmoPBv7RDgAJ

If it'll be helpful, I can create a simple React repo with code splitting to reproduce the warnings.

**Comment by Gauntlet173** [comment]
I'm having a similar problem, with warnings on load, and the main visible issue being that the block context menus will no longer display because `Msg` is undefined at `contextmenu_items.js` at 570.

I just tried it using 8.0.4-beta.1 and it did not resolve the problem.

![image](https://user-images.githubusercontent.com/11790846/176767807-e9110110-904e-43ac-a6bf-f5c8745dc534.png)

**Comment by Gauntlet173** [comment]
I have reverted Blawx to github's v8.0.2 and created a local copy of the 8.0.4 version of the en.js file, and loaded it as suggested above by @adrianfung and @jasonpanelli. That seems to be working.

**Comment by Insood** [comment]
Hey all, I've been using `<script src="https://unpkg.com/blockly/blockly.min.js"></script>` and it used to work until 8.0.4.

Downgrading to 8.0.3 fixes this for me: `<script src="https://unpkg.com/blockly@8.0.3/blockly.min.js"></script>`

I recommend bundling a specific version in your app :)

**Comment by maribethb** [comment]
@Insood can you provide more information? How did 8.0.4 break for you and how are you loading the message files?

In particular if you were using one of the workarounds listed here where you used an older version of the `msg` files with v8.0.3 then I think if you remove the workaround and use the version packaged in the release then everything should work... but if there's a test case we missed and 8.0.4 is broken for you we'd like to know asap. Thanks!

**Comment by Gauntlet173** [comment]
Just as follow up, #6329 seems to have solved the problem for me. If I remove the workaround, and clone from the "develop" branch of the repository, it seems to be resolved.

**Comment by maribethb** [comment]
Thanks for confirming! I believe most of the recent comments on this thread were really about #6123 and have accordingly marked that issue as closed.

Unfortunately that issue looked similar in effect to this one, but I've confirmed the original issue reported here is still occurring, as it relates to React specifically or perhaps lazy loading in general, so I'm going to leave this one open. In particular with this issue you'll get warnings in the console but everything will actually work as expected.

If anyone else reading this experiences a similar issue but things don't work as expected (in other words, you get these console warnings AND blocks/toolboxes actually appear broken) please open a new issue as that would not be related to this one. Thank you!

**Comment by frck006** [comment]
Hi,
I use @sveltejs/kit, vite 3.1.8 and with Blockly **V9.0.1**, the problem is always here:
![image](https://user-images.githubusercontent.com/10244725/197380656-48495054-b802-4b61-9d0f-9d211c1194fb.png)

**Comment by DaveWelling** [comment]
This creates a lot of garbage in our unit tests logs.
I know this workaround is ugly, but If you get as desperate as I was to get rid of this you can load your Blockly dependency like so:
```
/* eslint-disable */
// ******************************************************************************
// See issue https://github.com/google/blockly/issues/4369
// Blockly will not allow you to avoid printing out a bunch of useless
// localization warnings for messages we don't use.
// This clogs up unit testing logs, etc.
// The versions for both log and warn are because they keep changing which ones they are
// using across builds.
const tempConsoleLog = console.log;
const tempConsoleWarn = console.warn;
let Blockly;
try {
    console.log = message => {
        if (message.startsWith('WARNING: No message string for %{')) return;
        else tempConsoleLog(message);
    };
    console.warn = message => {
        if (message.startsWith('No message string for %{')) return;
        else tempConsoleWarn(message);
    };
    Blockly = require('blockly');
} finally {
    console.log = tempConsoleLog;
    console.warn = tempConsoleWarn;
}
// ******************************************************************************
/* eslint-enable */
```
I found we only needed to do this once in our entry point.

**Comment by semiaddict** [comment]
@maribethb,

> ... as it relates to React specifically or perhaps lazy loading in general...

This seems to be a general issue with lazy loading, as I am experiencing the same thing when lazy loading Blockly in a Vue 3 app.

**Comment by doctorpangloss** [comment]
Can this be resolved for real? I appreciate the purpose of these messages for developers, but it doesn't make sense to have them for end users.

**Comment by stasberkov** [comment]
M.b. introduce a flag do not show such errors when compile for prod mode?

**Comment by rachel-fenichel** [comment]
@cpcallen this now happens in the playground, after your recent change to bootstrapping/loading. Did you expect that?
