### ISSUE TITLE
Dynamic arguments and type check

### ISSUE THREAD

**Issue by starhu521** [google/blockly#4374]
**Is your feature request related to a problem? Please describe.**

Association between parameters on the block. When I change a parameter of a block, i need change  or create other parameters on the block, include quantity and type check. 

**Describe the solution you'd like**

I need help to implement a feature. That's like this:

The block with uncertain arguments, it has a argument of field_dropdown. When I change the selection of the field_dropdown, I will change all of the rest arguments of the block, includes number and type check of arguments of the block.

Just like merge some blocks together to defined one That has a main argument what decides the rest arguments of the block. 

thanks a lot.

**Comment by moniika** [comment]
You can achieve something like this using mutators. Our documentation for mutators is located [here](https://developers.google.com/blockly/guides/create-custom-blocks/extensions#top_of_page).
A simple example of a block that changes inputs based on dropdown value is the `math_number_property`. The code for that block is located in [blocks/math.js](https://github.com/google/blockly/blob/master/blocks/math.js#L172) and I would specifically recommend looking at how the mutator is implemented.

Please direct further questions for advice to our community [forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/blockly).

**Comment by starhu521** [comment]
> You can achieve something like this using mutators. Our documentation for mutators is located [here](https://developers.google.com/blockly/guides/create-custom-blocks/extensions#top_of_page).
> A simple example of a block that changes inputs based on dropdown value is the `math_number_property`. The code for that block is located in [blocks/math.js](https://github.com/google/blockly/blob/master/blocks/math.js#L172) and I would specifically recommend looking at how the mutator is implemented.
> 
> Please direct further questions for advice to our community [forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/blockly).

Yes, I have checked these mutator and block. And I do that with scratch-blocks has some bugs and complexe a lot. I will go to   
 community forum.
Thanks!
