### ISSUE TITLE
Provide more support for non auto closing flyouts

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4378]
**Is your feature request related to a problem? Please describe.**
We have a flag on flyouts so that they do not close automatically when someone clicks on the workspace. However, we do not provide any additional features with this.

**Describe the solution you'd like**
Add a way to: 
- Make the flyout and the toolbox both a delete area when `autoClose=false`
- Have `workspace.getMetrics` not include both the flyout and the toolbox when calculating the size of the workspace.

**Describe alternatives you've considered**
- Adding a flag to decide this behavior. I'm not against adding a flag, but I also don't want to add a bunch of unnecessary flags.

**Additional context**
Opening this as a place to add any other functionality we think would be nice to have when `autoClose=true` on a flyout.

**Comment by alschmiedt** [comment]
Adding this support would mean that we could remove the metrics manager changes from the continuous toolbox. This would allow the continuous toolbox to be able to be combined with the fixedEdges plugin.

**Comment by BeksOmega** [comment]
Closed by the same thing that closed #7506
