### ISSUE TITLE
clicking zoom in multi_playground doesn't close an open flyout on first page load

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#440]
This seems to fix itself after adding blocks or perhaps some other actions, but to reproduce:

1. load https://blockly-demo.appspot.com/static/tests/multi_playground.html with categories
2. click a category to open flyout
3. click zoom in (out also works) a few times.
4. click another category.

Notice the blocks in the flyout and the workspace (though it is not as obvious since it is blank, but scrollbars move if you zoom out) have changed zoom levels.

Expected behavior is that the flyout closes when you click the zoom in button.

**Comment by NeilFraser** [comment]
Good catch.  Fixed.
