### ISSUE TITLE
Rebuild error

### ISSUE THREAD

**Issue by ghwenti** [google/blockly#4402]
**Describe the bug**

Rebuild error on ver. 20200924.3 using "npm run build:core".

**To Reproduce**

1. Open cmd on Windows 10.
2. Input "npm run build:core"
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/73373055/97066083-d24e3680-15e4-11eb-84d9-8c712dfb5bc3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The error happened on all 20200924 versions.
No error on 20200625.2 version.

**Comment by samelhusseini** [comment]
We are currently using version `20200920` in Blockly.

**Comment by ghwenti** [comment]
Hi Samel, thanks for your reply. Could you show me where to download the 20200920 version? Would it be better to put it on the same place so that everyone can download it? Also, does it mean 20200924 is not ready for general use? Sorry for asking these questions as I do not know the development flow of this site.

**Comment by ghwenti** [comment]
I would be much appreciated if anyone can help answer the questions. Thanks!

**Comment by alschmiedt** [comment]
Hello!
The newest version is `3.20200924.0`.
You can get the `3.20200924.0` version by either pulling master or by updating to the version on [npm](https://www.npmjs.com/package/blockly).

**Comment by ghwenti** [comment]
Thanks a lot, I will try it.

**Comment by ghwenti** [comment]
I have found out that it is probably my machine's problem. I tried the
latest version on another machine and it works. Sorry for the trouble
caused.

**Comment by alschmiedt** [comment]
No worries! Going to close since it does not look like it is a problem with core.
