### ISSUE TITLE
Dropdown broken in Graph demo

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#4403]
Load the graph demo:
https://blockly-demo.appspot.com/static/demos/graph/index.html
Click on the dropdown for the arithmatic block.

Expect: +, -, *, /, ^
Actual: Empty menu.

This probably has to do with it being a compiled application.

**Comment by samelhusseini** [comment]
Looks like interference between our blocklyMenu (which contains a legacy class `goog-menu`) and https://www.gstatic.com/charts/49/css/util/util.css
