### ISSUE TITLE
In horizontal layout tollbox is still scrolled by UP/DOWN keys

### ISSUE THREAD

**Issue by svbatalov** [google/blockly#441]
I'd expect LEFT/RIGHT buttons to scroll the toolbox when `horizontalLayout` is true.

**Comment by rachel-fenichel** [comment]
Good point.  This isn't especially high priority right now, but if you submit a patch I'd be happy to take a look.

**Comment by svbatalov** [comment]
Nice move! :)

Alright, take a look at #460 then (WARNING: dirty hack ahead!).

**Comment by NeilFraser** [comment]
Still broken in two interesting ways.  A divider eats the focus.  Right and left are reversed in RTL.
