### ISSUE TITLE
both mouse and rat should appear in a rodents list

### ISSUE THREAD

**Issue by frmoded** [google/blockly#4411]
Trying to add two guys at the same time to the rodent list, a rat and a mouse.
It is implied by your naming (in this is the required use case) that the list will hold both rat and mouse simultaneously. Could you please check?

This is based on official example:
https://developers.google.com/blockly/guides/create-custom-blocks/type-checks#json_4

{
"type": "append_rat",
"message0": "Rat",
"previousStatement": "Rat",
"nextStatement": "Rat"
},
{
"type": "append_mouse",
"message0": "Mouse",
"previousStatement": "Mouse",
"nextStatement": "Mouse"
},
{
"type": "rodent_list",
"message0": "Rodents %1",
"args0": [
{
"type": "input_statement",
"name": "RODENTS",
"check": [
"Mo

**Comment by rachel-fenichel** [comment]
Please post clarification questions on the forum, not as issues.
