### ISSUE TITLE
Block ID not available on its SVG Group in IE 

### ISSUE THREAD

**Issue by ajpal** [google/blockly#4419]
I think https://github.com/google/blockly/blob/master/core/block_svg.js#L118 does not work for IE.
I also found [https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/data-*](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/data-*), which indicates that IE support for this is unknown.

Minimal example using the Blockly Playground:

Expected: `Blockly.selected.svgGroup_.dataset.id` returns the block's ID
Chrome
Observed: `Blockly.selected.svgGroup_.dataset.id` returns the block's ID
![image](https://user-images.githubusercontent.com/8787187/97643991-5e59c700-1a06-11eb-9cf9-6e31426193af.png)

IE
Observed: `Blockly.selected.svgGroup_.dataset.id` raises error `Unable to get property 'id' of undefined or null reference`
![image](https://user-images.githubusercontent.com/8787187/97644026-6d407980-1a06-11eb-8813-d4fb253e75bc.png)

We use the `data-id` from the SVG group to interact with blocks in UI tests, so this is blocking for us as we need to support IE.

**Comment by rachel-fenichel** [comment]
Right, it looks like we just avoid setting or accessing it for the IE case.

Which IE version do you need to support?

MDN [suggests](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) a workaround that we can try for IE, and that should end up with the data in the same place: 

> The main issues to consider are Internet Explorer support and performance. Internet Explorer 11+ provides support for the standard, but all earlier versions do not support dataset. To support IE 10 and under you need to access data attributes with getAttribute() instead. Also, the performance of reading data-attributes compared to storing this data in a regular JS object is poor.

**Comment by ajpal** [comment]
We just need to support IE11.
Using `setAttribute()` if `svgGroup_.dataset` is undefined works locally.

Happy to open a PR for this if you'd like!

**Comment by rachel-fenichel** [comment]
Yes, please open a PR.

**Comment by alschmiedt** [comment]
Fixed.
