### ISSUE TITLE
Combine horizontal toolbox and vertical flyout.

### ISSUE THREAD

**Issue by svbatalov** [google/blockly#442]
I believe the combination of horizontal toolbox and vertical flyout is more convenient than the current combination, because you can not (currently) easily scroll horizontal flyout with mouse (you have to figure out to press SHIFT button) and the amount of scroll is much bigger since blocks are wide.

As a quick hack I can emulate the required combination by setting `workspace.toolbox_.flyout_.horizontalLayout_ = false`, but in this case the flyout sticks to the left side and is not scrolable (vertically).

It would be great to have corresponding configuration option.

**Comment by rachel-fenichel** [comment]
No plan to support this--there are already so many combinations of configurations that it's almost impossible to test them all, and we're seeing plenty of bugs from the recent addition of horizontal flyout/toolbox.  I'll need to see those all shake out before adding more options seems like a good idea.

**Comment by svbatalov** [comment]
Ok-ok :)

**Comment by AntiochInteractiveMedia** [comment]
I'm looking for a solution for the same thing.  The horizontal menu is compelling for Blockly to fit into certain layouts -- but the horizontally scrolling list of blocks just isn't appealing.

**Comment by rachel-fenichel** [comment]
Noted, and thanks for letting us know this is a feature that you would use.  

I have the same maintenance concerns as I did last year, but I'll keep an ear out for more people who would use this and reassess if I hear higher demand.
