### ISSUE TITLE
Is it possible to copy a block to another tab in the browser?

### ISSUE THREAD

**Issue by Taikono-Himazin** [google/blockly#4424]
Is it possible to have a block etc. in the clipboard in the form of xml etc. and interpret the xml and set the block when pasting it in another tab?

If there is a way, please let me know.

It might be better to ask a question on the google forum, but I didn't know how to use it. sorry.

**Comment by alschmiedt** [comment]
Hello!

This is not currently available in core blockly. We are looking into implementing it as a plugin.

Closing this issue in favor of google/blockly-samples#371
