### ISSUE TITLE
Workspace constructor expects plugin option to exist

### ISSUE THREAD

**Issue by seldomU** [google/blockly#4429]
**Describe the bug**

Workspace creation fails (in `getClassFromOptions`) when the constructor is called with an options object that does not contain the _plugins_ property. This does not affect workspaces created via Blockly.inject, due to the Blockly.Options constructor adding the _plugins_ property.

**Comment by alschmiedt** [comment]
It can be a bit confusing, but the workspace actually expects a `Blockly.Options` object when created. 
```
Blockly.WorkspaceSvg(new Blockly.Options({}))
```
This is the second time I've seen someone have this problem We can add a check in `getClassFromOptions` but I think we should also update our documentation to make this more clear.

**Comment by seldomU** [comment]
The first time could have been me as well. This same error occurred a few releases ago with another new option. I will use the Options constructor from now on.

**Comment by rachel-fenichel** [comment]
Documentation changes needed:

- Add `plugins` property here https://developers.google.com/blockly/guides/configure/web/configuration_struct

- Maybe add a section at the bottom of the page saying that if you create a workspace directly, you need to pass in an instance of Blockly.Options. Add sample code.
