### ISSUE TITLE
Custom note field can't be edited on mobile

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#4430]
Open the custom note field on an Android device (presumably iOS too):
https://blockly-demo.appspot.com/static/demos/custom-fields/pitch/index.html

Attempt to change "C4" to "D4".  No change.

Full description here:
https://github.com/google/blockly-games/issues/212

**Comment by moniika** [comment]
Fixed in #4436. Tested on BrowserStack mobile emulator to confirm.
