### ISSUE TITLE
Ability to make block with infinite / unlimited inputs

### ISSUE THREAD

**Issue by 4n70w4** [google/blockly#4435]
**Is your feature request related to a problem? Please describe.**

Ability to make block with infinite / unlimited inputs.

For example need generate:

```php
$t = new Divide($k1, $k2, $k3, $k4);
```

or

```php
$t = new Sum($k1, $k2, $k3, $k4, $k5, $k6, ..., etc);
```

**Describe the solution you'd like**

Add an action to the context menu or somewhere else to add additional inputs.
It would be infinitely more convenient and beautiful to be able to add additional intputs to blocks.

**Describe alternatives you've considered**

Currently i know only one workaruond: use long bulky chains like this:
![image](https://user-images.githubusercontent.com/38257723/98361195-283ac980-203c-11eb-8bc4-caabc3e09f94.png)

or

![image](https://user-images.githubusercontent.com/38257723/98361217-35f04f00-203c-11eb-8b7b-38d14aaf72fd.png)
![image](https://user-images.githubusercontent.com/38257723/98361642-f5dd9c00-203c-11eb-8994-f93a7c16b036.png)

It is not convenient and not understandable for users. They are sad about it.

**Additional context**

**Comment by 4n70w4** [comment]
Okay in Blockly Developer Tools (https://blockly-demo.appspot.com/static/demos/blockfactory/index.html) I found blocks with ability needs me:

![image](https://user-images.githubusercontent.com/38257723/98376043-02212380-2054-11eb-8aa5-a7f6bae0c44e.png)

![image](https://user-images.githubusercontent.com/38257723/98376078-106f3f80-2054-11eb-945b-76bcd1675419.png)

But I don't see ability to configure similar block via Blockly Developer Tools.

I can not understand whether it is possible to make?

**Comment by rachel-fenichel** [comment]
You can do this with [mutators](https://developers.google.com/blockly/guides/create-custom-blocks/extensions). Your mutator will need to add and remove inputs.

Here's the [definition](https://github.com/google/blockly/blob/master/blocks/lists.js#L119) for the `lists_create_with` block, which has a mutator to add an arbitrary number of inputs.

The blocks in `@blockly/block-plus-minus` also do this, with a different UI. Here's the [code](https://github.com/google/blockly-samples/tree/master/plugins/block-plus-minus).

**Comment by 4n70w4** [comment]
Good mutator tutorial: https://www.kidscoding8.com/5646.html
