### ISSUE TITLE
"readOnly" disables scrolling

### ISSUE THREAD

**Issue by ctrowat** [google/blockly#444]
When you initialize an instance of Blockly with "readOnly" set to true you are unable to scroll the workspace.  If, for example, you are loading a large amount of blocks from XML but do not wish for them to be edited it is impossible for the user to scroll to view the full set of blocks.  I also see that zooming IS enabled when in readOnly mode making this even more confusing to the user.

"readOnly" should only stop you from modifying the contents, it should not lock the viewport.

**Comment by paulkoanui** [comment]
+1 for this.  I wish to make a workspace read-only while still having the ability to scroll

**Comment by picklesrus** [comment]
I believe you can configure this by setting readOnly to true and scrollbars true in the object you pass to inject.  So while only setting readOnly: true disables scrolling, you should be able to explicitly turn it back on as long as you have both of these:
readOnly: true
scrollbars: true

**Comment by ctrowat** [comment]
Good point!  I asked this on the google group and it went without answer but your solution does indeed work.  Thanks!
