### ISSUE TITLE
The link of closure-compiler-vxxxxxxxx.jar for download is broken

### ISSUE THREAD

**Issue by jossiey** [google/blockly#4442]
**Where**
https://developers.google.com/blockly/guides/modify/web/advanced#download_closure_compiler

**What**

  
- [ ] Text
- [ ] Image or Gif
- [x] Other

**Old content**
When you click the hyperlink of  closure-compiler-vxxxxxxxx.jar, it shows a 404 page

**Suggested content**
Suggest to redirect to a correct download page. 

**Additional context**

**Comment by moniika** [comment]
Updated

**Comment by NeilFraser** [comment]
The latest compiler is here:
  https://unpkg.com/google-closure-compiler-java/compiler.jar
Something I had to do some digging for while maintaining Blockly Games.

A simple download link is better than forcing people to use Maven or NPM.  Can we revert cl/341861307 and just update the link?

**Comment by rachel-fenichel** [comment]
Yes, as long as we know that the link will continue to work (since the closure compiler folks explicitly decided to stop publishing their latest version). But since it's unpkg, it should be fine.

**Comment by moniika** [comment]
Updated.
