### ISSUE TITLE
Support custom tooltip rendering

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#4444]
**Is your feature request related to a problem? Please describe.**

Tooltips currently only support text. It'd be great if we added support for folks wanting to customize the rendering of the tooltip.

**Describe the solution you'd like**

Similar to how it's done in the monkey patch in @blockly/block-extension-tooltip, we can allow the show method to call a method on the block it's showing to render the tooltip.

**Additional context**

Related bug https://github.com/google/blockly/issues/983 that would be much easier to implement with something like this.

**Comment by vgb1993** [comment]
Hy there, I also need to support html in tooltips.

**Comment by maribethb** [comment]
Fixed by #5956
