### ISSUE TITLE
undo is abnormal in controls_if

### ISSUE THREAD

**Issue by 1037221854** [google/blockly#4445]
**Describe the bug**
Undo is abnormal when add elif/else block to not the last one in `controls_if` block.

**To Reproduce**

1. Create a `controls_if` block.
![1](https://user-images.githubusercontent.com/26497579/98903329-56b01d00-24f2-11eb-8ab3-bf3f7ee58671.png)

2. Add `else if` after if.
3. Add a condition in `else if` just created.
![image](https://user-images.githubusercontent.com/26497579/98903430-86f7bb80-24f2-11eb-8863-23c5a4f645ee.png)

4. Add a new `else if` on the top of the `else if` just created.(find that some move events hanppen after this step)
![image](https://user-images.githubusercontent.com/26497579/98903456-9840c800-24f2-11eb-8a2c-6ab3ec6d1a49.png)
![image](https://user-images.githubusercontent.com/26497579/98903465-9f67d600-24f2-11eb-8378-7a0a00fbaeae.png)

5. Undo, and find it dosn't work before the thrid times.

**Expected behavior**

Undo is effective at the first time, the new `else if` will be delete.

**Comment by alschmiedt** [comment]
Thanks for reporting!

I can repro this issue. I'm not sure, but I think it has to do with the fact that when you create an input all the inputs below it are re create. This doesn't happen if you add another else if on the end.

**Comment by 1037221854** [comment]
@alschmiedt  You are right！But sometimes the order of ‘else if’ is important, and i want to add a 'else if' not on the end. Thanks for your help!
