### ISSUE TITLE
field image click event not work

### ISSUE THREAD

**Issue by samping** [google/blockly#4446]
i create block like this! but i click the image ,it can not handle the function . i run it in chrome

Blockly.Blocks['move_joint1'] = {
    init: function() {
      this.appendDummyInput()
          .appendField(new Blockly.FieldImage("https://www.gstatic.com/codesite/ph/images/star_on.gif", 15, 15,
           { alt: "*", flipRtl: "FALSE" ,**onClick:()=>{console.log(123)}}))**
          .appendField("move joint J1")
          .appendField(new Blockly.FieldTextInput("0"), "j1")
          .appendField("J2")
          .appendField(new Blockly.FieldTextInput("0"), "j2")
          .appendField("J3")
          .appendField(new Blockly.FieldTextInput("0"), "j3")
          .appendField("J4")
          .appendField(new Blockly.FieldTextInput("0"), "j4")
          .appendField("J5")
          .appendField(new Blockly.FieldTextInput("0"), "j5")
          .appendField("J6")
          .appendField(new Blockly.FieldTextInput("0"), "j6")
          .appendField("Wait")
          .appendField(new Blockly.FieldDropdown([["true","true"], ["false","false"]]), "wait");
      this.setPreviousStatement(true, null);
      this.setNextStatement(true, null);
      this.setColour(230);
   this.setTooltip("");
   this.setHelpUrl("");
    }
  };

**Comment by samping** [comment]
i write like this can work!!
Blockly.Blocks['move_joint'] = {
    init: function() {
      var image = new Blockly.FieldImage("https://www.gstatic.com/codesite/ph/images/star_on.gif", 15, 15,
      { alt: "*", flipRtl: "FALSE" ,})
      **image.setOnClickHandler(()=>{console.log(123)})**
      this.appendDummyInput()
          .appendField(image)
          .appendField("move joint J1")
          .appendField(new Blockly.FieldTextInput("0"), "j1")
          .appendField("J2")
          .appendField(new Blockly.FieldTextInput("0"), "j2")
          .appendField("J3")
          .appendField(new Blockly.FieldTextInput("0"), "j3")
          .appendField("J4")
          .appendField(new Blockly.FieldTextInput("0"), "j4")
          .appendField("J5")
          .appendField(new Blockly.FieldTextInput("0"), "j5")
          .appendField("J6")
          .appendField(new Blockly.FieldTextInput("0"), "j6")
          .appendField("Wait")
          .appendField(new Blockly.FieldDropdown([["true","true"], ["false","false"]]), "wait");
      this.setPreviousStatement(true, null);
      this.setNextStatement(true, null);
      this.setColour('#66cdaa');
   this.setTooltip("");
   this.setHelpUrl("");
    }
  };

**Comment by alschmiedt** [comment]
Hello! 

It looks like you resolved your issue which is great : ) In the future if you have any questions like this you can add them to the [blockly forum](https://groups.google.com/g/blockly). That way other developers will be able to help you and will benefit from the answers you receive. 

Thanks!
