### ISSUE TITLE
Standardize field number constraints API

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#445]
Looks like we've created three different APIs for field numbers.

Android: FieldNumber.setConstraints(double min, double max, double precision)
Web:      FieldNumber.setMin(float), FieldNumber.setMax(float), FieldNumber.setPrecision(float)
Scratch: new FieldNumber(text, opt_validator, min, max, precision)

I would personally lean towards the Android API since that allows ranges to be updated and verified when they are set. With the web version it would be possible for a developer to be temporarily inconsistent if they lowered the max below the min.

**Comment by carlosperate** [comment]
> Web: FieldNumber.setMin(float), FieldNumber.setMax(float), FieldNumber.setPrecision(float)

Is that really implemented in this repository?

**Comment by RoboErikG** [comment]
Not committed yet https://github.com/google/blockly/commit/732e9b065912e45462f806ce8c6e9ae2c7ebb502

**Comment by NeilFraser** [comment]
Scratch: new FieldNumber(text, opt_validator, min, max, precision)

Having an optional variable mid-way through the argument list is ... weird.  It is also inconsistent with all other fields where the optional validator is at the end.  What about:

```new FieldNumber(text, min, max, precision, opt_validator)```

Then I'll nuke the setMin/Max/Precision functions.

**Comment by RoboErikG** [comment]
@NeilFraser Do you think we'll see any developers that need to update the range without recreating the field?

**Comment by NeilFraser** [comment]
@RoboErikG This is JavaScript: they are welcome to access the private properties while filing a bug asking for getters and setters.  I generally don't create getters and setters without a reasonable usecase up front.

**Comment by RoboErikG** [comment]
Fair. One more question on values. What would you expect to use for unconstrained on each parameter?

On Android we're using NaN in general to mean unconstrained but will also accept +Inf for max, -Inf for min, and 0 for precision to mean unconstrained.

**Comment by AnmAtAnm** [comment]
These are not simple setters.  They should revalidate the value (with possible adjustments) when assigned, so we shouldn't encourage users to write the values directly.

When considering mutators (and similar app code), I think there are reasonable cases where a developer would want to update the min and max constraints.  For example, if a number input refers to the nth item in a list, the mutator or app might adjust the constraints that as a list size changes.

I have no problem including a convenience constructor that also calls setConstraints()

**Comment by NeilFraser** [comment]
Round 2: https://github.com/google/blockly/commit/0be0cc89c7f686ed6377248f7e1caa76578669c3
```
new FieldNumber(value, opt_min, opt_max, opt_precision, opt_validator)
FieldNumber.setConstraints(min, max, precision)
```
NaN or undefined may be used to remove any constraint, or they may be set to -Infinity, +Infinity, 0 respectively.

Everyone happy with this?  Scratch team too?

**Comment by tmickel** [comment]
Should work for us

**Comment by AnmAtAnm** [comment]
👍

**Comment by samelhusseini** [comment]
Looks like this has been fixed :)
