### ISSUE TITLE
Enable stricterMissingRequire in build_tasks

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#4457]
**Is your feature request related to a problem? Please describe.**

The closure compiler now has a flag to check for missing requires.

**Describe the solution you'd like**

Enable the flag and fix missing requires.

**Describe alternatives you've considered**

Ignore it.

**Comment by samelhusseini** [comment]
As of Jan 2021, this is enabled through `missingRequire`. Disabled temporarily in  https://github.com/google/blockly/pull/4581

**Comment by rachel-fenichel** [comment]
Bumping to q2 milestone, but we removed about 500 of these warnings during q1.
