### ISSUE TITLE
Update the language dropdown on documentation (devsite)

### ISSUE THREAD

**Issue by lvya-sy** [google/blockly#4462]
**Describe the bug**

Is the language toggle function working at offical site

**To Reproduce**

1. Go to 'https://developers.google.com/blockly/'
2. Click on 'language toggle'
3. See nothing works
![image](https://user-images.githubusercontent.com/52820436/99610082-17328500-2a4c-11eb-9a18-0530ec57a184.png)

**Expected behavior**
It can toggle language in the page.

**Comment by moniika** [comment]
This does appear to be working incorrectly. I don't believe we have translations for our documentation, so the dropdown of supported languages should only have english (or be removed).
This is likely a configuration we need to set or adjust specific to where we are hosting the documentation.

Thanks for reporting.

**Comment by maribethb** [comment]
After looking into this, the dropdown is controlled by the Google Developers site as a whole. If you pick your preferred language, it will show you any content it has in that language and English for everything else. This setting is shared between sites, so for example, Android may have documentation in your preferred language and they don't want you to have to keep changing the language dropdown. For now, we don't have any content in any language other than English, so this is working as designed, and we can't change the behavior.
