### ISSUE TITLE
Text and input field fills are black when painting the SVG to a canvas

### ISSUE THREAD

**Issue by Nekomajin42** [google/blockly#4474]
**Describe the bug**

I have a turtle graphics app, which draws shapes onto a canvas from a code generated by Blockly.

I have a button, which grabs the drawing canvas and the `svg` child of the Blockly `div`, turns the latter into a base64 data uri, and paints them onto a canvas, then saves the image via the save dialog of the browser.

It works fine, except on thing: Every `<text>` and `.bloclyFieldRect` has black fill on the composed image. Decoding the base64 uri has the black fills too, so either it goes wrong during the `window.btoa()` call or Blockly has a bug.

**Expected (on screen)**
![image](https://user-images.githubusercontent.com/6796246/100155763-1cf2f500-2ea8-11eb-929b-1df216520946.png)

**Actual (after saving)**
![image](https://user-images.githubusercontent.com/6796246/100155800-28deb700-2ea8-11eb-9822-ad9d8a323a60.png)

**Desktop (please complete the following information):**
 - OS: Win10 Pro 20H2
 - Browser: latest Chrome and Firefox stable

**Comment by samelhusseini** [comment]
It sounds like your SVG is missing blockly CSS. You might need to grab the CSS from the page and add it to your SVG.
We do something similar in our screenshot code for testing: https://github.com/google/blockly/blob/master/tests/playgrounds/screenshot.js#L84

In the future we ask that you please use the forums for asking questions and reserve Github issues for filing bugs:
https://groups.google.com/g/blockly
