### ISSUE TITLE
Very old deprecated functions

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4475]
**Describe the bug**
There are a collection of deprecated [block events](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/core/block_events.js#L18), and [block provides](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/blocks/lists.js#L18) that have been deprecated for 3 or 4 years. We should come up with a plan for how we want to deal with these. 

**Potential options:** 
- Just remove them.
- Add a comment about when we are going to remove them.
- Decide it is not worth it to remove them.

**Screenshots**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by nixgc** [comment]
Hello, I was wondering if I could go in and take out this collection of code and remove them if that is what has been decided? I've already started looking at the lines of code so I am familiar with them.

**Comment by alschmiedt** [comment]
Hello!

Thanks for your interest in this issue. I think we decided on two courses of action for right now:
- Remove the [block provides](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/blocks/lists.js#L18). 
- I don't think we are quite ready to remove the old block events. However, we think it would be helpful to switch around what class is being aliased. This would allow us to remove the old block events easier in the future. For example, we want [Blockly.Events.Change](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/core/block_events.js#L89) to instead be named `Blockly.Events.BlockChange`. And the following line should instead be `Blockly.Events.Change = Blockly.Events.BlockChange`: https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/core/block_events.js#L113

Feel free to respond with any questions!
