### ISSUE TITLE
More bugs in full screen mode

### ISSUE THREAD

**Issue by 4n70w4** [google/blockly#4476]
Hi! I open https://blockly-demo.appspot.com/static/demos/resizable/overlay.html

And run in Google Chrome 87.0.4280.66 

console:

```javascript
$('#blocklyDiv').requestFullscreen();
```

In full screen mode don't work text input. First 5 seconds - window mode, next - fullscreen mode:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/38257723/100220584-a21dee80-2f28-11eb-8907-8bd2ff53d7a6.gif)

Also don't work dropboxes. First 5 seconds - window mode, next - fullscreen mode:

![ezgif-3-85f2994c41e6](https://user-images.githubusercontent.com/38257723/100220709-c7aaf800-2f28-11eb-95ec-3e731982a8b4.gif)

Perhaps something does not work, I have no way to check it.

No errors in console.

**Comment by samelhusseini** [comment]
You'll need to first call `Blockly.setParentContainer` with your container for full screen mode to work.
see https://github.com/google/blockly/issues/3758 for context.

**Comment by 4n70w4** [comment]
I find solution in https://github.com/google/blockly/issues/4383
