### ISSUE TITLE
Overwriting of goog.getMsg(...) or any other closure library functions.

### ISSUE THREAD

**Issue by MarkusBordihn** [google/blockly#448]
Please make sure that you don't overwrite / manipulate any existing closure library functions or base.js functions.

Example:
https://github.com/google/blockly/blob/master/core/msg.js

`goog.getMsg = function(str, opt_values) {...};`

It would not be an issue if you are using some generic id like '__blockly__Today' but an mapping on 'Today' is very likely to be used in other projects as well.

Issue for closure based projects:
Let assume you are not using Blockly (not visible) at the moment, but the UI language is changed.
Because of this manipulation goog.getMsg('Today'); will still return the former Blockly used language and not the current select UI language.

Please keep in mind that the closure compiler is merging all code in one file.
Even if only one part of your project is using Blockly the goog.getMsg will be overwritten for the whole project.

**Comment by MarkusBordihn** [comment]
`var CLOSURE_DEFINES={"goog.DEBUG":!1};`

Disable goog.DEBUG even if it was enabled before.

Because Blockly is an library it should not do such global changes on the goog. scope.
Furthermore this definition should be not part of the JS files and should be declared outside like:
```javascript
<script>var CLOSURE_DEFINES = {"goog.DEBUG":false};</script>
<script src="....js"></script> 
```

**Comment by MarkusBordihn** [comment]
Found an additional conflict Blockly assume to have exclusive access to goog.  functions like `goog.ui.tree`.

But if you are using `goog.ui.Toolbar` as well it could be that Blockly process the Toolbar items in Blockly.Toolbox.prototype.populate_ as well which will fail in most cases.

So in this case the loading order is very important to make sure that blocks is working as expected and not processing any "wrong" items.

**Comment by jart** [comment]
Doesn't the Closure Compiler have a compiler pass that optimizes away calls to `goog.getMsg()` with the translated text?

**Comment by MarkusBordihn** [comment]
It have, but it depends on the use case e.g. soy template, uncompressed code, ... e.g.:
https://developers.google.com/closure/templates/docs/translation

But even if the Closure Compiler is optimizes away all goog.getMsg() calls (with valid translations).
The overwritten goog.getMsg will be still part of the code and will change the default behavior of goog.getMsg function calls for the hole closure project.

**blockly_compressed**
`goog.getMsg=function(a,b){var c=goog.getMsg.blocklyMsgMap[a];c&&(a=Blockly.Msg[c]);return goog.getMsgOrig(a,b)}`

**Comment by samelhusseini** [comment]
Closing as we've removed our closure library dependency.
