### ISSUE TITLE
Function mutator flyouts to not update (new events?)

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#4499]
**Describe the bug**

In previous versions the variable name in the functions' mutator flyout would update so that you couldn't get duplicate variable names. This is no longer working:
![BadMutator](https://user-images.githubusercontent.com/25440652/101262129-2161ae00-36f1-11eb-8a69-53f8d6ad1cec.gif)
I think this is related to the new events? But that's just an instinct, I'm not sure.

**To Reproduce**

1. Add a function definition block to the workspace (either type).
2. Drag parameters into the workspace.
3. Observe how the flyout does not update.

**Expected behavior**

The variable name should change as you add new blocks, going from x->z and a -> w

**Comment by alschmiedt** [comment]
Thanks for reporting!
I think you are correct, running a git bisect showed #4418 as the offending PR.

**Comment by alschmiedt** [comment]
The original PR this functionality was introduced in: #3527
