### ISSUE TITLE
Incorrect usage of goog.provide and goog.require statements

### ISSUE THREAD

**Issue by MarkusBordihn** [google/blockly#450]
As already mention in #366 there is a lot of incorrect usage of goog.provide and goog.require statements which make it hard to use these files directly in other closure based projects without any modifications.

Language Example:
Languages files under msg/js/... have an `goog.provide('Blockly.Msg.*');` which is never be used or has any usage at all.

The file which is included by `goog.require('Blockly.Msg');` use the `goog.getMsg` which is missing as required statement as well.

If you try to compile a single language file like 'blockly/msg/js/de.js' the compiler is not really able to understand the structure and the indention of the file and compilation will failed or the output includes definitions which are not really needed or wanted.

Again using the "precompiled" file works great for any projects which are not really using the closure compiler.
But for projects which are using the closure compiler this is an kind of blocker because they need to use work around.

**Comment by fly7632785** [comment]
@rachel-fenichel  ok

**Comment by samelhusseini** [comment]
This should be resolved with the removal of the closure library and the addition of the requires.js entry point.
