### ISSUE TITLE
Break/continue block does not react to movements of the parent block

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#4500]
**Describe the bug**

When you move the parent of a break/continue block, the block does not check if it is now inside/outside of a loop:
![BreakBlock](https://user-images.githubusercontent.com/25440652/101262379-1ad43600-36f3-11eb-8e06-69c3bce07327.gif)

Note: This repros on master.

**To Reproduce**

1. Add the break block, a loop block, and another block with a statement connection (eg controls_if) to your workspace.
2. Nest all of them together, with the loop block as the outer block.
3. Move the statement connection block inside and outside of the loop.
4. Observe how the break/continue block does not update.

**Expected behavior**

The break/continue block should update whenever it moves inside/outside of a loop.

**Additional information**
[EDIT: The same thing does not apply to the if-return block:]
![ReturnBlock](https://user-images.githubusercontent.com/25440652/101262458-c7aeb300-36f3-11eb-9e7d-df258ff08b95.gif)

**Comment by alschmiedt** [comment]
Thanks for reporting! 
It looks like the problem is with this [check](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/blocks/loops.js#L337). Since the parent block is the one getting dragged this part is failing.

**Comment by maribethb** [comment]
Fixed  by #4533.
