### ISSUE TITLE
Blockly playground doesn't work in iOS 12 

### ISSUE THREAD

**Issue by ajpal** [google/blockly#4510]
**Describe the bug**
Blockly workspace is not working in iOS 12. I repro this in the playground as well as in our application using the latest Blockly release.

**To Reproduce**

Open https://blockly-demo.appspot.com/static/tests/playground.html on a device running iOS 12
![image](https://user-images.githubusercontent.com/8787187/101524078-5151c100-393e-11eb-859d-7287f930f241.png)

**Expected behavior**
Expect to be able to drag/drop blocks, open the toolbox, scroll the workspace, etc
Observed: Unable to interact at all with the playground

**Screenshots**

**Desktop (please complete the following information):**
All devices running iOS 12

**Comment by alschmiedt** [comment]
Thanks for reporting!
I looked into this a bit today. I think the major problem is with the toolbox. When clicking on a category we are sometimes getting both a touchstart and mouse event in [onClick_](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/core/toolbox/toolbox.js#L255). For the touch start event [e.srcElement](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/core/toolbox/toolbox.js#L261) is undefined which is causing an error. I'll look into this more tomorrow and try to come up with a fix.

**Comment by alschmiedt** [comment]
@ajpal Just a heads up that the fix is hosted on http://google.github.io/blockly/tests/playground.html if you would like to do any more testing.
