### ISSUE TITLE
Make it easier to tell if a block or workspace comment is selected (Blockly.Events.Selected)

### ISSUE THREAD

**Issue by moniika** [google/blockly#4513]
**Is your feature request related to a problem? Please describe.**

The selected event does not include information on what kind of `ISelectable` element was selected (either `BlockSvg` or `WorkspaceCommentSvg`). Handlers of this event (when workspace comments are enabled) need to be able to tell how to use the provided id in the event.

**Describe the solution you'd like**

Add information to Selected event for easily determining what type of element is selected.

**Describe alternatives you've considered**

Use `getBlockById` to determine whether the id is a block id or workspace comment id and assume it's a workspace comment id if the return is `null`. 

**Additional context**

In Blockly Samples, our real-time-collaboration demo assumes that the Select event is always a block.

**Comment by rachel-fenichel** [comment]
Punting because we need to have a better definition of Selectable to avoid just having a list of possible types that we have to keep adding to.

**Comment by BeksOmega** [comment]
You should use a typeguard or an `instanceof` check when downcasting an interface.
