### ISSUE TITLE
Document using Blockly from npm

### ISSUE THREAD

**Issue by maribethb** [google/blockly#4514]
The Getting Started page only references cloning blockly from git. We should encourage developers to use the blockly npm package. https://developers.google.com/blockly/guides/get-started/web#get_the_code

**Comment by dellv305** [comment]
Hello!  My group and I are working on Blockly for our capstone project.  We would like to help with this issue.  We can write up information on npm as well as instructions for the user to install Blockly using it.  We appreciate any help and look forward to working on Blockly!

**Comment by GrantsGithub** [comment]
Hey dellv, my group is also working on documenting this. If you haven't started a google docs on it yet I can put a short one together on the steps and share it with you. The only snag we ran into was that when you npm install blockly there was no test folder so there was also no advanced playground to test the application on your personal machine. I've started looking into downloading github repositories from npm but that's as far as I've gotten.

**Comment by dellv305** [comment]
That's great.  We just made a Google doc this morning but don't have anything on it yet.  I can share it with you though.  We are still very early on.  What's your email?

**Comment by GrantsGithub** [comment]
My email is jacksonga@g.cofc.edu, and sounds great. I'll definitely add to it.

**Comment by BeksOmega** [comment]
Hey how would you peoples (@dellv305 @GrantsGithub) feel about sharing the WIP document it publicly? Maybe just with comment permissions if you don't feel comfortable handing out edit perms?

That way everyone who's interested will be able to participate, and it will be easier for you to get feedback from the core team in the future =)

Thank you for your interest in working on this by the way! More documentation on getting started is definitely something Blockly needs (especially as the library moves towards the plugin model) I think that your work on this will be awesome, and really helpful for future developers :D

**Comment by dellv305** [comment]
Most definitely! I've made it public with edit permissions. Here is the link: https://docs.google.com/document/d/10cRyLGgqZDZbbLHQYZz2y1KhVTrELlaq3L0DnFycuOg/edit?usp=sharing

Looking forward to working on it!

**Comment by BeksOmega** [comment]
> Most definitely! I've made it public with edit permissions. Here is the link: https://docs.google.com/document/d/10cRyLGgqZDZbbLHQYZz2y1KhVTrELlaq3L0DnFycuOg/edit?usp=sharing

Yay thank you so much! I'm excited to see how it goes hehe. If you peoples need anything, always feel free to ping =)

**Comment by maribethb** [comment]
Hey everyone, we're definitely glad to have some help with new and improved documentation. I just recently updated the Getting Started instructions to include some information about npm (and unpkg) but it's definitely not comprehensive for someone who hasn't used npm before, so it would be great to have a page specifically about setting up npm. 
The updated getting started page is here: https://developers.google.com/blockly/guides/get-started/web#get_the_code

The other things in particular I think we are still missing are
a) how to install and use plugins (there is nothing about this in the Plugins section of the docs, though the readme of each plugin does have some info)
b) how to access a test page / advanced playground / create a test page for your app

I think those would be good areas to focus on if you need some ideas about what to write, but we'd welcome any contribution you make! Thanks,
MB

**Comment by BeksOmega** [comment]
I was wondering (@ blockly team), is this documentation request for helping people get started developing /with/ Blockly? Or for helping people get started developing /for/ Blockly?

It looks like there's already a bit of information on the [Development Setup](https://developers.google.com/blockly/guides/modify/development_setup#step_by_step) page for how to get started contributing (although it's difficult to find). So are there extensions that need to made to that, or is it considered completed?

I just wanted to clarify since it looks like (although I could be wrong) developing /for/ Blockly is what the current doc is working on (which looks great so far by the way!) I just want to make sure no one is doing unnecessary work hehe

**Comment by dellv305** [comment]
Hey everybody, I believe that we have the documentation mostly finished.  How can we begin the process for submitting it?

**Comment by maribethb** [comment]
The documentation site is hosted internally, so we'll have to update it ourselves, but I'll review what you have and start the process. It looks like on the doc above, you have a separate document with the final content? If so, could you share it here? You can turn off editing permissions if you prefer, since we'll have to do editing internally anyway.

I missed your comment, Beka, but I think the answer is we could improve both! The development setup page is new but it's something I'd like to keep adding to and improving this year to make it easier for new folks to start contributing. And we also need to improve our documentation around developing with Blockly without forking the code, if we want people to stop forking it and start writing plugins :) 

Looking forward to reviewing what you have @dellv305 and improving our docs. Thanks!

**Comment by nixgc** [comment]
Hey everyone I've been working with @dellv305 on the documentation, this is the link to the final document for the documentation: https://docs.google.com/document/d/11LlnOLGIyjEHQogwNHQ6y3Z4zpxhbDHxpXWz4YvcHD8/edit?usp=sharing .

**Comment by maribethb** [comment]
Thanks for the doc, we really appreciate your contribution! I have a couple of notes:

* I currently have a change out for review that adds some information about installing plugins, and your steps listed out helped with that! I'll update this bug when that change is live. I also added some info about how the plugin versioning interacts with Blockly versioning, as well as how to install plugins without using npm (not in the scope of this bug, but we've gotten forum questions)
* Ideally, we want people to be able to fully use Blockly without having to clone the repository at all. Some of your instructions combine installing via npm and cloning the repo, which I suppose points to the need to make it more clear how to do everything without having to download the code. So I haven't fully used your steps, because I don't want to mix up the two methods.
* I had already updated the page about installing Blockly itself, I think while y'all were working on this document. That content is here: https://developers.google.com/blockly/guides/get-started/web#recommended_npm but let me know if you think this could be more clear. I think in general, our documentation assumes the reader is familiar with navigating the command line so we don't do things like explain `ls` or `cd`, but that could possibly be a better fit for a codelab.
* We still need information on accessing a test page without cloning the repo and using the built-in advanced playground. That could be as simple as pointing them to the info on injecting Blockly and telling them to go ahead and inject with the default options to get something going. But we also have the dev-tools package that could be used to inject an advanced playground, so we could have some instructions on using that package to create their own test page (that is, don't access the advanced playground that you have to clone blockly to get to under `blockly/tests/playgrounds/advanced_playground`, but create your own test page at `your_app/your_playground` using the published packages). Then we'd have to explain how to run a server for their app (probably using an npm script) and access said test page in the browser.
    * We already have the `create-package` script that we use for creating plugins. If you run that script, you automatically get a package.json that includes Blockly, an index page that injects the advanced playground, and an `npm run start` script that will start up the plugin and show the test page. It would be great if we could modify that to work for generic pages and not just plugins, so we would basically have the `create-react-app` script equivalent for Blockly. That is a bit beyond the scope of just documentation this bug is for, but it would be nice to have. Otherwise, I think we should at least describe how to create those things so that a user can install Blockly into their npm app, install the advanced playground into a test page, and access that page, all without ever having to clone the Blockly repo.

Hopefully that all made sense. If any of you are interested in making a PR to adapt the `create-package` script to work for a general case, that would be awesome, or otherwise if you have any other documentation suggestions we would love to see them.

(As a side note, I went to University of South Carolina, so we were basically neighbors, hi)

**Comment by BeksOmega** [comment]
This is fixed.
