### ISSUE TITLE
Event on changes inside statement inputs

### ISSUE THREAD

**Issue by 31piy** [google/blockly#4524]
**Is your feature request related to a problem? Please describe.**

A change event is emitted every time there is a field change inside a block. I've a use-case in which I want to detect changes inside a statement input of the block, i.e. whenever blocks are added to or removed from a statement input.

**Describe the solution you'd like**

A similar change event for the block which hosts the statement input. This would give a crisp and clear API to detect changes inside the statement input and act on those.

**Describe alternatives you've considered**

I've tried listening to workspace events. Every time a block is added to the statement input, a combination of block create and move events are fired. Similarly, every time a block is moved out of the statement input, a combination of block move events are fired. Currently, I'm trying with these combinations to detect changes inside statement inputs, but it doesn't seem like a full-proof solution.

**Comment by alschmiedt** [comment]
Hello! 
So I think the problem with this API is that it is for a very specific use case. We generally try to keep our events a bit more general so they can be used for multiple use cases. 

Would either of the following solutions work for your case?

If you only want to watch a certain type of block you can use [change listeners on the block level](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#change_listeners_and_validators).

Or if you want to watch any time a block is added or removed from any statement input you could use: 
```  
if (e.type === Blockly.Events.MOVE) {
    var workspace = Blockly.Workspace.getById(e.workspaceId);
    var input = null;
    var parentBlock = null;
    if (e.newParentId && e.newInputName) {
      parentBlock = workspace.getBlockById(e.newParentId);
      input = parentBlock.getInput(e.newInputName)
    } else if (e.oldParentId && e.oldInputName) {
      parentBlock = workspace.getBlockById(e.oldParentId);
      input = parentBlock.getInput(e.oldInputName)
    }
    if (input && input.type === Blockly.NEXT_STATEMENT) {
      console.log("A block has been disconnected or connected to a statement input");
    }
  }
```

**Comment by rachel-fenichel** [comment]
This issue asks for events that are more granular than the ones that we provide. As Abby said above, this can be done in the change listener and does not require API changes to Blockly. 

In general we do not want to add event types for information that can be derived from the existing events, due to maintenance overhead.
