### ISSUE TITLE
Update jsdom version

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4535]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Update jsdom dependency to the latest version. As of December 2020 we are one major version behind.

**Describe alternatives you've considered**

**Additional context**

**Comment by marsonya** [comment]
I would like to help with this task.
I basically gotta update the jsdom version and test the entire project. Right?
I am very new to Open Source Contributions.

**Comment by rachel-fenichel** [comment]
@marsonya Yes, that's what it would take. We know that right now tests fail when jsdom is updated, so you would have to figure out what change in jsdom broke our tests and what the upgrade path looks like.

(Sorry for the delay in responding--we were out for the holidays.)

**Comment by rachel-fenichel** [comment]
Update for @marsonya -- I just took a look and I have a PR up for this. Fixing it involved knowing how our serialization worked. However, if you want to grab another bug to work on, we have a help wanted tag on our issues that you can explore.

**Comment by marsonya** [comment]
Thanks for the update @rachel-fenichel. I will hunt down another issue 👍
