### ISSUE TITLE
Children of collapsed block are not enabled correctly

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4536]
**Describe the bug**

**To Reproduce**

1. Go to the playground
2. Import the below xml
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="controls_if" id="wR(irG/|K},+Wze3Hw?6" collapsed="true" disabled="true" x="63" y="113">
    <statement name="DO0">
      <block type="text_print" id="6ny1:?DW$Dj%#K8-9lmU">
        <value name="TEXT">
          <shadow type="text" id="ZlG;UbW;~uZu+Sy4:VB7">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
    </statement>
  </block>
</xml>
```
3. Enable the block
4. Expand the block
*Notice how the print block and shadow block on the repeat block are still disabled

**Expected behavior**
The shadow block and the print block should not be disabled.

**Screenshots**
<img width="204" alt="Screen Shot 2020-12-14 at 4 02 56 PM" src="https://user-images.githubusercontent.com/23059043/102150613-dd278980-3e25-11eb-9c7a-911ff8b7080d.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**
This bug looks like it was introduced between the June and September release.

**Comment by alschmiedt** [comment]
Looks like this was introduced in: #4302. 

I haven't looked into it too much, but one potential solution is to call `updateDisabled` when a block is expanded.

**Comment by Sherlock2505** [comment]
Can I work on this?

**Comment by alschmiedt** [comment]
Hello!

Thanks for your interest and I am sorry for the delay in getting back to you. I was informed that this bug seems straight forward but in the past has had a lot of unexpected side effects. For that reason I would recommend you try looking through our other [help wanted bugs](https://github.com/google/blockly/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22).
