### ISSUE TITLE
Copying in Safari makes an error sound even if copy works

### ISSUE THREAD

**Issue by maribethb** [google/blockly#4537]
**Describe the bug**

You can copy and paste blocks using Command+C/V  on Mac. However, in Safari, copying is accompanied by an annoying system-level error sound. It still copies successfully and you can paste fine.

**To Reproduce**

1. Open a playground in Safari  on  Mac
2. Select a block
3. Command+C to copy it
4. Hear  the error sound
5. Command + V  to paste and see it worked fine

**Expected behavior**

No error sound.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Additional context**

This reproduces  in both blockly master and beta channels (not a regression)

This does not happen on Chrome on the same macOS device. I tried to search about t his issue and  found  people complaining aboutit  from a  consumer side, but  nothing about how  to prevent  it on the  developer side, so I'm not sure if  this is  even possible to fix.

**Comment by alschmiedt** [comment]
I tested a 2018 version of Blockly as well as previous versions of safari and it looks like in every situation the same error is present.

**Comment by rachel-fenichel** [comment]
Link to consumer-side complaints?

**Comment by gonfunko** [comment]
In current (14.1.1) Safari, I can repro this but the paste doesn't actually work. Copy/paste with Control C/V works fine, but Command C beeps and Command V does nothing.

**Comment by gonfunko** [comment]
Edit: I have an extension that prevents websites from hijacking these shortcuts :) Can now repro the behavior described (command c/v works, but c beeps), looking into this further.
