### ISSUE TITLE
Feature: block for create list from range

### ISSUE THREAD

**Issue by 4n70w4** [google/blockly#4539]
**Is your feature request related to a problem? Please describe.**

I have not found a block or combination of blocks to do this.

Example: create a list with values from 1 to 5: 1, 2, 3, 4, 5.
Example: create a list with values from 2019 to 2015: 2019, 2018, 2017, 2016, 2015.

Where 1 to 5 or 2019 to 2015 - dynamically from variables.

**Comment by 4n70w4** [comment]
Workaround:

![image](https://user-images.githubusercontent.com/38257723/102347845-0c6b0180-3fb2-11eb-828e-bdc134a9a80d.png)

Generated:

```php
$buffer = 2019;
for ($i = 2018; $i >= 2015; $i--) {
  $buffer = implode('', array($buffer,',',$i));
}
$eee = explode(',', $buffer);
```

But this code smell ((

**Comment by 4n70w4** [comment]
Okay, next workaround:

![image](https://user-images.githubusercontent.com/38257723/102348421-ee51d100-3fb2-11eb-81c2-98ad0adeb6e8.png)

Generated:

```php
function lists_set_last_item(&$list, $value) {
  $list[count($list) - 1] = $value;
}


for ($i = 2019; $i >= 2015; $i--) {
  lists_set_last_item($eee, $i);
}
```

Also code smell and result array starts with `-1`:
![image](https://user-images.githubusercontent.com/38257723/102348911-96679a00-3fb3-11eb-8f54-d83fec62e526.png)


It might be better to use a function like this:
https://www.php.net/manual/en/function.array-push.php

**Comment by alschmiedt** [comment]
Hello! 
The blocks that we provide are example blocks that people can use in their applications if they wish. These blocks are not an exhaustive list of all the blocks that could be useful. If you would like to make your own block for the functionality you described you can follow these [guides](https://developers.google.com/blockly/guides/create-custom-blocks/overview) and ask any questions you have on the [forum](https://groups.google.com/g/blockly).
