### ISSUE TITLE
Travis not properly reporting typing errors

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4546]
**Describe the bug**
A bug was introduced into core when we removed a folder under core without removing it from the [typings script](https://github.com/google/blockly/blob/85874cd6962d6baf81c806a190a05be0b45f2838/scripts/gulpfiles/typings.js#L27). The travis build did not catch this, and instead reported it was passing.

On top of this there were folders that were not added to this script and so the typings in these folders were not being checked.

**To Reproduce**
1. Add a folder that does not exist into core.
2. Open a PR
2. Travis does not fail.

**Expected behavior**
Travis should fail.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

**Additional context**
One option for the second part of this bug is to have the script check all child directories of core. This would mean that we wouldn't have to worry about manually adding them whenever we add a new folder.

**Comment by moniika** [comment]
Fixed in #4721
