### ISSUE TITLE
goog.inherits in custom fields documentation

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#4559]
**Where**

1) At the bottom of the [implementing a constructor](https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/creating#implementing_a_constructor) code sample.
2) At the bottom of the [subclassing](https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/extending?hl=en#subclassing) code sample.

**What**

  
- [X] Text (Code)
- [ ] Image or Gif
- [ ] Other

**Old content**

`goog.inherits`

**Suggested content**

`Blockly.utils.object.inherits`

**Additional context**

Currently the linked code samples show using `goog.inherits` for inheritance, when they should use `Blockly.utils.object.inherits` (since Blockly moved away from closure).

**Comment by rachel-fenichel** [comment]
Done.
