### ISSUE TITLE
Allow right click of context menu

### ISSUE THREAD

**Issue by cpseager** [google/blockly#456]
Many younger children often struggle with the right-click left-click sequence that is currently required when using a context menu. They tend to instinctively use two right clicks instead.

Many applications (e.g. the windows versions of Chrome and Firefox browsers) support this by allowing either a left click or a right click whilst on a context menu. It would improve accessibility of Blockly (& scratch-blocks) if it did the same. Thanks!

**Comment by NeilFraser** [comment]
Good call.  Fixed in develop branch.
