### ISSUE TITLE
Advanced Playground and Test Blocks toolbox hosted on appengine do not load

### ISSUE THREAD

**Issue by moniika** [google/blockly#4567]
**Describe the bug**
The block test toolbox (on the playground) and advanced playground rely on having run `npm install` in order to load. When opening either of these on apengine hosted demo site, they do not load and emit the alert "You need to run 'npm install' in order to use the test blocks." or "You need to run 'npm install' in order to use this playground.".

**To Reproduce**

Go to either:
- https://blockly-demo.appspot.com/static/tests/playground.html?dir=ltr&toolbox=test-blocks
- https://blockly-demo.appspot.com/static/tests/playgrounds/advanced_playground.html

**Expected behavior**

The advanced playground should not be uploaded to appengine.
The playground should either not be uploaded to appengine or the test toolbox should not be allowed to be selected from the dropdown of toolboxes (this second option could be tricky and would be best if it only affected appengine hosted instances of the page).

**Additional context**

We already use github.io for testing on playground and the playgrounds do not seem linked in the index page, so not uploading them to appengine entirely seems like the most straightforward option.

**Comment by alschmiedt** [comment]
Alternatives to removing it are: 
1. Upload the node module needed for block tests.
2. Include the script tag for test blocks and try to load that way before trying to load from node_modules.
I think 1 might be the easiest solution.

**Comment by samelhusseini** [comment]
Remaining tasks: 
- [ ] Retrieve package.json from HEAD
- [ ] Don't rely on local node_modules for playground files, instead fetch them from unpkg.
