### ISSUE TITLE
How to correctly resize a block?

### ISSUE THREAD

**Issue by RomuloPBenedetti** [google/blockly#457]
I want to resize a block with a Image field but at the moment the update only happen if I move the block, at the moment I'm doing:

    field.height_ = Number(height);
    field.width_ = Number(width);
    field.size_ = new goog.math.Size(width, height + 2 * Blockly.BlockSvg.INLINE_PADDING_Y);
    field.imageElement_ = Blockly.createSvgElement('image', {'height': height + 'px', 'width': width + 'px'}, field.fieldGroup_);
    field.setValue(src);

but I only get this:

![blah3](https://cloud.githubusercontent.com/assets/12467382/16356101/333f9f46-3aa3-11e6-95b5-97f161d601a7.png)

And after moving it:

![blah3](https://cloud.githubusercontent.com/assets/12467382/16356102/5afd7e04-3aa3-11e6-9e18-0f2b81616102.png)

**Comment by RomuloPBenedetti** [comment]
Ok I've looked closer to the core classes and I've found a sane way to update my block, please let me know if there exist a more "orthodox" way of updating a block.

What I

**Comment by rachel-fenichel** [comment]
Hi @RomuloPBenedetti ,

Please consider mailing the [blockly google group](https://groups.google.com/forum/#!forum/blockly) with questions like this. There's a lot of aggregated experience developing with blockly over there.
