### ISSUE TITLE
Allow the workspace to be panned when a block is dragged near the edge

### ISSUE THREAD

**Issue by maribethb** [google/blockly#4570]
If a block is being dragged near/to the edge of the workspace, the workspace could pan/scroll in that direction.
This might be better as a plugin, but either way there may be changes needed in core to support that.

**Additional context**

code.org has implemented this in their fork. also, Monica notes "In our WorkspaceSearch plugin we have an implementation called scrollToVisible_ that scrolls the workspace to bring the specified block into view that we could port to core and reuse for this purpose."

This was mentioned elsewhere eg https://github.com/google/blockly/issues/2205#issuecomment-457748408

**Comment by moniika** [comment]
Is this part of core changes needed to enable https://github.com/google/blockly-samples/issues/372?

**Comment by maribethb** [comment]
Yeah, there are some changes needed in core to support the plugin so this issue is for those changes.
