### ISSUE TITLE
Block.interpolate_ calls the FieldLabel constructor directly instead of through the registry

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#4575]
**Describe the bug**

The `interpolate_` function in block.js [calls](https://github.com/google/blockly/blob/master/core/block.js#L1684) `new Blockly.FieldLabel(element)` instead of using `Blockly.FieldRegistry.fromJson.

All other fields are created through the registry.

This is only in the case where there is a bare string in the block definition, which is then interpreted as a label.

For consistency, and in case someone provides their own implementation of field label, we should use the registry.

Found by looking at missing requires.

**Expected behavior**

All fields are instantiated through the registry.

**Additional context**

Desired fix: call `fieldRegistry.fromJson`, passing in an object that has the correct information. I think it would need to have the contents of `element` as `'text'` and `'label'` as `'type'`.

**Comment by BeksOmega** [comment]
I can grab this =) And I'll write some tests for the interpolate_ while I'm at it.
