### ISSUE TITLE
Add support for generating C code

### ISSUE THREAD

**Issue by kmckee** [google/blockly#458]
I'm interested in using this to teach kids about C.  It would be great if C was one of the supported languages.

**Comment by NeilFraser** [comment]
C is a typed language (variables need to be declared as int, or float, or char), and as such it is difficult to generate C from Blockly.  However, we are actively working on adding support for typed variables, which will eventually enable us to support typed languages.  This will take some time though.

The main tracker for this is issue #446.

**Comment by tellts** [comment]
Hello. I found this development. But I don't know what the commands in the default block mean.
https://cra16.github.io/cake-core/index.html
Also I found another project. Only there I did not find the possibility of requesting a text from the user and printing a response. It would be nice if someone could modify this project to be able to make interactive dialogues.
https://github.com/admitrievsky/blockduino/blob/master/README.md

**Comment by tellts** [comment]
You may also be interested in another similar project.
https://github.com/dineshLL/lisa
