### ISSUE TITLE
Update Blockly.inject type for JSON toolbox in 

### ISSUE THREAD

**Issue by auginator** [google/blockly#4587]
I believe I found an issue with the TS types on the `Blockly.inject` method. It does not take into account the JSON toolbox option from the September release (https://github.com/google/blockly/releases/tag/3.20200924.0).

 I believe that the type here: https://github.com/google/blockly/blob/edd475f37b02888819b87ddfca1d6eeebe68898a/typings/blockly.d.ts#L17
 should be something like `toolbox?: HTMLElement | string | Blockly.utils.toolbox.ToolboxInfo;`, since the function supports passing in the JSON definition directly.

**Comment by alschmiedt** [comment]
Fixed.
