### ISSUE TITLE
Getters for copy information

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4600]
**Is your feature request related to a problem? Please describe.**
In the keyboard navigation demo I override the default paste functionality so I can paste the copied block to the current location of the cursor. In order to do this I need to use know what block was copied and from what workspace. This requires using `Blockly.clipboardSource_` and `Blockly.clipboardXml_`.

**Describe the solution you'd like**
Getters for these fields. 

**Describe alternatives you've considered**
Making the fields public. I'm not sure this is necessary. Since we have `Blockly.copy`, I don't see a reason why someone would want to set these fields manually.

**Additional context**

**Comment by George-the-1st** [comment]
I should be mentioning that I'm almost finished with this issue.

**Comment by cpcallen** [comment]
Closed by #5237.
