### ISSUE TITLE
Toolbox separator between blocks

### ISSUE THREAD

**Issue by hugoruscitti** [google/blockly#463]
Hi, i have an issue when i want to create a separation between blocks in the toolbar, i have a simple toolbar with a separation tag that blockly ignore:

![ember-blockly 2016-06-30 15-24-10](https://cloud.githubusercontent.com/assets/99183/16499443/e81d543a-3ed6-11e6-8707-f2f134b54383.png)

but in the documentation seems to be valid that code: https://developers.google.com/blockly/guides/configure/web/toolbox#separators

What am I doing wrong?

Thanks

**Comment by RoboErikG** [comment]
Hi Hugo,

Are you saying the gap isn't working or there's no line being drawn between
them? If the first, that's a bug and please file it to the issue tracker.
If the second, we have no code to draw a line or other UI element as a
separator between blocks, that tag only controls the spacing between
blocks. We haven't had a use case for such a UI element before (we do make
use of the one between labels in the list of categories). Please file a
feature request on the issue tracker if you have a good use case for it.

On Thu, Jun 30, 2016 at 11:29 AM, Hugo Ruscitti <notifications@github.com>
wrote:

> Hi, i have an issue when i want to create a separation between blocks in
> the toolbar, i have a simple toolbar with a separation tag that blockly
> ignore:
>
> [image: ember-blockly 2016-06-30 15-24-10]
> <https://cloud.githubusercontent.com/assets/99183/16499443/e81d543a-3ed6-11e6-8707-f2f134b54383.png>
>
> but in the documentation seems to be valid that code:
> https://developers.google.com/blockly/guides/configure/web/toolbox#separators
>
> What am I doing wrong?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/blockly/issues/463>, or mute the thread
> <https://github.com/notifications/unsubscribe/AKjbp0D66BbFCQiKeJ-weVtpDhuO9bp0ks5qRAsdgaJpZM4JCcq8>
> .
>



-- 
Erik Pasternak | Master of the House | epastern@google.com

**Comment by hugoruscitti** [comment]
Hi @RoboErikG, i think the gap isn't working between blocks. I can't reproduce this simple documentation behavior on master branch:

![toolbox blockly google developers 2016-06-30 15-46-43](https://cloud.githubusercontent.com/assets/99183/16500175/ebd0c1ea-3ed9-11e6-8f68-ad46de6f9238.png)

https://developers.google.com/blockly/guides/configure/web/toolbox#separators

**Comment by rachel-fenichel** [comment]
Definitely a bug, though this is only a problem on simple (no category) toolboxes.  

Thanks for pointing this out!

**Comment by rachel-fenichel** [comment]
Closed by #531
