### ISSUE TITLE
Block moves erratically when dragged a small amount

### ISSUE THREAD

**Issue by ajpal** [google/blockly#4636]
**Describe the bug**

Sometimes when I drag a block a small amount, it jumps erratically. I think this has to do with a weird interaction between the block drag surface and the workspace drag surface.

**To Reproduce**
1. Open the Playground
2. Drag a block to roughly the middle of the space
3. Scroll the workspace so that the block is in the top left corner of the workspace
4. Drag the block a small amount and release

**Expected behavior**

Expected: the block should stay where I release it.
Observed: the block jumps a seemingly random distance towards the center of the workspace.

**Screenshots**
![Feb-16-2021 10-26-21](https://user-images.githubusercontent.com/8787187/108105443-79962400-7041-11eb-8ce2-01553c50fc1f.gif)

**Desktop (please complete the following information):**
 - OS: Mac Mojave
 - Browser: Chrome
 - Version 88

**Stack Traces**
No errors

**Additional context**

**Comment by alschmiedt** [comment]
Just as an update, we (mostly monica) narrowed this down to a bug in `getBlocksBoundingBox`. It currently includes insertion markers when calculating the bounding box, which is causing the bug. If you want to test your feature without this bug interfering the quick fix is to add the following check before [this line of code](https://github.com/google/blockly/blob/d7e9eaff0fd533e8bfda905c8eb02a16722af89d/core/workspace_svg.js#L1701).

`if (!topElements[i].isInsertionMarker()) {}`
