### ISSUE TITLE
Can I get a copy event listener and get the copied target block

### ISSUE THREAD

**Issue by AtonalStar** [google/blockly#4640]
I want to copy a certain block and paste it to another workspace. 

Currently I can listen to an "click" event and save the block's xml to localStorage, but I need a way to listen the copy event. 
```javascript
  workspace.addChangeListener(onClick)

  function onClick(e){
    if(e.type === Blockly.Events.UI && e.element === "click"){
        const block = workspace.getBlockById(e.blockId)
        const blockXML = Blockly.Xml.blockToDom(block)
        const blockText = Blockly.Xml.domToText(blockXML)
        localStorage.setItem("copyblock", blockText)
    }
  } 
```
Can I have a Blockly.Events.UI element for "copy"?
Or is there other way to get the copied block xml?

**Comment by maribethb** [comment]
Hi, we don't have a copy event, or plans to add one at the moment. You can still implement this feature, by defining your own copy function and overriding both the keyboard shortcut and the context menu items. There are examples of overriding the keyboard shortcut here: https://github.com/google/blockly-samples/blob/610fa5ff5054101de689790d7cdebc83c1bd2b61/plugins/keyboard-navigation/src/navigation_controller.js#L697 to add custom copy behavior. And there is documentation on the context menu here: https://developers.google.com/blockly/guides/configure/web/context-menus including a link to a codelab.

If you need more help implementing this, please post a message on our developer forum: https://groups.google.com/g/blockly and someone will be able to better assist you there. Thanks!
