### ISSUE TITLE
Add support for generating Ruby code

### ISSUE THREAD

**Issue by dayvsonlima** [google/blockly#465]

**Comment by NeilFraser** [comment]
We have no plans to create a full set of generators for any additional languages.  However we are happy to support contributions of new generators that pass all the existing unit tests.  Python, PHP, Lua, and Dart were all contributions that we continue to maintain.

Feel free to contribute a set of Ruby generators.

**Comment by kbrock** [comment]
@NeilFraser thank you

**Comment by hamirmahal** [comment]
For contributors who want to add a generator for a new language, not necessarily Ruby, what things would they need to do?

I just opened an issue for this, #5933, to keep things organized.
