### ISSUE TITLE
Flyout contains little top padding

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#4655]
**Describe the bug**

The toolbox flyout has no top padding as it used to.
Currently only affecting develop.

**To Reproduce**

1. Go to the Playground
2. Open any toolbox category
3. Notice how there isn't any top padding as there used to be.

**Expected behavior**

see https://google.github.io/blockly/tests/playground.html

**Screenshots**
<img width="331" alt="Screen Shot 2021-02-25 at 1 06 27 AM" src="https://user-images.githubusercontent.com/16690124/109129935-073ed700-7706-11eb-9d49-1f8b7828ae15.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by alschmiedt** [comment]
This was introduced in #4643.
