### ISSUE TITLE
Events for variables

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#468]
Variable creation/deletion/renaming does not have events (in the new variable management scheme).  Events are necessary for undo/redo.

**Comment by rachel-fenichel** [comment]
#446

**Comment by marisaleung** [comment]
Variable events created here: https://github.com/google/blockly/commit/e9a480c51f593797154971db54428f3f5869ba3e
 Variable events fired here: https://github.com/google/blockly/commit/833c2d0c40b9eb1978678384d161a09fdb5cd683
