### ISSUE TITLE
Document XML Specification

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#4683]
**Where**

A page that details how to construct connected blocks using XML. For example, it should go over next nodes, value nodes, statement nodes, field nodes, etc. It would also be good to include info about how you can connect blocks using the UI and then serialize the workspace to get the correct XML.

This is helpful for people who want to add pre-set groups of blocks to their toolbox, or to the workspace on start up. I was helping someone with this recently (not on the mailing list) and they mentioned it might be helpful to have some documentation.

**What**

  
- [X] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

There's some information in the [Toolbox](https://developers.google.com/blockly/guides/configure/web/toolbox#preset_blocks) documentation, but not a lot.

**Suggested content**

Should include descriptions of:
* How to generate the correct xml using blockly's UI
  * Explanation of steps
  * Explanation of why this works? (eg all xml, toolbox, workspace, is treated the same way)
  * console.log(Blockly.Xml.workspaceToDom(workspace))
* How to connect blocks
  * next XML nodes
  * value XML nodes
  * statement XML nodes
  * Shadow XML nodes
* Block node attributes
  * deletable
  * movable
  * editable
  * enabled
  * collapsed
  * inputs inline
* How to set field values
  * This should also link/point to the individual serialization sections in the fields documentation. For example [dropdown serialization](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/dropdown#serialization_and_xml). It doesn't necessary need to link to each section individually, but this should provide enough guidance so people can find the info they need.
* How to set mutator values
  * Reference how it depends on the particular mutator
  * IMPORTANT: Should note that mutation XML should always be the first child of the block node (before any other nodes including field nodes or connection nodes). This is because those fields/connections may not exist until the mutator is run.

Note that the above order probably isn't good. This is just a brain dump of things I think would be good to mention.

Links:
  * Link to this doc from the [toolbox](https://developers.google.com/blockly/guides/configure/web/toolbox) doc
  * Link to it from the [configuration paradigm](https://developers.google.com/blockly/guides/create-custom-blocks/block-paradigms) doc.
  * Link to it from the serialization doc if it exists? (related: is there serialization documentation? closest I could find was [cloud storage](https://developers.google.com/blockly/guides/configure/web/cloud-storage))

**Additional context**

N/A

**Comment by NeilFraser** [comment]
Related, Blockly XML has an [XSD file](https://github.com/google/blockly/blob/master/tests/xml) (whatever that is -- apparently I wrote it).

**Comment by rachel-fenichel** [comment]
This could be a good topic for a codelab. It wouldn't cover all of those, but would be a good format for stepping through and explaining both the what and the why.

**Comment by vihangkale** [comment]
Thanks Beka for raising the issue for the documentation and for the efforts. In some examples like these [https://github.com/google/blockly/tree/master/demos/interpreter](url) and [https://github.com/google/blockly/blob/d7e9eaff0fd533e8bfda905c8eb02a16722af89d/demos/interpreter/step-execution.html#L100](url) there are predefined and  preconnected blocks which has <next> tag which connects the block to the next block which has a next statement and previous statement defined as true.It will be better if your team can create a good documention regarding these examples and tags in it.

**Comment by BeksOmega** [comment]
> This could be a good topic for a codelab. It wouldn't cover all of those, but would be a good format for stepping through and explaining both the what and the why.

I see what you're saying about it being a good format for stepping through each section, but this doesn't really feel like a codelab to me. In my mind, codelabs are more like tutorials. It seems like they're geared towards subjects where if you go through certain steps in order, by the end of the codelab you've built a cool thing (like a renderer, generator, etc). The issue above doesn't feel like that to me.

Creating docs has some other advantages as well; for example, the docs are more searchable, and it's easier to create deep links. The docs' search bar is works really well because it can find keywords inside pages, while the codelabs search only looks at titles. The headings on the docs site also (usually) have ids, while codelab ones don't seem to - only steps have IDs. This means that on the docs site you can link a lot closer to exactly what you're talking about. So, for example, if someone on the forum need info specifically about `<next>` tags, I could just do a search, and then directly link them to the section that talks about those tags.

But this may just be my docs-bias talking. I love codelabs and tutorials, but I think docs/source code will always be my thing haha. In the end any way to get the info out is a good way :D

**Comment by George-the-1st** [comment]
This should be a good start for this. I've gone through every node and mapped what values are present for each and gave some rough outline information for how to use block text to nest blocks inside each other with XML to achieve the result through this markup language. Full disclosure, this is my first time working with XML markup language. Please don't laugh TOO hard. In all seriousness, I hope this work provides some added progress towards this. Lord knows I've put in more hours here then I thought I would. (https://drive.google.com/file/d/1hxTzg5EkqKxNltLQPekK7kcBLXygqG3z/view?usp=sharing).

**Comment by BeksOmega** [comment]
Going to close this now that XML is iceboxed.
