### ISSUE TITLE
Zoom reset not centering workspace

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4724]
**Describe the bug**
The reset zoom button does not center the workspace anymore.

**To Reproduce**

1. Go to https://google.github.io/blockly/tests/playground.html
2. Drag some blocks on to the workspace.
3. Move the workspace around.
4. Hit the reset zoom button
5. Notice how nothing happens.
**Expected behavior**
The workspace should center itself.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by moniika** [comment]
Fixed by #4725
