### ISSUE TITLE
Events documentation references old event names

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#4728]
**Where**

[Listening to events](https://developers.google.com/blockly/guides/configure/web/events#listening_to_events) and [Event types](https://developers.google.com/blockly/guides/configure/web/events#event_types)

**What**

  
- [X] Text
- [ ] Image or Gif
- [X] Other (Code)

**Old content**

Listening to events:
```
function onFirstComment(event) {
  if (event.type == Blockly.Events.CHANGE &&
      event.element == 'comment' &&
      !event.oldValue && event.newValue) {
    alert('Congratulations on creating your first comment!')
    workspace.removeChangeListener(onFirstComment);
  }
}
workspace.addChangeListener(onFirstComment);
```

Event Types:
> One of Blockly.Events.CREATE, Blockly.Events.DELETE, Blockly.Events.CHANGE, Blockly.Events.MOVE, etc.

**Suggested content**

Listening to events:
```
function onFirstComment(event) {
  if (event.type == Blockly.Events.BLOCK_CHANGE &&
      event.element == 'comment' &&
      !event.oldValue && event.newValue) {
    alert('Congratulations on creating your first comment!')
    workspace.removeChangeListener(onFirstComment);
  }
}
workspace.addChangeListener(onFirstComment);
```

Event Types:
> One of Blockly.Events.BLOCK_CREATE, Blockly.Events.BLOCK_DELETE, Blockly.Events.BLOCK_CHANGE, etc.

**Additional context**

N/A

**Comment by alschmiedt** [comment]
Done, this will get pushed when we release documentation for the new release tomorrow.

Thanks!
