### ISSUE TITLE
Click event should include access to thing being clicked

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#4729]
**Is your feature request related to a problem? Please describe.**

Recently there was a [person on the forums ](https://groups.google.com/g/blockly/c/7UJIdRpddBM)that wanted to trigger an alert when one of their custom blocks was clicked. I think that ideally you should be able to do this by listening to the click event. But currently it is not possible to check what block a click occured on (so their alert would trigger regardless of whether it was their custom block or a different block).

**Describe the solution you'd like**

Since `click` is a UI event which doesn't need to be serialized, I think the element being clicked (eg field, block, or workspace) should be passed along with the event.

**Describe alternatives you've considered**

Information to reference the element being clicked could be passed. Eg, the block ID and field name in the case of a field click.

**Additional context**

N/A

**Comment by moniika** [comment]
The Click event has the property `blockId` that can be used to access the block that is being clicked.
Does that solve the issue or is there something else that's missing?

**Comment by BeksOmega** [comment]
> The Click event has the property `blockId` that can be used to access the block that is being clicked.
> Does that solve the issue or is there something else that's missing?

Haha I totally forgot about the common event properties. I think that solves it! Thank you =)
