### ISSUE TITLE
Add an option allowing to select and drag multiple blocks at the same time

### ISSUE THREAD

**Issue by HollowMan6** [google/blockly#4739]
**Is your feature request related to a problem? Please describe.**

Can blockly add an option that allows to select and drag multiple blocks at the same time? Now it's frustrating to only drag and drop the blocks one by one when I want to move a batch of blocks from one place to another to make it looks tidy, or when I want to delete them in batch. 

**Describe the solution you'd like**

Add an option to select and drag multiple blocks. When users press Shift key for example, users are allowed to select multiple blocks by clicking them. Then when the key is released, users can drag and move them. This is pretty much alike of selecting and dragging files on OS like Windows, Mac, etc.

**Describe alternatives you've considered**

I've tried using DragSelect to select multiple blocks in blockly: https://github.com/ThibaultJanBeyer/DragSelect

```html
<script src="https://dragselect.com/v2/ds.min.js"></script>
```
```javascript
s = new DragSelect({ 
  selectedClass: "blocklySelected",
  selectables: document.querySelectorAll("g.blocklyBlockCanvas > g.blocklyDraggable"),
  area: document.querySelector('.blocklyWorkspace'),
  multiSelectMode: true,
  draggability: false
});
```

But I can't drag the selections after selecting. Everytime I do this, only one block is dragged instead of a batch. I guess it's because of the event listener conflict.

So making that library work in blockly is also a feasible solution.

**Additional context**

Not applicable.

**Comment by rachel-fenichel** [comment]
This is best built as a plugin, and we have an issue for that on our other repository: https://github.com/google/blockly-samples/issues/267
