### ISSUE TITLE
JavaScript APIs

### ISSUE THREAD

**Issue by anonimo82** [google/blockly#4749]
**Is your feature request related to a problem? Please describe.**
No, it's not

**Describe the solution you'd like**
I'd like to script a WebPage without writing code, so I'd need to have access to all the JavaScript APIs in it
In example, I'd like to script a Canvas element with Blockly alone (but not limited to Canvas)

**Describe alternatives you've considered**
None yet

**Additional context**
Nothing

**Comment by yukiya383** [comment]
Blockly-core(this library) includes only limited blocks that are independent of language.
If you want blocks only for JavaScript such as Canvas API, I think it's better to **file feature request to blockly-samples**, where plugins to extend bockly-core are developed.
See detail [here](https://developers.google.com/blockly/guides/modify/contribute/write_a_good_issue#feature-request).

**Comment by anonimo82** [comment]
Cool, I didn't knew that.
Thanks a lot.
