### ISSUE TITLE
Cron job to delete expired data in appengine demos

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#4751]
**Is your feature request related to a problem? Please describe.**

Our data retention policy is to delete saved data from our appengine demos after one year without access.

We have the [code](https://github.com/google/blockly/blob/master/appengine/expiration.py) to do the expiration, but need to enable it to run.

This is not yet urgent because it's been less than a year since we added timestamps to all saved data.

**Describe the solution you'd like**

A cron job to run expiration.py

**Additional context**

**Comment by maribethb** [comment]
I created a cron job to run the script weekly. This can be managed through Cloud Scheduler in our project's GCP dashboard.
