### ISSUE TITLE
Why doesn't code generator give priority to Java

### ISSUE THREAD

**Issue by PaulMing** [google/blockly#4794]
Code generator does not give priority to Java language，but Java application scenarios are very wide
Can you tell us the reason for the generator language selection ?

How to better extend generator code language, now need to use Java，the extension cost is very high, the front-end developers have high requirements，It's difficult, it's distressing

**Comment by alschmiedt** [comment]
Hello!

I think the biggest reason is that Java is a strongly typed language and Blockly's built in type checker makes implementing strongly typed languages difficult. There is an [issue](https://github.com/google/blockly-samples/issues/346) on blockly samples to create a nominal type checker that would make creating a generator for strongly typed languages easier.

That being said people have still attempted to create Java generators. If you search the [forum](https://groups.google.com/g/blockly?pli=1), there are a few projects people have been working on that might be helpful. This [posts](https://groups.google.com/g/blockly/c/oy6NhQHssCQ) is a bit old, but might lead you in the correct direction.

If you would like to open a [feature request](https://github.com/google/blockly-samples/issues), feel free to do so in the blockly sample repo as this would make a good plugin.

In the future please ask any questions on the [forum](https://groups.google.com/g/blockly?pli=1). This will allow other developers a chance to answer question and give opinions.

Thanks!
