### ISSUE TITLE
<button></button> not working with  "kind": "categoryToolbox"

### ISSUE THREAD

**Issue by jsccjj** [google/blockly#4797]
Hello,

According to "https://developers.google.com/blockly/guides/configure/web/toolbox#buttons_and_labels"
One may be able to put a button or label anywhere you can put a block in the toolbox.

It seems that "the toolbox" is "flyoutToolbox". It also seems that "categoryToolbox" may not fit.

**When**

when defining the "button" along with categories 
![image](https://user-images.githubusercontent.com/79299554/115940383-39df2480-a456-11eb-9330-756718e38de2.png)

<br>
The "button" would not show and the console would return a warning:
![image](https://user-images.githubusercontent.com/79299554/115940242-a574c200-a455-11eb-94e5-91b648278988.png)
<br>

**Where**

"https://developers.google.com/blockly/guides/configure/web/toolbox#buttons_and_labels"

**What**

  
- [x ] Text
- [ ] Image or Gif
- [ ] Other

**Old content**
"You can put a button or label anywhere you can put a block in the toolbox."

**Suggested content**
You can put a button or label anywhere you can put a block in the toolbox other than "categoryToolbox".

**Additional context**

**Comment by alschmiedt** [comment]
Thanks for the issue! So, I think that statement is correct in this situation. You can not place a block at the same level as a category and therefore can not place a button or label there as well. However, looking at the docs we aren't entirely clear on where a block can go. Would it have been helpful to add some information to the [categories section](https://developers.google.com/blockly/guides/configure/web/toolbox#categories) about what a category can hold? Or is there another place that would have made this easier to understand?

**Comment by jsccjj** [comment]
Hello! Thanks for the response. I would say that a table explaining what blocks/categories can be added to what kind of category /toolbox (category vs categoryToolbox vs flyoutToolbox....). Thanks

**Comment by rachel-fenichel** [comment]
For the initial issue, the documentation is accurate: you cannot put a button at the top level with the toolbox categories, and you also can't put a block there. The documentation says that "You can put a button or label anywhere you can put a block in the toolbox." Developers also get warnings if they mis-define their toolboxes.

For why a button should not be put in a category toolbox: the toolbox is designed to hold blocks and categorize them. Buttons are necessary for in-context actions like creating new variables. But in general, actions like exporting the generated code should be part of your wrapper application. That also lets you style the buttons to match your application.
