### ISSUE TITLE
Blockly.Names.equal with called with null arguments

### ISSUE THREAD

**Issue by pn1k** [google/blockly#48]
Sometimes Blockly.Named.equal called with null or undefined arguments. 

This patch fix this issue:
Blockly.Names.equals = function(name1, name2) {
-  return name1.toLowerCase() == name2.toLowerCase();
+  return (name1 || '').toLowerCase() == (name2 || '').toLowerCase();
};

**Comment by NeilFraser** [comment]
While this patch will definitely squelch the error, I'd really be interested in knowing the scenario that causes this error in the first place.  Is it repeatable?

**Comment by pn1k** [comment]
Sorry for a long delay of my answer.

Neil Fraser пишет:
> While this patch will definitely squelch the error, I'd really be 
> interested in knowing the scenario that causes this error in the first 
> place. Is it repeatable?
This "bug" happened sometimes when I adopted blockly-lua https://github.com/espertus/blockly-lua
code to run with new version of blockly. For now, I can't remember how to reproduce this bug.

I'll try to remove my patch from blockly's code whitch I'm using in my project to get this bug again
and try to reproduce it.

**Comment by NeilFraser** [comment]
Sounds like it might be a bug in Blockly Lua.  Closing the issue here.
