### ISSUE TITLE
Add descriptions to devsite pages

### ISSUE THREAD

**Issue by maribethb** [google/blockly#4808]
**Where**

Every page on https://developers.google.com/blockly/guides/overview

**What**

There's a feature on devsite now where it suggests related articles. However, for every article, it has the same description: "Visual programming editor. Drag and drop blocks to generate executable..." which is not super useful.

![image](https://user-images.githubusercontent.com/8573958/117219074-59ad0b80-adb9-11eb-8b53-c128b8819d4a.png)

Best guess, if we provide the description metadata for each page, it would show that there instead. Hopefully.

https://developers.google.com/devsite/reference/metadata/page#page_description

**Comment by gonfunko** [comment]
Closing since the "Others also read" section appears to have been removed.
