### ISSUE TITLE
Support custom xml in flyout definition

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4809]
**Is your feature request related to a problem? Please describe.**
https://groups.google.com/g/blockly/c/HjY_KHA8680/m/ojqDWbgyBAAJ

It looks like there are a few places that a user would want to keep the xml from the toolbox definition instead of having us try to convert it into JSON.

**Describe the solution you'd like**
Add a way for developers to add certain names that they would want to keep in xml format instead of trying to convert to JSON. 
Something like:
```
Blockly.utils.toolbox.addExceptions('tagName');
```
And then in [xmlToJsonArray_](https://github.com/google/blockly/blob/master/core/utils/toolbox.js) we could check the array holding the name before trying to convert to JSON. 

```
if (exceptionArray.includes(tagName)) {
    obj["xml"] = child
}
```

**Describe alternatives you've considered**
Without any changes I think the user could do something like: 

```
<customElement customXml='<></>'></customElement>

Blockly.Xml.textToDom(object.customXml);
```
However, this is a pretty roundabout way to do what they are trying to. This also requires a call to `textToDom` which is better to avoid if possible.

**Additional context**

**Comment by gonfunko** [comment]
Closing as obsolete. We're not actively making changes to the XML system at this point, and the issue referenced on the forum would be (much!) better solved using the flyout inflater APIs coming in v12.
