### ISSUE TITLE
Compatibility blockly with Franka version 4.1+

### ISSUE THREAD

**Issue by GuiiBru** [google/blockly#4810]
We use blockly with the Franka Emika robot in an old version. And we would like to know if blockly is compatible with the latest Franka version: Version 4.1+ 2021-01-26 (https://support.franka.de/)?

**Comment by alschmiedt** [comment]
Hello!

Sorry for the delay in getting back to you. Unfortunately, I don't have anything super helpful to say. Blockly is a JavaScript library that can generate different javascript, lua, php, python or dart from blocks. We do not offer applications for any specific robot or platform. I think it would probably be most helpful to reach out to the robotics company to see if they offer a Blockly app.

If you have more questions feel free to ask on the [blockly forum](https://groups.google.com/g/blockly?pli=1) as there are more developers with a broader ranger of knowledge that might be able help : )
