### ISSUE TITLE
Define procedures interfaces

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#4829]
There is currently a typedef `Blockly.Procedures.ProcedureBlock` that says that the object has `getProcedureCall`, `renameProcedure`, and `getProcedureDef`.

Three questions:
- Should this be an interface instead of a typedef?
  - The ways that we construct blocks doesn't allow for the interface annotation on the block definition to be reflected in the uses of that block, so we need to cast in any case. So a typedef may be more accurate.
 - Should it actually be two typedefs?
   - `ProcedureDef` and `ProcedureCall`
- Should it/they be on the `Blockly.Procedures` namespace, or somewhere else?

Related to #4798

**Comment by BeksOmega** [comment]
Closed by #6745
