### ISSUE TITLE
sounds option not document

### ISSUE THREAD

**Issue by pelikhan** [google/blockly#4848]
This option https://github.com/google/blockly/blob/3fe56b083c62549cb2bdb17270846bf17ced5d7a/core/options.js#L69 seems to be missing from https://developers.google.com/blockly/guides/configure/web/configuration_struct

**Comment by pizzaz93** [comment]
![Sounds](https://user-images.githubusercontent.com/10904763/167505491-906d0298-a3fc-41f3-918c-6c9d6e645d88.png) It appears `sounds` is currently documented.

**Comment by BeksOmega** [comment]
You are correct! Thank you @pizzaz93 =)
