### ISSUE TITLE
Even the demos/fixed/index.html is not working

### ISSUE THREAD

**Issue by johnnyxwan** [google/blockly#485]
Opening the demos/fixed/index.html in Chrome, the following error shows:
> blockly_compressed.js:993 Uncaught TypeError: goog.dom.createUntypedDom is not a function

**Comment by picklesrus** [comment]
Hmm, blockly_compressed.js doesn't seem to be updating properly. I'm digging into this. I have updated closure per https://github.com/google/blockly/pull/481 and the demos work okay with blockly_uncompressed so something fishy is going on.

**Comment by picklesrus** [comment]
Fixed in develop branch by #487

**Comment by picklesrus** [comment]
Note: You'll need to recompile though if we haven't submitted that yet: https://developers.google.com/blockly/guides/modify/web/building
