### ISSUE TITLE
dragging blocks out of flyout - mouse click/drag weirdness

### ISSUE THREAD

**Issue by yoderjen** [google/blockly#488]
I'm having trouble dragging blocks out of the flyout.  

positioning the mouse so that the flyout block is selected, left clicking, and dragging the block into the workspace usually works fine.

However, I am getting a lot of times when I try to click and drag a block into the workspace where it seems that the drag doesn't work (though the block does get created in the workspace directly beneath its location in the flyout).

I can reproduce the following case:  if you open a flyout, left click the mouse away from a block, move the mouse over a block so that it is selected, release the left mouse button, hold there as long as you like, left click the (still selected) block, and attempt to drag it into the workspace, the block is created in the workspace but it isn't dragged where you want it (it is created as if you'd merely clicked the block in the flyout instead of dragging it).

This doesn't cover all the cases I'm seeing but is one I can reproduce.  

This behaviour can be seen in the current Blockly Code demo.  It did not exist in my ancient (8 months old?) version of Blockly.

**Comment by rachel-fenichel** [comment]
Fixed by #478

Thanks for the report!
