### ISSUE TITLE
Refactor shared code between BlockDragger and BubbleDragger

### ISSUE THREAD

**Issue by moniika** [google/blockly#4882]
**Is your feature request related to a problem? Please describe.**
BlockDragger and BubbleDragger have a lot of shared code (near identical blocks of code) between the two,.

**Describe the solution you'd like**

A common parent class and the introduction of an `IDraggable` interface type.

**Describe alternatives you've considered**

A utility class that can be shared between the two.

**Additional context**

**Comment by gonfunko** [comment]
These classes no longer exist, and the code seems well split between Dragger, BlockDragStrategy and BubbleDragStrategy. Closing accordingly.
