### ISSUE TITLE
blockly_compressed.js: goog.dom.createUntypedDom is not a function

### ISSUE THREAD

**Issue by MarkusBordihn** [google/blockly#491]
Currently **blockly_compressed.js** is broken, because it uses "_goog.dom.createUntypedDom_" but this dependency was never provided.

Related to #366

**Comment by rachel-fenichel** [comment]
Yes, we've reverted the broken change on develop and we are working on reverting and rebuilding in master as well.

**Comment by picklesrus** [comment]
This should be fixed on both master and develop now. blockly_compressed.js has also been updated.
