### ISSUE TITLE
Escape no longer reverts field edits

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#4910]
Open this ancient version of Blockly:
  https://2-dot-blockly-games.appspot.com/turtle?level=10
Edit a number field, type in a big number, then press escape.
The number reverts to its original value.

Open any modern version of Blockly:
  https://blockly.games/turtle?level=10
Edit a number field, type in a big number, then press escape.
The number no longer reverts to its original value.

Same with text inputs.

**Comment by moniika** [comment]
I think this may have been caused by https://github.com/google/blockly/pull/4351
