### ISSUE TITLE
Flyouts do not recalculate delete area

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#4912]
**Describe the bug**

If you have a simple toolbox (ie just a flyout) you can modify the blocks within the flyout before dragging them out. When you modify the blocks, this can cause the size of the flyout to change. However, the delete area is still the old size.

**To Reproduce**

1. Go to the advanced playground and open the simple toolbox.
2. Drag any block out of the flyout.
3. Go down to the last block in the flyout and change the dropdown from "letter #" to "letter # from end" to make the flyout wider.
4. Drag the block you created back over the flyout, and observe how the delete area is still the old size.

Note: if you switch steps 2 and 3, it doesn't reproduce. No clue what's up with that.

**Expected behavior**

The delete area should update based on the size of the flyout.

**Screenshots**

![delete-area-old](https://user-images.githubusercontent.com/25440652/121970516-93afec80-cd2b-11eb-93fa-992705864f83.gif)

**Comment by moniika** [comment]
Drag target areas are re-calculated for calls to `WorkspaceSvg.prototype.recordDragTargets`. 
In this case, we would need to trigger re-calculating the drag targets when the flyout resizes with a call to `recordDragTargets`.
