### ISSUE TITLE
Non autoclosing flyouts do not update zoom level correctly

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4931]
**Describe the bug**
When a toolbox has a flyout where `autoclose` is set to `false` it does not update its zoom level while the workspace is zoomed.

**To Reproduce**

1. Go to https://blockly-demo.appspot.com/static/tests/playground.html
2. Run `Blockly.getMainWorkspace().getToolbox().getFlyout().autoClose = false` in the console.
3. Zoom the workspace
4. Click on the flyout.
5. Notice how the flyout zoom level jumps

![flyout-bug](https://user-images.githubusercontent.com/23059043/122480218-488f1700-cf81-11eb-82ff-c4943031f28e.gif)

**Expected behavior**
The flyout should zoom in as the workspace zooms in.
![flyout-expected](https://user-images.githubusercontent.com/23059043/122480227-4d53cb00-cf81-11eb-8e5a-060f4e8344c0.gif)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by BeksOmega** [comment]
Closed by #4938
