### ISSUE TITLE
Disabling only one field on a block

### ISSUE THREAD

**Issue by jschanker** [google/blockly#4932]
**Is your feature request related to a problem? Please describe.**

While you can disable all fields on a block by calling [setEditable](https://github.com/google/blockly/blob/master/core/block.js#L882) on it, there doesn't appear to be a method to disable only one of its fields.

**Describe the solution you'd like**

Introduce a `setEnabled` method for fields so you can toggle whether the editor will display or not.

**Describe alternatives you've considered**

* Have the user extend a Field subclass to provide this method manually for the specific type of field he/she wants to have the ability to disable.  Not good for overriding multiple types of Fields.

**Additional context**

Related to the question in the post on the Blockly forum here: [https://groups.google.com/g/blockly/c/tnWc8-WM1lk](https://groups.google.com/g/blockly/c/tnWc8-WM1lk)

[Beka] And this topic as well: https://groups.google.com/d/msg/blockly/OiUL3gzGATQ/WUadyexeBwAJ

**Comment by jschanker** [comment]
Stumbled upon duplicate https://github.com/google/blockly/issues/2763 while looking at the Icebox issues.  Close this as duplicate?

**Comment by BeksOmega** [comment]
I think this one has more detail so I'm going to keep this one and close the other =) Plus this issue is already linked to your PR. I've added the forum link from that issue to this one. Thanks for finding the dupe!

**Comment by jschanker** [comment]
Resolved by #4941.
