### ISSUE TITLE
Add a 'Help' button to devsite

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4935]
**Where**
https://developers.google.com/blockly/guides/overview

**What**
Add a "Help" button to our developer guides that will link to the forum.

  
- [ ] Text
- [ ] Image or Gif
- [x] Other

**Old content**

**Suggested content**

**Additional context**

**Comment by rachel-fenichel** [comment]
Is the idea to have this on all pages, or just this one?

**Comment by alschmiedt** [comment]
I think the idea was to have it on all pages. Probably somewhere in the footer would be easiest.

**Comment by rachel-fenichel** [comment]
There's already a support link in the top bar, between samples and summits:
![image](https://user-images.githubusercontent.com/13686399/123690148-e8159a80-d808-11eb-9399-108c76e226e3.png)

Would changing that title to "Help" be sufficient? It goes directly to the forum.

**Comment by alschmiedt** [comment]
I think @maribethb was the one that brought this up in the meeting, so I will leave this decision up to her : ) 

Even if we decide to add some kind of button, I do think we should also change this to either "Help" or "Get Help".

**Comment by maribethb** [comment]
Yeah, changing this to "Get Help" sounds good. Part of me wants to run an A/B test and see which one gets more clicks, but part of me knows I have bigger things to worry about...

**Comment by BeksOmega** [comment]
Created internal PR changing this label from "Support" to "Get Help"

**Comment by BeksOmega** [comment]
Internal PR has been merged and it is available on the dev site.
