### ISSUE TITLE
Look into hosting developer docs in public repo

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#4937]
**Where**

**What**
We should look into possibly hosting our developer docs in a place where external contributors can modify them. This would probably involve using [copybara](https://github.com/google/copybara) to sync this external documentation with our internal documentation.

  
- [ ] Text
- [ ] Image or Gif
- [x] Other

**Old content**

**Suggested content**

**Additional context**

**Comment by BeksOmega** [comment]
I'm going to close this, discussed with Maribeth today and we decided not to do this based on:
  1) copybara is difficult to set up, and represents an additional tool with additional maintainance + knowledge cost
  2) We already encourage people to write codelabs in samples, and haven't had a lot of interest. Additionally, contributions we get in docs issues usually need a lot of fixup. So based on these two things, it's unlikely people actually want to contribute to our devsite guides.
