### ISSUE TITLE
Dispose of disconnected shadow blocks

### ISSUE THREAD

**Issue by moniika** [google/blockly#4939]
**Is your feature request related to a problem? Please describe.**
If a child block is disconnected without checking whether it is a shadow block, then we get into a state where there is a shadow block without a parent. This issues has happened before in the list and text blocks.
There are assumptions in code, such as in [`Gesture.setTargetBlock_`](https://github.com/google/blockly/blob/fc6a1be3d982349292b630d2818b3b5509688d5f/core/gesture.js#L843), that a shadow block always has a parent.

**Describe the solution you'd like**

Dispose of a child block at disconnect if it is a shadow block.

**Describe alternatives you've considered**

Review existing code and remove assumptions that shadow block has a parent (such as in gesture where we could target the shadow block if there is no parent).

**Additional context**
Related to: https://github.com/google/blockly/issues/4847

**Comment by maribethb** [comment]
Closing this issue, it still exists but relevant info is captured in #4847 and doesn't need additional discussion, just a solution :)
