### ISSUE TITLE
Missing mention of protected access in JSDoc section of Style Guide

### ISSUE THREAD

**Issue by jschanker** [google/blockly#4940]
**Where**

[Do section of Web Blockly Style Guide](https://developers.google.com/blockly/guides/modify/web/style-guide#do)

[JSDoc section of Web Blockly Style Guide](https://developers.google.com/blockly/guides/modify/web/style-guide#jsdoc)

**What**

  
- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

* _(6th bullet point of Do Section)_ Use underlines at the end of `privateVariableNames_` and `privateFunctionNames_` .

* Blockly uses **three** visibility tags.

* A visibility tag: public, package, or private _(mentioned under Properties and Functions sections)_

**Suggested content**

* _(6th bullet point of Do Section)_ Use underlines at the end of **`protectedVariableNames_`**, `privateVariableNames_`, **`protectedFunctionNames_`** and `privateFunctionNames_` .

* Blockly uses **four** visibility tags.

* _(Add bullet point about protected)_

* A visibility tag: public, **protected**, package, or private

**Comment by BeksOmega** [comment]
Put up internal PR to fix this. Thanks for filing :D

**Comment by jschanker** [comment]
Resolved by internal PR.
