### ISSUE TITLE
Consider Renaming the project.

### ISSUE THREAD

**Issue by vfrascello** [google/blockly#4943]
Blockly implies blockchain.  I am not a fan of the blockchain, but your project name is bound to confuse users which are generally young children.  As web-based programming is generally for beginner coders, this could set them down a path of confusion (and destruction).  I propose renaming Blockly to Google KidCode

**Comment by NeilFraser** [comment]
Blockly is not a product aimed at kids, Blockly is aimed at developers who create products which are (often) aimed at kids.  Thus kids use products such as Scratch, App Inventor, Open Roberta, etc, without ever encountering the word "Blockly". 
 Furthermore, our use of "Blockly" (released May 2012) predates the [first use of the word "blockchain"](https://trends.google.com/trends/explore?date=2012-01-01%202021-06-20&geo=US&q=blockchain).

As for "KidCode", there are already [11,400 search results](https://www.google.com/search?q=%22kidcode%22) in Google for this word.  We'd be creating far greater confusion by using this name.  By contrast, "Blockly" had only one result when we named it, it's apparently the name of [a house in Iowa](https://www.google.com/maps/place/Blockly,+IA+50144/@40.6597403,-93.7560607,337m/data=!3m1!1e3!4m5!3m4!1s0x87ebd608c9fe60a9:0xb26ea4e6f18cc1d5!8m2!3d40.6597249!4d-93.7549449).
