### ISSUE TITLE
Scrollbars Look Chunky on ChromeOS

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#4953]
**Describe the bug**

Scrollbars are wider than normal when viewed on chromeOS

**To Reproduce**

1. Go to any of the playgrounds while running ChromeOS.
2. Observe how the scrollbars are wider than normal.

**Expected behavior**

Scrollbars should be the normal thin size.

**Screenshots**

Viewed in Chrome while running a Linux OS:
![Screenshot from 2021-06-28 16-21-11](https://user-images.githubusercontent.com/25440652/123670893-8c401700-d7f2-11eb-977c-5ff05ec5a80c.png)

Viewed in Chrome while running ChromeOS:
![Screenshot 2021-06-28 09 22 55](https://user-images.githubusercontent.com/25440652/123670876-864a3600-d7f2-11eb-820d-5175c8af034f.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome
 - Version: 91

**Additional Context**
This issue exists on master.

**Comment by NeilFraser** [comment]
This may be working as intended.  Finger-sized scrollbars are a feature of touch-screen enabled devices.

**Comment by BeksOmega** [comment]
That makes sense! I was super confused about what could be causing this since everything else was the correct size haha. Closing as WAI.
