### ISSUE TITLE
Touchscreen ChromeOS: Long press selects text

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#4954]
**Describe the bug**

When you long press using a touchscreen on chromeOS, some text on the page will be selected (in addition to opening the context menu).

**To Reproduce**

1. Go to any of the playgrounds on a touchscreen chromeOS device.
2. Long press on the workspace or a block.
3. Observe how text is selected somewhere on the page.

**Expected behavior**

No text is selected.

**Screenshots**

![Screen recording 2021-06-28 09 43 48](https://user-images.githubusercontent.com/25440652/123673840-c5c65180-d7f5-11eb-90c7-e767870a7ea2.gif)

**Desktop (please complete the following information):**
 - OS: ChromeOS w/ Touchscreen
 - Browser: Chrome
 - Version: 91

**Additional context**

Related to but slightly different from #2188. In this situation the context menus do pop up, but in that situation they do not.

This issue exists on master.

**Comment by gonfunko** [comment]
Note that this also happens in Edge per #5800
