### ISSUE TITLE
Empty comments not saved during serialization

### ISSUE THREAD

**Issue by jschanker** [google/blockly#4960]
**Describe the bug**

If the comment for a block contains no text (even if pinned), this block state will not be serialized. 

**To Reproduce**

1. Go to the Blockly Playground,
2. Import the following XML:
```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="text_print" x="100" y="100">
    <comment pinned="true" h="80" w="160"></comment>
  </block>
</xml>
```
3. Export the XML.  Notice that the comment element is removed.

**Expected behavior**

The empty comment should be serialized.

**Comment by BeksOmega** [comment]
I think this is actually intentional. The idea being, if the comment doesn't provide any information to the user, you might as well make the save file a tiny bit smaller.

But I'm definitely open to changing this when I do some other serialization work this quarter. Do you have a use case for saving the empty comments?

**Comment by jschanker** [comment]
That makes sense, and I don't have any practical use case for saving the empty comments.  I was just thinking if someone did something like the following to refresh the workspace, the loss of comments might be unexpected:
```
Blockly.Xml.clearWorkspaceAndLoadFromXml(Blockly.Xml.workspaceToDom(workspace), workspace);
```
Closing as WAI.

**Comment by jschanker** [comment]
Just for some context, this is how I refreshed the workspace before I knew about the [`render`](https://github.com/google/blockly/blob/master/core/workspace_svg.js#L1412) method (or before it existed?).  I needed it when I used [`newBlock`](https://github.com/google/blockly/blob/master/core/workspace_svg.js#L990) for converting textual code to blocks to see the new blocks appear.  On a tangential note that might be useful for anyone who had forked the Blockly repository a number of years ago before this was necessary, when creating new blocks, [`initModel`](https://github.com/google/blockly/blob/master/core/block.js#L422) or [`initSvg`](https://github.com/google/blockly/blob/master/core/block_svg.js#L216) needs to be called on a block after creating it.
