### ISSUE TITLE
Field editors of blocks behind toolbox render atop toolbox

### ISSUE THREAD

**Issue by gonfunko** [google/blockly#4963]
**Describe the bug**
When blocks with editable fields are positioned behind the toolbox, tabbing to those fields causes the textfields to render atop the toolbox, even if the block they belong to is partially or totally obscured by the toolbox.

**To Reproduce**
1. Drag out several blocks with editable text fields, and position one or more of the blocks so that they are behind the toolbox.
2. Click into the text field of a block that is not behind the toolbox.
3. Press the Tab key to tab into one of the blocks that is behind the toolbox
4. Observe that the editable text field of the block(s) behind the toolbox becomes focused and renders atop the toolbox.

**Expected behavior**
Unsure, but the field should not be displayed on top of the toolbox. Possibly tabbing should only jump between text fields of blocks that are fully visible in the workspace, ie not scrolled offscreen/behind the toolbox?

**Screenshots**
https://user-images.githubusercontent.com/667459/123704171-4008cd00-d81a-11eb-87c5-914212d090d5.mov

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Browser: Safari 14.1.1, Chrome 91.0.4472.114

**Comment by alschmiedt** [comment]
The other options here is to do something like [workspace search](https://github.com/google/blockly-samples/blob/fb16a806ce44aeb5296647f77bbc5813c3b5ed93/plugins/workspace-search/src/WorkspaceSearch.js#L634) does, where it scrolls the workspace so the block is visible.

**Comment by gonfunko** [comment]
Duplicate of #4695.
