### ISSUE TITLE
Clicking Canvas inside of Iframe does not give Focus to the Iframe

### ISSUE THREAD

**Issue by acbart** [google/blockly#497]
So this is probably pretty niche, and I'm not entirely sure it's solvable.

I'm implementing cross-instance copy/paste, and while doing so I made a strange discovery. Clicking on the white part of the canvas (or any blocks on the canvas) does not give focus to the iframe. If I click anywhere else in the iframe, including the flyout categories, it will give focus to the iframe.

You can check this behavior by looking at the "document.activeElement" variable; clicking on the white canvas will leave it pointed at the Body, but clicking anywhere else in the iframe switches to the iframe.

This is a problem for me since users intuitively click the canvas to select that instance, and then the copy/paste keys don't work until they click somewhere else on the instance.

This is Chrome on Windows, last updated blockly a few weeks ago.

I'm not familiar with the APIs involved here, so it might be an unsolvable problem. But I thought you should know!

**Comment by gonfunko** [comment]
Tested with https://blockly-demo.appspot.com/static/tests/playgrounds/iframe.html and this no longer reproduces.
