### ISSUE TITLE
Hook to mutate block on copy

### ISSUE THREAD

**Issue by ericedem** [google/blockly#4996]
**Is your feature request related to a problem? Please describe.**

We have a use case where one of our blocks represents a system entity that has an ID. We track this through our system by adding a mutation to the block with an ID. This block has statements under it and forms a sort of "function" or "routine".

This works great but the problem is when someone wants to copy the blocks. Everything gets copied including this ID mutation. We would like the ability to strip out the ID when someone is trying to copy it so that it doesn't collide with the existing entity.

**Describe the solution you'd like**

I'm not exactly sure on the solution but I think it would center around having a hook that a block can define to inject behavior into `blockToDom()`. I noticed that in this method where copying happens, a value of `true` is passed in to `blockToDom()` to denote that it is a copy and the client ID of the block should be removed.

Perhaps we could add a method call into `blockToDom()` that will be called to manipulate mutations when this argument is `true`.

**Describe alternatives you've considered**

I've considered trying to monkey patch the `blockToDom()` call but I think it would be too hard to maintain long term. In the short term to work around this we will just disable copying of this block.

We are also considering just adding a "duplicate workspace" to our implementation where we will manually traverse the XML and strip out the ID mutation. But I don't think this would require a change to Blockly core.

**Additional context**

There is some discussion in the mailing list here: https://groups.google.com/g/blockly/c/A0TCzTvRW_o/m/MpbYgSL5AAAJ

**Comment by maribethb** [comment]
Based on the forum post, it seems like this particular request found a workaround (it's fairly specific so check out the forum if you're interested). However, we have gotten requests for additional hooks around copy/pasting so I'm going to throw this on the backlog so we can reference it if we decide to work on that in the future.

One other thing I was going to suggest was to register your own "copy" function that strips out the data from the block before copying it, or something like that.

**Comment by gonfunko** [comment]
Now that we have [IPaster](https://developers.google.com/blockly/reference/js/blockly.ipaster_interface.paste_1_methodsignature.md), I think we have a reasonable solution: create and register a custom paster that munges your blocks as needed at time of paste. I [used this in Scratch](https://github.com/gonfunko/scratch-blocks/blob/modern-blockly/src/scratch_block_paster.js), and while it's on the opposite end of the copy-paste cycle from what this issue described, it seems to do the job well enough.
