### ISSUE TITLE
XML toolbox does not parse in IE11 for <hr>

### ISSUE THREAD

**Issue by carlosperate** [google/blockly#50]
I've notice that the code demo does not work in IE11 in the latest head (1c39a638e312d19714dcd3f84a176de93853280e at the time of writing).

The problem arises in xml.js file when it is trying to parse the toolbox xml (https://github.com/google/blockly/blob/master/core/xml.js#L199). I'm not quite sure if i'll have the time in the inmediate future to look into it to submit a pull request, so I though I should post it here in case somebody else can do that.

**Comment by NeilFraser** [comment]
Just a random guess, is IE11 ok with <hr/> but not <hr>?

**Comment by NeilFraser** [comment]
Previous comment got rendered by GitHub.  Heh.  Let's try that again, this time HTML encoded...

Just a random guess, is IE11 ok with &lt;hr/&gt; but not &lt;hr&gt;?

**Comment by carlosperate** [comment]
That was my first guest as well, but it does not work either way. However, I just noticed that using `<hr/>` causes IE to also output the following:
 `XML5633 "End-tag name does not match the corresponding start-tag name."` (https://msdn.microsoft.com/en-us/library/ie/dn423949(v=vs.85).aspx).

I started looking back the git history up to when the separators were added (https://github.com/google/blockly/commit/5aed33b678a204f10f4f063136e4689095044726) and `parseFromString()` it's been problematic in IE11 from the beginning.

**Comment by NeilFraser** [comment]
Does it want &lt;hr&gt;&lt;hr/&gt;?

Or maybe it is allergic to an XML tag than looks like HTML?  Does switching from &lt;hr&gt; to &lt;ie_is_trash&gt; or &lt;ie_is_trash/&gt; work?

**Comment by carlosperate** [comment]
`<hr></hr>` doesn't work.
`<ie_is_trash>` and  `<ie_is_trash/>` don't work either.
`<ie_is_trash></ie_is_trash>` does work.
`br` behaves the same way `hr` does, so it seems to be specific to html tags.

**Comment by NeilFraser** [comment]
Ok, that's really helpful, thank you.
I propose changing Blockly to use &lt;sep&gt;&lt;/sep&gt; instead of &lt;hr&gt;.  Normally I'd push for allowing &lt;hr&gt; to live on as a deprecated alternative, but it looks like we need to actively eliminate it.  I'll have Blockly (in non-IE browsers) print an error to the console if it sees a &lt;hr&gt; tag, ignore the tag, and continue parsing.

**Comment by NeilFraser** [comment]
Change committed, documentation updated.

**Comment by carlosperate** [comment]
I was just about to suggest a slightly different approach. It's not an elegant fix, but it would maintain the hr tag usable in IE. I can prepare a demo in a little bit of time.

**Comment by NeilFraser** [comment]
The feature is only two months old, so I think it's fine to make a breaking change to it.  There's probably only one developer using &lt;hr&gt; right now (the one who asked for it originally).

**Comment by carlosperate** [comment]
Nevermind then. In case you are curios, IE was removing the self closing slash from the HTML DOM, and that is way it did not parse as valid XML (https://github.com/carlosperate/blockly/commit/e990eb4d668b5e083a3c071dd78ae8ca39d5a555). That is also why it worked in IE when I was loading the XML data from a file.
