### ISSUE TITLE
Blockly.Events.Abstract is missing type property

### ISSUE THREAD

**Issue by moniika** [google/blockly#5004]
The `type` property is not documented by the `Blockly.Events.Abstract` class which all Events inherit from.
This is evident from the generated [documentation](https://developers.google.com/blockly/reference/js/Blockly.Events.Abstract?hl=en) and leads to some confusion for developers.

The `type` property should be declared on `Blockly.Events.Abstract` or there should be an event interface that `Blockly.Events.Abstract` implements that declares the property.

**Comment by maribethb** [comment]
This has been fixed
