### ISSUE TITLE
Generator mocha tests emit warnings during blockToCode suite

### ISSUE THREAD

**Issue by moniika** [google/blockly#5029]
**Describe the bug**

**To Reproduce**

1. Run Generator mocha tests
2. See 50+ console warnings:
```
Generator init was not called before blockToCode was called
```

**Expected behavior**

No warnings

**Stack Traces**

```
Blockly.Generator.blockToCode	@	generator.js:180
loopTest	@	generator_test.js:133
(anonymous)	@	generator_test.js:142
callFn	@	mocha.js:4550
Runnable.run	@	mocha.js:4542
Runner.runTest	@	mocha.js:5078
(anonymous)	@	mocha.js:5196
next	@	mocha.js:4992
(anonymous)	@	mocha.js:5002
next	@	mocha.js:4926
(anonymous)	@	mocha.js:4965
done	@	mocha.js:4497
callFn	@	mocha.js:4573
Runnable.run	@	mocha.js:4542
next	@	mocha.js:4940
(anonymous)	@	mocha.js:4970
timeslice	@	mocha.js:82
setTimeout (async)		
Mocha.Runner.immediately	@	mocha.js:98
Runner.hook	@	mocha.js:4969
Runner.runSuite	@	mocha.js:5320
start	@	mocha.js:5472
Runner.run	@	mocha.js:5499
Mocha.run	@	mocha.js:1652
mocha.run	@	mocha.js:160
(anonymous)	@	index.html:97
```

**Additional context**
There was an active effort to clean test warnings and so there are relatively few console logs. In order to keep the console logs useful for debugging and catching signs of tricky bugs, these should be prevented.

**Comment by maribethb** [comment]
I'm putting this in the release milestone since it sounds like a recent regression and it's important with all the changes we are making this quarter that our tests remain useful.
