### ISSUE TITLE
Add docs page for playground and update information

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#5040]
**Where**

Currently the playground info is hidden under "[Building Blockly](https://developers.google.com/blockly/guides/modify/web/building)". It should be moved into its own page under Modifying Blockly.

This should be done *after* the move to goog.module, since the playground is changing anyway.

**What**

  
- [X] Text
- [X] Image or Gif (picture of playground)
- [ ] Other

**Old content**

See [here](https://developers.google.com/blockly/guides/modify/web/building#playground).

**Suggested content**

After the move to goog.module, the current information needs to be updated to tell people to use `npm run start` to run the playground. It should also inform people about the advanced playground.

**Comment by maribethb** [comment]
This is now live here: https://developers.google.com/blockly/guides/modify/web/playground 

I hope this is helpful; suggestions welcomed!
