### ISSUE TITLE
Support Positionable overlays

### ISSUE THREAD

**Issue by moniika** [google/blockly#5044]
**Is your feature request related to a problem? Please describe.**

Some `IPositionable`s are meant to overlay the top of the Blockly Workspace and aren't meant to affect the positioning of other elements.
For example, the search bar in [@blockly/workspace-search](https://www.npmjs.com/package/@blockly/plugin-workspace-search) isn't meant to shift around other UI elements if there are any in the top right corner.

**Describe the solution you'd like**

Add a flag to indicate that a `IPositionable`'s position should be ignored or allow `IPositionable`s to return `null` in `getBoundingRectangle`.

**Describe alternatives you've considered**

Support something like "layers" where UI elements only affect other UI elements on the same "layer". This would allow for adding multiple ui elements on a top layer that should affect each other but not the ui elements on the default lower layer.

**Additional context**
https://github.com/google/blockly/pull/5011

**Comment by gonfunko** [comment]
IPositionables are able to return null from getBoundingRectangle() to not force other things out of the way.
