### ISSUE TITLE
resizeable blockly not working with full screen

### ISSUE THREAD

**Issue by kirstyellis** [google/blockly#506]
Hi, 
I am using blockly with Erle's robot_blockly wrapper. I recently updated blockly to the most recent version of master and have found that the blockly workspace no longer resizes if my browser is maximised. Any other size of window and the workspace resizes as expected. I have also noticed that it isn't working on this page https://blockly-demo.appspot.com/static/demos/resizable/overlay.html
I am using Chrome Version 52.0.2743.82 (64-bit) on Ubuntu 14.04 and I have also checked that the issue exists on Firefox 47.0

Thanks.

**Comment by picklesrus** [comment]
I think you probably need to call svgResize one the div blockly lives in figures out its size.  I've fixed this in that demo here:
https://github.com/google/blockly/pull/489.  Sorry it hasn't been merged yet - we're a bit behind due to people being out.

**Comment by NeilFraser** [comment]
#489 now merged with develop branch.
