### ISSUE TITLE
Closure base.js should not request (non-existent) closure/goog/deps.js

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#5103]
**Describe the bug**

**To Reproduce**
On the goog_module branch, run `npm run start`.

See this error in the terminal:
`[Fri Jul 16 2021 14:32:57 GMT-0700 (Pacific Daylight Time)]  "GET /closure/goog/deps.js" Error (404): "Not found"`

You can also see it in the console on the actual playground page.

**Expected behavior**

Only expect one deps file.

**Comment by cpcallen** [comment]
I was aware of the issue, but thanks for filing this so that I don't forget.
