### ISSUE TITLE
buggy JavaScript code is generated from the "text_isEmpty" block

### ISSUE THREAD

**Issue by bkisdi** [google/blockly#511]
The **text_isEmpty** block with the **text** variable generates 
`!text.length`
JavaScript code.

It raises error when **text** was never assigned:
`Error in XXXXX on: TypeError: Cannot read property 'length' of undefined`

And what if  **text** is not a string or array - a number, for example?

**Comment by NeilFraser** [comment]
Blockly doesn't have typed variables yet, so this is completely unavoidable.  However #446 is addressing this.
