### ISSUE TITLE
Vertically dragging blocks from flyout with scrollbar scrolls flyout instead of moving block

### ISSUE THREAD

**Issue by yoderjen** [google/blockly#513]
I'm seeing this in both my own code (includes fix #478) and in the current Blockly Code demo.

When dragging a block from a flyout that includes a scrollbar, if you click and drag a block vertically to bring it into the workspace (either up or down) Blockly scrolls the flyout instead of moving the selected block.

**Comment by rachel-fenichel** [comment]
@drigz

**Comment by drigz** [comment]
This is working as intended - the main purpose of the change is to make scrolling easier on touchscreens where the scrollbar / flyout background is hard to hit reliably.

If you'd like to disable this, you can change [Blockly.mainWorkspace.toolbox_.flyout_.dragAngleRange_](https://github.com/google/blockly/blob/bbf2764cc8d7307201481874d2f1a75f70a88de9/core/flyout.js#L177) to 360. @rachel-fenichel, do you think we should add this setting to Blockly.Options?

**Comment by yoderjen** [comment]
If the scrolling is the desired behavior, then I can report another bug: At least on the current Blockly code demo, after the scrolling, Blockly actually creates the block you selected and dragged (right underneath where it was originally pictured).  I'm guessing you either want the scroll behaviour or the block creation behaviour - not both.
