### ISSUE TITLE
New Context menu API Docs

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#5134]
**Where**

[Define Blocks > Context menu](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#context_menus)

**What**

  
- [X] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

Disable the context menu on a block with
```
block.contextMenu = false;
```
Implement customContextMenu on your block to modify the options in the right-click menu for that block. This function takes in an array of menu options and modifies it in place, which means you may both add and remove items.

Each menu option is an object with three properties:
 * `text` is the display text.
 * `enabled` is a boolean. When disabled, the option is shown but with grey text.
 * `callback` is the function to be called when the option is clicked.

**Suggested content**

Add an additional link to the new [context menus codelab](https://blocklycodelabs.dev/codelabs/context-menu-option/index.html?index=..%2F..index#0), and maybe provide some info about the new API.

**Comment by maribethb** [comment]
Note there is already documentation on the new API here https://developers.google.com/blockly/guides/configure/web/context-menus so I think we just need to add a link and explain new API is for all blocks, old method is for one block at a time

**Comment by BeksOmega** [comment]
> Note there is already documentation on the new API here https://developers.google.com/blockly/guides/configure/web/context-menus so I think we just need to add a link and explain new API is for all blocks, old method is for one block at a time

Oh sweet! I hadn't noticed there were dev docs for it in addition to the codelab. that's rad :D
