### ISSUE TITLE
Refactor block and blocksvg initialization

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#5146]
**Is your feature request related to a problem? Please describe.**

The block initialization system needs some work (putting it generously). The logic is currently stored in the [XML system](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/core/xml.js#L560) this is bad because one:
  1) It violates the single responsibility principle, introducing fragility into a high-stakes system.
  2) It makes it hard for outside devs to create blocks programmatically, because the initialization logic isn't surfaced through a good API. See the [docs](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/core/workspace_svg.js#L994) I added to `workspace.newBlock` a while ago.

Setting aside the API, the actual logic also needs some work.
  1) Headless and rendered blocks are handled separately using [type checks](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/core/xml.js#L560). This goes against the principles of polymorphism/inheritance. There should be an `init` function on both types which handles the logic of each.
  2) To work efficiently, this relies on calling `initSvg`  and then `render` the blocks from leaf blocks to parent blocks, *and* not allowing the `render` calls to bubble. See [here](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/core/xml.js#L564). This is unclear and fragile.

**Describe the solution you'd like**

Both block types should have an `init` function which handles the logic for that type. This would:
  1) Follow the single responsibility principle by removing init logic from the XML system.
  2) Follow the principles of polymorphism/inheritance.
  3) Make life easier for outside devs, because they would only have to call one function. We might even be able to add the call to `workspace.newBlock`

I think it would be nice to have this `init` function recursively initialize and render child blocks (in such a way that there are no duplicate calls). But this may conflict with the fact that `render` calls generally bubble up to parents, and complicate the API.

**Describe alternatives you've considered**

N/A

**Additional context**

I really want to fix this so that I don't have to add this ugly init logic to the new serializer. But it's far too big to be in scope of my project :/

Note for external contributors that might want to take this on: This is a *big* project that would require *lots* of testing.

**Comment by tweini** [comment]
I came form here: https://github.com/google/blockly/blob/d2329f8cba661999cc7f03fcd6c0196770b05cdc/core/serialization/blocks.js#L611
While debugging, there were no traces from or into the xml system. As this issue is opened some time ago, an update what happened since then would be cool.

**Comment by BeksOmega** [comment]
So I dug into this a bunch, and eventually ended up failing.

The initialization logic has to live in the serialization system, because of how variable fields behave. If a variable field does not have a reference to a variable model and you call `init` on it, it will create a variable model to point to. So if we were to init fields before deserializing them, we would end up with extra variable models in the workspace, and we would have no way to clean them up.

We also can't add this logic to `newBlock` and have the serialization call the `Block` and `BlockSvg` constructors directly, because that causes circular dependencies.

So we are stuck with the system as it currently exists.
