### ISSUE TITLE
Migrate to named exports

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#5153]
### Background

The [JavaScript](https://google.github.io/styleguide/jsguide.html#es-module-exports) and [TypeScript](https://google.github.io/styleguide/tsguide.html#exports) style guides specifically prohibit default exports for ES/TS Modules:

> ```JS
> // Do not use default exports:
> export default class Foo { ... } // BAD!
> 
> // Use named exports:
> export class Foo { ... }
> 
> // Alternate style named exports:
> class Foo { ... }
> export {Foo};
> ```

For `goog.module` modules, the JavaScript style guide does not specifically prohibit default exports (`exports = MyClass;`), but it gives only examples of named exports.  (It does give examples of `goog.require`ing the default export, however.)

### Proposal

Migrate all modules which have a default export to use only named exports, so

```JS
const MyClass = function(...) {...};
exports = MyClass
```
becomes
```JS
const MyClass = function(...) {...};
exports.MyClass = MyClass;
```
and the corresponding import is (simultaneously) changed from
```JS
const MyClass = goog.require('MyClass');
```
to
```
const {MyClass} = goog.require('MyClass');
```

### Discussion

There's nothing wrong with default exports in the short term, but this is something we will want to fix eventually as we continue the migration from `goog.provide` -> `goog.module` -> ES modules -> TypeScript.  Issue #5073 records a number of cases where we will probably decide to fix this sooner rather than later.  This bug is to ensure that "later" arrives eventually.

**Comment by moniika** [comment]
When the time comes, we can automate changing all this with the following commands (swapping out core for each directory we want to fix):
```
# Change all the default exports to named exports
grep -rlE "^exports = \w+" core | xargs sed -i -E "s/^exports = (\w+)/exports = \{\1\}/"
# Change all the default imports to named imports
grep -rlE "^const \w+ = goog\.require" core | xargs sed -i -E "s/^const (\w+) = goog\.require/const \{\1\} = goog\.require/"
```

**Comment by cpcallen** [comment]
> When the time comes, we can automate changing all this with the following commands (swapping out core for each directory we want to fix):
This one is great:
> ```
> # Change all the default exports to named exports
> grep -rlE "^exports = \w+" core | xargs sed -i -E "s/^exports = (\w+)/exports = \{\1\}/"
> ```
But I believe this catch _all_ the cases where we do non-destructuring imports, even the ones where there wasn't a default export:
> ```
> # Change all the default imports to named imports
> grep -rlE "^const \w+ = goog\.require" core | xargs sed -i -E "s/^const (\w+) = goog\.require/const \{\1\} = goog\.require/"
> ```

**Comment by moniika** [comment]
> But I believe this catch _all_ the cases where we do non-destructuring imports, even the ones where there wasn't a default export:
> 
> > ```
> > # Change all the default imports to named imports
> > grep -rlE "^const \w+ = goog\.require" core | xargs sed -i -E "s/^const (\w+) = goog\.require/const \{\1\} = goog\.require/"
> > ```

I see. Good catch!
I think we could still write a short temporary script to do this, but we would need something a tad more complex. Something that would save matches of module names that match the first step and use those in the second step.
We'd need to save the

**Comment by BeksOmega** [comment]
> For goog.module modules, the JavaScript style guide does not specifically prohibit default exports (exports = MyClass;), but it gives only examples of named exports. (It does give examples of goog.requireing the default export, however.)

The internal styleguide actually does explicitly prohibit them for `goog.module` modules. See the bottom of 3.3.3 `goog.module` Exports:
> Do not use default exports as they don't translate easily to ES module semantics...

But I'm not sure if we care about that styleguide, or only the one available publicly.

**Comment by cpcallen** [comment]
> > For goog.module modules, the JavaScript style guide does not specifically prohibit default exports (exports = MyClass;), but it gives only examples of named exports. (It does give examples of goog.requireing the default export, however.)
> 
> The internal styleguide actually does explicitly prohibit them for `goog.module` modules. See the bottom of 3.3.3 `goog.module` Exports:
> 
> > Do not use default exports as they don't translate easily to ES module semantics...

Oh, interesting.  Maybe one day I will be allowed to view the internal version of the style guide.  :-(  Certainly [the external version] (https://google.github.io/styleguide/jsguide.html#file-goog-module-exports) does not contain that text.
 
> But I'm not sure if we care about that styleguide, or only the one available publicly.

The advice is almost certain good in any case, and since we will presumably migrate towards ES modules soon enough (for which even [the public version](https://google.github.io/styleguide/jsguide.html#es-module-exports) has a clear prohibition) there's not really any good argument in favour of keeping default exports other than temporarily to ease the transition.

**Comment by alschmiedt** [comment]
Closing as the last part of this was finished in #5719.
