### ISSUE TITLE
Rename enum Blockly.connectionTypes to follow the style guide

### ISSUE THREAD

**Issue by moniika** [google/blockly#5156]
### Issue

The enum `Blockly.connectionTypes` does not follow the style guide of using `UpperCamelCase` and also of generally being a singular noun.

### Suggested Fix

Renaming `Blockly.connectionTypes` to `Blockly.ConnectionType` for consistency.

### Additional context

https://google.github.io/styleguide/jsguide.html#naming-enum-names

**Comment by himanshujaidka** [comment]
@moniika pls assign this issue to me

**Comment by cpcallen** [comment]
Closed by #5407.
