### ISSUE TITLE
Use new eslint config for es6 / goog.module

### ISSUE THREAD

**Issue by maribethb** [google/blockly#5160]
## Describe the solution you'd like

After the round of goog.module conversion is finished, and we've converted all of the `var`s to `let/const`s, and clang-formatted all the things... we need to update the eslint config. We can't do it beforehand, because all of the unconverted code will have a lot of errors. Afterwards, there will probably still be some errors that we need to fix to actually be in agreement with the Google style guide.

Ideally, we'd be able to use the same library that we use in blockly-samples that understands the Google style guide: https://github.com/google/eslint-config-google. I think this is feasible, and while we will have some real problems to clean up afterwards, we'd be
a) conforming to Google style
b) using the same style in both blockly and blockly-samples.

## Describe alternatives you've considered

We might be able to use the same eslint config as blockly-samples, or extend that config (as opposed to both extending from the same config, but not each other). I'm not sure how feasible this will be yet, so when we're making this change, we should consider how similar they are and if this makes sense.

**Comment by rachel-fenichel** [comment]
There are a lot of issues in `tests/mocha/*`, including use of `this` and `var`.

Setting those aside and looking primarily at core and blocks, there are 492 violations of `comma-dangle`, which I'm fixing in https://github.com/google/blockly/pull/5625.

There are 512 violations of `camelcase`. We use `opt_argument` to indicate optional args, so we need to allow a few prefixes. This configuration of the rule yields 16 problems, all of which are legitimate:
```
"camelcase": ["error", {
    "properties": "never",
    "allow": ["^opt_", "^_opt_", "^testOnly_"]
}]
```

**Comment by rachel-fenichel** [comment]
Rules that we are currently violating outside of `tests/mocha/*`:

- [ ] `no-invalid-this`
- [ ] `comma-spacing`
- [ ] `key-spacing
- [ ] `camelcase`
- [ ] `new-cap`
- [ ] `padded-blocks`
- [ ] `prefer-const`
- [ ] `brace-style`
- [ ] `guard-for-in`
- [ ] `one-var`
- [ ] `quote-props`
- [ ] `prefer-spread`
- [ ] `require-jsdoc`
- [ ] `comma-dangle`
