### ISSUE TITLE
Design - default variables

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#518]
Related to #446 

if a developer specifies an explicit set of variables to always have in the variables category ("default variables"), 
- Should the user be allowed to delete those variables?
- Should the user be allowed to rename those variables?

My personal opinion is that they should not be allowed to delete the variables.  I'm less certain about renaming them.  In one sense renaming is just changing every existing instance to use a different name, which doesn't necessarily delete the variable.  In another sense, renaming is changing the base variable's name, which is analogous to deleting it and creating a different variable.

**Comment by tmickel** [comment]
Is this already in Blockly, or being added? What's the logic behind having default variables?

**Comment by rachel-fenichel** [comment]
If you use Blockly's basic set of blocks and categories, you'll default to having an "item" variable and a "list" variable that show up in the flyout.  In its present state Blockly doesn't have explicit variable creation or deletion, so the status of those variables isn't a concern.  

With the new variable management a user would be able to delete a variable that the developer explicitly put into the toolbox, which is undesirable.

The default variables would be defaults within the application that uses Blockly, not defaults in the Blockly code.

**Comment by tmickel** [comment]
Hmm, ok. I guess I don't understand the use case for undeleteable default variables in general.

just to be sure, this is separate from variables created by events or from an XML import, right? Those seem like they should be nameable/deletable to me.

**Comment by RoboErikG** [comment]
Correct. Variables that are added when xml is loaded are normal variables and can be renamed/deleted.

A use case for having a set of vars that can't be deleted/renamed could be a math class that is using blocks to teach equations and wants to restrict variables to the set in the problem statement.

**Comment by MNSDivya** [comment]
Is the reported issue still needs a fix?

**Comment by rachel-fenichel** [comment]
Solved by developer variables.
