### ISSUE TITLE
Mutator Editor UI occasionally does not correctly position blocks for an instant

### ISSUE THREAD

**Issue by hpnrep6** [google/blockly#5183]
**Describe the bug**
The position of blocks are sometimes temporarily incorrect before moving to the correct position when the mutator editor UI is opened.

**To Reproduce**

1. Open Blockly Playground, or any blockly demo
2. Add a block that has a mutator to the workspace
3. Open the mutator editor UI
4. Note how the block is sometimes misplaced for an instant

Note: Able to reproduce on everything but safari

**Expected behavior**

The block should be at the correct position when the mutator editor is opened and move to the correct position after it is opened.

**Videos**

https://user-images.githubusercontent.com/57055412/126721373-0dcc2017-7165-44a4-a831-2be84e3e035b.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04, macOS 11.4
 
**Browsers tested**
 - Chromium (on Ubuntu) (92.0.4515.107)
 - Opera (on Ubuntu)
 - Firefox (on Ubuntu)
 - Chrome (on macOS) (91.0.4472.164)
 - Safari (on macOS) (14.1.1)

**Comment by BeksOmega** [comment]
Closed by #5210
