### ISSUE TITLE
Could not find "storage.js"

### ISSUE THREAD

**Issue by SeniorCtrlPlayer** [google/blockly#5215]
https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/demos/blockfactory/index.html#L31

Should be `src="./storage.js"`

**Comment by NeilFraser** [comment]
Nope, this is intentionally designed to fail.  If you are running this off of a file system (instead of a server) then storage isn't going to work anyway.
