### ISSUE TITLE
Blockly documentation

### ISSUE THREAD

**Issue by guidoPaglie** [google/blockly#523]
Hi guys, i am using blockly to make a game and i wanted to ask where i can find all the functions, variables, etc i can get from blockly.

For example, i wanted to clear the workspace and it took more than the necessary to found that somebody used this( Blockly.mainWorkspace.clear() ).

Thank u in advance!

**Comment by acbart** [comment]
I've been hosting a copy of the API docs here: https://dl.dropboxusercontent.com/u/23141976/blockly-documentation/index.html

This was pretty easy to generate with JSDoc. Perhaps the team should, at some point, have the build system automatically generating documentation? I wasn't planning on keeping that documentation up-to-date or anything, and it's probably already lagging behind.

**Comment by guidoPaglie** [comment]
Thank u acbart!

**Comment by NeilFraser** [comment]
Duplicate of #119.  (But it's valid.)
