### ISSUE TITLE
STATEMENT_PREFIX / STATEMENT_SUFFIX inconsistent

### ISSUE THREAD

**Issue by bel2125** [google/blockly#5268]
**Describe the bug**

The use of  STATEMENT_PREFIX / STATEMENT_SUFFIX by flow control blocks (condition, loops) seems inconsistent for generating Lua code.

```JS
Blockly.Lua.STATEMENT_PREFIX = "Block.Enter(%1)\n";
Blockly.Lua.STATEMENT_SUFFIX = "Block.Leave(%1)\n\n";
```

For the "for" loop, the generator creates Lua code like

```Lua
Block.Enter('ID-OF-LOOP')
for count = 1, 2 do
  Block.Leave('ID-OF-LOOP')
  ... content of loop ...
  Block.Enter('ID-OF-LOOP')
end
Block.Leave('ID-OF-LOOP')
```

For an if/else block, there are two "Enter" calls:
```Lua
Block.Enter('IF-ELSE-BLOCK-ID')
Block.Enter('IF-ELSE-BLOCK-ID')
if condition then
  Block.Leave('IF-ELSE-BLOCK-ID')
   ... content of if branch 
else
  Block.Leave('IF-ELSE-BLOCK-ID')
   ... content of else branch 
end
Block.Leave('IF-ELSE-BLOCK-ID')
```

For an if block without else, there is only one "Enter" generated:
```Lua
Block.Enter('IF-BLOCK-ID')
if condition then
  Block.Leave('IF-BLOCK-ID')
  ... content of if branch
else
  Block.Leave('IF-BLOCK-ID')
end
```

It seems rather arbitrary if there are two enter or just one for flow control blocks.
If I use "Block.Enter/Leave" to keep track of activated blocks, sometimes the loop or condition block appears active if a contained block is active, sometimes the loop of condition block appears inactive.

The problem is, this behavior is inconsistent.

Calling "Enter" once before the loop or condition and once after would be consistent with the behavior when calling a user defined function.
For a call to a user defined function, the generated Lua code is:
```Lua
Block.Enter('callfunction-BLOCK-ID')
callfunction()
Block.Leave('call-function-BLOCK-ID')
```
Since the function will also start with a Block.Enter, there will be two (or multiple) active blocks - essentially a call stack with multiple elements. 

**To Reproduce**

Add the following lines in JavaScript:
```JS
Blockly.Lua.STATEMENT_PREFIX = "Block.Enter(%1)\n";
Blockly.Lua.STATEMENT_SUFFIX = "Block.Leave(%1)\n\n";
```
(Note: The \n are only for readability in the example below).

Use some Blockly example where you can see the generated Lua code, or add a button to show the generated Lua code to HTML:
```HTML
<button onclick="ShowLuaCode()">Show Lua Code</button>
<script>
  function ShowLuaCode() {
    var code = Blockly.Lua.workspaceToCode(workspace);
    alert(code);
  }
</script>
```

Full example with screenshot and code: see below

**Expected behavior**

Any behavior that allows to reliably and consistently detect all active blocks and create a callstack will be sufficient.
Having one additional Enter/Leave call around all flow control blocks would allow to do this.

**Screenshots**

![Blockly](https://user-images.githubusercontent.com/5619191/127782994-4922afc4-e690-491f-bc1e-caeeea9d11ae.png)

Generated Lua code:
```Lua
-- Describe this function...
function nothing()
  Block.Enter('[hIK):8(xAhU62!+T!64')
  Block.Leave('[hIK):8(xAhU62!+T!64')

  Block.Enter('*7KmU}JB.gc#NO(b3CwK')
  i = 12345
  Block.Leave('*7KmU}JB.gc#NO(b3CwK')

end



Block.Enter('~CL5HljRc6T?UC=5u}!X')
if true then
  Block.Leave('~CL5HljRc6T?UC=5u}!X')

  Block.Enter('a`{eF7YmX}lZd;jV!:~e')
  nothing()
  Block.Leave('a`{eF7YmX}lZd;jV!:~e')

else
  Block.Leave('~CL5HljRc6T?UC=5u}!X')

end
Block.Enter('L=61kY-ez9#ifG~2hfq4')
if true then
  Block.Leave('L=61kY-ez9#ifG~2hfq4')

  Block.Enter('i#.$SD8K}ke`2VUo(KNI')
  nothing()
  Block.Leave('i#.$SD8K}ke`2VUo(KNI')

elseif false then
  Block.Leave('L=61kY-ez9#ifG~2hfq4')

  Block.Enter('Ya7}i..:HyWqmZ+gT{m6')
  nothing()
  Block.Leave('Ya7}i..:HyWqmZ+gT{m6')

elseif false then
  Block.Leave('L=61kY-ez9#ifG~2hfq4')

  Block.Enter('kv$_Z1VM8SuBPpK(.|a|')
  nothing()
  Block.Leave('kv$_Z1VM8SuBPpK(.|a|')

else
  Block.Leave('L=61kY-ez9#ifG~2hfq4')

end
Block.Enter('dM=}ZIDCF/|E#]s-Yx)N')
Block.Enter('dM=}ZIDCF/|E#]s-Yx)N')
if true then
  Block.Leave('dM=}ZIDCF/|E#]s-Yx)N')

  Block.Enter('6P#{L?Uc{$w5IU8+LeVp')
  nothing()
  Block.Leave('6P#{L?Uc{$w5IU8+LeVp')

else
  Block.Leave('dM=}ZIDCF/|E#]s-Yx)N')

  Block.Enter('=@(:~nS`OQpQTE1go+u9')
  nothing()
  Block.Leave('=@(:~nS`OQpQTE1go+u9')

end
Block.Leave('dM=}ZIDCF/|E#]s-Yx)N')

Block.Enter('A)RF-i?AN|o6F3#m`0U7')
while false do
  Block.Leave('A)RF-i?AN|o6F3#m`0U7')

  Block.Enter('J8KoQF1}cb`-fntd+L|h')
  nothing()
  Block.Leave('J8KoQF1}cb`-fntd+L|h')

  Block.Enter('A)RF-i?AN|o6F3#m`0U7')
end
Block.Leave('A)RF-i?AN|o6F3#m`0U7')

Block.Enter(']SCo=lWj:-jL]XY#ww=m')
for count = 1, 2 do
  Block.Leave(']SCo=lWj:-jL]XY#ww=m')

  Block.Enter('#SKX1$kUwnHIl8Tbr5K[')
  nothing()
  Block.Leave('#SKX1$kUwnHIl8Tbr5K[')

  Block.Enter(']SCo=lWj:-jL]XY#ww=m')
end
Block.Leave(']SCo=lWj:-jL]XY#ww=m')

Block.Enter('PG^l?vYh7bj,u,){QH2J')
for i = 1, 3, 1 do
  Block.Leave('PG^l?vYh7bj,u,){QH2J')

  Block.Enter('0(h$.I6LP_c`+!-faBAZ')
  nothing()
  Block.Leave('0(h$.I6LP_c`+!-faBAZ')

  Block.Enter('PG^l?vYh7bj,u,){QH2J')
end
Block.Leave('PG^l?vYh7bj,u,){QH2J')

```

Tested with Firefox on Windows and Chrome on Android.
This issue does not depend on the browser.

**Stack Traces**

There is no error in the browser console.
Code generation works without generating any errors - except the generated code is not consistent in the way explained above.

**Additional context**

- Tested with a version from 2019 and tested again using the current release from July 1, 2021.
- All generated code is Lua code. The `Block.Enter()` and `Block.Leave()` functions have been added to the Lua environment. In their implementation, they add/drop one element (stack level) to a list. However, to understand and reproduce this issue, it is not required to run any Lua code, but only to read where the Enter/Leave calls are.

**Comment by NeilFraser** [comment]
I've removed "Lua" from the title, since this affects all languages equally.

Confirming the issue with the if/else.  This is a previously unknown bug.  PR #5290 will resolve this (there are two approaches, not sure which will be prefered by the team).

Also confirming the behaviour with the function call.  This was known behaviour when the feature was being implemented.  There was an argument that some applications would want to use the hanging prefix to keep track of the stack.

**Comment by bel2125** [comment]
Thank you.
So I have two options:

1) I could set "supressPrefixSuffix" for all blocks to false to have consistently two "Enter" statements everywhere.
This would be a defined behavior and I can build an application around this.

2) Set the "supressPrefixSuffix" to true for the if/else as well. Then there is only one "Enter" for loops and conditions, and I can work with "getSurroundParent" to find loops/conditions. This would also be a defined behavior I can work with.
If there are two "Enter" it is a bug in a Blockly library.

I assume that 2) is the recommended solution?

The general rule seems to be:
There can be multiple active blocks ("active" means between "Enter" and "Leave") if they are in different functions, 
but there are never two active blocks in a parent/child relation (getParent/getSurrondParent) - otherwise it is a bug in the code generator that should be reported.
Is this correct?

**Comment by NeilFraser** [comment]
The issue with the non-mutator 'if/else' block has been resolved (in the 'develop' branch, will be in the next release).  Its behaviour is now consistent with all other 'if' blocks.  This extra enter/exit was a straight-forward bug and was never intentional.

I'm inclined to leave the current behaviour regarding function calls (where multiple blocks might be entered) on the basis that it is helpful for tracking active stacks.
