### ISSUE TITLE
Custom generator codelab. Expecting valid order from member and lists_create_with block.

### ISSUE THREAD

**Issue by SebastianRohe** [google/blockly#5291]
Hi,

I followed all instructions of the tutorial: https://blocklycodelabs.dev/codelabs/custom-generator/index.html

In the block generator section I came across a few problems. I included all given code to generate the different block types and while i was testing everything seem to work fine expect when I tested the member and the lists_create_with block.

When I tested both I got the output: 

> Expecting valid order from block: ...

Because of this problem I was not able to create a proper JSON object.

I am not quite sure what went wrong.

Here is an additional screenshot: 
![Untitled](https://user-images.githubusercontent.com/79916430/128004948-c48a5aae-a719-4b24-adc0-911dff56fb25.png)

**Comment by SebastianRohe** [comment]
Issues solved.

**Comment by benglimus** [comment]
How was it solved? I am experiencing the same issue.
