### ISSUE TITLE
Update Tag module cleanup workflow to add instead of set labels

### ISSUE THREAD

**Issue by moniika** [google/blockly#5298]
**Is your feature request related to a problem? Please describe.**

The tag_module_cleanup github action workflow sets the list of labels to an explicit list which clears any existing labels, including those added by the `google-cla` bot.
This is convenient for 2 main reasons:
- This clears any labels added when the PR is created or between pushes and it can be easy to forget to re-add them
- The `google-cla` bot comments on the PR every time the `cla: yes` label is removed

![image](https://user-images.githubusercontent.com/6621618/128097295-78a0a7d1-7f3a-453b-92cd-754cc699e8d9.png)

**Describe the solution you'd like**

Update the github action script to add to the list of labels instead of setting.

**Describe alternatives you've considered**

Remove the set labels functionality and have the workflow only set the milestone. We would have to remember to manually add the `type: cleanup` label, but it would prevent conflicts with the `google-cla` bot.

**Comment by rachel-fenichel** [comment]
Robot fight!
https://media2.giphy.com/media/qCRhaWtcExo9W/giphy.gif?cid=ecf05e472qvvvxzq2w3wkq010jyjazu4465y5m3rqyg62g46&rid=giphy.gif&ct=g
