### ISSUE TITLE
domToText is not reversible with textToDom

### ISSUE THREAD

**Issue by acbart** [google/blockly#532]
... Unless you ignore assertions

    > var block = Blockly.mainWorkspace.getTopBlocks()[0];
    > var dom = Blockly.Xml.blockToDom(block);
    > var text = Blockly.Xml.domToText(dom);
    > var converted_dom = Blockly.Xml.textToDom(text)
    Assertion error: "Failure: Blockly.Xml.textToDom did not obtain a valid XML tree."

In the compressed version, this doesn't matter because ``goog.asserts.ENABLE_ASSERTS = false''. But on the uncompressed version where assertions are enabled, it throws up an error.

The reason is because the DOMParser returns a dom with a firstChild.nodeName that is not 'xml', but is instead 'block'. Perhaps that means that I should wrap the results of domToText with XML tags?

**Comment by RoboErikG** [comment]
domToText is usually only used for the entire workspace with workspaceToDom. See Storage.backupBlocks_ for an example. https://github.com/google/blockly/blob/2ed568ed62d362ea7465416f2adf89ff37d4b4cd/appengine/storage.js#L35

The blockToDom is used by workspaceToDom and also for temporary storage of blocks that aren't being saved, like in a copy operation.
