### ISSUE TITLE
Update require alias `Blockly.Events.Abstract`

### ISSUE THREAD

**Issue by moniika** [google/blockly#5336]
**Is your feature request related to a problem? Please describe.**
After updating to `goog.module` syntax, the alias for events:
```
const Abstract = goog.requireType('Blockly.Events.Abstract');
```
is no longer as clear in code as it was when we referred to the type as `Blockly.Events.Abstract.

**Describe the solution you'd like**

Update the require in all the files to:
```
const EventsAbstract = goog.requireType('Blockly.Events.Abstract');
```
or similar alias that follows the style guide.

**Comment by cpcallen** [comment]
Might `AbstractEvent` be an even more readable name?

The style guide seems to to permit reordering, as in this example:
```JS
// Out of sequence namespace-based aliases used to improve readability.
const SomeDataStructureModel = goog.requireType('identical.package.identifiers.models.SomeDataStructure');
const SomeDataStructureProto = goog.require('proto.identical.package.identifiers.SomeDataStructure');
```

**Comment by alschmiedt** [comment]
Before we make this change, are there any other names that we want to do this for?

**Comment by BeksOmega** [comment]
Pretty sure this can be closed because events are accessed via registries, and not requires. Any non-event require aliases can be handled on an ad-hoc basis.
