### ISSUE TITLE
Bad link to block styles script in guide

### ISSUE THREAD

**Issue by markdeloura** [google/blockly#5341]
**Where**

https://developers.google.com/blockly/guides/configure/web/themes?authuser=1#create_block_styles_script

**What**

  
- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

This script will take in a map of hues or hex values and will calculate the secondary and tertiary colours for them. The script can be found in the [theme_script](https://github.com/google/blockly/tree/master/theme_scripts) folder.

**Suggested content**

This script will take in a map of hues or hex values and will calculate the secondary and tertiary colours for them. The script can be found in the [scripts/themes](https://github.com/google/blockly/tree/master/scripts/themes) folder.

**Additional context**

Looks like the location of the script was moved as per [this issue](https://github.com/google/blockly/pull/4041) but link not updated in guide. Easy peasy :) Thanks!

**Comment by BeksOmega** [comment]
Thanks for the write up @markdeloura ! I've put up an internal PR to fix this =)

**Comment by BeksOmega** [comment]
Fixed!
