### ISSUE TITLE
Uncouple toolbox from XML system

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#5346]
**Is your feature request related to a problem? Please describe.**

Currently the toolbox/flyout is tightly coupled to the XML system because of the [createBlock_](https://github.com/google/blockly/blob/d4196c1105d3d7719e967edb0cecd0d7f76508c0/core/flyout_base.js#L665) method. This method expects XML, and is protected (making it part of the public API) so modifying the toolbox to support the new JSO system is difficult

The reason this is protected is because the [continuous toolbox uses it to recycle blocks](https://github.com/google/blockly-samples/pull/397). The reason we want to recycle blocks is because the domToBlock method is expensive (especially when one is rapidly scrolling through the toolbox).

Instead of these systems being tightly coupled, we would like them to not be. We would like developers to be able to specify their toolboxes completely using JSON and the new JSO serialization format.

**(A) Backwards compatible option**
We could create a method for converting from json -> xml, and then always pass the xml to the createBlock_ function. But the goal is to uncouple the toolbox and the XML so this option isn't great.

**(B) Non backwards compatible option**
We make the createBlock_ function private again. The flyout could handle creating the block, and we could add recycling to core. The problem is that recycling only really makes sense for the continous flyout. If you're just opening and closing different categories (not scrolling rapidly through them) performance isn't really an issue.

There's also the problem of not being sure when something should be recycled, vs when something should not be.

**(C) Non backwards commpatible option**
We could pass whatever we have (JSO or XML) to the createBlock_ function and expect it to deal with it. I don't like this option though because I feel the block notation should be internal to the core flyout/toolbox.

**Additional context**
There's also the question of: what things do we want to be able to exist in the flyout, and how do we want them to work? Do they also get recycled? Can flyout subclasses change how they are created?

Because the toolbox/flyout API is still so undefined at this point, it's probably best to leave as-is for now.

**Comment by gonfunko** [comment]
Closing this out. JSON or XML can be used now, and we've improved support for adding other types of things to the flyout and refactored recycling.
