### ISSUE TITLE
The injectDiv introduced in #512 isn't removed on workspace.dispose

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#536]
To reproduce:
On the blockly playground, in the js console:
1. call Blockly.getMainWorkspace().dispose()
2. call Blockly.inject again (e.g. Blockly.inject('blocklyDiv', {toolbox: '<xml><block type="controls_if"></block><block type="logic_compare"></block><block type="logic_operation"></block><block type="logic_boolean"></block><block type="logic_null" disabled="true"></block><block type="logic_ternary"></block></xml>'});)
3. Notice that the workspace is in the wrong spot and there are two divs with class injectionDiv in the dom.

**Comment by rachel-fenichel** [comment]
Fixed by #537
