### ISSUE TITLE
Empty English strings localized into "<!-- -->" in French

### ISSUE THREAD

**Issue by echoix** [google/blockly#5399]
**Describe the bug**

Some blocks, like the function block with or without outputs, are displayed differently in English and in French. 
In French, there is an extra `<!-- -->` on the left of the block.

**To Reproduce**

1. Open [Blockly Code Editor demo](https://blockly-demo.appspot.com/static/demos/code/index.html), in English.
2. Add a function block with an output and place it on the screen.
3. In the top right corner, change the language to French
4. Observe the left side of the block with an additional `<!-- -->`

You can also use the two following links to open the shared demo illustrating the problem:
https://blockly-demo.appspot.com/static/demos/code/index.html?lang=fr#czndiz
https://blockly-demo.appspot.com/static/demos/code/index.html?lang=en#czndiz

**Expected behavior**

There is no `<!-- -->` text displayed when not needed

**Screenshots**

![image](https://user-images.githubusercontent.com/27212526/130375203-e60f5b72-2109-454c-9243-9f53fdbb11ac.png)
![image](https://user-images.githubusercontent.com/27212526/130375214-0394b5d7-6154-4cd4-bb5c-eac9d0bf0736.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Google Chrome
 - Version 92.0.4515.159 (Build officiel) (64 bits)

**Stack Traces**

No error in stack trace if I looked at the good place.

**Additional context**

I did a little bit of investigation since I observed the problem when localizing a downstream project that we are about to release our version 2, that is using Blockly version 6.20210701.0. 
In French, there was an extra `<!-- -->` that weren't in my translated strings. 
The original problematic French string was `Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "<!-- -->";`
When searching in this repository's msg folder for `<!-- -->`, I didn't find any other language that was affected except French, where the following 7 strings have this value:

1. `Blockly.Msg["LISTS_GET_INDEX_TAIL"]`
2. `Blockly.Msg["LISTS_GET_SUBLIST_TAIL"]`
3. `Blockly.Msg["MATH_ONLIST_HELPURL"]`
4. `Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]`
5. `Blockly.Msg["PROCEDURES_DEFNORETURN_DO"]`
6. `Blockly.Msg["TEXT_CHARAT_TAIL"]`
7. `Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"]`

![image](https://user-images.githubusercontent.com/27212526/130375590-cade9285-a591-426d-b6ef-922e0912122a.png)

Other languages have some text in some of these 7 strings, and others leave it blank and have a comment saying it's untranslated (`Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated`).

Looking at the git history, the `<!-- -->` were introduced in commit aed9ba13a92a59d2083eef1a20c7227ef2231d34 (_Rebuild (#4733)_) on 2021-03-25 at 12:37 for the `msg/js/fr.js` file. For the `msg/json/fr.json` file, the commit introducing the changes was 21fd86a71a476f4b633f5bb12d891a7d59a2498b on 2021-02-15 at 08:40 (a translatewiki update).
Before the introduction of changes, there was either nothing, an empty string with the untranslated comment, or at one point `"ORDINAL_NUMBER_SUFFIX": "<!-- ---->"`.

In the issues I looked for, I couldn't see anything related except the discussion about the ordinal number suffix.

**Comment by NeilFraser** [comment]
Excellent bug report!  Looks like a one-off issue with whomever was doing French translations six months ago.  I've removed those translations from the translatewiki branch, and they should disappear from Blockly in the next release. 

It's possible that translatewiki's next push reverts the deletion by restoring these translations.  If this happens, then we need to delete them again, and notify them to explicitly pull.

**Comment by echoix** [comment]
> Excellent bug report!
Thanks for the compliment! I did my best, but couldn't find the strings like `PROCEDURES_DEFNORETURN_DO` in the translatewiki system, and I don't understand it yet, so couldn't fix it myself.

Could I be notified when the fixes are actually included in a release, so we could bump our requirements in the downstream project with that version?

**Comment by NeilFraser** [comment]
New releases are announced here: https://groups.google.com/g/blockly-announce

Although, it looks like we forgot to announce the July 2021 release on that newsgroup.  Will bring this up with the team on Monday.

In the mean time, you can hack your local copy by just editing msg/js/fr.js and setting the seven offending messages to "".  You can ignore the JSON files, they are part of the upstream build process.

**Comment by echoix** [comment]
I don't think hacking a local copy is possible, because blocky is a dependency included in our package.json resolved by npm for the users installing our node package, so it can't work that way, unless it's possible to overwrite these strings, but I'm not sure its worth that maintenance.

**Comment by NeilFraser** [comment]
Yup, they are globals.  So you should be able to just add this to your project somewhere:
```
Blockly.Msg["LISTS_GET_INDEX_TAIL"] = '';
Blockly.Msg["LISTS_GET_SUBLIST_TAIL"] = '';
Blockly.Msg["MATH_ONLIST_HELPURL"] = '';
Blockly.Msg["ORDINAL_NUMBER_SUFFIX"] = '';
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = '';
Blockly.Msg["TEXT_CHARAT_TAIL"] = '';
Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"] = '';
```

**Comment by NeilFraser** [comment]
But make sure that you only do the above when your application is in French!

**Comment by echoix** [comment]
Since the project didn't use the `Blockly.Msg["XXX_YYY"]` syntax in the localization files, but rather `Blockly.Msg.XXX_YYY`, I wasn't sure it would work. But I added this to the end of my `fr.js` file where we localize additional custom blocks, and it seems to work. I might temporarily patch it this way.

**Comment by BeksOmega** [comment]
> Although, it looks like we forgot to announce the July 2021 release on that newsgroup. Will bring this up with the team on Monday.

That's my bad. I missed that the internal release docs say we're supposed to bcc the announce group :/
