### ISSUE TITLE
Multiline input fields don't group edits

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#5437]
**Describe the bug**

Multilinee input fields should group all of their edits so that they can be undone at once.

**To Reproduce**

1. Go to the playground, and open the test blocks toolbox.
2. Drag out a multiline input field from the Fields -> Defaults category.
3. Edit the text to be "testing"
4. Undo using ctrl + z. Observe how this only undoes a single letter.

**Expected behavior**

The entire edit should be undone.

**Comment by gonfunko** [comment]
This no longer repros.
