### ISSUE TITLE
How to limit the workspace can only be extended to the bottom right corner?

### ISSUE THREAD

**Issue by ErvenDai** [google/blockly#5477]
How to limit the workspace can only be extended to the bottom right corner?

**Comment by alschmiedt** [comment]
Hello!

Could you please move your question to the [forum](https://groups.google.com/g/blockly?pli=1)? Having all questions on the forum helps us keep our issue list clean and allows you to get more help from other developers. When you ask your question on the forum, can you please add more information on what you are trying to accomplish or what is exactly going wrong? If you can, an image is usually helpful as well : ) 

Thanks!
