### ISSUE TITLE
how can i change the category arrow color?

### ISSUE THREAD

**Issue by mrredo-and-josetrindade1** [google/blockly#5481]
how could a change the color of this arrow? with xml
![unknown](https://user-images.githubusercontent.com/90334854/133672849-670e825a-61a7-42be-a061-1153853ca1b2.png)

**Comment by alschmiedt** [comment]
Hello!

You might be able to do this using [css filters](https://stackoverflow.com/questions/7415872/change-color-of-png-image-via-css) or you can add your own icon and style it by following [this guide](https://blocklycodelabs.dev/codelabs/custom-toolbox/index.html?index=..%2F..index#4).

If you have any more questions, please ask them on the [forum](https://groups.google.com/g/blockly?pli=1). We like to keep all of our questions in one place and this will allow other developers a chance to offer their insights as well. Thanks!
