### ISSUE TITLE
Reexport `global.globalThis` as `global` from `Blockly.utils`

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#5503]
The default export from `Blockly.utils.global` was renamed `globalThis` in PR #5451 and then reexported by `Blockly.utils` as `Blockly.utils.global.globalThis` in PR #5465.

For consistency with our plan for the Blockly legacy namespace going forward, `core/utils.js` should instead export it under its old name:

```
exports.global = global.globalThis;
```

This may involve undoing some of the changes made to the `dev-tools` package to accommodate these changes in the first place.

**Comment by NeilFraser** [comment]
Heh, without being aware of this bug, I just filed #5506 about this same issue, but with a different proposed solution.
