### ISSUE TITLE
Console errors while loading playground

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#5542]
**Describe the bug**

Console errors while loading playground

**To Reproduce**

1. Go to 'https://google.github.io/blockly/tests/playground.html'
2. Verify console for errors

**Expected behavior**

Expecting no console errors

**Screenshots**

![image](https://user-images.githubusercontent.com/56336353/134903318-abf9764f-5c57-4b79-83ed-a625f7c8b098.png)

**Desktop (please complete the following information):**
OS: [ChromeOS]
Browser [chrome]
Version [93.0.4577.85 (Official Build) (64-bit)]

Errors:
Uncaught TypeError: Cannot add property TestHats, object is not extensible
    at test_themes.js:14

**Comment by NeilFraser** [comment]
Objects (but not functions) which are exported appear to have preventExtentions called upon them by goog.module.  Thus:
```
Object.isExtensible(Blockly.Themes) -> false
Object.isExtensible(Blockly.ThemeManager) -> true
```
test_themes.js attempts to add a new property on Blockly.Themes, and fails accordingly.

**Comment by gonfunko** [comment]
This appears to have been resolved.
