### ISSUE TITLE
Project cereal - Comment is not loading 

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#5543]
**Describe the bug**

Project cereal - Comment is not loading 

**To Reproduce**

1. Go to 'https://google.github.io/blockly/tests/playground.html'
2. Right Click on workspace
3. Add a comment and Save JSON
4. Refresh the page and Load

**Expected behavior**
Comment needs to be loaded as in Save XML

**Screenshots**
https://screencast.googleplex.com/cast/NTIwNjg5MDgyMjc2MjQ5Nnw4MDI3MWFlZC0zNQ

**Desktop (please complete the following information):**
OS: [ChromeOS]
Browser [chrome]
Version [93.0.4577.85 (Official Build) (64-bit)]

**Comment by alschmiedt** [comment]
Thanks for reporting! 

I believe this is working as intended. We are planning on moving workspace comments into their own plugin with their own serializer, so Beka didn't add this functionality to core. Developers can work around this by adding their own serializer.
