### ISSUE TITLE
Blocks which are dragged from RTL positioning is not as BAU

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#5545]
**Describe the bug**

Blocks which are dragged from RTL positioning is not as BAU

**To Reproduce**

1. Go to 'https://google.github.io/blockly/tests/playground.html'
2. Select RTL positioning
3. Drag and drop a block
4. Block should be positioned next to flyout as in PROD

**Expected behavior**

Block positioning should be as in PROD

**Screenshots**

Testing environment Screencast- https://screencast.googleplex.com/cast/NjUxMDQzNDQzNTcyNzM2MHw2YTkzZGEzOC1kNA
PROD screencast for reference- https://screencast.googleplex.com/cast/NjE2ODg0NjE5MDc3MjIyNHxlNDU2MWI2Ni01OA

**Desktop (please complete the following information):**
 OS: [ChromeOS]
Browser [chrome]
Version [93.0.4577.85 (Official Build) (64-bit)]

**Comment by BeksOmega** [comment]
Thank you for the bug Divya :D I figured out a fix for this, but I'm not sure which branch to put the PR against. @alschmiedt ?

**Comment by alschmiedt** [comment]
Develop please : ) We just merged goog_module into develop 2 minutes ago.
