### ISSUE TITLE
Browser contextual menu displayed over Blockly contextual menu in Safari

### ISSUE THREAD

**Issue by gonfunko** [google/blockly#5552]
**Describe the bug**
When right-clicking on a block stack or the workspace in Safari 15.0, the browser's contextual menu is displayed atop Blockly's contextual menu, obscuring the latter.

**To Reproduce**
- Open https://blockly-demo.appspot.com/static/tests/playground.html
- Right-click on the workspace in Safari 15
- Notice that the browser contextual menu is displayed atop Blockly's

**Expected behavior**
- Blockly's contextual menu is displayed

**Screenshots**
<img width="256" alt="Screen Shot 2021-09-27 at 3 11 03 PM" src="https://user-images.githubusercontent.com/667459/134992281-76cad7aa-79f9-43f7-a090-8ba20a719be7.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Browser Safari
 - Version 15.0

**Comment by alschmiedt** [comment]
This looks like it is not a problem with this release, but with the new update to Safari which AFAICT came out earlier this month. This should still be fixed before our next official release since it is a renders context menus useless in Safari 15.

**Comment by gonfunko** [comment]
This appears to have been resolved as of Safari 15.4.
