### ISSUE TITLE
Duplicating blocks in RTL duplicates them offscreen

### ISSUE THREAD

**Issue by gonfunko** [google/blockly#5553]
**Describe the bug**
Duplicating a block via the context menu in an RTL workspace duplicates the block outside of the workspace viewport, requiring you to scroll to find the duplicate block.

**To Reproduce**
- Open https://google.github.io/blockly/tests/multi_playground.html
- In an RTL workspace, drag out a block
- Right click and choose Duplicate in the contextual menu
- Observe that the duplicate block is not visible
- Scroll around the workspace until you find it

**Expected behavior**
- The block is duplicated within the viewport, near to the block it was duplicated from

**Additional context**
This happens in Safari and Chrome on macOS Big Sur. It appears to be a regression from Blockly 6, which duplicates blocks in RTL workspaces near the original block.

**Comment by BeksOmega** [comment]
Probably the same problem as #5545 I can take a look tomorrow if nobody grabs it.
