### ISSUE TITLE
No preview shown for Block Factory

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#5556]
**Describe the bug**

No preview shown for Block Factory

**To Reproduce**

1. Go to 'http://google.github.io/blockly/demos/blockfactory/index.html'
2. Edit the name and verify preview

**Expected behavior**

Preview should be shown

**Screenshots**

![Screenshot 2021-09-28 12 07 25 PM](https://user-images.githubusercontent.com/56336353/135038232-f5123214-4aad-470e-99d0-d52b47b8669f.png)

**Desktop (please complete the following information):**
 OS: [ChromeOS]
Browser [chrome]
Version [93.0.4577.85 (Official Build) (64-bit)]

**Comment by NeilFraser** [comment]
Hmm, this version works fine:
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html
But github.io is broken immediately upon loading.

**Comment by alschmiedt** [comment]
http://google.github.io/blockly/demos/blockfactory/index.html is currently pointing at develop, while the appspot site is pointing at master. If we aren't seeing it on the appspot site then it means that the problems we are running into are coming from our current release.

**Comment by MNSDivya** [comment]
Preview is shown now. Not sure what made this change.
![image](https://user-images.githubusercontent.com/56336353/135292107-ba8eeb90-65c5-4d3b-b800-07d9f3122418.png)

**Comment by alschmiedt** [comment]
I just tried it and I think it works when you load in a block. When you first go to the page without a block loaded it is still throwing an error and not displaying the preview.

**Comment by cpcallen** [comment]
Looking at this at the moment.  This code from `factory.js` is not going to work any more, though I'm not yet certain that it's the source of the error:

```JS
  // Backup Blockly.Blocks object so that main workspace and preview don't
  // collide if user creates a 'factory_base' block, for instance.
  var backupBlocks = Blockly.Blocks;
  try {
    // Make a shallow copy.
    Blockly.Blocks = Object.create(null);
    for (var prop in backupBlocks) {
      Blockly.Blocks[prop] = backupBlocks[prop];
    }
```
