### ISSUE TITLE
"Import Custom Blocks" on Workspace Factory produces spurious "An imported block uses the same name" errors when loading JS

### ISSUE THREAD

**Issue by MNSDivya** [google/blockly#5570]
**Describe the bug**

"Import Custom Blocks" on Workspace Factory is not working appropriately

**To Reproduce**

1. Go to 'http://google.github.io/blockly/demos/blockfactory/index.html'
2. Create configuration in Block factory and verify the preview
3. Navigate to Block Exporter and select the preview Block
4. Select Block Definition as JSON and Generatir Stub as JavaScript 
5. Click on Export and verify the files are downloaded successfully
6. Navigate to WOrkspace factory and Click on Import Custome blocks
7. Select either by JSON or Javascript - select respective file 
8. Issue 1- JSON file says "Cannot read blocks from file"(image 1)
 Issue 2- Javascript file doesnot show any blocks(image 2)

**Expected behavior**

Import custome blocks should work properly

**Screenshots**
![image](https://user-images.githubusercontent.com/56336353/135431872-84f01635-1cea-40bc-b92f-54c0b6973c94.png)
![image](https://user-images.githubusercontent.com/56336353/135432661-8c0cd06c-2e6e-4c5e-8b3f-0323e6db6614.png)

**Desktop (please complete the following information):**
OS: [ChromeOS]
Browser [chrome]
Version [93.0.4577.85 (Official Build) (64-bit)]

**Comment by cpcallen** [comment]
I get the same errors at https://blockly-demo.appspot.com/static/demos/blockfactory/index.html, so I don't think this is `goog.module` related.

**Comment by cpcallen** [comment]
OK, specifically:

* Re: issue 1: I get the message "Cannot read blocks from file" and the following console error when loading JSON in both the old and new versions (line numbers ±1):
  ```
  SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at Object.FactoryUtils.defineAndGetBlockTypes (factory_utils.js:841)
      at FileReader.reader.onload (wfactory_controller.js:1206)
  ```
  This happens despite the JSON block definition appearing to be valid (it is certainly valid JSON, at least!)

* Re: issue 2: when I load the JavaScript block definition into either old or new version I get the message "An imported block uses the same name as a block already in your toolbox. Are you sure you want to override the currently defined block?", despite my custom block not having been shown in the toolbox toolbox previously.  Nevertheless, clicking "OK" does cause the custom block to be imported successfully and appear in the toolbox.  Repeating steps 6–8 causes a second copy to appear.  So it seems that there is a bug of some kind here (the apparently spurious "same name" message), but the reproduction steps do not seem to be entirely correct.  @MNSDivya: can you clarify?

**Comment by MNSDivya** [comment]
@cpcallen For issue 2, I have selected Javascript under "Import custome blocks". 
I can confirm that there is no pop up shown for me. But the .js file is added successfully without showing any blocks on the workspace. 
Hope I have answered your query.

**Comment by alschmiedt** [comment]
Looked into this a bit. AFAICT the bug is coming from [this function](https://github.com/google/blockly/blob/4e87be706906281177c8f07c120e543ee6df1c6a/demos/blockfactory/factory_utils.js#L822). The JSON going in is correct, however when it comes out it is incorrect and failing in `JSON.parse`. I looked back at a 2019 release and this is not working there as well.

**Comment by cpcallen** [comment]
And upon further investigation, issue 1 as described above was already reported as #697.  Please use that issue for any further discussion of the JSON loading bug.

Leaving this open but retitling to be specific to issue 2, which requires further investigation.

**Comment by tashee** [comment]
WAI
