### ISSUE TITLE
Adding/removing a Warning while editing a field causes field misalignment

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#5572]
**Describe the bug**

Calls to `BlockSvg.prototype.setWarningText` while a field is being edited will cause the field to be misaligned with the underlying block.

**To Reproduce**

1. Go to [the Block Factory demo](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html) (note: not, for now, the google.github.io version, as this bug is masked there by #5556).
0. Click on the 'name' field.
0. Type `x`
0. Click on empty part of workspace.
0. Click on the 'name' field again.
0. Type `block_type`
0. Click on empty part of workspace again.

**Expected behavior**

When the warning disappears, the field in which we are entering text moves in alignment with the field displayed as part of the block.

**Screenshots**

https://user-images.githubusercontent.com/5603958/135534588-f3e15906-1ec1-4b10-9d4a-d02f6c321c91.mov

**Desktop:**
 - OS: macOS
 - Browser Chrome
 - Version 93.0.4577.82 (Official Build) (x86_64)

**Stack Traces**

None.

**Comment by gonfunko** [comment]
This no longer repros.
