### ISSUE TITLE
Move context menu items to use JSON

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#5579]
**Is your feature request related to a problem? Please describe.**

The XML serializaation system is being iceboxed, so internal usages of the XML system should be moved to the new JSON system.

In particular, the context menu system should be moved to use JSON.

**Describe the solution you'd like**

A new [callback factory](https://github.com/google/blockly/blob/a9f9086e03745f010b798b8fcb880d15bad40159/core/contextmenu.js#L190) which uses JSON should be defined, and the existing one should be deprecated.

All uses of the existing callback factory should be moved to the new JSON one.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by johnnesky** [comment]
I ran into this while experimenting with designing struct/record definition blocks. I was using procedures as a model, and I saw that they could generate call blocks via the context menu, and I figured it would be nice to be able to generate instantiation blocks from a struct definition block. I suppose context menu support for adding a related block to an existing block in the workspace is more of a nice-to-have than a blocker. Probably everything should be accessible without a context menu, especially for phones/tablets.
