### ISSUE TITLE
Facilitate implementation of an advanced section in a block

### ISSUE THREAD

**Issue by Chrisb0606** [google/blockly#5582]
We'd like to implement, in an easier manner, new blocks with an advanced section.

Our main objective is to offer the simplest block as much as we do.
To achieve that, we've implemented many blocks with 2 or 3 fields and a checkbox field named "advanced options". This button trigger a mutator and display advanced options. These options are considered to be reserved for advanced users. This a typical UI sugar, we can find in many applications, to not lost first users, on the one hand, and, on the other hand, allows advanced users to find expert parameters.
Please find a concrete example in the following pictures:
The compact block:
![Screen Shot 2021-10-04 at 21 41 16](https://user-images.githubusercontent.com/47278321/135914187-4c6f3e8d-414c-4356-9feb-cab77246b079.png)
When we click on advanced options the bloc self extends:
![Screen Shot 2021-10-04 at 21 41 28](https://user-images.githubusercontent.com/47278321/135914216-1d32c75e-dc54-4711-9d13-db5d8e5a3652.png)

A way to implement in a simpler way directly in the block's JSON definition could be :
```
Blockly.Blocks["question_true_false"] = {
  init: function() {
    this.jsonInit({
      type: "question_true_false",
      message0: "%{BKY_QUESTION_TRUE_FALSE_MESSAGE}",
      args0: [
        {
          type: "input_dummy",
        },
        {
          type: "input_value",
          name: "text",
          align: "RIGHT",
        },
        {
          type: "input_value",
          name: "solution",
          check: "Boolean",
          align: "RIGHT",
        },
        {
          type: "field_checkbox",
          name: "moreOptions",
          checked: false,
          advancedOptions : true // this option could tell to activate advancedOptions defined below **
        },
        advancedOptions : 
        { //this subsection could define all block's component to display when advancedOptions has been checked
           {
             type: "field_dropdown",
             name: "display",
             options: ["external"...]
           }
          {
             type: "field_variable",
             name: "answer",
          },
      }
...
      ],
      inputsInline: false,
      previousStatement: null,
      ...
    });
  },
};

```
It could, under the hood, behave like the mutator method.

That feature could be really great to simplify writing code to define blocks with advanced options.

Thanks
Chris

**Comment by rachel-fenichel** [comment]
This issue is asking for a general-purpose way to define groups of fields that can be added to blocks as an "advanced" section. [Mutators](https://developers.google.com/blockly/guides/create-custom-blocks/extensions) already allow you to do this. We suggest defining a single mutator that adds or removes all of the fields in your advanced section, and then using that same mutator for each of your block definitions.

This use case is not general enough to add a new layer to the block definition API.
