### ISSUE TITLE
Using Blockly in jquery/bootstrap modal

### ISSUE THREAD

**Issue by jano42** [google/blockly#56]
If using Blockly in a modal created by jquery, and bootstrap; there are two artifacts which are hard to debug.

Maybe this issue should be placed into a special chapter in blockly documentation for Bootstrap integration fixes.

Issue 1. all drop down appears behind the modal.
Solution 1 : Just update the page css 

```
.blocklyWidgetDiv {
    z-index: 9999 !important;
}
```

Issue 2 : all input fileds (numbers, strings,...) are not working (never focused)
Solution 2 : when the modal is shown, apply this fix 

Boostrap 3

```
$('div#modal-blockly').on("shown.bs.modal", function () {
   //fix input field
   $(document).off('focusin.modal');
}
```

Boostrap 2

```
$('div#modal-blockly').on("shown", function () {
   //fix input field
   $(document).off('focusin.modal');
}
```

**Comment by moniika** [comment]
Appears to be fixed.
