### ISSUE TITLE
Changing workspace's language doesn't change dropdown values in blocks.

### ISSUE THREAD

**Issue by Chrisb0606** [google/blockly#5610]
Changing workspace's language doesn't change dropdown values in blocks.

I've implemented a language switcher to change workspace by following https://blockly-demo.appspot.com/static/demos/code/index.html approach. I've added a locale Blockly file to implement languages values of my personnal blocks as recommended.

I've coded as follows when I change language: 
`    workspace.dispose();
      if (locale == "fr") {
        Blockly.setLocale(Fr);
        Blockly.setLocale(CustomFr);
      } else {
        Blockly.setLocale(En);
        Blockly.setLocale(CustomEn);
      }    
      workspace = Blockly.inject(blocklyDiv);
`
When I change the language, the workspace takes into accont the language changing by changing all category titles and blocks excepted as expected. But after looking into details, it appears that dropdown text doesn't change in my blocks whereas dropdown texts in native Blockly blocks change well.
There are 3 reasons, why I suppose this is a bug:
- In the previous Blockly versions, if I remember well, I didn't notice that wrong behavior
- The block texts outside the dropdown changes correctly for native blocks as well as mine. The bug is limited to my block dropdown texts.
- They are no difference between how I've implemented translations for text included directly in block "shape" comparing to block dropdown texts:
Example of code (illustrated by the following screenshots)
for CustomEN:
   LINE_LINE: "line",
   LINE_SEGMENT: "segment",
   LINE_ARROW: "arrow",
   LINE_DOTTED: "dotted",
   LINE_MESSAGE: "%1 passing through%2 and%3",
for CustomFR:
  LINE_LINE: "droite",
  LINE_SEGMENT: "segment",
  LINE_ARROW: "flèche",
  LINE_DOTTED: "pointillé",
  LINE_MESSAGE: "%1 passant par%2 et%3",

.json:
`var blocklyLineJson = {
  type: "line",
  message0: "%{BKY_LINE_MESSAGE}",
  args0: [
    {
      type: "field_dropdown",
      name: "type",
      options: [
        ["%{BKY_LINE_LINE}", "line"],
        ["%{BKY_LINE_SEGMENT}", "segment"],
        ["%{BKY_LINE_ARROW}", "arrow"],
        ["%{BKY_LINE_DOTTED}", "dotted"],
      ],
    },
    {`

**Expected behavior**

Blocks dropdown texts change as well as other text in blocks.

**Screenshots**
When the first loading of the workspace, it works well (dropdows are in good language), I obtain:
<img width="463" alt="Capture d’écran 2021-10-17 à 22 54 53" src="https://user-images.githubusercontent.com/47278321/137644663-30b16201-e6bf-405c-a82a-9bff27be9d3e.png">

When I change  the workspace language by another one (implemented through dispose(), inject() and  setLocale detailed above, I obtain: 
<img width="636" alt="Capture d’écran 2021-10-17 à 22 55 05" src="https://user-images.githubusercontent.com/47278321/137644774-44346f9d-225e-47cf-8795-d930bcdd0154.png">
The purple block text changes but without changing the dropdown options.

If I reload the page in browser in the opposite way (french language in the first loading and then english), the dropdown texts stay in french: Therefore, the bug seems to be consistent.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome Firefox, Safari in their last versions

Thanks a lot for your support.
Chris

**Comment by nico-oops** [comment]
Was there a solution for this  ?
