### ISSUE TITLE
AccessibilityAccessibility

### ISSUE THREAD

**Issue by SebCanet** [google/blockly#564]
Hi,
I created [Blockly@rduino](https://github.com/technologiescollege/Blockly-at-rduino), thanks to your work and Gasolin's [BlocklyDuino](https://github.com/BlocklyDuino/BlocklyDuino).

French & Quebec teacher likes it and use it with pupills from 9 to .... years old. I also had enhancement request from a lot of different countries, thanks to your multilingual possibilities.

I'm also working with kids with vision problems, a lot resolved with zoom. BUT, yes there's a 'but', I would like to know if you could add a speech plugin, or maybe something to generate text as it generates java/python/LUA code. And in this particular workspace add the Tex2speech API (like this one : [https://developers.google.com/web/updates/2014/01/Web-apps-that-talk-Introduction-to-the-Speech-Synthesis-API](https://developers.google.com/web/updates/2014/01/Web-apps-that-talk-Introduction-to-the-Speech-Synthesis-API) ) ?

Thanks for your work !!!

**Comment by rachel-fenichel** [comment]
@seanlip @madCode

**Comment by madCode** [comment]
Hi @SebCanet! I hear your concern. There is a screen-reader accessible version of Blockly called "[AccessibleBlockly](https://github.com/google/blockly/tree/master/accessible)"! Hopefully that should address some of your concerns. You and your students can play around with it [here](https://accessible-blockly.appspot.com/demos/accessible/index.html) and see if it works for you.

**Comment by NeilFraser** [comment]
@SebCanet Please note that AccessibleBlockly is still under active development and we don't currently consider it to be ready for blind students.  But @seanlip is working really hard on it and we hope to release it officially soon.  In the meantime if you don't mind sharp edges and unintuitive interfaces, you are welcome to try it out and provide feedback.
