### ISSUE TITLE
Assign requested reviewers to pull requests

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#5643]
**Is your feature request related to a problem? Please describe.**
We could not find an easy way to view all the requested reviews for a single person. This was leading to pull requests getting lost and forgotten about. We still want to use [GitHub's auto assigner](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team), however we also want to be assigned PRs.

**Describe the solution you'd like**
A GitHub action that will automatically assign the requested reviewers to the pull request.

**Describe alternatives you've considered**
There are GitHub actions available that will randomly assign a PR to a person (instead of requesting a review like GitHub). However, I could not find one that would take into account whether or not a developer had a status of busy or not.

**Additional context**

**Comment by rachel-fenichel** [comment]
The check script is now failing with "Resource not accessible by integration" ([example run](https://github.com/google/blockly/runs/4073818478?check_suite_focus=true)).

**Comment by cpcallen** [comment]
> The check script is now failing with "Resource not accessible by integration" ([example run](https://github.com/google/blockly/runs/4073818478?check_suite_focus=true)).

This is the issue reported in #5659, though I am surprised to discover it applies to PRs from project contributors.
