### ISSUE TITLE
Add test for renamings.js

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#5645]
**Is your feature request related to a problem? Please describe.**
We have a new [renamings.js](https://github.com/google/blockly/blob/develop/scripts/migration/renamings.js) file that we plan on using to help developers update easier. We need to make sure this files is formatted properly when it is updated. See google/blockly-samples#924 for more information. 

**Describe the solution you'd like**
A test that is run during CI to check that the format of `renamings.js` is correct and valid.

**Describe alternatives you've considered**

**Additional context**

**Comment by cpcallen** [comment]
Closed by #5980.
