### ISSUE TITLE
changedTouches is undefined

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#5688]
[Blockly.TouchGesture.prototype.getTouchPoint](https://github.com/google/blockly/blob/master/core/touch_gesture.js#L320) sometimes throws an error due to e.changedTouches being undefined.  Thus subscripting [0] fails.

Discovered via Blockly Games Maze.  Currently unable to recreate.  Multiple reports from iOS and Android:
* Mozilla/5.0 (Linux; Android 8.0.0; BAC-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Mobile Safari/537.36
* Mozilla/5.0 (Linux; Android 10; JSN-L22) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.80 Mobile Safari/537.36
* Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1

**Comment by jschanker** [comment]
Also, undo is sometimes broken on block duplication.

Steps to reproduce:
1. Go https://blockly.games/maze.
2. Drag in a move forward block.
3. Right-click the dragged in block and click duplicate.
4. Open up the console and observe the warning, "Moved object in bounds but there was no event group. This may break undo." 
5. Try using Ctrl + Z, and observe that the warning appears again.

Not sure if the use of duplicate was intended as you can delete the one you start with but cannot duplicate it from the context menu.

**Comment by NeilFraser** [comment]
@jschanker The issue you raised is valid, but unrelated to this changedTouches issue.  I've filed it as #5689.

**Comment by NeilFraser** [comment]
Additional instrumentation reveals these are PointerEvent objects (not TouchEvent) with pageX properties set to `0` and pageY properties set to some positive number.
