### ISSUE TITLE
Keep the operator precedence when collapse a block

### ISSUE THREAD

**Issue by carloslfu** [google/blockly#57]
![operator-precedence](https://cloud.githubusercontent.com/assets/5993168/5993040/4f6fde08-aa10-11e4-9e50-83d09041706d.jpg)

**Comment by NeilFraser** [comment]
Do you have suggestions on how to achieve this?  In this example, parentheses would be nice, but in most cases that would be awful (e.g. "if ((x) = (true)) do".  I don't see a solution here that doesn't make things worse.

**Comment by carloslfu** [comment]
I have tested this solution and should be good:
```
Blockly.Block.prototype.toString = function(opt_maxLength) {
  var text = [];
  for (var i = 0, input; input = this.inputList[i]; i++) {
    for (var j = 0, field; field = input.fieldRow[j]; j++) {
      text.push(field.getText());
    }
    if (input.connection) {
      var child = input.connection.targetBlock();
      if (child) {
        /////------------------------------
        // could be declared in block definition like (in 'math_arithmetic' case):
        /*
          this.setPrecedence(true); //default false
          this.setPrecedenceOrder({'ADD' : 0,
                             'MINUS': 0,
                             'MULTIPLY': 1,
                             'DIVIDE': 1,
                             'POWER': 2
                             });
          this.getPrecedence = function(){
            return this.precedenceOrder[this.getFieldValue('OP')];
          };
        */
        //simulate blocks using precedence (for testing)
        this.precedence = false; //default value
        if (this.type == "math_arithmetic") {
          this.precedence = true;
          this.precedenceOrder = {'ADD' : 0,
                             'MINUS': 0,
                             'MULTIPLY': 1,
                             'DIVIDE': 1,
                             'POWER': 2
                             };
          this.getPrecedence = function(){
            return this.precedenceOrder[this.getFieldValue('OP')];
          };
        }
        if(child.type == "math_number") {
          child.precedence = false; //if not precedence , it have 99 order
        } else if (child.type == "math_arithmetic") {
          child.precedence = true;
          child.precedenceOrder = {'ADD' : 0,
                             'MINUS': 0,
                             'MULTIPLY': 1,
                             'DIVIDE': 1,
                             'POWER': 2
                             };
          child.getPrecedence = function(){
            return this.precedenceOrder[this.getFieldValue('OP')];
          };
        } else {
          //others like 'remainder of' block, this may be declared in each math block
          child.precedence = true;
          child.getPrecedence = function() {
            return -1;
          } 
        } 
        ///////////------------------------------------

        //compare precedence
        if (this.precedence) {
          var childPrecedence = child.precedence?child.getPrecedence():99;
          var precedenceCondition = childPrecedence < this.getPrecedence();
        }
        if (this.precedence && precedenceCondition) {
          text.push('(' + child.toString() + ')');
        } else {
          text.push(child.toString());
        }
      } else {
        text.push('?');
      }
    }
  }

  text = goog.string.trim(text.join(' ')) || '???';
  if (opt_maxLength) {
    // TODO: Improve truncation so that text from this block is given priority.
    // TODO: Handle FieldImage better.
    text = goog.string.truncate(text, opt_maxLength);
  }
  return text;
};
```

**Comment by gmp26** [comment]
Given the discussion in https://developers.google.com/blockly/custom-blocks/operator-precedence, it is surely a bug for blockly to interpret `[i * [j + 5]] as [i * j]+5`.

Actually it's a show stopper. :(

**Comment by moniika** [comment]
This is still an issue.
![image](https://user-images.githubusercontent.com/6621618/72394239-5e444100-36ea-11ea-93c2-7a3e49c5679e.png)

**Comment by gmp26** [comment]
This just popped up in my mail again. In case it's under review, here's what I think should happen :)

The block [2 + 4] should behave like [6] no matter what the context. Blocks imply parenthesis, and Blockly should therefore have absolutely no knowledge of operator precedence. 

Changing the 1 to a 3 in the example to show the difference:
If I want 3 x 2+4 with normal maths precedence of x over +, I need the blocks to be [[3 x 2] + 4].
If I want  3 x (2 + 4), I need the blocks to be [3 x [2 + 4]].
That should be fairly clear and very easy to explain to students. 

Blockly builds a tree of operations directly, and in that regard it is exactly like Lisp. 
Lisp also has no concept of operator precedence as the parentheses there are explicit and never implied.
In Lisp syntax we would have (+ (* 3 2) 4) to give 10, and (* 3 (+ 2 4)) to give 18.

Hope that helps.

**Comment by MNSDivya** [comment]
Issue still persists.

**Comment by samelhusseini** [comment]
I've taken a look at this, and it's a much simple problem to tackle given we now have an AST in Blockly.
Here's the solution I came up with: 

Run through the Blockly AST and create the text of ``toString``. If we pass over a connection that has a Number or Boolean check, add parenthesis. Finally remove any simple parenthesis around a single field, eg: ``((10) * (50)) + (10)`` turns into ``(10 * 50) + 10``.

**Comment by samelhusseini** [comment]
Fixed.
