### ISSUE TITLE
Enable a block to change connectors while dragging

### ISSUE THREAD

**Issue by mark-friedman** [google/blockly#5720]
**Is your feature request related to a problem? Please describe.**

With the current Blockly implementation, if I change a block's connections while dragging (via, say, an event handler) it doesn't correctly modify it's insertion marker block, nor does it correctly update the insertion marker manager's set of available connections.  In the former case is throws an error when the obsolete marker block approaches a potential connection.  In the latter case, it doesn't highlight all the potential connection points.

**Describe the solution you'd like**

I would like to be able to change a block's connectors while dragging.  More specifically:
-  I would like` InsertionMarkerManager.showInsertionMarker_()` to recreate the insertion marker block in the case where its call to `imBlock.getMatchingConnection()` throws an error.
- I would like `InsertionMarkerManager.getCandidate_()` to update its available connections.

Note that I intend to file a PR for these changes.

**Describe alternatives you've considered**

**Additional context**

I would like to be able to create a "chameleon" block which would have previous, next and output connections when
created, so that it could be used as either a value or a statement. Once it is actually connected it would change to an appropriate shape depending on its context.  When it is dragged out of its connection I would like it to be able to change back to a state where it has all the connectors again.  

Note that this is somewhat of a sibling issue with #5691.  With that feature and this one I would be able to have a dynamic chameleon block.

**Comment by alschmiedt** [comment]
Closing since it was resolved in #5722.
