### ISSUE TITLE
Strip Closure Library licence from compressed file

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#5732]
Have we (or can we get) permission to strip the "Copyright The Closure Library Authors" copyright notice from the compiled output should `closure/goog/base.js` (or, after #5721 lands, `closure/goog/base_minimal.js`) be included in the compiler input?

(See issue #2412 which dealt with this same question in respect to the Google LLC and MIT notices.)

**Comment by cpcallen** [comment]
(This is mainly for consistency rather than filesize, since the notice only appears once in `blockly_compressed.js`—but it's a bit funny—and possibly confusing—for that to be the only copyright notice in the entire file.)

**Comment by NeilFraser** [comment]
If the roadmap involves the eventual removal of `closure/goog/base.js` in the future, then I'd advise accepting the temporary inclusion of this notice.

I have no special knowledge here; just an aversion to poking things which have the potential to backfire and cause major regressions for legal reasons.

**Comment by gonfunko** [comment]
Closing since closure/* is no more.
