### ISSUE TITLE
Not able to change color of Blocks in blockly

### ISSUE THREAD

**Issue by sourabhmandal** [google/blockly#5747]
**Describe the bug**
Changing the colour in block description doesn't reflect on blocks and renders with the same default colour i.e Green
**To Reproduce**

Define a block in XML
```
<Block type="contract_init">
        <Field disabled name="TITLE">
          main
        </Field>
</Block>
```

Define Generator code
```
Blockly.Rust["contract_init"] = function (block) {
  // Define a procedure with a return value.
  var funcName = Blockly.Rust.variableDB_.getName(
    block.getFieldValue("TITLE"),
    Blockly.Procedures.NAME_TYPE
  );
  var branch = Blockly.Rust.statementToCode(block, "STACK");

  if (Blockly.Rust.STATEMENT_PREFIX) {
    var id = block.id.replace(/\$/g, "$$$$"); // Issue 251.
    branch =
      Blockly.Rust.prefixLines(
        Blockly.Rust.STATEMENT_PREFIX.replace(/%1/g, "'" + id + "'"),
        Blockly.Rust.INDENT
      ) + branch;
  }
  if (Blockly.Rust.INFINITE_LOOP_TRAP) {
    branch =
      Blockly.Rust.INFINITE_LOOP_TRAP.replace(/%1/g, "'" + block.id + "'") +
      branch;
  }
  //  User-defined function: Define the function
      var code = `function ${funcName}() {
     // This is the ${funcName} function. Code starts here
     ${branch}
}
`;
  // console.log(['code', funcName, code]); ////
  code = Blockly.Rust.scrub_(block, code);
  // Add % so as not to collide with helper functions in definitions list.
  Blockly.Rust.definitions_["%" + funcName] = code;
  return null;
};
```
Register a block
```
var reactContractMainField = {
  type: "contract_init",
  message0: "Contract %1",
  args0: [
    {
      type: "field_dropdown",
      name: "TITLE",
      options: [["main", "This is the entry point of programme"]],
    },
  ],
  message1: "update %1 %2",
  args1: [
    {
      type: "input_value",
      name: "UPDATE",
      check: "Number",
      align: "RIGHT",
    },
    { type: "input_statement", name: "STACK" },
  ],
  tooltip: "Hello",
  inputsInline: false,
  color: 355,
  tooltip: "",
  helpUrl: "",
  extensions: ["parent_tooltip_when_inline"],
};

Blockly.Blocks["contract_init"] = {
  init: function () {
    this.jsonInit(reactContractMainField);
    this.setStyle("loop_blocks");
  },
};
```
Here I cannot change the color of block

1. Download blockly-react sample from official site
2. Add the above code in app.js , generator/generator.js and blocks/customblocks.js respectively.
3. run the app.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- [X] Browser [e.g. chrome, safari]

**Smartphone (please complete the following information):**
 - Browser [chrome browser]

**Stack Traces**
No errors generated

**Additional context**
Hi, I am using blockly npm package with reactJS. When I define a custom block I am not able to change the colour of the block even after specifying different colours. All the blocks are with the default colour green.
Even though after adding a colour of 355 ... the block still stays green

**Comment by alschmiedt** [comment]
I believe the problem here is that you are using `color` instead of `colour` in your block definition. 

I'm going to close the issue for now, but please feel free to reopen if that does not fix your problem. 

Thanks!
