### ISSUE TITLE
Tests: write a test for removing/adding inputs on a procedure & caller block

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#5752]
**Is your feature request related to a problem? Please describe.**
There was a bug in core where callers would break when an input was removed. This was only caught because of [tests in samples](https://github.com/google/blockly-samples/blob/fade7b12adce75fef0c0687d0feab1cb9573fa9b/plugins/block-plus-minus/test/procedures.mocha.js#L334).

We should look at pulling some of those into core. 

**Describe the solution you'd like**
Not entirely sure yet. Depending on how [this issue](https://github.com/google/blockly/issues/5466) goes we might want to look at following the same pattern. Where we create a set of procedure tests that blockly supplies and plugins can also run.

**Describe alternatives you've considered**
The simple solution is to just copy and paste the test into core.

**Additional context**

**Comment by rachel-fenichel** [comment]
Fixed during @BeksOmega's procedure work.
