### ISSUE TITLE
Check on legibility of multiline strings in generators

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#5761]
**Describe the bug**

Running clang-format in generator files made some multiline generated functions hard to read by compressing lines together. 
This does not cause runtime errors, and we don't touch these files much, but it does make it harder to read.

**Expected behavior**

Readable code, even after clang-format

**Additional context**

A couple of possible solutions:
- Use template literals (js multiline strings)
- Insert clang-format-disable and clang-format-enable directives

**Comment by NeilFraser** [comment]
Fixed.
