### ISSUE TITLE
Add example for setting maxInstance in options struct

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#5773]
**Where**
https://developers.google.com/blockly/guides/configure/web/configuration_struct 

**What**

  
- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**
Map from block types to maximum number of blocks of that type that may be created. Undeclared types default to Infinity.

**Suggested content**
Map from block types to maximum number of blocks of that type that may be created. Undeclared types default to Infinity. **Ex. maxInstances: {'controls_if': 3, 'math_number': 42}**

**Additional context**
We might want to go through the rest of our options structs to see if anything else would benefit from an example.

**Comment by gonfunko** [comment]
This will go out with the next devsite publication run.
