### ISSUE TITLE
Longpress on workspace in Edge highlights contents on surrounding page

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#5800]
**Describe the bug**

Longpressing on the workspace in Edge in touch mode causes a highlight and right-click on contents of the surrounding page.

**To Reproduce**
1. Go to google.github.io/blockly/tests/playgorunds/compressed.html on Edge
2. Long-press on the workspace
3. Observe that the word "Blockly" to the left of the workspace gets highlighted and a browser context menu appears.

**Expected behavior**
Context menu opens on Blockly workspace.

**Additional context**

Long-pressing on blocks works. Long-pressing on the workspace works once text outside has already been selected. Clicking around the page to deselect the text and then long-pressing on the workspace returns to the same state.

**Comment by gonfunko** [comment]
Duplicate of #4954 (this is Edge vs Chrome, but Edge is Chromium, so this is almost assuredly the same underlying issue)
