### ISSUE TITLE
Visibility of some field properties is wrong

### ISSUE THREAD

**Issue by maribethb** [google/blockly#5803]
**Describe the bug**

Some fields that inherit from the basic fields have properties like `isDirty_` and `configure` to be protected, but in the base field those properties are public. This is illegal in typescript and the child classes should also use public visibility

**Additional context**

found in #5802

**Comment by Hanaffi** [comment]
@rachel-fenichel Is this available? I see you already merged a PR for it.

**Comment by rachel-fenichel** [comment]
@Hanaffi it looks like it's still open. Maribeth's fix just fixed it for the generated type definition file for release.

Steps here:
- Make a list of properties in all of the `field_*.js` files that are `protected`.
- For each protected property, check whether it's also protected in `field.js`.
  - If visibility is different in the base class, update all of the subclasses to match the visibility in the base class.

**Comment by Hanaffi** [comment]
@rachel-fenichel Can you assign?
