### ISSUE TITLE
Setting default saturation and value

### ISSUE THREAD

**Issue by rd--** [google/blockly#5812]
**Describe the bug**

I've been setting Blockly.HSV_SATURATION and Blockly.HSV_VALUE, as described at:

https://groups.google.com/g/blockly/c/kTIxjJa39TM/m/tESoM6wofzQJ

however this seems to have stopped working recently? 

I'm loading Blockly using: <script src="https://unpkg.com/blockly/blockly.min.js"></script>

Is there a new way to do this?

I see they're now internalConstants exported for "legacy reasons": 

https://github.com/google/blockly/blob/02a57122debaa4ca043312dec547944afae658c4/core/blockly.js#L627

There are no console errors, and Blockly.HSV_VALUE prints as the value it's been set to, but the colours of the blocks and in the toolbox don't reflect this.

This was sent to the forum, where it was suggested I should file a bug, though it's quite possible this is my mistake!  

https://groups.google.com/g/blockly/c/Zme8UGnh0Bg/m/pjAEQBjeBwAJ

**To Reproduce**

There is a version of the editor this affects at:
 
https://rohandrape.net/?t=blksc3&e=blksc3.html

There are no errors in the console, and Blockly.HSV_SATURATION and Blockly.HSV_VALUE print with the modified values, but the blocks drawn don't reflect this.

**Expected behavior**

Previously the blocks were recoloured.  I'm almost certain I didn't change anything related to this, but perhaps it was only working initially by chance.

**Screenshots**

N/A

**Desktop (please complete the following information):**

OS: Linux x1 5.14.0-4-amd64 #1 SMP Debian 5.14.16-1 (2021-11-03) x86_64 GNU/Linux

Browser: Chromium Version 90.0.4430.212 (Developer Build) built on Debian 11.0, running on Debian bookworm/sid (64-bit)

**Stack Traces**

N/A

**Additional context**

I'm quite new to Blockly, it's wonderful, this is quite possibly a beginner mistake!

**Comment by rd--** [comment]
Below is a more minimal example.  I think this used to work?  Best, Rohan

````
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="https://unpkg.com/blockly/blockly.min.js"></script>
  </head>
  <body>
  <div id="blocklyDiv" style="height: 480px; width: 600px;"></div>
  <xml xmlns="https://developers.google.com/blockly/xml" id="toolbox" style="display: none">
    <block type="logic_compare"></block>
    <block type="controls_repeat_ext"></block>
    <block type="math_number"></block>
    <block type="text"></block>
  </xml>
  <script>
    Blockly.HSV_SATURATION = 0.20;
    Blockly.HSV_VALUE = 0.95;
    var blk_workspace = Blockly.inject('blocklyDiv', {toolbox: document.getElementById('toolbox')});
  </script>
  </body>
</html>
````

**Comment by KlemenDEV** [comment]
I can also confirm this is happening

**Comment by alschmiedt** [comment]
Thank you for reporting this issue! I believe we are planning on fixing this and releasing a patch either today or tomorrow. We will update this issue when the patch is available.

**Comment by alschmiedt** [comment]
The fix for this was just released in the [most recent patch](https://github.com/google/blockly/releases/tag/7.20211209.1).
