### ISSUE TITLE
When is the next major release planned? Please update the README.

### ISSUE THREAD

**Issue by Taikono-Himazin** [google/blockly#5817]
When is the next major release planned? Please update the README.

The README remains as follows.
"The next major release will be September 30th, 2021."

Next is 2022Q1. I want you to write just the release month.

**Comment by gonfunko** [comment]
Thanks for flagging this! The next release will be during March 2022, I've opened a PR to update the README.

**Comment by Taikono-Himazin** [comment]
Thanks
