### ISSUE TITLE
npm - en.d.ts not found.

### ISSUE THREAD

**Issue by johnduffynh** [google/blockly#5841]
Hi,
Error: ../../node_modules/blockly/index.d.ts:15:22 - error TS6053: File '.../my-workspace/node_modules/blockly/msg/en.d.ts' not found.
15 /// &lt;reference path="msg/en.d.ts" />

**To Reproduce**
```
ng new ws --create-application=true --routing=false --style=scss;
cd ws;
npm install blockly;
```
notice ws/node_modules/blockly/[index.d.ts](https://github.com/google/blockly/blob/master/typings/index.d.ts) references msg/en.d.ts.

Work around is to just add [en.d.ts](https://github.com/google/blockly/blob/master/typings/msg/en.d.ts) or remove reference.  I could not find where you do the packages to do a pull request.

Thanks for this great product!

**Comment by alschmiedt** [comment]
Just a heads up we have released a [patch](https://github.com/google/blockly/releases/tag/7.20211209.2) for this and it is now available on [npm](https://www.npmjs.com/package/blockly).
