### ISSUE TITLE
statement of type null in type checked statement stacks is accepted

### ISSUE THREAD

**Issue by kaktus42** [google/blockly#5843]
**Describe the bug**

When having a typed statement stack, e.g. https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#mfpcyz, it is possible to add a "null"-typed statement to it (e.g. a `controls_if` statement).
However, it should only accept statements of type "Mouse" or "Rat".

**To Reproduce**

Use the linked block and add a `controls_if` statement in the statement list.

**Screenshots**

<img width="192" alt="Screenshot 2021-12-28 at 18 16 11" src="https://user-images.githubusercontent.com/1608815/147590734-7e9e16fd-bd3d-49a9-b846-d8a93018f077.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.2
 - Browser: Chrome Version 96.0.4664.55

**Comment by BeksOmega** [comment]
Hello,

Sadly this is actually the intended behavior :/ It is meant to support variables, which are "dynamically typed" by default (meaning we want them to connect anywhere). You can use the [strict connection checker plugin](https://www.npmjs.com/package/@blockly/plugin-strict-connection-checker) to get the behavior you're looking for.

Best wishes,
--Beka

**Comment by kaktus42** [comment]
I see. Thank you.
