### ISSUE TITLE
Broken references to documenation of Built-in Fields

### ISSUE THREAD

**Issue by antonykamp** [google/blockly#5849]
**Where**
https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#args 

**What**

- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

Currently, the links of the Built-in Fields are references to (for example)
```
https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#checkbox_field
```
But the link doesn't work 😢  

**Suggested content**

Actually, the Build-in Fields are documented at (for example)

```
https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/checkbox
```
Sounds like simply updating the links 🥳 I would fix it on my own, but I couldn't find any associated open source code 😕 Thank you! 🦖

**Comment by rachel-fenichel** [comment]
I just put together an internal PR to fix this. I'll close the issue when it goes live in the next day or two.

**Comment by antonykamp** [comment]
Thank you! :)
