### ISSUE TITLE
Set up API Extractor to generate API documentation

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#5854]
[API Extractor](https://api-extractor.com/pages/overview/intro/) is a tool from Microsoft for analyzing and doing useful stuff with a library's type definitions.

It has three output types: an API report, which we can diff to see when our API changes; a single .d.ts file for the entire library, which may be what we want to expose; and documentation that can be published as a website.

API Extractor also supports tagging APIs as internal, alpha, beta, deprecated and public. These match how we think about APIs for Blockly better than private, protected, package and public.

It will replace our current scripts for generating a unified typings file and part of our internal JSDoc publication pipeline.

It works on the `.d.ts` files generated by the typescript compiler, so we may be able to use it before we have finished converting our library fully to Typescript.  API Extractor does *not* work on JSDoc, even though the Typescript compiler accepts JSDoc.

Required work for API Extractor to generate (nice) documentation:
- [x] #6338
    - [x] Convert `@return` to `@returns`
    - [x] Use correct `@param` syntax with the hyphen e.g. `@param block - the block we are doing stuff to.`
    - [ ] Remove `@alias` tags and the text following them.
    - [ ] Remove the `@supress` annotations if we can. If we still need these for Closure, then we can configure TsDoc to accept that this is actually a valid tag by editing the tsdoc config.
- [x] Fix the warning when exported members don't have a release tag (public, beta, etc.) IMO we could keep the convention that anything that doesn't have a modifier is public, and just silence this warning. The warning comes from API Extractor and NOT from the TsDoc tool. I can't find anything in the TsDoc requirements stating this is required, `eslint-plugin-tsdoc` doesn't list what rules it enforces, and since Google recommends keeping JsDoc they also don't have guidance. So I think it's fine to silence this warning, assuming the output is okay.
- [x] Fix the `_2` problem where some classes that are re-exported get renamed in the documentation output e.g. `Comment_2`. We might be able to fix this in the code by not re-exporting them but from what I understand we can't at this time since we have purposely decided to re-export these particular items. We can probably post-process the intermediate json file that is generated in order to remove this before generating the md files. If in the future we decide to use the rollup feature we'd have to also work out a solution there.
- [x] Write a script that will generate the markdown and upload it to devsite. This can live alongside the old script in google source code.

**Comment by rachel-fenichel** [comment]
API Extractor also supports defining custom TSDoc tags: https://api-extractor.com/pages/configs/tsdoc_json/

We may need to use this to handle some of the jsdoc tabs that we use (so far it has complained about `alias`).

**Comment by maribethb** [comment]
This will be closed by #6506
