### ISSUE TITLE
Links in themes doc page broken

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#5855]
**Suggested content**

https://github.com/google/blockly/blob/master/core/theme/dark.js#L17 ->
https://github.com/google/blockly-samples/blob/aba88bea60bddf3d31ce630b836e2933836ed287/plugins/theme-dark/src/index.js#L21

https://github.com/google/blockly/blob/master/core/theme/deuteranopia.js -> https://www.npmjs.com/package/@blockly/theme-deuteranopia

https://github.com/google/blockly/blob/master/core/theme/tritanopia.js -> https://www.npmjs.com/package/@blockly/theme-tritanopia

Reported by the lovely Koen van Wijk in a pm.

**Comment by rachel-fenichel** [comment]
Fixed on [this page](https://developers.google.com/blockly/guides/configure/web/themes). Let me know if I missed them in another place.
