### ISSUE TITLE
Add information about conventional commits to our Contributing docs

### ISSUE THREAD

**Issue by maribethb** [google/blockly#5893]
**Where**

Probably here https://developers.google.com/blockly/guides/modify/contributing

**What**

Info about conventional commits

**Old content**

Nothing

**Suggested content**

- a section we can link to that says "oh no, I didn't do conventional commits, what do i do now?"
- a section with a list of our valid tags and their meanings

**Additional context**

**Comment by BeksOmega** [comment]
I can grab this one.
