### ISSUE TITLE
Convert to ES Modules

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#5904]
Closure compiler documentation:
- [ES6 modules and Closure interop](https://github.com/google/closure-compiler/wiki/ES6-modules-and-Closure-interop)
- [Migrating from `goog.modules` to ES6 modules](https://github.com/google/closure-compiler/wiki/Migrating-from-goog.modules-to-ES6-modules)

The specific steps that we need to take, pulled from the closure documentation:
**Migrating Closure modules with named exports**
For Closure modules that use named exports we recommend migrating files in place over 3 changes.

1. Edit the implementation file to be an ES module that calls `goog.declareModuleId` with the old Closure module name (i.e. the old argument to `goog.module`). This should allow other files to continue using `goog.require` on the Closure namespace. (Be sure to import Closure's `goog.js` file rather than use the global `goog` symbol!)
3. Edit all ES module files that are using `goog.require` on the module namespace to instead use ES `import`.
4. Remove the call to `goog.declareModuleId` in the migrated file once it is not being referenced by any `goog.module` or `goog.provide` files.

**Reasons to migrate**
- (As I understand it) the Typescript compiler cannot pick up and use the correct types for imports in the form of `const {Foo} = goog.require('Blockly.Foo')`.
- Tsickle assumes that the input files are ES modules.
- Tsickle relies on correct parsing by the typescript compiler, and chokes when the compiler chokes.
- The closure compiler understands ES modules, so *in theory* this change can be done without involving the typescript compiler--meeting my goal of being able to compiler with the closure compiler up until we've fully debugged our typescript compilation flow.

**Comment by cpcallen** [comment]
Title tweaked: although they were introduced in ES6, they are more widely referred to simply as "ES modules" rather than "ES6 modules".

**Comment by cpcallen** [comment]
> 1. (Be sure to import Closure's `goog.js` file rather than use the global `goog` symbol!)

Have you verified that this is necessary?

**Comment by rachel-fenichel** [comment]
We may be able to skip directly to TypeScript, in which case we can close this entirely. @gonfunko is currently investigating this.

**Comment by cpcallen** [comment]
This was done (for `core/`) as part of the TypeScript conversion.  Will track conversion of `blocks/` and `generators/` along with their conversion to TypeScript.
