### ISSUE TITLE
Codelabs should not encourage people to edit core

### ISSUE THREAD

**Issue by maribethb** [google/blockly#5973]
**Where**

All codelabs should be audited. For example, https://blocklycodelabs.dev/codelabs/custom-generator/index.html?index=..%2F..index#1

**What**

Codelabs

**Old content**

Encourages people to edit core by making changes in the tests/ directory to test out their changes. This gives people the false idea that they should implement their applications by writing code inside the core directory, which is counterproductive.

**Suggested content**

Either the codelab should provide starter code, or the plugin should begin by calling the `create-package` script which creates starter code for a plugin. Codelabs that implement "plugin-like" features (such as new generators) should be implemented just like a plugin would be.

**Additional context**

**Comment by rachel-fenichel** [comment]
Justin cleaned up many of the codelabs. @maribethb to audit and close this issue if they are all done, or leave a list of remaining items if any are not done.

**Comment by maribethb** [comment]
None of the codelabs now instruct users to modify core or a plugin's code! They all either have starter code or use the sample app.
