### ISSUE TITLE
Playground context menu missing "create" item in `develop`

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#5975]
**Describe the bug**

I was attempting the reproduce steps for issue #5972 in `develop`, but was unable to to find the "create 'do something'" item in the `procedure_defreturn` block's context menu.  It is present in `master`.

**To Reproduce**

1. Check out `develop` branch.
2. `npm start`
3. Open the "Functions" section of the toolbox.
4. Drag a `procedure_defreturn` block (the one with a "return" input) to the workspace.
5. Right-click (or appropriate gesture) to open the context menu for this newly created block.

**Expected behaviour**

The last item in the menu will be "create 'do something'"

**Expected behaviour**

The menu ends with "Help".

**Screenshots**

See #5972, step 2 for expected.

Actual:
![Screenshot 2022-03-03 at 12 12 16](https://user-images.githubusercontent.com/5603958/156562511-b5293ac4-7815-410a-9d79-c6db5823ebda.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1
 - Browser: Chrome 99.0.4844.51
 - Version: `develop`, at 2a0e5475

**Additional context**

I wondered if this have been caused by my changes to playground loading in PR #5931, but `multi_playground.html` has the same problem despite not being converted yet.

**Comment by cpcallen** [comment]
After a quick manual bisect, I see that the problem began when PR #5959 was merged.  @BeksOmega: any idea what might have caused this?

**Comment by alschmiedt** [comment]
Fixed in #5976
