### ISSUE TITLE
Mutators on control_if blocks throw errors

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#5999]
**Describe the bug**
Opening the mutator on the `controls_if` block throws an error.

**To Reproduce**

1. Go to the playground.
2. Drag an if block to the workspace.
3. Click the mutator
4. See error in the console

**Expected behavior**
No error

**Screenshots**

**Stack Traces**

```
Uncaught TypeError: Cannot read properties of undefined (reading 'block_')
    at sourceListener_ (mutator.js:372:16)
    at WorkspaceSvg.Workspace.fireChangeListener (workspace.js:699:5)
    at fireNow (utils.js:348:22)
```

**Additional context**

**Comment by rachel-fenichel** [comment]
When did this break?

**Comment by alschmiedt** [comment]
I think 15 days ago in #5952.

**Comment by BeksOmega** [comment]
> I think 15 days ago in #5952.

Sorry about that :/

**Comment by rachel-fenichel** [comment]
It happens. I just wanted to tie together the PRs in this chain.
