### ISSUE TITLE
Address nameDB_ or add api to get name of a variable

### ISSUE THREAD

**Issue by maribethb** [google/blockly#6008]
**Is your feature request related to a problem? Please describe.**

The recommended way to get the name of a variable is the same way we do it in the built-in variable blocks:

```
const varName = JavaScript.nameDB_.getName(
      block.getFieldValue('VAR'), NameType.VARIABLE);
```

However, as you can tell by the underscore, `nameDB_` is a protected variable on the generator, so it shouldn't be accessed outside the generator class (including by us in the default block).

Also, somewhat related, we are not currently exporting `Blockly.Names.NameType` in `blockly.js` so developers can't even do this successfully outside of Blockly.

**Describe the solution you'd like**

We could add an API to get the name of a variable for a given generator. That way developers don't have to know about the nuances of the nameDB, which seems too low-level to want to surface to them just to do this task.

**Describe alternatives you've considered**

Alternatively, we could make `nameDB_` not protected. I don't think this is ideal because it's asking developers to be too familiar with the implementation. Plus, we just renamed the variable so there's a lot of churn if we renamed it again to remove the underscore, or it would be confusing if we didn't remove it.

**Additional context**

Discovered this via https://groups.google.com/g/blockly/c/JzVgbKEcyaw

**Comment by Daniel-del-Castillo** [comment]
I'm having this problem!
> Also, somewhat related, we are not currently exporting Blockly.Names.NameType in blockly.js so developers can't even do this successfully outside of Blockly.

 So, I get there isn't a way right now to get the name of a variable? That would really be a problem for me.

Btw, I don't know if this has already been reported, but the documentation still shows [this way](https://developers.google.com/blockly/guides/create-custom-blocks/generating-code?hl=en#getfieldvalue) of doing it and even with `variableDB_` instead.

**Comment by Daniel-del-Castillo** [comment]
Okay, I found a workaround in  the google groups conversation @maribethb linked. I will copy here the workaround, in case anyone needs it.

```js
Blockly.JavaScript.nameDB_.getName(block.getFieldValue('MYVAR'), 'VARIABLE');
```

**Comment by maribethb** [comment]
@Daniel-del-Castillo Hi, thank you for pointing out the documentation issue! I will get that fixed up as well.

For the current release (v7.20211209), you would have to use the plain string `VARIABLE` just as you are doing. #6030 should go into the upcoming release (in the next two weeks) which will make `Blockly.Names.NameType.VARIABLE` work again which will be the recommended approach (in case, for some reason, we ever need to change the underlying string represented by that enum)

**Comment by maribethb** [comment]
After discussion, let's add APIs to `generator.ts`:

- `getVariableName`
- `getProcedureName`

that just call `nameDB_` under the hood and pass in the appropriate `NameType` so the developer doesn't have to

also need to update documentation where needed

**Comment by maribethb** [comment]
Started working on this and realized `nameDB_` does need to be public after all, because there are additional APIs that would have to be added such as:
`getDistinctName` (used here as example)
`getDeveloperVariableName` (used in block code generators for procedures in certain languages)

However, `getVariableName` and `getProcedureName` still have utility as they should work for the main use cases within block code generator functions and can print more helpful warnings if the generator hasn't been fully initialized, which is a common failure mode. The other methods from `nameDB_` are more niche and can be accessed from the (to-be-made) public `nameDB_` object.
