### ISSUE TITLE
Hosted advanced playground times out

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#6019]
**Describe the bug**
The hosted advanced playground times out. See #5557 for more information.

**To Reproduce**

1. Go to https://blockly-demo.appspot.com/static/tests/playgrounds/advanced_playground.html
2. Notice how it does not load.
**Expected behavior**
It should load.

**Additional context**
I originally did not fix the advanced playground because we were thinking about taking it out of core. Since we [decided to hold off on that](https://github.com/google/blockly/issues/5834#issuecomment-1057568156), I think it should be fixed so that it works when hosted.

**Comment by BeksOmega** [comment]
Closed by #6021
