### ISSUE TITLE
playground advance display nothing

### ISSUE THREAD

**Issue by msccreater** [google/blockly#6022]
**Describe the bug**
open playground and click advance,nothing to display, in console display error message:
"GET /node_modules/@blockly/block-test/dist/index.js" Error (404): "Not found"

**To Reproduce**

1. Go to 'root  dictory of blockly and input command in terminal :   npm start'
2. Click on 'open broswer playground and click advance button'
3. Scroll down to 'display nothing'

**Expected behavior**

**Screenshots**
![Snipaste_2022-03-23_17-04-27](https://user-images.githubusercontent.com/1811267/159662663-302ca469-7a64-42e5-b2f2-ca82e8071371.png)

**Desktop (please complete the following information):**
 - OS: [windows11]
 - Browser [windows edge]
 - Version []

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```
[2022-03-23T09:00:19.076Z]  "GET /node_modules/@blockly/block-test/dist/index.js" Error (404): "Not found"
**Additional context**

**Comment by BeksOmega** [comment]
Hello @msccreater =) Have you run `npm install` before running `npm start`?

**Comment by rachel-fenichel** [comment]
Closing as stale.
