### ISSUE TITLE
Download screenshot contextual menu item is broken

### ISSUE THREAD

**Issue by gonfunko** [google/blockly#6023]
**Describe the bug**

The Download Screenshot contextual menu item (on the workspace) is broken in the develop branch.

**To Reproduce**
1. Open the playground on the develop branch
2. Add some blocks
3. Right click on the workspace and choose the Download Screenshot contextual menu item.

**Expected behavior**
A screenshot of the workspace is downloaded. Instead, the following is logged to the console and nothing visibly happens:

```
playground.html?dir=rtl&toolbox=categories:245 Uncaught TypeError: Blockly.downloadScreenshot is not a function
    at Object.callback (playground.html:245:15)
    at Object.actionHandler (:8080/core/contextmenu.js:158:16)
    at MenuItem.performAction (:8080/core/menuitem.js:276:12)
    at Menu.handleClick_ (:8080/core/menu.js:387:16)
    at HTMLDivElement.wrapFunc (:8080/core/browser_events.js:86:14)
```

**Comment by BeksOmega** [comment]
Note that we should probably fix this, but if it breaks its fine. The download screenshot thing isn't something we actually provide, it was just a prototype sam built.
