### ISSUE TITLE
Playground does not support IE11

### ISSUE THREAD

**Issue by alschmiedt** [google/blockly#6032]
**Describe the bug**
We us the playground for all of our testing before a release. This includes testing on IE11. Currently, the playground will not load on IE11 for a few reasons: 
- Since we can now use template literals and arrow functions in core we understandably started using them in the playground and scripts the playground loads as well.
- The playground that is in develop right now loads `Blockly` using es6 imports.

**To Reproduce**
1. Try to load the playground using IE11.

**Additional Information**

I think there are probably three different tasks to this:
- [ ] Document what playgrounds we use for what testing and what playgrounds need to work in what browsers.
- [ ] Look into how we can load the playground in IE11 but still use es6 syntax that we love in the playground.
- [ ] I believe the next one is, do not try to load Blockly as a module if we are loading compressed, however this is more of a question for @cpcallen.

**Additional context**

**Comment by cpcallen** [comment]
IE11 support has been removed from Blockly, so closing this as obsolete.
