### ISSUE TITLE
Clicking field with open editor (menu, colour picker, etc) should close editor.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#6037]
Currently if one opens a dropdown by clicking on the field, then clicks a second time on the field, the menu animates a reopen.  It should close.

This is not a regression, it's just never worked the way it should.

**Comment by shaleen1985** [comment]
Hi @NeilFraser 
Did we got any update from Blockly team as to whether they will fix this default behavior or it will remain as is. Based on the outcome our internal project issue can be updated.
Again thanks for the help provided.
