### ISSUE TITLE
Modifying the name of a procedure's input variable creates intermediate variables

### ISSUE THREAD

**Issue by gonfunko** [google/blockly#6039]
**Describe the bug**

Changing the name of a procedure block's input variable with the Variables category of the toolbox is open causes many temporary variable blocks to appear in the toolbox until it is closed and reopened.

**To Reproduce**

1. Drag out a procedure block
2. Open its mutator and add an input
3. Open the Variables category in the toolbox
4. Change the name of the input variable in the mutator of the procedure block
5. Observe that each keystroke causes a new variable to be created with the current name of the input variable

**Expected behavior**
Rather than creating a new variable for every keystroke, the existing variable is renamed. Closing and reopening the Variables category consolidates the intermediate variables to only one with the new name.

**Screenshots**

https://user-images.githubusercontent.com/667459/160478535-f80833c6-a218-4c6d-b16b-8b619468c2fa.mov

**Comment by BeksOmega** [comment]
I think I've tried that solution before, and I found out that we have to create new variables every time, otherwise we get accidental collisions/coalescions :/

**Comment by BeksOmega** [comment]
Happened to stumble on the thing where I tried this previously: [comment](https://github.com/google/blockly/issues/3725#issuecomment-596165874), [demo PR](https://github.com/google/blockly/pull/3724). It was when I was working on the +/- blocks, which is probably why I couldn't find it before.

**Comment by BeksOmega** [comment]
Closing as per above explanations.
