### ISSUE TITLE
Movable XML argument no longer works to disable movable blocks (movable="false")

### ISSUE THREAD

**Issue by KlemenDEV** [google/blockly#6078]
**Describe the bug**

In order Blockly releases, this used to work to make a block not movable:

`<block deletable="false" movable="false" type="text"><field name="TEXT">name</field></block>`

but now blocks set with movable can still be moved out of the value input.

**Comment by maribethb** [comment]
Hello,

I'm not able to reproduce this in v8. e.g. in the demo here https://blockly-demo.appspot.com/static/demos/code/index.html copying your provided block definition to the xml tab works as expected - the block is not movable. Have you noticed this only in certain circumstances or can you provide more detailed reproduction steps?

**Comment by KlemenDEV** [comment]
I place the block dynamically by adding it to the DOM, maybe this causes this bug?

**Comment by KlemenDEV** [comment]
This also happens if you make a toolbox block that has default input filled with block set to movable false. The block can still be removed from the input

**Comment by rachel-fenichel** [comment]
We cannot reproduce this based on the examples you've given. Feel free to reopen this with sample code that triggers this issue for you.
