### ISSUE TITLE
Issue with default export in typescript definitions

### ISSUE THREAD

**Issue by maribethb** [google/blockly#6079]
**Describe the bug**

TypeScript error when importing Blockly types, see stack trace section

**To Reproduce**

(taken from forum post: https://groups.google.com/g/blockly/c/hFuWPbkXRSk )

set allowSyntheticDefaultImports: true in tsconfig.json.
To reproduce:
ng new ws --create-application=true --routing=false --style=scss;
cd ws;
npm install blockly;
ng g c test
sed -i "2i import Blockly from 'blockly';" src/app/test/test.component.ts
ng serve

**Stack Traces**

```
 node_modules/blockly/blocks.d.ts:14:26 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.

import * as Blockly from './core';
```

**Additional context**

https://www.typescriptlang.org/tsconfig#esModuleInterop

I think this might go away if in blocks.d.ts we did `import Blockly from 'blockly';` instead of `import * as Blockly` but I don't fully understand the intricacies of the module system we're using and how that interacts with the various tools being used. I think @cpcallen you are the expert here if this means anything to you.

**Comment by joseluiz98** [comment]
I'm having that same problem :(

**Comment by maribethb** [comment]
Hello @FrancescoPandolfi and @joseluiz98 and anyone else experiencing this issue, could you please try blockly beta `8.0.3-beta.0` and let me know if these errors are resolved and if there are any new ones? I think we have a fix for this problem in the beta and if it does not introduce new issues then we should be able to issue a patch release next week. Thanks!

**Comment by Chappie74** [comment]
I installed it, upgrading from [7.20211209.5](https://www.npmjs.com/package/blockly/v/7.20211209.5). 
One issue I found is the type binding for ToolboxCategory class may have changed. 

Prior to the version change, this was working just fine. 

![image](https://user-images.githubusercontent.com/21108487/172516973-09b5ccf6-06e4-4069-a8e1-dd13f3a7b708.png)
![image](https://user-images.githubusercontent.com/21108487/172517042-586cb40e-527a-4cf5-ba22-3225274717c6.png)

**Comment by maribethb** [comment]
@Chappie74 Thanks for testing! Those errors are unfortunately regressions introduced in v8 - I think all of the interface classes got a bit weird. Ultimately this bug was hiding all of the other type declaration regressions since this was preventing any type checking from occurring. Feel free to file a separate bug for that, and in the meantime you can have the compiler ignore the problematic lines :/ sorry about that!

The good news is we are on the cusp of converting our whole codebase to TS ourselves so all of these inconsistencies will get a lot more obvious to us and hopefully less likely to occur in the future. Thanks!
