### ISSUE TITLE
Disconnect sound defaults to .wav not .mp3

### ISSUE THREAD

**Issue by cpseager** [google/blockly#609]
Simply wrong order , disconnect.mp3 should be the first one

https://github.com/google/blockly/blob/master/core/inject.js#L347

**Comment by NeilFraser** [comment]
Why should the MP3 be first?

The current is order is based on file size.  The disconnect sound is short enough that the wav file is smaller than the MP3, so we give it preference.  If your browser can play wav, then let's use the smaller file.

**Comment by cpseager** [comment]
Ok, thanks for the explanation.

The specific issue was when running Blockly as an app offline using the default nw.js build.

In this situation there was a sound inconsistency - 'disconnect' did play but 'connect' did not. Hence the different file type order did cause different behaviour in this specific case.

This is because, unfortunately, under nw.js .canPlayType('mp3') returns a vague 'maybe' which Blockly then  interprets as 'true' but is actually 'false' (mpeg is not 'officially' included due to the licensing issues).

However it is simple to workaround - when targeting nw.js put them in the same order, and put 'wav' first.
