### ISSUE TITLE
procedure call blocks don't update correctly when defining procedure's arguments change

### ISSUE THREAD

**Issue by yoderjen** [google/blockly#61]
This used to work, but doesn't now (I last updated blockly ~ a week ago).

If you define a procedure, the flyout correctly shows the labels of the arguments in the call block like this:  
![aa_correct](https://cloud.githubusercontent.com/assets/10271662/6088840/9354426e-ae0f-11e4-911a-ba808282b5d4.jpg)

However, if you change the arguments (change the names, add an argument, whatever) the labels for those arguments disappear in the calling block:
![aa_incorrect](https://cloud.githubusercontent.com/assets/10271662/6088852/b6d26fb8-ae0f-11e4-912d-44b28a196215.jpg)

**Comment by yoderjen** [comment]
I just checked and this issue remains in the current version.

**Comment by NeilFraser** [comment]
Confirmed.  Working on it...

**Comment by NeilFraser** [comment]
Fixed.  Thanks!
