### ISSUE TITLE
when compenent use in a model dialog box, this block button can not show normal！ blocklyDropDownDiv was in out of the dialog box.

### ISSUE THREAD

**Issue by qduck** [google/blockly#6117]
![image](https://user-images.githubusercontent.com/7345411/165534295-4c1eee1c-591d-41d3-9dc8-aa943f485415.png)

the blocklyDropDownDiv and others are in html body default , when compenent was in the model dialog box 。

the block button click dropdown can not show normally

**Comment by BeksOmega** [comment]
Hello! Just to clarify: You are injecting your workspace into a modal, but the DropDownDiv is _not_ being added to that modal which is creating visual errors?

**Comment by maribethb** [comment]
Hello, if what Beka described matches what you're experiencing, I think you just need to call

`Blockly.setParentContainer(yourContainerDivHere)`

before calling `Blockly.inject`. If that doesn't solve your problem or that isn't the problem at all, please reopen with additional info.
