### ISSUE TITLE
Dragging variable block out of toolbox stops mid-drag

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#613]
This seems to be a touch event problem since it is reproducible on a chromebook with a touchscreen or an android device, but not chrome on a mac.

Steps to reproduce on blockly playground (version on appspot):
1. Create a variable block with the variable button in the variable flyout
2. Try to drag the block out of the toolbox.
3. Notice the block is created in the workspace but the drag never really starts and the block remains highlighted as if it were dragging.

Looks like there's a missing mouseup/touchend handler somewhere.

**Comment by rachel-fenichel** [comment]
This happens on any block with a variable, including the ones in the list category.  Looks like it's the result of the call
`    this.sourceBlock_.workspace.createVariable(this.getValue());
`
which refreshes the contents of the toolbox if it's open.  That changes the DOM on the path that the touch events were on, which is somehow making touchmove events disappear.

**Comment by picklesrus** [comment]
That's tricky.... I wonder if the drag surface in scratch-blocks would cause have the same problem?

**Comment by rachel-fenichel** [comment]
Solvable by checking for Blockly.Flyout.startFlyout_ being non-null.  I'll have a patch soon.

**Comment by rachel-fenichel** [comment]
Fixed in #637
