### ISSUE TITLE
The append of a Dummy Input to a Block doesn't work

### ISSUE THREAD

**Issue by CualeMarke** [google/blockly#6135]
Hi, I'm using a block with a FieldDropDown and a Validator.
Every time the value of the dropdown changes I need to modify my block, so I can chose to show an input value, an input statement or a dummy input.
I've found that every time I try to append a Dummy input to the block, an error is displayed in the console and the input isn't appended.
The append of Value input and Statement input doesn't have any problem, it works perfectly.

To reproduce you can apply the code in the documentation (https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/dropdown#creating_a_dropdown_validator), but instead of append a value/statement input you should append a dummy input.

Expected behaviour: the dummy input is added without any error

The displayed error is:
![image](https://user-images.githubusercontent.com/104019510/166258046-fdaa1a37-bb09-4c87-8590-7b0097773f6d.png)

I've tested the issue on:
 - OS: Windows 10
 - Browser: Google Chrome, Firefox, Opera Gx Corner

**Stack Traces**

```
Uncaught TypeError: Cannot read properties of undefined (reading 'width')
    at InputRow.module$exports$Blockly$blockRendering$InputRow.InputRow.measure (Ez?_t=1651501442:772:219)
    at RenderInfo.module$exports$Blockly$blockRendering$RenderInfo.RenderInfo.computeBounds_ (Ez?_t=1651501442:873:145)
    at RenderInfo.module$exports$Blockly$blockRendering$RenderInfo.RenderInfo.measure (Ez?_t=1651501442:856:159)
    at Renderer.module$exports$Blockly$blockRendering$Renderer.Renderer.render (Ez?_t=1651501442:892:352)
    at BlockSvg.module$exports$Blockly$BlockSvg.BlockSvg.render (Ez?_t=1651501442:1088:282)
    at BlockSvg.module$exports$Blockly$BlockSvg.BlockSvg.appendInput_ (Ez?_t=1651501442:1080:183)
    at BlockSvg.module$exports$Blockly$Block.Block.appendDummyInput (Ez?_t=1651501442:975:251)
    at updateShape (Ez?_t=1651501442:4928:19)
    at BlockSvg.onchange (Ez?_t=1651501442:4671:25)
    at WorkspaceSvg.module$exports$Blockly$Workspace.Workspace.fireChangeListener
```

**Comment by BeksOmega** [comment]
Hello! Thank you for reporting this issue @CualeMarke ! Sadly I wasn't able to reproduce it given the steps you provided :/ Could you provide some additional information?
 * What version of Blockly you are using
 * What renderer you are using (if you're using something besides the default)
 * The full text of ablock definition that reproduces this issue.

Thank you for your time! Hopefully with a bit more information we can get this resolved =)

**Comment by CualeMarke** [comment]
Hi,
Thanks for the reply

I'm using the Version 7.20211209.2
My renderer is Thrasos
This is the block
`
Blockly.Blocks["appendDummyInput"] = {
    init: function () {
        this.appendDummyInput()
            .appendField("Hi")
            .appendField(new Blockly.FieldDropdown(function () {
                return [
                    ["VALUE", Blockly.INPUT_VALUE.toString()],
                    ["DUMMY", Blockly.DUMMY_INPUT.toString()],
                    ["STATEMENT", Blockly.NEXT_STATEMENT.toString()]
                ];
            }, this.validate.bind(this)), 'TYPE');
    },
    validate: function (newValue) {
        if (this.getInput("INPUT"))
            this.removeInput("INPUT");
        switch (newValue) {
            case Blockly.INPUT_VALUE.toString():
                this.appendValueInput("INPUT").appendField("Input");
                break;
            case Blockly.DUMMY_INPUT.toString():
                this.appendDummyInput("INPUT").appendField("Input");
                break;
            case Blockly.NEXT_STATEMENT.toString():
            default:
                this.appendStatementInput("INPUT").appendField("Input");
                break;
        }
        return newValue;
    }
}
`

Let me know if you need further informations =)

**Comment by Zauzolkov** [comment]
@CualeMarke, try to use other renderer (eg. 'geras') as temporary workaround. Looks like that `thrasos` renderer is affected by this issue.
