### ISSUE TITLE
improve the perfomance of getNeighbours in connection_db.js

### ISSUE THREAD

**Issue by shenjg1981** [google/blockly#614]
Hello, 
      When I read the code, I found getNeighbours in connection_db.js may be improved. the walk forward and back on the y axis can be stopped in advance if call isInYRange_ function. Is it?

**Comment by RoboErikG** [comment]
Hi Shen, I'm pretty sure that's how getNeighbours works already. getNeighbours calls checkConnection which returns dY < maxRadius. When that's false we stop walking the list, which is the same behavior as calling isInYRange_ would have.

**Comment by shenjg1981** [comment]
thks

**Comment by shenjg1981** [comment]
OK, thanks.
