### ISSUE TITLE
`parent_tooptip_extension` typo in the Extensions section of the documentation

### ISSUE THREAD

**Issue by johnnyoshika** [google/blockly#6151]
**Where**

https://developers.google.com/blockly/guides/create-custom-blocks/extensions#extensions

**What**

- [x] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

```
{
 //...,
 "extensions": "parent_tooptip_extension",
}
```

**Suggested content**

```
{
 //...,
 "extensions": "parent_tooltip_extension",
}
```

**Additional context**

Note this typo: parent_too`p`tip_extension

Anyone following the example and copying and pasting will encounter an error

**Comment by BeksOmega** [comment]
Fixed! Will be viewable next time we release our docs.

**Comment by johnnyoshika** [comment]
Thanks for the quick fix!
