### ISSUE TITLE
Remove workspace drag surface and block drag surface

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6160]
**Describe the bug**

With the drag surface (~2-5 FPS) on https://github.com/google/blockly/commit/b92cbd3b915ad99659ed2ad58adf1a4950fbbf79:
![image](https://user-images.githubusercontent.com/25440652/167512135-69db8d73-676a-4d8b-a085-92c468703de7.png)

Without the drag surface (~10 FPS) https://github.com/google/blockly/commit/b92cbd3b915ad99659ed2ad58adf1a4950fbbf79:

![image](https://user-images.githubusercontent.com/25440652/167512192-fabee584-c533-4000-9f89-a8a078bc5689.png)

**To Reproduce**

1. Go to the playground.
2. Hit the 'Airstrike' button
3. Go to the performance tab of the chrome devtools.
4. Enable recording screenshots.
5. Set CPU Throttling to 6x.
6. Start a recording.
7. Drag the workspace left... right... and left again.
8. Stop the recording.

**Expected behavior**

Ideally we wouldn't drop frames while dragging. Unfortunately most of the costs of dragging occur in the SVG engine, which we don't have a ton of control over.

**Additional context**

I have been able to make this a lot faster by changing things from using `setAttribute` to using `<element>.style`. This lets the browser use its CSS optimizations.

On https://github.com/BeksOmega/blockly/tree/perf/ws-drag (~30 FPS):

![image](https://user-images.githubusercontent.com/25440652/167512322-c463305f-11e3-412a-a410-23392ea4c6cf.png)

But that branch needs *a lot* of cleanup. Eg this does not work in IE, because IE does not support CSS transforms on SVG elements. So we need some utils that will handle setting SVG locations in a generalized way.

**Comment by BeksOmega** [comment]
I'm going to reopen this because the removal was reverted due to it being a breaking change, but we still want to remove it in the future.

**Comment by rachel-fenichel** [comment]
We decided not to include this change in the March 2023 release because it's a breaking change. Instead we're holding it until we release v10.

When reapplying the fix in https://github.com/google/blockly/pull/6758, also apply https://github.com/google/blockly/pull/6874 to resolve https://github.com/google/blockly/issues/6852.

**Comment by maribethb** [comment]
Note: We need to fix the scroll-options plugin when we release this as well.

**Comment by BeksOmega** [comment]
Related to: https://github.com/google/blockly-samples/issues/1664
