### ISSUE TITLE
Multiline field not correctly size in parent block when copy/paste

### ISSUE THREAD

**Issue by MrAndrewMal** [google/blockly#6165]
Describe the bug

![printscreen](https://user-images.githubusercontent.com/26713505/168569461-aa53d1f0-0be6-4265-b4a1-580a1a740378.png)

The multinline field is not sized correctly in the another block when copy/paste.

To Reproduce

Go to the playground.
Add on playground a block which can connect with multiline block.
Paste multiline block with a text in this block.
Copy/paste the parent block

**Expected behavior**

The background rect and block should show the text in full.

**Comment by BeksOmega** [comment]
Closed by #6461
