### ISSUE TITLE
XML file generated contains ton of commas, arrange in reverse pyramid almost every line of XML

### ISSUE THREAD

**Issue by mrkprdo** [google/blockly#6166]
Generating the XML code using this line:
`Blockly.Xml.domToPrettyText(Blockly.Xml.workspaceToDom(Blockly.mainWorkspace))`
generates lots of commas, arrange in some sorts of pattern like reverse pyramid or triangle. Something like this.
```
,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,
,,,,,,,,,,,,
.
[ommited]
.
,,,,
,,,
,,
,
```

**Comment by BeksOmega** [comment]
Hello! Could you provide reproduction steps for this? =)

Best wishes, --Beka

**Comment by mrkprdo** [comment]
Issue not related to blockly, closing.
