### ISSUE TITLE
Arrow functions used within mixins don't have their `this` pseudo-variable bound.

### ISSUE THREAD

**Issue by mark-friedman** [google/blockly#6167]
**Describe the bug**

Consider code like the following:
```
const testMixin = { printThis: () => console.log(this) };

Blockly.Blocks['mixin-tester'] = {
  init: function() {
    // < Block initialization code here>
    // ...
    this.mixin(testMixin);
    this.printThis();
  },
}

```
I would expect the console log to show the mixin-tester block, but it displays `undefined`.  Note that if I use a function defined via a `function` keyword, e.g.:
```
const testMixin = { printThis: function() { console.log(this) } };
```
then I do see the block in the console.

**To Reproduce**

1. Define a mixin object and Block definition as shown above
2. Add block above to toolbox
3. Open toolbox (and category, if necessary)
4. Look in console to see if the block has been displayed

**Expected behavior**

The block object will be displayed in the console, not `undefined`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 101.0.4951.64 

**Smartphone (please complete the following information):**

Not applicable.

**Stack Traces**

Not applicable.

**Additional context**

**Comment by BeksOmega** [comment]
I'm not sure if this is something we actually want to change. The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) state:

> Arrow functions don't have their own bindings to this, arguments or super, and should not be used as methods.

So the current behavior is not what one naturally expects. But working around it would *also* not be what someone expects if they have read the above doc.

I think the best recommendation is to use the `function` keyword if you want to use a function as a method.

**Comment by mark-friedman** [comment]
Well, color me embarrassed!  I was going to write whole screed about the possible meanings of the terms "function",  "method", and "mixin" to our users and how we should allow for the loose interpretations of the terms and say that regardless of that quote from MDN we should still bind `this` in the mixin functions.  However, I realized that once again I was tripped up by the peculiarities of JavaScript and that you simply **cannot bind `this` in an arrow function**, so my point would have been moot!

Sorry for the trouble :-(

**Comment by BeksOmega** [comment]
> However, I realized that once again I was tripped up by the peculiarities of JavaScript and that you simply cannot bind this in an arrow function, so my point would have been moot!

Oh I had no idea either haha! How interesting :D Even if we can't implement this, I'm happy you posted about it, because now I've learned something new!
