### ISSUE TITLE
code generated from combination of math_on_list and lists_create_empty blocks produces errors

### ISSUE THREAD

**Issue by nederland074** [google/blockly#6169]
**Describe the bug**

The code generated by "lists_create_empty" connected to "math_on_list" causes errors if the "math_on_list" block has its "operation" field set to "sum" or "average".

**To Reproduce**

1. Go to https://blockly-demo.appspot.com/static/demos/code/index.html#no6a4p or https://blockly-demo.appspot.com/static/demos/code/index.html#3braq6
2. Hit the run button.
3. See the popup window containing error message: "Program error: TypeError: reduce of empty array with no initial value"

**Expected behavior**

The code runs without any errors.

**Screenshots**

Both following block setups cause this error:
![blocks](https://user-images.githubusercontent.com/11175695/169037936-7608ddfb-4b23-4236-8701-1c4f58bd548f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 101.0.4951.64

**Comment by BeksOmega** [comment]
Thanks for reporting this @nederland074 !

Extra repro details: Tested in all generators, and this only occurs with the JavaScript generator.

**Comment by gregdyke** [comment]
If you put this as help wanted, it's likely it will be something I can take a look at fixing

**Comment by rachel-fenichel** [comment]
Is this fixed?

**Comment by maribethb** [comment]
fixed by #6178
