### ISSUE TITLE
Change assertFieldValue in test helpers to use deepEqual

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6180]
**Describe the bug**

[assertFieldValue](https://github.com/google/blockly/blob/b92cbd3b915ad99659ed2ad58adf1a4950fbbf79/tests/mocha/test_helpers/fields.js#L72) doesn't work for fields that return object values (including arrays).

**Expected behavior**

The test helper should work with fields that return objects/arrays.

**Additional context**

Should be able to fix this by changing it to use [chai.assert.deepEquals](https://www.chaijs.com/api/assert/#method_deepequal)

**Comment by Samridhi-98** [comment]
Hey @BeksOmega, is this issue still open? 
I would like to take it.

**Comment by BeksOmega** [comment]
Go for it @Samridhi-98 !

**Comment by Samridhi-98** [comment]
Hey @BeksOmega, I am facing some issue while project setup, I ran `npm install` then `npm run build` & `npm run test` , getting this error `gulp-google-closure-compiler: Error writing to stdin of the compiler. write EPIPE`

<img width="1792" alt="screenshot" src="https://user-images.githubusercontent.com/54466041/197973882-c5654151-abe1-45e9-950e-5ca0e9e32a45.png">

**Comment by BeksOmega** [comment]
Hmmm @Samridhi-98 it looks like the closure compiler plugin might not have installed correctly. Could you run an `npm ci` and then `npm run build` and see if you still get the same issue?

If that doesn't fix the problem, could you provide:
  * What operating system you're using
  * The full output of your console as text
  * Any other info you think might be helpful

Thank you so much!

**Comment by Samridhi-98** [comment]
> Hmmm @Samridhi-98 it looks like the closure compiler plugin might not have installed correctly. Could you run an `npm ci` and then `npm run build` and see if you still get the same issue?
> 
> If that doesn't fix the problem, could you provide:
> 
> * What operating system you're using
> * The full output of your console as text
> * Any other info you think might be helpful
> 
> Thank you so much!

Still getting same error! :(

![image](https://user-images.githubusercontent.com/54466041/198211204-c6ee0533-247d-49a6-9463-72ce6d22d367.png)


**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome

**Comment by Samridhi-98** [comment]
```
> blockly@9.0.1 build
> gulp build

Using gulpfile ~/Projects/blockly/gulpfile.js
Starting 'build'...
Starting 'buildLangfiles'...
Starting 'buildJavaScript'...
Finished 'buildLangfiles' after 269 ms
Finished 'buildJavaScript' after 6.8 s
Starting 'buildDeps'...


Finished 'buildDeps' after 4.12 s
Starting 'buildCompiled'...
gulp-google-closure-compiler: Error writing to stdin of the compiler. write EPIPE
'buildCompiled' errored after 1.38 s
Error in plugin 'gulp-google-closure-compiler'
Message:
    Compilation errors occurred
Details:
    domainEmitter: [object Object]
    domainThrown: false
 'build' errored after 12 s
```

**Comment by BeksOmega** [comment]
@Samridhi-98 Sorry I don't have any idea what's going on here :/ I'm gonna pass it off to someone else to see if they have thoughts!

**Comment by cpcallen** [comment]
@Samridhi-98: Beka asked me about this a few days ago and I couldn't offer any better answer than "seems like Closure Compiler is not working; is it installed correctly?".

Can you try running `npx google-closure-compiler --version` in the repository root, and tell us what happens?

**Comment by Samridhi-98** [comment]
> npx google-closure-compiler --version

Yeah, I have followed setup guide proper.
```
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20221004
```

**Comment by cpcallen** [comment]
OK.  So that's good, but it doesn't help us figure out what is going on.  Luckily, one of my colleagues _has_ been able to reproduce this issue, but we're still not sure what's causing it.

One theory is that it only occurs on machines that have been updated to macOS Ventura (v13).  Can you tell us what version of macOS you are using?

**Comment by cpcallen** [comment]
Update: @Samridhi-98: my colleague filed google/closure-compiler-npm#265.  Can you check to see if that applies to you too?

**Comment by Samridhi-98** [comment]
> OK. So that's good, but it doesn't help us figure out what is going on. Luckily, one of my colleagues _has_ been able to reproduce this issue, but we're still not sure what's causing it.
> 
> One theory is that it only occurs on machines that have been updated to macOS Ventura (v13). Can you tell us what version of macOS you are using?

I am using macOS Monterey version 12.6.

**Comment by Samridhi-98** [comment]
> Update: @Samridhi-98: my colleague filed [google/closure-compiler-npm#265](https://github.com/google/closure-compiler-npm/issues/265). Can you check to see if that applies to you too?

Recently, I got an update now I am also using macOS Ventura(v13).

Also, now if I run `npx google-closure-compiler --version` command, not getting any output in the terminal.

**Comment by cpcallen** [comment]
OK, it looks like you have had the same problem that @gonfunko has had.

**Comment by Samridhi-98** [comment]
Hey @cpcallen, @BeksOmega I am still facing same issue. 

<img width="1728" alt="Screenshot 2022-12-27 at 1 26 37 PM" src="https://user-images.githubusercontent.com/54466041/209632464-957c6a16-95fc-4a54-9c67-034d4550db15.png">

**Comment by gonfunko** [comment]
I believe updating your branch to the latest version of the code and re-running `npm install` should resolve this.
