### ISSUE TITLE
Stuggle with typescript and blockly:import { Block } from 'core/block'

### ISSUE THREAD

**Issue by codeh2o** [google/blockly#6197]
``` typescript
import { Block } from 'core/block'
```
when I import **Block** type when IDE show me an error

`Module is not listed in package.json dependencies `

I notice there is a blockly.d.ts in blockly but the module name is  not **blocky** ,and It is listed in dependencies. 

is any way to bypass and resovle the problem?

**Comment by maribethb** [comment]
Hello,

It looks like you are trying to directly import one of the submodules in Blockly, which is not currently supported. I am not sure which file you are trying to access. You may need to reference the recommended imports here: https://www.npmjs.com/package/blockly

Most of the time you will just `import * as Blockly from 'blockly';`

Most files / modules in Blockly are accessible via the top-level export called `Blockly`, so if you are trying to reference the `Block` module then that is part of the core library and is accessible via `Blockly.Block`.

If you are trying to access the object containing all of the block definitions, that is `Blockly.Blocks`. If you are trying to access the module that contains utilities related to the built-in blocks (like loops) that is `Blockly.libraryBlocks`.

If you are using Blockly v8 note that there is currently a bug with our TypeScript declarations and you may get errors. We are issuing a patch release with a fix for that this week, until then you can disable type checking for your dependencies, sorry for the inconvenience!

If you have further questions about how to import correctly, I'd recommend [posting on the forum](https://groups.google.com/g/blockly) as a faster way to get technical help as I don't believe there is a bug report here. It would help to include more information about your goal so we can better assist you. Thanks!
