### ISSUE TITLE
Some typescript declares are still error

### ISSUE THREAD

**Issue by willzhanglala** [google/blockly#6215]
**Describe the bug**
Several typescript declarings are still wrong in version 8.0.3
1.  A lot of abstract objects are declaring as ()=>void
  - Blockly.getMainWorkspace()
  -  Blockly.Options {  constructor(options: () => void);  }
  - WorkspaceSvg.getMetricsManager() ： ()=>void
  - etc...
2.  Most of "xxx : someType | undefined" should be defined as "xxx? : someType" in typescript
3.  createSerializedKey(keyCode:number, modifiers:string[])  should be (keyCode:number, modifiers:number[]) 
4. ComponentManager.Capability.AUTOHIDEABLE/DELETE_AREA/DRAG_TARGET/POSITIONABLE  are not exported
5. Blockly.utils.Rect is exported as "const Rect: {" , it should be "class Rect"  

**To Reproduce**
1. 

**Expected behavior**
Typescript compilation should be ok.

**Additional context**

**Comment by Entkenntnis** [comment]
previous discussion: https://github.com/google/blockly/issues/6075

Looks like a lot of patience is needed here...

**Comment by zz-james** [comment]
ok, Blockly inject is a pretty important one! any chance of a hotfix ?
![Screenshot from 2022-07-28 16-00-33](https://user-images.githubusercontent.com/1120870/181575380-0c17dab3-8a11-4571-aa80-0673d07c68fa.png)

**Comment by gonfunko** [comment]
I believe these are now resolved after Blockly v9 when we migrated the codebase to Typescript. If you're still seeing typing issues (we know there are some things that are still e.g. marked as `any`, and are working towards eliminating those), please open a new issue.
