### ISSUE TITLE
serialization JSON schema / format

### ISSUE THREAD

**Issue by wakuflair** [google/blockly#6223]
Hi I would like to do some kind of parsing stuffs against the JSON content that serialized by `Blockly.serialization.workspaces.save`,
but I cannot find a schema or format documentation of the JSON content.

Is it existed?

**Comment by BeksOmega** [comment]
Hello! In the future, please direct questions like this to our [developer forum](https://groups.google.com/g/blockly) =) We try to keep the github issues uncluttered!

I don't believe there's currently a schema for the JSON output, however there is documentation for it. You can check out the type definitions via the [reference docs](https://developers.google.com/blockly/reference/js/Blockly.serialization.blocks#abstract-types), or the [source code](https://github.com/google/blockly/blob/e1bfbfa8cda568e7bbcb46ffdda11776bfc05eb5/core/serialization/blocks.js#L41). You can also see an [example in the original design doc](https://docs.google.com/document/d/1Dbpezxsd4H1S0p31ncrZ1hLaMfFYBeanv8pqjkpxoHI/edit?resourcekey=0-hYVVlo828cnLmnlj30Lysg#bookmark=id.5fg0g1xu5cmu). The [guides for serialization](https://developers.google.com/blockly/guides/configure/web/serialization) may also be helpful.

Best wishes =)
--Beka
