### ISSUE TITLE
'this' in getTopLevelWorkspaceMetrics_ and setTopLevelWorkspaceMetrics_

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#623]
appengine/third-party/blockly/core/workspace_svg.js:1302: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  var svgSize = Blockly.svgSize(this.getParentSvg());
                                ^

appengine/third-party/blockly/core/workspace_svg.js:1303: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  if (this.toolbox_) {
      ^

appengine/third-party/blockly/core/workspace_svg.js:1304: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    if (this.toolboxPosition == Blockly.TOOLBOX_AT_TOP ||
        ^

appengine/third-party/blockly/core/workspace_svg.js:1305: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
        this.toolboxPosition == Blockly.TOOLBOX_AT_BOTTOM) {
        ^

appengine/third-party/blockly/core/workspace_svg.js:1306: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
      svgSize.height -= this.toolbox_.getHeight();
                        ^

appengine/third-party/blockly/core/workspace_svg.js:1307: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    } else if (this.toolboxPosition == Blockly.TOOLBOX_AT_LEFT ||
               ^

appengine/third-party/blockly/core/workspace_svg.js:1308: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
        this.toolboxPosition == Blockly.TOOLBOX_AT_RIGHT) {
        ^

appengine/third-party/blockly/core/workspace_svg.js:1309: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
      svgSize.width -= this.toolbox_.getWidth();
                       ^

appengine/third-party/blockly/core/workspace_svg.js:1317: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  var blockBox = this.getBlocksBoundingBox();
                 ^

appengine/third-party/blockly/core/workspace_svg.js:1320: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  var contentWidth = blockBox.width * this.scale;
                                      ^

appengine/third-party/blockly/core/workspace_svg.js:1321: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  var contentHeight = blockBox.height * this.scale;
                                        ^

appengine/third-party/blockly/core/workspace_svg.js:1322: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  var contentX = blockBox.x * this.scale;
                              ^

appengine/third-party/blockly/core/workspace_svg.js:1323: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  var contentY = blockBox.y * this.scale;
                              ^

appengine/third-party/blockly/core/workspace_svg.js:1324: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  if (this.scrollbar) {
      ^

appengine/third-party/blockly/core/workspace_svg.js:1342: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  if (this.toolbox_ && this.toolboxPosition == Blockly.TOOLBOX_AT_LEFT) {
      ^

appengine/third-party/blockly/core/workspace_svg.js:1342: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  if (this.toolbox_ && this.toolboxPosition == Blockly.TOOLBOX_AT_LEFT) {
                       ^

appengine/third-party/blockly/core/workspace_svg.js:1343: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    absoluteLeft = this.toolbox_.getWidth();
                   ^

appengine/third-party/blockly/core/workspace_svg.js:1346: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  if (this.toolbox_ && this.toolboxPosition == Blockly.TOOLBOX_AT_TOP) {
      ^

appengine/third-party/blockly/core/workspace_svg.js:1346: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
  if (this.toolbox_ && this.toolboxPosition == Blockly.TOOLBOX_AT_TOP) {
                       ^

appengine/third-party/blockly/core/workspace_svg.js:1347: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    absoluteTop = this.toolbox_.getHeight();
                  ^

appengine/third-party/blockly/core/workspace_svg.js:1355: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    viewTop: -this.scrollY,
              ^

appengine/third-party/blockly/core/workspace_svg.js:1356: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    viewLeft: -this.scrollX,
               ^

appengine/third-party/blockly/core/workspace_svg.js:1361: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    toolboxWidth: this.toolbox_ ? this.toolbox_.getWidth() : 0,
                  ^

appengine/third-party/blockly/core/workspace_svg.js:1361: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    toolboxWidth: this.toolbox_ ? this.toolbox_.getWidth() : 0,
                                  ^

appengine/third-party/blockly/core/workspace_svg.js:1362: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    toolboxHeight: this.toolbox_ ? this.toolbox_.getHeight() : 0,
                   ^

appengine/third-party/blockly/core/workspace_svg.js:1362: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    toolboxHeight: this.toolbox_ ? this.toolbox_.getHeight() : 0,
                                   ^

appengine/third-party/blockly/core/workspace_svg.js:1363: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    flyoutWidth: this.flyout_ ? this.flyout_.getWidth() : 0,
                 ^

appengine/third-party/blockly/core/workspace_svg.js:1363: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    flyoutWidth: this.flyout_ ? this.flyout_.getWidth() : 0,
                                ^

appengine/third-party/blockly/core/workspace_svg.js:1364: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    flyoutHeight: this.flyout_ ? this.flyout_.getHeight() : 0,
                  ^

appengine/third-party/blockly/core/workspace_svg.js:1364: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    flyoutHeight: this.flyout_ ? this.flyout_.getHeight() : 0,
                                 ^

appengine/third-party/blockly/core/workspace_svg.js:1365: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_
    toolboxPosition: this.toolboxPosition
                     ^

appengine/third-party/blockly/core/workspace_svg.js:1377: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
  if (!this.scrollbar) {
       ^

appengine/third-party/blockly/core/workspace_svg.js:1380: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
  var metrics = this.getMetrics();
                ^

appengine/third-party/blockly/core/workspace_svg.js:1382: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
    this.scrollX = -metrics.contentWidth * xyRatio.x - metrics.contentLeft;
    ^

appengine/third-party/blockly/core/workspace_svg.js:1385: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
    this.scrollY = -metrics.contentHeight * xyRatio.y - metrics.contentTop;
    ^

appengine/third-party/blockly/core/workspace_svg.js:1387: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
  var x = this.scrollX + metrics.absoluteLeft;
          ^

appengine/third-party/blockly/core/workspace_svg.js:1388: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
  var y = this.scrollY + metrics.absoluteTop;
          ^

appengine/third-party/blockly/core/workspace_svg.js:1389: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
  this.translate(x, y);
  ^

appengine/third-party/blockly/core/workspace_svg.js:1390: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
  if (this.options.gridPattern) {
      ^

appengine/third-party/blockly/core/workspace_svg.js:1391: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
    this.options.gridPattern.setAttribute('x', x);
    ^

appengine/third-party/blockly/core/workspace_svg.js:1392: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
    this.options.gridPattern.setAttribute('y', y);
    ^

appengine/third-party/blockly/core/workspace_svg.js:1395: WARNING - dangerous use of this in static method Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_
      this.updateGridPattern_();
      ^

42 warning(s)

**Comment by rachel-fenichel** [comment]
This is a result of #574.

The code is being called in exactly the same way of before, except that it's missing the annotation
@this Blockly.WorkspaceSvg
Blockly.WorkspaceSvg.getTopLevelWorkspaceMetrics_ and Blockly.WorkspaceSvg.setTopLevelWorkspaceMetrics_.

I can and will add the annotation back, which will get rid of some warnings, but this also seems like a code smell.
