### ISSUE TITLE
Android/iOS: Cannot edit text and number fields with webview_flutter

### ISSUE THREAD

**Issue by deadlocklogic** [google/blockly#6235]
**Describe the bug**

Using `webview_flutter` with the demos, the input field aren't showing the soft keyboard.

**To Reproduce**

Any demos which requires input.(Almost all of them).

**Expected behavior**

The keyboard showing as it does for online demos.

**Smartphone (please complete the following information):**
 - Any

**Additional infos**

Probably related to #2076?

Thanks

**Comment by maribethb** [comment]
Can you provide more information on your development setup? Our team doesn't use Flutter so if you could provide a reproduction (such as a sample repo we can run that demonstrates the problem) that greatly increases the chance we can figure out the problem and solve it. Thanks!

**Comment by rachel-fenichel** [comment]
I'm closing this as stale, but we can reopen if you provide more information on your development setup.
