### ISSUE TITLE
Update demos to use compiled message files

### ISSUE THREAD

**Issue by deadlocklogic** [google/blockly#6236]
**Describe the bug**

Demos in core use the uncompiled message files, which is no longer supported. Demos need to be updated to use the compiled messages.

**To Reproduce**

Open any demo of the master branch(Only the html is rendered correctly).

**Expected behavior**

To render correctly, as version 8.0.0 for example

**Screenshots**

<img width="819" alt="Screen Shot 2022-06-23 at 2 35 28 PM" src="https://user-images.githubusercontent.com/57906342/175290100-5e35b4b5-4422-4244-9d0d-8d7a954aa2e8.png">
<img width="429" alt="Screen Shot 2022-06-23 at 2 34 04 PM" src="https://user-images.githubusercontent.com/57906342/175290116-78ae1a37-bcfd-4bf9-8cfe-07d48de8bcd1.png">

**Desktop (please complete the following information):**
 - OS: OSX Monterey 12.4
 - Browser chrome, safari
 - Version master

**Smartphone (please complete the following information):**
 - Device: iPhone7 Plus
 - OS: iOS15.5
 - Browser flutter_webview/webkit
 - Version master

The same issue even on windows/iOS simulator.

**Comment by maribethb** [comment]
This is probably related to #6123 but I thought the fix for that was in master and was specifically tested with demos. Needs investigation

**Comment by maribethb** [comment]
The demos in core use uncompiled message files which is no longer supported. The remaining demos need be updated to use the compiled message files.

**Comment by maribethb** [comment]
@cpcallen fyi since I think you are working on a solution for other hosted playgrounds. This needs to be fixed before release so that developer tools continues to work.

**Comment by maribethb** [comment]
This was fixed, not by updating the demos, but by updating the uncompiled message files.
