### ISSUE TITLE
When controls_forEach is combined with JS-Interpreter, there can be more iterations than expected

### ISSUE THREAD

**Issue by benjie** [google/blockly#624]
Because [`controls_forEach` uses a `for (... in ...)` loop](https://github.com/google/blockly/blob/a2a4d4194df43e81407df65d6b0c09c6ad290d29/generators/javascript/loops.js#L162), this triggers an issue in JS-Interpreter where both the array indexes **and** the array methods are looped over - see https://github.com/NeilFraser/JS-Interpreter/issues/77

The simplest fix would be to wrap the insides of the loop with a `hasOwnProperty` call; however switching to another looping method [may be appropriate](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Array_iteration_and_for...in).

**Comment by benjie** [comment]
For anyone suffering this issue, a quick fix is to override [line 162 of generators/javascript/loops.js](https://github.com/google/blockly/blob/a2a4d4194df43e81407df65d6b0c09c6ad290d29/generators/javascript/loops.js#L162):

```js
code += 'for (var ' + indexVar + ' in ' + listVar + ') {\n' + branch + '}\n';
```

with this:

```js
code += 'for (var ' + indexVar + ' in ' + listVar + ') {if (' + listVar + '.hasOwnProperty(' + indexVar + ')) {\n' + branch + '}}\n';
```

(You can do this by just adding this code to your project:

```js
// HACK to solve https://github.com/google/blockly/issues/624
Blockly.JavaScript['controls_forEach'] = function(block) {
  // For each loop.
  var variable0 = Blockly.JavaScript.variableDB_.getName(
      block.getFieldValue('VAR'), Blockly.Variables.NAME_TYPE);
  var argument0 = Blockly.JavaScript.valueToCode(block, 'LIST',
      Blockly.JavaScript.ORDER_ASSIGNMENT) || '[]';
  var branch = Blockly.JavaScript.statementToCode(block, 'DO');
  branch = Blockly.JavaScript.addLoopTrap(branch, block.id);
  var code = '';
  // Cache non-trivial values to variables to prevent repeated look-ups.
  var listVar = argument0;
  if (!argument0.match(/^\w+$/)) {
    listVar = Blockly.JavaScript.variableDB_.getDistinctName(
        variable0 + '_list', Blockly.Variables.NAME_TYPE);
    code += 'var ' + listVar + ' = ' + argument0 + ';\n';
  }
  var indexVar = Blockly.JavaScript.variableDB_.getDistinctName(
      variable0 + '_index', Blockly.Variables.NAME_TYPE);
  branch = Blockly.JavaScript.INDENT + variable0 + ' = ' +
      listVar + '[' + indexVar + '];\n' + branch;
  code += 'for (var ' + indexVar + ' in ' + listVar + ') {if (' + listVar + '.hasOwnProperty(' + indexVar + ')) {\n' + branch + '}}\n';
  return code;
};
```
)

**Comment by NeilFraser** [comment]
This is a bug in the JS Interpreter.  Thanks for this.

**Comment by NeilFraser** [comment]
Fixed.  Polyfills are no longer enumerable in the JS Interpreter:
https://github.com/NeilFraser/JS-Interpreter/commit/08f81e7fe657d852a65fa9889a7a8861dfe90fc6

Note that the compressed package hasn't been updated yet.
