### ISSUE TITLE
Simple typo in docs

### ISSUE THREAD

**Issue by nmay231** [google/blockly#6245]
**Where**

https://developers.google.com/blockly/guides/configure/web/toolbox#dynamic_categories

**What**

- [X] Text
- [ ] Image or Gif
- [ ] Other

**Old content**

There are two instances of `PALLET` instead of `PALETTE` (easily found with ctrl-f). Funnily enough, a third instance was correctly spelled.

**Suggested content**

**Additional context**

**Comment by Shubham-Rasal** [comment]
Can i fix the typo ?

**Comment by BeksOmega** [comment]
> Can i fix the typo ?

Sadly not, as our docs aren't kept on github. But thank you for your interest! If you want to contribute we have a list of [help wanted issues](https://github.com/google/blockly/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22), which are a good place to get started =)

**Comment by gonfunko** [comment]
This should now be fixed.
