### ISSUE TITLE
Remove % from id generator

### ISSUE THREAD

**Issue by andrewfstratton** [google/blockly#625]
Retrieving a generated id can (rarely) fail due to parsing the json containing %1B (see https://groups.google.com/forum/#!topic/blockly/jk3T1_e5de0) which is parsed as an escape character.

This may only occur when referencing an id (which I have used to refer one block to another), this is uncertain since the persisted xml is quite long by the time this error occurs. This may also be specific to using PHP as a server side scripting (a deployment requirement).

Suggestion - remove % from the 'soup_', as has been done with $ (see https://github.com/google/blockly/commit/aeabf0ec6f9b9cde5888c51a6e83b5448c413d0f).

This could (probably) be encoded on saving - but introduces a rare, hard to debug, error and is probably better avoided.

Best wishes
Andy Stratton

**Comment by NeilFraser** [comment]
> which is parsed as an escape character.

Who or what is parsing % as an escape character?  XML and JSON (the two places where the ID shows up) do not consider % to be a special character.

**Comment by andrewfstratton** [comment]
Hi Neil
  Fair enough  - withdrawn

  Cheers
    Andy
