### ISSUE TITLE
Generate code from XML on the server side

### ISSUE THREAD

**Issue by shenjg1981** [google/blockly#626]
I try to generate code from XML on the server side in headless mode with nodejs, and I found two problems:
1. Get an error:  'DOMParser is not defined ' (in function textToDom() of xml.js), and I avoid it by importing xmldom module and copying the textToDom() code;
2. Get 'document is not defined' error unless Blockly.Events.disabled_ = 1;

    Is there anything I've missed ? I can't get more information about these problems.

 Any help would be greatly appreciated.

**Comment by rachel-fenichel** [comment]
1) DOMParser is a web API, so it makes sense that you need to do extra work to use it with node.
https://developer.mozilla.org/en-US/docs/Web/API/DOMParser#Browser_compatibility

2) Tracking in #631.  If you don't need events, call Blockly.Events.disable() and you should be fine.

**Comment by shenjg1981** [comment]
Thanks.

**Comment by TechplexEngineer** [comment]
This NPM package provides the DOMParser https://www.npmjs.com/package/xmldom
