### ISSUE TITLE
Move delete keyboard shortcut in-progress gesture check to precondition

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6274]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

**Describe the bug**

The delete keyboard shortcut currently checks if there is a gesture in progress from within its `callback` function, and returns early if so. This is what the `preconditionFn` is meant to do. Other keyboard shortcuts check for in-progress gestures from there.

See the [relevant code](https://github.com/google/blockly/blob/61322294da70c770b32abb28b9d695af75f61a16/core/shortcut_items.js#L85).

## To Fix

1) Add a check to the [precondition function](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/shortcut_items.ts#L57) to make sure a gesture is not in progress.
2) Remove the [gesture check](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/shortcut_items.ts#L72) from the callback.

**Comment by SophieNguyen113** [comment]
I would love to work on this issue

**Comment by humera811** [comment]
@BeksOmega I am interested in working on this

**Comment by patelb268** [comment]
I am interested
 in these issue

**Comment by BeksOmega** [comment]
@SophieNguyen113 Go for it!

@humera811 @patelb268 Looks like sophie got here first! If you comment on a different issue I can get you assigned =)

**Comment by humera811** [comment]
oh okay

**Comment by johnnesky** [comment]
I assigned @SophieNguyen113 to https://github.com/google/blockly/issues/7176 so I assigned @humera811 to this one.
