### ISSUE TITLE
Refactor the clipboard API

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6275]
**Is your feature request related to a problem? Please describe.**

The clipboard functions use a [module-private variable](https://github.com/google/blockly/blob/61322294da70c770b32abb28b9d695af75f61a16/core/clipboard.js#L26) to store the copy data for copying and pasting. This makes the clipboard API difficult for external developers to use. E.g. if they want to create a clipboard with multiple "slots" it is impossible for them to do so.

This is particularly bad because the clipboard API includes some important logic for preventing pasting from going over limits to the maximum number of blocks, and the maximum number of blocks of a given type. So if a developer wanted to create a customized clipboard, they would need to duplicate this code from core.

**Describe the solution you'd like**

The `copy` function should return what is being copied.
The `paste` function should take in an optional parameter for what to paste, that takes precedence over the module-private variable.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by maribethb** [comment]
Related issues: #3833, #6846
