### ISSUE TITLE
Add blocks to default categories

### ISSUE THREAD

**Issue by EvilPeanut** [google/blockly#628]
Hi All,

Is it possible to add blocks to the default categories?
If not, could we add this functionality?
I would like to add a block to the Variables category.

Thanks,
Reece

**Comment by rachel-fenichel** [comment]
There isn't a way to add a block to the variables category through the usual toolbox XML.  You can go edit this code: https://github.com/google/blockly/blob/develop/core/variables.js#L99 to directly add blocks.

This constraint applies to the variables and procedures categories, which are dynamically generated.

Agreed that it's a nice feature to have; it's not currently at the top of our queue.

**Comment by maribethb** [comment]
This is not something we're going to add a specific API for. The contents of the dynamic categories are controlled by dynamic category callbacks and if you want custom contents in there you can define your own callback.
