### ISSUE TITLE
procedure call block without arguments gets a "with" field after collapsing and expanding

### ISSUE THREAD

**Issue by yoderjen** [google/blockly#63]
My blockly is less than a week old.

Bring out a procedure and a call block and it looks great:
![aaaaagood](https://cloud.githubusercontent.com/assets/10271662/6135525/416f42b6-b11e-11e4-8fcf-312c2cc89e61.jpg)

If you then collapse and expand the call block, it gets a "with" field (gets it while collapsed too, I didn't make a screenshot):
![aaaaabad](https://cloud.githubusercontent.com/assets/10271662/6135538/56024ade-b11e-11e4-91f4-e246a9898a31.jpg)

**Comment by NeilFraser** [comment]
Confirmed.  Working on it...  (Collapsing blocks has been the source of endless bugs.)

**Comment by NeilFraser** [comment]
Fixed.  Uncovered (and fixed) a nest of other fun bugs in the process (e.g. collapse a call block, then add parameters to the procedure definition).  Thanks!
