### ISSUE TITLE
browser_events try to make every event look like a MouseEvent without defining the type properly

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6311]
**Describe the bug**

In the browser_events `.bind` function, we add `clientX` and `clientY` properties to touch events, so that callbacks can react uniformly to events, regardless of whether they were actually triggered by a mouse or a pointer.

However, when we do this, we are just adding new properties to the object, instead of constructing a new object with the new properties. This makes typescript unhappy. It forces us to cast to `AnyDuringMigration` before adding the new properties.

**Proposed solution**

We should define a new custom event type that only provides properties we are guaranteeing we will provide. Besides `clientX` and `clientY` not sure exactly what these should be.

**Additional Information**

In an ideal world we would probably just use Pointer events (since this sort of input-agnostic handling is what they're meant for). However, that would be a breaking change because right now external developers rely on the `clientX` and `clientY` properties.

**Comment by cpcallen** [comment]
I think the proposed solution sounds suitable, but if you want you could sell us on why the obvious backwards-compatible alternative of adding `clientX` and `clientY` to a suitable superclass is not a good idea.

**Comment by rachel-fenichel** [comment]
Long-term we definitely want to move to PointerEvents and delete as much of our custom code as possible. It all predates PointerEvents as a fully-implemented standard.

**Comment by cpcallen** [comment]
> This alternative is not obvious to me lol Could you elaborate on what you mean?

I think there may be miscommunication resulting from my ignorance about the hierarchy of event types involved.

Your proposal sounded like you want to create a new class within the hierarchy, perhaps somewhere towards the leaves, that adds `clientX` and `clientY`.  I was instead proposing to modify an existing class—whichever one is the common ancestor of all the event types that should have coordinates associated with them—to add those properties.

Perhaps that is not possible for some reason?

**Comment by rachel-fenichel** [comment]
The classes here are `Event`, `MouseEvent`, `TouchEvent`, and `PointerEvent`. Those are all browser APIs, and so we can't just change the hierarchy.

**Comment by cpcallen** [comment]
> The classes here are `Event`, `MouseEvent`, `TouchEvent`, and `PointerEvent`. Those are all browser APIs, and so we can't just change the hierarchy.

Not with that attitude.  😉

(Unseriously: those are all `var`s, and `Object.setPrototypeOf` is a thing.  The only hard part would be getting the TypeScript compiler to go along with it…)

**Comment by BeksOmega** [comment]
> > The classes here are `Event`, `MouseEvent`, `TouchEvent`, and `PointerEvent`. Those are all browser APIs, and so we can't just change the hierarchy.
> 
> Not with that attitude. 😉
> 
> (Unseriously: those are all `var`s, and `Object.setPrototypeOf` is a thing. The only hard part would be getting the TypeScript compiler to go along with it…)

Sometimes the TypeScript compiler is rightly cantankerous :P

**Comment by maribethb** [comment]
> In an ideal world we would probably just use Pointer events (since this sort of input-agnostic handling is what they're meant for). However, that would be a breaking change because right now external developers rely on the clientX and clientY properties.

`PointerEvent` is a subclass of `MouseEvent` so it would still have `clientX` and `clientY` properties. So this wouldn't actually be a breaking change in that case, right?

see also #6543 which I vote we close this issue in favor of, since it is currently on our OKRs to do.
