### ISSUE TITLE
Blockly demos dont look right in browser

### ISSUE THREAD

**Issue by GogittossjX** [google/blockly#6332]
**Describe the bug**
I have downloaded blockly through github and the google page. In both instances I just downloaded the zip, went to the demos folder location and opened a few of them in browser. I used multiple browsers but when i open it, the code blocks on the left either dont show up, are undraggable, or just look incorrect. Am I downloading the package incorrectly, because from what ive read thats all that needs to be done. I also tried on a different computer with the same result
![Capture3](https://user-images.githubusercontent.com/110940774/183765327-e2b5fa7c-486f-4e52-8c72-ed38df6daf70.PNG)
![Capture2](https://user-images.githubusercontent.com/110940774/183765330-dfa45acb-fde4-45df-b185-7a75f9a7f452.PNG)
![Capture](https://user-images.githubusercontent.com/110940774/183765333-81da40ea-126e-4fad-8e44-b9136990a2fd.PNG)

**To Reproduce**

1. Clone repository
2. Open one of the demos in browser
3. See error

**Comment by rachel-fenichel** [comment]
This is a symptom of #6123. We are aware of the issue and working on it.

Did you clone the repository to work on Blockly or to use Blockly as part of another project?

If you just want to use the demos, you can find them on our [GitHub pages site](https://google.github.io/blockly-samples/) under "Demos".

**Comment by GogittossjX** [comment]
I want to integrate blockly into a larger project. I was looking through the demos to get started, and basically want to do the same thing as the Code generator example with some changes

**Comment by rachel-fenichel** [comment]
If you're just getting started, you can go back one release or wait for our next patch release to fix this issue. I recommend getting Blockly either through [npm](https://www.npmjs.com/package/blockly) or unpkg rather than cloning the repository, because you'll be able to easily stay up to date with new releases. There are instructions on the [Getting Started](https://developers.google.com/blockly/guides/get-started/web) page.

**Comment by GogittossjX** [comment]
I tried npm but the demos werent inside the downloaded file. Ill use the old release for now. Thank you
