### ISSUE TITLE
Remove EdgeHTML support

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#6339]
**Is your feature request related to a problem? Please describe.**

The Edge browser used to use the [EdgeHTML](https://en.wikipedia.org/wiki/EdgeHTML) browser engine, but has not done so since version 79. Our checks for Edge in `useragent.js` were actually looking for EdgeHTML. It is now fully deprecated, so we can remove these workarounds.

**Describe the solution you'd like**

- [x] Remove uses of `userAgent.EDGE` in Blockly core.
- [x] Remove `isEdge` and `EDGE` from `useragent.ts`
- [ ] Remove EdgeHTML workarounds from stripped-down `base.js` **Left in to match upstream `base.js`**

**Describe alternatives you've considered**

Leave them in. Rejected as extra ongoing maintenance for something that is not used.

**Additional context**

Inspecting user agent strings is strongly discouraged because they often contain misleading information--for instance, the Edge browser uses the Blink browser engine.

Found while looking into user agent strings for #6336.

**Comment by cpcallen** [comment]
> Remove EdgeHTML workarounds from stripped-down base.js

From a maintenance point of view it is better that the implementations in `base-minimal.js` be identical to the ones in the upstream Closure-supplied `base.js`.  So until Closure drops support we should not either.
