### ISSUE TITLE
BlocklyFactory: When a block has an output type, blockly factory doesn't recognize a save

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#636]
When you attach an output type to the factory base block in blockly factory, and click the update button to save changes to the block, it doesn't recognize the save and the update button stays highlighted as if you never clicked it.

Looking at the xml of the workspace, it seems like clicking the update button is causing the id of the "any" shadow block to change. i.e. if you do a workspaceToDom then click the update button and do another workspaceToDom, the ids of the "any" shadow block are different.  Not sure why yet though.

**Comment by picklesrus** [comment]
This turns out to be a rather odd interaction between shadow blocks and the mutating factory_base block trying to spawn shadow blocks as it mutates.
When you add a connection in the container block and replace the "type" shadow block with a regular block, the xml you get from blockToDom for the output portion looks something like this (this is what we put in local storage):
<value name="OUTPUTTYPE">
  <block type="type_boolean" id="-Gj,l7rh(YYFU:1CfK:I"></block>
  <shadow type="type_null" id="teL,2l7V+X;c+%%O7{ev"></shadow>
</value>

There is also code in the factory base block that creates a new shadow block using workspace.newBlock.  That code is there to spawn a shadow block when the user adds an output connection in the base block.  See https://github.com/google/blockly/blob/develop/demos/blockfactory/blocks.js#L101

So, when you load into block factory workspace from xml, the shadow block mentioned above is the one that ends up winning and the code to compare the current workspace with what's in storage fails reports a difference.

There are a few ways I can think to side-step this problem, but it is kind of interesting because any of manipulation like this in the block definition is likely to alter the xml on load so perhaps worth discussion.

**Comment by picklesrus** [comment]
Fixed in develop

**Comment by NielsH12** [comment]
I'm still experiencing this issue. Didn't it get fixed?

**Comment by RoboErikG** [comment]
Looks like it's back. Possibly related to removal of ids in the stored xml, but needs investigation.

**Comment by samelhusseini** [comment]
Fixed by #2801
