### ISSUE TITLE
Add custom Block to Variable/Procedure/... categories

### ISSUE THREAD

**Issue by bidinzky** [google/blockly#6405]
**Describe the solution you'd like**

An API to add a Block to the “special” categories Variables, Procedures, …

**Comment by bidinzky** [comment]
If there is already a solution to this and i was just to dumb to find it please close the issue

**Comment by BeksOmega** [comment]
Hello!

There is no way to add a block to these categories, but you can redefine them! See the dynamic category docs for reference.

If you have any further questions, please direct them to the [forums](https://groups.google.com/g/blockly).

Best wishes,
--Beka
