### ISSUE TITLE
Context Menu Rendering Customization

### ISSUE THREAD

**Issue by oltdaniel** [google/blockly#6406]
**Is your feature request related to a problem? Please describe.**

Currently there is no way of customizing the rendering of the context menu. This is as far as I know, the only thing the developer cannot overwrite like the block renderer, without monkey patching a dozen functions. (See additional context on how monkey patching would look like to add a custom value to an menu item that is used for DOM rendering of such item).

_Why would someone like to do that?_ Well, imagine you want to add additional elements to the DOM of the context menu, like a icon. 

**Describe the solution you'd like**

I'd like to have a similar solution the block renderer. This would allow the developer to simply extends the base class of the context menu and just overwrite the underlying functions to make the code work to e.g. render an additional DOM child in the menu item, extend the context menu items with a custom additional function, ...

```js
Blockly.inject(blocklyDiv, {
  plugins: {
    contextMenuItem: CustomContextMenuItem,
    contextMenuRegistry: CustomContextMenuRegistry,
  }
})
```

**Describe alternatives you've considered**

- **Monkey Patching**: The only solution to avoid a fork, as there is no public API that would allow changes to the extend needed for context menu rendering customization. For more context with an example, see the **Additional context** below.
- **Forking**: Causes way to much overhead, if you consider everything else allows full customization with public APIs (as far as I know).

**Additional context**

Let's take adding custom icons the context menu items as an example, and see what would be required to change via monkey patching to make this work.

- We know, that `Blockly.MenuItem` is the class where the DOM is created for the Context Menu Item. However, due to abstractions this class only has access to a very few infos, as everything is abstracted via setters. So there is no access to the original Option Value from the registry.
- Let's see where `Blockly.MenuItem` is being constructed to form the menu itself. We end up at `populate_` in `core/contextmenu.js` which is a private function. Thereby, overwriting via Monkey patching is not possible (bundling could change where this will end up).
- Ok, so where is `populate_` being used? In `Blockly.ContextMenu.show`. Great a public function. But it uses more private functions... `menu_` to store the menu instance and `position_`... So this is too much work to Monkey patch and would probably cause other issues. 

Anyway, let's assume we accept copying the whole `core/contextmenu.js` and make our changes. **How would we know which icon to add anyway?**

- Let's see what we have in the `options` variable in the `core/contextmenu.js`. Well, only an array with the already interpolated translation text and only the bare minimum of infos. No id or value of the original context menu item in the registry.
- Where do we get the `options` value from? Looks like we get that from `Blockly.ContextMenuRegistry.registry.getContextMenuOptions`. Something that would be more or less, easily monkey patched.

I hope you see what I'm trying to show here. Everything in Blockly is more or less easily customizable. But the Context Menu remains to be a real difficult part to extend with requiring a full patch of the `core/contextmenu.js` file and modifying  `Blockly.ContextMenuRegistry.registry.getContextMenuOptions`. As there is nearly no monkey patching needed for anything else, I think it would be great to finally move the context menu into a similar system.

**Comment by oltdaniel** [comment]
After some more digging, I found some more context on how this can be changed/implemented depending on the effort someone (I would also like to submit a patch if it will be accepted):

- The Context Menu is something, that is kind of detached from the workspace/block in some sense. A Block or Workspace, implement a `showContextMenu` function that is being called by `core/gestures.js`. The only connection to the target is only shown as a scope. So there is an abstraction necessary for handling workspace specific ContextMenu classes upon injection as done with e.g. the Toolbox. This would be a very time consuming task, but may offer the result of a fully customizable Blockly.
- An probably easier approach would be, to extend the context menu item object with a function like `mutateDom` which is being called before the dom is returned for rendering. See an example below.

However, the short version is essentially: Currently the context menu is extremely global and loses quickly context of its parent Workspace. It may be time to change that, as the context menu is and will always be workspace specific. 

#### Example for context registry item extension

`core/contextmenu_registry.js`
```js
/**
 * A menu item as entered in the registry.
 * @typedef {{
 *    callback: function(!ContextMenuRegistry.Scope),
 *    scopeType: !ContextMenuRegistry.ScopeType,
 *    displayText: ((function(!ContextMenuRegistry.Scope):string)|string),
 *    // Allow for mutation of the rendered DOM
 *    mutateDom: function(!ContextMenuRegistry.Scope), !Element): !Element,
 *    preconditionFn: function(!ContextMenuRegistry.Scope):string,
 *    weight: number,
 *    id: string
 * }}
 */
ContextMenuRegistry.RegistryItem;
```

`core/contextmenu.js`
```js
/**
 * Create the context menu object and populate it with the given options.
 * @param {!Array<!Object>} options Array of menu options.
 * @param {boolean} rtl True if RTL, false if LTR.
 * @return {!Menu} The menu that will be shown on right click.
 * @private
 */
const populate_ = function(options, rtl) {
  // ...

  for (let i = 0; i < options.length; i++) {
    const option = options[i];
    // NOTE: Pass full option for more info in the future handling of this item
    const menuItem = new MenuItem(option.text, option);

    // ...
  }

  // ...
}
```

`core/menu.js`
```js
/**
 * A basic menu class.
 * @alias Blockly.Menu
 */
const Menu = class {

  // ...

  /**
   * Creates the menu DOM.
   * @param {!Element} container Element upon which to append this menu.
   */
  render(container) {
      // ...

    // Add menu items.
    for (let i = 0, menuItem; (menuItem = this.menuItems_[i]); i++) {
      // NOTE: Create DOM and check if the is a mutateDom functionp resetn
      let dom = menuItem.createDom();
      if (menuItem.value_ && menuItem.value_.mutateDom) {
        // Mutate DOM if required by the context menu item
        dom = menuItem.value_.mutateDom(dom);
      }
      element.appendChild(dom);
    }

    // ...
  }

  // ...

}
```

**Comment by cpcallen** [comment]
Thanks for this well-thought out proposal.  I'm not sure we have the resources to implement it in the near future, but I'll see if the team has any feedback about it, and perhaps you or another interested developer can send us a PR for it in due course.

**Comment by maribethb** [comment]
Thanks again for this proposal. This is something we're interested in supporting, but probably in a slightly different form than you've proposed.

`menuitem.ts` already supports passing in an HTMLElement instead of a string.
So in `ContextMenuRegistryItem` we could allow you to supply a function that returns an HTMLElement. If that function is provided, we'll call it and pass that Element to `menuitem` instead of the `displayText` value.

This way you wouldn't modify the DOM after its created; you have control over it in the first place. It would be a bit simpler though may require you to take special care with the CSS classes to match the built-in options.

This is something we'd accept a PR for but is not currently on our priority list for us to implement ourselves.

**Comment by BeksOmega** [comment]
Additional request: https://groups.google.com/g/blockly/c/lIP_k8jgA4s/m/8_3bE5m_AAAJ

**Comment by BeksOmega** [comment]
App Inventor also has a request for this. They want to be able to add help icons to their context menu items that people can click to get more info about the option.
