### ISSUE TITLE
How to set a function for Block's helpURL?

### ISSUE THREAD

**Issue by pmkary** [google/blockly#641]
Hy everyone.

I'm making a custom blockly language to replace RegEx's syntax:

[![](https://cloud.githubusercontent.com/assets/2157285/18604069/2f72743e-7c8d-11e6-90a0-7aebc5555faf.png)](https://github.com/karyfoundation/orchestra)
_You may find it [here](https://github.com/karyfoundation/orchestra)_

Now as you may have noticed it runs inside of Electron hence I can't set a URL for it. So about the only thing I knew to make it work was to insert some JavaScript into the URL:

```JavaScript
this.setHelpUrl(`javascript: void openHelpWindowAtReferenceId("${ block_id }")`);
```

But what happens is that nothing happens. I tried to see what goes wrong and did this:

```JavaScript
this.setHelpUrl(`javascript: void ( ( ) => {
   try {
      openHelpWindowAtReferenceId("${ block_id }");
   } catch ( err ) {
      alert( err );
   }
})( )`);
```

And what I got was `openHelpWindowAtReferenceId`. So it was in the global namespace at first and changed it's place to be initialized before Blockly and changed the loading process so that could be loaded first. But still it's not defined.

All the basic JavaScript functions are available but none of my functions works there.

Why is that so? Is Blockly using any XSS blocker for URLs? What can I do to set a function for the block's Help property?

**Comment by NeilFraser** [comment]
Just set the help URL to be a function.  The function should return the URL of the help page.  Within the function `this` is the block in question.
```
this.setHelpUrl(function () {return 'http://example.com?' + this.id;});
```

**Comment by pmkary** [comment]
No the problem is not with the block properties, Infact it works well:

<img width="477" alt="screen shot 2016-09-26 at 3 11 42 pm" src="https://cloud.githubusercontent.com/assets/2157285/18833045/9978d1c8-83fb-11e6-9320-ec79d3e55166.png">

I have a help window that opens separately:

<img width="1280" alt="screen shot 2016-09-26 at 9 32 04 am" src="https://cloud.githubusercontent.com/assets/2157285/18833199/70b983bc-83fc-11e6-80cb-c46f3b53bc05.png">

Now I can't open this window with a URL. I have to open it myself. So I want to set a function instead of a URL string. And as I can't set an `onclick` event the only thing I could imagine was to use `<a href="javascript: someFunction( );"></a>` and it works with native JavaScript functions and tools, but when it comes to custom functions it says that the function is not defined and my question is that how can I call my functions there. What's the problem that keeps my functions from being available in the href?

**Comment by pmkary** [comment]
Okay I think I found a workflow. It's to override this:

```JavaScript
Blockly.BlockSvg.prototype.showHelp_ = function ( ) {
    ...
};
```
