### ISSUE TITLE
Mutators broken due to `TypeError` in `Mutator.prototype.createEditor_`

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#6420]
**Describe the bug**

Mutator button fails to open the mutator flyout for many (but not all) mutable sample blocks due to a `TypeError` in `Mutator.prototype.createEditor_`.

**To Reproduce**

1. Open `tests/playground.html`
0. Open browser console.
0. Click on 'Lists' in the toolbox.
0. Drag a "create empty list" or "create list with" block to the main workspace.
0. Click on the mutator (gear) button of the newly-created block.
0. Observe no mutator flyout appears; observe instead an error in the console (stack trace below).

**Expected behavior**

No error occurs, and the flyout appears.

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Browser: Chrome ~latest
 - Version: Blockly `9.0.0-beta.1`

**Smartphone (please complete the following information):**

**Stack Traces**

```
mutator.ts:168 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Mutator.createEditor_ (mutator.ts:168:26)
    at Mutator.setVisible (mutator.ts:309:57)
    at Mutator.iconClick_ (icon.ts:107:12)
    at Mutator.iconClick_ (mutator.ts:149:13)
    at SVGGElement.wrapFunc (browser_events.ts:80:14)
```

**Additional context**

This bug is _not_ present in `master` (i.e., previous to v `9.0.0-beta.1`).

**Comment by BeksOmega** [comment]
Closed by #6440
