### ISSUE TITLE
An Error after Blockly.serialization.workspaces.load

### ISSUE THREAD

**Issue by dingdinglz** [google/blockly#6443]
**Describe the bug**

An Error after Blockly.serialization.workspaces.load,and I can't do anything in workspace then.Even move.

**To Reproduce**

1. Use the code Blockly.serialization.workspaces.load

My code is this:

```
      axios.get('/api/plugin/getjson?name=' + plugin_name).then(function (res) {
        Blockly.serialization.workspaces.load(res.data, that.workSpace, true);
      });
```

**Expected behavior**

Load and I can work correctly.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [firefox]
 - Version [105.0]

**Stack Traces**

```
Uncaught Error: Unable to find connection in connectionDB.
    removeConnection connection_db.js:154
    moveTo rendered_connection.js:204
    moveToOffset rendered_connection.js:227
    updateConnectionLocations_ block_svg.js:1788
    render block_svg.js:1744
    showInsertionMarker_ insertion_marker_manager.js:648
    showPreview_ insertion_marker_manager.js:544
    maybeShowPreview_ insertion_marker_manager.js:523
    update insertion_marker_manager.js:264
    drag block_dragger.js:217
    handleMove gesture.js:559
    handleMove touch_gesture.js:176
    h browser_events.js:88
    conditionalBind browser_events.js:98
    bindMouseEvents touch_gesture.js:138
    doStart gesture.js:531
    doStart touch_gesture.js:117
    handleWsStart gesture.js:673
    onMouseDown_ workspace_svg.js:1767
    h browser_events.js:86
    conditionalBind browser_events.js:98
    createDom workspace_svg.js:913
    module$contents$Blockly$inject_createMainWorkspace inject.js:163
    inject inject.js:78
    mounted pluginwrite.vue:24
    callWithErrorHandling runtime-core.esm-bundler.js:155
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:164
    __weh runtime-core.esm-bundler.js:2682
    flushPostFlushCbs runtime-core.esm-bundler.js:339
    render2 runtime-core.esm-bundler.js:6232
    mount runtime-core.esm-bundler.js:4422
    node_modules chunk-22XXMGDN.js:8911
    bootstrap main.ts:38
    async* main.ts:41
connection_db.js:154:12
    removeConnection connection_db.js:154
    moveTo rendered_connection.js:204
    moveToOffset rendered_connection.js:227
    updateConnectionLocations_ block_svg.js:1788
    render block_svg.js:1744
    showInsertionMarker_ insertion_marker_manager.js:648
    showPreview_ insertion_marker_manager.js:544
    maybeShowPreview_ insertion_marker_manager.js:523
    update insertion_marker_manager.js:264
    drag block_dragger.js:217
    handleMove gesture.js:559
    handleMove touch_gesture.js:176
    <anonymous> self-hosted:1356
    h browser_events.js:88
    (异步：EventListener.handleEvent)
    conditionalBind browser_events.js:98
    bindMouseEvents touch_gesture.js:138
    doStart gesture.js:531
    doStart touch_gesture.js:117
    handleWsStart gesture.js:673
    onMouseDown_ workspace_svg.js:1767
    h browser_events.js:86
    (异步：EventListener.handleEvent)
    conditionalBind browser_events.js:98
    createDom workspace_svg.js:913
    module$contents$Blockly$inject_createMainWorkspace inject.js:163
    inject inject.js:78
    mounted pluginwrite.vue:24
    mounted self-hosted:1356
    callWithErrorHandling runtime-core.esm-bundler.js:155
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:164
    __weh runtime-core.esm-bundler.js:2682
    flushPostFlushCbs runtime-core.esm-bundler.js:339
    render2 runtime-core.esm-bundler.js:6232
    mount runtime-core.esm-bundler.js:4422
    mount runtime-dom.esm-bundler.js:1606
    bootstrap main.ts:38
    AsyncFunctionNext self-hosted:807
    (异步：async)
    <anonymous> main.ts:41

```

**Additional context**

**Comment by dingdinglz** [comment]
@BeksOmega How can I solve this problem in a short time. Or is there any alternative.

**Comment by maribethb** [comment]
Hello, there may be a problem with the code you are trying to load. Can you post the data you're trying to load, and possibly how you are generating that data as well?

**Comment by dingdinglz** [comment]
> Hello, there may be a problem with the code you are trying to load. Can you post the data you're trying to load, and possibly how you are generating that data as well?

I use Blockly.serialization.workspaces.save()

this is a simple code. Thank You

`{"blocks":{"languageVersion":0,"blocks":[{"type":"controls_repeat_ext","id":"|1XUOUBIxEYoIwPe2Hxt","x":206,"y":84,"inputs":{"TIMES":{"shadow":{"type":"math_number","id":"g,*uSa^E6lcu,;Xi?hV+","fields":{"NUM":10}}},"DO":{"block":{"type":"controls_if","id":"W4[W9Q$4?98,a6;6BD~y"}}}},{"type":"text_join","id":"l`qc[-^?v+Nb?R_Cx;82","x":363,"y":100,"extraState":{"itemCount":2}},{"type":"math_arithmetic","id":"x)cC;#Y|Z,^Ob~eNvm?e","x":515,"y":288,"fields":{"OP":"ADD"},"inputs":{"A":{"shadow":{"type":"math_number","id":"N7n6qdn)LpF;nbX[T}9;","fields":{"NUM":1}}},"B":{"shadow":{"type":"math_number","id":"y(@kL8%._?yvz!(xm(@7","fields":{"NUM":1}}}}},{"type":"text","id":"dsjFn?JfMP1~l+2^PM4p","x":567,"y":322,"fields":{"TEXT":""}}]}}`

**Comment by BeksOmega** [comment]
Hello! Are you sure that this is being triggered by the `load` call? I don't see that anywhere in your stack trace, and the JSON you are loading also works properly in the [playground](https://blockly-demo.appspot.com/static/tests/playground.html).

**Comment by dingdinglz** [comment]
> Hello! Are you sure that this is being triggered by the `load` call? I don't see that anywhere in your stack trace, and the JSON you are loading also works properly in the [playground](https://blockly-demo.appspot.com/static/tests/playground.html).

 Could this be a problem with async ？

**Comment by dingdinglz** [comment]
> > Hello! Are you sure that this is being triggered by the `load` call? I don't see that anywhere in your stack trace, and the JSON you are loading also works properly in the [playground](https://blockly-demo.appspot.com/static/tests/playground.html).
> 
> Could this be a problem with async ？

But I must use axios，In Vue and nodejs , I can't solve this problem for a long time.

**Comment by maribethb** [comment]
Hi, since we can't identify a bug with the serialization system right now (e.g. the json you're trying to load works fine in the playground) this seems like an issue we'd have better luck supporting you with on the forum. We don't typically provide developer support over GitHub issues and I don't want your problem to get lost in the noise here.

Could you repost this question on the forum? https://groups.google.com/g/blockly As Beka said, it doesn't look like the `load` call is actually what's triggering this error, so if you can provide a set of reproduction steps, or show more of your application's code and explain the circumstances, that would help us debug. And someone on the forum might have experience with axios and can chime in with their ideas as well.

If we uncover an actual bug in Blockly code, then we can open another issue at that time. Thanks!

**Comment by dingdinglz** [comment]
> Hi, since we can't identify a bug with the serialization system right now (e.g. the json you're trying to load works fine in the playground) this seems like an issue we'd have better luck supporting you with on the forum. We don't typically provide developer support over GitHub issues and I don't want your problem to get lost in the noise here.

ok,thank you
