### ISSUE TITLE
Dead links to `run_prettify.js` in code demo and blockfactory

### ISSUE THREAD

**Issue by derwehr** [google/blockly#6458]
**Describe the bug**

The [Code Demo](https://github.com/google/blockly/blob/02a57122debaa4ca043312dec547944afae658c4/demos/code/code.js#L204). the [blockfactory](https://github.com/google/blockly/blob/2bf842ac65456e61d8c655daec99f8fbc75d2c29/demos/blockfactory/index.html#L34) and the [old blockfactory](https://github.com/google/blockly/blob/3fe56b083c62549cb2bdb17270846bf17ced5d7a/demos/blockfactory_old/index.html#L91) all use an [outdated link](https://github.com/googlearchive/code-prettify/pull/573) link to RawGit, which had now wound down.

This link should be replaced with the new [jsdelivr link](https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js), as described in the [readme](https://github.com/googlearchive/code-prettify#setup). I'll submit a PR to fix this

**Comment by BeksOmega** [comment]
Closed via #6459
