### ISSUE TITLE
Blockly Factory: Save toolbox XML without id attributes.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#649]
Toolbox block ids are not currently used by Blockly apps.  The current exporter exports ids for child blocks, including shadows. Root block ids are stripped.

Further, if an app ever tries to use ids to toolbox, they will probably prefer human/developer readable ids over the randomly generated strings.

**Comment by picklesrus** [comment]
Ability to remove ids in xml also requested in another context. See #524

**Comment by rachel-fenichel** [comment]
Fixed by #675
