### ISSUE TITLE
Improve type information for the validator in `./core/field.ts`

### ISSUE THREAD

**Issue by btw17** [google/blockly#6505]
**Is your feature request related to a problem? Please describe.**

`Function`, the type of `validator_` in `./core/field.ts`, doesn't provide the information needed to use it. Additionally, it's a banned type in **Blockly Samples** by default.

**Describe the solution you'd like**

1. Upgrade `validator_`'s type in `./core/field.ts`
2. Update field classes in `./core` to reflect that change
3. Update impacted [Blockly Samples plugins](https://github.com/google/blockly-samples/tree/master/plugins)

**Additional context**

See the [field-slider plugin upgrade to TypeScript](https://github.com/google/blockly-samples/pull/1217#discussion_r990442714) in **Blockly Samples** to see the disabled eslint rule and the initial discussion about this issue.

**Comment by MatoPlus** [comment]
@BeksOmega My group (for a uni project) would like to pick this up : )

**Comment by BeksOmega** [comment]
Hi @MatoPlus we actually already have someone internally working on this! We just forgot to assign them :/ But I've just fixed that!

For now you can just disable the lint rule like @btw17 did here: https://github.com/google/blockly-samples/pull/1217#discussion_r990442714

Best wishes!
