### ISSUE TITLE
Undo of Input Block will reset it if changing was the last action

### ISSUE THREAD

**Issue by pip8786** [google/blockly#651]
This is on the master branch.

To reproduce, go here: https://blockly-demo.appspot.com/static/demos/toolbox/index.html
1. Drag in a number block (defaults to 0)
2. Edit the block to be anything but 0
3. Trash the block
4. Undo the trashing

Expected behavior: The block will have the value prior to trashing
Current Behavior: The block will be reset to 0

This set of steps works fine:
1. Drag a number block (defaults to 0)
2. Edit the block to be anything but 0
3. Drag another block or do any other action that would create an undo even.
4. Trash the original block
5. Undo the trashing

The block will retain it's value prior to trashing.

Based on my debugging through the code it seems that for some reason changing the value is grouped with the trashing in the first scenario. I feel this is unwanted behavior.

**Comment by pip8786** [comment]
@NeilFraser Any update on this?

**Comment by ademenev** [comment]
It's even worse

1. Drag a number to workspace
2. Drag another number
3. Change first number to 10
4. Change second number to 20
5. Trash first number
6. Undo

Ufter undo, first number is restored, with value of 0. And the second number is reset to zero, too!
