### ISSUE TITLE
field_checkbox loses its value in domToWorkspace

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#653]
Calling domToWorkspace with a block that contains a checkbox fails to load the value correctly.

To test, add the following block definition to a Blockly app:
Blockly.Blocks['motor_select'] = {
init: function() {
    this.jsonInit({
  "message0": "Motors a %1 b %2",
  "args0": [
    {
      "type": "field_checkbox",
      "name": "MOTOR_A",
      "checked": false
    },
    {
      "type": "field_checkbox",
      "name": "MOTOR_B",
      "checked": false
    }
  ],
  "previousStatement": null,
  "nextStatement": null,
  "tooltip": "",
  "helpUrl": "http://www.example.com/"
});}
};

Blockly.JavaScript['motor_select'] = function(block) {
  // Generate JavaScript for setting the colour.
  var motor1 = block.getFieldValue('MOTOR_A');
  var motor2 = block.getFieldValue('MOTOR_B');
  console.log('motor 1 returned ' + motor1);
  return 'console.log(\'MotorA= ' + motor1 + ', motor2= ' + motor2 + '\');\n';
}

Then pass the following xml through textToDom and domToWorkspace:
<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="motor_select" id="f47913cc-4559-4bb4-a6fe-e0e0a3108ca6" x="-150" y="-211">    <field name="MOTOR_A">true</field>    <field name="MOTOR_B">true</field>  </block></xml>

After calling domToWorkspace the workspace will have a top level block that looks like this:
<block type="motor_select" id="f47913cc-4559-4bb4-a6fe-e0e0a3108ca6" x="-150" y="-211"><field name="MOTOR_A">FALSE</field><field name="MOTOR_B">FALSE</field></block>

**Comment by rachel-fenichel** [comment]
I think you would succeed if you had TRUE instead of true.  
fieldCheckbox setValue looks like it's case sensitive: https://github.com/google/blockly/blob/master/core/field_checkbox.js#L87
