### ISSUE TITLE
Use <element>.style instead of setAttribute

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#6547]
**Is your feature request related to a problem? Please describe.**

Blockly uses `setAttribute` on SVG and HTML elements because setting `style` on SVG elements is not supported in Internet Explorer. Now that we've stopped supporting IE, we can use `style` and take advantage of browser performance optimizations around CSS.

**Comment by gonfunko** [comment]
This isn't actually this straightforward - per https://stackoverflow.com/questions/47088409/svg-attributes-beaten-by-cssstyle-in-priority (and experimentally confirmed), SVG attributes have a lower priority than inline styles or stylesheets, so changing to setting style in some cases changes what does or doesn't get overridden.

**Comment by BeksOmega** [comment]
Going to close this as wont-fix due to the priority problems linked above.
