### ISSUE TITLE
When displayed on a mac, the position of the inverted triangle in the pull-down is shifted upward

### ISSUE THREAD

**Issue by Taikono-Himazin** [google/blockly#6552]
**Describe the bugs**

**To Reproduce**

1. View Blockly on Mac.
2. Show block with pull down
3. The inverted triangle is shifted up.

On Mac
<img width="184" alt="スクリーンショット 2022-10-17 9 31 21" src="https://user-images.githubusercontent.com/25480502/196067574-f6fdd0f3-cdf1-41d9-a7e0-de4f5a557222.png">

On windows it looks like this:
![image](https://user-images.githubusercontent.com/25480502/196067657-c71ad20a-9a3e-4e22-9327-345889de173a.png)

You can see that the inverted triangle is slightly higher on the Mac.
Is this the spec?
I feel a little uncomfortable.

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1
 - Browser Safari 15.4 17613.1.17.1.13
 - Blockly v9.0.0

**Comment by NeilFraser** [comment]
Sadly I'm unable to recreate:
* MacOS 12.6.1
* Safari 16.1
* https://blockly-demo.appspot.com/static/demos/code/index.html?lang=zh-hant

<img width="361" alt="Screen Shot 2022-10-31 at 10 17 19" src="https://user-images.githubusercontent.com/250480/198973960-160edb91-a9f6-4383-baf5-dcc84718058b.png">

Can you try the above URL and tell us what you see?

**Comment by NeilFraser** [comment]
Also, could you try another browser (Chrome or Firefox), just so we can narrow down if it's a Safari issue or a Mac issue.

**Comment by Taikono-Himazin** [comment]
It was displayed without problems when it was the above site.
So I think this is a problem with my site, not Blockly.
I'm sorry.
