### ISSUE TITLE
Consider moving to ES6 classes and modules

### ISSUE THREAD

**Issue by wizzard0** [google/blockly#658]
Compared with modern codebases like React, Blockly is very fragile. Moving to standards-compliant classes and modules will make it a lot easier to extend and generally tinker with the project.

**Comment by NeilFraser** [comment]
Will do.  As soon as IE supports ES6 classes and modules.

**Comment by wizzard0** [comment]
From our experience, targeting IE8 or maybe even IE6 (we dropped it just 2 years ago) via TypeScript translated to ES3 + polyfills works surprisingly good
