### ISSUE TITLE
Using Blockly.Msg.TEXTS_HUE (or any other hue) don't change the colors of the respective blocks

### ISSUE THREAD

**Issue by randrei12** [google/blockly#6589]
**Describe the bug**
When I use Blockly.Msg.TEXTS_HUE, it doesn't change default blocks color.

![image](https://user-images.githubusercontent.com/79661902/198871001-0dbfb2c6-983c-4100-8e73-12444b036355.png)

I use blockly 9.0.1 (npm version)

**Comment by NeilFraser** [comment]
Addressed on the forum.
https://groups.google.com/g/blockly/c/GEt5e1Tcayo
