### ISSUE TITLE
Blockly Factory warns about anything with 'var' in the name

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#659]
If you create a block named 'get_var' that just contains text/edit text fields and try to drop it into a toolbox a popup appears warning that you need a variables toolbox. It should only pop up that message if the block contains a field_variable.

**Comment by RoboErikG** [comment]
It also rechecks and pops a warning for each block every time you switch to that toolbox.

**Comment by picklesrus** [comment]
@RoboErikG: I'm not sure how to make this happen.
I tried the following and I can add that to the toolbox (categories or not) just fine.  Am I missing a field?
{
  "type": "get_var",
  "message0": "%1 var stuff testing",
  "args0": [
    {
      "type": "field_input",
      "name": "NAME",
      "text": "default"
    }
  ],
  "colour": 120,
  "tooltip": "",
  "helpUrl": "http://www.example.com/"
}

**Comment by picklesrus** [comment]
It is the field name that can't be "VAR" not the block name. Sample json dfn:
{
  "type": "get_var",
  "message0": "%1",
  "args0": [
    {
      "type": "field_number",
      "name": "VAR",
      "value": 0
    }
  ],
  "colour": 210,
  "tooltip": "",
  "helpUrl": "http://www.example.com/"
}

**Comment by picklesrus** [comment]
Fixed in develop.
