### ISSUE TITLE
Blockly.utils.genUid() can not load in block factory

### ISSUE THREAD

**Issue by zhaoyilun** [google/blockly#6626]
**Describe the bug**

When I open the block factory with 'blockly-blockly-v9.0.1\demos\blockfactory\index.html', the page doesn't load completely and it says "Blockly.utils.genUid() is not a function." from the console.

**The way to solve**
blockly-blockly-v9.0.1\demos\blockfactory\workspacefactory\wfactory_model.js(line 480): 
change `this.id = Blockly.utils.idGenerator.genUid();` to `this.id = Blockly.utils.idGenerator.genUid();`
blockly-blockly-v9.0.1\demos\blockfactory\workspacefactory\wfactory_generator.js(line 28): 
change `  var hiddenBlocksId = Blockly.utils.genUid();` to `  var hiddenBlocksId = Blockly.utils.idGenerator.genUid();`

**Comment by BeksOmega** [comment]
Hello, it looks like these issues have already been fixed in version 9.0.1 =) So I'm going to go ahead and close this! If you run into further issues, please feel free to reopen =)
