### ISSUE TITLE
Warning icon on block causes misaligned input field

### ISSUE THREAD

**Issue by kelanAlbertson** [google/blockly#6631]
**Describe the bug**

When the warning icon on a custom block of mine appears or disappears, it changes the width of the block and causes the focused text input field to stay in place and no longer align with the block while a duplicate field does move with the rest of the block. The warning is caused by that input field being empty and so the warning status is always changed while the user is typing or deleting within that input field.

**To Reproduce**

1. Use a custom block with a dummy input containing a text label and then a text input field and an extension that creates a warning and disables the block when the text input field is empty. Here is my full block definition:
```
    "type": "literal_match",
    "message0": "literal: %1 %2",
    "args0": [
      {
        "type": "field_input",
        "name": "LITERAL",
        "text": "",
      },
      {
        "type": "input_value",
        "name": "REPEAT",
        "check": "repeat"
      }
    ],
    "inputsInline": false,
    "previousStatement": null,
    "nextStatement": null,
    "colour": 230,
    "tooltip": "",
    "helpUrl": "",
    "extensions": ["disable_empty_input"]
```
The extension sets a warning and disables the block when the input is empty. Here is my extension:
```
Blockly.Extensions.register("disable_empty_input", function() {
  this.setOnChange(function(changeEvent) {
    if (changeEvent.type == Blockly.Events.BLOCK_MOVE || changeEvent.type == Blockly.Events.BLOCK_CHANGE) {
      if (this.getFieldValue("LITERAL") != "") {
        this.setWarningText(null);
      } else {
        this.setWarningText("Must provide input");
        this.setEnabled(false);
      }
    }
  });
});
```
2. Place this block into a workspace and immediately the block should have a warning icon and be disabled
3. Click the text input field and enter any text. As soon as you enter any character, the warning goes away and so the block shortens, but the active input field that you are typing in stays put while a copy of it moves to its appropriate location with the rest of the block (see screenshots)
4. Remove focus from the text input field by clicking elsewhere or pressing enter and the field you were typing in should disappear leaving only the field in the correct position
5. Click the text input field again and delete the text in it. This will cause the warning to return and the block lengthens to fit the warning icon but now has two versions of the input field
6. Remove focus from the input again and the duplicate will disappear and everything will go to normal again

**Expected behavior**

I expected the focused text input field to move to the new appropriate location in the block while the block changes in width and not to see a duplicate of the text input field

**Screenshots**

This is how the block looks immediately after adding it to my workspace. Everything is as I expect here.
![image](https://user-images.githubusercontent.com/89397886/202288100-e9935ef3-8ebb-4bce-a3b0-3de2879ce9ba.png)

This is how the block looks once any text is typed into the input field. The warning goes away and so the block shrinks in width but there are unexpectedly two copies of the input field showing now.
![image](https://user-images.githubusercontent.com/89397886/202288368-900b189b-c338-4566-90d1-faa25600f26c.png)

This is how the block looks as soon as focus is removed from the input field. Everything is as I expect here.
![image](https://user-images.githubusercontent.com/89397886/202288529-2b651e0d-f4f0-47e3-aee4-11b5fe5dc7aa.png)

This is how the block looks once the text that was in the input field is deleted. The warning returns and the block lengthens to accommodate the icon and again there are two copies of the input field showing now.
![image](https://user-images.githubusercontent.com/89397886/202288620-d983437e-5df1-4338-855f-b35021b0b4bb.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome (version 105.0.5195.125)
 - Version: Blockly version 9.1.0

**Smartphone (please complete the following information):**
N/A

**Stack Traces**
N/A

**Additional context**

Using inspect in my browser it appears that the field that correctly follows the block is a blocklyFieldRect while the duplicate that stays in place is a blocklyHtmlInput

I'm sorry if this could actually be an issue in my implementation but it seems odd to me.
Thank you!

**Comment by BeksOmega** [comment]
Hello! Instead of using a warning icon, have you tried using a [field validator callback](https://developers.google.com/blockly/guides/create-custom-blocks/fields/validators)? This will turn the [text input](https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/text-input) red if the user types in something in valid, which I think will cover your use case, and avoid the visual bug =)

**Comment by kelanAlbertson** [comment]
Hi, 

Thanks for the response! I had not tried a field validator but when I just tried it now I was not able to find a way to have it do quite what I am looking for. Since my text input field is empty by default I would like it to be red, disabled, or flagged in some way initially until the user provides input. Once there is input, I have been able to get it to successfully turn the field red when that input is deleted and then resist changes to the input if the new input is invalid (empty). Is there a way to have the field validator check immediately on the block's creation? Or is there another approach that you would recommend looking into?

Thanks again!
Kelan

**Comment by BeksOmega** [comment]
Hello! Ahh I see how this doesn't work for your use case. The field validator for text input fields only affects the HTML input where the user is entering text (it doesn't affect the block itself). Which fixes your weird rending bug, but doesn't actually accomplish the warning you want it to :P

I think you would probably be better off asking for advice on the [developer forum](https://groups.google.com/g/blockly). Other devs using Blockly may have run into similar problems, or other people on the core team may have different suggestions!

**Comment by kelanAlbertson** [comment]
Okay, I will give the developer forum a try. Thank you so much for taking the time to read these and respond!
