### ISSUE TITLE
BlocklyFactory: Throws js error in firefox when loading.

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#664]
It throws the following error and then doesn't work at all:

TypeError: this.getParentSvg(...).getScreenCTM(...) is null
Blockly.WorkspaceSvg.prototype.updateInverseScreenCTM()
blockly_compressed.js:1043
Blockly.WorkspaceSvg.prototype.updateScreenCalculations_()
blockly_compressed.js:1050
Blockly.WorkspaceSvg.prototype.resize()
blockly_compressed.js:1051
Blockly.svgResize()
blockly_compressed.js:1449
Blockly.createMainWorkspace_()
blockly_compressed.js:1430
Blockly.inject()
blockly_compressed.js:1424
WorkspaceFactoryController()
wfactory_controller.js:53
AppController()
app_controller.js:51
init()

**Comment by NeilFraser** [comment]
Fixed.
