### ISSUE TITLE
`loopTypes` not available via `Blockly.libraryBlocks.loops.loopTypes` in Blockly v9.1

### ISSUE THREAD

**Issue by Taikono-Himazin** [google/blockly#6648]
**Describe the bug**

Blockly uploaded to npm is broken.

**To Reproduce**
1. Download Blockly v9.1.0 from npm.
2. Run `Blockly.libraryBlocks.loops.loopTypes.add('custom_loop');`
3. An error occurs.

**Expected behavior**

no error occurs.

```
Replace with error stack trace.
```

**Additional context**

As of v8, the problem is gone [here](https://github.com/google/blockly/issues/5819),
But in v9.1.0 of npm this problem recurs.
`Blockly.libraryBlocks.loops.loopTypes.add('custom_loop');`
Just in case, if you run console.log (Blockly.VERSION) with npm, it will output 9.1.0, so it is certain that the source code is 9.1. It doesn't seem to mean that all the source code is reverted to the previous version.

Strangely, this problem does not occur when downloading from the GitHub release page and running it in Google Chrome.

**Comment by Taikono-Himazin** [comment]
Hi @cpcallen .
I run blockly with node.js so no html.
(I use it to convert the xml that saved the workspace to python.)
Below is the minimal code that reproduces the problem.

package.json
```
{
    "name": "sample",
    "version": "0.0.0",
    "private": true,
    "scripts": {
        "audit": "npm audit fix",
        "update": "npm update",
        "start": "node index.js"
    },
    "dependencies": {
        "blockly": "^9.0.0",
    }
}
```

index.js
```
Blockly = require('blockly');
Blockly.blocks = require('blockly/blocks');

var mainJson = {
    "type": "main",
    "message0": "main",
};
Blockly.Blocks['main'] = {
    init: function () {
        this.jsonInit(mainJson);
    }
};
Blockly.libraryBlocks.loops.loopTypes.add('main');
```

command
1. `npm install`
2. `node index.js`

the error that occurs
```
Blockly.libraryBlocks.loops.loopTypes.add('main');
                      ^

TypeError: Cannot read properties of undefined (reading 'loops')
    at Object.<anonymous> (\index.js:13:23)       
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)     
    at node:internal/main/run_main_module:17:47
```

**Comment by cpcallen** [comment]
> ```
> Blockly = require('blockly');
> Blockly.blocks = require('blockly/blocks');
> ```

Ahh, here is your problem.  This should be:

```
const Blockly = require('blockly');
const libraryBlocks = require('blockly/blocks');
```
> 
> var mainJson = {
>     "type": "main",
>     "message0": "main",
> };
> Blockly.Blocks['main'] = {
>     init: function () {
>         this.jsonInit(mainJson);
>     }
> };
> Blockly.libraryBlocks.loops.loopTypes.add('main');

**Comment by cpcallen** [comment]
(Previous comment was inadvertently saved while still being drafted.  If reading this by email, please check the GitHub issue for the final, corrected version.)

**Comment by Taikono-Himazin** [comment]
However, if I try to do this in the same way as browser code, I don't think compatibility can be maintained, is that correct?

If you write the following in your browser, it looks like Blockly.blocks contains the contents of require('blockly/blocks').
`<script src="https://unpkg.com/blockly/blockly.min.js"></script>`

What should I do to maintain compatibility?
