### ISSUE TITLE
Cannot find viable example of use of "blockly_compressed.js" with current version

### ISSUE THREAD

**Issue by JDang-At-Festo** [google/blockly#6651]
**Where**
Current version released v-9.1.0 has no files "blockly_compressed.js", "python_compressed.js" as in previous version. Under main in the demos/blockfactory/index.html on line 7 it seems to indicate that the file was moved to a directory named "dist". I however cannot find it two levels up as it specifies. I need these .js files for a webserver, or I need to understand which js files allow me to generate custom blocks generate python code from browser. 

For reference:
(https://github.com/google/blockly/blob/develop/demos/blockfactory/index.html)

**Comment by cpcallen** [comment]
Hi JDang-At-Festo,

> Current version released v-9.1.0 has no files "blockly_compressed.js", "python_compressed.js" as in previous versionP

Yes: they were intentionally removed in PR #6475.  If you need these files you should obtain them via [the `blockly` npm package](https://www.npmjs.com/package/blockly), [via unpkg](https://developers.google.com/blockly/guides/get-started/web#unpkg), or as a `.tgz` (gzipped tar file) file from [the Releases page](https://github.com/google/blockly/releases) of this repository.

> Under main in the demos/blockfactory/index.html on line 7 it seems to indicate that the file was moved to a directory named "dist". I however cannot find it two levels up as it specifies.

These demos are intended to be used via [our GitHub Pages](https://google.github.io/blockly/demos/) and [AppEngine demo site](https://blockly-demo.appspot.com/static/demos/index.html).  If you wish to use these demos locally, then `npm run package` will build and package the requisite files.

For contributors to Blockly: to test changes made to blockly manually, it suffices to run `npm start`, which will:
* do the requisite preliminary build steps,
* run `tsc` in `--watch` mode,
* fire up `http-server`, and
* open a web browser window pointing at `tests/playground.html`
