### ISSUE TITLE
Lua generators use None instead of nil

### ISSUE THREAD

**Issue by NathanSnail** [google/blockly#6720]
This causes
![image](https://user-images.githubusercontent.com/47441022/209071905-c7147d33-650e-4231-a26d-e761eea97373.png)
this generates `list = {None, None, None} print(#list)` printing 0

Expected Behavior:
The generator should produce `list = {nil, nil, nil} print(#list)` printing 3

## To Fix

1) In the [list block-code generators](https://github.com/google/blockly/blob/develop/generators/lua/lists.ts). Change references to `'None'` to `'nil'`.
2) Update the [block-code generator tests](https://github.com/google/blockly/blob/develop/tests/generators/golden/generated.lua) if they are failing.

**Comment by Nathdsgfiugaoiysfnhuah** [comment]
Oops, the second example also outputs 0, however, nil should still be used though as None can be assigned to while nil can't be. nil is also a special type in Lua for no data

**Comment by BeksOmega** [comment]
The following code in the playground:
![image](https://github.com/google/blockly/assets/25440652/74f0b475-3507-49ee-b1c0-8643c817ede8)
Generates the following Lua:
```
None = 123
list = {None, None, None}
print(list[1])
```
Which results in:
```
123
```
---

Ideally it should be:
```
None = 123
list = {nil, nil, nil}
print(list[1])
```
Resulting in:
```
nil
```

**Comment by neerajkumarc** [comment]
@BeksOmega Can I be assigned?

**Comment by BeksOmega** [comment]
@neerajkumarc Go for it =)
