### ISSUE TITLE
Block Factory: Include the save URL in comments/JSON attribute

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#674]
A block's save URL is not currently in a location that is easy to reference (especially in teams).  We could easily fix it by including the URL in any exported file's comment.

This also applies to the Block Factory inside Blockly Factory.

**Comment by Spoorthy1423** [comment]
@AnmAtAnm  i would like to work on this issue, please assign me

**Comment by BeksOmega** [comment]
I have no idea what the actual intention of this issue was, so I'm going to close.
