### ISSUE TITLE
Add annotated screenshots as documentation of anatomy of Blockly

### ISSUE THREAD

**Issue by maribethb** [google/blockly#6792]
**Where**

Somewhere in dev site

**What**

- [x] Text
- [x] Image or Gif
- [ ] Other

**Old content**

None, though note that [this page](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks) explains and has all the pictures of pieces of blocks.

**Suggested content**

Annotated screenshots showing the names of pieces of Blockly, with links to the documentation pages for those topics. The idea being that often when you are new to the library, you know you want to change "this thing" you can point to, but you don't have a word for that thing. Ideas for what the images could show:

Basic pieces of Blockly:
- Workspace
- Toolbox
- Flyout
- Trashcan
- Zoom Controls
- Blocks
- Context menu

Toolboxes:
 - Category
 - Collapsible Category
 - Dynamic Category
 - Separator 
 - "Simple" / flyout-only toolbox

Blocks - this is potentially replicated on the blocks page but having it all together in one image may still be useful:
- Inputs
    - Statement
    - Value
    - Dummy
- Fields
    - one example with label / text only
    - one example with user input like text or number  
- Outputs
- Next/previous connections

**Additional context**

**Comment by surajguduru** [comment]
Hey @maribethb I would to work on this issue. Can you assign it to me ?

**Comment by BeksOmega** [comment]
Sorry @surajguduru our docs are actually internal to Google and not able to be contributed to :/

This is also fixed, I just forgot to close. See: https://developers.google.com/blockly/guides/get-started/workspace-anatomy
