### ISSUE TITLE
Unexpected child block disconection when changing a field option

### ISSUE THREAD

**Issue by gpfernandezflorio** [google/blockly#6801]
### Check for Duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When changing the field WHERE of the block text_charAt the child block in the input AT gets disconnected.
![image](https://user-images.githubusercontent.com/5846063/215172976-b8295e4b-1e27-4a66-a4ad-db35f3d175d2.png)
![image](https://user-images.githubusercontent.com/5846063/215173011-827168db-b50b-4c1e-802d-b1ffb0d8315d.png)
This only happends with text_charAt but it doesn't happen with text_getSubstring, lists_getIndex and lists_getSublist.

### Reproduction Steps

1. Create a text_charAt block
2. Fill it's input AT
3. Change the field WHERE to "letter # from end"

### Browsers

Chrome desktop

**Comment by gpfernandezflorio** [comment]
I saw that and suspected the same but the fact that it doesn't happen with the other blocks (text_getSubstring, lists_getIndex and lists_getSublist) makes me doubt.

Changing the function so the input is only removed when it is not necessary does indeed fix the problem. The question is why the other blocks don't need that. I couldn't find what else is different and also, I don't understand how the child block is maintained after a change (in the code I only see the input being removed and then added again but nothing about the child block being reconnected to the new input).

**Comment by gonfunko** [comment]
This no longer repros and may have been fixed by #8575.
