### ISSUE TITLE
Serialize movable, editable, and deletable properties in JSON.

### ISSUE THREAD

**Issue by maribethb** [google/blockly#6807]
**Backstory**

The XML serializer serializes the movable, editable, and deletable properties on each block.

When the JSON serializer was originally created, we opted not to serialize these attributes for several reasons:
- It was thought that since the user cannot edit these properties, they don't need to be serialized/saved. Since the developer controls setting these properties, they could manage that data themselves.
- Relatedly, you don't need to serialize these attributes if they apply to all blocks of the same type and they can be set in the block definition.
- #2285 exists and we didn't want to introduce this bug into a new system

For developers who rely on these attributes, we added the [serialize-disabled-interactions plugin](https://google.github.io/blockly-samples/plugins/serialize-disabled-interactions/test/) as an alternative.

For more context, see [this forum post](https://groups.google.com/g/blockly/c/eP9PXVfCaHs/m/S4rPmwnTAQAJ).

**Problems**

After completing the JSON serializer, we updated many aspects of Blockly to use it rather than XML. One of these is the event system, leading to #6793 which is pretty game-breaking to anyone using non-movable or non-editable but still deletable blocks (which, admittedly, may be a minority of users of these attributes). This bug occurs even for users who exclusively use XML for their own serialization. There are also other problems:

- It's actually pretty common for people to not be able to use the block definition to set these properties. Take the case of seeding the workspace with some starter blocks that aren't deletable, but the same type of block is available in the toolbox for there to be additional usages of that would be deletable. This use case would either need to be covered by the plugin or by the developer implementing their own system for loading in starter blocks to a workspace.
    - This adds needless friction - we already have a system for loading blocks into a workspace that developers should be able to use and not have to implement their own system.
- Adding friction to upgrading from XML to JSON is not ideal.
- Even using the plugin serializer does not avoid certain problems with Blockly's internal use of JSON serialization such as #6793 so there is no adequate workaround for the problems caused

**Solution**

- Have the JSON serializer also serialize the movable, editable, and deletable properties.
- Deprecate the plugin and provide instructions for moving off of it. I think this would mean we can't delete the plugin; developers would need to load data serialized with the plugin at least once after this issue is fixed, then save the data without using the plugin. So developers using it would need to have it available to update previously saved data. In addition or instead, we could provide an upgrade script that updated the serialized data, so that developers could make bulk updates.

**Justification**

After seeing the tradeoffs play out in real use, we feel the problems caused by not serializing these attributes outweighs the gains we got from that decision. The big remaining problem is #2285. This bug is less important than #6793:
- It should be more rare (a read-only workspace shouldn't need to be re-serialized - if it's read only then presumably nothing has changed)
- It has a workaround - use a headless workspace or a hidden non-read-only workspace to make programmatic changes
- It can more easily be fixed (comment in that bug)

**Comment by BeksOmega** [comment]
For dealing with the plugin, what I want to do is:
1) Release one new major version of the plugin that deserializes the properties, but doesn't serialize them.
    This way developers can upgrade to use Blockly to serialize these properties, and leave the plugin installed as long as they want, and overtime it will slowly clean their saves.
2) Deprecate the plugin package (the whole thing, not a specific version) so that new people can't find it.
3) Delete the plugin code from this repository.

Does that sound good to you @maribethb ?

**Comment by maribethb** [comment]
That sounds good to me.

**Comment by cpcallen** [comment]
> 3\. Delete the plugin code from this repository.

Might it be wise to delay actually deleting the sources for the plugin for some time, in case we realise there are bugs that need fixing?  I realise we can revert the delete, but I'd keep the source around until there is evidence that the plugin is no longer in use.

**Comment by BeksOmega** [comment]
> Might it be wise to delay actually deleting the sources for the plugin for some time, in case we realise there are bugs that need fixing? I realise we can revert the delete, but I'd keep the source around until there is evidence that the plugin is no longer in use.

So like delete at EOQ2? or EOY?

**Comment by cpcallen** [comment]
> So like delete at EOQ2? or EOY?

I was thinking specifically to look at the weekly downloads graph on [the npmjs.com page for the plugin](https://www.npmjs.com/package/@blockly/plugin-serialize-disabled-interactions).  It's currently getting ~100/wk and wait for this to have dropped substantially (say, <10/wk)—though in case it does not drop quickly I think EOY is plenty.
