### ISSUE TITLE
Blocky for flutter/dart

### ISSUE THREAD

**Issue by Manishmg3994** [google/blockly#6808]
**As everyone know *GOOGLE* DEVELOPED DART BUT TILL NOW THERE IS NO CODE BASE FOR BLOCKLY WITH DART .**

Please create a no code base design library with dart to support dart drag and drop no code design patterns
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rachel-fenichel** [comment]
Blockly is a JavaScript library. We have generators for Dart. We do not intend to rewrite Blockly in Dart.
