### ISSUE TITLE
add a larger playing area in blockly developer tools

### ISSUE THREAD

**Issue by rylid-umil** [google/blockly#6819]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Problem

i wish there was a larger area to test out the blocks you made in the block factory, i just like having fun with the blocks.

### Request

a larger work space preview area, 

### Alternatives considered

a custom blocks playground or custom-made block compatibility in blockly playground.

**Comment by maribethb** [comment]
Hi, thank you for the feature request. Unfortunately this is not something we are likely to work on - dev-tools needs a more general update and we aren't going to invest time in the current iteration. You can always export your blocks from dev-tools and import them into your own application to use them on a bigger workspace.
