### ISSUE TITLE
Remove backtick from the character set used in block ids

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#682]
Backtick (`) is used to quote ES6 template strings, which are also useful [as mutliline strings](https://jack.ofspades.com/multiline-strings-in-es6-javascript/).  Back ticks in ids can break these strings.

**Comment by NeilFraser** [comment]
That's not a problem with IDs, that's a problem with a lack of escaping at some higher level.  Backticks can occur in many other places, such as field values.

Also, if we start trimming characters from the block IDs every time one conflicts with some system that someone is using, we'll soon run out of characters.  See #625 for the most recent example.  In retrospect I made a bad call on #251 and ought to reverse that decision.

**Comment by AnmAtAnm** [comment]
I agree it is an escaping issue, in the current form.  However, I think intelligent selection of characters can easily solve many potential issues. We aren't going to "run out of characters"; as long as we don't use the alphanumerics, we'll resolve many of these conflicting issues (hence why so many ids prefer longer length to more characters).

In my case, it had nothing to do with block highlighting. I just wanted to store an XML string to load into the workspace.  Using a multiline string without escaping simplified the update process.

For what it is worth, I think #625 is a valid issue.

This is a trivial fix.  Expect a pull request.
