### ISSUE TITLE
Regression: Tooltips no longer show in toolbox

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#683]
Both simple and category toolboxen used to show tooltips:
https://blockly-demo.appspot.com/static/demos/fixed/index.html
Now they don't.  This makes it harder to explore what blocks do.

**Comment by picklesrus** [comment]
One more thing to test when fixing this since I think it is related: hovering over blocks in flyout should show the highlighted yellow line.

**Comment by rachel-fenichel** [comment]
Fixed both by #684
