### ISSUE TITLE
Support for copy-pasting procedures between workspaces

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6846]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

When we copy a block we serialize it and its extra state.

In the case of the new `@blockly/block-sharable-procedures`  (specifically the procedure definition block) the extra state includes the ID of the procedure model the block is referencing.

Normally when we deserialize a procedure definition block, and it has an ID in its extra state, we want the procedure definition block to grab a reference to the procedure model with that ID. However, if there is /already/ another procedure definition block associated with that procedure model, then we want the pasted/deserialized block to create a new procedure model and reference it.

Currently we do this by searching the workspace to see if any blocks are referencing the model we want to reference. However, this will fail if we ever add the ability to copy-and-paste blocks between workspaces. We won't be able to check if there is a block /in the other/ workspace referencing the model we want to reference.

### Request

We could fix this by  changing how we handle copy-and-pasting. E.g. add the ability to serialize a different set of extra state when we're copy and pasting vs when we're serializing.

### Alternatives considered

We could also fix this by adding functionality to the procedure models to allow them to be "claimed". This would probably involve changes to the procedure model interface (which is a breaking change), and an additional event in the `@blockly/block-sharable-procedures` plugin to allow the "claimed-ness" to be propogated between workspaces.

### Additional context

We do have a plugin that kind of allows copying and pasting between workspaces: https://www.npmjs.com/package/@blockly/plugin-cross-tab-copy-paste

However, this is specifically for copying between different projects on the same website in different tabs. E.g. there is no way to filter or check the copied data to see if all of the copied blocks are valid in another workspace, making it an ineffective plugin for copying blocks between multiple different workspaces on the same page.

**Comment by BeksOmega** [comment]
Talked about this with Maribeth offline!

We /could/ fix this specifically for the plugin, either by:
  A) Implementing by "Alternatives considered" option, or
  B) Providing a custom copy-paste context menu option that special-cases the procedure blocks.

Or we could fix this more generally by modifying how copying and pasting works in core.

We already have a [`doFullSerialization`](https://github.com/google/blockly/blob/f6d2f4803a463f89ff4b0d08af325d07032a8fcb/core/serialization/blocks.ts#L73) parameter which we pass to variable fields to allow them to handle pasting (because variable fields also reference backing data models). So we could also pass this blocks to solve the same problem. This is an easy fix.

However, there is evidence that copy pasting needs to be rethought in more detail (e.g. #3833 ) so we're not sure that we want to go with the easy fix - since we may want to do something even more general.


Also note: I was mistaken about the cross tab copy paste plugin. While it may not have the filtering mentioned in my "Additional context", it is intended to support copying and pasting between workspaces on the same page.

**Comment by maribethb** [comment]
After additional discussion, we are at
- if we can prioritize fixing copy/paste in core next quarter, we can do that
- if we can't, we should do one of the workarounds to fix for just this plugin

We haven't yet gotten to next quarter's roadmap so this is still undecided.
