### ISSUE TITLE
Paste block in viewport / near cursor

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6848]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When you paste a block, you expect the block to appear in the part of the workspace you are looking at. Usually either:
  * In the middle of the view
  * Near where your cursor is

Currently in Blockly, this is ignored, and blocks are always pasted near the original block that was copied.

### Reproduction steps

1. Copy a block to the clipboard using ctrl + c.
2. Scroll the workspace so that the original block is not in view.
3. Paste the bloc using ctrl + v.
4. Observe how the new pasted block is not in view, and was instead pasted near the original block.

### Additional Info

Pasting in the viewport may cause cascading block bumps for the pasted blocks, which would also be a bad user experience. I'm nopt sure if this occures with the current system or not.

Note: block bumping is when we move blocks away from other blocks connections so they don't accidentally appear to be connected.

## To Fix

1. Follow the reproduction steps to reproduce the bug.
2. Add a `getRelativeToSurfaceXY(): Coordinate` method to the [IMovable interface](https://github.com/google/blockly/blob/develop/core/interfaces/i_movable.ts).
3. Modify the [copy](https://github.com/google/blockly/blob/7e9d1eb3ba780f523863ba94b4af5cce36292295/core/shortcut_items.ts#L121) and [cut](https://github.com/google/blockly/blob/7e9d1eb3ba780f523863ba94b4af5cce36292295/core/shortcut_items.ts#L161) callbacks to store the result of `getRelativeToSurfaceXY` in a `copyCoords` variable.
4. Modify the [paste](https://github.com/google/blockly/blob/7e9d1eb3ba780f523863ba94b4af5cce36292295/core/shortcut_items.ts#L193) callback to:
    A. Run `copyWorkspace.getMetricsManager().getViewMetrics(true)` to get the coordinates of the viewport of the workspace.
    B. If the `copyCoords` are within the viewport, pass `copyCoords` to `clipboard.paste`.
    C. Otherwise, paste at a new `Coordinate` in the middle of the viewport. You can use the view metrics to calculate this.
1. Rerun the reproduction steps. This time if the original block is not in view, the block should be pasted  in the middle of the viewport.⚠️

**Comment by koenvanwijk** [comment]
As a user I copy a block, scroll to the place where I want to block to appear and paste. So scrolling to the default (duplicate) position will break my intent. I think pasting in the middle of my current view is ok as long as it will not connect to an existing stack at that place.

**Comment by maribethb** [comment]
This seems reasonable to add to core.

**Comment by bsampada7** [comment]
I would like to work on this issue

**Comment by patelb268** [comment]
I would like to work on this issue

**Comment by BeksOmega** [comment]
@bsampada7 Go for it!

@patelb268 Happy to assign you to a different issue since @bsampada7 got here first =) Just comment on a different one and I'll get you assigned!

**Comment by Daphne-wu** [comment]
I would like to work on this issue

**Comment by BeksOmega** [comment]
Hiya @Daphne-wu Someone has already been assigned! If you coment on a different issue I'll get you assigned =)

**Comment by BeksOmega** [comment]
The code now relies on [getSelected in the paste callback](https://github.com/orgs/google/projects/95/views/1). Which means if you don't have a block selected when you paste, you get an error and pasting fails. This should be changed to not rely on `getSelected`.

**Comment by BeksOmega** [comment]
Marking this as triage re: https://github.com/google/blockly/pull/7521#issuecomment-2026946798

Looks like we might have had some conflicting changes and lost the fix from OSD.

**Comment by bsampada7** [comment]
Hi @BeksOmega , do I need to work on a fix for this? I'd be happy to work on it.

**Comment by BeksOmega** [comment]
Oh nope! You already wrote up a good fix, I think we just need to dig it out of the git history somewhere =) Thank you for your interest though! If you want to work on something else we have a list of other [good first issues](https://github.com/google/blockly/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

**Comment by ggramlich** [comment]
@BeksOmega @maribethb Could you give an update about this?
It looks like there is an implementation which did not make it into the main branch and nobody is assigned to this issue any more.
It would be great, if the implementation could be integrated.

**Comment by BeksOmega** [comment]
@maribethb Assigning this to you since  you mentioned wanting it yesterday.
