### ISSUE TITLE
Paste blocks  between workspaces on the same page

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6849]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Sometimes you want your application to have multiple workspaces that have different purposes. And you may want your users to be able to copy paste blocks between them. This is currently kind of possible with the cross-tab-copy-paste plugin. However, this plugin doesn't allow you to restrict which blocks are shared and which ones aren't. So it's doesn't work if you want some blocks to only be available in some workspaces.

### Request

Add a way to paste blocks between workspaces, and filter which blocks are allowed to be pasted.

### Alternatives considered

N/A

### Additional context

https://www.npmjs.com/package/@blockly/plugin-cross-tab-copy-paste

**Comment by maribethb** [comment]
I don't think we need to add this to core. We already have APIs that allow developers to add their own copy/paste functions, and they could use the cross-tab-copy-paste plugin as an example implementation, and create their own copy function that only works on certain block types.
