### ISSUE TITLE
Dragged blocks appear behind blocks in the workspace

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6852]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When you drag a block from the flyout, or drag blocks on the workspace, they appear behind other blocks, when they should be on top.

### Reproduction steps

1. Drag a block from the flyout
2. Drag another block from the flyout
3. Observe how the second block is rendered behind the first block.

### Stack trace

```shell
N/A
```

### Screenshots

[Screen recording 2023-02-16 10.36.51 AM.webm](https://user-images.githubusercontent.com/25440652/219457133-b8ade7b3-2b9a-47ab-86cb-28cfe450c1e7.webm)

### Additional Info

Does not reproduce on master. I'm assuming this is related to #6758

**Comment by BeksOmega** [comment]
This was "fixed" when we reverted #6758, but I'm leaving it open because we will need to fix it if we reimplement that change.

Readding the triage label in case peeps disagree.

**Comment by rachel-fenichel** [comment]
Closing because we are tracking it in the original issue: https://github.com/google/blockly/issues/6160
