### ISSUE TITLE
Documentation code bug, msg/js/en.js

### ISSUE THREAD

**Issue by alexNecroJack** [google/blockly#6853]
### Location

https://developers.google.com/blockly/guides/get-started/web

### Type

- [X] Text
- [ ] Image or Gif
- [ ] Other

### Suggested content

The demo code at https://developers.google.com/blockly/guides/get-started/web
shows this:

```
...
<script src="javascript_compressed.js"></script>
<script src="msg/js/en.js"></script>
```
The problem lies here "msg/ **→js/←** en.js".
but when downloaded the code from Github - V.9.2.1 (not the source code, but the release, the .tar.gz file)
and extracted it, the path was actually ".../**msg/en.js**", and thus Blockly didn't play.

**Comment by cpcallen** [comment]
This appears to have been fixed.
