### ISSUE TITLE
Easy not to see, same looking filename

### ISSUE THREAD

**Issue by alexNecroJack** [google/blockly#6854]
### Location

https://developers.google.com/blockly/guides/get-started/web

### Type

- [X] Text
- [ ] Image or Gif
- [ ] Other

### Suggested content

At this page: https://developers.google.com/blockly/guides/get-started/web

The documentation shows on one code of block:
```
Once you've downloaded Blockly, you can add the following to your application code to load it:


<script src="blockly_compressed.js"></script>
```

and then 
```
You will probably also want to load Blockly's built-in blocks, at least one language generator, and at least one language file.


<script src="blocks_compressed.js"></script>
<script src="javascript_compressed.js"></script>
<script src="msg/js/en.js"></script>

```

And it seems to me as a pitfall for anyone with a slight hurry,
not to notice how the first code block says: block**ly**_compressed.js
while the second says block**s**_compressed.js.
It would be nice if the documentation changed a bit to make this clear,
for example making the suffix (-ly, -s) bold,
or another example would be making the "narrative" comments in the same block of code, like this:

```
<!-- Once you've downloaded Blockly, you can add the following to your application code to load it: -->
<script src="blockly_compressed.js"></script>

<!-- You will probably also want to load Blockly's built-in blocks, at least one language generator, and at least one language file.-->

<script src="blocks_compressed.js"></script>
<script src="javascript_compressed.js"></script>
<script src="msg/js/en.js"></script>
```

I know the last example doesn't seem good, but I'm just suggesting, I have no solution.

**Comment by BeksOmega** [comment]
I think it's unlikely we're going to fix this github downloads are not recommended.
