### ISSUE TITLE
"Add custom block": Bad redirect

### ISSUE THREAD

**Issue by alexNecroJack** [google/blockly#6855]
### Location

https://developers.google.com/blockly/guides/create-custom-blocks/overview

### Type

- [X] Text
- [ ] Image or Gif
- [ ] Other

### Suggested content

The location of interest:

```
Use the new Block
After creating your block don't forget to add it to your toolbox or use it in a workspace.

→ More info on the [Toolbox](https://developers.google.com/blockly/guides/configure/web/toolbox)...
```

More info should redirect to https://developers.google.com/blockly/guides/configure/web/custom-blocks
which has the section "Add Custom Blocks",
rather than to Toolbox, which says nothing for custom blocks

**Comment by raushanranjan** [comment]
HI, where this file can be located to make changes.

**Comment by Akashdeep312** [comment]
hi @BeksOmega i would like to work on this

**Comment by Akashdeep312** [comment]
Thanks for letting me know @BeksOmega 👍
