### ISSUE TITLE
WorkspaceSvg.cleanUp() method doesn't account for immovable blocks

### ISSUE THREAD

**Issue by mikeharv** [google/blockly#6889]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

If blocks are immovable when `cleanUp()` is called, they are skipped. Other blocks are moved into a column but ignoring any immovable blocks that might already be there: https://github.com/google/blockly/blob/4125fd31534dd9f450219259b9ccb3c1495605c9/core/workspace_svg.ts#L1812-L1830

This creates a situation where `cleanUp()` can actually make things look worse, covering up immovable blocks with movable ones.

### Reproduction steps

1. Add several blocks to the workspace.
2. Set one or more blocks to be immovable (e.g. `Blockly.selected.setMovable(false)`)
3. Select "Clean up blocks" from the workspace context menu.

### Screenshots

https://user-images.githubusercontent.com/43474485/224034976-c49bc4b7-3fba-44bd-b849-074abbc4fff6.mp4

![image](https://user-images.githubusercontent.com/43474485/224035536-efdde068-644d-4728-8c0e-0d996e3ca593.png)

**Comment by rachel-fenichel** [comment]
Desired behaviour: when moving blocks during cleanup, check whether they will overlap with an immovable block, and move them somewhere else to avoid the conflict.

[`cleanUp`](https://github.com/google/blockly/blob/develop/core/workspace_svg.ts#L1810) is a fairly simple function on `WorkspaceSvg`. The change here is to build a list of immovable blocks and then check for conflicts. @mikeharv do you want to take a crack at this?

**Comment by maribethb** [comment]
For more background discussion, see https://github.com/google/blockly/issues/1734. Not necessarily related but has information about a smarter algorithm for cleaning up.
