### ISSUE TITLE
 How to make procedures shared betwen different workspaces

### ISSUE THREAD

**Issue by githubalvin** [google/blockly#6906]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Problem

I wanna make a custom procedure shared betwen different workspaces.

The idea is :
 1.workspace A defines a procedure block, then exports as a custom procedure model 'a'.
 2.workspace B  loads procedure model 'a'.
 3.workspace B could drag function 'a' into it's canvas directly without any duplicate definitions of 'a'

Actually,  a duplicate definition(which has been defined in workspace A) will be generated automatically  in workspace B, when procedure caller of 'a' was dragged into workspace B. 

Finaly, i found the answer in file blocks/procedures.js.
![impicture_20230320_140737](https://user-images.githubusercontent.com/13799840/226260468-c78a3cce-0e49-465c-932c-7ecdb197aa5a.png)

### Request

I hope a way to override function 'getDefinition' to makes my idea possible.
Maybe, an delegate function instead.

**Comment by githubalvin** [comment]
> 

That's awesome! 
Thanks for your reply  ^3^

**Comment by BeksOmega** [comment]
Closing this as the plugin has been released =)
