### ISSUE TITLE
Soft keyboard issues on Android

### ISSUE THREAD

**Issue by maribethb** [google/blockly#6915]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

If you disable modal inputs on mobile, then trying to edit number or text fields on Android devices will fail. The soft keyboard will pop up and then close immediately.

The cause of this is that when Android opens the keyboard, it fires a resize event. When Blockly, hears a resize event, it will hideChaff. This includes closing the widget div, which is the html element that should have focus that the user is typing into. Since it goes away, so does the soft keyboard. This issue does not occur on iOS because iOS does not fire resize events when the keyboard appears. It is an overlay on top of the browser content and the user (or app) is responsible for scrolling the content if desired.

#### Proposed option
During the window resize window event listener, do not hide all the chaff. Only hide a subset of it:

- Do not hide widget div. This solves the immediate problem and matches what Scratch does. This requires adding logic to reposition the widget div during a resize, which I have borrowed from Scratch and tested on multiple devices.
- Do not hide dropdown div. We already have the logic to reposition it correctly (I've tested it) and this would prevent this bug from occurring if there was a dropdown div with an html input in it (which I don't know of any right now, but doesn't seem that far fetched, like a combobox)
- Tooltip: hide (though I cannot think of a way to resize a window while a tooltip is triggered, better safe than sorry)
- Registrable components: hide (it's a shame that there is no way for components to opt out of this hiding the way we're doing for the built-in divs, but that's a feature we could implement if somebody asks, for now, YAGNI). we should hide them by default because they may not know how to reposition themselves during a resize. and because they may have been designed knowing that they would be hidden whenever `hideChaff` is called.

#### Alternatives considered
If you search the web for this issue (Android firing a resize event when showing the keyboard) you'll find a few solutions:

- In the resize event handler, check if the currently focused element is an html input element. if so, then assume this is a spurious android resize triggered by the keyboard, then skip the rest of the resize logic. This doesn't work because you might legitimately resize the browser (or rotate your device) while the input is active, and if you did then things would be positioned badly
- On mobile devices, make the current `resize` handler an `orientationchange` handler instead. That way, nothing happens during the resize event that Android fires. This is not a good idea because as mobile devices improve there may be ways to change the browser or window size without rotating the device (e.g. a tablet that can use windowed apps). Also, it adds complexity to change the behavior between mobile and desktop.

Other options:

- Since we haven't yet documented the new inject option, just get rid of it and don't fix this issue, people should continue to use the modal inputs. This is a shame, since Code.org doesn't want to use them and Scratch has made it work without them.
- Same as proposed fix, but continue hiding the dropdown div. This would match Scratch's behavior but may keep this bug around for html inputs in dropdowns.
- Same as proposed fix, but only skip hiding all the chaff if we've checked that we're on mobile and the `modalInputs` option is false. I don't like this because it adds complexity and behavior changes based on the device you're using, but it does limit the impact/scope of the behavior changes.

### Historical Notes

- [Scratch](https://github.com/LLK/scratch-blocks/blob/388eef441fce55fe11f1acc29e680fc8afbbdab8/core/blockly.js#L331) does not hide the widget div when doing the resize event, precisely because of this issue.
- Scratch [issue](https://github.com/LLK/scratch-blocks/issues/1345) about this
- Scratch [fix](https://github.com/LLK/scratch-blocks/pull/1743/files) for this issue
- We have [this bit of code](https://github.com/google/blockly/blob/252b204adb4148588eabdd28224c451c6069d68e/core/dropdowndiv.ts#L674) which also claims to reposition the dropdowndiv similarly, but it's never been used by us.
    - This was imported from [pxt-blockly](https://github.com/microsoft/pxt-blockly/blob/a932820978ebece8ff23098910dc22ea79112f41/core/dropdowndiv.js#L764) where, despite the name, it is used for some reason when moving connections and not ever used when the window is resized. This is not relevant to moving connections in blockly as if you were to drag a block then all chaff would be hidden. I assume their name/logic was just copied over from the name used by Scratch in the original fix for the widget div. We just copied it over when we took in the dropdown div.

### Why do we even care about this? Backstory time!

Blockly has historically used a modal prompt editor for editing input fields, like numbers and text fields where on desktop you would type a value. On mobile, there were too many issues with the soft keyboard showing up and disrupting the layout or ability to see the field you're editing. Thus, Blockly solved this problem by detecting mobile browsers and just opening a modal editor for them, which always gets the soft keyboard correctly.

In modern times, as browsers have better learned how to deal with soft keyboards, some Blockly users want to disable the prompt editor. For example, Scratch and Code.org do not use the prompt editor and just use the native soft keyboard. However, the prompt behavior in our built-in is not easily modifiable. Code.org disabled it in their fork by patching Blockly. If you wanted to disable this without patching, you must subclass every type of field that has an input. Thus, we added an inject option for this in https://github.com/google/blockly/issues/6608

### Reproduction steps

1. Open the playground on Android with the setting `modalInputs: false` in the inject options.
2. Click on a number field
3. Watch the keyboard appear and disappear quickly, and note the input does not have focus

You can also reproduce this in Code.org labs if you don't want to open the playground.

### Browsers

Android mobile

**Comment by rachel-fenichel** [comment]
> Registrable components: hide (it's a shame that there is no way for components to opt out of this hiding the way we're doing for the built-in divs, but that's a feature we could implement if somebody asks, for now, YAGNI). we should hide them by default because they may not know how to reposition themselves during a resize. and because they may have been designed knowing that they would be hidden whenever hideChaff is called.

And this is an argument for people to put their stuff inside a widget or dropdown div whenever possible (because we as the library can deal with this issue).

**Comment by rachel-fenichel** [comment]
> On mobile devices, make the current resize handler an orientationchange handler instead. That way, nothing happens during the resize event that Android fires. This is not a good idea because as mobile devices improve there may be ways to change the browser or window size without rotating the device (e.g. a tablet that can use windowed apps). Also, it adds complexity to change the behavior between mobile and desktop.

Microsoft surface laptops can be tablets with windowed apps.
