### ISSUE TITLE
Infinite loop when disposing the workspace

### ISSUE THREAD

**Issue by pavi2410** [google/blockly#6943]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

https://github.com/google/blockly/blob/69afe5b60fe43b5ed911db91ae62058d66ffe5ec/core/workspace.ts#L356-L358

This piece of code runs into an infinite loop. As the first element of the `topBlocks` array is not popped off the array, it never proceeds to the next element in the array. I do not know if it's already removed with the `dispose` call on the `topBlock` element. If it does, then my assumption is false.

Blockly version: `9.3.1`

### Reproduction steps

This is how my React component looks like:

```jsx
function BlocklyComponent(props: React.PropsWithChildren<{ initialXml: string } & BlocklyOptions>) {
    const ws = useRef<WorkspaceSvg | null>(null);

    useEffect(() => {
        const {initialXml, children, ...blocklyOptions} = props;

        if (!ws.current) {
            console.log('creating new workspace...');
            const newWs = Blockly.inject(
                "blocklyDiv",
                blocklyOptions,
            );
            Blockly.Xml.domToWorkspace(Blockly.Xml.textToDom(initialXml), newWs);
            ws.current = newWs;
        }

        return () => {
            ws.current?.dispose(); // infinitely loops here 
        }
    }, [ws, props]);

    return (
        <div id="blocklyDiv"/>
    );
}
```

### Stack trace

```shell
clear               workspace.ts:356
clear               workspace_svg.ts:2356
dispose             workspace.ts:157
dispose             workspace_svg.ts:852
BlocklyComponent    BlocklyComponent.tsx:62
```

**Comment by BeksOmega** [comment]
Hello @pavi2410 ! Can you reproduce this on [the playground](https://blockly-demo.appspot.com/static/tests/playground.html)? I tried running `Blockly.getMainWorkspace.clear()` as well as `Blockly.getMainWorkspace().dispose()` and didn't run into any issues.

**Comment by pavi2410** [comment]
I couldn't reproduce that on the playground. But this still persists on the React code. However, it works fine without disposing the workspace. It didn't notice much of any performance implications.

**Comment by pavi2410** [comment]
I feel that this could be an error in my block definitions. Other than that, there's not much changes.

**Comment by BeksOmega** [comment]
Hello @pavi2410 ! Were you able to isolate a block definition that reproduces the issue? If so, we could try to debug it and see if it's a Blockly problem or a React problem.

**Comment by pavi2410** [comment]
Hi @BeksOmega, now that I think more about it, this could be caused due to several factors:
1. I imported the block definitions from the App Inventor repo. I have some unresolved references to fix yet. Do you know which method in a block definition object is called when a workspace disposed?
2. When I tried reproducing this issue with the playground, I noticed that the codepath for dispose was different than what I found when debugging my project. It was `workspace.ts:dispose` vs `workspace_svg.ts:dispose` for the playground and my project respectively. I'm not sure if that makes any difference as I didn't use headless Blockly workspace there.

This is the project where I use the component: https://github.com/Kodular/ai-unchive/tree/react/src/components/blockly/BlocklyComponents.tsx

**Comment by rachel-fenichel** [comment]
Closing ad not reproducible. If you're still having this issue, please reopen and add a minimal reproduction case.
