### ISSUE TITLE
blockfactory demo when drag function category block to workspace at workspace factory tab will throw an error :The block associated with the block move event could not be found

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#6945]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

the question is descibe as title did,bellow I give two screenshot pictures,
after throw this issue,it could not drag any block to workspace anymore

I used v9.3.1 found this bug,and also tried v8.0.5,the old version didn't has this issue

### Reproduction steps

1. 
2. 
3. 

### Screenshots

![u0](https://user-images.githubusercontent.com/42778/229277133-9548150f-6276-467e-ad08-418db20afb81.png)
![u1](https://user-images.githubusercontent.com/42778/229277138-ff7fe5fe-dacd-4efa-8601-6c993405fae4.png)

**Comment by rachel-fenichel** [comment]
@BeksOmega please try to reproduce--this looks like a procedure issue.
