### ISSUE TITLE
Underscore naming convention mismatch with jsdoc privacy annotations.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#695]
The following end in underscores, but are not marked private (thus are getting published by jsdoc)
- Blockly.Bubble.resizeCallback_
- Blockly.FieldAngle.textElement_
- Blockly.FieldCheckbox.textElement_
- Blockly.FieldColour.textElement_
- Blockly.FieldDate.textElement_
- Blockly.FieldDropdown.textElement_
- Blockly.FieldImage.fieldGroup_
- Blockly.FieldImage.imageElement_
- Blockly.FieldImage.rectElement_
- Blockly.FieldImage.textElement_
- Blockly.FieldLabel.textElement_
- Blockly.FieldNumber.textElement_
- Blockly.FieldTextInput.htmlInput_
- Blockly.FieldTextInput.textElement_
- Blockly.FieldVariable.textElement_
- Blockly.Flyout.blockRightClick_
- blockly.Scrollbar.setHandleLength_
- Blockly.WorkspaceSvg.flyout_
- Blockly.WorkspaceSvg.resizeHandlerWrapper_
- Blockly.WorkspaceSvg.svgBackground_
- Blockly.WorkspaceSvg.svgBlockCanvas_
- Blockly.WorkspaceSvg.svgBubbleCanvas_
- Blockly.WorkspaceSvgsvgGroup_
- Blockly.WorkspaceSvg.zoomControls_
- Blockly.WorkspaceSvg
- Blockly.WorkspaceSvg

**Comment by cshung** [comment]
Is this still relevant? I would like to get started contributing with this one.
