### ISSUE TITLE
Opening `controls_if` block mutator dislocates attached blocks

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#6953]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Opening the mutator in a `controls_if` (if/elseif/else) block will cause any blocks attached to the elseif and else inputs of the block to be temporarily dislocated.

### Reproduction steps

In the Blockly playground, in v9.3.1:

1. Add an "if" block.
2. Open the block's mutator and add "elseif" and "else" clauses.
3. Close the mutator.
4. Add blocks to all the blocks inputs:
   <img width="201" alt="Screenshot 2023-04-05 at 13 50 42" src="https://user-images.githubusercontent.com/5603958/230085615-c13a828d-198d-4fc8-acb8-01d5a5a60851.png">
5. Open the mutator and observe the blocks attached to the elseif and else inputs have been dislocated:
   <img width="344" alt="Screenshot 2023-04-05 at 13 53 42" src="https://user-images.githubusercontent.com/5603958/230086674-32107928-56ad-47fc-adfa-7b917e02215a.png">
6. Drag the block and observe the blocks snap back to their correct location:
   <img width="232" alt="Screenshot 2023-04-05 at 13 53 54" src="https://user-images.githubusercontent.com/5603958/230086795-7a2ebc79-ee57-45b9-ba12-2b9cb845b0a4.png">

### Stack trace

Nothing in the console.

### Browsers

Chrome desktop

### Additional info

Discovered [via this report in the Blockly forum](https://groups.google.com/g/blockly/c/59KaiSYPoj8/m/kDny9uCOBAAJ).

**Comment by BeksOmega** [comment]
This is already fixed by #6918 ! We might want to get that merged and release a patch for this though.
