### ISSUE TITLE
Move `destroy` hook to beginning of `dispose`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6974]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Sometimes the references that external developers want to clean up in a blocks `destroy` hook are keyed based on other properties of the block. E.g. field input values. Currently we call `destroy` at the very end of `dispose`, after fields (and etc) have already been cleaned up, so they can't use these values to clean up references.

### Request

Call `destroy` first (or nearer to the beginning of the cycle) before the rest of the block has been disposed.

### Alternatives considered

N/A

### Additional context

I don't /think/ this would be a breaking change. But I'd need to noodle on it a bit more to see if it would cause any major problems.

Originally reported by @mark-friedman related to the lexical variables plugin.

**Comment by mark-friedman** [comment]
Might I also suggest that whether or not the code is changed, the documentation of `destroy` should mention where in `dispose` it is called and, ideally, what state the block will be in when it is called.

**Comment by maribethb** [comment]
This is probably a breaking change, and since we're already planning on doing v10 we might as well label it that way to make things clear for developers who may have implemented the destroy hook.
