### ISSUE TITLE
More granular events for changes

### ISSUE THREAD

**Issue by rtibbles** [google/blockly#70]
It would be useful to have a more fully fleshed out event API. At the moment anything interacting with Blockly has to listen to changes on the workspace as a whole and then attempt to inspect to see if values of interest have changed. While this is feasible, it is cumbersome, particularly considering how frequently the workspace change event gets fired.

At a first pass just firing 'change' events on individual blocks when something happens to them would be helpful, but it might perhaps also be helpful to fire 'value_change', 'unplug', and other values. These could be triggered from within the relevant methods that already exist in the Blocks.

Happy to try to implement this if it is something that is desirable, and this design seems appropriate.

**Comment by NeilFraser** [comment]
Fixed: https://developers.google.com/blockly/hacking/events

**Comment by rtibbles** [comment]
Excellent!
