### ISSUE TITLE
Insertion markers get disconnected/reconnected before being deleted

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#7002]
### Description

When a block is inserted into a stack, the stack is split, and the tail of the stack is reconnected to the bottom of the new block.  Unfortunately, this also applies to insertion markers.  An insertion marker gets disconnected and reconnected.  The corresponding events get broadcast.  And this results in errors when undoing and redoing, since there's no block with the ID of the insertion marker.

### Reproduction steps

1. On the playground, turn on event logging and open the console.
2. Create two statement blocks.
3. Connect one statement block to the bottom of the other statement block

Observe that in addition to the expected events, there's also two events relating to the insertion marker:
1. The insertion marker is disconnected from the bottom of the top statement block.
2. The insertion marker is connected to the bottom of the bottom statement block.

### Stack trace

```shell
{
    "workspaceId": "Ug].Xjo0iE8en8B=Rxq3",
    "isUiEvent": false,
    "type": "move",
    "group": "2OAGxl(TQw%EHp)AFA,C",
    "recordUndo": true,
    "isBlank": false,
    "blockId": "#iC6mjz3JEkmX3L|FDqz",
    "oldParentId": "if2",
    "reason": [
        "disconnect"
    ],
    "newCoordinate": {
        "x": 112.40234375,
        "y": 74.25
    }
}

{
    "workspaceId": "Ug].Xjo0iE8en8B=Rxq3",
    "isUiEvent": false,
    "type": "move",
    "group": "2OAGxl(TQw%EHp)AFA,C",
    "recordUndo": true,
    "isBlank": false,
    "blockId": "#iC6mjz3JEkmX3L|FDqz",
    "oldCoordinate": {
        "x": 112.40234375,
        "y": 74.25
    },
    "reason": [
        "connect"
    ],
    "newParentId": "if1"
}
```

### Screenshots

<img width="156" alt="Screenshot 2023-04-21 at 15 21 34" src="https://user-images.githubusercontent.com/250480/233646845-49af51ac-6ec1-4398-9689-607f421d843a.png">

**Comment by BeksOmega** [comment]
I think this might be a regression? I reordered some things in insertion markers when I was making performance improvements, and I might have broken this. But I haven't checked.

**Comment by NeilFraser** [comment]
Confirming, this is a regression.  Verified working correctly in v8.0.5, and broken in v9.3.2 (none of the intervening versions seems to compile on my machine).
