### ISSUE TITLE
Blockly.mainWorkspace doesn't update when interacting with certain UI elements

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#704]
The ones I've found so far that don't update are:
1. zoom buttons
2. scrollbars

You can verify https://blockly-demo.appspot.com/static/tests/multi_playground.html and checking Blockly.getMainWorkspace() in the console.

**Comment by NeilFraser** [comment]
Zoom buttons got fixed in 4d65b606bd13c30e762ac1d7e1eed4b568e6c078

**Comment by NeilFraser** [comment]
Scrollbars fixed in 6300faf85ed3bc8f574f9d3a9e9c516a92d9ad21.
