### ISSUE TITLE
Add support for tooltips on icons

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7047]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Currently icons don't support tooltips, and it might be nice if they did.

### Request

Allow one to provide a `getTooltip` method as part of an icon's class.

### Alternatives considered

N/A

### Additional context

There are places where we want to apply tooltips to fields, so it seems reasonable that one might also want to apply tooltips to icons.

**Comment by maxkoretskyi** [comment]
is there any ETA for this feauture? very useful with alongside custom tooltip

before it's implemented, if I need to have it now, am I right to assume I need to build my own icon, add it to the block, add click handler and inside the click handler get coordinates and render HTML at these coordinates?
