### ISSUE TITLE
Blockly with next 13 doesnt work

### ISSUE THREAD

**Issue by DanavsSite** [google/blockly#7051]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

i tried using blockly by installing blockly npm module but when i initialize it.There is a error "cant resolve module 'canas'"

### Reproduction steps

1. create nextjs project
2. install blockly npm module 
3. initialize it

**Comment by rachel-fenichel** [comment]
Have you tried posting on the [forum](https://groups.google.com/g/blockly) to see if anyone else has had this issue?

If you can't get any help there, please reopen this issue and add a minimal reproduction case, including code.

**Comment by daviFrag** [comment]
Hi, i'm new with this framework, but i have managed to install and deploy a nextjs 13 application with a Blockly editor page. If you want i can push an example in the blockly-sample repository

**Comment by mohamedsobhi777** [comment]
@daviFrag Could you provide the code for that? I am having some issues running blockly with nextjs 13. 
Thanks

**Comment by waseemhnyc** [comment]
I am also having difficulty getting blockly working with NextJS 13. @daviFrag / @mohamedsobhi777 did you ever figure it out? 

The error I am getting is pointing to an issue with webpack loader. 

If you have an example app up that I could clone and try it out that would be great.

**Comment by Zmnortal** [comment]
I think it is jsdom related issue. By checking other repo's issue, I found this and work fine on me.

```
/** @type {import('next').NextConfig} */
module.exports = {
+ webpack: (config) => {
+   config.externals = [...config.externals, "canvas", "jsdom"];
+   return config;
+ },
};
```
