### ISSUE TITLE
no arrows in <input  type="number" min="0" max="100" value="50"/> since 9.3.0

### ISSUE THREAD

**Issue by artbot1** [google/blockly#7092]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

After upgrading from 9.2.1 to 9.3.0 (and 9.3.1 and 9.3.3)

my input fields

 <input  type="number" min="0" max="100" value="50"/>

lost their arrows. switching back to 9.2.1 -> problem is gone!

reading the release notes: 

maybe it has to do with

refactor: Use input type=number for field_number.ts by @gonfunko in https://github.com/google/blockly/pull/6845

### Reproduction steps

<html>
<script>
   ... init here blocklyDiv ...
</script>
<body>
 <input  type="number" min="0" max="100" value="50"/>
<div id="blocklyDiv" style="width:600px;height:400px" />
</body>
</html>

**Comment by artbot1** [comment]
here it comes:

![input](https://github.com/google/blockly/assets/8578472/1eaad4b3-e53f-4ae6-8a4f-8b6d115a3a94)

(arrows are displayed by default on input type="number" and disappear using blockly 9.3 but not using 9.2)

**Comment by maribethb** [comment]
Hello,

In core Blockly we actually cannot use `input type="number"` for number fields unfortunately, and in the next release that will be changed back to a normal html input. For more information, see the [reason why in this issue](https://github.com/google/blockly/issues/1595#issuecomment-1533953067).

If you'd like to use `input type="number"` (or `inputMode="numeric"` which is probably better) in your own blocks, you can create a subclass of the built-in number field and override the generated HTML. Just note the limitations, such as not being able to type `Infinity` or hexadecimal numbers. If those restrictions don't matter for your app, then creating a custom field is a great option. But in core Blockly we can't abide by that restriction.

That said, do note Rachel's message above, where it is up to the browser to display those arrows. If you require them to be present, you may also wish to design your own number input field that always includes arrows. That would also be done as a custom field.

I hope that helps. If you need any assistance in creating the custom field, please ask on the [developer forum](https://groups.google.com/g/blockly). Thanks!
