### ISSUE TITLE
Impossible to use a block of a function call with a parameter

### ISSUE THREAD

**Issue by alexdz18** [google/blockly#71]
Was checked with the demo ....tmp/google-blockly-610565e/demos/code/index.html

* from the 'Functions' menu add a function block into the editor (e.g. name it 'testfunc')
* for the function block define use of a parameter - click at the Star icon and attach 'input name' block to the main block  (give it a name: arg)
* click at the Star icon to hide the context menu of the created function block
* try using a block for calling the function: from the 'Functions' menu select the block 'testfunc with arg'.
The calling block will be displayed in the editor just as 'testfunc' without a possiblity to specify its argument

**Comment by acbart** [comment]
Can confirm. Also, changing the parameters in the definition will trigger the missing parameters to appear in the calling block.

**Comment by acbart** [comment]
I think I've tracked down the problem. In the following line:

https://github.com/google/blockly/blob/315a5fc7623fd1dcdec44e7e6ff5abf52dad5649/blocks/procedures.js#L588

Modifies the arguments_ array and then passes it into setProcedureParameters. Meanwhile, in that function, there is a shortcut to determine if no update is required.

https://github.com/google/blockly/blob/master/blocks/procedures.js#L490

That shortcut compares arguments_ to the passed in value (which in this case is arguments_) and exits early if they're the same. I'm not sure if it's a perfect fix, but I believe that building a temporary array instead should solve the problem most correctly (at least, it works for me):

      var temp_arguments_ = [];
      for (var i = 0, childNode; childNode = xmlElement.childNodes[i]; i++) {
        if (childNode.nodeName.toLowerCase() == 'arg') {
          temp_arguments_.push(childNode.getAttribute('name'));
        }
      }
      // For the second argument (paramIds) use the arguments list as a dummy
      // list.
      this.setProcedureParameters(temp_arguments_, temp_arguments_);

**Comment by NeilFraser** [comment]
I believe this was fixed with pull 68.
https://github.com/google/blockly/pull/68
