### ISSUE TITLE
Have `getIcons` take in a generic `Type` type that allows it to return a specific icon type

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7126]
Currently the `getIcons` method returns an `IIcon` which means that if you want to retrieve a specific icon an call methods on it, you have to cast to that specific type of icon.

For example:
```
(block.getIcon(CommentIcon.TYPE) as CommentIcon).setBubbleSize(new Size(150, 150));
```

It would be much better if you could do:
```
block.getIcon(CommentIcon.TYPE).setBubbleSize(new Size(150, 150));
```

and have proper type checking.

This could be done by having the `.TYPE` property be a generic type, similar to how the registry works.

For example:

```
class CommentIcon {
  static TYPE = new IconType<CommentIcon>('comment');
}

class Block {
  getIcon<T>(type: IconType<T> | string): T;
}
```

**Comment by cpcallen** [comment]
An alternative would be to use literal types for the argument, as [TypeScript does for certain DOM methods like `Document.createElement`](https://www.typescriptlang.org/docs/handbook/dom-manipulation.html#the-document-interface), where the return type depends on the actual literal value passed in.

I'm not sure that that is as extensible as Beka's proposal, though.
