### ISSUE TITLE
Bug pinch zoom more than two fingers infinite loop

### ISSUE THREAD

**Issue by Plomging** [google/blockly#7134]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When you are in a pinch zoom, and you have more than two fingers on the screen, an infinite loop occurs.

### Reproduction steps

1. Start a pinch zoom
2. Add a third finger

### Browsers

Android mobile, iOS mobile

**Comment by gonfunko** [comment]
This was fixed by #8470.
