### ISSUE TITLE
Unable to control the style of hat

### ISSUE THREAD

**Issue by qsnote** [google/blockly#7139]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Problem

The display of the hat in the starting block can be controlled through code. We can customize a theme and control hat through the parameter 'startHats'. But I can't customize the style of hat.

### Request

Please open the control of the hat style.

**Comment by maribethb** [comment]
Hello,

You can customize the hat by creating a custom [renderer](https://developers.google.com/blockly/guides/configure/web/appearance/renderers). In the `ConstantProvider` class of your custom renderer, you can override the `makeStartHat` method to draw your own shape, or else the relevant height and width constants if you want to keep the shape but change the size. If you need help with this, you can post in the [forum](https://groups.google.com/g/blockly). When asking for help, note that posting your code, especially for something as complicated as renderers, is essential for us to help you. Thanks!
