### ISSUE TITLE
Clicking on blank space between toolbox items closes the item tree

### ISSUE THREAD

**Issue by aminmarashi-binary** [google/blockly#714]
This is much worse if you have many nested categories, in which case you need to go through those categories to select an item and you click in between of two by mistake and need to start over.
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/6560964/19675670/37163e20-9ac2-11e6-82ca-8f62e81650d3.gif)
Using separators makes this more likely to happen.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6560964/19675677/44fb6e52-9ac2-11e6-99a5-c0366cc3a140.gif)

**Comment by zgtm** [comment]
When having the same problem, I found a work-around. It is to make the following change in `core/toolbox.js`:

In the section

    '.blocklyTreeRow {',

change 

      'margin-bottom: 3px;',

to

      'padding-bottom: 3px;',

However this results in the colored borders merging into eachother, which is slightly less beautiful (but not as annoying as having the categories close by accident all the time): 

![image](https://user-images.githubusercontent.com/17168083/66921055-c10f3900-f024-11e9-8b4c-a0a3b94c4cf9.png)

A better fix would probably be to have a TreeNode bring an additional `<div>` node that encloses the whole thing with the padding of 3 Pixels and remove the margin from the inner node.

**Comment by samelhusseini** [comment]
Fixed.
