### ISSUE TITLE
Save comment bubble locations

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7140]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Comment bubble locations are not saved, so if you move them and then close/reopen them, they are shown at a different position from where they were before.

### Request

Save the positions of comment bubbles relative to their block.

### Alternatives considered

After v10 is released it will be possible to create custom icons. We could create a comment icon plugin that saves the position of the comment bubble.

### Additional context

The other built-in bubbles (mutators bubbles and warning bubbles) do not currently save their positions either.

If we have the comment bubbles save their positions, they could overlap the block when opened, which we currently avoid:

[Screen recording 2023-06-09 2.33.04 PM.webm](https://github.com/google/blockly/assets/25440652/9cb6c2b5-73e8-4cc8-be98-7c7948356b8c)

**Comment by maribethb** [comment]
@BeksOmega has someone asked for this? Putting the comment in a sensible location relative to the current location of blocks on the workspace makes more sense to me than always opening in the previous location.

This is as opposed to workspace comments, where the location on the workspace is very important and should be saved. But that already happens, I believe.

**Comment by BeksOmega** [comment]
Ah whoops, here's the original forum post askin for this feature: https://groups.google.com/g/blockly/c/buHsBxta0YE/m/Q_4WLEOAAQAJ

**Comment by maribethb** [comment]
We're not going to do this, because our default behavior solves the problem of overlapping comments and blocks. If someone wants this behavior they can also now implement a custom icon that behaves the way they want.
