### ISSUE TITLE
Blockly toolbox expanded onload even though expanded set to false in the xml category

### ISSUE THREAD

**Issue by gundupatil** [google/blockly#7152]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

Blockly categories are by default getting *expanded even though expanded set to false in the xml category

```
  '<xml id="toolbox" style="display: none">' +
      '<category name="Logic" expanded="false" colour="210">' +

        '<category name="Assign" colour="300">' +
        '<block type="logic_boolean"></block>' +
        '<block type="math_number"></block>' +
        '<block type="text"></block>' +
        '<block type="text_timestamp"></block>' +
        '</category>' +
       '</category>' +
     '<xml>'
```
not using expanded property in the xml category still by default it expands but subcategory blocks were unable use till we collapse and expand again

### Screenshots

![blockly-expand-issue](https://github.com/google/blockly/assets/17068378/1ed443db-e275-4f05-a894-8d4fc3398850)

**Comment by BeksOmega** [comment]
Closing this as a dupe of https://github.com/google/blockly/issues/6940 Please feel free to reopen if this is documenting a different problem =)

If it's the same problem the fix will be availble with v10 coming out at the end of this month!
