### ISSUE TITLE
disable-top-blocks should not enable procedure callers if their associated definitions are disabled

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7154]
**Describe the bug**

Procedure callers are supposed to be disabled if their associated definitions are disabled. However, this plugin automatically enables procedure caller blocks when they are attached to a start block, even if they are supposed to be disabled.

**To Reproduce**

1. Open the playground file, and add the follow code at the bottom of the `start` function.
```js
workspace.addChangeListener(Blockly.Events.disableOrphans);
```
3. Drag two procedure definitions into the workspace.
4. Disable the second one.
5. Drag a caller for the second one into the workspace.
6. Observe how it is disabled.
7. Attach the caller to the first procedure.
8. Observe how it is incorrectly enabled (incorrectly because its definition is disabled).

![image](https://github.com/google/blockly/assets/25440652/4589d23b-8d92-4053-9b5a-3b455dd4009b)

**Expected behavior**

Procedure callers should remain disabled if their definitions are disabled.

![image](https://github.com/google/blockly/assets/25440652/2a3e5bdd-e99d-4a11-a837-f3c3b170518f)

## To Fix

1) Run through the reproduction steps and make sure you can reproduce the issue.
2) In the [disableOrphans](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/events/utils.ts#L542) listener check if the block [isProcedureBlock](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/interfaces/i_procedure_block.ts#L19). If it is, make sure that its procedure model is enabled before enabling it.
1) Run the reproduction steps again and make sure the issue doesn't reproduce.

**Comment by KrautRock** [comment]
@BeksOmega I am interested in working on this

**Comment by Taru-Shukla** [comment]
I would like to work on this issue

**Comment by BeksOmega** [comment]
Hiya @KrautRock Taru actually messaged me on slack a few minutes before you commented, so I'm going to assign them =)

If you'd like to find a different issue I can get you assigned!

Go for it @Taru-Shukla =)

**Comment by harsh-791** [comment]
@BeksOmega I would like to work on this issue

**Comment by harsh-791** [comment]
@BeksOmega Please review my pr and if any changes required do tell me plese.

**Comment by BeksOmega** [comment]
Looks like this was already fixed by @johnnesky
