### ISSUE TITLE
When calling `setExpanded(false)`  on a collapsible toolbox category programmatically, the flyout should be closed 

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7174]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Originally reported by: https://groups.google.com/g/blockly/c/V5thY4HxQPI/m/bnlVYlzBAgAJ?utm_medium=email&utm_source=footer

If you call `setExpanded(false)` on a collapsible toolbox category, and one of the sub-categories is currently selected (i.e. its blocks are shown in the flyout). That flyout should be closed.

### Reproduction steps

1. Open the playground with the test blocks toolbox.
2. Select the "Connections > Row" toolbox category
3. Run the following code in the console `Blockly.getMainWorkspace().getToolbox().getToolboxItems()[2].setExpanded(false);`
4. Observe how the category is closed but the flyout is still open.

### Stack trace

```shell
N/A
```

### Screenshots

Step 2:
![Screenshot 2023-06-15 3 02 31 PM](https://github.com/google/blockly/assets/25440652/cd074ebb-2977-4c6a-851c-040496539ab5)

Step 4:
![Screenshot 2023-06-15 3 03 20 PM](https://github.com/google/blockly/assets/25440652/04f29eb8-b004-445f-8ccc-f02e40a44244)

**Comment by jibranabsarulislam** [comment]
i can take a look at this one! i'll double check the [guidelines](https://developers.google.com/blockly/guides/contribute/get-started) and [message guide](https://developers.google.com/blockly/guides/contribute/get-started/commits) for when I open a PR (saw a comment in another PR 🕵️‍♀️)
