### ISSUE TITLE
Add an API to programmatically scroll the workspace

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7176]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Problem

Sometimes you want to change how your users interact with scrolling the workspace. E.g. if you have a workspace that only supports vertical scrolling or only supports horizontal scrolling, you may want to add buttons that scroll instead of using the scrollbars.

Context: https://groups.google.com/g/blockly/c/klLbJ1aQqsA/m/lYjP5tyAAgAJ

### Request

Add an API for programatically scrolling the workspace. I'm not sure what the units should be (absolute vs relative, percentage vs workspace units, etc).

### Additional context

We currently have a scroll method on the workspace, but it is marked as `@internal`: https://github.com/google/blockly/blob/b8ad7d307f9f2abffe5306818155907287cfa634/core/workspace_svg.ts#L2179

## To Fix

1) Remove the `@internal` tag from the [scroll method](https://github.com/google/blockly/blob/b8ad7d307f9f2abffe5306818155907287cfa634/core/workspace_svg.ts#L2179).

**Comment by maribethb** [comment]
Seems reasonable to make the `scroll` function public. We just need to remove the `@internal` tag from the documentation comment.

**Comment by carthick** [comment]
Could you please assign me this issue.

**Comment by maribethb** [comment]
Hi @carthick, I've assigned you the issue. You can find some information about how to contribute to Blockly [here](https://developers.google.com/blockly/guides/contribute/get-started). Thanks for your interest!

**Comment by SophieNguyen113** [comment]
I would love to work on this issue

**Comment by BeksOmega** [comment]
@SophieNguyen113 Go for it!
