### ISSUE TITLE
Workspace comments aren't deletable and can cause infinite loops.

### ISSUE THREAD

**Issue by johnnesky** [google/blockly#7177]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Adding a workspace comment in the advanced playground permanently makes some playground features unusable, and the comments cannot be deleted.

### Reproduction steps

1. Navigate to https://blockly-demo.appspot.com/static/tests/playgrounds/advanced_playground.html
2. Right-click in the workspace and add a comment.
3. Delete the comment, either by dragging it to the trash, clicking the X button, or right clicking on it.
4. Refresh the page. The comment reappears. The serialized XML is also visible and always contains the comment regardless of whether it's "deleted" or not. I'm not aware of any way to permanently delete the comment except to delete your browser's local storage's copy of the workspace xml.
5. Regardless of whether the comment is hidden or not, try changing the renderer or theme, or click the reset button at the top of the advanced playground controls. Any of these actions causes an apparently infinite loop that can only be interrupted by closing the browser tab (or using the browser's developer tools).

**Comment by rachel-fenichel** [comment]
I have some debug info but not yet a fix:
- The rendered workspace comment calls [`dispose`](https://github.com/google/blockly/blob/develop/core/workspace_comment_svg.ts#L132) on itself when the x is clicked (or other ways of doing deletion)
- `dispose` [calls `disposeInternal`](https://github.com/google/blockly/blob/develop/core/workspace_comment_svg.ts#L148) and [then `super.dispose`](https://github.com/google/blockly/blob/develop/core/workspace_comment_svg.ts#LL151C1-L151C1)
- `disposeInternal` sets [`this.disposed_ = true`](https://github.com/google/blockly/blob/develop/core/workspace_comment_svg.ts#L994)
- [`super.dispose`](https://github.com/google/blockly/blob/develop/core/workspace_comment.ts#L96) bails early if `this.disposed` is `true`
- [Removing](https://github.com/google/blockly/blob/develop/core/workspace_comment.ts#L105) the comment from the workspace's array of top level comments happens in the `super.dispose` call, so it's never happening

**Comment by johnnesky** [comment]
I think the infinite loop is related to what you discovered. I paused the javascript execution after triggering the infinite loop, and the stack trace ended up pointing here:
![image](https://github.com/google/blockly/assets/54517768/60242093-bb0f-4007-b4eb-ce657800b8db)

It looks like it's just repeatedly trying to dispose the comment and failing.

**Comment by johnnesky** [comment]
I suspect we can just delete disposeInternal() entirely to fix this problem, although I'm also confused about how this ever worked. Is there a known good release somewhere that we can use as a basis for a git bisect?

**Comment by rachel-fenichel** [comment]
Yes, that would certainly explain the infinite loop.

No, I don't have a known good release to start from, but you could work backward through major releases to look for this problem.

**Comment by johnnesky** [comment]
With some help from the team, I've verified that workspace comments were working in version 6: https://github.com/google/blockly/releases/tag/6.20210701.0
But not in version 7: https://github.com/google/blockly/releases/tag/7.20211209.0-beta.0

In version 6, `workspace_comment.js` did not initially define a `disposed_` property. Instead, it used the `workspace` property to determine if it was disposed:
<img width="609" alt="image" src="https://github.com/google/blockly/assets/54517768/83046b60-c28e-446a-baa4-d1cfab127c40">

`workspace_comment_svg.js` also used the `workspace` property in the same way. HOWEVER `workspace_comment_render_svg.js` did in fact assign a value to the `disposed_` property in `disposeInternal_()`, and referenced it (regardless of whether it has been assigned a value) in focus-related methods:
<img width="609" alt="image" src="https://github.com/google/blockly/assets/54517768/bcfc5fd6-5eaf-44ca-a8ad-4e6537c27ebc">

On July 29, 2021, the contents of `workspace_comment_render_svg.js` were moved into `workspace_comment_svg.js` although I think this did not substantially change disposing behavior:
https://github.com/google/blockly/commit/beff5e19bf5e8fab93a7fac6d5f76a34e6ee0c3b

On August 6, 2021, I think https://github.com/google/blockly/commit/b834d9026b17886f862418181983965db5879b19 is where workspace comments broke. This commit finally defined a default value of false for the `disposed_` property in `workspace_comment.js`, which is good! It also changed the `dispose()` methods in both `workspace_comment.js` and `workspace_comment_svg.js` to check this `disposed_` property before continuing instead of checking `workspace`, which is probably also good! However, it preserved the existing behavior of setting `disposed_` to true in the subclass's `disposeInternal_()` method before attempting to call the super class's `dispose()` method, which is why the super class's method no longer works. 

The super class is now also trying to set `disposed_` to true, but that code doesn't run because its `dispose()` method doesn't run. In my opinion, this method should be responsible for setting the property to true, and the subclass should not be doing it.
