### ISSUE TITLE
visual Mutators build factory

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#7184]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

block factory is awesome,but lack of some useful kind of blocks,could you add some extra useful block into block factory,or made a visual mutators build factory is great 

### Request

I have many custom blocks to build my business,so a visual mutators build factory is very helpful

**Comment by maribethb** [comment]
Thanks for your feature request! While we do appreciate that building mutators is difficult, we don't have plans to add this to block factory. If you run into specific questions as you're building your blocks, please do ask in our [forum](https://groups.google.com/g/blockly). Thanks!
