### ISSUE TITLE
Add gitattributes file to standardize line endings

### ISSUE THREAD

**Issue by maribethb** [google/blockly#7191]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

If you change files when working on Windows, you will end up checking in files with Windows-style CRLF line endings, but the library should use Linux-style LF endings.

To rectify this, we should add a `.gitattributes` file with the following content:

```text
* text=auto
```

This will have Git automatically convert the line endings in any text-based file (so not binary files like images) to LF when checking them out, but allow you to use CRLF endings on your local copy if you're using Windows.

h/t [this article](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#configuring-line-endings-in-git-with-coreautocrlf) for the info

**Comment by mehboobali98** [comment]
Hi, can I work on this? TIA

**Comment by 1mazin** [comment]
@maribethb can I work on this issue?

**Comment by maribethb** [comment]
Hi @mehboobali98 you got here first, go for it! We have information about contributing on our [site](https://developers.google.com/blockly/guides/contribute/get-started). One important thing it to make sure your [commit messages are formatted appropriately](https://developers.google.com/blockly/guides/contribute/get-started/commits). Thanks!

@1mazin Someone else asked first but will let you know if they decide to drop the issue. You might find other issues you want to work on by checking the `size: small` label, or check the `good first issue` tag in our sister repo google/blockly-samples

Thanks!

**Comment by sam301100** [comment]
Hello @maribethb,
Can I work on this issue?

**Comment by BeksOmega** [comment]
@sam301100 Go for it!

**Comment by sam301100** [comment]
Thank you so much!
