### ISSUE TITLE
Support the dynamic connections plugin without hacky monkey-patching.

### ISSUE THREAD

**Issue by johnnesky** [google/blockly#7204]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

The `block-dynamic-connection` plugin monkey-patches `Blockly.InsertionMarkerManager`. It adds a new property, `pendingBlocks`, and overrides the `update` and `dispose` methods, but there's no facility to provide an alternative implementation of the interface so it has to fall back on monkey-patching. 

Additionally, my PR to migrate the plugin to TypeScript uses hacky syntax (square brackets) to access private methods, which maybe could be made protected instead. https://github.com/google/blockly-samples/pull/1719

### Request

Design and implement support for the dynamic connections plugin and similar plugins. The plugin logic can be modified too if necessary.

**Comment by BeksOmega** [comment]
Related stuff about reindeer connections: https://github.com/microsoft/pxt-blockly/pull/287

**Comment by BeksOmega** [comment]
Closed by https://github.com/google/blockly-samples/pull/2190
