### ISSUE TITLE
block support layer feature,like adobe photoshop

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#7207]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Request

If we use block design software,one workspace may contain many function,this workspace will have too many blocks,so suggestion is use adobe photoshop layer feature,fucntion block could belongs one layer,and other could belongs another layer,layer could show & hidden,and the workspace will clear ,we could focus our current work,I think this is a good idea,hope accept it

**Comment by maribethb** [comment]
Hi, thanks for your feature request! This is the kind of feature that would be best implemented in your own application and not something we'd add to core Blockly. Another related idea is using multiple workspaces to simulate having multiple text files. We aim to enable those types of experiences without building them into core. So to implement this idea, you can use our APIs that make blocks editable or not to design your own interface for dealing with this. If you run into more specific feature requests needed to make this possible, please open another bug with more details about your goals. Thanks!
