### ISSUE TITLE
Horizontal flyout cleanup tasks

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#7215]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

I want to pull the horizontal flyout into a plugin, but it uses some internal APIs.

### Request

Find everything that the horizontal flyout uses that is internal and decide whether to make it externally visible, change how the flyout works, or something else. Implement those decisions.

### Additional context

- [ ] ~`targetWorkspace`: is `@internal` on `FlyoutBase`, needs to become `public`. Can't just be `protected` because we also access it from gesture code.~ Split into #7461 
- [ ] ~`isDragTowardWorkspace` is `internal` on `FlyoutHorizontal` and is called from gesture code. It's already part of the flyout interface. It should not be `internal`.~ Split into https://github.com/google/blockly/issues/7462

**Comment by gonfunko** [comment]
Closing since subtasks have been completed.
