### ISSUE TITLE
Delete fields that were moved to samples out of core

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7226]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

To actually make Blockly smaller when compressed, we need to delete the fields that were moved into samples out of core.

### Request

Delete the fields from core.

### Alternatives considered

N/A

### Additional context

Dependent on https://github.com/google/blockly/issues/7225

Issues that tracked moving the fields:
https://github.com/google/blockly-samples/issues/1646
https://github.com/google/blockly-samples/issues/1645
https://github.com/google/blockly-samples/issues/1644

**Comment by maribethb** [comment]
We put this in the Q3 project, but we haven't decided if we're doing a major release yet or not this quarter. So a PR for this should not be submitted until we've confirmed we plan to do a major release as this is a breaking change.

**Comment by maribethb** [comment]
Note https://github.com/google/blockly-samples/issues/1733 needs to be fixed before this can be submitted as well.

**Comment by rachel-fenichel** [comment]
Issues to track additional work for moving block definitions into the field plugins:

- https://github.com/google/blockly-samples/issues/2152
- https://github.com/google/blockly-samples/issues/2153
-  https://github.com/google/blockly-samples/issues/2154

**Comment by rachel-fenichel** [comment]
We also need to validate that all of the `register` functions (`registerMutator`, `registerMixin`, etc) can handle registering the same extension multiple times. The desired behaviour is:
- Check for any other functions that need to have the same behaviour
- Check the currently registered function and ensure it matches the one attempting to be registered. If so, silently accept the registration call and do nothing. If they don’t match, emit a warning or error. 
- Update if needed

Rationale: An accepted pattern of use for fields is to unregister a field class, then register a substitute class under the same name. This allows users to install a default Blockly block but change the underlying field to one with different functionality. 

Documentation: We may need to instruct users to unregister fields only *after* installing any blocks, so their objects are not overwritten by the built-in objects.
