### ISSUE TITLE
Make connection's getOffsetInBlock public

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7227]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

The `getOffsetInBlock` method is `@internal`, which means that external developers aren't supposed to access it.

However, it is currently used by the debug renderer in `@blockly/dev-tools` as well as the marker_svgs in the default renderer and zelos.

### Request

The `getOffsetInBlock` method should be made public. The fact that it is accessed by the marker_svgs is a particularly compelling reason, because we want external developers to be able to create their own marker_svgs, and this is a significant blocker to them doing so.

### Alternatives considered

N/A

### Additional context

https://github.com/google/blockly-samples/pull/1747

**Comment by maribethb** [comment]
All that needs to happen here is remove the `@internal` annotation from [`getOffsetInBlock`](https://github.com/google/blockly/blob/a677355f7319140f68c13c3468470b0ecd9d25b8/core/rendered_connection.ts#L267) method.
