### ISSUE TITLE
start/stop of a script using "javascript.X.scriptEnabled." throws error

### ISSUE THREAD

**Issue by gidhap** [google/blockly#7232]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

From within a Blockly script "test1" I start and stop another script "MP3", by updating script "MP3" datapoint javascript.X.scriptEnabled.MP3, to true or false. 

Doing so the log throws an error:

javascript.0 (7069) script.js.test.test1: Own states (javascript.0.scriptEnabled.test.MP3) should not be used in javascript.X.scriptEnabled.*! Please move the states to 0_userdata.0.*

JScript engine 7.0.3
NPM 9.5.1
NodeJS 18.16.0

### Reproduction steps

1. make a simple Blockly script updating another scripts datapoint  "javascript.0.scriptEnabled.xxx"

### Screenshots

![image](https://github.com/google/blockly/assets/28500973/cfbded3d-b15e-4c63-934b-fd7d5451ff98)
![image](https://github.com/google/blockly/assets/28500973/c89ac53e-7948-432a-9dad-de03cebd579d)

### Browsers

Chrome desktop

**Comment by maribethb** [comment]
Hi @gidhap ,

It looks like you might have a question about how to use a tool that is written with Blockly. The errors you're showing aren't thrown by Blockly, so they must be thrown by whatever application is executing the code generated by these blocks.

If you are the author of that application and are looking for help in how to fix your generated code, you can ask on the [forum](https://groups.google.com/g/blockly) for help. We will need more information to help you though. Please post your block definition and generator functions along with any other information that might help us such as the goal/purpose of these blocks and how you import Blockly.

If you are not the author of an application and instead you are using a tool that uses Blockly, then unfortunately we are not the right people to be able to help you, and you would need to contact the creators of the tool you're trying to use.

Best of luck!
