### ISSUE TITLE
Delete devsite docs on fields that were moved out of core into samples

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7245]
### Location

https://developers.google.com/blockly/guides/create-custom-blocks/fields/built-in-fields/overview

### Type

- [X] Text
- [ ] Image or Gif
- [ ] Other

### Suggested content

None content! How to use these fields will now be included in the respective packages' readmes.

### Additional context

Part of https://github.com/google/blockly/issues/7226

**Comment by maribethb** [comment]
When we delete the content, let's either add a redirect automatically to the readme, or add a link on the page to point to the readme.
