### ISSUE TITLE
Flexible Blockly Flyout layout 

### ISSUE THREAD

**Issue by ahana204** [google/blockly#7263]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

I would like to implement a toolbox (blockly Flyout) that is more flexible in its layout as compared to the existing layout which only allows blocks in the toolbox to be placed one below the other. Below is a template of the toolbox.
![blockly_flexible_flyout](https://github.com/google/blockly/assets/20275839/3b89295a-2b15-49b3-9613-0d26121c501e)

### Request

Would it be possible to have a more flexible XML description of the toolbox layout that would allow a wider range of Flyout layouts?

**Comment by maribethb** [comment]
Hello, thank you for filing this feature request! We've discussed it amongst the team and unfortunately this is not something we plan to add to the core library. It is likely to be quite custom to your own application and would require changes to the XML or JSON format used to define toolboxes, which would be difficult to update for existing users, in addition to adding custom rendering to handle this case. We encourage you to attempt this using a custom flyout and report back if you were successful in the forum, though! This is the kind of custom behavior we hope to support by letting you register custom classes, without us building in direct support in core.
