### ISSUE TITLE
Add support for selecting toolbox items by ID

### ISSUE THREAD

**Issue by gonfunko** [google/blockly#7273]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Currently, IToolbox defines a `selectItemByPosition()` method, that allows for selecting a toolbox item by its index. There is however no straightforward way to select an item by type/kind; this came up in https://github.com/google/blockly-samples/pull/1751/files#diff-af9d92f020d53ffacb71e0519ecb2e9fa99c6b0d888131f7e7c5a32376df3553R71, where a toolbox item had to go hunting for itself in the toolbox definition in order to determine its index to select itself.

### Request

It would be great if IToolbox also allowed selecting an item by kind and/or ID, so that a known toolbox item could easily be selected without having to know (or find) where exactly in the toolbox it is.

**Comment by maribethb** [comment]
Seems reasonable, but I think if we add a required method to an interface, that would be a breaking change, so let's save this for the next major release
