### ISSUE TITLE
Disabling scrollbars causes odd behavior when retrieving blocks from toolbox

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#728]
I wanted to turn off the scrollbars on a workspace I had, the toolbox has categories.

With the scrollbars turned off, when I grab a block from the toolbox the block appears a few inches left of the cursor. When the block is in the workspace I can grab it and move it as normal.

**Comment by picklesrus** [comment]
https://github.com/google/blockly/pull/732 doesn't fix this bug and neither does the work I've been doing on the workspace dragging. We'll need separate fix.

**Comment by picklesrus** [comment]
Took a quick look and it seems in placeNewblock in flyout, the xyNew (from the call to getSVGXY) is different when there are scrollbars and when there aren't.  Haven't dug into why yet.

**Comment by picklesrus** [comment]
Another minor update (looking at this between tasks), It appears the blocklyBlockCanvas <g> element has different transform attribute on load.  With scrollbars it is shifted by the width of the toolbox, but without the scrollbars it is set to 0.

**Comment by samelhusseini** [comment]
Tried disabling scrollbars and can no longer repro this. Closing.
