### ISSUE TITLE
Only first block registering when connected in a serial

### ISSUE THREAD

**Issue by adamalbu** [google/blockly#7302]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

I tried making my own custom blocks and they work, but when connected in a series, only the first block generates any code.
Script:
```javascript
const toolbox = {
    "kind": "flyoutToolbox",
    "contents": [
        {
            "kind": "block",
            "type": "start_of_file"
        },
        {
            "kind": "block",
            "type": "include"
        }
    ]
}

const cppGenerator = new Blockly.Generator('cppGenerator');

Blockly.Blocks['start_of_file'] = {
    init: function() {
        this.appendDummyInput()
            .appendField("File name:")
            .appendField(new Blockly.FieldTextInput("main"), "filename");
        this.appendDummyInput()
            .appendField("Description: ")
            .appendField(new Blockly.FieldTextInput("The main file"), "description");
        this.setNextStatement(true, null);
        this.setColour(230);
        this.setTooltip("");
        this.setHelpUrl("");
    }
};

Blockly.Blocks['include'] = {
    init: function() {
        this.appendDummyInput()
            .appendField("use the")
            .appendField(new Blockly.FieldTextInput("iostream"), "header")
            .appendField("header");
        this.setPreviousStatement(true, null);
        this.setNextStatement(true, null);
        this.setColour(230);
        this.setTooltip("");
        this.setHelpUrl("");
    }
};

cppGenerator.forBlock['start_of_file'] = function(block, generator) {
    var filename = block.getFieldValue('filename');
    if (filename.slice(-4) != ".cpp") {
        filename += ".cpp"
    }

    var description = block.getFieldValue('description');

    console.log(block)

    return `// ${filename}\n// ${description}`;
}

cppGenerator.forBlock['include'] = function(block, generator) {
    var header = block.getFieldValue('header');

    return `#include <${header}>`
}

const workspace = Blockly.inject('blocklyDiv', { toolbox: toolbox });

function updateCode(event) {
    const code = cppGenerator.workspaceToCode(workspace);
    document.getElementById('textarea').value = code;
}
// workspace.addChangeListener(Blockly.Events.disableOrphans);
workspace.addChangeListener(updateCode);
```

### Screenshots

Current Result:
![image](https://github.com/google/blockly/assets/45970222/2646f1af-4c55-4534-aa17-7674c2d1542f)
Expected Result:
![image](https://github.com/google/blockly/assets/45970222/69e1ebae-5163-48a0-a53a-99a786c27c82)

**Comment by maribethb** [comment]
Hello,

Creating a new block generator requires more work than just instantiating the class and adding your block's code. Apologies that the docs on this topic are a bit misleading in that way. In particular, getting the generator to generate code for connected blocks needs to be implemented by you and this topic is covered in the [Custom Generator codelab](https://blocklycodelabs.dev/codelabs/custom-generator/index.html?index=..%2F..index#8). I highly recommend that you do that codelab and also check out the existing generators to see what other kind of setup you might need to do for your generator. If you have any questions about how to implement your custom generator, please ask them on our [developer forum](https://groups.google.com/g/blockly). We provide active support there whereas questions in GitHub may get lost.
