### ISSUE TITLE
TypeError: Expecting tuple from value block blockly

### ISSUE THREAD

**Issue by Eleftheria-99** [google/blockly#7309]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

I am trying to 'set' a variable, then 'get' it to use it in a custom block I've created.  But I'm not getting the value of the variable, I'm getting this error instead:  Uncaught (in promise) TypeError: Expecting tuple from value block blockly.

### Reproduction steps

When I add the blocks this way, everything works okay
![image](https://github.com/google/blockly/assets/58575584/0e6069b9-2103-41cd-acf8-bae1a3ef96c8)

When I try to use a variable , it does not work !
![image](https://github.com/google/blockly/assets/58575584/487c2db8-db4b-4a14-84d3-14b91d15d4e6)

### Stack trace

```shell
The code : 
Blockly.Blocks['digital_input_pin_value'] = {
    init: function () {
        this.appendValueInput('NAME')
           .setCheck('INPUT_PIN')
           .appendField('Get value')
        this.setOutput(true, null)
        this.setColour(355)
        this.setTooltip('')
        this.setHelpUrl('')
    },
}

Blockly.Python['digital_input_pin_value'] = function (block) {
    var value_name = Blockly.Python.valueToCode(block, 'NAME',
    Blockly.Python.ORDER_ATOMIC)
    var code = value_name + '.value()\n'
    return code
}

and :

Blockly.Blocks['digital_input_pin_obj_up_down_resistance'] = {
	init: function () {
		this.appendDummyInput()
			.appendField('Input pin number')
			.appendField(new Blockly.FieldNumber(0, 0, 40), 'pin_number')
			.appendField('with PULL UP resistance')
		this.setOutput(true, 'INPUT_PIN')
		this.setColour(355)
		this.setTooltip('')
		this.setHelpUrl('')
	},
}

Blockly.Python['digital_input_pin_obj_up_down_resistance'] = function (block) {
	var pin_number = block.getFieldValue('pin_number')
	//Assemble Python into code variable.
	var code = 'Pin(' + pin_number + ', Pin.IN, Pin.PULL_UP)\n'
	//Change ORDER_NONE to the correct strength.
	return [code, Blockly.Python.ORDER_NONE]
}
```

### Browsers

Chrome desktop

**Comment by maribethb** [comment]
Hello, I see that you've also asked this question in our [forum](https://groups.google.com/g/blockly/c/a3ZMp_0Sg2M). We do all of our developer support there rather than on GitHub Issues. I will close this bug and someone will answer your question on the forum soon, usually within 2 business days. Thanks!
