### ISSUE TITLE
Zelos Renderer Glitchy on Raspberry Pi Chrome

### ISSUE THREAD

**Issue by MatzElectronics** [google/blockly#7318]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When using the Zelos renderer on Chromium version 113 on a Raspberry Pi, the block highlighting that surrounds the block when selected, dragging, etc. is glitchy to the point of unusable.  I cannot replicate this on other systems, just the Pi - unfortunately, that is our target platform the the product we are developing.  The other renderers appear to work correctly.

### Reproduction steps

1. Open Chromium on a Raspberry Pi
2. Go to https://blockly-demo.appspot.com/static/tests/playgrounds/advanced_playground.html#renderer=zelos&debugEnabled=false
3. Try dragging around or manipulating blocks to experience the glitching.

### Stack trace

There are no errors displayed in the browser console

### Screenshots

![ezgif com-video-to-gif (2)](https://github.com/google/blockly/assets/19737272/214ee10c-d101-4fd4-b193-deb30295a817)

### Browsers

Chrome desktop

**Comment by rachel-fenichel** [comment]
A couple of debugging questions for you:
- Does this happen with other renderers as well?
- Does this happen outside of the playground?
- Do you have any custom CSS? (seems unlikely since you're seeing it in the hosted playground, but I'm asking for completeness.)
- With the playground, does the problem go away if you clear the cache and reload?

I don't have an immediate answer to what's going on here. It looks like possibly an issue with either SVG or CSS in the chrome implementation on the Pi. We'll definitely take a fix if you have one.

**Comment by MatzElectronics** [comment]
Good afternoon,

To answer your questions:
- Does this happen with other renderers as well? - No, it only appears to be an issue with the Zelos renderer
- Does this happen outside of the playground? - Yes, I can replicate it on our project with the Q3 2020 version and v10.0
- Do you have any custom CSS? (seems unlikely since you're seeing it in the hosted playground, but I'm asking for completeness.) - a small amount, a little for a couple of blocks, and the toolbox
- With the playground, does the problem go away if you clear the cache and reload? - I'll test this as soon as I can and report back.

I don't have an immediate answer to what's going on here. It looks like possibly an issue with either SVG or CSS in the chrome implementation on the Pi. We'll definitely take a fix if you have one. - Thank you - I have no idea either, and I don't even know where to start.

**Comment by rachel-fenichel** [comment]
Closing as not planned because I don't have enough information to move forward, and suspect that it's an issue with Chrome on the Pi. Please reopen if you have more information.
