### ISSUE TITLE
Browser test helper: get workspace SVG root

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#7332]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Request

Add a helper that gets the svg root of the main workspace so that it can be clicked on.

Optionally also add a helper to do this for a mutator workspace.

**Comment by rachel-fenichel** [comment]
To get set up for this issue:
- Run `npm install` from the root of the repository.
- Run `npm run build` from the root of the repository.
- Run `npm run test:browser` from the root of the repository and make sure all tests pass (this may take a few minutes)
There is [code that clicks on the workspace](https://github.com/google/blockly/blob/osd/tests/browser/test/field_edits_test.js#L50-L53) in `tests/browser/test/field_edits_test.js`.

Steps to fix:
- Extract this code to a function in [`tests/browser/test/test_setup.js`](https://github.com/google/blockly/blob/osd/tests/browser/test/test_setup.js)
- Export the function from `test_setup.js`
- Import the function in `field_edits_test.js` and call it
- Run `npm run test:browser` from the root of the repository and make sure all tests pass (this may take a few minutes)

**Comment by anmbajaj** [comment]
I am attending GHC 2023, and I will be interested in taking up this issue

**Comment by rachel-fenichel** [comment]
Thanks for your interest! This is currently being worked on in the `blockly-caribou` breakout room.

**Comment by RaunaqMalhotra** [comment]
Hi, I'm just getting started with Open Source Projects, specifically Blockly, and this looks like a good first issue to pick up. Is this issue still being worked on?

**Comment by BeksOmega** [comment]
Nope you can go for it @RaunaqMalhotra =) Let us know if you have any questions!

**Comment by RaunaqMalhotra** [comment]
Great, thank you @BeksOmega :)

**Comment by BeksOmega** [comment]
Heya @RaunaqMalhotra Are you still interested in working on this issue? If not I'll unassign you on Friday!

**Comment by bsampada7** [comment]
Hi @BeksOmega , Can I work on this issue?

**Comment by bsampada7** [comment]
Hi @BeksOmega, Is this issue open to work?

**Comment by BeksOmega** [comment]
> Hi @BeksOmega, Is this issue open to work?

Sorry missed your first message! Absolutely go for it =)
