### ISSUE TITLE
Blockly.utils defines functions on raw Blockly namespace

### ISSUE THREAD

**Issue by hochhaus** [google/blockly#734]
When using blockly in ADVANCED compiled mode, we realized that `utils.js`defines some functions (eg: `Blockly.addClass_`) on the raw `Blockly` namespace.

For example: https://github.com/google/blockly/blob/master/core/utils.js#L45

As `utils.js` specifies `goog.provide('Blockly.utils');`, these functions should either be moved inside the namespace (eg: `Blockly.utils.addClass_`) or moved into `core/blockly.js`.

**Comment by NeilFraser** [comment]
I agree.  The newer functions in utils are namespaced to utils, but the older ones are still on Blockly.  The question is how many can be moved without breaking third party code.  I don't want to break stuff and run, so I nominate @rachel-fenichel to make this change and handle the aftermath.

**Comment by hochhaus** [comment]
Thanks Neil and Rachel!

**Comment by NeilFraser** [comment]
Done.  All changes checked into develop branch.  We'll let it sit here for a bit before merging with master.
