### ISSUE TITLE
blockfactory dummyinput didn't have name

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#7353]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

I learnning the https://google.github.io/blockly-samples/plugins/block-plus-minus/test/index.html code to implement a print with mutiple input,and I want to use blockfactory to archive the definition json,but I found the dummy input could not give a name thourh the blockfactory tool

![Snipaste_2023-08-03_14-48-49](https://github.com/google/blockly/assets/42778/622d8c6a-481d-4d3b-94ba-c8c91f758d30)

what I want is change the dummy input block,give an name just like other input block

### Reproduction steps

1. 
2. 
3.

**Comment by maribethb** [comment]
Hello, thank you for filing this issue. You can manually add the name to the block definition when you copy it into your application. While we hope the block factory is a useful starting point for your custom blocks, it is not intended to support every way that you could customize blocks, so this is not something we would likely add to block factory at this time.
