### ISSUE TITLE
Add documentation for newlines in messages and "input_end_row" JSON type.

### ISSUE THREAD

**Issue by johnnesky** [google/blockly#7360]
### Location

https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks

### Type

- [X] Text
- [ ] Image or Gif
- [X] Other

### Suggested content

The new feature is the ability to easily split a block into multiple rows even if the block has inline inputs. This also works for non-inline blocks, so this can probably replace dummies as the primary way to organize rows. (Dummies might still be useful for controlling groups of fields within a row, e.g. with mixed alignment or mutators.)

There are technically 3 ways to invoke the new feature: adding a newline "\n" character to a JSON block definition's message property, adding an input of type "input_end_row", or using the new JavaScript API method appendEndRowInput().

I also added "implicitAlign" as an alias for "lastDummyAlign". Both properties apply to both the implicit EndRowInputs created via newline characters, and the implicit DummyInput at the end of a block.

Many sections will need to be updated but at the very least: \
https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#block_inputs \
https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#args \
https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#lastdummyalign0 \
https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#inputs_and_fields_in_javascript

### Additional context

See: https://github.com/google/blockly/pull/6944

**Comment by johnnesky** [comment]
I've submitted the changes to the documentation.

**Comment by BeksOmega** [comment]
> I've submitted the changes to the documentation.

Documentation is good! I'm going to leave this open until the EOQ release to make sure we remember to release the changes.

**Comment by BeksOmega** [comment]
Released with v10.2!

**Comment by YoshiRulz** [comment]
Could you add another line to [*Inputs and Fields in JavaScript*](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#inputs_and_fields_in_javascript) explaining that `appendEndRowInput` without an argument is equivalent to a newline in a message string in JSON? I must have spent an hour trying to get mixed JSON+programmatic to flow how I wanted before I realised that.
