### ISSUE TITLE
setWarningText(null, id) has no function

### ISSUE THREAD

**Issue by willzhanglala** [google/blockly#7362]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

setWarningText(null, id) doesn't delete message for the id.

### Reproduction steps

1.  block.setWarningText('something', 'abc')
2. wait a minute
3.  block.setWarningText( null, 'abc')

block still has warning

Expected:
block should not have a warning

**Comment by maribethb** [comment]
Thank you for filing this issue! It has been fixed and will be updated in the next release.
