### ISSUE TITLE
content error

### ISSUE THREAD

**Issue by Jayce-liang** [google/blockly#7366]
### Location

https://developers.google.com/blockly/guides/configure/web/configuration_struct

### Type

- [X] Text
- [ ] Image or Gif
- [ ] Other

### Suggested content

![image](https://github.com/google/blockly/assets/76100439/a2df6ece-52a4-4f03-8317-50f26964f2a6)

The content of the red box in the picture should be the toolbox, right?

**Comment by BeksOmega** [comment]
Thanks for the report! Fixed and should be up in the next day or two =)
