### ISSUE TITLE
typo: "codefor" -> "code for"

### ISSUE THREAD

**Issue by montmorill** [google/blockly#7367]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

[/core/generator.ts#L256](https://github.com/google/blockly/tree/develop/core/generator.ts#L256)
```ts
`${this.name_} generator does not know how to generate code` +
  `for block type "${block.type}".`,
```
it will become "codefor" instead of "code for" after joined.

**Comment by montmorill** [comment]
oops.

**Comment by goldenkairos** [comment]
Can I please be assigned to work on this issue?

**Comment by BeksOmega** [comment]
Go for it @goldenkairos  =)
