### ISSUE TITLE
Dragging stack out of function input list doesn't remove all inputs

### ISSUE THREAD

**Issue by johnnesky** [google/blockly#7381]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When you try to drag a stack of function definition inputs out of the input container, some inputs will remain.

### Reproduction steps

1. Go to: https://blockly-demo.appspot.com/static/tests/playgrounds/advanced_playground.html
2. Drag a new function into the workspace.
3. Open up the input list editor.
4. Add at least two inputs to the input list container. ("x" and "y")
5. Click and drag the first input out from the container, taking the entire stack of inputs with it.
6. At least one copy of the "x" input still remains in the container, in addition to the dragged stack!
7. You can drag the original stack back into the list of inputs and repeat the process to rapidly double the number of copies of the first input.
8. If the current inputs include "y" and "z" but no "x", and you drag the entire stack away, the remaining inputs will include "x" even though it wasn't previously included.
9. Find a large stack of inputs that are not attached to the container, and try dragging from the middle of the stack. A similar phenomenon will leave junk inputs attached to the stack.
10. Sometimes I can remove a chunk of inputs from a stack at a time, but usually all but one of the removed inputs is replaced with an "x" input.

### Screenshots

![image](https://github.com/google/blockly/assets/54517768/fe8ea938-b9e1-44e1-b682-6de83be2f133)

**Comment by laurensvalk** [comment]
Can confirm. Here is a video of some of the scenarios described above.

https://github.com/google/blockly/assets/12326241/a90bca8c-a326-4f80-a407-09900ab8648a

**Comment by johnnesky** [comment]
Confirmed that this is fixed now, thanks to https://github.com/google/blockly/pull/7384
