### ISSUE TITLE
blockly load performance

### ISSUE THREAD

**Issue by CaffeMrDe** [google/blockly#7395]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

Hello, blockly developers. I would like to ask a performance question, if there are 500 blocks that need to be loaded, in the current version it is very slow and takes 25s. I capture performance hotspots on the rendering of the browser. Do I have another way to optimize loading speed? And how can I improve loading time? Thanks!

### Reproduction steps

1. Custom blocks
2. Batch generate 500 identical blocks in the form of JSON
3.Wait 25s for the graph block to be generated

### Stack trace

```shell
462.2  ms 54.5 %	691.0  ms 81.5 %	 getRelativeXY$$module$build$src$core$utils$svg_math
202.6  ms 23.9 %	202.6  ms 23.9 %	 getAttribute
87.1  ms 10.3 % 	778.1  ms 91.8 %	 getRelativeToSurfaceXY
29.0  ms 3.4 %	        777.2  ms 91.7 %	 moveConnections
26.2  ms 3.1 %	        26.2  ms 3.1 %	         RegExp: translate\(\s*([-+\d.e]+)([ ,]\s*([-+\d.e]+)\s*)?
```

### Screenshots

![image](https://github.com/google/blockly/assets/35086726/234dffa6-2fc8-436b-8894-3fc9db250aa7)

### Browsers

Chrome desktop

**Comment by CaffeMrDe** [comment]
My Deviecs:
cpu:   Intel(R) Core(TM) i5-9400 CPU 
ram:  16.0 GB
os:     win10

I'm using blockly version 10.0.0. And I found a phenomenon that if you create 500 consecutive blocks through the XML DOM, the performance will be slower, but if you render 500 blocks together and divide 50 blocks into 10 times, the performance will be greatly improved.

The strategy of rendering in batches is fine, but I'm thinking about how to connect batched blocks using the API. How do you use the API interface to connect blocks？Thanks.

**Comment by CaffeMrDe** [comment]
I've found the interface for the block connection, which is very hidden. In addition, I render blocks and unified render blocks in batches, and there is a performance difference. I think it should be a bug.

**Comment by CaffeMrDe** [comment]
`
function createDom1(count)  // create `count` block
{
   const doc = document.implementation.createDocument(
      "https://developers.google.com/blockly/xml",
      "xml",
      null,
      );

    var blockNum = count; // sum - 1 
    const block = document.createElement("block");
    block.setAttribute("type", "lbl");
    block.setAttribute("fields", {LBL_ID: 0});
    block.setAttribute("x", "50");
    block.setAttribute("y", "0");
    block.setAttribute("id", blockCount);

    var cnext =[];
    var cblock1 = [];
    ++blockCount;
    for(var i = 0; i < blockNum; i++)
    {
      cnext[i] = document.createElement("next");
      cblock1[i] = document.createElement("block");
      cblock1[i].setAttribute("fields", {LBL_ID: 0});
      cblock1[i].setAttribute("type", "lbl");
      cblock1[i].setAttribute("id", blockCount);
      ++blockCount;
      cnext[i].appendChild(cblock1[i]);
    }

    for(var i = 1; i < blockNum; i++)
    {
      cblock1[i -1].appendChild(cnext[i]);
    }

    block.appendChild(cnext[0]);
    doc.documentElement.appendChild(block);
    var serializer = new XMLSerializer();
    var xmlString = serializer.serializeToString(doc);

    const dom = Blockly.utils.xml.textToDom(xmlString);  
    Blockly.Xml.domToWorkspace(dom, Blockly.getMainWorkspace());
}

// create 500 block,  It takes 16s
createDom1(500);

// create 10 * 50 block It takes 2s
for(var i = 0; i < 10; ++i)
  createDom1(50);
`

**Comment by BeksOmega** [comment]
@CaffeMrDe Could you [save a performance profile](https://developer.chrome.com/docs/devtools/performance/reference/#save) as JSON and send it to us? That would really help with figuring out where the slowdown is coming from!

**Comment by BeksOmega** [comment]
Hello @CaffeMrDe I don't think the trace actually uploaded :/ could you try uploading it again?

**Comment by CaffeMrDe** [comment]
[Trace-20230830T161944.txt](https://github.com/google/blockly/files/12473393/Trace-20230830T161944.txt)
Is it?

**Comment by BeksOmega** [comment]
> [Trace-20230830T161944.txt](https://github.com/google/blockly/files/12473393/Trace-20230830T161944.txt) Is it?

Thanks for the upload! but this doesn't show a 25 second load time, it shows an ~1.5 second load time, which is what we expect.

Thank you for taking the time to report! If you have any further comments feel free to reopen but for now I'm going to close this =)
