### ISSUE TITLE
Logging API for Blockly

### ISSUE THREAD

**Issue by maribethb** [google/blockly#7396]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Problem

Developers don't like when we spam warnings/messages in their developer console. e.g. many requests in https://github.com/google/blockly/issues/4369

Also, developers might want to see deprecation notices when testing, but not have them in their production sites.

### Request

We could add a logging API that lets developers choose if debug, info, warning, or error messages should be logged. The default could be warning and above or info and above are displayed. We should probably match today's behavior for the default, but we might want to argue over whether some current messages are warnings or info messages.

We also have some places where there are debugging messages left in the code but effectively commented out or disabled, and you have to modify the code itself if you want to display the messages while debugging e.g. a custom field. These could be converted to use the logging framework to make it friendlier for developers creating plugins.

We should take care that stack traces and any info provided by the browser during an error or crash is preserved. This may mean that we need to modify the `console.log` functions directly, instead of just providing wrapper functions.

### Alternatives considered

We could use an existing package like https://www.npmjs.com/package/loglevel. This is already a lightweight library, but it still includes some extra bells and whistles we probably don't need (like IE support) and it uses a global object which we probably don't want. Additionally, we tend to avoid hard dependencies in core.

**Comment by BeksOmega** [comment]
Is this solved by recommending people remove log messages as part of their bundling process?

**Comment by maribethb** [comment]
The main source of log spam was fixed (the no message string found... issue) and for everything else, making it the developer's responsibility to strip logs seems fine unless someone asks for this specifically.
