### ISSUE TITLE
Spell checking in text input field

### ISSUE THREAD

**Issue by carloslfu** [google/blockly#74]
Hi Neil.
When i create a custom block with a text input with `Blockly.FieldTextInput`, should be a way to disable spell checking in case of not need it.

![image](https://cloud.githubusercontent.com/assets/5993168/6372704/fb4e0328-bcd3-11e4-9f57-54c7a95b5a64.png)

**Comment by NeilFraser** [comment]
Fixed.  After creating a FieldTextInput, you can now call its .setSpellcheck(false) if you want to turn off spellchecking (defaults to true).  Function definition blocks have been changed accordingly.
