### ISSUE TITLE
Changing variable on creating a block makes it hard to connect, insertion marker has wrong shape

### ISSUE THREAD

**Issue by laurensvalk** [google/blockly#7410]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

This happens with blocks similar to `variables_set`, with an extension that creates and sets a new variable on picking the block from the toolbox.

In some cases, the newly created block won't connect when hovering in the normal position. It seems that the shape change isn't always fully registered. Hovering somewhere in/above the parent block sometimes gets the insertion marker in the right place.

After dropping it on the workspace and attempting to reconnect, it always works. The video below illustrates this better.

One symptom that is always visible is the insertion marker, which takes the original shape as it was on the toolbox. In some cases it still connects despite the wrong shape though, so this may not be all of it.

In reproducing this, I noticed that the likelihood of this occurring is a bit lower compared to a larger app, so maybe other events make this more/less likely.

I have tested this on Blockly 9.3, 10.0, and 10.1.2. It seems to happen on any browser.

### Reproduction steps

Pick any Blockly app, e.g. `blockly-samples/examples/sample-app-ts. This happens to any block type that updates a variable on create. In this test I've modified `variables_set` to keep it minimal.

I used Zelos, but it seems to happen on other renderers too.

Tweak `variables_set` slightly to:
- Add a default variable name (`item`)
- Add an extension:

```js
// Same as standard blocks, except where indicated by comments
const variableSet = {
  type: "variables_set",
  message0: "%{BKY_VARIABLES_SET}",
  args0: [
    {
      type: "field_variable",
      name: "VAR",
      variable: "item" // fixed name for testing
    },
    {
      type: "input_value",
      name: "VALUE",
    },
  ],
  previousStatement: null,
  nextStatement: null,
  style: "variable_blocks",
  tooltip: "%{BKY_VARIABLES_SET_TOOLTIP}",
  helpUrl: "%{BKY_VARIABLES_SET_HELPURL}",
  extensions: ["contextMenu_variableSetterGetter", "variable_set_rename"], // added rename extension
};
```

Use any extension that updates the variable name.  Here is a minimal version for testing:

```js
Blockly.Extensions.register(
  "variable_set_rename",
  function (this: Blockly.Block) {
    this.setOnChange((event: Blockly.Events.Abstract) => {
      if (this.isInFlyout) {
        return;
      }
      if (
        event.type === Blockly.Events.BLOCK_CREATE &&
        (event as Blockly.Events.BlockCreate).blockId === this.id
      ) {

        // Create the variable we'll use in this test once.
        const name = 'insertion marker is too small for this name';
        if (!this.workspace.getAllVariableNames().includes(name)) {
          this.workspace.createVariable(name);
        }

        // Find the field and variable, and set it.
        const longVar = this.workspace.getAllVariables().find((v) => v.name === name);
        const varField = this?.getField("VAR") as Blockly.FieldVariable;
        if (!varField || !longVar) {
          return
        }
        varField.setValue(longVar.getId());

        // At this point, the block is (sometimes) hard to connect. The
        // insertion marker also has the wrong shape, which may be an indicator
        // of this.
        
        // Forcing a re-render seems to make no difference.
        (this as Blockly.BlockSvg).render(); 
      }
    });
  }
);
```

Add to toolbox if it isn't already:

```js
    {
      'kind': 'category',
      'name': 'Variables Custom',
      'categorystyle': 'variables',
      'contents': [
        {
          'kind': 'block',
          'type': 'variables_set',
        },
      ],
    },
```

### Screenshots

https://github.com/google/blockly/assets/12326241/f99e5202-517b-4e65-8ed9-8c4ec1702f6e

**Comment by maribethb** [comment]
Hello! This is happening because you are changing the shape of a block in the middle of the drag, which is not allowed.

Extensions already run when a block is created. So you can move the logic that is currently in your onChange handler into a regular extension and it will run when the block is created, before the drag and insertion marker logic takes place. That should fix this problem.
