### ISSUE TITLE
Dragged block doesn't get focus first

### ISSUE THREAD

**Issue by clementcontet** [google/blockly#7411]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When we drag a block, it doesn't get the browser focus first, and thus can be in background, hidden by other blocks.

### Reproduction steps

1. Get a workspace with two blocks
2. Select (click on) first block so that it gets focus and send the second one to background
3. Drag the second block (without selecting it first) and move it near the first block
4. The second block, while dragged, is displayed behind the first one

### Screenshots

Tested right now on https://developers.google.com/blockly:
https://github.com/google/blockly/assets/7261426/7242614b-1115-4736-9437-34400f167599

### Browsers

Chrome desktop

**Comment by BeksOmega** [comment]
I think we forgot to reroll https://github.com/google/blockly/pull/6874

**Comment by BeksOmega** [comment]
Fixed by #6874
