### ISSUE TITLE
Change `isMutator` to `isMiniWorkspace`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7422]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

The block dragger looks at `isMutator` to make sure it's converting between workspace units and pixel units correctly for a mini workspace. This is confusing because not all mini workspaces are necessarily mutators.

### Request

Change `isMutator` to `isMiniWorkspace`

### Alternatives considered

Add an additional API. Or just leave as-is assuming people won't use mini workspaces for things besides mutators.

### Additional context

https://github.com/google/blockly/issues/7421

**Comment by rachel-fenichel** [comment]
Let's leave this as-is. I think it's a small corner of our API, but don't want to change it just for naming purposes in case it *is* in use. For clarity you could update the docstrings on `internalIsMutator` and `isMutator`:

```
  /**
   * Is this workspace the surface for a mutator?
   *
   * @internal
   */
  internalIsMutator = false;

  /** Is this workspace the surface for a mutator? */
  get isMutator(): boolean {
    return this.internalIsMutator;
  }
  ```
