### ISSUE TITLE
First block from flyout matches ID and subsequent ones do not

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7432]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When you drag a block from the flyout for the first time, the block has the same ID as the block in the flyout. For subsequent blocks it has a different ID.

The first block has the same ID because we are serializing the flyout block and deserializing it into the main workspace (ids are included in serialization). Subsequent blocks do not have the same ID, because during deserialization the ID conflicts with the block that already exists in the workspace, so it gets a new ID.

This causes problems with unit tests because we have multiple blocks on the page that have the same `[data-id]` attribute.

Instead it would be nice if all blocks dragged from the flyout have a different ID than their originator.

We should add a `saveIds` parameter to `Blockly.serialization.blocks.save` that allows us to save blocks without IDs. If we save the blocks in the flyout like this and then deserialize them, we ensure that the IDs are always different.

### Reproduction steps

1. Run `npm run start` from the root of the repository.
2. Switch from "Category toolbox" to "Simple toolbox"
3. Drag the if-else block from the flyout.
4. Inspect the page for both the block in the flyout and the block on the main workspace. Observe how the `data-id` attribute is the same for both.

## To Fix

1) Run the reproduction steps and make sure you can reproduce the issue.
2) Add a new optional `addIds` parameter to the [save function](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/serialization/blocks.ts#L82) that defaults to `true`.
3) Change the logic to only save the Id if `addIds` is true.
4) Pass the parameter through all the recursive calls. Namely `saveInputBlocks` and `saveNextBlocks`.
5) Modify the [flyout code](https://github.com/google/blockly/blob/344861698e65c3fc5f05db000c01cff2155f56ff/core/flyout_base.ts#L1216) to pass `addIds: false` to `save`.
6) Run the reproduction steps again and make sure the blocks have different IDs.

**Comment by bsampada7** [comment]
I would like to work on this, if I don't get assigned for the first one

**Comment by KrautRock** [comment]
@BeksOmega I am interested in working on this, thanks!

**Comment by rl-dhanush** [comment]
@BeksOmega I am interested in working on this, thanks !!

**Comment by patelb268** [comment]
@maribethb I would like to work on these issue

**Comment by Yitao-Wang01** [comment]
@BeksOmega I am interested in working on this, thanks!

**Comment by Leonora-cat** [comment]
I am interested in this issue!

**Comment by arinzeng** [comment]
I am interested in working on this!

**Comment by patelb268** [comment]
@BeksOmega  I would like to work on this issue

**Comment by nithyabach11** [comment]
I'd like to work on this!

**Comment by patelb268** [comment]
@BeksOmega I would like to work on this issue

**Comment by vprerana** [comment]
Hi I would like to work on this issue

**Comment by treypisano** [comment]
Hi, I'm interested in working on this!

**Comment by BeksOmega** [comment]
@treypisano go for it! If you have any questions don't hesitate to reach out =)
