### ISSUE TITLE
Zelos renders wrongly when dynamically adding fields

### ISSUE THREAD

**Issue by lukeplays33** [google/blockly#7442]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

when using the "Zelos" render adding dynamic fields causes the render to render completely white.

this doesn't happen with the other renders.

### Reproduction steps

1. set workspace render to "Zelos".
2. create a block with an text or number input.
3. add a field (e.g. dropdown) to it outside of the definition function.
4.

### Screenshots

https://github.com/google/blockly/assets/54947833/0839e2fb-00a6-4622-a90b-3b645066f4a4

### Browsers

Chrome desktop

**Comment by maribethb** [comment]
Hi Luke,

We're not quite sure what's going on here. Could you provide your block definition and mutator code for us? Also, if you could reproduce this with any of the built-in blocks, that would also be helpful to know. Thanks!

**Comment by lukeplays33** [comment]
Hi @maribethb.

sure here it is:

Blockly.Blocks['math_number'] = {
  init: function() {
    this.appendDummyInput('dummy')
        .appendField(new Blockly.FieldNumber(0), "NAME")
        .appendField(new Blockly.FieldDropdown([["cm","cm"], ["mm","mm"], ["in","in"], ["px","px"], ["pt","pt"], ["pc","pc"], ["em","em"], ["ex","ex"], ["ch","ch"], ["rem","rem"], ["vw","vw"], ["vh","vh"], ["vmin","vmin"], ["vmax","vmax"], ["%","%"], ["deg","deg"], ["s","s"],['no unit','nt']]), "unit");
    this.setOutput(true, 'Number');
    this.setColour('%{BKY_MATH_HUE}');
 this.setTooltip("A number");
 this.setHelpUrl("");
  },updateBlock: function(block) {
		block.removeInput('dummy', /* no error */ true);
		
		if(window['variableType'] == 'css') {
			 block.appendDummyInput('dummy')
        .appendField(new Blockly.FieldNumber(0), "NAME")
        .appendField(new Blockly.FieldDropdown([["cm","cm"], ["mm","mm"], ["in","in"], ["px","px"], ["pt","pt"], ["pc","pc"], ["em","em"], ["ex","ex"], ["ch","ch"], ["rem","rem"], ["vw","vw"], ["vh","vh"], ["vmin","vmin"], ["vmax","vmax"], ["%","%"], ["deg","deg"], ["s","s"],['no unit','nt']]), "unit");

			block.setFieldValue('nt','unit');
		} else {
			 block.appendDummyInput('dummy')
        .appendField(new Blockly.FieldNumber(0), "NAME");
		}
}
};

the upadteBlock functions gets called outside of the workspace, when the user switches from a CSS variable to JS variable.
depending on the content it adds or removes the "dummy" input.

as far as i was able to check it doesn't happen with the default blocks.

**Comment by rachel-fenichel** [comment]
Okay, so you want the number block to have a number field (which it already does), and then you want it to sometimes have a `units` dropdown. In both cases, you'll have a dummy input, but one has an additional field.

Where are you calling `updateBlock` from?

**Comment by lukeplays33** [comment]
it gets called from this block:
Blockly.Blocks['create_variables'] = {
  init: function() {
    this.appendValueInput("NAME")
        .setCheck(null)
        .appendField("initialize")
        .appendField(new Blockly.FieldDropdown([["css","css"], ["javascript","js"]],this.validate), "type")
        .appendField(new Blockly.FieldTextInput("name",this.textValidate), "NAME")
        .appendField("variable to");
    this.setColour('%{BKY_VARIABLE_HUE}');
 this.setTooltip("Defines a new CSS or JavaScript variable");
 this.setHelpUrl("");
  },textValidate: function (newValue) {
		if(!getComputedStyle(parent.document.documentElement).getPropertyValue('--' + newValue) == '') {
			this.getSourceBlock().setWarningText('Variable name is already in use');
		} else {
			this.getSourceBlock().setWarningText(null);
		}
		
		return newValue;
	},validate: function(newValue) {
  this.getSourceBlock().updateConnections(newValue);
  return newValue;
},updateConnections: function(newValue) {
	if(newValue == 'css') {
		window['variableType'] = 'css';
	} else {
		window['variableType'] = 'js';
	}	

			for (let i of workspace.getAllBlocks(false)) {
				if(i.type == 'create_variables' || !i.updateConnections) {} else {
					i.updateBlock(i);
				}
	}
}
};

when the user changes the selection the updateBlock function is called to remove or add the required inputs.
