### ISSUE TITLE
Animation rendering glitch on JavaFX WebView in recent releases (not present in v9.2.0)

### ISSUE THREAD

**Issue by KlemenDEV** [google/blockly#7444]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When dragging blocks, a strange glitch sometimes happens in the JavaFX WebView window that did not happen in Blockly v9.2.0 but happens in 10.0.x and in 10.1.x.

Unfortunately, the same thing does not happen in the minimal reproducible example I tried to make when executed in Google Chrome. It does not seem that anything special is required for this to start happening in the WebView, however, in Chrome it never happens.

https://github.com/google/blockly/assets/16374228/1b80e0b8-982b-4f77-baa7-2b96120061e3

I understand this could be a problem with JavaFX WebView, but I find it interesting this is used perfectly with previous releases.

---------------------

Updated demo: [demo-with-run.zip](https://github.com/google/blockly/files/12583351/demo-with-run.zip)

To build: `./gradlew build`

To run: `./gradlew run`

Java 17 is needed

**Comment by rachel-fenichel** [comment]
This looks like the mouse pointer is jumping, rather than the animation. To debug more, can you add an event listener on the page that just logs the mouse location, and see if it's changing unexpectedly mid-drag?

**Comment by KlemenDEV** [comment]
The glitch happens the moment dragging is finished. So one grabs the block, moves it to attach and after/at the moment when releasing the mouse cursor, the glitch happens.

I tried this code 

```js
let lastMouseX = null, lastMouseY = null;

document.addEventListener('mousemove', (event) => {
    if (lastMouseX !== null) {
        const distance = Math.sqrt((event.clientX - lastMouseX) ** 2 + (event.clientY - lastMouseY) ** 2).toFixed(2);
        console.log(`X=${event.clientX}, Y=${event.clientY}, Distance=${distance} pixels`);
    }

    lastMouseX = event.clientX;
    lastMouseY = event.clientY;
});
```

but the mousemove event is not firing while dragging Blockly block.

However, I have visually observed the mouse visually, and it seems only the Blockly block moves, while the cursor remains at a fixed location, at least visually.

**Comment by BeksOmega** [comment]
@KlemenDEV would you be able to provide a minimal reproducable example of this using JavaFX? That would be very helpful for debugging!

**Comment by KlemenDEV** [comment]
Here is an example workspace, the minimal needed to get Blockly running on JavaFX webview: [demo.zip](https://github.com/google/blockly/files/12574277/demo.zip)

Here is ZIP of video showing glitches in this  minimal reproducible example: 
[demo_video.zip](https://github.com/google/blockly/files/12574327/demo_video.zip)

The workspace uses Gradle to load JavaFX. Can be opened in IDEA or launched from command line using gradle.

![image](https://github.com/google/blockly/assets/16374228/4e17ec6c-77b4-4961-93a6-2ec1db089e1b)

**Comment by KlemenDEV** [comment]
If you need anything else or help getting the demo up and running, let me know :)

Glad to help to make Blockly work with JavaFX webview properly too.

**Comment by KlemenDEV** [comment]
Additional info. This is not visible in the example video above, but in some cases, when grabbing block connected to another block and disconnecting it, additional insertion marker is shown at incorrect position as can be visible in this screenshot I managed to grab while messing around to see any patterns on when this happens:

![image](https://github.com/google/blockly/assets/16374228/07434290-837b-42df-a516-da567f10eb92)

**Comment by BeksOmega** [comment]
> If you need anything else or help getting the demo up and running, let me know :)
> 
> Glad to help to make Blockly work with JavaFX webview properly too.

Hello! Thank you for writing up the demo =) I cloned it and built it using `./gradlew build` but I'm not sure how to get it to run. If I run `java -jar ./build/libs/BlocklyJava-1.0-SNAPSHOT.jar` I get `no main manifest attribute, in ./build/libs/BlocklyJava-1.0-SNAPSHOT.jar`.

**Comment by KlemenDEV** [comment]
Updated demo: [demo-with-run.zip](https://github.com/google/blockly/files/12583351/demo-with-run.zip)

To build: `./gradlew build`

To run: `./gradlew run`

Java 17 is needed

**Comment by BeksOmega** [comment]
Ran a bisect and found the root cause to be render queueing: https://github.com/google/blockly/pull/6851

So sounds like it's probably an issue on the JavaFX end if they're not properly triggering callbacks before the frame is drawn. I'm going to send this issue back to triage for feedback.

**Comment by KlemenDEV** [comment]
Thanks for bisecting the issue. JavaFX (OpenJFX) uses WebKit "behind the scenes" if it helps the triage team.

In case there is not much that can be done in regard to #6851 as of course the benefit of that PR is much bigger than the need for JavaFX support, could some workaround be implemented for JavaFX at least, maybe togglable by some parameter?

**Comment by BeksOmega** [comment]
If we wanted to it would be technically possible to add a toggle to the render management system that always triggers an immediate render on `queueRender` instead of waiting for the `requestAnimationFrame` callback. But I'll leave it up to other folks whether we want to do that or not!

**Comment by KlemenDEV** [comment]
Alright, hope something like this could be done.

Also if someone knows how I could phrase bug report to the OpenJFX developers, it would be welcome as right now I am not sure what exactly happens "behind the scenes" for this to happen.

**Comment by rachel-fenichel** [comment]
Are we able to detect that we're in JavaFX through the user agent or some other form of inspection? If yes, I'm fine with adding behaviour to always trigger an immediate render. However, I want it to be entirely internal (that is, Blockly decides whether to do it), not something that a developer can set through a function.

**Comment by BeksOmega** [comment]
> Are we able to detect that we're in JavaFX through the user agent or some other form of inspection? If yes, I'm fine with adding behaviour to always trigger an immediate render. However, I want it to be entirely internal (that is, Blockly decides whether to do it), not something that a developer can set through a function.

JavaFX is one of our user agent consts! https://github.com/google/blockly/blob/00d870ee03ffd502984aa2881d6c1d1d1c406596/core/utils/useragent.ts#L74

**Comment by KlemenDEV** [comment]
> If yes, I'm fine with adding behaviour to always trigger an immediate render. However, I want it to be entirely internal (that is, Blockly decides whether to do it), not something that a developer can set through a function.

That would be really neat :)

**Comment by KlemenDEV** [comment]
Thank you!

**Comment by BeksOmega** [comment]
> Thank you!

Change should go out with v10.2 on the 28th!

**Comment by KlemenDEV** [comment]
Would it be possible to rever this fix as the fix now makes Blockly unusable due to: https://github.com/google/blockly/issues/7556?

This fix fixes visual glitch, but introduces much more concerning usability issue reported at https://github.com/google/blockly/issues/7556
