### ISSUE TITLE
setInputsInline fires an incorrect `BlockChange` event during `jsonInit`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7448]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

If you have a block defined in JSOn that explicitly sets its `inputsInline` property, you will get a `BlockChange` event that fires before the `BlockCreate` event when the block is created. This breaks mirroring blocks between workspaces.

### Reproduction steps

1. Add the following code playground right above the [start call](https://github.com/google/blockly/blob/8193cffe774a8bf61a59fa9d2f84afec3ca1abe8/tests/playground.html#L482):
```js
 Blockly.defineBlocksWithJsonArray([
        {
          'type': 'test',
          'message0': '%1',
          'args0': [
            {
              'type': 'input_value',
              'name': 'INPUT_NAME',
            }
          ],
          'inputsInline': true,
        }
      ]);
```
3. Run `npm run start` to start the playground.
4. Check the 'log workspace events' checkbox in the playground.
5. Open the browser console and run the following code.
```js
Blockly.getMainWorkspace().newBlock('test');
```
6. Observe how you get a `BlockChange` event and then a `BlockCreate` event in the console.

You should see a `BlockCreate` event and no `BlockChange` event.

### To Fix

In jsonInit disable events during the call to [`setInputsInline`](https://github.com/google/blockly/blob/8193cffe774a8bf61a59fa9d2f84afec3ca1abe8/core/block.ts#L1663).

**Comment by devbysn** [comment]
Hello @BeksOmega ,

can i work on this?

**Comment by BeksOmega** [comment]
@devbysn go for it! I've assigned you =) We also have [getting started docs](https://developers.google.com/blockly/guides/contribute/get-started) if you need them!
