### ISSUE TITLE
enable clicking fields while in flyout

### ISSUE THREAD

**Issue by maribethb** [google/blockly#7450]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Blocks can have buttons with click handlers on them, but the click handler is never fired when the block is in the flyout. For some types of buttons, developers want to fire the click handler even in the flyout (e.g. code.org would like to be able to open their modal editor via the `edit` button while the block is still in the flyout, or perhaps the blocks-plus-minus plugin would be better if the block could be mutated while in the flyout)

### Request

Allow a field to receive a click event while in a flyout. This is currently never allowed [here](https://github.com/google/blockly/blob/8193cffe774a8bf61a59fa9d2f84afec3ca1abe8/core/gesture.ts#L1173-L1174). One way we could enable this is to have a property on the field `isClickableInFlyout` that defaults to false but is overridable.

### Additional context

n.b. icons are currently allowed to be clicked inside flyouts, though i think they didn't used to be. filing a separate issue about this.

## To Fix

1) Add a function to the [Field class](https://github.com/google/blockly/blob/8193cffe774a8bf61a59fa9d2f84afec3ca1abe8/core/field.ts#L69) called `isClickableInFlyout` have it return `false`.
2) Modify the gesture code to return true if `isClickableInFlyout` returns true, or the block is not in a flyout, or the flyout does not autoclose.

**Comment by maribethb** [comment]
decision: add the property to the `Field` base class, defaults to false, and check that property in the gesture code linked above.

whatever property name we ultimately decide on should also be used for icons (#7451)

**Comment by BeksOmega** [comment]
Fields are already clickable within flyouts, but not flyouts that auto close. If the flyout is always open, then you can edit it no problem. If the flyout auto-closes, the block is added to the workspace instead. Not sure what that means for the current decision.

**Comment by truongductri01** [comment]
@maribethb can I handle this? Would love to learn more about what it means that a block is left in flyout

**Comment by KrautRock** [comment]
@BeksOmega I am interested in working on this

**Comment by Daphne-wu** [comment]
Hello! I am interested in working on this

**Comment by Patty8122** [comment]
@BeksOmega I am interested in this as well!

**Comment by rl-dhanush** [comment]
@BeksOmega I am interested in working on this, thanks !!

**Comment by patelb268** [comment]
@BeksOmega I am interested in working on this, thanks !!
