### ISSUE TITLE
mutator icons are clickable but weird in flyouts

### ISSUE THREAD

**Issue by maribethb** [google/blockly#7451]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Click on the mutator icon of any block while it's in a flyout. The mutator bubble opens but the workspace isn't sized correctly so you can't actually mutate the block (not easily anyway).

Note that in version 10.0.0, you can open the mutator bubble and it is mostly sized correctly and the flyout even resizes to become wider to accommodate the bubble. Still slightly wrong.

In version 9.1.1, you couldn't open the mutator bubble at all. It would just create the block on the workspace, the same as it currently does if you try to click a field or anywhere else on a block while in a workspace.

I would say that maybe you shouldn't be able to click an icon while inside the flyout, except I just filed #7450 . So I think we should let icons decide whether or not they should be clickable inside flyouts. and the built-in mutator icon probably shouldn't be.

### Reproduction steps

1. Open Procedures category of toolbox
2. Click gear icon
3. See how it's weird

### Screenshots

current

![Screenshot 2023-08-29 at 1 48 15 PM](https://github.com/google/blockly/assets/8573958/c143e5ee-f685-42e1-a4b0-fdec4f1dd1c6)

v10.0.0
![Screenshot 2023-08-29 at 1 51 12 PM](https://github.com/google/blockly/assets/8573958/2a00c87b-8194-4be3-b77c-7924bb18ce53)

**Comment by maribethb** [comment]
decision: add a property `isClickableInFlyout` (or whatever matches the decision for fields in #7450) to the mutator interface/base class to determine behavior, and set it to false for mutator icons

also note: comment icons can be clicked, but the bubble doesn't open. but it doesn't follow the behavior of fields where the block gets created. we should make this consistent by either allowing the bubble to open, or making the icon not clickable.

**Comment by BeksOmega** [comment]
I think if you don't want your icon to open in a flyout, you should just add that logic to `onClick`, which is already overrideable.

**Comment by maribethb** [comment]
> I think if you don't want your icon to open in a flyout, you should just add that logic to `onClick`, which is already overrideable.

we discussed offline and decided to add the function for two reasons:
1) consistency with fields api
2) consistency with blocks - if you click on an area of a block where "nothing happens" the block gets created in the workspace
