### ISSUE TITLE
How to post questions.?

### ISSUE THREAD

**Issue by bhs67** [google/blockly#7452]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Problem

I just discovered Blockly - very useful.  It is not clear to me how to post questions.  Please advise. <cte677@gmail.com>

### Request

How to post questions?

**Comment by cpcallen** [comment]
Answered in #7453.

**Comment by bhs67** [comment]
I've been there.  Attached is what I see.  
![bl1](https://github.com/google/blockly/assets/18146997/b37ef5ef-a153-4f4d-9d05-d0492c4593d9)

**Comment by BeksOmega** [comment]
https://support.google.com/groups/answer/1046523?hl=en

The button is here! 
![image](https://github.com/google/blockly/assets/25440652/6a2cfaf3-e06f-42e8-9018-d64f1b7b2e23)

Best of luck =)
