### ISSUE TITLE
How to post questions.?

### ISSUE THREAD

**Issue by bhs67** [google/blockly#7453]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Problem

I just discovered Blockly - very useful.  It is not clear to me how to post questions on this forum.  

It is also not clear how to search "how to ask questions".

I have extensive experience writing code and posting on forums.

Please advise. <cte677@gmail.com>

### Request

How to post questions?

**Comment by cpcallen** [comment]
Hi @bhs67.  You should post questions about Blockly to the [the Blockly forum on Google Groups](https://groups.google.com/g/blockly).  You'll need to sign in using your Google account (e.g your `@gmail.com` address) in order to be able to post.

**Comment by bhs67** [comment]
I posted a question yesterday - https://groups.google.com/g/blockly/c/cjFNWsIl1ak - no response.  Please advise.  Thanks!

**Comment by maribethb** [comment]
Hello,

We aim to answer all questions within 2 business days. We are a small engineering team; please be patient with us and someone will get back to you soon. Thank you,

Maribeth

**Comment by bhs67** [comment]
My apologies.  I did not realize that.  Thanks!

**Comment by bhs67** [comment]
I received a Blockly email ... don't know why?  

It is titled "need help with a validator on a fieldTextInput that triggeres after entire string is entered" from "'Ivan Gospodinov' via Blockly <blockly@googlegroups.com>"

**Comment by BeksOmega** [comment]
If you go to your membership settings you can change your subscription to not receive emails:
![image](https://github.com/google/blockly/assets/25440652/bfe9f622-e2b7-40f0-9356-03795385112f)

**Comment by bhs67** [comment]
For choices I see ... Each email ... Digest ... Abridged ... No email.  I don't see "My email".

**Comment by bhs67** [comment]
For choices I see ... Each email ... Digest ... Abridged ... No email. I don't see "My email".

**Comment by BeksOmega** [comment]
If you have further questions about how to use google groups I would check the support center! https://support.google.com/groups/?hl=en#topic=9216

**Comment by bhs67** [comment]
I cannot find that info at https://support.google.com/groups/?hl=en#topic=9216.  

For Subscription choices I see --- Each email ... Digest ... Abridged ... No email ---. I do not see "My email".  What do I change so I receive only "My Conversations"?  Thanks!

**Comment by bhs67** [comment]
Ok.  I'm surprised that no one has asked this question.  I'll take a chance and select, "No email".  Hopefully I'll still get emails from Conversations I post.  Thanks for the prompt responses.
