### ISSUE TITLE
Add a `getTargetWorkspace` method to flyout_base.ts

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7461]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Sometimes flyout subclasses need to access the target workspace, but currently it is inaccessible.

### Request

1) Add a method that to the [flyout base class](https://github.com/google/blockly/blob/8193cffe774a8bf61a59fa9d2f84afec3ca1abe8/core/flyout_base.ts) called `getTargetWorkspace` that returns the target workspace..

### Alternatives considered

N/A

### Additional context

Part of https://github.com/google/blockly/issues/7215

**Comment by bhaveshvasnani** [comment]
Hi @BeksOmega! Is this issue up for grabs? Could I please work on this to familiarize myself better with this project so that I could help with more issues going forward?

**Comment by BeksOmega** [comment]
Hiya sorry for the late reply @bhaveshvasnani ! This issue is actually being saved for an event we're running called [Grace Hopper Open Source Day](https://anitab-org.github.io/open-source-day/)! It is meant to help young girls and non-binary technologists make their first contributions to open source =)

If you still want to contribute we have some good [help wanted issues](https://github.com/google/blockly/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) that aren't being saved for the event!

**Comment by bhaveshvasnani** [comment]
Thanks @BeksOmega for letting me know. Yes definitely, I'll check out the other issues.

**Comment by ivalkshfoeif** [comment]
Hi @BeksOmega , I'd like to work on this issue

**Comment by BeksOmega** [comment]
@ivalkshfoeif Go for it :D
