### ISSUE TITLE
Remove `@internal` tag from `isDragTowardWorkspace`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7462]
🚧⚠️🚧 This issue is being saved for **Grace Hopper Open Source Day**. 🚧⚠️🚧 An event we're running to help girls and non-binary technologists make their first contributions to open source! Please see our list of [help wanted issues](https://github.com/google/blockly/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+-label%3A%22ghc-osd%22) if you'd like to contribute! 

---

### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

`isDragTowardWorkspace` is part of the `I_Flyout` interface. Having it marked as `@internal` means that subclasses of `Flyout` can't easily override it. This makes it difficult for external developers to create custom flyouts.

### Request

Remove the `@internal` tag from `isDragTowardWorkspace` in `Flyout`, `FlyoutVertical`, and `FlyoutHorizontal`

### Alternatives considered

N/A

### Additional context

Part of https://github.com/google/blockly/issues/7215

**Comment by saymedgm** [comment]
@BeksOmega can you please assign me this issue

**Comment by NikoRaisanen** [comment]
Hey @BeksOmega! I just opened a PR for this issue, let me know if you want any changes

**Comment by ramyaram2092** [comment]
I would like to work on this

**Comment by KrautRock** [comment]
@BeksOmega I am interested in working on this, thanks!

**Comment by ajita86** [comment]
Hi! Can I be assigned to this?

**Comment by ramyaram2092** [comment]
@BeksOmega  I think you have assigned this to a person that has commented two weeks ago

**Comment by Patty8122** [comment]
@BeksOmega I am interested in this as well!

**Comment by Shreyagundu** [comment]
@BeksOmega I am interested in this as well! Can I be assigned to this?
