### ISSUE TITLE
Shadow blocks inside statements with mutator input get rendered in insertion marker

### ISSUE THREAD

**Issue by laurensvalk** [google/blockly#7466]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When a mutator adds an input with a shadow block, it gets rendered in the statement insertion marker.

It's not just a visual glitch. It accepts connections, so it can turn into a real block. This makes it an orphaned shadow block, which causes a crash when clicked. It seems somewhat related to https://github.com/google/blockly/pull/7384 and the related recent fixes.

### Reproduction steps

The following example is a bit contrived but offers a minimalist way to reproduce. See context below for a more sensible use case. This can be reproduced without the plugin as well; using it just provides a ready-made block with a mutator that exhibits the issue.

1.  Use blockly-samples/plugins/block-plus-minus
2.  Apply the following patch:

```diff
diff --git a/plugins/block-plus-minus/package.json b/plugins/block-plus-minus/package.json
index 6d74dd98..d7116253 100644
--- a/plugins/block-plus-minus/package.json
+++ b/plugins/block-plus-minus/package.json
@@ -41,13 +41,13 @@
   "devDependencies": {
     "@blockly/dev-scripts": "^2.0.1",
     "@blockly/dev-tools": "^7.0.3",
-    "blockly": "^10.0.0",
+    "blockly": "^10.1.3",
     "chai": "^4.2.0",
     "mocha": "^10.2.0",
     "sinon": "^9.0.1"
   },
   "peerDependencies": {
-    "blockly": "^10.0.0"
+    "blockly": "^10.1.3"
   },
   "publishConfig": {
     "access": "public",
diff --git a/plugins/block-plus-minus/src/if.js b/plugins/block-plus-minus/src/if.js
index 10f6cd24..3bb8ca16 100644
--- a/plugins/block-plus-minus/src/if.js
+++ b/plugins/block-plus-minus/src/if.js
@@ -142,6 +142,14 @@ const controlsIfMutator = {
         .appendField(Blockly.Msg['CONTROLS_IF_MSG_ELSEIF'])
         .appendField(
             createMinusField(this.elseIfCount_), 'MINUS' + this.elseIfCount_);
+
+    const input = this.getInput('IF' + this.elseIfCount_);
+    if (input.connection) {
+      const field = '<field name="BOOL">TRUE</field>';
+      const xml = `<shadow type="logic_boolean">${field}</shadow>`;
+      input.connection.setShadowDom(Blockly.utils.xml.textToDom(xml));
+    }
+
     this.appendStatementInput('DO' + this.elseIfCount_)
         .appendField(Blockly.Msg['CONTROLS_IF_MSG_THEN']);

```

3. Install and run the demo for this plugin. The video illustrates the following steps.
4. Attach the block to an existing statement on the workspace.
5. Add some inputs using `+`. Set the bool value to `FALSE` to make the difference easier to see
6. Drag it around. Observe shadow blocks rendered in the insertion marker (note that their value is `TRUE`).
7. Drag it around more and catch the rendered shadow to become a real, orphaned shadow block.

**context**

The aforementioned demo isn't particularly useful but shadow blocks in mutator statements can have good use cases. Consider, for example:
- a `print` block with a `+/-` like mutator that adds additional inputs, each with a `text` shadow block for easy text entry
- a procedure caller with shadow inputs. See [this link](https://groups.google.com/g/blockly/c/uxos41JxjDE/) for context and a response from Neil.

**context 2**

Other than this issue, shadow block in mutators work great, so I'm hoping this is a valid use case. For some reason my own application does not reproduce step `7`, so I have only the visual glitch.

**on json vs xml**

This seems unrelated because the same issue reproduces when replacing the patch above with:

```js
    const input = this.getInput('IF' + this.elseIfCount_);
    if (input.connection) {
      // Create the new block.
      const boolBlock = Blockly.serialization.blocks.append(
          {
            type: 'logic_boolean',
          },
          this.workspace,
      );

      // Convert to shadow block and attach.
      boolBlock.setShadow(true);
      input.connection.connect(boolBlock.outputConnection);
    }
```

But this has a second issue: it renders visually different, and shows the bool block's border rect until you refresh the page to reload it as a normal shadow block. Edit: a `render()` *after* `setShadow` and *before* `connect` makes it look correctly (but the main issue persists). Edit2: `setShadow` should perhaps always call `renderEfficiently`.

### Screenshots

https://github.com/google/blockly/assets/12326241/3ee4cb78-6bf1-489b-89dd-fa0914c74d64

**Comment by BeksOmega** [comment]
Currently you can check if the block `isInsertionMarker()` during deserialization and not add shadows if that's the case. But if we reimplement https://github.com/google/blockly/issues/7316 then it would become impossible (without additional changes), because `isInsertionMarker` would be set to `true` after the extra mutation state is deserialized.

**Comment by laurensvalk** [comment]
Thanks for the hint! This gives a couple of variations. In the context of this example:

0. The original case, which also triggers the bug above.

https://github.com/google/blockly/assets/12326241/2a768cf3-ffee-4da7-b287-b7a90f5f7ac0

1. Don't insert the `bool` blocks if the `if` block is an insertion marker.

    This avoids the bug, but naturally the marker has a smaller shape now (which is OK here, but could be an issue). Or maybe this is the expected result [because normal inputs also aren't rendered in the insertion marker](https://github.com/google/blockly/assets/12326241/c6955c87-8c19-48ec-b0bc-b90f26ad1dca)?

https://github.com/google/blockly/assets/12326241/71b3cdfd-b5ba-4d5f-ba1b-270ddd124aa3


2. Insert the `bool` blocks, but set them to insertion marker when the `if` block is an insertion marker.

    Avoids the duplication issue and has the right shape. This seems to be the best for now.


https://github.com/google/blockly/assets/12326241/14228f6e-9500-4025-9241-c5ec96e76d38

> But if we reimplement https://github.com/google/blockly/issues/7316 then it would become impossible (without additional changes), because isInsertionMarker would be set to true after the extra mutation state is deserialized.

Inspired by variant 2, perhaps child blocks could be set as insertion markers as well. (But somehow ensure that this is not applied to blocks already on the workspace, when considering an insertion marker that makes an outer connection).

**Comment by BeksOmega** [comment]
> Inspired by variant 2, perhaps child blocks could be set as insertion markers as well. (But somehow ensure that this is not applied to blocks already on the workspace, when considering an insertion marker that makes an outer connection).

I think this is a good idea! Because this issue could also be triggered by people creating shadow blocks in their `init` method. It doesn't /just/ apply to mutators.
