### ISSUE TITLE
Blockly.serialization.blocks.load mentioned in docs is not a function

### ISSUE THREAD

**Issue by danbopes** [google/blockly#7468]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

In the guide here: https://developers.google.com/blockly/guides/create-custom-blocks/block-paradigms

It mentions `Blockly.serialization.blocks.load({'type': 'factory_base'}, workspace);`

`Blockly.serialization.blocks.load` is not a function

### Reproduction steps

1. Include standard javascript  blockly_compressed.js, blocks_compressed.js, msg/en.js
2. Attempt to call `Blockly.serialization.blocks.load()` (`load` is not on blocks object)

### Screenshots

![](https://i.imgur.com/v0jILrK.png)

**Comment by BeksOmega** [comment]
Hello! The correct method is `Blockly.serialization.blocks.append` I've put in a docs change and it should go up soon =) Thank you for reporting!

**Comment by rachel-fenichel** [comment]
I've removed from triage. Beka, please close this when your change is live.
