### ISSUE TITLE
Modifying a block comment does not fire a block change event

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7480]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

If you type into a block comment, it does not fire a change event. It should.

### Reproduction steps

1. Run `npm run start` to open up the playground.
2. Enable workspace event logging by clicking the checkbox on the left.
3. Load the following JSON into the workspace. By pasting it into the textbox and hitting the "Load" button.
```
{
  "blocks": {
    "languageVersion": 0,
    "blocks": [
      {
        "type": "controls_if",
        "id": "GU6;.7|eVLgZ)A0#JvJv",
        "x": 62,
        "y": 87,
        "icons": {
          "comment": {
            "text": "a comment",
            "pinned": true,
            "height": 80,
            "width": 160
          }
        }
      }
    ]
  }
}
```
4) Open the browser console and clear it.
5) Type into the comment.
6) Observe how no events are fired.

### Additional Info

I'm going to add this as a "good first issue" because I think it is a good one, but I'm not tagging it with "ghc-osd" since we have enough now =)

## To Fix

In the comment icon's [onTextChange method](https://github.com/google/blockly/blob/07fec204bf66589625ad7816a248cf2ae9b5c3b6/core/icons/comment_icon.ts#L219
) fire a change event. You can work off of the example [here](https://github.com/google/blockly/blob/07fec204bf66589625ad7816a248cf2ae9b5c3b6/core/block.ts#L2195).

**Comment by treypisano** [comment]
Hi, can I take a shot at resolving this?

**Comment by BeksOmega** [comment]
@treypisano Go for it =) I've assigned you!

**Comment by treypisano** [comment]
Hi @BeksOmega , I just had a few questions about this issue. I believe that I got the [onTextChange method](https://github.com/google/blockly/blob/07fec204bf66589625ad7816a248cf2ae9b5c3b6/core/icons/comment_icon.ts#L219) to fire the block change event, but there is an issue. This method is only firing when a comment is changed and then there is a MouseDown event, **not** when the text itself is changed. Should this be separated into another issue?

Also, I'm not sure if the old value of the comment is saved (pre-change), so I am just leaving BlockChange.oldValue as null at the moment.

Thanks
