### ISSUE TITLE
Simplify renderer choice

### ISSUE THREAD

**Issue by SebCanet** [google/blockly#7481]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Renderer choice, as inject option, cannot be modified after workspace rendering, unlike theme. We need to dispose workspace and recreate this (and this breaks some plugins), not easy as method.

### Request

Need to create a 'setSomething' for element injected, this way it helps accessibility feature. Renderer modify a lot of thing (color, font size, shape, etc) useful for accessibility.
So a setRendere() function would be useful.

**Comment by BeksOmega** [comment]
This post provides more good context: https://groups.google.com/g/blockly/c/nZj8ZUdVz7M/m/AZif2kmsAgAJ

**Comment by rachel-fenichel** [comment]
I agree that reinjecting should work with the different plugins, but we don't plan to change the logic around changing renderers to work without reinjection. Renderers change enough about Blockly (including the DOM) that reinjecting is the best way to guarantee correctness after a switch.
