### ISSUE TITLE
Events stop firing after failed serialization (JSON)

### ISSUE THREAD

**Issue by michaelnixonau** [google/blockly#7486]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

If you have a failed serialization (JSON), then all Blockly events appear to stop firing.

### Additional Observations
- Other functions seem to be OK. You can still add and modify blocks, generate code, etc.
- It's possible to successfully load another valid JSON file, but events are still stopped.
- An error is thrown when the serialization fails, but the error is thrown at a much lower level (e.g. `new Block()`) than the serialization function.

### Reproduction steps

1. Run `npm run start` to open up the playground.
2. Enable workspace event logging by clicking the checkbox on the left.
3. Open the browser console and observe that events are firing properly.
4. Load the following JSON into the workspace, containing a `controls_if_broken` block which is not defined within the playground.

```
{
  "blocks": {
    "languageVersion": 0,
    "blocks": [
      {
        "type": "controls_if_broken",
        "id": "JR#^CG[88QmWD*uo`3t=",
        "x": 112,
        "y": 87
      }
    ]
  }
}
```
5. Make change(s) to the workspace.
6. Observe that events no longer fire, but other operations are generally fine.

### Stack trace

```shell
Uncaught TypeError: Invalid block definition for type: controls_if_broken
    at new Block (block.ts:257:15)
    at new BlockSvg (block_svg.ts:174:5)
    at WorkspaceSvg.newBlock (blockly.ts:422:10)
    at appendPrivate (blocks.ts:451:27)
    at appendInternal (blocks.ts:402:17)
    at append (blocks.ts:359:17)
    at BlockSerializer.load (blocks.ts:785:7)
    at Module.load (workspaces.ts:82:38)
    at HTMLInputElement.load (playground.html:181:44)
```

**Comment by rachel-fenichel** [comment]
@BeksOmega can you take a look? There's probably a missing try/catch/finally for turning events back on, buried somewhere in serialization.
