### ISSUE TITLE
Modifying the structure of a block does not trigger widgets to be repositioned

### ISSUE THREAD

**Issue by maribethb** [google/blockly#7491]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

If a warning icon is added or removed during field editing, the field is not rendered correctly.

related to the rendering queue and might be related to #7068 ?

### Reproduction steps

1. Open Block Factory
2. Drag two value input blocks into the inputs input. Notice how they each have a warning now due to conflicting names.
3. Change the name of one of the inputs. The warning disappears, and the underlying block is resized. But the text input html element is now in the wrong place because it did not move when the block was resized.
4. Click outside the field to end editing / close the widget div.
5. Change the name back to `NAME`. The warning reappears, causing the same problem again.

### Screenshots

<img width="433" alt="Screenshot 2023-09-14 at 5 39 53 PM" src="https://github.com/google/blockly/assets/8573958/d4f20eaf-1243-48f1-9880-9c71935c3073">

**Comment by BeksOmega** [comment]
Not related to render queueing. Repros back to at least 2020: https://20200123-dot-blockly-demo.appspot.com/static/demos/blockfactory/index.html
