### ISSUE TITLE
Better style for highlighted block

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#750]
Blocks that are currently executing can be highlighted (the orange selection border is unrelated).  This highlighting was programmed in haste and looks lame:
  https://github.com/google/blockly/blob/master/core/block_svg.js#L1236
  https://blockly-demo.appspot.com/static/demos/interpreter/index.html

Let's unleash a UI person to design a nicer effect.  For bonus marks, make it pulsing, or sparkly, or something.  After all, it's the user's end goal so it's important that this looks good.  You've got all of SVG's awesome filters available.  And performance is a non-issue since it's normally one block at a time with nothing else happening.  Also, you can go bleeding edge with the effects since if some idiot browser (IE) doesn't support it, they can fall back to what we currently have.

**Comment by rachel-fenichel** [comment]
We're accepting pull requests!

**Comment by rachel-fenichel** [comment]
Performance does matter a little if they're doing something complicated to execute the code--we have seen cases where performance issues on the blockly side make executing code lag.  But I agree that we can be pretty free with this.

**Comment by pelikhan** [comment]
The currently highlighting filter is quite ugly and not clearly identifiable.

**Comment by sachan13harshit** [comment]
@rachel-fenichel @NeilFraser please assign this issue to me

**Comment by BeksOmega** [comment]
@rachel-fenichel if we change this now is that going to break external folks' tutorials / curriculum?

**Comment by omwagh28** [comment]
Hey @BeksOmega please assign me this issue

**Comment by omwagh28** [comment]
@BeksOmega Please assign me this issue

**Comment by rachel-fenichel** [comment]
> @rachel-fenichel if we change this now is that going to break external folks' tutorials / curriculum?

It would be best to make it easy to keep the existing highlight, and also easy to replace it with a new one. Completely removing the existing highlight could cause issues with existing tutorials.

**Comment by BeksOmega** [comment]
Chatted offline, and we think it's best to have people style via CSS instead of adding more options to the internals of Blockly.

**Comment by NeilFraser** [comment]
That said, it would be great if the community could see some options for what enhanced highlighting could look like and the code needed to achieve this.
