### ISSUE TITLE
need a dynamic control workspace readonly mode

### ISSUE THREAD

**Issue by tinysrc** [google/blockly#7508]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Request

pseudo code
```javascript
workspace.setReadonly(true)
workspace.setReadonly(false)
```

**Comment by maribethb** [comment]
Hey there, thanks for the feature request! Unfortunately there's a lot of work we don't do if a workspace starts in readOnly mode, that would be tricky to make sure we re-enable if you switch it. The most foolproof way of doing this is to re-inject the workspace with the new option, similar to what we suggest you do if you want to change the renderer.
