### ISSUE TITLE
Deletion of a highlighted block makes highlightBlock(id) stop working

### ISSUE THREAD

**Issue by ruslan-simonenko** [google/blockly#752]
When highlighted block is deleted `highlightBlock` stops working.
```javascript
workspace.highlightBlock(id);
// delete that block
workspace.highlightBlock(anything); // Error: this.svgPath_ is undefined
workspace.highlightBlock(anything, true|false); // Works
```

**Comment by NeilFraser** [comment]
Sorry about that.  My fault.  Fixed on develop branch in a66d274169540553c022b9f204a77b4589968db5.

(And if anyone on the team wants me to stop abusing my power with regards to pushing directly, just say so.)
