### ISSUE TITLE
Check for undefined in horizontal flyout layout function

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#7522]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

In [`layout_`](https://github.com/google/blockly/blob/osd/core/flyout_horizontal.ts#L258) in `flyout_horizontal.ts` we access the block with `const block = item.block`. The result is nullable, so all later uses of `block` have to have a [non-null assertion](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix-)

To fix:
- Check whether `block` is `undefined` after setting `const block = item.block`.
- `continue` if `block` doesn't exist.
- Remove `!` from after the remaining uses of `block` within the for loop.

To get set up for this issue:
- Run `npm install` from the root of the repository.
- Run `npm run build` from the root of the repository.
- Run `npm run start` to launch the test playground.

**Comment by SophieNguyen113** [comment]
I would love to work on this

**Comment by TroySigX** [comment]
I'd love to work on this

**Comment by juhithaVd** [comment]
I want to work on this

**Comment by rachel-fenichel** [comment]
Thanks for your interest! This is being worked on in the `blockly-dragon` breakout room.

**Comment by juhithaVd** [comment]
Does that mean any of us can do the issue?

**Comment by rachel-fenichel** [comment]
Please join the breakout room to see what the status is and who is working on this.

**Comment by priya-rjb** [comment]
Hi, we are currently in the breakout room and would like to be assigned this code as we made progress. Thanks!
