### ISSUE TITLE
Check for undefined in vertical flyout layout function

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#7523]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

In [`layout_`](https://github.com/google/blockly/blob/osd/core/flyout_vertical.ts#L227) in `flyout_vertical.ts` we access the block with `const block = item.block`. The result is nullable, so all later uses of `block` have to have a [non-null assertion](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix-)

To fix:
- Check whether `block` is `undefined` after setting `const block = item.block`.
- `continue` if `block` doesn't exist.
- Remove `!` from after the remaining uses of `block` within the for loop.

Related to https://github.com/google/blockly/issues/7522

To get set up for this issue:
- Run `npm install` from the root of the repository.
- Run `npm run build` from the root of the repository.
- Run `npm run start` from the root of the repository to launch the test playground.

**Comment by ivalkshfoeif** [comment]
Hi @rachel-fenichel, I'd like to work on this issue!

**Comment by rashmi29** [comment]
Hi @rachel-fenichel , I would like to work on this issue. Could you please assign it to me?

**Comment by 11aparna91** [comment]
Hi @rachel-fenichel , I would like to work on this issue.

**Comment by rachel-fenichel** [comment]
Hi all, and thanks for your interest! This is being worked on in the `blockly-elephant` breakout room.
