### ISSUE TITLE
Remove underscore from `isLabel_` in `flyout_button.ts`

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#7526]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

There is a property in `flyout_button.ts` that has an underscore and doesn't need to:
 [`private readonly isLabel_` ](https://github.com/google/blockly/blob/osd/core/flyout_button.ts#L62)

To fix:
- Rename the property to `isLabel`.
- Verify that [labels and buttons](https://developers.google.com/blockly/guides/configure/web/toolbox#buttons_and_labels) still work in the playground.

To get set up for this issue:
- Run `npm install` from the root of the repository.
- Run `npm run build` from the root of the repository.
- Run `npm run start` to launch the test playground. 

## Additional information
Our old convention was to use underscores to mark private properties, because the language did not include privacy. Typescript has explicit public and private, and [Google's style guide now recommends](https://google.github.io/styleguide/tsguide.html#naming-style) never ending in an underscore.
This change is safe because the property is private, meaning it's only used in this single file and the API is not changing.

**Comment by 11aparna91** [comment]
hey i would like to work on this

**Comment by BeksOmega** [comment]
Heya @11aparna91 We have limited issues for the second session, so we're planning on having people work in groups! If you're still interested in that, you can join our call in ~20 minutes and we'll give y'all more info =)

**Comment by Shreyagundu** [comment]
Hey @BeksOmega Can I work on this?

**Comment by sayalikandarkar** [comment]
Could you please assign it to me?
