### ISSUE TITLE
Wrong documentation: Date Field

### ISSUE THREAD

**Issue by volkf** [google/blockly#753]
I think the semicolon is wrong here. 

![datefield](https://cloud.githubusercontent.com/assets/13332383/20556469/91e07698-b167-11e6-85af-6ac1a02075ea.png)

I'm not sure where should I report such little issues?

**Comment by rachel-fenichel** [comment]
This location is fine for now.  Thanks for pointing it out!

**Comment by AnmAtAnm** [comment]
Fixed.  Thanks for the report.
