### ISSUE TITLE
Mutator constructor is not a function - after version update

### ISSUE THREAD

**Issue by mrzewnicki** [google/blockly#7546]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description
I'm just updated from 9.3.3 to 10.1.3 and i'm receiving the error (in stack trace)

It has been moved to other namespace? I didn't found this class in entire core space

I'm working on react and my implementation is:
```
import * as Blockly from 'blockly/core';
Blockly.Blocks['select_fields'] = {
    init: function () {
        this.appendDummyInput("FieldLabel").appendField("SELECT");
        this.itemCount_ = 1;
        this.updateShape_();
        this.setPreviousStatement(false);
        this.setNextStatement(true, ['precondition', 'select_where']);
        this.setColour('#8007f2');
        this.setMutator(new Blockly.Mutator(['lists_create_with_item']));
        this.setTooltip(Blockly.Msg['LISTS_CREATE_WITH_TOOLTIP']);
        this.setInputsInline(false);
        this.setOnChange(this.onChangeHandler);
    },
```
and it was working very well for 9.3.3

### Stack trace

```shell
Uncaught TypeError: Blockly.Mutator is not a constructor
```

**Comment by BeksOmega** [comment]
Hello! I think this issue got resolved on the forum =) `Blockly.Mutator` no longer exists, instead it is called `Blockly.icons.MutatorIcon`.

https://groups.google.com/g/blockly/c/gO_zPvDS3ME/m/zjD4sE6RAAAJ

**Comment by pachtymi** [comment]
What was the new implementation that was used by @mrzewnicki ? I am in the exact same boat here but I can't figure out how to get the new required second param of MutatorIcon, sourceBlock.

**Comment by Saifulgani** [comment]
> MutatorIcon



> What was the new implementation that was used by @mrzewnicki ? I am in the exact same boat here but I can't figure out how to get the new required second param of MutatorIcon, sourceBlock.

try this.setMutator(new Blockly.icons.MutatorIcon([], this));
