### ISSUE TITLE
Can mutate blocks in readOnly workspace

### ISSUE THREAD

**Issue by michaela-mm** [google/blockly#7557]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

If there is a block with mutator in a `readOnly` workspace, I can click on the mutator icon, open the mutator bubble and change the block that way. I think the icon used to just be disabled pre-v10?

### Reproduction steps

1. Run `npm run start` and switch to the `Advanced playground` link.
2. Drag in an `if` block
3. Check the `readOnly` option and reload.
4. You can add `else` and `ifelse` rows to the `if` block.

### Screenshots

![image](https://github.com/google/blockly/assets/63740955/830202af-1972-4a62-a0aa-b25672795c7f)

### Browsers

Chrome desktop

## To Fix

1) Run the reproduction steps to make sure you can replicate the issue.
2) Modify the `onClick` method of the `MutatorIcon` to return early if `this.sourceBlock.isEditable()` is `false`.
3) Rerun the reproduction steps and make sure you can't reproduce.

**Comment by Apoorvgarg-creator** [comment]
@BeksOmega @maribethb Can I take this issue ?
