### ISSUE TITLE
Block Factory injection vulnerability

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#756]
Failure to escape user data.  Look at the JSON for this block:
https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#xd6zrv

Obviously check other places than just this one field.  And don't rely on the validation of number fields, since one could disable the validators locally, save arbitrary XML, then send the URL to someone else.

**Comment by rachel-fenichel** [comment]
The problem appears to be in how we're escaping the input to prettyPrintOne.
