### ISSUE TITLE
mutiple line text container add a scroll bar if content is too long

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#7570]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Problem

![image](https://github.com/google/blockly/assets/42778/a770fdb8-5837-478e-a0e7-5e0c37d026a5)

test with v9.2.1

### Request

make mutiple line text support scroll bar if content is too long

**Comment by maribethb** [comment]
Hello, you can set the maximum displayed lines before the scrollbar is activated. This is done either in the [constructor](https://developers.google.com/blockly/reference/js/blockly.fieldmultilineinput_class._constructor__1_constructor.md) for the field or by calling [`setMaxLines`](https://developers.google.com/blockly/reference/js/blockly.fieldmultilineinput_class.setmaxlines_1_method.md) after construction.

I hope this helps! If you have follow up questions about how to use this, please post on the [forum](https://groups.google.com/g/blockly). Thanks!
