### ISSUE TITLE
What about the graphical trigger tree like graphical programming for Warcraft III

### ISSUE THREAD

**Issue by qq1053831109** [google/blockly#7574]
What about the graphical trigger tree like graphical programming for Warcraft III? May be easier to use. 

And there is no way to trigger multiple events in block graphics. And it's not concise enough.
![image](https://github.com/google/blockly/assets/17372170/05fdcec0-d91c-428d-8df5-ef9d20e5812a)

I'm just looking for a better way to program graphical events and actions in games。

**Comment by rachel-fenichel** [comment]
Thanks for the idea. That would be a large change from what Blockly is and we are not considering this type of UI change.
