### ISSUE TITLE
Scroll-to-zoom is hard to use on touchpads

### ISSUE THREAD

**Issue by drigz** [google/blockly#758]
I've seen this on a Chromebook and on a laptop running Ubuntu. If you open the [code demo](https://blockly-demo.appspot.com/static/demos/code/index.html) and scroll up or down on a touchpad, the program zooms in/out extremely fast. It is very hard to get the right zoom level.

Using a mouse which "clicks" when scrolling, there is no problem.

**Comment by rachel-fenichel** [comment]
What's your ideal solution for this?

**Comment by drigz** [comment]
I'd expect [this line](https://photos.google.com/share/AF1QipP_lOZOWwjFWxfJamqu1JlUiEtySz-BtfnwkWIp70BJGdVcfGjgDyWcLauQNvuOcw?key=ckJFWVJMZTlUZnowa2dYYTZvUlZ4VDdDWkxqMnVn) to change from:
```var delta = e.deltaY > 0 ? -1 : 1;```
to something like:
```var delta = e.deltaY * -50;```

But I don't know if this might have other consequences. Is there a reason for the current behaviour?

(PS. I chose 50 because on my desktop, a single click of the mousewheel gave deltaY = 53.)

**Comment by rachel-fenichel** [comment]
Which line?  I think you had a stale copy-paste buffer.

I would have to dig into the current behaviour.  I don't know off the top of my head where that number comes from.

**Comment by drigz** [comment]
Oops, fixed now!

I looked again and realised it just needs a small change to zoom(), so I went ahead and sent a PR. However, I just thought of an alternative approach: if onMouseWheel_() accumulates the distance and only zooms when this exceeds PIXELS_PER_ZOOM_STEP, then you'd get the "clicky" behaviour of a mousewheel on touchpads as well (not sure which is preferable).

**Comment by rachel-fenichel** [comment]
Fixed by #769.  Thanks!
