### ISSUE TITLE
Dropdowns and context menus don't close on clicks outside of blockly

### ISSUE THREAD

**Issue by Anton2478** [google/blockly#7583]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

If I open a dropdown or a context menu, clicking outside of it but still inside blockly closes the dropdown/context menu. But clicking outside of blockly but still on the same web page doesn't close the dropdown/context menu.

**Comment by rachel-fenichel** [comment]
Blockly doesn't generally register event handlers outside of the part of the DOM that we own. You can resolve this by calling `Blockly.hideChaff` in a listener on your page.
