### ISSUE TITLE
Crash if a field click deletes a block

### ISSUE THREAD

**Issue by maribethb** [google/blockly#7587]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

If you have a block with a field that deletes the block*, Blockly will crash because the gesture handling code assumes the block continues to exist.

We can fix this in several ways:

1. Move `bringBlockToFront` to the beginning of [`doFieldClick`](https://github.com/google/blockly/blob/9c7c71ad879a62e285d97236e1c6907287463251/core/gesture.ts#L938) (so that it happens before the field has a chance to handle the click)
2. Have `bringBlockToFront` make sure `disposed` is false on the block before calling the `bringToFront` method. This would prevent trying to move a dead/dying block.

### Reproduction steps

1. Add the following block definition to the playground above the `start` call.
```js
Blockly.Blocks['test'] = {
        init: function() {
          this.setStyle('math_blocks');
          this.appendDummyInput()
              .appendField(new Blockly.FieldImage(
                  'media/arrow.png',
                  30,
                  30,
                  'test',
                  function() {
                    this.getSourceBlock().dispose();
                  }
              ));
        }
```
2. Run `npm run start` to start the playground.
3. Load the following JSON into the playground:
```
{
  "blocks": {
    "languageVersion": 0,
    "blocks": [
      {
        "type": "test"
      }
    ]
  }
}
``` 
4. Open the browser.
4. Click the arrow on the block.
5. Observe the error in the console.

### Stack trace

```shell
Uncaught TypeError: Cannot read properties of null (reading 'childNodes')
    at BlockSvg$$module$build$src$core$block_svg.bringToFront (block_svg.ts:1227:34)
    at Gesture$$module$build$src$core$gesture.bringBlockToFront_ (gesture.ts:940:25)
    at Gesture$$module$build$src$core$gesture.doFieldClick_ (gesture.ts:880:10)
    at Gesture$$module$build$src$core$gesture.handleUp (gesture.ts:591:14)
    at HTMLDocument.g (browser_events.ts:70:9)
```

### Additional Info

This should also be fixed for icons since, https://github.com/google/blockly/issues/7588 is fixed.

## To Fix

1) Run the reproduction steps above to make sure you can reproduce the issue.
2) Add a check in `bringToFront` that checks if `this.isDeadOrDying()`, and returns early if so.
3) Run the reproduction steps again to make sure the issue doesn't reproduce.

**Comment by Apoorvgarg-creator** [comment]
Interested to solve the issue

**Comment by maribethb** [comment]
Great, I'll assign you @Apoorvgarg-creator ! If you have any questions please feel free to ask here.

**Comment by Apoorvgarg-creator** [comment]
> Great, I'll assign you @Apoorvgarg-creator ! If you have any questions please feel free to ask here. 

Thank you !

**Comment by Apoorvgarg-creator** [comment]
@maribethb I am working on this issue, I cloned the repo and ran ```npm i``` after that I want to build and reproduce the issue, can you please help me !

**Comment by Apoorvgarg-creator** [comment]
Getting this on running ```npm run start```

<img width="1121" alt="Screenshot 2023-10-28 at 10 06 22 PM" src="https://github.com/google/blockly/assets/57873504/a40a59a1-da9c-4a92-a201-59bc9ad4a950">

**Comment by BeksOmega** [comment]
> Getting this on running `npm run start`

Looks like you're probably using an old version of node. Can you upgrade to Node v20 @Apoorvgarg-creator and see if that fixes the issue?

**Comment by Apoorvgarg-creator** [comment]
@BeksOmega Thank you, It worked !

**Comment by Apoorvgarg-creator** [comment]
@maribethb @BeksOmega I have solved the bug with the solution proposed in the issue.
But I wanted to know if this solution is also logically correct or not -
if I add parent !== null check before accessing properties of parent ?

**Comment by Apoorvgarg-creator** [comment]
How can I correct the commit message, due to that tests are failing
