### ISSUE TITLE
clicking an icon should bring the block to front

### ISSUE THREAD

**Issue by maribethb** [google/blockly#7588]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

In the gesture code for handling a field click, we bring the block to the front. But for icon clicks, we don't bring the block to the front. This is unexpected.

We can fix this behavior by calling `this.bringBlockToFront()` in the [`doIconClick`](https://github.com/google/blockly/blob/9c7c71ad879a62e285d97236e1c6907287463251/core/gesture.ts#L942) method. Due to #7587 this should be called *before* we call `startIcon.onClick()`.

After making this change, you can run the reproduction steps again and ensure the block is brought to the front.

### Reproduction steps

1. Add a block with an icon to the workspace (such as the mutator gear icon).
2. Add another block on top of that one.
3. Click the icon.
4. Notice how the block does not come to the front.

### Screenshots

![image](https://github.com/google/blockly/assets/8573958/5467421f-d5a5-4ecc-93ca-987918d1c03d)

**Comment by BeksOmega** [comment]
Hello! You can run `npm run start` from the root of your fork. This will bring up a local version of the [playground](https://blockly-demo.appspot.com/static/tests/playground.html) where you can test your changes! Thank you for your work on this :D

**Comment by maribethb** [comment]
Hey, Oscar! You can find all of the steps to validate a change in our [documentation](https://developers.google.com/blockly/guides/contribute/core#making_and_verifying_a_change). Let us know if you need help with this. Thanks!
