### ISSUE TITLE
Manual JSON dropdown option allows editing javascript code & breaks generator stub dropdown

### ISSUE THREAD

**Issue by 0scvr** [google/blockly#7592]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

It is possible to edit the javascript code of a block in the developer tools demo by selecting the Manual JSON... option in the block definition dropdown. The dropdown label 'Manual JSON...' is misleading in this case since it can also edit javascript code.

The second problem I noticed is that at this point the generator stub dropdown no longer functions.

### Reproduction steps

1.  In the Blockly developer tools demo, click on the javascript option in the block definition dropdown.
2.  Then select the Manual JSON... option
3. You are now able to edit the javascript code + the generator stub dropdown no longer works.

### Screenshots

https://github.com/google/blockly/assets/71343264/c8477efe-9dce-4eaa-b7c3-fa8a926212e7

### Browsers

Chrome desktop

**Comment by rachel-fenichel** [comment]
Thanks for the report. We're currently updating the block factory and do not plan to have the manual JSON option going forward.
