### ISSUE TITLE
JSON deserialization does not fire variable create events for blocks

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7599]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

JSON deserialization does not fire variable create events for blocks. It does fire variable create events for serialized variables.

XML does properly fire variable create events.

### Reproduction steps

1. Run `npm run start` to run the playground.
2. Enable workspace event logging.
3. Load the following JSON into the playground:
```js
{
  "blocks": {
    "languageVersion": 0,
    "blocks": [
      {
        "type": "variables_set",
        "fields": {
          "VAR": {
            "id": "}XEzZCNb@$C$ZWc1%awz"
          }
        }
      }
    ]
  }
}
```

4. Observe how no variable create event is fired.

**Comment by Apoorvgarg-creator** [comment]
@BeksOmega Can I work on this issue ?

**Comment by BeksOmega** [comment]
This issue hasn't been triaged yet :/ but I can assign you to one of the [good first issues](https://github.com/google/blockly/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or [help wanted issues](https://github.com/google/blockly/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)! Just comment on one and I'll get you assigned =)

**Comment by BeksOmega** [comment]
## To Fix

1) Run the reproduction steps and make sure you can reproduce the problem.
2) Create a function in the [block serialization file](https://github.com/google/blockly/blob/develop/core/serialization/blocks.ts) that fires variable events like how the [XML serializer does](https://github.com/google/blockly/blob/3e75f4f6f6fdaf0d2c578a30b1725cd6d42a2767/core/xml.ts#L607).
3) Call that function from [`appendInternal`](https://github.com/google/blockly/blob/3e75f4f6f6fdaf0d2c578a30b1725cd6d42a2767/core/serialization/blocks.ts#L426) before the block create event is fired.
4) Run the reproduction steps and make sure you can no longer reproduce.

**Comment by bsampada7** [comment]
Hi @BeksOmega , if you need this ticket off your hands, I would like to work on it

**Comment by BeksOmega** [comment]
Go for it @bsampada7 =)
