### ISSUE TITLE
As mutators expand, they don't bump away their neighbors

### ISSUE THREAD

**Issue by yoderjen** [google/blockly#76]
If I have an "if" mutator with a couple of statements in it like so:
![start](https://cloud.githubusercontent.com/assets/10271662/6414929/46bea5a6-be69-11e4-9ff2-6ab65ede70f2.jpg)

and then take away the else statement via the mutator dialog, I get (as expected):

![middle](https://cloud.githubusercontent.com/assets/10271662/6414887/ef0e81a0-be68-11e4-8a7b-f91beaa714c2.jpg)

If I then re-add the else statement to the if block, the expanded mutator doesn't bump away the unconnected second statement, making it look like there is a connection when there isn't one.

![end](https://cloud.githubusercontent.com/assets/10271662/6414909/1d22c272-be69-11e4-9f2b-bba190671be1.jpg)

**Comment by NeilFraser** [comment]
Fixed.  Thanks!
