### ISSUE TITLE
Create block with own icon from assets.

### ISSUE THREAD

**Issue by edi233** [google/blockly#760]
Hello,
I want to create custom block where I want to add my own icon from assets. I create block:
 ```
{
    "type": "left_arrow",
    "message0": "%1",
    "args0": [
      {
        "type": "field_image",
        "src": "file:///android_asset/ic_arrow_left.png",
        "width": 15,
        "height": 15,
        "alt": "*"
      }
    ],
    "previousStatement": null,
    "nextStatement": null,
    "colour": 210,
    "tooltip": "",
    "helpUrl": "http://www.example.com/"
  }

but I can't see my arrow. Any help?
```

**Comment by bkisdi** [comment]
Is your page served from the file system or a (local) web server?
I guess file:// is not applicable in your case. Can you reference the image with a relative path?

**Comment by edi233** [comment]
yes, I want to load image from internal storage my phone with android.

**Comment by bkisdi** [comment]
I see, but is the blockly file served from the same/parent /sibling directory as the image?

See [Blockly.Blocks['text']](https://github.com/brownplt/BlockLang/blob/master/blockly/language/common/.svn/text-base/text.js.svn-base) lines 32-33 and 35-36 for an example of Blockly.pathToBlockly. (You can use it after the **"src":** as well.) Warning! This is an older version of Blockly from 2013 (NOT the current branch  by Google), but the example should work.

**Comment by AnmAtAnm** [comment]
Assuming you are loading your .html containing Blockly from the assets, also, can you use a relative URL? No leading slash. Parent directory references (`../`) should be allowed.

**Comment by edi233** [comment]
ok, I find what was wrong in code. I use new .arr files from blockly, but only with release .arr file works. For debug .arr nothing happen in code. So when I build release version my app I could see icons, for debug I can't see changes.

**Comment by AnmAtAnm** [comment]
It sounds like you're using the Android build. If so, let's move the discussion to [blockly-android](https://github.com/google/blockly-android/issues) or to [the general mailing list](groups.google.com/forum/#!forum/blockly). This repo is for the web version.
