### ISSUE TITLE
intermediate field change events don't have a run method

### ISSUE THREAD

**Issue by maribethb** [google/blockly#7601]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Intermediate field change events don't have a run method. I've talked to Beka and John about this and I think it was just an oversight. Since these events are never undoable, they don't need a run method... unless you are mirroring events and want to reflect the changes in the mirrored workspace during editing.

### Reproduction steps

1. Open the [mirror demo](https://google.github.io/blockly-samples/examples/mirror-demo/index.html).
2. Start typing in a text field.
3. Notice how changes aren't mirrored until you finish editing.

**Comment by truongductri01** [comment]
@maribethb I would love to help with this, could you show me the files I could look into to fix this?

**Comment by BeksOmega** [comment]
> I would love to help with this, could you show me the files I could look into to fix this?

Hello! Thanks for your interest in working on this issue =) You need to modify the [field intermediate change event](https://github.com/google/blockly/blob/develop/core/events/events_block_field_intermediate_change.ts) file to have a `run` method that "plays" the action forward or backward based on a boolean passed to the `run` method. If you've ever heard of the [command pattern](https://en.wikipedia.org/wiki/Command_pattern) it's basically that! You can check out the other events in that directory for examples =)

If you have any other questions don't hestitate to reach out!

**Comment by truongductri01** [comment]
@BeksOmega I have reached out to you through your email (posted on your GitHub). Hope that find you well since I need help with fixing this issue

**Comment by BeksOmega** [comment]
> @BeksOmega I have reached out to you through your email (posted on your GitHub). Hope that find you well since I need help with fixing this issue

Heya! I don't reply through my personal email for work-related projects, only personal ones =) If you post any questions you have here I can do my best to answer them!

**Comment by truongductri01** [comment]
@BeksOmega I was confused with how to test the changes. After editing the event like you suggested, how could I check it out in the mirror demo to verify the changes? I see that the event gets exported but not sure where it is used. Is it being used in another repo to create the demo?

**Comment by BeksOmega** [comment]
> @BeksOmega I was confused with how to test the changes. After editing the event like you suggested, how could I check it out in the mirror demo to verify the changes? I see that the event gets exported but not sure where it is used. Is it being used in another repo to create the demo?

If you could create a unit test similar to the ones [here](https://github.com/google/blockly/blob/develop/tests/mocha/event_block_change_test.js) (create a new file, and add a unit test that tests the intermediate change events) I think that would be perfect. When you put up the pull request I can pull down your code and manually test it =)

**Comment by truongductri01** [comment]
@BeksOmega I also be able to set up the environment (running the mirror sample) to test the changes, like I showed in the pr. Do you think there is a way that I could document that for other new contributors to have some basic ideas of how to do similar set up?

**Comment by BeksOmega** [comment]
> @BeksOmega I have created a pull request: #7671
> 
> Thank you for your help and passion.
> 
> I am currently have some issue with running `npm run build` on my forked repo. When running `npm run build` on blockly (this original version) it works fine, but when running on my forked repo, it raise an error: "Error: No supported platform for closure-compiler found". I believe this could be because of some set up that I may not aware of. Do you have any idea on this?

1) Make sure you're using node 20 and npm 10.
2) Run `npm ci` from the root of Blockly.

If that doesn't fix the issue could you post the full text of the error?

**Comment by truongductri01** [comment]
> > @BeksOmega I have created a pull request: #7671
> > Thank you for your help and passion.
> > I am currently have some issue with running `npm run build` on my forked repo. When running `npm run build` on blockly (this original version) it works fine, but when running on my forked repo, it raise an error: "Error: No supported platform for closure-compiler found". I believe this could be because of some set up that I may not aware of. Do you have any idea on this?
> 
> 1. Make sure you're using node 20 and npm 10.
> 2. Run `npm ci` from the root of Blockly.
> 
> If that doesn't fix the issue could you post the full text of the error?

When running `npm run build`, this is the error I got:
```
 Error: No supported platform for closure-compiler found.
    at getFirstSupportedPlatform (/Users/tritruong/Documents/ComputerScience/Projects/tri-blockly/node_modules/google-closure-compiler/lib/utils.js:57:11)
    at new CompilationStream (/Users/tritruong/Documents/ComputerScience/Projects/tri-blockly/node_modules/google-closure-compiler/lib/gulp/index.js:101:23)
    at /Users/tritruong/Documents/ComputerScience/Projects/tri-blockly/node_modules/google-closure-compiler/lib/gulp/index.js:254:49
    at compile (/Users/tritruong/Documents/ComputerScience/Projects/tri-blockly/scripts/gulpfiles/build_tasks.js:530:10)
    at buildCompiled (/Users/tritruong/Documents/ComputerScience/Projects/tri-blockly/scripts/gulpfiles/build_tasks.js:561:13)
    at bound (node:domain:432:15)
    at runBound (node:domain:443:12)
    at asyncRunner (/Users/tritruong/Documents/ComputerScience/Projects/tri-blockly/node_modules/bach/node_modules/async-done/index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

However, this only happen with the code I forked, running build in the original repo does not raise any error.
The branch I got when fork the repo is `osd`, not `develop`. I am not sure why.
