### ISSUE TITLE
Add label to readme 

### ISSUE THREAD

**Issue by shraddha761** [google/blockly#7611]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

I think there should be label to readme which make it look more attractive. 

![image](https://github.com/google/blockly/assets/106100728/e389c472-722f-4261-aaf9-f4548d4eac72)

### Request

Assign this issue to me.

**Comment by maribethb** [comment]
Hi @shraddha761 thanks for the suggestion. At this time we don't feel the labels would add useful information to our readme, so we're not going to accept this issue. Thanks!
