### ISSUE TITLE
Add icon CSS

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7623]
Some partners have requested being able to style our icons (comment, mutator, and warning). They could register and use their own custom icons, but that seems a little heavy if they just want to change the background color.

## To Fix

Add the following css classes to each of the icons. You need to modify the `initView` method to call `dom.addClass(this.svgRoot, <css class>);`

- [Comment](https://github.com/google/blockly/blob/37bfcbc31e5e024d45e37cc3d01a57e52e809ddb/core/icons/comment_icon.ts#L77): `blockly-icon-comment`
- [Mutator](https://github.com/google/blockly/blob/37bfcbc31e5e024d45e37cc3d01a57e52e809ddb/core/icons/mutator_icon.ts#L82): `blockly-icon-mutator`
- [Warning](https://github.com/google/blockly/blob/37bfcbc31e5e024d45e37cc3d01a57e52e809ddb/core/icons/warning_icon.ts#L55): `blockly-icon-warning`

**Comment by Asymtode712** [comment]
I want to work on it. Please assign me

**Comment by Tashuuuu** [comment]
I would like to work on this. Could you please describe it more?

**Comment by BeksOmega** [comment]
Hiya @Tashuuuu @Asymtode712 is already working on this issue =) But if you want to comment on a different good-first-issue that doesn't have anyone assigned, I'd be happy to assign you!
