### ISSUE TITLE
Stop loading JS generator in the main blockly bundle

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7625]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When you access Blockly via `import * as Blockly from 'blockly';` It loads the JS generator, but it isn't made accessible to external developers in any way. We should stop loading the JS generator.

**Comment by BeksOmega** [comment]
@cpcallen This is not a docs issue. This issue covers the fact that the `browser` and `node` packages unnecessarily import the javascript generator, but don't make it available.

**Comment by cpcallen** [comment]
> @cpcallen This is not a docs issue.

Quite correct.  I was trying to close #6656, but apparently went to the wrong tab…

**Comment by cpcallen** [comment]
This was fixed by #7822.
