### ISSUE TITLE
Wrong link in docs

### ISSUE THREAD

**Issue by nighthawk** [google/blockly#7627]
The [documentation page on context menus](https://developers.google.com/blockly/guides/configure/web/context-menus) has two broken links to GitHub.

The links point to `https://github.com/google/blockly/blob/master/core/contextmenu_items.js` when they should point to `https://github.com/google/blockly/blob/master/core/contextmenu_items.ts`, i.e., the links need to be updated to point to the new TypeScript files rather than the old JavaScript files.

**Comment by truongductri01** [comment]
@BeksOmega Can I try to work on this? I am new to blockly but would love to help with these issues

**Comment by BeksOmega** [comment]
> @BeksOmega Can I try to work on this? I am new to blockly but would love to help with these issues

Thanks for your interest! But our documentation is sadly closed-source for historical reasons :/ So only people working at google can edit it.

I've assigned the other issue you asked about to you!
