### ISSUE TITLE
Update `setShadow` TSDoc for Block and BlockSvg

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7636]
### Location

https://github.com/google/blockly/blob/02cd1c6a1be1e5040ec712c0418373405eadfa5a/core/block.ts#L872 and https://github.com/google/blockly/blob/02cd1c6a1be1e5040ec712c0418373405eadfa5a/core/block_svg.ts#L762

### Type

- [X] Text
- [ ] Image or Gif
- [ ] Other

### Suggested content

Add the following to the TSDoc.

"This method is internal and should not be called by users of Blockly. To create shadow blocks programmatically call connection.setShadowState"

**Comment by systemc12ashe** [comment]
I'm hoping to get started with contributing to Blockly, could I start with this issue?

**Comment by BeksOmega** [comment]
Yeah this is a perfect place to start @systemc12ashe :D I've assigned you, let me know if you have any questions!
