### ISSUE TITLE
Enable/Disable Reported in #7113, Still happening in v10.2.2

### ISSUE THREAD

**Issue by mrkprdo** [google/blockly#7648]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

As I described in this issue #7113, this seems to happen in v10.2.2

### Reproduction steps

See video/gif:

[screen-capture (40).webm](https://github.com/google/blockly/assets/15664355/888b765c-a050-4a0a-a25c-28654dea9b43)

### Screenshots

See reproduction steps.

### Browsers

Chrome desktop

**Comment by BeksOmega** [comment]
Sorry we missed your comment on the other issue! I've reopened it and marked it for triage, so I'm going to go ahead and close this one =)
