### ISSUE TITLE
Mocha test failures not reported by `test/mocha/webdriver.js`

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#7649]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When running the mocha tests, our webdriver harness correctly reports the number of test failures but not any details.

### Reproduction steps

1. Modify any of the test files in `tests/mocha/*_test.js` such that one or more test will fail.  This can be done by changing one of the arguments to any `chai.assert.equal` call such that the assertion will fail.
2. Run `npm run build && node tests/mocha/webdriver.js` (or `npm test` if you're not in a hurry).
3. Observe output.

**Expected output**

Per code in `tests/mocha/webdriver.js`, the "Blockly Mocha Test Failures" section of the output is expected to be non-empty: it should contain either useful error messages from the controlled Chrome instance, or the string "There is at least one test failure, but no messages reported. Mocha may be failing because no tests are being run.".

**Actual output**

That section contains only blank lines (one per failure):
```
Loading URL: file:///Users/cpcallen/src/blockly/tests/mocha/index.html
============Blockly Mocha Test Failures================


============Blockly Mocha Test Summary=================
2 tests failed
============Blockly Mocha Test Summary=================
Mocha tests failed
```
Technically correct (is not empty, so does not get the "no messages" message), but not the best kind of correct.

### Stack trace

There are a number of stack traces in the browser console, but they all appear to be directly the result of tests that elicit errors rather than being related to this issue (e.g., mocha not being able to find the `#failureMessages` element to write to or other problems of that nature).

### Browsers

Chrome desktop

**Comment by maribethb** [comment]
Pretty sure this used to work, the likely candidate for breaking this was I think we changed something about how mocha was being run with webdriver around the time we added the browser tests

**Comment by btw17** [comment]
I'll take a look at this one!

**Comment by btw17** [comment]
So the gist of the issue is that the message exists in the page, though it's beneath `#failureMessages` which has `display: none`. We're currently using `getText()` from `webdriverio` which only displays text of interactable elements.

https://webdriver.io/docs/api/element/getText

I'll get a workaround out soon.
