### ISSUE TITLE
Make blocks with multiple outputs

### ISSUE THREAD

**Issue by Lingareddy515** [google/blockly#7653]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Details:
In my project, we create pipelines. pipeline is a sequence of calculation steps which execute one after another.
And at some calculation step there will be branching. lets say at the branching we have two results, with one result we perform some operations and with another result we perform some other operations. at last I could have merge the results.
Attached basic prototype of pipelines, one with no branching, another with branching. Note: As in the attachment we create rectangular shaped blocks which connect vertically.

Problem is, for a block there is only one previous statement and next statement. So, i have reached out to your team via blockly google groups, and i got suggestion that if I want multiple inputs for a block i could use Value input blocks. 
Conversation link: https://groups.google.com/g/blockly/c/Lb8B9bI9hek/m/PJGAvI1IBwAJ

But, blockly does not provide blocks with multiple outputs. In my case we need blocks with multiple inputs also multiple outputs.

### Request

If we have blocks with multiple inputs and outputs, we can perform multiple branching operations in the pipeline and ultimately it is very easy to understand the flow by the users.

### Additional context
[pipeline_example.pdf](https://github.com/google/blockly/files/13437227/pipeline_example.pdf)

_No response_

**Comment by Lingareddy515** [comment]
[pipeline_example.pdf](https://github.com/google/blockly/files/13437210/pipeline_example.pdf)

**Comment by mrkprdo** [comment]
That might need some changes on how blocks expands as they get stacked each other. I had similar conundrum and ended by using statement instead of output, just need to the define scopes within statement.

But I am interested on how maintainers will respond. :)
