### ISSUE TITLE
Since 10.0.0, the toolbar has blocked blocks in the drag and drop

### ISSUE THREAD

**Issue by LuofengZhang** [google/blockly#7663]
### Description
https://github.com/google/blockly/assets/34879650/48125199-04c2-46aa-b532-0e232d4b0253

**Comment by mrkprdo** [comment]
That toolbox seems to be always open. If you check other samples where toolbox shows up when you open a category, it doesn't do that.

**Comment by LuofengZhang** [comment]
> That toolbox seems to be always open. If you check other samples where toolbox shows up when you open a category, it doesn't do that.
I know you're talking about categoryToolbox, which closes automatically, but I'm using flyoutToolbox, which doesn't close automatically, and until version 10.0.0, drag blocks are higher in the hierarchy than the toolbox.Is this a planned change?

**Comment by BeksOmega** [comment]
This has been fixed and will go out with the next release of Blockly (planned for ~Dec= 7th) Thank you for reporting!
