### ISSUE TITLE
procedure_defnoreturn and procedure_defreturn blocks in toolbox, blockText does not show full text

### ISSUE THREAD

**Issue by mrkprdo** [google/blockly#7664]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

I am extracting blocks in toolbox for search feature. I works but not for those type of blocks coz they seem not show all text.
In context, we have pre-defined macro method blocks that are collapsed and added in the toolbox.
When iterating over them they seem to not have all of the text.

We also have search in workspace, and getting text from those blocks are working fine.

### Reproduction steps

1. Create method using procedure_defreturn and procedure_defnoreturn blocks
2. Add them in the toolbox
3. Iterate over the blocks in the toolbox and get the blocktext by calling `block.toString()`
4. Those affected blocks will show something like in screenshot.

### Screenshots

![image](https://github.com/google/blockly/assets/15664355/769ed486-a0d4-4bb5-819e-b73c7d559cfe)

**Comment by maribethb** [comment]
Hello @mrkprdo can you clarify what additional text you are expecting to see? the built-in blocks don't contain any text beyond that.

**Comment by mrkprdo** [comment]
Hi @maribethb,
Im just gonna take the example when you iterate over the blocks in the workspace and try to extract blockText, those "method" blocks will show something like `to <method name> <inner block texts> return <return var name>`. I am expecting if the hardcoded method blocks defined in the toolbox should have same blockText as well.
Hope that makes sense.

**Comment by maribethb** [comment]
Sorry, I'm still not sure what you mean. In this screenshot, are you asking that you want block #1's text to match that of block #2?

![image](https://github.com/google/blockly/assets/8573958/6b1ee457-8372-4b48-95bc-ea9f5bae6ca7)

If so, in that case the function call blocks (block #1) aren't deeply aware of the blocks in the definition block (block #2). You could write your own function that checks if the block is a function call block and if so checks the test of the matching definition block instead. That isn't a feature we are going to add to core.


If not, could you provide a screenshot of the block in the toolbox that isn't behaving as you expect? You can reopen this issue if so.

**Comment by mrkprdo** [comment]
Hi @maribethb 
Thanks for the triaging the issue. I will create a sample code in the playground and see if its a valid thing or not before re-opening.
