### ISSUE TITLE
Add ability to mute Blockly audio

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7669]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Some projects want their app to be muteable through their own UI (rather than by muting the browser / OS). But currently this is not possible because we do not allow Blockly itself to be muted.

This is a request from MakeCode.

### Request

Add a `mute` method to the `WorkspaceAudio` class, and have it ignore any requests to play sounds while muted.

### Alternatives considered

We could use a state pattern here, but it's a small enough class I don't think it's worth it.

## To Fix

2) Add a `private muted: boolean` field to the [`WorkspaceAudio`](https://github.com/google/blockly/blob/develop/core/workspace_audio.ts) class to keep track of whether the audio is muted or not.
1) Add a `setMuted` method to the class that toggles `muted`.
3) At the top of `play`, early return if `this.muted` is true.

**Comment by riknoll** [comment]
Might also be nice to add a global volume

**Comment by truongductri01** [comment]
@BeksOmega Can you assign this ticket to me?

**Comment by BeksOmega** [comment]
@truongductri01 Go for it =)

**Comment by truongductri01** [comment]
@BeksOmega https://github.com/google/blockly/pull/7714

I have created the PR for this issue. Sorry for the late submission. 
I am not sure how to create an example with work space so that I could try to disable the sound. Could you show me how you would test it?

**Comment by BeksOmega** [comment]
You can modify the [playground.html](https://github.com/google/blockly/blob/develop/tests/playground.html) file to call `setMuted(true)` and see if it plays any sounds!
