### ISSUE TITLE
Release wheel listener when disposing workspace.

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7674]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

We have a dummy wheel listener we add to the document to work around a bug in safari. Currently this listener is  not getting disposed when the workspace is disposed.

## To Fix

1) Create a class member variable to store the [dummy listener](https://github.com/google/blockly/blob/3d3cd3fbb0c86b7c855baa592663d2989f921c2e/core/workspace_svg.ts#L790).
2) Remove the listener inside the WorkspaceSvg's `dispose` method.

**Comment by ananta** [comment]
@BeksOmega I would love to work on this :)
