### ISSUE TITLE
Comments don't raise when clicked

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#7675]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Clicking on the lower of two comments does not raise it.  One has to drag it by a pixel to get the desired visibility.

Applies to BOTH block comments and workspace comments.

This contrasts with the previously expected behaviour of comments as seen here:
https://blockly.games/pond-duck

### Reproduction steps

1. Go to the playground.
2. Create two overlapping comments (either on the workspace or on blocks)
<img width="223" alt="Screenshot 2023-12-01 at 20 39 31" src="https://github.com/google/blockly/assets/250480/24778205-c701-4ca7-aac7-b327e046a986">
3. Click on the lower one.

**Comment by BeksOmega** [comment]
Not a regression in the latest release.

**Comment by BeksOmega** [comment]
Still reproducible with new workspace comments.

**Comment by UCYT5040** [comment]
Unable to reproduce with block comments. Still reproducible with workspace comments.

**Comment by harsh-791** [comment]
@BeksOmega I would like to work on this
