### ISSUE TITLE
Workspace comments don't use undo groups when created.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#7676]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

After creating a workspace comment, if one clicks 'undo', the comments jumps to 0,0 instead of disappearing.

### Reproduction steps

1. Go to the playground.
2. Create workspace comment
3. Click 'undo' in context menu.

**Comment by BeksOmega** [comment]
Fixed by new workspace comments.
