### ISSUE TITLE
Function call/def blocks out of sync when disabled/enabled

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#7678]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Blockly should not be able to generate syntax errors.  However, one can get into such a state by disabling a function definition block (upon which all callers automatically and correctly disable too), then enabling a caller block.

### Reproduction steps

1. Create a function call/def pair.
2. Disable the def block.  The call block disables too.
3. Enable the call block.

### Screenshots

<img width="263" alt="Screenshot 2023-12-01 at 21 03 47" src="https://github.com/google/blockly/assets/250480/e70bc0e4-5698-4078-938c-b9b83ad0b5b1">

**Comment by BeksOmega** [comment]
This is solved by https://www.npmjs.com/package/@blockly/disable-top-blocks
