### ISSUE TITLE
Mutators work in the trash

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#7679]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

An 'if' block (or another with a mutator) can have their shapes modified while in the trash.

This is unlike comments which cannot be opened while in the trash.

This is a regression, as seen here:
https://blockly.games/turtle?level=10

### Reproduction steps

1. Delete an 'if' block.
2. Open the trash, and click on the 'if' block's mutator icon.
3. The block is fully editable.

### Screenshots

<img width="180" alt="Screenshot 2023-12-01 at 21 16 48" src="https://github.com/google/blockly/assets/250480/7935a86e-1296-4ae7-acf2-67041a9f1a20">

**Comment by BeksOmega** [comment]
Solved by https://github.com/google/blockly/pull/7672
