### ISSUE TITLE
Trash can flyout opens when throwing away a block.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#7681]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When throwing away a block by dragging it over the trashcan, the trashcan flyout should not open when the block is deleted.  And even if it should open, the just-deleted block should be in the trashcan.

This is a regression, as seen here:
https://blockly.games/maze

### Reproduction steps

1. Throw away a block (so the trashcan has something in it)
2. Throw away a different block

**Comment by BeksOmega** [comment]
Could not reproduce :/

**Comment by BeksOmega** [comment]
[Screen recording 2023-12-01 2.24.45 PM.webm](https://github.com/google/blockly/assets/25440652/67653fa2-0e12-47c7-a57c-bf5e236899f4)
