### ISSUE TITLE
Buged Toolbox when open on popup

### ISSUE THREAD

**Issue by mods-code** [google/blockly#7688]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

i have a html file and when i open my popup ( .showModal() ) and open a toolbox category no blocks show ):

### Reproduction steps

1. make a html file with a popup (<dialog>) and a blockly div in the popup
2. open the popup (with js code)
3.now open a toolbox category

### Screenshots

![image](https://github.com/google/blockly/assets/105726855/774335c0-82cb-4305-9d16-a826b09ee44d)

**Comment by maribethb** [comment]
If you can add reproduction steps, feel free to reopen this issue or post on the forum for assistance.
