### ISSUE TITLE
Text newline

### ISSUE THREAD

**Issue by liuhz2013** [google/blockly#77]
When I input too many words in one text, the block will be too long. How could I make it start from a newline?
![image](https://cloud.githubusercontent.com/assets/4328376/6425420/d12d3212-bf62-11e4-95ad-5007a043db69.png)

now：
public void test() { System.out.println("Hello blockly"); }

hope：
public void test() { 
    System.out.println("Hello blockly"); 
}

**Comment by starfishmod** [comment]
See pull request #30 it will allow you to make blocks to do what you would like

**Comment by samelhusseini** [comment]
https://github.com/google/blockly/pull/2663 introduce multi-line fields that resolves this. Closing.
