### ISSUE TITLE
Weird movement on zoom and scroll 

### ISSUE THREAD

**Issue by timgrossmann** [google/blockly#770]
I'm not really sure if i do something wrong, but when zooming or panning around i get really annoying overlays.
In my opinion the blocks in the workspace shouldn't overlay the toolbox...
Is there a fix for that ?

Thank you.

<img width="1232" alt="screen shot 2016-12-09 at 12 38 57" src="https://cloud.githubusercontent.com/assets/16529337/21047876/933c90ba-be0c-11e6-84f7-c0b222e4afbe.png">

**Comment by picklesrus** [comment]
TLDR; Yup - I'm hoping to have a fix landed in the develop branch before the end of the year.
 
Longer version:  This configuration of a simple flyout without categories and a workspace that scrolls is actually quite uncommon so it had been a low priority. Usually when there's only a couple of blocks available, folks don't need the workspace to be scrollable. The recent features added to Block Factory exposed it this a bit more widely though.  I'm in the process of refactoring some of the dom structure to make way for some performance improvements and those changes fix this bug.

**Comment by picklesrus** [comment]
I think this is the same as https://github.com/google/blockly/issues/352

**Comment by rachel-fenichel** [comment]
Closing as duplicate.
