### ISSUE TITLE
Add webcomponent/shadowdom support

### ISSUE THREAD

**Issue by jogibear9988** [google/blockly#7717]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

At the moment blockly is not usable in webcomponents, this issue should track work to support them

### Request

Add support for webcomponents

- [x] Add a sample wich uses blockly in webcomponents
- [ ] Add an API to include the styles in shadowDom
- [ ] Fix issues with Tooltips shown at the wrong position/Dom Node
- [ ] Fix issue with Text inputs shown at the wrong position dom node
- [ ] Styles for Poppuout nodes (like tooltip etc), need to be seperated from the others. Cause the Tooltips for example could be placed in normal dom, and Blockly inside of shadow dom

**Comment by jogibear9988** [comment]
I'll try to work on those open points for WC support

**Comment by jogibear9988** [comment]
refs issue: https://github.com/google/blockly/issues/1114

**Comment by jogibear9988** [comment]
Can someone help me out, where to finde the code for the tooltips and the text input?

**Comment by jogibear9988** [comment]
Blockly.setParentContainer could be used for setting the Parent for Blockly, but this works only once, and with webcomponents you could have multiple blockly components on the page.
So the parentContainer needs to be stored per workspace

**Comment by jogibear9988** [comment]
Question:

I'd like to work on official webcomponent support. But there will be refactorings needed, cause you could have multiple blockly instance with different containers for example for tooltips, ....)

Is this something wich will be accepted later? What are the opinions about this?

**Comment by BeksOmega** [comment]
Hello! I'm going to close this in favor of #1114

Will repost your question on the other thread.
