### ISSUE TITLE
Prevent `deprecation.warn` from filing duplicate warnings

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7719]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Deprecation warnings fire multiple times (even for the same warning). This spams dev's consoles and is... not great.

### Request

Add some hashing of deprecation warnings so that duplicate warnings don't get fired.

### Alternatives considered

N/A

### Additional context

N/A

## To fix

First reproduce the issue.
1) Add the following code to the playground:
```
deprecation.warn('test warning', 'vA', 'vB', 'test substitute');
deprecation.warn('test warning', 'vA', 'vB', 'test substitute');
```
2) Run `npm run start` and observe that two warnings get logged to the browser console.

Then fix the issue.
1) Add a new module-local [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) to the deprecation file.
2) Concatenate all of the parameters, check if that exists in the set. If it does, return (the deprecation has already been logged). Otherwise, add the concatenation to the set and log the deprecation warning.

Test that the issue was fixed.
1) Run `npm run start` and observe that only one warning is logged.

**Comment by ebrahim95** [comment]
Hello Beks,

I'm having difficulty reproducing the error. 
Should the import statement be added in playground.html?
Because when I do, I get MIME Type disallowed error. 

Thank You,
Ebrahim

**Comment by BeksOmega** [comment]
Ah sorry about that @ebrahim95 It should have been:

```
Blockly.utils.deprecation.warn('test warning', 'vA', 'vB', 'test substitute');
Blockly.utils.deprecation.warn('test warning', 'vA', 'vB', 'test substitute');
```
