### ISSUE TITLE
Function copy/paste bug

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#772]
Steps to reproduce:
1) Add function "do something" to the workspace
2) Add variable "x" to function definition
3) Drag a caller function "do something" into the workspace
4) Copy caller block to clipboard
5) Open function definition and rename variable "y"

This is what the workspace looks now:

![screen shot 2016-11-21 at 6 54 23 pm](https://cloud.githubusercontent.com/assets/13686399/21068647/4d0125cc-be28-11e6-9872-d4c3f52022b4.png)

6) Paste caller block from clipboard

This results in:
![screen shot 2016-11-21 at 6 54 34 pm](https://cloud.githubusercontent.com/assets/13686399/21068654/5ab6d8c4-be28-11e6-9753-c20d7fdd7956.png)

Notice:
- The original block has its input renamed to "x"
- The pasted block doesn't match the new definition "do something2"

**Comment by picklesrus** [comment]
This might be related to https://github.com/google/blockly/issues/503

**Comment by rachel-fenichel** [comment]
After #803 the original caller block will have the correct input name, but the pasted caller block will not be renamed to "do something2" even though it should be.

**Comment by samelhusseini** [comment]
This no longer repro's, followed the steps above and got: 

![Screen Shot 2020-01-16 at 12 55 43 PM](https://user-images.githubusercontent.com/16690124/72562117-87d2a900-385f-11ea-8b79-d7f6685d38e6.png)
