### ISSUE TITLE
BlocklyOptions interface with null

### ISSUE THREAD

**Issue by SerSerch** [google/blockly#7728]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Hello!
I am developing the [flutter_blockly](https://github.com/SerSerch/flutter_blockly) package.
It works through a web browser, but I have a problem with [null safety](https://dart.dev/null-safety).
According to the documentation [BlocklyOptions interface](https://developers.google.com/blockly/reference/js/blockly.blocklyoptions_interface)
we can pass in null parameters, but it makes the wrong render.
I would be grateful if you could fix it
```js
// defaultType !== null
// undefined !== null
// false !== null

export interface BlocklyOptions {
    collapse?: null | boolean;
    comments?:  null | boolean;
    css?:  null | boolean;
    disable?:  null | boolean;
    grid?:  null | GridOptions;
    horizontalLayout?:  null | boolean;
    // ......
}

inject(container: Element | string, opt_options?: null | BlocklyOptions) {
  const css = opt_options?.css ?? true;
  const scrollbars = opt_options?.scrollbars ?? true;
  // ..... and other options need to be checked
}
```

so far I've solved it with the function
```js
function nullToUndefined(data, defaultData) {
  if (data === null || typeof data === 'undefined') {
    return defaultData;
  } else if (Array.isArray(data)) {
    return data.map(item => nullToUndefined(item, defaultData?.[0]));
  } else if (typeof data === 'object') {
    const tempObj = {};
    for (let key in data) {
      tempObj[key] = nullToUndefined(data[key], defaultData?.[key]);
    }
    return tempObj;
  } else {
    return data;
  }
}
```

### Reproduction steps

1. create html fullscreen container `id="blocklyEditor"`
2. create options
```js
const options = {
    grid: {
      spacing: 20,
      length: 3,
      colour: '#ccc',
      snap: true,
    },
    toolbox: null,
    collapse: null,
    comments: null,
    css: null,
    disable: null,
    horizontalLayout: null,
    maxBlocks: null,
    maxInstances: null,
    media: null,
    modalInputs: null,
    move: null,
    oneBasedIndex: null,
    readOnly: null,
    renderer: null,
    rendererOverrides: null,
    rtl: null,
    scrollbars: null,
    sounds: null,
    theme: null,
    toolboxPosition: null,
    trashcan: null,
    maxTrashcanContents: null,
    plugins: null,
    zoom: null,
    parentWorkspace: null,
  };
```
3. inject
```js
Blockly.inject(document.querySelector('#blocklyEditor'), options);
```

### Screenshots

![image](https://github.com/google/blockly/assets/26460350/8a69356f-c738-48de-9fca-d7563c6ad558)

**Comment by maribethb** [comment]
Hello, you should not pass null for the options you don't want to set. You can leave them as undefined. As far as I'm aware, the documentation you linked to shows they can be undefined, but not null. If there's a place it does say null, please let us know.

**Comment by SerSerch** [comment]
@maribethb Hello!
There is no undefined in dart. So I have to always use the function "nullToUndefined"?
It is not difficult for me, but I thought that it is possible to add null support to the BlocklyOptions interface.

**Comment by maribethb** [comment]
Unfortunately I'm not familiar with Dart or Flutter. You can try asking this question on the forum and perhaps someone in the community can help you. The BlocklyOptions interface is not the only place where the difference between null and undefined can be important, so this is probably something you need to solve in general rather than asking us to use them interchangeably. Is it possible to just not include the properties that should be undefined in the object you pass to Blockly?

**Comment by SerSerch** [comment]
@maribethb This is only possible with the nullToUndefined function or to check for null separately for each [property](https://github.com/SerSerch/flutter_blockly/blob/main/lib/src/types/blockly_options.dart#L157)

You can also get BlocklyOptions from the backend. Then you need to replace null with undefined.

In my case, I invented such the function, but it would be nice not to have to think about whether it is possible to pass null.
