### ISSUE TITLE
Edge bug: Highlighting usually doesn't go away when mousing out of block in flyout.

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#773]
So far, I've only seen this on Edge and IE11.

Mouse over and out of some blocks in a flyout (either from toolbox or always open).

Sometimes the yellow border goes away when I mouse out. Usually not.

**Comment by ctrowat** [comment]
We are also noticing this issue in IE/Edge even with a current version of the master branch.  Obviously it's not a huge deal but it looks kind of bad

**Comment by gonfunko** [comment]
Closing since we've dropped support for IE.
