### ISSUE TITLE
After dragging many blocks for a period of time, the console prompts that the memory overflows.

### ISSUE THREAD

**Issue by tracer1023** [google/blockly#7738]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

After dragging many blocks for a period of time, the console prompts that the memory overflows.

### Reproduction steps

1. Drag blocks
2. Block following cannot trigger dragEnd event

3.

**Comment by tracer1023** [comment]
Uploading VID_20231227_111408.mp4…

**Comment by tracer1023** [comment]
![Uploading 5.png…]()

**Comment by maribethb** [comment]
Can you provide more detailed reproduction steps, please? Your video and image did not upload. You may also be able to upload some profiling information from developer tools that would assist us in debugging. Thanks!

**Comment by maribethb** [comment]
Hello, without further information we are unable to debug this with you.

Please consider posting in the forum if you would still like help and can provide additional information.
