### ISSUE TITLE
Documentation for creating a new generator

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#774]
This is missing from the developers site.  In the meantime, here is some basic information:

https://groups.google.com/forum/#!topic/blockly/RO3Ep6VrRRY

**Comment by MNSDivya** [comment]
@rachel-fenichel 
I could see some info regarding Code generators. Is there anything else you expect to add? 
https://developers.google.com/blockly/guides/configure/ios/code-generators?hl=en

**Comment by rachel-fenichel** [comment]
Written and published: https://blocklycodelabs.dev/codelabs/custom-generator/index.html#0
