### ISSUE TITLE
Move build scripts into a subdirectory

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#7758]
This is part of the [monorepo project](https://github.com/google/blockly/issues/7755).

- Move build scripts (for `core` directory) into a subdirectory.
- Check that build and test scripts continue to work after the move.
  - Including through github actions and release workflow.
- Decide if any other scripts should be moved at the same time.

**Comment by cpcallen** [comment]
I'm not sure I understand the purpose of this task.  Surely all the build scrips for the core repository should move, along with all the other pre-existing contents of that repository, to the same subdirectory?  E.g., if `core/` becomes `blockly/core/`, `blocks/` becomes `blockly/blocks/` etc. then the scripts will naturally follow to `blockly/scripts/`?

**Comment by rachel-fenichel** [comment]
This was my misunderstanding of the plan. The other issue (moving core) covers this one.
