### ISSUE TITLE
Default Context Menu is not appearing anymore after upgrading from 9.2.1 to any higher version

### ISSUE THREAD

**Issue by BriceFaller** [google/blockly#7776]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

I updated my version of Blockly  to the 10.2.2 (and theme-dark, therme-modern) and realized the contextual menu is not showing anymore on the right click.

It seems that just by going from 9.2.1 to 9.3.0 the menu is not showing anymore.

I couldn't find anything on the documentation except creating a custom contextual menu but all I want is to keep the default one.

I'm on Windows, using Chrome.

### Browsers

Chrome desktop

**Comment by maribethb** [comment]
Hello @BriceFaller can you provide more information? This isn't something we're seeing in our normal test environments so we'll need more information before we can help you debug this problem. If you can provide a minimum reproducible example, that would be most helpful. Thanks!

**Comment by BriceFaller** [comment]
Hi @maribethb , 
I'm using blockly on Angular 15.
I followed the documentation to add a custom entry to my context menu and it's working like a charm on the 9.2.1 version.
Here's the code : 
```
const workspaceItem = {
        displayText: 'Hello World',
        preconditionFn: function(scope: any) {
          return 'enabled';
        },
        callback: function(scope: any) {
        },
        scopeType: ContextMenuRegistry.ScopeType.BLOCK,
        id: 'hello_world',
        weight: 100,
      };
ContextMenuRegistry.registry.register(workspaceItem);

this.workspace = inject(blocklyDiv, {
        sounds: false,
        move: {
          scrollbars: true,
          drag: true,
          wheel: true
        },
        collapse: true,
        zoom: {
          controls: true,
          wheel: false,
          startScale: 1.0,
          maxScale: 3,
          minScale: 0.3,
          scaleSpeed: 1.2
        },
        toolbox: activeToolbox.xml || undefined,
        theme
});
```

And here's the result : 
![image](https://github.com/google/blockly/assets/40170252/fcf87825-bb20-48b1-8373-2617c6a088d0)

Unfortunately when I'm updating to 9.3.0 by example, the right click doesn't show the context menu at all, neither on workspace nor block.

**Comment by maribethb** [comment]
Unfortunately, I'm still not able to reproduce this issue when adding the code you've shared to our test playground. So I think this is likely some interaction between other custom code you've written and Blockly. Do you have any errors in the console? Can you turn on event handler breakpoints to see if some other event handler is swallowing events before they get to Blockly?

**Comment by maribethb** [comment]
Hello @BriceFaller without more information there's not a lot we can do here. Feel free to reopen this issue if you can provide a minimum reproducible sample. You can also consider posting on the forum if you'd like additional tips on debugging. Thanks!
