### ISSUE TITLE
Since xml is not deprecated yet... https://developers.google.com/blockly/xml is 404

### ISSUE THREAD

**Issue by mrkprdo** [google/blockly#7803]
### Location

https://developers.google.com/blockly/xml

### Type

- [ ] Text
- [ ] Image or Gif
- [X] Other

### Suggested content

I was trying to understand custom namespacing and was looking at the link defined as the XML namespace (xmlns) in the generated XML. Is there any link that I can look up for more information?

**Comment by mrkprdo** [comment]
lol. not sure if its even still relevant, its been 404 since 2021 when i checked wayback machine :)

**Comment by maribethb** [comment]
This URL is just to give the Blockly XML spec a custom namespace, which according to the XML spec must be in the form of a URI](https://en.wikipedia.org/wiki/XML_namespace). It is not intended to be a real URL with information. If you have specific questions about using XML with Blockly, you can ask on the forum. In general though we don't expect you to be hand-writing or inspecting the generated XML so there's not a lot of documentation on the exact spec.
