### ISSUE TITLE
Handle registering the same field multiple times

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#7804]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

When custom blocks register themselves they also should register the custom fields that they need. This means that a file that defines multiple blocks may register a field multiple times if all of those blocks are installed.

### Request

Check whether the new field being registered under a specific name is the same as the field that was previously registered under that name, and act as a no-op if that's the case.

### Additional context

Part of https://github.com/google/blockly/issues/7226

**Comment by maribethb** [comment]
Closed by #7988 (I tagged the wrong number in that PR)
