### ISSUE TITLE
 Finger following

### ISSUE THREAD

**Issue by tracer1023** [google/blockly#7807]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

When dragging building blocks, they cannot be released and follow the movement

### Reproduction steps

1. blockly v10.3.1

https://github.com/google/blockly/assets/33512446/25635611-9cd5-4ca1-9e61-83bd99b2de18

2. 
3.

**Comment by tracer1023** [comment]
blockly version v10.3.1

**Comment by maribethb** [comment]
Hello, we're not able to reproduce this on our end. Are you able to reproduce this on one of our test sites such as https://blockly-demo.appspot.com/static/tests/playgrounds/advanced_playground.html?

If so, can you provide us more detailed reproduction steps (browser, device, url, etc.)?
If not, then there may be an error in your custom code especially that related to mutators or connection checks. You should check the developer console for any errors.
