### ISSUE TITLE
Blocks deselect when the workspace is dragged

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#7816]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Dragging a workspace should not deselect the currently selected block.

### Reproduction steps

1. Select a block.
2. Drag the workspace

The deselects for no reason.  It doesn't deselect when the workspace is scrolled using the scrollbars.  Likewise there's no deselection when the workspace is zoomed in or out.

**Comment by BeksOmega** [comment]
Deselecting is actually going to be necessary for the new dragging system to work.
