### ISSUE TITLE
Have widget div grab reference to div if it already exists

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7819]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

It seems there are circumstances where a widget div has already been created, but Blockly doesn't have a reference to it (perhaps because it was created by a different instance of Blockly). We should grab a reference to it if it exists.

Related forum post: https://groups.google.com/g/blockly/c/dikX9DqVaR0/m/1PhAXoK2AAAJ

### Reproduction steps

N/A

## To Fix

Modify `createDom` to assign to `containerDiv` if the widget div already exists: https://github.com/google/blockly/blob/0b25a8a27f156a8104cd242ee68de304506693cd/core/widgetdiv.ts#L61

**Comment by BeksOmega** [comment]
Heya @lotusotho thanks for grabbing this issue! Could you comment there so I can assign you?

**Comment by lotusotho** [comment]
Of course! I'll be resolving this issue.

**Comment by BeksOmega** [comment]
Closed by #7980
