### ISSUE TITLE
Verify code demo will not be impacted by moving blocks to plugins

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#7826]
The storage demo in `demos/storage` was created to demonstrate how to save and load Blockly programs from a web app, but is known to be used by members of the public as a way to provide a URL that will load a particular Blockly program.

As we are planning to delete some of the current blocks from this repository after moving them to the blockly-samples repository (see also #7226), this has the potential to result in some of the saved Blockly programs in the storage backend becoming un-loadable.

A quick look at the `demos/storage/index.html` suggests that this demo has provided only a very limited toolbox, and it does not appear that any of the provided blocks are on the to-delete list, but it would be worth verifying what blocks are actually used in stored programs, since programs may have been created with blocks not currently provided in the toolbox but still present (until now) in the block definitions in `blocks/`.

@NeilFraser may be able to assist with auditing the contents of the storage backend.

**Comment by NeilFraser** [comment]
After talking with Chris, we agreed that this bug is about the Code Demo, not the Storage Demo.  Storage Demo is unaffected.

Yes, the Code Demo will be affected as it has colour blocks.  That said, the colour blocks are useless in the code demo since there is not graphical output.  The only I/O is `prompt` and `alert`.

Rather than adding the colour picker, I vote we just delete the 'Colour' category from the Code Demo.  Loading saved programs with those blocks will fail.  Do we want to invest time in auditing the database to see how many such programs exist?

**Comment by rachel-fenichel** [comment]
If there are any uses at all, we want to keep them working. Your choice whether that means you think it's worth auditing the database or just implementing https://github.com/google/blockly/issues/7938 but the only count that would lead to removing the blocks is zero uses.

**Comment by NeilFraser** [comment]
I've pulled down 10,135 programs saved by the code demo (after filtering out the Block Factory which shares the same database).  Of these, exactly 100 use colour blocks.  I've individually loaded each one, and every one is a garbage program.  Here are some samples:

<img width="442" alt="Screenshot 2024-03-28 at 23 40 00" src="https://github.com/google/blockly/assets/250480/bcf7a215-71d4-427e-a9fc-3dd3d089c96a">
<img width="497" alt="Screenshot 2024-03-28 at 23 39 44" src="https://github.com/google/blockly/assets/250480/08a9ebad-22d5-454d-8144-bf36d9da7355">
<img width="399" alt="Screenshot 2024-03-28 at 23 39 26" src="https://github.com/google/blockly/assets/250480/3669de2e-a29a-4357-97c8-7f08aafa75c6">
<img width="237" alt="Screenshot 2024-03-28 at 23 39 00" src="https://github.com/google/blockly/assets/250480/83cadadd-5f08-4444-b0bc-c0f3947a230c">
<img width="559" alt="Screenshot 2024-03-28 at 23 37 50" src="https://github.com/google/blockly/assets/250480/2a15909a-d29f-4273-ba0d-53c979863862">
<img width="405" alt="Screenshot 2024-03-28 at 23 36 23" src="https://github.com/google/blockly/assets/250480/01be5b25-22bd-481d-a52f-5ba8d9aa2659">
<img width="371" alt="Screenshot 2024-03-28 at 23 35 09" src="https://github.com/google/blockly/assets/250480/e2797bdc-b6bb-4875-813a-3aded4b69236">

**Comment by NeilFraser** [comment]
BTW, does anyone know if this issue affects our "Try it" demo at https://developers.google.com/blockly

If so, deleting the colour category is even easier since there's no save database.  Note that this demo also has multiline text fields.

**Comment by rachel-fenichel** [comment]
Good point. Can you clean the colour and multiline text blocks out of that as well?
