### ISSUE TITLE
Perf: Grid still repaints during workspace drag

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#784]
The grid is still causing repaints during a workspace drag.  The paint time is significantly less, but there should be a way to move it to the drag surface like we do the blocks & bubbles.

**Comment by rachel-fenichel** [comment]
Another option: hide the grid during a ws drag.

**Comment by MNSDivya** [comment]
@picklesrus / @rachel-fenichel Can you please share more info on this defect?

**Comment by BeksOmega** [comment]
I don't think there's anything we can do to eliminate repaints in this case, especially because we're getting rid of the drag surfaces.
