### ISSUE TITLE
Firing delete events before setting `disposing` to `true` causing issues errors in the dynamic connections

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#7864]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Currently we set `disposing` after we fire a delete event for the block (I'm not sure why this is). This causes issues for the dynamic connections plugin because the delete event triggers serialization, which triggers the block to be reconstructed due to historical reasons (the plugin was originally serialized with the wrong XML format, and we need to fix that). However the reconstruction fails because the renderer constants have already been disposed before it is triggered. So anything that references `getConstants()!` assuming it should exist during rendering triggers an error.

### Reproduction steps

1. Go to the [dynamic connections blocks plugin demo page](https://google.github.io/blockly-samples/plugins/block-dynamic-connection/test/index.html).
2. In the console run `Blockly.getMainWorkspace().dispose()`.
3. Observe the error

### Stack trace

```shell
blockly_compressed.js:708 Uncaught TypeError: Cannot read properties of null (reading 'FIELD_TEXT_BASELINE_CENTER')
    at FieldLabel$$module$build$src$core$field_label.createTextElement_ (blockly_compressed.js:708:211)
    at FieldLabel$$module$build$src$core$field_label.initView (blockly_compressed.js:897:1147)
    at FieldLabel$$module$build$src$core$field_label.init (blockly_compressed.js:706:494)
    at $.ValueInput$$module$build$src$core$inputs$value_input.insertFieldAt (blockly_compressed.js:900:189)
    at $.ValueInput$$module$build$src$core$inputs$value_input.appendField (blockly_compressed.js:899:555)
    at BlockSvg$$module$build$src$core$block_svg.addFirstInput (dynamic_text_join.ts:282:42)
    at BlockSvg$$module$build$src$core$block_svg.addItemInputs (dynamic_text_join.ts:264:24)
    at BlockSvg$$module$build$src$core$block_svg.finalizeConnections (dynamic_text_join.ts:219:10)
    at BlockSvg$$module$build$src$core$block_svg.mutationToDom (dynamic_text_join.ts:52:10)
    at blockToDom$$module$build$src$core$xml (blockly_compressed.js:167:332)
createTextElement_ @ blockly_compressed.js:708
initView @ blockly_compressed.js:897
init @ blockly_compressed.js:706
insertFieldAt @ blockly_compressed.js:900
appendField @ blockly_compressed.js:899
addFirstInput @ dynamic_text_join.ts:282
addItemInputs @ dynamic_text_join.ts:264
finalizeConnections @ dynamic_text_join.ts:219
mutationToDom @ dynamic_text_join.ts:52
blockToDom$$module$build$src$core$xml @ blockly_compressed.js:167
blockToDomWithXY$$module$build$src$core$xml @ blockly_compressed.js:165
BlockDelete$$module$build$src$core$events$events_block_delete @ blockly_compressed.js:1110
dispose @ blockly_compressed.js:1118
dispose @ blockly_compressed.js:1189
clear @ blockly_compressed.js:1048
clear @ blockly_compressed.js:1105
dispose @ blockly_compressed.js:1044
dispose @ blockly_compressed.js:1073
dispose @ blockly_compressed.js:1482
dispose @ blockly_compressed.js:1073
(anonymous) @ VM341:1
```

### Additional info

We can fix this by moving `disposing` to be set before the delete event is constructed, and then have `mutationToDom` check whether the block `isDeadOrDying()`.

We could also modify things to check whether the constants exist instead of asserting that they do exist.

Would love opinions ^^^

We need to fix this before we can release the 1.0 of the dynamic connection blocks plugin.

**Comment by maribethb** [comment]
- Let's try to set `disposing` earlier in the process of disposing a workspace. That just makes sense. But let's call that a breaking change because who knows who might be relying on this quirk. And if we discover that core itself is relying on this quirk let's revisit this depending on how complicated it gets.
- Regardless of the above, let's check that constants exist rather than asserting. we should be moving away from using `!` and doing more type/nullable checks for safety

**Comment by monkeeee** [comment]
Hello, this bug is not fixed for me in version 0.7.1. To reproduce try the demo https://google.github.io/blockly-samples/plugins/block-dynamic-connection/test/index.html and connect the dynamic_text_join like this or with any other block:

![image](https://github.com/google/blockly/assets/61760112/9a86222e-fff7-4560-b25f-88f1ca5f319b)

now call Blockly.getMainWorkspace().dispose() and the same error as before is beeing thrown

**Comment by roddc** [comment]
I still have this error in v0.7.9

**Comment by roddc** [comment]
I still have this error in v0.7.9
