### ISSUE TITLE
Dropdown field arrow misplaced on Safari when using Thrasos renderer

### ISSUE THREAD

**Issue by mikeharv** [google/blockly#7890]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

When using the Thrasos renderer on Safari, all arrows in dropdown fields appear too high. This is evidently because Safari does not inherit the property `dominant-baseline: "central"` from the parent element. 

Note: Code.org fixed this by overriding `createTextArrow_` to add the attribute to the SVG element: https://github.com/code-dot-org/code-dot-org/pull/55480

### Reproduction steps

Observe any dropdown field while using Safari with Thrasos.

### Screenshots

<img width="173" alt="image" src="https://github.com/google/blockly/assets/43474485/7a7109d3-5052-45fc-bc6c-dcf050b8a840">

**Comment by maribethb** [comment]
Thanks for reporting! Would you be interested in putting up a PR for the fix y'all have? :)
