### ISSUE TITLE
Save/Reload: Function definition block added, copy of "do something"

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#792]
Before:

<img width="267" alt="screen shot 2016-12-21 at 9 02 53 am" src="https://cloud.githubusercontent.com/assets/9916202/21398588/ae7e8bd6-c75c-11e6-98e0-fab2a3f2fe7a.png">

After:

<img width="468" alt="screen shot 2016-12-21 at 9 03 30 am" src="https://cloud.githubusercontent.com/assets/9916202/21398597/b9dd4f1c-c75c-11e6-88c9-f8aa278e73ac.png">

In addition to the calling block now calling the wrong function (#503, now with the wrong parameters), a new copy of "do something" (with rename) has been added.

**Comment by rachel-fenichel** [comment]
Fixed by #803
