### ISSUE TITLE
Workspace shifts position when deleting blocks via drag to toolbox.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#793]
Initial conditions:
 * More than one block on the workspace.
 * All block stacks near the toolbox (left edge in LTR).
 * No blocks near the opposite edge (right edge in LTR). Neither by placement or by long chaining inputs.
 * No blocks above or below the visible bounds of the workspace (need to confirm).

Action:
 * Drag one block over the toolbox to delete it.

Expected:
 * Other blocks remain in their initial location.

Observed:
 * Workspace scrolls away from the toolbox, making all blocks appear to jump.

**Comment by rachel-fenichel** [comment]
Fixes by #1078
