### ISSUE TITLE
Official docs are ahead of develop

### ISSUE THREAD

**Issue by pelikhan** [google/blockly#796]
It seems that the image support in dropdown is not yet in master but in the developer docs at https://developers.google.com/blockly/guides/create-custom-blocks/dropdown-menus#images

**Comment by NeilFraser** [comment]
My fault.  Image support was checked into the 'develop' branch, and I pushed the documentation before going on paternity leave.  However, the holidays have meant that the routine push from develop to master is somewhat overdue.  I expect that master will be updated soon after the team returns in the new year.

**Comment by pelikhan** [comment]
Congratulations on the kiddo and enjoy the break!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
