### ISSUE TITLE
Parameter adding modal overlaps when name is too long

### ISSUE THREAD

**Issue by asanzo** [google/blockly#798]
If the parameter name is too long, the "input name" block gets behind the "inputs" block.

Example:

![seleccion_019](https://cloud.githubusercontent.com/assets/5421992/21483892/a9febeea-cb68-11e6-8bae-dec6e645781d.png)

It would be great if the "inputs" block could move to the right if the text is long.

**Comment by psyduck1203** [comment]
can i work on this issue ?

**Comment by gonfunko** [comment]
This no longer repros, the bubble resizes to fit the flyout and workspace.
