### ISSUE TITLE
Blockly code generation is broken! Please fix!

### ISSUE THREAD

**Issue by gmp26** [google/blockly#80]
The example below shows that [2 - [3+4]] is handled differently to [2 * [3+4]].

Blocks should act as parentheses -- as the [2 * [3 + 4]] example and the discussion in https://developers.google.com/blockly/custom-blocks/operator-precedence indicates.

The interpretation of [2 - [3+4]] as (2 - 3 + 4) = 3 instead of (2 - (3+4)) = -5 is plainly inconsistent and extremely unfortunate if blockly is to be taken seriously as an educational application.

![2015-03-03 01 02 36 pm](https://cloud.githubusercontent.com/assets/141701/6462943/9b58ac76-c1a5-11e4-84cb-290d89eed25c.png)

**Comment by gmp26** [comment]
Any thoughts on how this should be fixed? Happy to submit a PR.

**Comment by gmp26** [comment]
See also #57, which is similarly gross.

**Comment by gmp26** [comment]
It's possible to generate the correct code in this case by patching in a new precedence level
```
Blockly.JavaScript.ORDER_SUBTRACTION=5.5;
```
to rank subtraction above addition. This is not a correct or complete solution. It does not cater for the fact that subtraction is not associative, and it does not handle a similar issues that will appear with division.

Fixing this bug will certainly break some existing programs, but that's preferable to breaking a lot of young programmers.

**Comment by gmp26** [comment]
Here are the similar issues that are caused because subtraction and division are not associative.

![2015-03-03 03 21 33 pm](https://cloud.githubusercontent.com/assets/141701/6465442/18d10a64-c1b9-11e4-8e00-32b919847a3a.png)


![2015-03-03 03 14 04 pm](https://cloud.githubusercontent.com/assets/141701/6465358/7e699b94-c1b8-11e4-968d-4041ecba135b.png)

**Comment by gmp26** [comment]
And here's the multiplicative case that's analogous to the first problem. This one can be fixed by changing the priority of division slightly.
![2015-03-03 03 29 45 pm](https://cloud.githubusercontent.com/assets/141701/6465644/4d627618-c1ba-11e4-8ed8-34d31a9fe2ef.png)

**Comment by gmp26** [comment]
Pending resolution of this, I'd suggest removing all parenthesis removal code. At least evaluations will then be correct.

**Comment by gmp26** [comment]
So a better but still incomplete patch is to `generators/javascript/math.js`. Other language generators are similarly affected and would need their patches.
```
line 59:  return [code, Blockly.JavaScript.ORDER_NONE];
```

**Comment by NeilFraser** [comment]
Fixed:
https://github.com/google/blockly/commit/57d0ffa68b110b7b6bd8f95f78ef0bf6ccae8d51

The bug was introduced here:
https://code.google.com/p/blockly/source/diff?spec=svn1568&r=1568&format=side&path=/trunk/core/generator.js

**Comment by gmp26** [comment]
Wonderful! Thanks so much Neil.

Any chance the new code could also go live at https://blockly-demo.appspot.com and similar?

**Comment by NeilFraser** [comment]
Sorry, I was traveling and didn't want to risk a push to production on an unreliable connection.  The new version went out two days ago.
