### ISSUE TITLE
Deleting large amounts of blocks takes forever

### ISSUE THREAD

**Issue by bruh-9000** [google/blockly#8022]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Deleting many blocks will take an extremely long amount of time.

### Request

Make deleting blocks have the speed scale based on the amount of blocks present.

**Comment by maribethb** [comment]
@bruh-9000 feel free to reopen this if you can provide additional info! Without that it's tough for us to take action. Thanks!
