### ISSUE TITLE
Included code snippets are not working

### ISSUE THREAD

**Issue by yasanthaniroshan** [google/blockly#8028]
### Location

https://developers.google.com/blockly/guides/create-custom-blocks/block-colour#defining_the_block_colour

### Type

- [X] Text
- [ ] Image or Gif
- [ ] Other

## Code snippet in Docs
```javascript
Blockly.colour.setHsvSaturation() // 0 (inclusive) to 1 (exclusive), defaulting to 0.45
Blockly..colour.setHsvValue() // 0 (inclusive) to 1 (exclusive), defaulting to 0.65 
```
## Description
- Code snippet given in above docs have grammer errors ("double dots")
- Given functions `setHsvSaturation()` and `setHsvValue()` not accessible

## Suggestion
The code snippet should be changed as follows
```javascript
Blockly.utils.colour.setHsvSaturation() // 0 (inclusive) to 1 (exclusive), defaulting to 0.45
Blockly.utils.colour.setHsvValue()// 0 (inclusive) to 1 (exclusive), defaulting to 0.65 
```

**Comment by maribethb** [comment]
Hi, thanks for filing this issue! I've made an edit to the docs that should be live soon.
