### ISSUE TITLE
make two input in one line display or add a removeField method

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#8045]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Request

![image](https://github.com/google/blockly/assets/42778/d310605a-5af4-47d5-8199-9e3ba3e0337f)
I have two input (dummy input and value input),it will return in a new line,dose any way could make this in a single line ,
in fact , I was use some dynamic way(javascript to change the block shape,so need use removeInput(current seems didn't have direct removeField method,so I need make dynamic part in a single input for remove use) 
could add removeField method also could fix this problem

**Comment by cpcallen** [comment]
Questions like this should be posted to [the Blockly forum](https://groups.google.com/g/blockly), but in short: don't use a dummy input, just put all the fields into the value input.

If you have further questions, please follow-up on the forum, not here—that will make it easier for others looking for help about the same topic to find the question and answer.
