### ISSUE TITLE
XML/JSON change for disabled blocks

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#8095]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

The XML save format is changing from 
```
disabled="true"
```
to
```
disabled-reasons="MANUALLY_DISABLED"
```
Loading the former in v11 results in this console warning:
```
disabled was deprecated in v11 and will be deleted in v12.
Use disabled-reasons with the value "MANUALLY_DISABLED" instead.
```
It is utterly unprecedented to deprecate a core part of the XML parser.  XML lives forever in external databases.  This implies that v12 will no longer be able to load existing user code!

The offending code is here:
https://github.com/google/blockly/blob/rc/v11.0.0/core/xml.ts#L1024

### Reproduction steps

1. Open the 'Logic' category in the playground.  Since the 'null' block is disabled, a warning is printed.

**Comment by NeilFraser** [comment]
The same issue is true for JSON serialization.

Furthermore, the new XML/JSON serialization is not backwards compatible.  In practice this is a lesser problem, but none-the-less, there's no reason to needlessly break V10 versions of Blockly getting V11 serialization.

**Comment by NeilFraser** [comment]
This was introduced by #7958.  @johnnesky

**Comment by BeksOmega** [comment]
Good point, we shouldn't delete support for the old format, but we should migrate to the new one, because it fixes several bugs.

So the TODO here is to remove the deprecation warnings.

**Comment by NeilFraser** [comment]
Ok, I'll take it.

**Comment by johnnesky** [comment]
Yeah we can remove the deprecation warnings. 

If you don't mind redundant data, we could also continue to serialize the old properties (when the disabled reason `MANUALLY_DISABLED` is present) for backwards compatibility.

**Comment by BeksOmega** [comment]
I think it's fine as long as we **deserialize** the old attributes. Serializing them is less important, and there are partners that really care about keeping save file sizes small since they're financially constrained (I.E. App Inventor will be grumpy with me).
