### ISSUE TITLE
Connection DB error in V11

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#8096]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Dragging blocks around can trigger stack traces very reliably in Chrome & Safari (but not Firefox).  Can't recreate on V10.

### Reproduction steps

1. Using a Webkit browser, open the playground.
2. Click 'Airstrike'
3. Take a 'Set' block from the toolbox, and wave it around.

The console will fill up with the error below.

### Stack trace

```shell
[Error] Unhandled Promise Rejection: Error: Unable to find connection in connectionDB.
	removeConnection (connection_db.js:117)
	moveTo (rendered_connection.js:162)
	updateConnectionLocations (block_svg.js:497)
	updateComponentLocations (block_svg.js:488)
	moveBy (block_svg.js:261)
	positionNearConnection (block_svg.js:1226)
	(anonymous function) (insertion_marker_previewer.js:118)
```

### Browsers

Chrome desktop, Safari desktop

**Comment by NeilFraser** [comment]
Safari and Opera seem to get this error 10x more than Chrome.  Feels like a race condition.

**Comment by BeksOmega** [comment]
I haven't been able to reproduce this one :/ Which definitely feels like race condition territory. Tried performance throttling and still couldn't repro.

**Comment by NeilFraser** [comment]
https://github.com/google/blockly/assets/250480/695a3d6e-c270-43a2-abe8-9f17bdc5c045
