### ISSUE TITLE
Delete animation and sound don't play when dragging blocks to a delete area.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#8098]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Dragging a block to the trash or the toolbar deletes the block, but does not play the delete sound.  This is a regression in V11, it works properly on V10.  All browsers.

### Reproduction steps

1. Drag a block to the trash.

**Comment by NeilFraser** [comment]
Deleting a block using the delete key does play the sound.  Also the click sound works fine.

**Comment by BeksOmega** [comment]
This also affects the delete animation.
