### ISSUE TITLE
Paste places the blocks in strange places

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#8099]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

Pasting blocks in V11 no longer pastes them in a neat diagonal.  The pasting location jumps all over the place, up, down, overlaping.  All browsers.  Worked fine in V10.

### Reproduction steps

1. Create a loop block.  Nest a loop block inside the first loop.
2. Copy the inner loop block with the keyboard shortcut.
3. Repeatedly paste with the keyboard shortcut.

### Screenshots

V10 is good:
<img width="511" alt="Screenshot 2024-05-13 at 19 19 45" src="https://github.com/google/blockly/assets/250480/ad993530-db63-4ae3-a306-3d8a48ec8d51">

V11 is unexpected:
<img width="491" alt="Screenshot 2024-05-13 at 19 19 08" src="https://github.com/google/blockly/assets/250480/72b516a0-f0c5-4d7a-ae34-8d6444255d96">

**Comment by maribethb** [comment]
possibly related to #6848
