### ISSUE TITLE
Unable to build compressed version with closure service as of 3/8

### ISSUE THREAD

**Issue by tarunpondicherry** [google/blockly#81]
Something seems to have changed in the closure compiler service on 3/9 that prevents blockly from building the compressed files. I have successfully built them prior to this date (on 3/8).

Steps to reproduce:
Clone blockly
Download the closure zip file from the link provided by build.py
Run build.py

Console output:
...
SUCCESS: msg/js/zh-hant.js
SUCCESS: blockly_uncompressed.js
FATAL ERROR
required "goog.html.SafeHtml" namespace never provided
core/connection.js at line 33:
goog.require('goog.html.SafeHtml');

**Comment by sawady** [comment]
It happend the same to me.

**Comment by NeilFraser** [comment]
The Closure Compiler team have fixed the issue.
