### ISSUE TITLE
Blocks jump across workspace in Safari V11

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#8105]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

Dragging some assembly of blocks in the V11 playground in Safari results in unexpected jumps instead of aligning with the grid.

Can not recreate in V10.  Doesn't seem to be reproducible in other browsers.

### Reproduction steps

1. Create the shown block structure.
2. Drag it around the workspace.

### Screenshots

https://github.com/google/blockly/assets/250480/92f80c12-95a1-4a25-a6ab-03d939dec3b7

### Browsers

Safari desktop

**Comment by BeksOmega** [comment]
Maribeth wasn't able to reproduce this yesterday.

I think this might also be fixed with https://github.com/google/blockly/pull/8120, @NeilFraser can you test when you next sit down to do testing.

**Comment by NeilFraser** [comment]
Looks good to me on Safari.  Closing!
