### ISSUE TITLE
V11 advanced playground context menu is broken

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#8108]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

The advanced playground has a couple of errors which may be related to versions:

* `Colour` category breaks when opening toolbox.
* Right-clicking on the workspace generates: `Uncaught TypeError: Blockly.ContextMenu.workspaceCommentOption is not a function`

**Comment by rachel-fenichel** [comment]
Code for configuring the context menu in `tests/playgrounds/advanced_playground.html`: 
```
      function configureContextMenu(menuOptions, e) {
        var workspace = this;
        var screenshotOption = {
          text: 'Download Screenshot',
          enabled: workspace.getTopBlocks().length,
          callback: function () {
            downloadScreenshot(workspace);
          },
        };
        menuOptions.push(screenshotOption);

        // Adds a default-sized workspace comment to the workspace.
        menuOptions.push(
          Blockly.ContextMenu.workspaceCommentOption(workspace, e),
        );
      }
```

There's a bad access on the last line: `menuOptions.push(Blockly.ContextMenu.workspaceCommentOption(workspace, e));`

**Comment by maribethb** [comment]
Some of these issues are already noted here https://github.com/google/blockly-samples/issues/2345 and have already been fixed.

But the context menu one is part of the configuration in core and does need to be fixed.
