### ISSUE TITLE
Fire workspace comment resize events

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8113]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Problem

Currently we don't do this and it wasn't planned, but it might be nice to fire resize events for workspace comments. Main use-case being RTC

### Request

Fire an event with the old size and the new size of the workspace comments after a resize.

**Comment by maribethb** [comment]
@johnnesky this is the issue in core to fire resize events for workspace comments if you're interested

**Comment by johnnesky** [comment]
Thanks. Related to https://github.com/google/blockly-samples/issues/2330
