### ISSUE TITLE
Buttons for dynamic drop-down blocks in playground are broken

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8118]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

The buttons attempt to call a prompt function that doesn't exist.

### Reproduction steps

1. Switch to the test blocks in the playground.
2. Open up the dropdown block tests.
3. Try the "Add option" button. Observe the error.

### Stack trace

```shell
index.js:2 Uncaught TypeError: t.prompt is not a function
    at c (index.js:2:23634)
    at FlyoutButton.onMouseUp (flyout_button.ts:339:9)
    at SVGGElement.wrapFunc (browser_events.ts:63:14)
```

**Comment by maribethb** [comment]
This was a bug in the block-test plugin, not core. It was already fixed in the advanced playground. Core isn't using the latest fixed version. https://github.com/google/blockly-samples/pull/2344
