### ISSUE TITLE
not shown in bootstrap tabset.need resize window will show

### ISSUE THREAD

**Issue by coolxv** [google/blockly#812]
`<div class="wrapper-md">`
    `<tabset class="tab-container">`
        `<tab>`
            `<tab-heading>`
                `<span translate="content.common.BASE">Base Info</span>`
            `</tab-heading>`
            `<div class="row" ng-controller="StepCtrl">`
                `<div class="col-md-12">`
                    `<xml id="toolbox" style="display: none">`
                        `<category name="Control" colour="210">`
                            `<block type="controls_if"></block>`
                            `<block type="controls_whileUntil"></block>`
                            `<block type="controls_for"></block>`
                        `</category>`
                        `<category name="Logic" colour="110">`
                            `<block type="logic_compare"></block>`
                            `<block type="logic_operation"></block>`
                            `<block type="logic_boolean"></block>`
                        `</category>`
                    `</xml>`
                    `<div id="blocklyDiv" style="height: 480px; width: 100%;"></div>`
                `</div>`
            `</div>`
        `</tab>`
        `<tab>`
            `<tab-heading>`
                `<span translate="content.test.PREPARE">Prepare</span>`
            `</tab-heading>`
            `<div class="row">`
            `<div class="col-md-12">`
                    `<div style="height:480px;width:100%">`
                    `</div>`
                `</div>`
            `</div>`
        `</tab>`
    `</tabset>`
`</div>`

===============debug info===================

`<div id="blocklyDiv" style="height: 480px; width: 100%;">`
`<div class="injectionDiv" dir="LTR">`
` <div class="blocklyToolboxDiv" dir="LTR" **style="left: 0px; height: 0px;"**>`

**Comment by rachel-fenichel** [comment]
Can you explain what the bug is?

**Comment by coolxv** [comment]
Reason:
‘<div id="injectionDiv"> , offsetParent=null,offsetTop=0,offsetLeft=0,offsetWidth=0,offsetHeight=0,in Blockly.svgResize function

**Comment by coolxv** [comment]
<img width="580" alt="default" src="https://cloud.githubusercontent.com/assets/12321831/21875936/8224989a-d8ba-11e6-9726-f9eb35e3dae6.PNG">
<img width="533" alt="2" src="https://cloud.githubusercontent.com/assets/12321831/21875937/83b5c288-d8ba-11e6-8c57-ee805850cbcb.PNG">

**Comment by rachel-fenichel** [comment]
[Blockly.svgResize](https://github.com/google/blockly/blob/f5f6d69d5ef86d92e249054004c39690b0961f61/core/blockly.js#L164) does not have an offsetParent variable.

I did a quick [search](https://github.com/google/blockly/search?utf8=%E2%9C%93&q=offsetParent); offsetParent doesn't occur in the core Blockly library.

It does appear in two of the demos.  These are examples to get you started, but may need to be modified based on your page structure.

**Comment by coolxv** [comment]
Solve the problem ,use $timeout
```
angular.module('app')
    .directive('blocklyAngular', ['BlocklyAngular','$timeout',function ( BlocklyAngular,$timeout) {
        return {
            restrict: 'E',
            template: '<div style="height:600px;width:100%"></div>',
            link: {
                post:function ($scope, element, attrs) {
                    $timeout(function () {
                        var options = BlocklyAngular.getOptions();
                        var workspace=Blockly.inject(element.children()[0], options);
                        BlocklyAngular.setWorkspace(workspace);
                    }, 0);
                }
            }
        };

    }]);
```
