### ISSUE TITLE
Automated browser tests reference broken or missing categories

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#8132]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

The automated browser tests open all of the categories in the toolbox and drag out each block.

- [ ] There's a hard-coded list of basic categories in `tests/browser/test/toolbox_drag_test.js`, and it includes `Colour`. This category and the associated blocks have been removed from core and need to be removed from this test.
- [ ] There's a hard-coded list of test categories in the same file, including `Validators`. This fails because some of the validator blocks referred to now-removed fields. This has been fixed in the most recent version of dev-tools, so the solution is to update the dependency and then verify that the validators category works again.

### Reproduction steps

1. 
2. 
3.

**Comment by johnnesky** [comment]
I addressed the problems described above, but created https://github.com/google/blockly/issues/8466 to track another problem I discovered in this test.
