### ISSUE TITLE
Workspace comments have no ability to scroll

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#8143]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Description

Unlike for block comments, there's no scrollbar.

In a block comment the mouse wheel will scroll up and down.  In a workspace comment the mouse wheel will zoom in and out.

### Screenshots

<img width="419" alt="Screenshot 2024-05-17 at 15 34 52" src="https://github.com/google/blockly/assets/250480/f2732374-6594-4997-bbe4-4947383b882d">

**Comment by BeksOmega** [comment]
I think this might be WAI. Assigning to myself to check.

**Comment by BeksOmega** [comment]
This is WAI. Matches behavior in MakeCode and Scratch.
