### ISSUE TITLE
Block vanishes while it is being dragged.

### ISSUE THREAD

**Issue by lilliesAndRoses** [google/blockly#815]
If I select a block and drag it - to get it on the workspace from the flyout or to move it in the workspace, it simply disappears. 
Is there any setting that I need to change?

**Comment by rachel-fenichel** [comment]
Hi @lilliesAndRoses,

Please consider mailing the [blockly google group](https://groups.google.com/forum/#!forum/blockly) with questions like this. There's a lot of aggregated experience developing with blockly over there.
