### ISSUE TITLE
Scrollbars are in front of everything

### ISSUE THREAD

**Issue by harbaum** [google/blockly#816]
Scrollbars seem to be in front of everything. This can e.g. be seen if the code demo is scaled down. In the attached screenshot the horizontal **workspace scrollbar** at the screens bottom is i**n front of the toolbox**. In a more complex setup when content is temporarily overlaying the workspace the scrollbars are also in front of that overlay.

![blockly_scrollbars](https://cloud.githubusercontent.com/assets/9105084/21854095/c508a80a-d819-11e6-8179-5e19cd1bf11a.png)

**Comment by harbaum** [comment]
Might be a similar issue as #169

**Comment by picklesrus** [comment]
Good catch. Thanks for the report.

The z-index of the flyout is 20.
The z-index of the scrollbars is 30.
The scrollbar that scrolls the flyout does need to be on top of the flyout, but the workspace scrollbars should be under.  Currently scrollbars don't know much (anything?) about the workspace they scroll, so we'll have to figure out a clean way to distinguish the two so we can set the z-index differently.

**Comment by harbaum** [comment]
I don't think the z-index is the (only) problem as other html elements are also under the scrollbar. The scrollbars don't seem to be a part of the workspace at all. My patch #817 just stores the scrollbars in the bubble canvas which (from some comments in workspace_svg.js) seems to be how it was supposed to be done. Also the scrollbar corner was already stored there and didn't expose the odd behaviour.

**Comment by picklesrus** [comment]
Yeah, the scrollbars are not part of the workspace as of [this commit](https://github.com/google/blockly/commit/a82bd49d7e38ec61b127e0bf527f50ac282bd3d7) . They are their own <svg> elements now. That was necessary to make some performance improvements.

Which other html elements were you thinking of?
In the element inspector in chrome, if I add z-index:15 in the main workspace's horizontal scrollbar, leaving the flyout's vertical scrollbar at 30, I think it works.

The bubble canvas is supposed to be for drawing bubbles (like mutators and comments) and is usually empty so that's quite the right spot for it.  Perhaps some comments need to be updated though - which comments were you referring to?

**Comment by harbaum** [comment]
The comment is in line 323 of workspace_svg.js

I have written a fairly ordinary drop down menu based on some simple HTML and CSS which when opened overlaps the workspace. The scrollbars are even in front of that.

**Comment by rachel-fenichel** [comment]
https://github.com/google/blockly/blob/master/core/workspace_svg.js#L323

**Comment by picklesrus** [comment]
Thanks, I'll get that comment updated.

@harbaum what is the z-index of your dropdown? If you increase to something silly large like 10000 does your dropdown show up on top of the scrollbars. Depending on what blockly items you want to be above/below, I can help you choose a more reasonable value.

**Comment by harbaum** [comment]
Yes, i can confirm that with a z-index of 10000 my dropdown is in front of the scrollbars even without my patch.

This is sufficient for me.

**Comment by harbaum** [comment]
If the comment is wrong and my pathc is wrong then this line is also wrong:

https://github.com/google/blockly/blob/master/core/scrollbar.js#L47

as it places the scrollbar corner in the bubble canvas as well.

**Comment by picklesrus** [comment]
Thanks @harbum!

I'm in meetings all day for the rest of the week but I'll try and get the scrolbars on top of the flyout and the comments fixed up next week.

I'll also try and document our use of z-index so that it is a bit more understandable how layers work.

**Comment by rachel-fenichel** [comment]
@harbaum insertAfter doesn't place it in the bubbleCanvas.  It makes it a sibling of bubbleCanvas, but after bubbleCanvas in the DOM.  See https://github.com/google/blockly/blob/master/core/utils.js#L766 and the documentation for the similar [insertBefore](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore).

**Comment by harbaum** [comment]
@rachel-fenichel Thank you for that explanation. I am still digging through all the details while enabling the kids to control their fischertechnik Robots with blockly.

**Comment by picklesrus** [comment]
This is now fixed in develop.
