### ISSUE TITLE
New dancing blocks with Zelos - blocks move when field edited

### ISSUE THREAD

**Issue by clementcontet** [google/blockly#8168]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

I have found another strange dancing blocks issue in my app, that I can reproduce in the playground.
I don't know if it is linked to https://github.com/google/blockly/issues/7898 ?

### Reproduction steps

See screencast

### Screenshots

https://github.com/google/blockly/assets/7261426/dd23247a-b3ac-451a-a68e-ff7f79373f69

### Browsers

Chrome desktop

**Comment by BeksOmega** [comment]
Thanks for filing! I think this is related to bumping neighbours.

**Comment by BeksOmega** [comment]
This also repros on 10.3

**Comment by johnnesky** [comment]
Confirmed that the same bug occurs in the geras renderer.
https://github.com/user-attachments/assets/a68fdf48-f5ad-44a3-b210-e3dab0e7d430
