### ISSUE TITLE
Publish "real" ESM modules usable by browser

### ISSUE THREAD

**Issue by jogibear9988** [google/blockly#8170]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

With issue https://github.com/google/blockly/issues/7449 you seem to provide ESM modules.
But this are not real ESM modules wich are usable by the browser. They could only be used if you use a bundler

### Reproduction steps

1. Try the code from https://github.com/jogibear9988/blocklyEsmTest

### Stack trace

```shell
Uncaught SyntaxError: The requested module './index.js' does not provide an export named 'default' (at index.mjs:1:8)
```

### Screenshots

<img width="571" alt="image" src="https://github.com/google/blockly/assets/364896/e8d58113-d40a-4224-a4d7-67809ea46225">

### Browsers

Chrome desktop, Safari desktop, Firefox desktop, Android mobile, iOS mobile

**Comment by cpcallen** [comment]
You are quite correct, and issue #7449 had been left open for exactly the reason you note.  I will update that issue and then close this one.

**Comment by jogibear9988** [comment]
@cpcallen  you need to reopen it, it has been closed.

Maybe you could add the sample: https://github.com/jogibear9988/blocklyEsmTest

**Comment by cpcallen** [comment]
> you need to reopen it, it has been closed.

[Done](https://github.com/google/blockly/issues/7449#issuecomment-2124852536).

 > Maybe you could add the sample: https://github.com/jogibear9988/blocklyEsmTest

Also done.  Thanks for the great import map example!
