### ISSUE TITLE
Adding blocks from toolbox can move the grid enable workspace

### ISSUE THREAD

**Issue by carlosperate** [google/blockly#82]
I'm not 100% sure how to replicate this issue, I can currently trigger it in the https://blockly-demo.appspot.com/static/demos/code/index.html demo and the latest master with Chrome and Firefox. It is more likely to happen when there are no other block in the workspace and I have not yet dragged the workspace.

When a new block is clicked from the toolbox flyout it moves the entire workspace a few pixels to the right and bottom. This workspace movement happens before I release the click. It will continuously happen until I drag the workspace around to move the current blocks to the side.

Please let me know if you need a better explanation or a quick video.

**Comment by NeilFraser** [comment]
Fixed.  Thanks.
