### ISSUE TITLE
Workspace comments do not have a delete cursor when dragged over the trashcan

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8204]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Workspace comments do not have a delete cursor when dragged over the trashcan

### Reproduction steps

1. Right click to create a workspace comments.
2. Drag it over the trashcan.
3. Observe that the cursor doesn't get an "x"

**Comment by BHAV0207** [comment]
hey @BeksOmega  I would like to work on this issue, please assign this issue to me

**Comment by BeksOmega** [comment]
I think this is actually a duplicate of #8413
