### ISSUE TITLE
statement block could as long as condtion block

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#8222]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Request

![image](https://github.com/google/blockly/assets/42778/8d9a0787-f1c1-4240-9b07-fb661d26f5be)

to archive this, dose need any api support?

**Comment by cpcallen** [comment]
Hello.  An interesting idea!  This is not something we're going to implement, but it is something you could implement yourself via a [custom renderer](https://developers.google.com/blockly/guides/configure/web/appearance/renderers).  Have a look at the [custom renderer codelab](https://blocklycodelabs.dev/codelabs/custom-renderer/index.html?index=..%2F..index#0) and feel free to post on the [Blockly forum](https://groups.google.com/g/blockly) if you have any questions!
