### ISSUE TITLE
Height of WidgetDiv does not take into account widget location

### ISSUE THREAD

**Issue by ferrao** [google/blockly#823]
I am experiencing a problem similar to the one reported in #131 , which fixed it in `Blockly.WidgetDiv.position` with:

```javascript
Blockly.WidgetDiv.DIV.style.height = windowSize.height - anchorY + 'px';
```
But now it seems to be back to :

```javascript
  Blockly.WidgetDiv.DIV.style.height = windowSize.height + 'px';
```

**Comment by Nekomajin42** [comment]
There is a temporary workaround to set the `max-height` property of the `.blocklyWidgetDiv` to a certain size. I've found that `120px` works for me. The  context menu is visible without scrollbars. It can be a problem with large dropdowns though.

**Comment by rachel-fenichel** [comment]
Here's where the change happened: https://github.com/google/blockly/commit/927cabe992026a2bc3b6b3ac1b064b56b5d8d711

The line changed to 
`Blockly.WidgetDiv.DIV.style.height = windowSize.height + 'px';`
from 
`Blockly.WidgetDiv.DIV.style.height = (windowSize.height - anchorY + scrollOffset.y) + 'px';`

**Comment by rachel-fenichel** [comment]
@samelhusseini How about this one?

**Comment by samelhusseini** [comment]
Yeah I think so, the WidgetDiv doesn't restrict the max height of what's inside of it, but the DropdownDiv does (300px). The dropdown div also positions its content appropriately inside of the view.

I would close this under the recommendation to use the Dropdown div for any field content that doesn't get placed directly on top of the field.
