### ISSUE TITLE
Expose `bringToFront()` method

### ISSUE THREAD

**Issue by JonasFocke01** [google/blockly#8233]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Hi, I have the problem, that i have a fixed top level block in my szenario. It can happen now, that a block by accident gets obershadowed by this, making it unpossible to fix this sittuation by the user.

### Request

I would love a way to bring all __parentless__ blocks to the front by calling something like `bringToFront()` on it. I know, that this method exists internally, i just could not find a way to call it from outside.

**Comment by cpcallen** [comment]
Hello and thanks for this feature request.

Just out of interest, can you tell us what happened when you attempted to call this method?

After discussing this request with a teammate we think it seems reasonable to remove the `@internal` tag from `bringToFront`, though the JSDoc for the method should be updated to note that reordering the DOM nodes (which is what this method does) might be expensive (i.e. slow) so it should perhaps be used sparingly.

We would welcome a PR from you that makes this change!

**Comment by Spoorthy1423** [comment]
Hey!! @cpcallen i would love to work on this issue, please assign me

**Comment by BeksOmega** [comment]
Go for it @Spoorthy1423 =) let me know if you have any questions!

**Comment by BeksOmega** [comment]
This is being worked on by @UCYT5040
