### ISSUE TITLE
Replace goog.asserts when validating user data

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#824]
goog.asserts functions will only throw when goog.asserts.ENABLE_ASSERTS is true.  This is turned off as part of the compilation process, and so no asserts will throw in the blockly_compressed.js package.  We want these validations for user data, and should replace goog.assert in those case.

goog.asserts methods should be reserved for checks against things that should never happen (cases the imply other code is wrong).  Not expected failures.

**Comment by rachel-fenichel** [comment]
[Done](https://github.com/google/blockly/commit/3909bd420a22fec4cc830b0d7a31e75c5d0ff244)!
