### ISSUE TITLE
Workspace comments are missing the `blocklyDraggable` CSS class

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8253]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Workspace comments should have the `blocklyDraggable` class at the top level (where `blocklyComment`, `blocklyEditable`, and `blocklySelected` live). 

### Reproduction steps

1. Right click to add a comment to the workspace.
2. Use the inspector to see that it's missing the relevant class.

**Comment by changminbark** [comment]
I would also like to tackle this issue

**Comment by BeksOmega** [comment]
Go for it @changminbark =) Thanks for picking this up!

**Comment by changminbark** [comment]
I have fixed this in this PR: https://github.com/google/blockly/pull/8358

**Comment by changminbark** [comment]
I think this issue can now be closed. Thank you!
