### ISSUE TITLE
Add a `blocklyBlock` CSS class to the block's root SVG

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8261]
## To Fix

In the [common PathObject's constructor](https://github.com/google/blockly/blob/17dfa462a357b553523393145c9d5045023e627b/core/renderers/common/path_object.ts#L61), call `setClass`  to add a `blocklyBlock` class to the svgRoot.

The PR to fix this should be made against the `rc/v12.0.0` branch.

To work on this issue, please comment below asking to be assigned.

**Comment by ChaitanyaYeole02** [comment]
Hey, can you please assign this issue to me?

**Comment by BeksOmega** [comment]
Go for it @ChaitanyaYeole02 =)

**Comment by BeksOmega** [comment]
Closed by #8397
