### ISSUE TITLE
Add a `blocklyShadow` CSS class to shadow blocks' root SVG

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8262]
In the [common PathObject's `updateShadow_` method](https://github.com/google/blockly/blob/17dfa462a357b553523393145c9d5045023e627b/core/renderers/common/path_object.ts#L187), call setClass to add a `blocklyShadow` class to the svgRoot, or remove the class.

The PR to fix this should be made against the rc/v12.0.0 branch.

To work on this issue, please comment below asking to be assigned.

**Comment by devesh-2002** [comment]
May I take this issue?

**Comment by BeksOmega** [comment]
Go for it @devesh-2002 =)

**Comment by BeksOmega** [comment]
Closed by #8336
