### ISSUE TITLE
Add a `blocklyCollapsed` CSS class to collapsed blocks' root SVG

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8264]
## To Fix

In the [updateCollapsed method](https://github.com/google/blockly/blob/17dfa462a357b553523393145c9d5045023e627b/core/block_svg.ts#L481) call `dom.addClass` on the `this.svgGroup_` to add the `blocklyCollapsed` class, or `dom.removeClass` to remove it.

The PR to fix this should be made against the `rc/v12.0.0` branch.

To work on this issue, please comment below asking to be assigned.

**Comment by BeksOmega** [comment]
@ga-fleury is working on this

**Comment by Apocalypse96** [comment]
@BeksOmega I would love to solve this issue

**Comment by sachan13harshit** [comment]
@BeksOmega can you pls assign it to me?

**Comment by BeksOmega** [comment]
Closed by #8308
