### ISSUE TITLE
Add a `blocklyNotEditable` CSS class to the block's root SVG

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8266]
## To Fix

In the [BlockSvg class' `setEditable` method](https://github.com/google/blockly/blob/17dfa462a357b553523393145c9d5045023e627b/core/block_svg.ts#L684), call `dom.addClass` on the `this.svgGroup_` to add a `blocklyNotEditable` class when the block is not editable, or `dom.removeClass` to remove the class when the block is editable.

The PR to fix this should be made against the `rc/v12.0.0` branch.

To work on this issue, please comment below asking to be assigned.

**Comment by dianaprahoveanu23** [comment]
Hi @BeksOmega can I please be assigned to this issue?

**Comment by BeksOmega** [comment]
Go for it @dianaprahoveanu23 =) Let me know if you have any questions!

**Comment by BeksOmega** [comment]
Closed by #8391
