### ISSUE TITLE
Add the block's type as a CSS class to the block's root SVG

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8268]
## To Fix

In the [BlockSvg class' constructor](https://github.com/google/blockly/blob/17dfa462a357b553523393145c9d5045023e627b/core/block_svg.ts#L1924), call `dom.addClass` on the `this.svgGroup_` to add the `prototypeName` as a CSS class on the block.

The PR to fix this should be made against the `rc/v12.0.0` branch.

To work on this issue, please comment below asking to be assigned.

**Comment by BeksOmega** [comment]
@ga-fleury is working on this.

**Comment by Apocalypse96** [comment]
@BeksOmega I would love to solve this issue

**Comment by sachan13harshit** [comment]
@BeksOmega can you pls assign it to me?

**Comment by Aarya01Patil** [comment]
@BeksOmega Hey I would love to solve this issue

**Comment by GarvitDadheech** [comment]
Hii @BeksOmega , Can you please assign this issue to me? I'd like to resolve this issue.

**Comment by BarryByte** [comment]
@BeksOmega Please assign this to me.

**Comment by CodeMaverick2** [comment]
@BeksOmega I would like to solve this

**Comment by harsh-791** [comment]
i want to work on this issue @BeksOmega

**Comment by BeksOmega** [comment]
This is open for work again @harsh-791 Are you still interested in it?

**Comment by BeksOmega** [comment]
Nvm looks like @CodeMaverick2 is taking a swing =)

**Comment by BeksOmega** [comment]
Closed by #8428
