### ISSUE TITLE
Add the block's style as a CSS class to the block's root SVG

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8269]
## To Fix

In the [BlockSvg class' `setStyle` method](https://github.com/google/blockly/blob/17dfa462a357b553523393145c9d5045023e627b/core/block_svg.ts#L1103), call `dom.addClass` on the `this.svgGroup_` to add the `blockStyleName` as a CSS class on the block. You should also call `dom.removeClass` with `this.styleName_` to remove any previous style.

The PR to fix this should be made against the `rc/v12.0.0` branch.

To work on this issue, please comment below asking to be assigned.

**Comment by BeksOmega** [comment]
@ga-fleury is working on this.

**Comment by Shreshthaaa** [comment]
Hey @BeksOmega, I would like to work on this issue. Kindly assign this to me.

**Comment by BeksOmega** [comment]
Hiya @Shreshthaaa =) Someone is already working on this issue! (I had to comment for them because they forgot.)

If you comment on an issue that isn't assigned to anyone (most of the ones in [this list](https://github.com/google/blockly/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+label%3A%22good+first+issue%22)). I can assign you to it!

**Comment by Shreshthaaa** [comment]
@BeksOmega, I've commented on a few other issues as well. Could you kindly review and assign them to me? Thank you

**Comment by Aarya01Patil** [comment]
@BeksOmega Hey can i work on this if its available to solve

**Comment by GarvitDadheech** [comment]
Hey @BeksOmega , Can you please assign this issue to me? I'd love to solve this issue.

**Comment by Shreshthaaa** [comment]
> @Shreshthaaa Are you still interested in working on this? It's now available.

Yeah sure, I'm interested in working on this.

**Comment by Shreshthaaa** [comment]
Hey @BeksOmega, I have raised the [PR](https://github.com/google/blockly/pull/8436) for this issue. Kindly review.

**Comment by omwagh28** [comment]
@BeksOmega I would like to solve this issue

**Comment by BeksOmega** [comment]
Closed by #8436
