### ISSUE TITLE
Add `addClass` and `removeClass` methods to the block to deal with CSS classes

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8270]
## To Fix

1. Add an `addClass` method to the BlockSvg class, that takes in a passed string, and calls `dom.addClass` with the `this.svgGroup_` to add it as a CSS class on the block.
2. Add a `removeClass` method to the BlockSvg class, that takes in a passed string, and calls `dom.removeClassClass` with the `this.svgGroup_`.
3. Refactor any calls in the BlockSvg class to `dom.addClass` with `this.svgGroup_` to call `this.addClass` instead.
3. Refactor any calls in the BlockSvg class to `dom.removeClass` with `this.svgGroup_` to call `this.removeClass` instead.

The PR to fix this should be made against the `rc/v12.0.0` branch.

To work on this issue, please comment below asking to be assigned.

**Comment by BeksOmega** [comment]
Heya @ishon19 Happily =) But you have to comment on #8271 for me to assign you :/ (this is a restriction with the GitHub UI)

**Comment by ishon19** [comment]
> Heya @ishon19 Happily =) But you have to comment on #8271 for me to assign you :/ (this is a restriction with the GitHub UI)

My bad! No problem, adding a comment over there.

**Comment by BeksOmega** [comment]
Closed by #8337
