### ISSUE TITLE
Add a `classes` property to the JSON block definitions to add CSS classes

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8271]
Dependent on #8270

## To Fix

In the [BlockSvg class](https://github.com/google/blockly/blob/17dfa462a357b553523393145c9d5045023e627b/core/block_svg.ts#L1924), Override the `jsonInit` method to take the value of the `json['classes']` property, concatenate it if it is an array, and pass it to the `this.addClass` method.

The PR to fix this should be made against the `rc/v12.0.0` branch.

To work on this issue, please comment below asking to be assigned.

**Comment by ishon19** [comment]
Hey @BeksOmega, I'd like to work on this issue! 👋

**Comment by BeksOmega** [comment]
Sweet! Thanks for commenting, I know it's a bit annoying :P

**Comment by ishon19** [comment]
> Sweet! Thanks for commenting, I know it's a bit annoying :P

Thanks for assigning and no problem at all! Getting started on it :)

**Comment by BeksOmega** [comment]
Closed by #8377
