### ISSUE TITLE
Remove references to `getFastTextWidth`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8277]
Use `getTextWidth` instead. `getFastTextWidth` relies on already knowing about the styling that will be applied to the text, which we can't guarantee now that we're styling with CSS.

To work on this, please comment below asking to be assigned.

This change should be made against the `rc/v12.0.0` branch.

**Comment by BeksOmega** [comment]
@ga-fleury is working on this

**Comment by BeksOmega** [comment]
Heya @AbhinavKRN ga-fleury has a PR up for this at the moment, but if they end up not completing it I'll reassign to you =)

**Comment by AbhinavKRN** [comment]
@BeksOmega Sure!

**Comment by Apocalypse96** [comment]
@BeksOmega I would love to solve this issue

**Comment by sachan13harshit** [comment]
@BeksOmega can you pls assign it to me?

**Comment by BeksOmega** [comment]
Closed by #8307
