### ISSUE TITLE
Generated python from if block defaults to 'false' and not to 'False'

### ISSUE THREAD

**Issue by harbaum** [google/blockly#828]
When generating python code from an if block without any condition attached the generated code will be:

`if false:`

But python requires the first letter to be upper case. Lower case 'false' is not defined in python.

The bug is in this line:
https://github.com/google/blockly/blob/master/generators/python/logic.js#L38

**Comment by NeilFraser** [comment]
Thanks!  Fixed in 90b63f49cb1c8f67e1b1e2098567a9ac59a62c49 in the develop branch.  Looks like it was a recently introduced bug.  @AnmAtAnm
