### ISSUE TITLE
Add `addClass` and `removeClass` methods to the workspace to deal with CSS classes

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8281]
## To Fix

1. Add an `addClass` method to the WorkspaceSvg class, that takes in a passed string, and calls `dom.addClass` with the `this.injectionDiv` to add it as a CSS class on the block.
2. Add a `removeClass` method to the WorkspaceSvg class, that takes in a passed string, and calls `dom.removeClassClass` with the `this.injectionDiv`.
3. Refactor any calls in the WorkspaceSvg class to `dom.addClass` with `this.injectionDiv` to call `this.addClass` instead.
3. Refactor any calls in the WorkspaceSvg class to `dom.removeClass` with `this.injectionDiv` to call `this.removeClass` instead.

The PR to fix this should be made against the `rc/v12.0.0` branch.

To work on this issue, please comment below asking to be assigned.

**Comment by kabeer95** [comment]
Hey I can solve this  issue 
Here' s how it will solve 
To add addClass and removeClass methods to the WorkspaceSvg class, create new functions that call dom.addClass and dom.removeClass with this.injectionDiv. Refactor existing code to use these new methods, replacing direct calls to dom.addClass and dom.removeClass with this.addClass and this.removeClass. This simplifies the code and makes it more maintainable. Finally, create a pull request against the rc/v12.0.0 branch with these changes, ensuring a clean and organized codebase. This update will improve the overall structure and readability of the WorkspaceSvg class.

**Comment by BeksOmega** [comment]
Go for it @kabeer95 ! Let me know if you have any questions =)

**Comment by UCYT5040** [comment]
Hi, it's almost been a month since @kabeer95 was assigned. Is it okay if I am assigned instead?

**Comment by BeksOmega** [comment]
Sure thing, go for it @UCYT5040 =)

**Comment by UCYT5040** [comment]
@BeksOmega I can't find any existing calls within the `WorkspaceSvg` class to add/remove `this.injectionDiv` classes. Am I okay to just add the new methods, or am I missing something here?

**Comment by BeksOmega** [comment]
Yesh! New methods are what we want.
