### ISSUE TITLE
Delete styles without associated classes from `css.ts`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8285]
The following styles exist in `css.ts` but the classes are never actually applied anywhere in core. We should delete the styling.

- blocklyHidden
- blocklyResizeLine
- blocklyResizeSW
- blocklyResizeSE
- blocklyDropDownButton

If you want to work on this issue, please comment below asking to be assigned.

This should be merged into the `rc/v12.0.0` branch. It should be marked as a breaking change.

**Comment by aishwaryavenkatesan** [comment]
Hi I am looking to contribute to open source for the first time, can I work on this issue?

**Comment by BeksOmega** [comment]
Hiya @aishwaryavenkatesan awesome! Absolutely :D Let me know if you have any questions!

**Comment by aishwaryavenkatesan** [comment]
Thank you @BeksOmega, just read through on the fork and clone, will post here if I have any doubts!

**Comment by Suswetha6** [comment]
Hey @BeksOmega ,i want to work on this issue

**Comment by aishwaryavenkatesan** [comment]
Hi @BeksOmega, i have committed my changes, would it be possible to review my PR?

**Comment by BeksOmega** [comment]
Hi @aishwaryavenkatesan I try to review daily (on work days) =)

**Comment by aishwaryavenkatesan** [comment]
perfect, thanks for the reply and my first contribution to Open Source
