### ISSUE TITLE
Stop applying old closure UI library menu styles

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8286]
We used to use a UI library called Closure (loosely associated with the JS compiler). There are still places where we apply CSS classes that were used by that library. We should stop doing that, since we have Blockly CSS classes folks can use instead.

- goog-menuitem
- goog-menuitem-disabled
- goog-menu

If you want to work on this issue, please comment below asking to be assigned.

This should be merged into the rc/v12.0.0 branch. It should be marked as a breaking change.

**Comment by Arun-cn** [comment]
I like to work on this issue please assign to me

**Comment by Arun-cn** [comment]
Thank you! I'll start working on it. I'll reach out if I have any questions

**Comment by Arun-cn** [comment]
I working on removing deprecated Closure UI library and replacing them with blockly css classes . however, i'm encountering errors when running `npm run start` .

branch : rc/v12.0.0

Error : gulp-google-closure-compiler: Error writing to stdin of the compiler. write EPIPE ,
Error: gulp-google-closure-compiler: Compilation errors occurred at CompilationStream._compilationComplete

is necessary to make and verify a changes in locally?

**Comment by BeksOmega** [comment]
Yes you should verify your changes locally! Can you follow these steps and see what happens? If you get an error again, can you post the full error log?

1. Use the console to navigate to the root directory of your blockly repo.
2. Run `npm run clean`.
3. Run `npm ci`.
4. Run `npm run start`.

**Comment by Arun-cn** [comment]
I still getting error on windows 10 pro. I tried on wsl2 ubuntu 20 it's worked fine 👍

**Comment by BeksOmega** [comment]
Ah ok @cpcallen do you know if the issue Arun raised is covered by https://github.com/google/blockly/issues/4762 or https://github.com/google/blockly/issues/5000 ?

**Comment by BeksOmega** [comment]
Closed by #8339
