### ISSUE TITLE
Rename `editing` CSS class to `blocklyEditing`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8287]
1. In the[ `widgetCreate_` method](https://github.com/google/blockly/blob/8323642d0eb677648f004f294208d2734c6e8d65/core/field_input.ts#L408) on the `FieldInput` change the `editing` string passed to `dom.addClass` to `blocklyEditing`.
2. Also change references to `editing` in the [common renderer CSS](https://github.com/google/blockly/blob/8323642d0eb677648f004f294208d2734c6e8d65/core/renderers/common/constants.ts#L1157) and the [zelos renderer CSS](https://github.com/google/blockly/blob/8323642d0eb677648f004f294208d2734c6e8d65/core/renderers/zelos/constants.ts#L828) to `blocklyEditing`.

This should be merged into the `rc/v12.0.0` branch. It should be marked as breaking.

If you want to work on this, comment below to be assigned this issue.

**Comment by ga-fleury** [comment]
Hello, I would like to work on this

**Comment by BeksOmega** [comment]
Go for it @ga-fleury ! Let me know if you have any questions =)

**Comment by ga-fleury** [comment]
@BeksOmega I don't think I have permission to push to the `rc/v12.0.0` branch

**Comment by BeksOmega** [comment]
> @BeksOmega I don't think I have permission to push to the `rc/v12.0.0` branch

Oh yeah, the correct flow is to use a pull request. You should create a branch off of `rc/v12.0.0`, make your changes, and then put up a pull request against `rc/v12.0.0`. See our [contributing docs](https://developers.google.com/blockly/guides/contribute/core) for more info.

**Comment by ga-fleury** [comment]
missing CLA, opening new PR

**Comment by ga-fleury** [comment]
@BeksOmega I think everything is OK now, took me some time to figure out the correct PR workflow

**Comment by ga-fleury** [comment]
@BeksOmega finally got it

**Comment by BeksOmega** [comment]
Closed by #8301
