### ISSUE TITLE
Add `.blocklyField` to the field's SVG group

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8289]
In the [`initView` method](https://github.com/google/blockly/blob/8323642d0eb677648f004f294208d2734c6e8d65/core/field.ts#L323) of the field, add a call to `dom.addClass` that adds a `blocklyField` CSS class to the `this.fieldGroup_`

This change should be made against the `rc/v12.0.0` branch.

To work on this issue, comment below asking to be assigned.

**Comment by nullHawk** [comment]
Hi @BeksOmega,

I am interested in solving this issue. Can you please assign this issue to me ?

**Comment by BeksOmega** [comment]
Go for it @nullHawk =) Let me know if you have any questions!

**Comment by nullHawk** [comment]
Hi @BeksOmega, I have raised the [PR](https://github.com/google/blockly/pull/8334), please take a look at  it

**Comment by BeksOmega** [comment]
Closed by #8334
