### ISSUE TITLE
Three type annotation errors.

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#829]
From this report: https://github.com/google/blockly-games/issues/52

appengine/third-party/blockly/core/blockly.js:391: WARNING - Bad type annotation. missing opening ( See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

@return {function} A function that calls jsonInit with the correct value
^
appengine/third-party/blockly/core/field.js:71: WARNING - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

@type {string=}
^
appengine/third-party/blockly/core/variables.js:236: WARNING - Bad type annotation. missing closing ) See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

@param {function(null|undefined|string)=} opt_callback A callback. It will
^

**Comment by AnmAtAnm** [comment]
Annotation errors are blocking doc updates (#868).

    ERROR: Unable to parse a tag's type expression for source file /tmp/blockly-jsdoc/core/variables.js with tag title "param" and text "{function(null|undefined|string)=} opt_callback A callback. It will return an acceptable new variable name, or null if change is to be  aborted (cancel button), or undefined if an existing variable was chosen.": Invalid type expression "function(null|undefined|string)=": Expected "#", "$", "(", "-", ".", "/", "0", ":", "<", "=", "[]", "\\", "\u200C", "\u200D", "_", "|", "~", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter or [1-9] but ")" found.
    ERROR: Unable to parse a tag's type expression for source file /tmp/blockly-jsdoc/core/variables.js with tag title "param" and text "{function(null|undefined|string)=} opt_callback A callback. It will return an acceptable new variable name, or null if change is to be aborted (cancel button), or undefined if an existing variable was chosen.": Invalid type expression "function(null|undefined|string)=": Expected "#", "$", "(", "-", ".", "/", "0", ":", "<", "=", "[]", "\\", "\u200C", "\u200D", "_", "|", "~", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter or [1-9] but ")" found.
