### ISSUE TITLE
Rename `blocklyEditableText` to `blocklyEditableField` and `blocklyNonEditableText` to `blocklyNonEditableField`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8290]
1. In the field's [`updateEditable` method](https://github.com/google/blockly/blob/8323642d0eb677648f004f294208d2734c6e8d65/core/field.ts#L533), rename `blocklyEditableText` to `blocklyEditableField` and `blocklyNonEditableText` to `blocklyNonEditableField`
2. Rename references in the [common constants](https://github.com/google/blockly/blob/8323642d0eb677648f004f294208d2734c6e8d65/core/renderers/common/constants.ts#L1136) and the [zelos constants](https://github.com/google/blockly/blob/8323642d0eb677648f004f294208d2734c6e8d65/core/renderers/zelos/constants.ts#L806).

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by SinBin10** [comment]
Hello, I believe I can fix this issue. Can you please assign this issue to me ?

**Comment by dianaprahoveanu23** [comment]
Hi @BeksOmega can I please be assigned to this issue? I am eager to make my first open-source contribution to this project. Thank you

**Comment by BeksOmega** [comment]
Heya @SinBin10 Go for it =) Let me know if you have any questions!

@dianaprahoveanu23 Happy to assign you a different issue! Just comment on it and I'll get you assigned.

**Comment by Adityajaiswal03** [comment]
hey @BeksOmega please assign me this issue

**Comment by BeksOmega** [comment]
Sure it looks like the other assignee is not going to complete it.

Go for it @Adityajaiswal03 , let me know if you have any questions =)

**Comment by Adityajaiswal03** [comment]
@BeksOmega Thanks for assigning me the issue. I'll raise the draft PR asap.

**Comment by Adityajaiswal03** [comment]
Hi @BeksOmega,
I have created a draft pull request and would appreciate it if you could review it and provide your feedback.

**Comment by Adityajaiswal03** [comment]
@BeksOmega I have raised the pull request again. Could you please review it and provide your feedback at your earliest convenience?
