### ISSUE TITLE
Add a `blocklyFieldText` CSS class to fields' text elements

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8291]
In the field's `createTextElement_` method, add a `blocklyFieldText` class to the [`class` property](https://github.com/google/blockly/blob/8323642d0eb677648f004f294208d2734c6e8d65/core/field.ts#L376).

https://github.com/google/blockly/blob/8323642d0eb677648f004f294208d2734c6e8d65/core/field.ts#L376

**Comment by ga-fleury** [comment]
Hey @BeksOmega, can you assign this to me?

**Comment by BeksOmega** [comment]
Closed by #8302
