### ISSUE TITLE
Move and rename `blocklyCheckbox` to `blocklyCheckboxField`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8299]
In the checkbox field's `initView` method, change the [call to `dom.addClass`](https://github.com/google/blockly/blob/8323642d0eb677648f004f294208d2734c6e8d65/core/field_checkbox.ts#L117) to pass the `this.fieldGroup_` and `blocklyCheckboxField`.

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by ishon19** [comment]
Hey @BeksOmega, I want to get started with this issue, do you mind assigning me?

**Comment by ishon19** [comment]
Absolutely! thanks @BeksOmega

**Comment by BeksOmega** [comment]
Closed by #8309
