### ISSUE TITLE
Add a `blocklyTextInputField` CSS class to text input fields

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8312]
In the `FieldTextInput` class override the `initView` method to call `dom.addClass` with the `this.fieldGroup_` and `'blocklyTextInputField'`. You will need to add `import * as dom from './utils/dom.js';` to call `dom.addClass`.

This change should be made against the `rc/v12.0.0` branch.

To work on this issue, comment below asking to be assigned.

**Comment by siddharthbaleja7** [comment]
Please assign this issue to me. I have made the necessary changes to override the initView method in the FieldTextInput class to add the blocklyTextInputField CSS class.

**Comment by BeksOmega** [comment]
Hiya @siddharthbaleja7 If you comment on a `help-wanted` issue where someone else isn't already assigned I can assign you =) Most of the issues [in this list](https://github.com/google/blockly/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee+sort%3Acreated-desc+label%3A%22help+wanted%22) are unassigned.

**Comment by Apocalypse96** [comment]
hey!! @BeksOmega  pls assign this to me

**Comment by sachan13harshit** [comment]
@BeksOmega pls assign this issue to me
