### ISSUE TITLE
Add a `blocklyNumberField` CSS class to number fields

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8313]
In the `FieldNumber` class override the `initView` method to call `dom.addClass` with the `this.fieldGroup_` and `'blocklyNumberField'`. You will need to add `import * as dom from './utils/dom.js';` to call `dom.addClass`.

This change should be made against the `rc/v12.0.0` branch.

To work on this issue, comment below asking to be assigned.

**Comment by ruthwikchikoti** [comment]
@BeksOmega, please assign this to me. I'm eager to work on it.

**Comment by BeksOmega** [comment]
Go for it @ruthwikchikoti ! Let me know if you have any questions =)

**Comment by Apocalypse96** [comment]
Hey @ruthwikchikoti  Can you pls give me a chance to solve this issue

**Comment by Apocalypse96** [comment]
Hey @BeksOmega can you pls assign it to me now??

**Comment by sachan13harshit** [comment]
@BeksOmega  can you pls assign it to me?

**Comment by BeksOmega** [comment]
Closed by #8414
