### ISSUE TITLE
Add a `blocklyImageField` CSS class to image fields

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8314]
In the `FieldImage` class modify the `initView` method to call `dom.addClass` with the `this.fieldGroup_` and `'blocklyImageField'`.

This change should be made against the `rc/v12.0.0` branch.

To work on this issue, comment below asking to be assigned.

**Comment by vexora-0** [comment]
i want to work on this

**Comment by BeksOmega** [comment]
Go for it @vexora-0 =) Let me know if you have any questions!

**Comment by vexora-0** [comment]
hey @BeksOmega can you check my pr
