### ISSUE TITLE
Add a `blocklyLabelField` CSS class to label fields

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8315]
In the `FieldLabel` class modify the `initView` method to call `dom.addClass` with the `this.fieldGroup_` and `'blocklyLabelField'`.

This change should be made against the `rc/v12.0.0` branch.

To work on this issue, comment below asking to be assigned.

**Comment by surajguduru** [comment]
Hey @BeksOmega I would like to work on this one. Can you assign it to me ?

**Comment by BeksOmega** [comment]
Hiya @surajguduru Go for it =)

Sorry @Shreshthaaa surajguduru commented first, but if you find a different unassigned `help-wanted` issue I can assign you.

**Comment by surajguduru** [comment]
Hey @BeksOmega  @gonfunko  I have raised a PR.  I have made the required changes. Please review the changes and let me know !

**Comment by BeksOmega** [comment]
Closed by #8423
