### ISSUE TITLE
Add a `blocklyVariableField` CSS class to variable fields

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8316]
In the `FieldVariable` class override the `initView` method to call `dom.addClass` with the `this.fieldGroup_` and `'blocklyVariableField'`. You will need to add `import * as dom from './utils/dom.js';` to call `dom.addClass`.

This change should be made against the `rc/v12.0.0` branch.

To work on this issue, comment below asking to be assigned.

**Comment by shashwatpathak98** [comment]
Hi @BeksOmega, I want to work on this one, can you please assign me?

**Comment by BeksOmega** [comment]
Sure thing @shashwatpathak98 =)

**Comment by BeksOmega** [comment]
Closed by #8359
