### ISSUE TITLE
Remove the field `CURSOR` property

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8319]
Remove the field `CURSOR` property, and instead assign cursors to fields in `css.ts`.

This is a breaking change.

**Comment by CodeMaverick2** [comment]
@BeksOmega  please assign me this issue i would like to work on it

**Comment by BeksOmega** [comment]
Heya @CodeMaverick2, we'd love to have you work on Blockly, but this issue has some tricky complexity about reassigning all the cursor values via CSS! If you comment on a `good-first-issue` or `help-wanted` issue I can assign you =)

**Comment by CodeMaverick2** [comment]
@BeksOmega I have recently worked and built a Hotel booking chatbot using open ai API and there are several other projects I have build, I think I can solve this issue I wont cause a problem

**Comment by BeksOmega** [comment]
Haha ok sounds good!

**Comment by CodeMaverick2** [comment]
@BeksOmega Should we also redo the cursor for field.ts
