### ISSUE TITLE
Combine the `blocklyArrowTop` and `blocklyArrowBottom` styling into the `blocklyDropDownArrow` styling

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8323]
1. Remove the `blocklyArrowTop` and `blocklyArrowBottom` CSS classes from being assigned to the dropdown div ([source code](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/dropdowndiv.ts#L716)). Instead, only assign `blocklyDropDownArrow`.
2. Combine the styling from `blocklyArrowTop` and `blocklyArrowBottom` in `css.ts` into the [`blocklyDropDownArrow` styling](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/css.ts#L133). It should have a `1px solid` border on all sides, and a 4px radius in the top left and bottom right.

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by BeksOmega** [comment]
I don't think this quite works because of how the elements get layered :/ The menu content doesn't quite cover the arrow, so it looks like a separate element instead of being part of the background. We could maybe add another separate background element? But I'm not sure if that's the right approach.

**Comment by mayank1365** [comment]
@BeksOmega please assign this issue to me
