### ISSUE TITLE
Remove the `blocklyFocused` CSS class and use the `focused` CSS selector instead

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8326]
1. Remove the `blocklyFocused` class from being assigned in [`menu.ts`](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/menu.ts#L160).
2. Remove the `blocklyFocused` class from being assigned in [`dropdowndiv.ts`](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/dropdowndiv.ts#L140).
3. Change the [styles in `css.ts`](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/css.ts#L122) to use the [`:focus` css pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus).

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by Skye967** [comment]
Can I get assigned to this?

**Comment by BeksOmega** [comment]
Go for it @Skye967 =) Let me know if you have any questions!

**Comment by BeksOmega** [comment]
Closed by #8360
