### ISSUE TITLE
Remove the `blocklyMenuItemHighlight` CSS class and use the `hover` CSS selector instead

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8327]
1. Remove the `blocklyMenuItemHighlight` CSS class from the [menu item](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/menuitem.ts#L73).
2. Use the [`:hover` CSS pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) in [`css.ts`](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/css.ts#L481).

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by Arun-cn** [comment]
I like to work on this issue

**Comment by BeksOmega** [comment]
Go for it @Arun-cn =) Let me know if you have any questions!

**Comment by Arun-cn** [comment]
Please inform me if any changes are required. Additionally, provide more context. Answer the question of why that change is necessary.

**Comment by gonfunko** [comment]
Fixed by #8536.
