### ISSUE TITLE
Remove the `blocklyNonSelectable` CSS class and include non-selectability in existing classes instead

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8328]
The [`blocklyNonSelectable` class](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/css.ts#L84) just disables user selection. Instead of having a CSS class that is used to apply one CSS rule, we should include the rule in a more relevant class.

**Comment by dakshkanaujia** [comment]
Hey! @BeksOmega, please assign me this issue, I am working on it!

**Comment by BeksOmega** [comment]
Hiya @dakshkanaujia Go for it! Let me know if you have any questions =)

**Comment by dakshkanaujia** [comment]
Hey @BeksOmega, I can see the issue. The blocklyNonSelectable class is redundant. I can implement the functionality directly in the existing class. Am I on the right track?

**Comment by BeksOmega** [comment]
Yes! You want to move `user-select: none` into other CSS classes that are also defined on the DOM element.

**Comment by dakshkanaujia** [comment]
Hey @BeksOmega , can you help me with how can I proceed from here , to get this PR merged. I am facing issue in signing the CLA thing.

**Comment by BeksOmega** [comment]
Closed by #8433
