### ISSUE TITLE
Rename the blockly icon CSS classes to use camelCase

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8329]
Rename the following CSS classes and references to them:

* `.blockly-icon-comment` -> `blocklyCommentIcon`
* `.blockly-icon-warning` -> `blocklyWarningIcon`
* `.blockly-icon-mutator` -> `blocklyMutatorIcon`

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by ga-fleury** [comment]
Hey @BeksOmega, I'd like to work on this

**Comment by BeksOmega** [comment]
Sweet, thanks for the comment @ga-fleury =)
