### ISSUE TITLE
Add a `blocklyTextBubble` CSS class to the text bubble

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8331]
In the [text bubble constructor](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/bubbles/text_bubble.ts#L26), add a call to `dom.addClass` that adds a `blocklyTextBubble` CSS class to the `this.svgRoot`.

This change should be made against the `rc/v12.0.0` branch.

To work on this issue, comment below asking to be assigned.

**Comment by Nirmalkumar6112** [comment]
Hey @BeksOmega, I would like to work on this.

**Comment by BeksOmega** [comment]
@Nirmalkumar6112 sweetness :D Thanks for commenting! I've assigned you, and I'll take a look at your PR.

**Comment by siddharthbaleja7** [comment]
@Nirmalkumar6112 Please assign this issue to me.

**Comment by BeksOmega** [comment]
Closed by #8333
