### ISSUE TITLE
Add a `blocklyToolboxFlyout` CSS class to the flyout if it is used by the toolbox

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8341]
In the [`init` method](https://github.com/google/blockly/blob/f8025a1bdd12025ecb8830159509148ff27ad3c8/core/toolbox/toolbox.ts#L146) on the toolbox before inserting the result of `this.flyout.createDom` into the dom call `dom.addClass` with the created DOM element and `blocklyToolboxFlyout`.

This change should be made against the `rc/v12.0.0` branch.

To work on this issue, comment below asking to be assigned.

**Comment by nullHawk** [comment]
Hi @BeksOmega , I would like to work on this issue.

**Comment by Shreshthaaa** [comment]
Hey @BeksOmega, I would like to work on this issue. Kindly assign it to me.

**Comment by BeksOmega** [comment]
Go for it @nullHawk =)

**Comment by nullHawk** [comment]
Hi @BeksOmega, I have raied the [PR](https://github.com/google/blockly/pull/8386), please have a look at it

**Comment by BeksOmega** [comment]
Closed by #8386
