### ISSUE TITLE
Rename the `blocklyToolboxDiv` CSS class to `blocklyToolbox`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8343]
Rename any references to `blocklyToolboxDiv` to `blocklyToolbox`.

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by Venki1402** [comment]
@BeksOmega I would like to work on this issue. Can you assign it to me?

**Comment by BeksOmega** [comment]
Go for it @Venki1402 =)

**Comment by Venki1402** [comment]
@BeksOmega Thanks!

**Comment by ruthwikchikoti** [comment]
hey @Venki1402 i want to work on this issue !!!

**Comment by Venki1402** [comment]
@BeksOmega could you pls review this PR?

**Comment by shivam1234100** [comment]
Hey @BeksOmega can I work on this?

**Comment by BeksOmega** [comment]
Sure @shivam1234100 =) Let me know if you have any questions!
