### ISSUE TITLE
Rename the `blocklyToolboxContents` CSS class to `blocklyToolboxCategoryGroup`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8344]
Rename any references to `blocklyToolboxContents` to `blocklyToolboxCategoryGroup`.

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by Venki1402** [comment]
@BeksOmega I would like to work on this issue. Can you assign it to me?

**Comment by BeksOmega** [comment]
Go for it @Venki1402 =) Let me know if you have any questions!

**Comment by Venki1402** [comment]
@BeksOmega Thanks!!

**Comment by ruthwikchikoti** [comment]
hey @Venki1402  can i work on this

**Comment by Venki1402** [comment]
@ruthwikchikoti sure!

**Comment by ruthwikchikoti** [comment]
@BeksOmega  can you please assign this issue  me !!

**Comment by BeksOmega** [comment]
@ruthwikchikoti Are you still interested in working on this issue? It looks like you deleted your fork of Blockly.

**Comment by ruthwikchikoti** [comment]
@BeksOmega  working on this

**Comment by ruthwikchikoti** [comment]
@BeksOmega  can you review 
moreover i am facing issue in CLA even after signing the form

**Comment by BeksOmega** [comment]
Closed by #8384
