### ISSUE TITLE
Rename the `blocklyTreeRow` CSS class to `blocklyToolboxCategory`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8345]
Rename any references to `blocklyTreeRow` to `blocklyToolboxCategory`.

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by Abhinav-Chdhary** [comment]
### Hi Beka! Can I work on this?
I tried to identify the files that reference to **blocklyTreeRow** and there are only 3. 
Is there anything else I should change except just renaming?

**Comment by BeksOmega** [comment]
Go for it @Abhinav-Chdhary =) Nope just those changes!
