### ISSUE TITLE
Rename the `blocklyTreeIcon` CSS class to `blocklyToolboxCategoryIcon`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8347]
Rename any references to `blocklyTreeIcon` to `blocklyToolboxCategoryIcon`.

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by krishchvn** [comment]
Hey. Can you assign the issue to me please?
I'm new to github commands, I don't know how to reflect the change 'against' some branch. Could you help me with that?

**Comment by ruthwikchikoti** [comment]
@BeksOmega, please assign this to me. I'm eager to work on it.

**Comment by BeksOmega** [comment]
Go for it @krishchvn ! I believe you are correct and there are only two instances =)

**Comment by BeksOmega** [comment]
Closed by #8367
