### ISSUE TITLE
Rename the `blocklyTreeIconOpen` CSS class to `blocklyToolboxCategoryIconOpen`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8348]
Rename any references to `blocklyTreeIconOpen` to `blocklyToolboxCategoryIconOpen`.

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by Harsh-svg988** [comment]
hey @BeksOmega can you assign me this issue

**Comment by ruthwikchikoti** [comment]
@BeksOmega Could you please assign me this issue? I’d like to work on it. Thanks!

**Comment by BeksOmega** [comment]
Hiya @Harsh-svg988 , go for it! Let me know if you have any questions =)

@ruthwikchikoti I assigned you a different issue =)

**Comment by Shreshthaaa** [comment]
Hey @BeksOmega, I would like to work on this issue.

**Comment by poojatalele** [comment]
I would like to work on this issue, kindly assign.

**Comment by srivastavaarpit977** [comment]
Hey @BeksOmega I want to work on this issue.....plz assign this issue to mee

**Comment by AbhinavKRN** [comment]
hey @BeksOmega can you assign this issue to me?

**Comment by UtkershBasnet** [comment]
@BeksOmega can you please review my PR.

**Comment by BeksOmega** [comment]
Closed by #8440
