### ISSUE TITLE
Rename the `blocklyTreeIconClosed` CSS class to `blocklyToolboxCategoryIconClosed`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8349]
Rename any references to `blocklyTreeIconClosed` to `blocklyToolboxCategoryIconClosed`.

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by YashrajKupekar17** [comment]
@BeksOmega I would like to work on this issue. please could you assign me this issue?

**Comment by BeksOmega** [comment]
Go for it @YashrajKupekar17 =) Let me know if you have any questions!

**Comment by harsh-791** [comment]
@BeksOmega If no one is working on this, I  would llike to work on this

**Comment by BeksOmega** [comment]
Go for it @harsh-791

**Comment by harsh-791** [comment]
@BeksOmega Can u review this PR and tell me if any changes need to be done

**Comment by crazyshrut** [comment]
Hey @BeksOmega , is it done?
I would like to work on this. 
if not done, kindly assign it to me.
