### ISSUE TITLE
Rename the `blocklyTreeLabel` CSS class to `blocklyToolboxCategoryLabel`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8350]
Rename any references to `blocklyTreeLabel` to `blocklyToolboxCategoryLabel`. 

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by YashrajKupekar17** [comment]
@BeksOmega I would like to work on this issue, please assign this to me.

**Comment by BeksOmega** [comment]
Go for it @YashrajKupekar17 ! Thanks for picking this up =)

**Comment by harsh-791** [comment]
@BeksOmega i would like to work on this issue

**Comment by siddharthbaleja7** [comment]
is this issue still open?

**Comment by BeksOmega** [comment]
Yep looks like this hasn't been worked on. Go for it @siddharthbaleja7 =) Let me know if you have questions!

**Comment by DevMhrn** [comment]
@BeksOmega I have collaborated with @siddharthbaleja7 ans solved this issue he unassigned himself so that I can solve this.  I have solved this and could raise pr for it

**Comment by DevMhrn** [comment]
@BeksOmega Please review this pr. I have solved this issue

**Comment by srivastavaarpit977** [comment]
@BeksOmega ...I have collaborated with @DevMhrn,he is not active to solve this issue so can you plz assign this issue to me!!

**Comment by BeksOmega** [comment]
Done @srivastavaarpit977 =)

**Comment by srivastavaarpit977** [comment]
@BeksOmega plz review the PR...I have solved the issue.Thanks!!
