### ISSUE TITLE
Rename the `blocklyTreeSelected` CSS class to `blocklyToolboxSelected`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8351]
Rename any references to `blocklyTreeSelected` to `blocklyToolboxSelected`.

This change should be made against the `rc/v12.0.0` branch. This should be marked as a breaking change.

To work on this issue, comment below asking to be assigned.

**Comment by Harsh-svg988** [comment]
@BeksOmega can you assign this to me

**Comment by ruthwikchikoti** [comment]
@BeksOmega  i want to work on this

**Comment by BeksOmega** [comment]
Hiya @Harsh-svg988 Go for it =)

**Comment by Adityajaiswal03** [comment]
hey @Harsh-svg988  can you please assign this issue to me

**Comment by omwagh28** [comment]
@Harsh-svg988 I haved solved this issue could you assign it to me if you aren't working on this please

**Comment by omwagh28** [comment]
@BeksOmega I collaborated with @Harsh-svg988 and solved this he unassigned himself so that i can solve this issue 
I have raised a PR for it

**Comment by BeksOmega** [comment]
Closed by #8459
