### ISSUE TITLE
Delete the `InsertionMarkerManager`

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#8353]
We should delete the `InsertionMarkerManager` and any remaining references to it. There may be some complications where it hooks into the renderer that mean we have to keep some enums.

**Comment by ChaitanyaYeole02** [comment]
Hey. Can you assign the issue to me please?

**Comment by BeksOmega** [comment]
Go for it @ChaitanyaYeole02 =) Let me know if you have any questions!

**Comment by BeksOmega** [comment]
Ah actually @ChaitanyaYeole02 I didn't realize this wasn't a `good-first-issue` when I assigned it. Might be better to start with something like https://github.com/google/blockly/issues/8342 instead =)

**Comment by ChaitanyaYeole02** [comment]
Ok sure, I will work on #8342 instead.

**Comment by ChaitanyaYeole02** [comment]
Hey @BeksOmega, I have done two good first issues. I am not able to find any more available right now. Do you think, that I could work on this right now?

**Comment by BeksOmega** [comment]
Sounds good! But like the issue warns, there might be some trickiness. Let me know if you have any questions =)

**Comment by ChaitanyaYeole02** [comment]
@BeksOmega, what will be the type of this issue?
I think this is a `chore`, but can you please confirm this?

**Comment by BeksOmega** [comment]
> @BeksOmega, what will be the type of this issue? I think this is a `chore`, but can you please confirm this?
> 
> https://developers.google.com/blockly/guides/contribute/get-started/commits
> 
> I am referring this.

Yes chore is correct!

**Comment by ashmichheda** [comment]
@BeksOmega - Is this issue still open?
