### ISSUE TITLE
Unpin node 22 in `build` workflow

### ISSUE THREAD

**Issue by cpcallen** [google/blockly#8392]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Problem

Due to an issue with node.js v22.5.0 (see e.g. nodejs/node#53902) and/or the npm v10.8.2 (see e.g. npm/cli#7657 amongst many) the CI `build` workflow has been failing for node.js v22.x.  In PR #8393, it was pinned to v22.4.1.

### Request

Once these bugs are resolved it should be unpinned.

**Comment by TUSHAR1651** [comment]
@BeksOmega I want to work on this issue can you please assign this issue to me

**Comment by BeksOmega** [comment]
Sorry @TUSHAR1651 this is actually already fixed by https://github.com/google/blockly/pull/8398 I just forgot to mark it properly.
