### ISSUE TITLE
Infinite loop when handling 'pointermove' events.

### ISSUE THREAD

**Issue by mikeharv** [google/blockly#8396]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Users get `RangeError: Maximum call stack size exceeded` if they attempt to drag a block with multiple fingers on a workspace where zoom controls/wheel are disabled.

My understanding of these two functions is as follow:
1. **`handleMove` Function:**
   - Checks if the gesture is a drag or a multi-touch event
   - If it's a multi-touch event, it calls `handleTouchMove`.

2. **`handleTouchMove` Function:**
   - Updates cached touch points and checks for pinch zoom conditions.
   - If the conditions for pinch zoom are not met, it calls `handleMove` again.

If there's a multi-touch event that doesn't meet the conditions for a pinch zoom, an infinite loop is created.

Code.org use NewRelic to detect JS errors like this. Since migrating two more labs to Google Blockly this week (:tada:), the errors have been above our threshold causing an alarm. This alarm pages our on-call engineer. 

In order to fix this, I was able to monkey-patch `handleMoveTouch` to independently handle the touch events without needing to call `handleMove` again: https://github.com/code-dot-org/code-dot-org/pull/59864

### Reproduction steps

1. On a touch device, go to the advanced playground.
2. Disable zoom wheel and controls
3. Add block to the workspace.
4. Using two fingers, attempt to drag the block.
5. Observe the range error in the console.

### Stack trace

```shell
[Error] RangeError: Maximum call stack size exceeded.
	handleTouchMove (blockly_compressed.js:733)
	handleMove (blockly_compressed.js:730:349)
```

...repeats infinitely...

### Screenshots

<img width="403" alt="image" src="https://github.com/user-attachments/assets/0fb5303b-e406-458c-98e3-c36caf8e2f7c">

**Comment by cpcallen** [comment]
Hi @mikeharv.  Thanks for finding this.  We'd take a patch for it, if you would be so kind as to submit one.

**Comment by AbhinavKRN** [comment]
@mikeharv can you assign this issue to me?

**Comment by mikeharv** [comment]
@cpcallen We've been running this patch for a couple weeks without any reported issues: https://github.com/code-dot-org/code-dot-org/blob/189a4fd5e223ffebcaf19677d0d9788e13a52625/apps/src/blockly/addons/cdoGesture.js

It does repeat some code shared by `handleMove`, but if you like the approach I'm happy to find a time to submit.

@AbhinavKRN I do not have permissions to assign issues from this repository, sorry!

**Comment by BeksOmega** [comment]
Hiya @AbhinavKRN if you're still interested feel free to give this a shot!

**Comment by AbhinavKRN** [comment]
@BeksOmega On it!

**Comment by AbhinavKRN** [comment]
@BeksOmega Can you let me know in which typeScript file do I get to read the code of handleTouch function and handleMoveTouch function

**Comment by BeksOmega** [comment]
> @BeksOmega Can you let me know in which typeScript file do I get to read the code of handleTouch function and handleMoveTouch function

Did you try searching for those strings in this repo? https://github.com/search?q=repo%3Agoogle%2Fblockly%20handleTouchMove&type=code
