### ISSUE TITLE
RFE: Configure input inlining per input.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#845]
We've see two different requests for this feature, and we have a hack for web, but the second request came for Android.

https://groups.google.com/forum/#!msg/blockly/Bf6mp2vBTUc
https://groups.google.com/forum/#!topic/blockly/Q3Pbf_YO1Sg

**Comment by samubura** [comment]
This could give greater flexibility and avoid the "whiteboxes" when having inline multiple inputs with different sizes! I support this!

**Comment by BeksOmega** [comment]
Dupe of #216
