### ISSUE TITLE
Documentation incorrect for "prevStatement" JSON block definition

### ISSUE THREAD

**Issue by timdawborn** [google/blockly#847]
The documentation on https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks gives the JSON key for enabling the previous statement on a block two different names at different points on the page: `prevStatement` and `previousStatement`. Only the later of the two is accepted by Blockly.

**Comment by AnmAtAnm** [comment]
Thanks for catching this.  Fixing this now.

**Comment by AnmAtAnm** [comment]
Fixed
