### ISSUE TITLE
Expose workspace to the browser developer tools

### ISSUE THREAD

**Issue by UCYT5040** [google/blockly#8471]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Request

It would be useful if the `workspace` from the playground was exposed to the console in the browser's developer tools. This would make testing easier.

### Alternatives considered

If it's not acceptable to have the workspace immediately available, although I cannot think of a reason why that wouldn't be, there could be a button in the advanced playground to expose that.

**Comment by BeksOmega** [comment]
You can use `Blockly.getMainWorkspace()` in the console!
