### ISSUE TITLE
Variable deletion confirmation prompt is not shown when deleting a variable with one reference from the flyout

### ISSUE THREAD

**Issue by gonfunko** [google/blockly#8528]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Normally when a variable is deleted, Blockly will confirm that you want to also delete blocks that reference the variable before proceeding. However, if only one block referencing a variable is placed on the workspace, and the variable is deleted via the variable dropdown menu item of a block *in the flyout*, the confirmation is not shown, and the block and variable are immediately deleted.

### Reproduction steps

1. Go to https://google.github.io/blockly-samples/plugins/continuous-toolbox/test/index.html (This is not dependent on the continuous toolbox, but that demo is the easiest way to get a non-autoclosing flyout)
2. Create a variable
3. Drag a block that references that variable into the workspace
4. From the variable picker dropdown menu of one of the blocks in the flyout, click the "Delete the 'X' variable" menu item
5. Observe that the variable and block in the workspace are deleted with no confirmation

**Comment by abhinavjha0239** [comment]
@gonfunko can i work on this issue?

**Comment by gonfunko** [comment]
I already have a fix for it in #8529, thank you though!
