### ISSUE TITLE
Workspace comments and comment drag strategy undo bug with multiselect plugin

### ISSUE THREAD

**Issue by changminbark** [google/blockly#8531]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

After multiselecting comments, copy/pasting them, and then undoing that action does not get rid of the comments from the multiselection. This is usually not a problem as it also happens to blocks. However, the blocks and comments have different isMovable (drag strategy) and isDeletable methods, which lead to a breaking behavior in the multiselect plugin. I have already tested a fix for this by implementing the missing isDeadOrDying() check for the isMovable and isDeletable methods for comments.

### Reproduction steps

1. 
2. 
3.

**Comment by changminbark** [comment]
I have made a PR to fix this issue.

**Comment by cpcallen** [comment]
Hi @changminbark.  Thanks for the bug report and PR.  Can you provide steps to reproduce this issue, please?  It would be great if it included a minimal `index.html` that has all the required imports, but at minimum please include a link to a demo page and fill in the numbered reproduction steps in enough detail that we can try it out.
