### ISSUE TITLE
Next.js Export Breaks Blockly

### ISSUE THREAD

**Issue by DylDevs** [google/blockly#8563]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

Hello!
I have been building a Next.js app that uses Blockly for block based coding. It is fully working on localhost, but when I export it as static, it breaks the site.

Here's what it normally looks like:

![Screenshot 2024-09-02 at 08-22-30 ](https://github.com/user-attachments/assets/ba3046a8-4a0e-4679-a643-11ee9b0b5531)

Here's what it looks like after static export:

![Screenshot 2024-09-02 at 08-22-42 ](https://github.com/user-attachments/assets/0aac4dd6-10d9-4b0e-b421-5410aefbca95)

### Reproduction steps

1. Clone my [repository](https://github.com/DylDevs/Blockly-PyBricks) containing the code
2. `npm i && npm run dev` in the root directory, if you head to localhost:3000, you should see the functioning website.
3. Now, run the static export in the root directory `npm run build`
4. In the out folder that is generated, run the index.html file, and you'll see the broken website

### Browsers

Chrome desktop, Firefox desktop

**Comment by abhinavjha0239** [comment]
@BeksOmega hey I wanted to work on this.

**Comment by DylDevs** [comment]
This is still an issue, but instead of doing it this way, i used the GitHub pages Nextjs compiler, and it's working perfectly!

**Comment by GrahamSH-LLK** [comment]
This is very likely not a Blockly issue. You said you switched compilers- sounds like a setup issue on your side or a Next issue?

**Comment by DylDevs** [comment]
Might be, I have no idea. I'll report this to the Next devs when i get a chance.
