### ISSUE TITLE
bi-direction generate both in block and flowchart

### ISSUE THREAD

**Issue by mlzboy** [google/blockly#8579]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

most student learn programming at begging with flowchart ,hope blockly support flowchart automatic generate blocks also support the block to flowchart

### Request

most student learn programming at begging with flowchart ,hope blockly support flowchart automatic generate blocks also support the block to flowchart

**Comment by cpcallen** [comment]
This is a really interesting area of exploration, but unfortunately is out of scope for the Blockly team: we want to concentrate our resources on doing the things that we already do well.

Here are some things that you could do if you were interested in exploring this area:

* If you have a language for defining flowcharts in, it should be possible to write a [custom language generator](https://blocklycodelabs.dev/codelabs/custom-generator/index.html?index=..%2F..index#0) to produce flowcharts from a Blockly program.
* Converting flowcharts to blocks could take advantage of [the serialisation system](https://developers.google.com/blockly/guides/configure/web/serialization) to define a set of blocks from a flowchart.
* Other people have been interested in this topic; you could check [the Blockly forum](https://groups.google.com/g/blockly/) for previous conversations about it, and/or post something new to find others who are currently interested in this topic.
