### ISSUE TITLE
Creating an Object variable using XML

### ISSUE THREAD

**Issue by dkhan11** [google/blockly#858]
Hi,

I'm not sure what is the status of support for objects, as described here:
https://github.com/google/blockly/pull/243
If it is supported, can anyone please provide an example of how to use it using headless code generator, such as XML? I was looking for an example but I didn't find any.

Thanks in advance, 
DD.

**Comment by rachel-fenichel** [comment]
Objects are not supported.  #243 was a prototype but there's a lot of other work that would need to be done.
