### ISSUE TITLE
Custom idGenerator

### ISSUE THREAD

**Issue by FranciscoCaetano88** [google/blockly#8594]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Problem

Blockly's id generator soup has the '${' characters that in combination are special keywords in javascript. When such characters are present in a block/workspace id, which is used for various operations inside my code, it breaks.

### Request

I'd like to be able to customize Blockly's id generator soup variable to, in my case, remove the special keyword character '$'. Or customize the genUid function to follow my rules.

**Comment by cpcallen** [comment]
This shouldn't be a problem unless you're doing something weird—and possily insecure.  If you're putting block IDs into template literals, you should be escaping them.  If you're using generated block IDs in a toolbox definition, you can probably delete the IDs (or manually change them to something else).

I'm going to close this for now, but we're curious about what you're doing and if you can supply more information we might be able to suggest a better way to do it.

**Comment by weizhang-dotcom** [comment]
This stops AI to generate correct block json!!!!  Some AI can do this good, but a lot of AIs are stuck in building the json especially which hierarchy level reaches 9 or more.   

Now we are in AI era.  This issue should be fixed as quick as possible.
