### ISSUE TITLE
Use setText instead of setValue in fieldTextInput

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#860]
See #840

**Comment by BeksOmega** [comment]
Using setValue is now the recommended method for all fields.

**Comment by rachel-fenichel** [comment]
Remaining todo: check that procedure renaming works with `setValue`--that's what #840 was fixing.

**Comment by NeilFraser** [comment]
The current state is that `Blockly.Field.prototype.setText` and `Blockly.FieldImage.prototype.setText` are defined, but the only caller of `setText` is in `Blockly.Block.prototype.updateVarName`.  This is messed up, but I don't grok the current system to know what the intention is.

**Comment by BeksOmega** [comment]
> The current state is that `Blockly.Field.prototype.setText` and `Blockly.FieldImage.prototype.setText` are defined, but the only caller of `setText` is in `Blockly.Block.prototype.updateVarName`. This is messed up, but I don't grok the current system to know what the intention is.

Both of those calls are being removed by [this pr](https://github.com/google/blockly/pull/2668/files).

With regard to updating variables:
The original intention was to update the name of the variable, without updating the variable model (b/c the variable model is technically the same object, the name property just got changed). It /could/ call setValue(sameModel) instead, which would update the text & do some other stuff. But it is a little bit more efficient to just set the text.

With regard to the images:
This was originally intended as a way to be able to modify the alt text of an image. For example, if you want to change the value (src) you should probably also change the text (alt). 

But now those calls are getting their own explicit methods, which will make it more clear & easier to fiddle with in the future. (setText will rename on the image field for backwards compatibility)
