### ISSUE TITLE
Allow importing additional types (PuzzleTab, FlyoutItem, ImageProperties)

### ISSUE THREAD

**Issue by mikeharv** [google/blockly#8621]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Request

For some of our customization, we need to work with some Blockly types that are not available with the standard import of Blockly core.

Specifically, we've had to create local interface definitions for the following:
* `PuzzleTab`: https://github.com/google/blockly/blob/60da7d87625080ee44093c45a56689456883d6f6/core/field_dropdown.ts#L669-L674
* `FlyoutItem`: https://github.com/google/blockly/blob/60da7d87625080ee44093c45a56689456883d6f6/core/flyout_base.ts#L1372-L1376
* `ImageProperties`: https://github.com/google/blockly/blob/60da7d87625080ee44093c45a56689456883d6f6/core/field_dropdown.ts#L669-L674

These interfaces are exported from these files and used through the core Blockly repo, but don't seem to exported such that they can be accessed off of the imported `Blockly` object. Previously, we have been managing to access these types via deep imports, but as that will no longer work with v11, we've need to switch to re-defining each of these ourselves.

### Alternatives considered

With v10 and earlier, our build tools supported deep importing from Blockly to access these types. For v11, until this issue is resolved, we'll need to maintain duplicate definitions for each type.

**Comment by gonfunko** [comment]
Thanks for reporting! PuzzleTab should be available as `Blockly.blockRendering.PuzzleTab` - does that work for you? I've opened a PR to export the others along with some other missing types.
