### ISSUE TITLE
installer

### ISSUE THREAD

**Issue by BreadAndEggs** [google/blockly#8635]
### Check for duplicates

- [ ] I have searched for similar issues before opening a new one.

### Problem

i want a installer for blockly like an exe or msi

### Request

ufrhbrucbrhvbrhvbrhvb4bveh bvrv gvtvctyctgfrbhfruvcbudybcuev eu vudev yevuy4

**Comment by cpcallen** [comment]
Have you seen our [getting Blockly instructions](https://developers.google.com/blockly/guides/get-started/get-the-code)?  If you have node.js (and npm) installed on your machine already (which you'll need in any case) you can install Blockly with a single command.
