### ISSUE TITLE
debug / step through mode

### ISSUE THREAD

**Issue by jogibear9988** [google/blockly#8638]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Problem

I'd like to support a step through mode in my app wich is using blockly. As in my app, every command is async, it would easy to wait after each execution of a command, but is there support in the blockly UI for such a mode?

### Request

Support a debug / step through mode in the UI, with the posibillity to show results on the blocks

**Comment by gonfunko** [comment]
https://google.github.io/blockly-samples/examples/interpreter-demo/step-execution.html illustrates how to do this using the JS Interpreter package. If you run into issue with that or have specific questions, feel free to [post on the forum](https://groups.google.com/g/blockly)!
