### ISSUE TITLE
CWE-1333 in debug peer dependency

### ISSUE THREAD

**Issue by antoninmeunier** [google/blockly#8643]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

Hello,

We found an error CWE-1333 in the npm debug package which is a peer dependency of blockly : 

[jsdom @ 23.0.0] -> [http-proxy-agent @ 7.0.2] -> [debug @ 4.3.4]

Thanks for looking at it

### Reproduction steps

1. 
2. 
3.

**Comment by cpcallen** [comment]
Fixed by #8220, #8444, #8553, and #8604.
