### ISSUE TITLE
updateToolbox Do blocks in the workspace change when the blocks in the toolbox are modified?

### ISSUE THREAD

**Issue by xinSanta** [google/blockly#8653]
"I want to confirm something: Will the existing blocks in the workspace change if the blocks and parameters in the toolbox are updated? For example, if I'm editing in the workspace and then use updateToolbox to update the blocks and parameters in the toolbox, will the corresponding blocks in the workspace also change? In my project, this does happen, but we want to avoid this, so I just want to clarify this behavior."

Let me know if you need any further adjustments!

**Comment by gonfunko** [comment]
I see you also asked this on the forum - thank you! The forum is better suited for this type of question so I'll close this bug.
