### ISSUE TITLE
User functions may be called even when function definition is disabled

### ISSUE THREAD

**Issue by RealJohnSmith** [google/blockly#8661]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

This user program produces an illegal generated code:

![Image](https://github.com/user-attachments/assets/46e6dbdb-9023-4337-8ffb-0af864192446)

While there are mechanisms how to prevent this combination in the workspace, it does not catch all situations.

**Catches (good, expected):**
* When function definition is disabled while function call is in the scope, the function call gets disabled automatically as well

**Doesn't catch (bug):**
* When a function definition is already disabled, and a new function call is created (e.g. paste action or from a flyout), the function call is kept enabled (observed), however the expected behavior is that it will get disabled.

**Environment:**
I am using blockly installation from npm:
```
npm view blockly version 
11.1.1
```

### Stack trace

_Not relevant_

**Comment by gonfunko** [comment]
Thank you for reporting this! I've created a PR to resolve it.

**Comment by RealJohnSmith** [comment]
Thank you. When can we expect this in npm release?

**Comment by gonfunko** [comment]
Sure thing - we're tentatively aiming to have a release December 11th.
