### ISSUE TITLE
Dragging blocks does not work in IE10 

### ISSUE THREAD

**Issue by timdawborn** [google/blockly#871]
Block dragging appears to be offset by the scrollbar delta in IE10, rendering Blockly almost useless in IE10 as as soon as you click on a block, it jumps away from the mouse such that it's off the screen. See screen capture video: https://s3-ap-southeast-2.amazonaws.com/grok-uploads/bug-reports/blockly-IE10-block-dragging-bug.mp4

**Comment by fenichel** [comment]
I think this is a problem with our calculations as we put things back onto the workspace from the drag surface.

Not present in IE11 or Edge.

**Comment by rachel-fenichel** [comment]
Caused by #878 

Doesn't repro on chrome because of the user agent check.  We can now repro on Chrome and debug normally.

**Comment by rachel-fenichel** [comment]
Looks like removeAttribute may not be doing what we want when it's called on an SVG group.

If that's the case, blockSvg:clearTransformAttributes doesn't do anything on IE10.

```
/**
* Clear the block of transform="..." attributes.
* Used when the block is switching from 3d to 2d transform or vice versa.
* @private
*/
Blockly.BlockSvg.prototype.clearTransformAttributes_ = function() {
 this.getSvgRoot().removeAttribute('transform');
};
```
