### ISSUE TITLE
Documentation for dynamic toolbox categories

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#872]
#863 implemented this, but the documentation does not yet reflect it.

**Comment by carlosperate** [comment]
Is there more info about this somewhere?

**Comment by rachel-fenichel** [comment]
Not yet (hence this bug), but here's a first pass:

--------
Developers may also use the `custom` property to create dynamically populated flyout categories.
For example, to create a flyout with a custom set of colour blocks:
- Create a category with a custom property.
`<category name="Colours" custom="COLOUR_PALETTE"></category>`
- Define a callback to provide the category contents.  This callback should take in a workspace and return an array of XML block elements.
```
/**
 * Construct the blocks required by the flyout for the colours category.
 * @param {!Blockly.Workspace} workspace The workspace this flyout is for.
 * @return {!Array.<!Element>} Array of XML block elements.
 */
myApplication.coloursFlyoutCallback = function(workspace) {
  // Returns an array of hex colours, e.g. ['#4286f4', '#ef0447']
  var colourList = myApplication.getPalette();
  var xmlList = [];
  if (Blockly.Blocks['colour_picker']) {
    for (var i = 0; i < colourList.length; i++) {
      var blockText = '<xml>' +
          '<block type="colour_picker">' +
          '<field name="COLOUR">' + colourList[i] + '</field>' +
          '</block>' +
          '</xml>';
      var block = Blockly.Xml.textToDom(blockText).firstChild;
      xmlList.push(block);
    }
  }
  return xmlList;
}
```
- Register the callback on the workspace.
`myWorkspace.registerToolboxCategoryCallback('COLOUR_PALETTE', 
    myApplication.coloursFlyoutCallback);`


--------
This documentation would live in the [Categories](https://developers.google.com/blockly/guides/configure/web/toolbox#categories) section of the toolbox documentation.

**Comment by carlosperate** [comment]
This looks great, I might have a use for it in the near future, thanks @rachel-fenichel.

**Comment by rachel-fenichel** [comment]
Now live: https://developers.google.com/blockly/guides/configure/web/toolbox#dynamic_categories
