### ISSUE TITLE
realtime not working playground.html 

### ISSUE THREAD

**Issue by jcmack** [google/blockly#88]
I noticed that realtime wasn't working in tests/playground.html nor in demos/realtime/index.html. I have included the steps to reproduce. Let me know you need more information or I need to configure something else. 

OS: Ubuntu 14.10 (64-bit)
Google Chrome: Version 41.0.2272.101 (64-bit)
Google Closure: 848686a4791374beaa99478cdf37d95deb2752e1
Commit: 706080c7ae49f6ccc6e3de68afe42d7ceabf8834
Last known working commit: 8d537888107b9588d92b05e886871a75692de6f7

Steps to reproduce:
1. Go to /blockly/tests/playground.html. In start() set realtime to true and change clientId to valid client id. 
2. Run in localhost or appengine. I tested both. I use WebStorm for running locally. 
3. Login in your google account and agree.
4. After the workspace is reloaded, click on any block in the workspace and no flyout menu will appear. I included a screenshot of the javascript console.

![screenshot from 2015-03-22 13 52 01](https://cloud.githubusercontent.com/assets/4740942/6771429/c8bedbfa-d09a-11e4-8d38-0828fb92f0fe.png)

**Comment by NeilFraser** [comment]
Yes, realtime broke in December as a result of a large refactoring
(headless blocks and workspaces).

Realtime was very buggy when it was 'working', it has always been in
alpha.  Nobody is currently working on it, but it is something we'd like to
get working properly eventually.

It is worth noting that although headless broke realtime, headless should
make realtime easier and more reliable.  Sort of a good news bad news
situation.

Send (awkwardly) from an Android phone.

**Comment by NeilFraser** [comment]
The Realtime feature this issue pertained to was removed from Blockly many years ago since we could not get it to work.  Any future realtime will be based on Blockly's events, not Google's sharing API.  Closing as obsolete.
