### ISSUE TITLE
Opening flyouts broken on Firefox in touch

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#883]
Clicking on a toolbox category opens the flyout for a second, and then it closes.

Tested on desktop firefox in responsive mode, with touch events turned on and a reload.  This occurs on master.

This does not happen with a mouse.

**Comment by picklesrus** [comment]
Do events have to be turned on for this to be a problem?  I did test firefox on an android tablet when I did the drag surface stuff so I'm wondering if this is just a responsive mode thing.  Charging up the tablet to see if the live demo still works on there.

**Comment by rachel-fenichel** [comment]
I didn't turn events on.

If this is just a problem with responsive mode that would be excellent.

**Comment by picklesrus** [comment]
Oh, whoops, processed that as the wrong type of events.

Anyway, the playground on Firefox on a Nexus 9 is working. I can open categories, scroll the flyout and takes blocks out of it and put them on the workspace.

I haven't tried it on iOS or windows though.
