### ISSUE TITLE
Event for committing a text field edit

### ISSUE THREAD

**Issue by stevekrouse** [google/blockly#890]
Whenever blockly fires a change event, my app recompiles and runs that code for the user. This works great except in the case of the input field when a user makes a lot of changes all at once. 

I cannot see a way (without editing blockly source code) to allow myself to detect when a user is *finished* making changes to an input text field, as opposed to just typing in it. 

My messy work-around is that I dirty modify blockly source code so that input fields only emit a change event when they are blurred (when the user clicks out of them or clicks enter), not when they are typed into.

**Comment by rachel-fenichel** [comment]
We don't have a specific event for committing a text field edit.  In this case I suggest waiting a few ms between getting a change event and recompiling, and resetting your delay every time you get a new change event.

**Comment by stevekrouse** [comment]
Thanks, Rachel! I did try throttling my compile function with a higher number of ms. The problem, as you'd expect, is that the delay is either too slow for regular block editing or too fast for text editing. Without a separate event for committing a text field edit, it's impossible to optimize both use cases and you have to pick a compromise in between.

Even given how annoying maintaining this as a "dirty change" is, I will opt for that option for now because it's important to me that the delay be optimized well for both use-cases,

**Comment by rachel-fenichel** [comment]
Hi Steve,

That's a good point, and I'll keep it in mind.  I'm going to update the title of the issue to reflect that.

**Comment by stevekrouse** [comment]
Thanks!

**Comment by BeksOmega** [comment]
This is covered by the new `FieldIntermediateChange` events.
