### ISSUE TITLE
Problem deleting blocks with the delete key until you do certain actions

### ISSUE THREAD

**Issue by stevekrouse** [google/blockly#891]
This is a strange bug and I haven't had much success debugging it in the Blockly source, but I am able to reproduce it:

1. Go to https://developers.google.com/blockly/

2. Click on a block

3. Click delete. (Notice that nothing happens when the block should've deleted itself.)

4. Drag that same block to the toolbox or the trashcan. (Notice that the blocks delete properly.)

5. Here you can do a number of different actions that will all have the same effect, namely allowing you to delete blocks via the delete key:

  - click on the variable menu of a block as if to change or rename the variable 

  - open and close an arbitrary toolbox menu

6. Click on a block and press the delete key. (Notice now that the block now deletes via the delete key.)

**Comment by picklesrus** [comment]
I played around with a little demo I have locally and I think it is related to whether the parent document or the iframe has focus. When the parent frame has focus, I believe the delete key (and any of the keyboard listeners) don't fire.

**Comment by stevekrouse** [comment]
That's a good guess! I'm going to go ahead and un-iframe myself here and hope a lot of these problems magically disappear. Thanks for all your help :)

**Comment by stevekrouse** [comment]
Removing the iframe did fix this bug
