### ISSUE TITLE
Clicking on the workspace causes the workspace to jump N pixels north-west

### ISSUE THREAD

**Issue by timdawborn** [google/blockly#892]
This is running `HEAD` of `develop` (ff578359a697d93d4a6aa19677d38cb3034b841e) as of the time of filing this ticket. Best illustrated by a screen capture: https://s3-ap-southeast-2.amazonaws.com/grok-uploads/bug-reports/workspace-jumping-bug.mov

This is really annoying for not-wide blocks as often the entire connected component disappears underneath the flyout.

**Comment by timdawborn** [comment]
It's actually worse than I initially found. Have a look at this screen capture: https://s3-ap-southeast-2.amazonaws.com/grok-uploads/bug-reports/workspace-jumping-bug2.mov

 When the blocks end up in this broken state, they don't move with the workspace when the workspace is panned. The blocks stay fixed when the grid moves.

Also note at the end of the screen capture that some of the blocks disappear completely behind the flyout. When the flyout is opened, they are restored to the positions they should be at, but when the workspace is clicked again, they return to the broken state.

**Comment by timdawborn** [comment]
Well, that's embarrassing. Apparently I caused this with the CSS changes to support older webkit browsers.

```
$ git bisect bad
39731c6ddc28febe844235dfbfd7dd222367820d is the first bad commit
commit 39731c6ddc28febe844235dfbfd7dd222367820d
Author: Tim Dawborn <tim.dawborn@gmail.com>
Date:   Sat Jan 28 04:19:58 2017 +1100

    Change CSS transforms to work with older browsers (#879)
...
```

I'll look into why that's the case...

**Comment by picklesrus** [comment]
Thanks for the fix!
