### ISSUE TITLE
No docs for static functions on developers.google.com (Blockly.Utils, Blockly.Xml, etc.). Broken links.

### ISSUE THREAD

**Issue by benjie** [google/blockly#896]
It's referenced from "Index All": https://developers.google.com/blockly/reference/js/index-all

But it cannot be loaded, gives a 404:

https://developers.google.com/blockly/reference/js/Blockly.Xml#.blockToDom

**Comment by RoboErikG** [comment]
It looks like this is an issue with linking to .xml files (whether or not they're actually xml). We'll have to figure out a workaround to make those accessible. In the meantime, you can look at the [file that generated the docs](https://github.com/google/blockly/blob/master/core/xml.js) in the source code.

Thanks for the bug!

**Comment by AnmAtAnm** [comment]
<Sigh>  Our jsdoc script is not creating this file at all. I'm investigating.

**Comment by AnmAtAnm** [comment]
This should now be fixed.  Source updates pending in #900.
