### ISSUE TITLE
Add password field to Blockly

### ISSUE THREAD

**Issue by asalmhofer** [google/blockly#906]
It is currently not possible to add a password field (i.e. a normal textfield, where bullets are shown instead of clear text characters) in a Blockly block.

Would it be possible to implement such a password (secret) field and provide it as input type for blockly?

Thank you!

**Comment by RoboErikG** [comment]
Blockly probably won't support that use case as it would give the impression of being secure without actually being secure.

The trivial implementation if you want to add it to your own project would be to add a new field that extends input field and have it set the right html tags to render as a password.

**Comment by AnmAtAnm** [comment]
It's worth noting the primary concern is any password field would would result in a plain text password in the generated source code (at least, without a significant overhaul to do it right).
