### ISSUE TITLE
Adding a variable from within a field_variable dropdown disappeared

### ISSUE THREAD

**Issue by stevekrouse** [google/blockly#915]
There used to be a way to create a new variable in a dropdown, but it is no longer there.

There used to be `variableList.push(Blockly.Msg.NEW_VARIABLE);` in [creating a field_variable's dropdown](https://github.com/google/blockly/blob/5c2c4d8400e672636d33f910117683137a667a6b/core/field_variable.js#L112) so I assume that's what's causing this because that line is no longer there.

I wasn't able to conclusively find the commit that changed this. The closest I came is that before https://github.com/google/blockly/commit/350e1ff2cc79994bad130ee2cf0a59a6bfe27d2e it was there and after that commit it was not (however I you don't see the line removed in that commit's diff which is really befuddling).

Is this a bug or did you all purposefully remove this feature? Thanks!

**Comment by rachel-fenichel** [comment]
Hi Steve,

I removed this feature last year.  See https://groups.google.com/forum/#!searchin/blockly/variable|sort:relevance/blockly/4g-jvqrydLg/S1csbFioBQAJ

That set of changes made variable creation and deletion more explicit, which makes typed variables possible in the future.  Variable creation is now with a button in the toolbox.

**Comment by stevekrouse** [comment]
Ok, thanks Rachel!
