### ISSUE TITLE
auto scroll to an absolute position

### ISSUE THREAD

**Issue by victoralex** [google/blockly#93]
I am currently using Blockly on an application where per screen there is a specific group of blocks. Essentially, blockly defines what will happen on various events, per screen.

When i go to a screen, the blocks for it must load on one active workspace which is reused.

i am using: blocklyObject.Xml.domToWorkspace( blocklyObject.mainWorkspace,   blocklyObject.Xml.textToDom( blocklyAsText ) );    

It seems that whenever i do this, the previous position on screen is not preserved, the blocks being positioned on a different offset every time, somehow related to the previous screen's blocks. It creates a confusing experience for the users, as they have to always scroll back to what they had before.

Could you please provide some feedback on how do i save the previous workspace scroll position for a group of blocks and how to restore it?

**Comment by victoralex** [comment]
Tried using  blocklyObject.mainWorkspace.scrollbar.set with blocklyObject.mainWorkspace.scrollY and  blocklyObject.mainWorkspace.scrollX, with their values cached per screen, however, no luck.

The end result is always different. I am sure there's something related to the ratio and transformations, but i believe it is over my head. Is there a function i could use for save / restore scroll positions on the fly?

**Comment by victoralex** [comment]
any feedback, guys?

**Comment by tarling** [comment]
You could try adding a custom node to the XML that you save.

```
var workspace = Blockly.mainWorkspace;
var xml = Blockly.Xml.workspaceToDom(workspace);
var custom = $.parseXML("<custom />").firstChild;
custom.setAttribute("scrollx", workspace.scrollX);
custom.setAttribute("scrolly", workspace.scrollY);
xml.insertBefore(custom, xml.firstChild);
//then save this XML somewhere
```

Then you can read the values from a saved file.

```
var content; //this has been read from an external source
var workspace = Blockly.mainWorkspace;
var xml = Blockly.Xml.textToDom(content);
Blockly.Xml.domToWorkspace(workspace, xml);
var custom = xml.getElementsByTagName("custom")[0];
if (custom)
{
  var scrollX = parseInt(custom.attributes.scrollx);
  if (!isNaN(scrollX)) workspace.scrollX = scrollX;
  var scrollY = parseInt(custom.attributes.scrolly);
  if (!isNaN(scrollY)) workspace.scrollY = scrollY;
  workspace.render();//update the workspace
}
```

**Comment by victoralex** [comment]
works nicely

thank you

**Comment by MNSDivya** [comment]
Can someone help me in reproducing the issue please.  @victoralex Does your last comment mean its working as expected? Please confirm.
