### ISSUE TITLE
Blockly: How to reduce the size of the trash in workspace?

### ISSUE THREAD

**Issue by shaokaoxianren** [google/blockly#936]
I wrote a blockly app with web , but when running on a mobile phone, trash icon look too big, how to reduce its size?

**Comment by picklesrus** [comment]
For future questions like these, that aren't necessarily bugs, I suggest mailing the blockly [google group](https://groups.google.com/forum/#!forum/blockly). You'll reach a wider audience of blockly users that are likely to have good advice.

 Here are a couple of suggestions to get you started:
1. Look at the trashcan code and see if you can change it to meet your needs.  You'll find the relevant parts here: https://github.com/google/blockly/blob/master/core/trashcan.js
2. You could not show the trash can at all by changing the options object that you send to Blockly.inject. Search for "trashcan" here https://developers.google.com/blockly/guides/get-started/web#configuration
