### ISSUE TITLE
Code for stubbing a function for a function call should move to workspace

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#942]
When the user pastes a function call that doesn't have an associated function definition we create an empty one with the right signature. The code that does this is defined in the [onChange methods](https://github.com/google/blockly/blob/develop/blocks/procedures.js#L685) of the function calls, though. It should be moved into a listener that is registered once on the workspace and handles all types of function calls, not on each function call block.

**Comment by rachel-fenichel** [comment]
@BeksOmega fyi here's an old issue about procedures.
