### ISSUE TITLE
Change playground background based on document URL.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#947]
To prevent developers trolling themselves with the wrong tab, adjust the playground background color (or similar) based on the window.document.URL pattern.
   If "file:.." URL, make it pale red.
   If "https://blockly-demo.appspot.com/static/tests/playground.html", leave it white. 
   Other "http:..." or "https:..." might be pale blue.

**Comment by ChristopherBlackman** [comment]
Would something like this be valid?

https://github.com/ChristopherBlackman/blockly/commit/21a1d531f6d2feb89ef64e31bf3200dbc6fa2a10

Just putting a helper function in-front of a index.html page>

**Comment by rachel-fenichel** [comment]
Done.  Thanks @ChristopherBlackman!
