### ISSUE TITLE
Flyout height is based on tallest category

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#966]
If the tallest category needs scrollbars, all flyouts categories will get scrollbars, all of which are the same size.  That points to en error in metrics recalculation when changing the flyout category.

Present in develop.
- Browser: Chrome
Not present in master.
- Browser: Chrome
Not release-blocking.

**Comment by picklesrus** [comment]
I'm going to guess that this was really #1195.
@rachel-fenichel Please re-open if you disagree.

**Comment by rachel-fenichel** [comment]
ohhhhh

Yeah that makes sense.
