### ISSUE TITLE
Warning thrown on some undo

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#968]
To repro:
1. Go to playground https://blockly-demo.appspot.com/static/tests/playground.html
2. Click Airstrike
3. undo (ctl-z) a bunch of times

You get a bunch of warnings (not on every undo) that look like this:

```
Can't change non-existant block: 3IcSq@ON|9Cg|ITI}n3.
Blockly.Events.Change.run @ events.js:548
Blockly.Workspace.undo @ workspace.js:421
Blockly.onKeyDown_ @ blockly.js:235
wrapFunc @ blockly.js:444
```

**Comment by moniika** [comment]
Can repro on master, but appears to be fixed on develop.
