### ISSUE TITLE
field_angle not rendering degree symbol consistently

### ISSUE THREAD

**Issue by maxosprojects** [google/blockly#973]
`field_angle` not rendering degree symbol consistently.

When creating an input block with a `field_angle` the degree symbol is not showing. It is showing only after the block is connected to some other block.
The issue appear in the `BlockFactory` as well.

The block is defined as follows:

```javascript
Blockly.Blocks['math_angle'] = {
  /**
   * Block for numeric angle value.
   * @this Blockly.Block
   */
  init: function() {
    this.setColour(Blockly.Blocks.math.HUE);
    this.appendDummyInput()
        .appendField(new Blockly.FieldAngle('0'), 'NUM');
    this.setOutput(true, 'Number');
    // Assign 'this' to a variable for use in the tooltip closure below.
    var thisBlock = this;
    // Number block is trivial.  Use tooltip of parent block if it exists.
    this.setTooltip(function() {
      var parent = thisBlock.getParent();
      return (parent && parent.getInputsInline() && parent.tooltip) ||
          Blockly.Msg.MATH_NUMBER_TOOLTIP;
    });
  }
};
```

Chrome 56.0.2924.87

**Comment by rachel-fenichel** [comment]
setText checks the source block to decide whether the degree symbol goes on the left or the right:

```
  // Insert degree symbol.
  if (this.sourceBlock_.RTL) {
    this.textElement_.insertBefore(this.symbol_, this.textElement_.firstChild);
  } else {
    this.textElement_.appendChild(this.symbol_);
  }
```

It's possible that setText is being called when connecting to another block and setValue is being called when the block is on its own, so it's skipping setting the degree.  I need to investigate further.
