### ISSUE TITLE
Inline and external input connectors

### ISSUE THREAD

**Issue by Nekomajin42** [google/blockly#976]
Hello!

I am building a visual formula editor for Excel, and I've bumped into a problem. It seems that a block can not have both inline and external input connectors at the same time. I've found a workaround, so my app works, but I have to use an additional block type, which makes the interface messier.

Would it be possible to solve this issue somehow?

**Comment by RoboErikG** [comment]
Hi Neko,

Probably not in the near future. Block layout is pretty complicated so it takes a while to think through the effects of any changes. We've seen a few requests for this, so we know there's interest, but there are other fixes and work that needs to come first.

**Comment by Nekomajin42** [comment]
Thanks for the answer! I am looking forward to it.
