### ISSUE TITLE
Merge PythonToBlocks into Blockly Factory

### ISSUE THREAD

**Issue by Immortalin** [google/blockly#977]
The [BlockyPy](https://github.com/RealTimeWeb/blockpy) [Project](http://think.cs.vt.edu/blockpy/load), has a feature called `PythonToBlocks` which allows for the direct generation of blocks by directly parsing the Python AST. The integration of this feature into the Blockly Factory would greatly improve its efficiency since the end-user would be able to generate blocks directly from code, instead of having to design them from scratch.

**Comment by RoboErikG** [comment]
We're happy some advanced apps are building ways to convert code into Blocks, but it's not a feature we'd like to support in core Blockly.
