### ISSUE TITLE
Performance regression when dragging blocks out of the flyout

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#981]
tldr: composite layers got quite expensive (~.2ms -> 40ms) when dragging a block out of the flyout.

This is present on develop. Marking as a bug for now since it is a big enough regression that I'd like to figure it out before we push to master.

See https://github.com/LLK/scratch-blocks/issues/835 for more context.

**Comment by picklesrus** [comment]
On second thought, I'm less convinced that this is new....

**Comment by picklesrus** [comment]
Long update with more context on how how things are done, what options I looked into and tradeoffs made with the PR I'm about to submit.

Some context of how things are done:
We show 3 different custom cursors for blockly.  We also show standard cursors for things like text boxes.

- Open hand 
     - when you’re hovering over a block in toolbox, flyout, or workspace
- Closed hand
    - when you have your mouse down on a block (i.e. when you initially mouse down on a block and when you’re dragging a block around).
- Closed hand with X
    - Indicates a block will be removed when you’re dragging a block and hovering over the trash or the toolbox

**Implementation**:
We use a custom .cur file for all 3 cursors.
To switch the cursor between the open hand, closed hand, and delete cursor we currently do the following:

1. Reach into the stylesheet, remove the .blocklyDraggable rule (which is assumed to be at position 0 in the css list, build a new one with the appropriate cursor and add it back.  
2. Since the toolbox is on top of the block, changing the .blocklyDraggable rule (which applies to blocks and bubbles) doesn’t work.  The toolbox’s cursor property overrides the block’s. Instead we loop over toolboxes (plural in case of multiple blockly instances on one page) and change the style of their cursor.

**Problem**:
This is slow. Changing the stylesheet can cause the browser to recalculate styles and repaint much larger swaths of the page than it really needs to.  For reasons I still don’t understand, fetching the .cur files is slow. Chrome’s timeline and network tool indicate that the cost is:
~10ms to load the .cur when running blockly via a file:// url.  
~ 65ms to load .cur when loading over the network (to appspot.com)
Could we cache this better?

A relatively clean technical solution
Do this in CSS.  We don’t need the custom .cur files for the open and closed hand since browsers (via vendor specific prefixes) supply them for us.  We still need the delete unless we’re willing to switch to one of the ones existing ones. See https://developer.mozilla.org/en-US/docs/Web/CSS/cursor.  “Not-allowed” is the most similar to our current hand with X.

CSS rules can handle the hand open/closed distinction on all blocks without javascript. Here are the rules we’d need. Note that the vendor specific prefixes have been removed to keep them short

To show the hand hand when hovering over blocks
```
.blocklyWorkspace .blocklyDraggable {
  cursor: grab;
}
```

To show the closed hand when blocks have the mouse down in them
```
.blocklyDraggable:active {
  cursor: grabbing;
}
```
To show the closed hand while dragging a block quickly and the mouse escapes the boundaries of the block  
```
.blocklyBlockDragSurface .blocklyDraggable {
     cursor: grabbing;
}

```
To show the delete cursor over the trash and the toolbox, we still need some javascript, but instead of changing the stylesheet, we add a class to block when it is over the trash or the toolbox.  We also still need to add a class to the toolboxes because of the ordering reasons mentioned above.

Problems:
The performance profile of this is much nicer since the browser seems to optimize changing the cursor via css much better.  There are a few tradeoffs:
- This solution takes advantage of the :active pseudo class to change the cursor when the user mouses down over a block. Unfortunately, blockly calls event.preventDefault() on a block mousedown.  The spec does not define behavior for :active in this case and Firefox does not apply the :active class (Edge, Chrome, Safari do). From a 5 year old bug, Firefox has no intention to fix this: https://bugzilla.mozilla.org/show_bug.cgi?id=771241.  Here’s a jsfiddle demonstrating the broken behavior in firefox: http://jsfiddle.net/kq4d03f1/
- setCursor is public so we have to deprecate it, but it generally is the wrong way to be doing this.
- The cursor turns back to whatever the surrounding page has it set to be when you drag outside the bounds of blockly.  This is especially noticeable when you delete a block from the blockly playground and drag your mouse to the left past the toolbox.
- There is a behavior change required such that a block doesn’t jump to the top (in z ordering) until either a drag starts, or, in the case of a click, the mouse up.  Here’s a jsfiddle that demonstrates the new behavior: http://jsfiddle.net/kq4d03f1/ For comparison, here’s the old behavior: http://jsfiddle.net/y051bt55/
 We currently do this on mouse down.  This is due to the interaction between the :active pseudo class and z ordering in SVG.  The only way to put an element on top of another element in SVG is for it to come first in a list.  For example, the block dom structure looks like this:
```
<g class = “blockCanvas”>
  <g class = ”blocklyDraggable> block JKL</g>
  <g class = ”blocklyDraggable> block ABC </g>
  <g class = ”blocklyDraggable> block XYZ </g>
</g>

```
In this case, if they overlap, block JKL sits on “top” of ABC and XYZ. If the user then clicks on block XYZ, we want to pop it to the front, but the only way to do that is to move it to be the first child of the <g class=”blockCanvas”>. This dom manipulation undoes the “active” element unless we delay it to the start of a drag or the end of a click.

**Another Try**:
Change setCursor to just change the draggable rule and call rule.style.cursor = “myCursor” instead of adding & deleting a rule.
No go:
This still recalculates style.

**Another Try**:
Instead of modifying the entire blocklyDraggable class’s cursor, only change the cursor on the block’s the user is interacting with.  In code: Replace calls of Blockly.Css.setCursor(cursor type) with calls to a function defined on block
The good:
Performance wise this works well.

The bad:
The code is tricky, especially in its current form where the terminateDrag function doesn’t necessarily have a block object to operate on. Here’s an example of how/when this gets tricky:

Dragging a block out of the flyout causes a mousedown on a flyout block (called originBlock in code), so we set cursor on the origin block to be the closed hand. When a new block is created on the main workspace via placeNewBlock_, it gets the closed hand style and the drag begins. At the end of the drag we trigger a mouse up on the new block, setting the cursor back to the open hand on hover. But, we never set the cursor on the flyout origin block back.  It isn’t that difficult to handle this particular case, but given the number of calls to terminateDrag in the code base, the potential for more edge cases is high.

There are a lot of variations on this approach (e.g. adding/removing classes from the block instead of directly modifying the style attribute), but they all run into the same issue with not reliably being able to map the end of an interaction (by losing a mouse up, etc.) back to the block that it began on.  This part of the code is being significantly refactored which should make this less of a problem in the future so we could revisit when it is done.

**Comment by rachel-fenichel** [comment]
> Instead of modifying the entire blocklyDraggable class’s cursor, only change the cursor on the block’s the user is interacting with. In code: Replace calls of Blockly.Css.setCursor(cursor type) with calls to a function defined on block

Changing CSS for only one block also means that if you exceed the block's boundaries while dragging (with a fast drag, e.g.) the cursor changes.  This can produce flickering.

**Comment by rachel-fenichel** [comment]
Is loading the .cur file slow every time, or only the first?

**Comment by picklesrus** [comment]
R: changing css for only 1 block: Yes! that is true.  I should have also mentioned that to minimize the flickering if you mouse gets out ahead, I put the closed hand style on the entire block drag surface div.  It isn't perfect because you still could mouse down on the very edge of the drag surface too, but it does mitigate the problem some.

RE slow cursor loading: The .cur file seems to cost about ~2ms when cached.  Caveat: my numbers aren't particularly scientific and sometimes depend on what else my computer is doing... On the currently live playground the delete cursor seems to fetch (according to the network tab) over and over.  When it is cached, it is ~2ms which is 12% of our frame budget.  On my new version it only shows up on the network tab the first time we show the delete cursor. I don't have a good sense of why that behavior changed though, but at least it is better?

**Comment by picklesrus** [comment]
Fixed in Develop!

**Comment by ewpatton** [comment]
FYI we had addressed at App Inventor by embedding base64 versions of the icons in the JavaScript and then using those to set the cursor icon to prevent the additional round trips on every drag operation and that seemed to go pretty well.
