### ISSUE TITLE
Publish developer tutorial

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#984]
"There used to be a tutorial on the developer's site that walked through the process of creating a simple tic-tac-toe game.  But it appears to have been lost in recent updates.  Here's the slide deck that this tutorial was based on:
https://docs.google.com/presentation/d/1Aovpbe0QHM_gFLSj--e7ovgOldanOQO2mWGBh3Ga-dE/edit#

It would probably be good to get this tutorial back online."

**Comment by AnmAtAnm** [comment]
Is the [Code Lab](https://codelabs.developers.google.com/codelabs/blockly-web/index.html) a sufficient replacement? We probably need to link to it from the getting started page.

**Comment by NeilFraser** [comment]
Why does that code lab require one to install a web server?

Is it just my browser, or does every element in that lab other that the next/prev buttons have a tooltip  that says, "Learning to use Blockly on the Web".

**Comment by AnmAtAnm** [comment]
Interesting... The entire page has that tooltip, but the next and previous buttons have "Next Step" and "Previous Step" in my browser.

Agreed, the server step is overkill for most developers. It looks like it makes it possible for web development on a Chromebook. That should be called out as an optional step.

**Comment by alschmiedt** [comment]
@rachel-fenichel can we close in favor of our current codelab issues on Blockly Samples?
