### ISSUE TITLE
'Redeclaration of const property' in IE10

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#987]
Uncompressed blockly does not work on IE10

The culprit is this line: https://github.com/google/blockly/blob/master/blockly_uncompressed.js#L8
which is added by build.py: https://github.com/google/blockly/blob/master/build.py#L87

IE 10 objects to the mere possibility of redeclaring "window", probably due to variable hoisting.  IE11 and Edge don't care.

This appears to have been broken for two years without anyone noticing.

Current advice for developers working directly with IE10 in uncompressed mode is to remove lines 86-89 of build.py and rebuild.

**Comment by rachel-fenichel** [comment]
@timdawborn @ctrowat

**Comment by timdawborn** [comment]
Goodo. I would have reported it a while ago, I just assumed you weren't supporting IE10 :)

**Comment by rachel-fenichel** [comment]
We support IE10, it's just that we thought that if stuff worked on IE11 it probably mostly worked on IE10.  We were wrong.

Go ahead and report IE10 bugs as issues.  I can't guarantee we'll fix every one of them, but at least we'll be aware of them. @picklesrus and I are trying to squash the worst of the current ones for our next release.

**Comment by ctrowat** [comment]
Sorry to chime in so late.  We always run with the compressed version of blockly so we never ran into this and just this year we have desupported IE10 so we are only supporting FF/Chrome/IE11/Edge.

I'm impressed you're still humouring IE10 bugs - try to stay sane!

**Comment by rachel-fenichel** [comment]
"solved" by deprecating IE10.
