### ISSUE TITLE
Zoom-center is wrong with an always-open flyout

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#989]
In the multi-playground, with the same block dragged into each playground and then one click on the "zoom to center" button:

![image](https://cloud.githubusercontent.com/assets/13686399/24220758/d18e49c4-0f08-11e7-8383-a0e23451d24c.png)

![image](https://cloud.githubusercontent.com/assets/13686399/24220738/b9cc3530-0f08-11e7-9f76-6eee7d4745b0.png)

**Comment by rachel-fenichel** [comment]
With categories there is no problem:

![image](https://cloud.githubusercontent.com/assets/13686399/24220811/0e3d104e-0f09-11e7-8741-f28090b286a7.png)

![image](https://cloud.githubusercontent.com/assets/13686399/24220821/1d5c4752-0f09-11e7-99db-51574e4a2a3f.png)

**Comment by rachel-fenichel** [comment]
This exists on master right now.

**Comment by alschmiedt** [comment]
Closing as I can no longer repro. From what I can tell it was probably fixed in #2247.
