### ISSUE TITLE
problem work with webview of javafx

### ISSUE THREAD

**Issue by luokailiang** [google/blockly#99]
there is a problem when put the  webpage into a webview of javafx
![qq 20150513132245](https://cloud.githubusercontent.com/assets/6735061/7604396/a5c38a26-f974-11e4-8598-187b7106df22.png)

**Comment by NeilFraser** [comment]
Thanks for the bug report.  This is the second report of JavaFX getting filters wrong.  I've added a check for JavaFX and disabled the bubble's filter for this case.  See if the problem is fixed now.

**Comment by luokailiang** [comment]
Thank you very much, the problem is already fixed
