### ISSUE TITLE
Inlining inputs on a in block in RTL leaves a tail

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#993]
![blocktail](https://cloud.githubusercontent.com/assets/15675877/24260520/598b461c-0fb1-11e7-9357-0f99ca0e0aaa.png)

To reproduce:
1. Open playground in RTL
2. add block with multiple inputs (e.g. create text with)
3. right click and select "inline inputs"
4. Notice the extra line in the screenshot.

**Comment by AnmAtAnm** [comment]
Seems specific to `text_join ` block.  Perhaps related to the mutator button?

![screen shot 2018-04-30 at 2 47 53 pm](https://user-images.githubusercontent.com/9916202/39452055-b5c320e6-4c85-11e8-9a28-e98221c2829c.png)

**Comment by gonfunko** [comment]
This no longer repros, closing accordingly.
