### ISSUE TITLE
Multitouch: A long press can interrupt dragging

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#994]
To reproduce (on a mobile device)
1. start dragging a block around
2. while you're dragging place another finger on the workspace and leave it there
3. notice the context menu pops up and interrupts the drag. 

We should figure out a way to cancel the long press if there is another action in progress.

**Comment by picklesrus** [comment]
Likely fixed by https://github.com/google/blockly/pull/1078, but still needs verification.

**Comment by gonfunko** [comment]
Confirmed this no longer repros.
