### ISSUE TITLE
RTL mutators are broken on IE11 and Edge

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#998]
![image](https://cloud.githubusercontent.com/assets/13686399/24267415/6f6b35ee-0fc7-11e7-8a8a-fc0f95c9ef82.png)

Present on IE11 and Edge, but not on Chrome.

**Comment by rachel-fenichel** [comment]
@picklesrus @NeilFraser I wonder if this is related to our current RTL mutator problems.

**Comment by rachel-fenichel** [comment]
RTL mutators quite broken in IE11 for Q3 2019 release:
![image](https://user-images.githubusercontent.com/13686399/66773557-7fdc2500-ee7c-11e9-8adf-dbfce8364d4d.png)

`Object doesn't support property or method 'decompose'`

**Comment by RoboErikG** [comment]
That screenshot with not supporting 'decompose' is the test block's problem. It doesn't define a decompose function and that error is given regardless of orientation.

**Comment by rachel-fenichel** [comment]
An excellent point.  I just checked with the if/else block and this issue is fixed.
