### ISSUE TITLE
Unittest warns about prior definition of blocks

### ISSUE THREAD

**Issue by picklesrus** [google/blockly#999]
Open up index.html in tests/jsunit directory and open console.
Notice some of the tests print warnings

For example:
Running test: test_use_mutator_mixin_as_extension_fails
blockly.js:414 Block definition #0 in JSON array overwrites prior definition of "mutator_test_block".
Blockly.defineBlocksWithJsonArray @ blockly.js:414

**Comment by moniika** [comment]
Outdated. Closing in favor of #4194
